/**
 * P0.5C.6 — Generic Studio World Visual Authority constants.
 */

export const VISUAL_AUTHORITY_SYSTEM_VERSION = 'VISUAL_AUTHORITY@P0.5C.6' as const;

export const ARTISTICALLY_RICH_COGNITIVELY_SIMPLE = 'ARTISTICALLY_RICH_COGNITIVELY_SIMPLE' as const;

export const NDX_FIRST_SLIDE_DESIGN_AUTHORITY_CHAIN = [
  'CONTENT_THESIS',
  'VISUAL_SUBJECT_ARTISTIC_PREMISE',
  'BESPOKE_COMPOSITION',
  'ART_BOARD_PHYSICAL_CONSTRUCTION',
  'EDITORIAL_HIERARCHY',
  'TYPOGRAPHIC_GOVERNANCE',
  'EVIDENCE_PLACEMENT',
  'CHARACTER_TRACE',
  'SIGNATURE_LIME_INTERRUPTION',
  'FINAL_QA',
] as const;

export const VISUAL_PRIORITY_HIERARCHY = [
  'ART_CULTURAL_SUBJECT_VISUAL_HOOK',
  'THE_THOUGHT',
  'THE_PROOF',
  'THE_TRACE',
  'METADATA',
] as const;

export const TEXT_REMOVAL_RESULTS = [
  'STRONG',
  'VIABLE',
  'TEXT_DEPENDENT_BUT_JUSTIFIED',
  'TOO_TEXT_DEPENDENT',
  'ARTISTICALLY_EMPTY',
] as const;

export const EVIDENCE_COMPOSITION_ROLES = [
  'INTEGRATED',
  'SUPPORTING',
  'SECONDARY_DISCOVERY',
  'SEQUENCE_DEFERRED',
  'DOMINANT_JUSTIFIED',
  'DOMINANT_UNJUSTIFIED',
] as const;

export const FEED_ARTISTIC_BEHAVIORS = [
  'IMAGE_DOMINANT',
  'IMAGE_PLUS_TYPOGRAPHY',
  'IMAGE_PLUS_EVIDENCE',
  'ARTIFACT_DOMINANT',
  'TYPOGRAPHY_DOMINANT',
  'DATA_DOMINANT',
  'MIXED_MEDIA',
  'ILLUSTRATION_DOMINANT',
] as const;

export const VISUAL_AUTHORITY_FAILURE_STATES = [
  'FAIL_NO_PRE_READING_VISUAL_APPETITE',
  'FAIL_TEXT_AS_DEFAULT_VISUAL_INTEREST',
  'FAIL_EVIDENCE_BECAME_DEFAULT_COMPOSITION',
  'FAIL_MATERIALITY_AS_ART_DIRECTION_SUBSTITUTE',
  'FAIL_REUSABLE_TEMPLATE_COMPOSITION',
  'FAIL_ARTISTIC_RANGE_COLLAPSE',
  'FAIL_NINE_VARIATIONS_OF_ONE_LAYOUT',
  'FAIL_DOCUMENT_FEED_CONVERGENCE',
  'FAIL_TYPOGRAPHY_FEED_CONVERGENCE',
  'FAIL_MATERIALITY_FEED_CONVERGENCE',
  'FAIL_RANDOM_CELEBRITY_IMAGE',
  'FAIL_REFERENCE_STUFFING',
  'FAIL_DECORATIVE_CULTURAL_IMAGE',
] as const;

export const VISUAL_APPETITE_AUTHORITY_IMPLEMENTED = true as const;
export const BESPOKE_ART_DIRECTION_DOMINANCE_IMPLEMENTED = true as const;
export const ARTISTICALLY_RICH_COGNITIVELY_SIMPLE_IMPLEMENTED = true as const;
export const V2_1_VISUAL_DISCOVERY_INHERITED = true as const;
export const V2_3_EDITORIAL_LOGIC_PRESERVED = true as const;
export const INFORMATION_ARCHITECTURE_SUBORDINATE_TO_ART_DIRECTION = true as const;
export const EVIDENCE_DEFAULT_COMPOSITION_BLOCKED = true as const;
export const MATERIALITY_ART_DIRECTION_SUBSTITUTION_BLOCKED = true as const;
export const TEXT_DEFAULT_VISUAL_INTEREST_BLOCKED = true as const;
export const TOPIC_SPECIFIC_ART_DIRECTION_IMPLEMENTED = true as const;
export const REUSABLE_TEMPLATE_COMPOSITION_BLOCKED = true as const;
export const FEED_ARTISTIC_RANGE_IMPLEMENTED = true as const;
export const STUDIO_WORLD_VISUAL_AUTHORITY_SYSTEM_IMPLEMENTED = true as const;
export const V2_4_CREATED = false as const;
