/**
 * P0.5C.4B — Generic Studio World signature brand trace (brand-agnostic).
 */

export const SIGNATURE_TRACE_PRESENCE_RESULTS = [
  'ABSENT',
  'TOO_SUBTLE_TO_REGISTER',
  'PRESENT_RESTRAINED',
  'PRESENT_MODERATE',
  'DOMINANT_WITH_REASON',
  'OVERPOWERING',
] as const;

export const SIGNATURE_TRACE_DOMINANCE_RESULTS = [
  'RESTRAINED',
  'MODERATE',
  'DOMINANT',
  'OVERPOWERING',
] as const;

export const SIGNATURE_TRACE_COLOR_OWNERSHIP = [
  'SOURCE_COLOR',
  'BRAND_SIGNATURE_COLOR',
  'SEMANTIC_EXCEPTION',
  'ACCIDENTAL_GENERATED_COLOR',
] as const;

export const SIGNATURE_TRACE_REVISION_CLASSES = [
  'PASS_AS_IS',
  'MICRO_LIME_REVISION',
  'SEMANTIC_LIME_REVISION',
  'MAKER_MARK_REVISION',
  'FULL_REVISION_REQUIRED',
] as const;

export const SIGNATURE_TRACE_FAILURE_STATES = [
  'FAIL_SIGNATURE_TRACE_ABSENT',
  'FAIL_SIGNATURE_TRACE_INVISIBLE',
  'FAIL_DECORATIVE_ONLY',
  'FAIL_TRACE_OVERPOWERING',
  'FAIL_TEMPLATE_REPETITION',
  'FAIL_RANDOM_ACCENT_COLOR',
  'FAIL_BRAND_MARK_WRONG_COLOR',
  'FAIL_ACCENT_WITHOUT_SEMANTIC_REASON',
  'FAIL_SIGNATURE_TRACE_OUTSIDE_READING_PATH',
] as const;

export const SIGNATURE_BRAND_TRACE_GENERALIZED = true as const;
