/**
 * P0.PAF.2 — Failure taxonomy for product asset delivery pipeline.
 */

export const P0_PAF_2_FAILURE_CODES = [
  'FAIL_FS_STORAGE_NAMESPACE_MISSING',
  'FAIL_FAL_URL_USED_AS_CANONICAL_ASSET',
  'FAIL_PRODUCT_ASSET_NOT_PERSISTED',
  'FAIL_ACTIVE_BINDING_AMBIGUOUS',
  'FAIL_UNAPPROVED_ASSET_BOUND_LIVE',
  'FAIL_VARIANT_KEY_RESOLUTION',
  'FAIL_BUILD_A_WIG_WRONG_ASSET',
  'FAIL_PDP_WRONG_ASSET',
  'FAIL_VISUAL_VARIANT_MUTATES_COMMERCE_VARIANT',
  'FAIL_SERVICE_ROLE_EXPOSED_CLIENTSIDE',
  'FAIL_ACTIVE_ASSET_DELETED',
  'FAIL_CROSS_REPO_CONTRACT_MISMATCH',
] as const;

export type P0Paf2FailureCode = (typeof P0_PAF_2_FAILURE_CODES)[number];

export const P0_PAF_2_LINEAGE = 'P0.PAF.2' as const;

export const FS_SHARED_SUPABASE_PROJECT_ID = 'hyycomvcaqxxvyrfupes';
