/**
 * P0.5C.2 — Cultural Image Participation + Visual Subject Matter Governance
 */

export const CULTURAL_VISUAL_PARTICIPATION_V1 = 'CULTURAL_VISUAL_PARTICIPATION_V1' as const;
export const EXPERIMENT_01_V21_VERSION = 'EXPERIMENT_01_V2_1_CULTURAL_IMAGE_PARTICIPATION' as const;

export const CULTURAL_VISUAL_EVIDENCE_CLASSES = [
  'HUMAN_PORTRAIT',
  'EDITORIAL_PHOTOGRAPHY',
  'DOCUMENTARY_PHOTOGRAPHY',
  'ARCHIVAL_PHOTOGRAPHY',
  'HISTORICAL_IMAGE',
  'FASHION_IMAGE',
  'LIFESTYLE_IMAGE',
  'STREET_PHOTOGRAPHY',
  'INTERIOR',
  'OBJECT',
  'PRODUCT',
  'PACKAGING',
  'ADVERTISEMENT',
  'MAGAZINE_FRAGMENT',
  'NEWSPAPER_FRAGMENT',
  'CULTURAL_EPHEMERA',
  'FILM_LANGUAGE_REFERENCE',
  'SYMBOLIC_IMAGE',
  'ORIGINAL_ILLUSTRATION',
  'ORIGINAL_ARTWORK',
  'COLLAGE_FRAGMENT',
  'MAP',
  'DIAGRAM',
  'VISUAL_METAPHOR',
  'PHYSICAL_ARTIFACT',
  'FOUND_OBJECT',
  'UI_FRAGMENT',
  'SCREEN_CAPTURE',
  'DATA_VISUAL',
  'TYPOGRAPHIC_OBJECT',
] as const;

export const CULTURAL_VISUAL_ROLES = [
  'HERO',
  'SUBJECT',
  'CONTEXT',
  'EVIDENCE',
  'CONTRAST',
  'CALLBACK',
  'MEMORY',
  'EMOTIONAL_ENTRY',
  'HUMOR',
  'SYMBOL',
  'PATTERN',
  'REFERENCE',
  'COUNTERPOINT',
  'ATMOSPHERE',
  'HUMANIZE',
  'REVEAL',
] as const;

export const VISUAL_PARTICIPATION_MODES = [
  'IMAGE_DOMINANT',
  'IMAGE_PLUS_TYPOGRAPHY',
  'IMAGE_PLUS_EVIDENCE',
  'ARTIFACT_DOMINANT',
  'TYPOGRAPHY_DOMINANT',
  'DATA_DOMINANT',
  'MIXED_MEDIA',
  'ILLUSTRATION_DOMINANT',
  'PHOTOGRAPHIC_ASSEMBLAGE',
] as const;

export const IMAGE_PARTICIPATION_REQUIREMENTS = [
  'REQUIRED',
  'STRONGLY_RECOMMENDED',
  'OPTIONAL',
  'NOT_HELPFUL',
  'WOULD_DISTRACT',
] as const;

export const VISUAL_PARTICIPATION_BALANCE = [
  'IMAGE_HEAVY',
  'IMAGE_LED',
  'BALANCED',
  'TYPE_LED',
  'EVIDENCE_LED',
  'DATA_LED',
  'SPARSE',
] as const;

export const VISUAL_EVIDENCE_CLASSIFICATIONS = [
  'FACTUAL_SOURCE_EVIDENCE',
  'CULTURAL_SOURCE_EVIDENCE',
  'ARTISTIC_INTERPRETATION',
  'GENERATED_ILLUSTRATION',
  'SYMBOLIC_EXPRESSION',
  'HUMAN_TRACE',
  'DECORATIVE_MATERIAL',
] as const;

export const VISUAL_APPETITE_RESULTS = ['STRONG', 'SUFFICIENT', 'WEAK', 'NONE', 'NOT_APPLICABLE'] as const;

export const PHOTOGRAPHY_BEHAVIORS = [
  'DOCUMENT',
  'OBSERVE',
  'GLAMORIZE',
  'REASSESS',
  'COMPARE',
  'MEMORIALIZE',
  'HUMANIZE',
  'CONTRAST',
  'ARCHIVE',
  'INTERRUPT',
  'ISOLATE',
  'ZOOM_IN',
  'PULL_BACK',
] as const;

export const FEED_CULTURAL_RHYTHM_TYPES = [
  'HUMAN',
  'OBJECT',
  'ARCHIVAL',
  'PHOTOGRAPHIC',
  'TYPOGRAPHIC',
  'DATA',
  'DOCUMENTARY',
  'ILLUSTRATIVE',
  'MIXED_MEDIA',
] as const;

export const FEED_EMOTIONAL_TEMPERATURES = [
  'FUNNY',
  'NOSY',
  'CURIOUS',
  'SUSPICIOUS',
  'BEAUTIFUL',
  'NOSTALGIC',
  'PLAYFUL',
  'SERIOUS',
  'REFLECTIVE',
  'OBSESSIVE',
  'SURPRISED',
  'CONVICTED',
] as const;

export const CULTURAL_FAILURE_STATES = [
  'FAIL_RANDOM_CELEBRITY_IMAGE',
  'FAIL_RANDOM_NOSTALGIA',
  'FAIL_REFERENCE_STUFFING',
  'FAIL_DECORATIVE_CULTURAL_IMAGE',
  'FAIL_TEXT_DOMINANT_FEED',
  'FAIL_DOCUMENT_DOMINANT_FEED',
  'FAIL_NO_HUMAN_PRESENCE',
  'FAIL_NO_CULTURAL_IMAGE',
  'FAIL_NO_ARTISTIC_RANGE',
  'FAIL_VISUALLY_MONOTONOUS',
  'FAIL_FAKE_FACTUAL_EVIDENCE',
  'FAIL_GENERATED_AS_FACTUAL',
  'FAIL_IMAGE_UNRELATED_TO_THESIS',
  'FAIL_FORCED_DIVERSITY_IMAGERY',
] as const;

export const V21_FOUNDER_JUDGMENTS = [
  'YES_FEELS_ALIVE',
  'LOVE_IMAGE_PARTICIPATION',
  'NEEDS_MORE_CULTURE',
  'NEEDS_MORE_HUMANITY',
  'NEEDS_MORE_ART',
  'NEEDS_MORE_PLAY',
  'TOO_TEXT_HEAVY',
  'TOO_DOCUMENT_HEAVY',
  'TOO_SERIOUS',
  'TOO_RESEARCH_Y',
  'TOO_MANY_PHOTOS',
  'IMAGE_IS_DECORATIVE',
  'IMAGE_DOESNT_BELONG',
  'WRONG_CULTURAL_REFERENCE',
  'TOO_NOSTALGIC',
  'TOO_TRENDY',
  'NEEDS_MORE_EVIDENCE',
  'RIGHT_CONTENT_WRONG_VISUAL_SUBJECT',
  'CHARACTER_RIGHT_VISUAL_ENTRY_WRONG',
  'THATS_NDX',
  'NO_IMAGE_NEEDED',
  'NEEDS_MORE_CULTURE',
  'TOO_CULTURE_HEAVY',
  'WRONG_IMAGE_LOGIC',
] as const;

export const FAL_CULTURAL_PROMPT_SECTION_ORDER = [
  'WHAT_HAPPENED',
  'WHAT_NDX_NOTICED',
  'SINGLE_PRIMARY_EDITORIAL_IDEA',
  'VIEWER_MUST_NOTICE_FIRST',
  'CULTURAL_HUMAN_ARTISTIC_SUBJECT',
  'WHY_VISUAL_SUBJECT_BELONGS',
  'IMAGE_PARTICIPATION_MODE',
  'FIRST_SLIDE_SEMANTIC_ROLE',
  'INFORMATION_HIERARCHY',
  'PRIMARY_EVIDENCE',
  'DEFERRED_EVIDENCE',
  'NDX_TRACE',
  'TYPOGRAPHIC_ROLE_ASSIGNMENTS',
  'UPPERCASE_GOVERNANCE',
  'IMAGE_TYPE_BALANCE',
  'READING_PATH',
  'DENSITY_TARGET',
  'PLAYFULNESS_EMOTIONAL_TARGET',
  'MATERIAL_CONDITIONS',
  'COMPOSITIONAL_CONDITIONS',
  'LIME_FUNCTION',
  'PHOTOGRAPHIC_ILLUSTRATIVE',
  'CULTURAL_REFERENCE_DISCIPLINE',
  'NEGATIVE_CONSTRAINTS',
] as const;

export const CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED = true as const;
export const VISUAL_SUBJECT_MATTER_GOVERNANCE_IMPLEMENTED = true as const;
export const CULTURAL_VISUAL_EVIDENCE_IMPLEMENTED = true as const;
export const ARTISTIC_EVIDENCE_IMPLEMENTED = true as const;
export const IMAGE_PARTICIPATION_DECISION_IMPLEMENTED = true as const;
export const CULTURAL_ACCOMPLICE_VISUAL_EVALUATION_IMPLEMENTED = true as const;
export const VISUAL_APPETITE_EVALUATION_IMPLEMENTED = true as const;
export const PLAYFULNESS_EVALUATION_IMPLEMENTED = true as const;
export const FEED_CULTURAL_RHYTHM_IMPLEMENTED = true as const;
export const FEED_EMOTIONAL_RHYTHM_IMPLEMENTED = true as const;
export const TEXT_DOMINANT_FEED_GUARD_IMPLEMENTED = true as const;
export const DOCUMENT_DOMINANT_FEED_GUARD_IMPLEMENTED = true as const;
export const RANDOM_CULTURAL_REFERENCE_GUARD_IMPLEMENTED = true as const;
export const GENERATED_IMAGE_EVIDENCE_BOUNDARY_IMPLEMENTED = true as const;
export const P0_5C_1_EDITORIAL_HIERARCHY_PRESERVED = true as const;
export const EXPERIMENT_01_CULTURAL_VISUAL_PIPELINE_READY = true as const;
export const CONTENT_OPERATIONS_VISUAL_SUBJECT_MATTER_INTEGRATED = true as const;
