/**
 * P0.5D.1 — NDXBOOK Live Cultural Intelligence adapter.
 */

export const NDXBOOK_LIVE_CULTURAL_INTELLIGENCE_RUN_ID = 'ndxbook-live-cultural-intelligence' as const;

export const NDX_RELEVANCE_FILTER_IMPLEMENTED = true as const;
export const NDX_TREND_DEPENDENCY_GUARD_IMPLEMENTED = true as const;
export const NDX_CULTURAL_MEMORY_IMPLEMENTED = true as const;
export const LIVE_SIGNAL_INGESTION_MANUAL_CONNECTED = true as const;
export const LIVE_SIGNAL_INGESTION_PARTIALLY_LIVE = true as const;

export const NDX_LIVE_CULTURAL_INTELLIGENCE_PROVING_RUN_01 = 'NDX_LIVE_CULTURAL_INTELLIGENCE_PROVING_RUN_01' as const;
export const NDX_WEEKLY_CULTURAL_FORECAST_LIVE_01 = 'NDX_WEEKLY_CULTURAL_FORECAST_LIVE_01' as const;

export const CURRENT_WEB_DISCOVERY_CONNECTED = true as const;
export const KNOWN_EVENT_SOURCE_CONNECTED = true as const;
export const SEARCH_ATTENTION_SOURCE_CONNECTED = false as const;
export const COMMUNITY_SOCIAL_SOURCE_CONNECTED = false as const;

export const NDX_CHARACTER_BEHAVIOR_MODES = [
  'QUICK_CATCH',
  'SIDE_EYE',
  'RECEIPT_PULL',
  'RABBIT_HOLE',
  'PATTERN_NOTICE',
  'CULTURAL_CALLBACK',
  'DATA_CHECK',
  'CONTRADICTION',
  'SELF_CORRECTION',
  'WAIT_AND_WATCH',
  'QUIET_INVESTIGATION',
  'EXPLAIN_THE_SYSTEM',
  'THIS_AGED_INTERESTINGLY',
  'EVERYBODY_FORGOT_THIS',
  'OKAY_BUT',
  'BE_SERIOUS',
  'I_HAVE_A_THEORY',
] as const;

export const NDX_TREND_DEPENDENCY_RESULTS = [
  'NATURAL_NDX_INTEREST',
  'TREND_ACTIVATED_EXISTING_INTEREST',
  'TREND_CREATED_USEFUL_CONNECTION',
  'TREND_ONLY_INTEREST',
  'FORCED_RELEVANCE',
] as const;

export const NDX_FOUNDER_INTELLIGENCE_JUDGMENTS = [
  'YES_NDX_WOULD_NOTICE_THIS',
  'INVESTIGATE',
  'WATCH',
  'SAVE_FOR_LATER',
  'CALLBACK_POTENTIAL',
  'NEEDS_MORE_EVIDENCE',
  'TOO_EARLY',
  'TOO_LATE',
  'TOO_SATURATED',
  'TOO_OBVIOUS',
  'EVERYONE_ALREADY_SAID_THIS',
  'FORCED_NDX_ANGLE',
  'NOT_CULTURALLY_RELEVANT',
  'NOT_INTERESTING',
  'NOT_NDX',
] as const;

export type NdxTrendDependencyResult = (typeof NDX_TREND_DEPENDENCY_RESULTS)[number];
export type NdxCharacterBehaviorMode = (typeof NDX_CHARACTER_BEHAVIOR_MODES)[number];
