import type { FigmaStyleInterfaceTranslationPackage } from '../../../shared/site00-design-bench/grokTwinTestA/types.js';
import type { GrokVisionTranslateInput } from './grokVisionProvider.js';

/** Vitest-only contract fixture. Never served as a founder golden reference. */
export function buildGrokTestHarnessPackage(input: GrokVisionTranslateInput): FigmaStyleInterfaceTranslationPackage {
  const w = input.width || 390;
  const h = input.height || 844;
  const n = (x: number, y: number, width: number, height: number) => ({
    x: x / w,
    y: y / h,
    width: width / w,
    height: height / h,
  });

  return {
    visualInterfacePreview: {
      kind: 'FIGMA_STYLE_ARTBOARD',
      frameWidth: w,
      frameHeight: h,
      background: '#111111',
      layers: [
        { id: 'canvas', type: 'rect', name: 'Page', x: 0, y: 0, width: w, height: h, fill: '#111111', zIndex: 0 },
        { id: 'chrome', type: 'rect', name: 'Top chrome', x: 0, y: 0, width: w, height: Math.round(h * 0.08), fill: '#1a1a1a', zIndex: 1 },
        {
          id: 'title',
          type: 'text',
          name: 'Headline',
          x: 16,
          y: Math.round(h * 0.1),
          width: w - 32,
          height: 40,
          text: 'TEST HARNESS ARTBOARD',
          textColor: '#f5f5f4',
          fontFamily: 'Martian Mono',
          fontSize: 18,
          fontWeight: 700,
          textTransform: 'uppercase',
          zIndex: 2,
        },
        {
          id: 'hero',
          type: 'rect',
          name: 'Hero surface',
          x: 16,
          y: Math.round(h * 0.18),
          width: w - 32,
          height: Math.round(h * 0.28),
          fill: '#2a2a2a',
          radius: 4,
          zIndex: 1,
        },
      ],
      notes: 'Vitest harness artboard only. Production Grok must translate the uploaded golden image.',
    },
    pageFrameSpec: {
      sourceViewportWidth: w,
      sourceViewportHeight: h,
      designFrameWidth: w,
      designFrameHeight: h,
      pageBackground: '#111111',
      contentBounds: { x: 16, y: 16, width: w - 32, height: h - 32 },
      outerMargins: { top: 16, right: 16, bottom: 16, left: 16 },
      columnGrid: { columns: 4, gutter: 8, margin: 16 },
      gutters: 8,
      majorSectionPositions: [
        { id: 'chrome', name: 'Chrome', x: 0, y: 0, width: w, height: Math.round(h * 0.08) },
        { id: 'hero', name: 'Hero', x: 16, y: Math.round(h * 0.18), width: w - 32, height: Math.round(h * 0.28) },
      ],
    },
    sectionTree: {
      id: 'page',
      name: 'PAGE',
      kind: 'PAGE',
      children: [
        {
          id: 'sec-chrome',
          name: 'Chrome',
          kind: 'SECTION',
          children: [{ id: 'cmp-title', name: 'Headline', kind: 'COMPONENT', children: [] }],
        },
        { id: 'sec-hero', name: 'Hero', kind: 'SECTION', children: [] },
      ],
    },
    componentTree: [
      {
        componentId: 'cmp-title',
        name: 'Headline',
        parentId: 'sec-chrome',
        role: 'headline',
        siblingOrder: 0,
        x: 16,
        y: Math.round(h * 0.1),
        width: w - 32,
        height: 40,
        normalizedGeometry: n(16, Math.round(h * 0.1), w - 32, 40),
        layoutBehavior: 'block',
        alignment: 'left',
        visualPriority: 'PRIMARY',
      },
      {
        componentId: 'cmp-hero',
        name: 'Hero surface',
        parentId: 'sec-hero',
        role: 'surface',
        siblingOrder: 0,
        x: 16,
        y: Math.round(h * 0.18),
        width: w - 32,
        height: Math.round(h * 0.28),
        normalizedGeometry: n(16, Math.round(h * 0.18), w - 32, Math.round(h * 0.28)),
        layoutBehavior: 'block',
        alignment: 'stretch',
        visualPriority: 'SECONDARY',
      },
    ],
    layoutGeometrySpec: {
      sectionDimensions: [
        { id: 'chrome', width: w, height: Math.round(h * 0.08), relativeWidth: 1, relativeHeight: 0.08 },
        { id: 'hero', width: w - 32, height: Math.round(h * 0.28), relativeWidth: (w - 32) / w, relativeHeight: 0.28 },
      ],
      rowColumnRelationships: ['chrome above hero'],
      gaps: { section: 16 },
      padding: { page: 16 },
      alignmentAnchors: ['left-16'],
      nesting: ['PAGE > SECTION > COMPONENT'],
      repeatedDimensions: ['horizontal inset 16'],
      overlaps: [],
      positioningBehavior: 'absolute artboard',
    },
    typographySystem: {
      hierarchy: [
        {
          id: 't-headline',
          role: 'headline',
          fontCategory: 'monospace',
          size: 18,
          weight: 700,
          lineHeight: 1.2,
          tracking: '0',
          casing: 'uppercase',
          alignment: 'left',
          lineCount: 1,
          wrapBehavior: 'truncate',
        },
      ],
      notes: 'Harness typography. Live Grok must sample the reference.',
    },
    colorSystem: {
      pageBackground: '#111111',
      surfaceColors: ['#1a1a1a', '#2a2a2a'],
      primaryText: '#f5f5f4',
      secondaryText: '#c4c4c4',
      mutedText: '#6b6b6b',
      accents: ['#e8192c'],
      statusColors: [],
      bordersDividers: ['#2a2a2a'],
      sampled: false,
    },
    spacingSystem: {
      outerMargin: 16,
      sectionGap: 16,
      panelPadding: 12,
      componentGaps: 8,
      inlineGaps: 6,
      metadataSpacing: 4,
      denseRegions: ['chrome'],
      openRegions: ['hero'],
    },
    borderRadiusSurfaceSystem: {
      borderWidths: [0, 1],
      borderColors: ['#2a2a2a'],
      radii: [0, 4],
      surfaceHierarchy: ['page', 'chrome', 'hero'],
      fills: ['#111111', '#1a1a1a', '#2a2a2a'],
      shadows: [],
      separators: ['chrome bottom edge'],
      selectedActiveSurfaces: [],
    },
    assetPlacementMap: [],
    controlStateSystem: [],
    visualHierarchyMap: {
      firstVisualFocus: 'Headline',
      secondVisualFocus: 'Hero surface',
      tertiaryInformation: 'Chrome metadata',
      dominantRegions: ['hero'],
      subordinateRegions: ['chrome'],
      highContrastAnchors: ['headline on dark'],
      visualWeightRelationships: ['headline heavier than chrome'],
    },
    implementationHandoff: {
      title: 'GrokComposerImplementationHandoff',
      summary: 'Vitest harness handoff. Production Grok must write from the uploaded golden image only.',
      buildOrder: ['page frame', 'chrome', 'hero', 'type'],
      componentImplementationNotes: ['Do not treat this harness as visual authority.'],
      layoutNotes: ['Preserve uploaded width × height.'],
      typographyNotes: ['Sample from reference in live runs.'],
      colorNotes: ['Sample from reference in live runs.'],
      assetNotes: ['None in harness.'],
      stateNotes: ['None visible in harness.'],
      doNotReinterpret: ['Do not invent product sections.'],
      acceptanceChecks: ['Package keys present', 'Artboard layers exist'],
    },
    doNotChangeRules: {
      rules: ['Do not use this harness output as founder visual authority.', 'Preserve uploaded aspect.'],
    },
  };
}
