export const P0_VR_TWIN_V27_BUILD = 'v382' as const;

export const EXECUTION_INTENT_TRANSLATION = 'TRANSLATION' as const;
export const INVENTION_BUDGET_NONE = 'NONE' as const;

export const BLUEPRINT_RELATIONSHIP_TYPES = [
  'ALIGNED_LEFT',
  'ALIGNED_RIGHT',
  'ALIGNED_TOP',
  'ALIGNED_BOTTOM',
  'SHARES_BASELINE',
  'GAP_TO',
  'ANCHORED_TO',
  'CONTAINED_BY',
  'OVERLAPS',
  'SHARES_EDGE',
  'SAME_WIDTH',
  'SAME_HEIGHT',
  'CENTERED_ON',
  'PROPORTIONAL_TO',
] as const;

export const ASSET_TYPES_V27 = [
  'EXISTING_PROJECT_ASSET',
  'GENERATED_TRANSPARENT_ASSET',
  'GENERATED_RASTER_ASSET',
  'GENERATED_COMPLEX_MEDIA',
  'SVG_SYSTEM',
  'CSS_GRAPHIC',
  'DOM_ONLY',
] as const;

export const TWIN_V27_FAILURE_CODES = [
  'TWIN_V2_BLUEPRINT_POSTHOC_ONLY',
  'BLUEPRINT_TRANSLATION_GAP',
  'TWIN_V2_PARALLEL_FUNCTION_UI',
  'TWIN_V2_AUTHORITY_RUNTIME_DEPENDENCY',
  'FUNCTION_VISUAL_TARGET_MISSING',
  'TWIN_RECONCILIATION_FAILED',
  'UNBOUND_PRIMARY_OBJECT',
] as const;

export const DATA_VISUAL_STATES = ['KNOWN', 'UNKNOWN', 'LOADING', 'ERROR', 'NOT_APPLICABLE'] as const;

export const RESPONSIVE_RULES = [
  'FIXED_RELATIONSHIP',
  'REFLOW',
  'STACK',
  'EXPAND',
  'CONTRACT',
  'CROP_CHANGE',
  'HIDE',
  'SHOW',
  'REORDER',
  'RECOMPOSE',
] as const;
