/**
 * Character field completeness display states — never imply missing data is valid content.
 */

export const CHARACTER_FIELD_DISPLAY_STATES = [
  'AVAILABLE',
  'NOT_FORMED_AT_TERRITORY_STAGE',
  'MISSING_PROVIDER_OUTPUT',
  'RECOVERABLE_PROVIDER_OUTPUT',
  'DATA_PIPELINE_ERROR',
  'NOT_EVALUATED',
] as const;

export type CharacterFieldDisplayState = (typeof CHARACTER_FIELD_DISPLAY_STATES)[number];

export const BLANK_FIELD_ROOT_CAUSES = [
  'PROVIDER_MISSING',
  'PROVIDER_EMPTY',
  'PROVIDER_TRUNCATED',
  'PARSER_DROPPED',
  'SCHEMA_DROPPED',
  'NORMALIZATION_DROPPED',
  'PERSISTENCE_DROPPED',
  'API_DROPPED',
  'UI_BINDING_ERROR',
  'UI_RENDERING_ERROR',
  'INTENTIONALLY_NOT_FORMED',
  'UNKNOWN',
] as const;

export type BlankFieldRootCause = (typeof BLANK_FIELD_ROOT_CAUSES)[number];

export type CharacterFieldCompleteness = {
  fieldPath: string;
  displayState: CharacterFieldDisplayState;
  rootCause: BlankFieldRootCause;
  canonicalValue: string | null;
  recoveredValue: string | null;
  recoveryProvenance: 'RECOVERED_FROM_ORIGINAL_PROVIDER_RESPONSE' | 'RECOVERED_FROM_ALTERNATE_PROVIDER_SCHEMA' | null;
  belongsToStage: 'TERRITORY' | 'DEVELOPMENT' | 'SYSTEM';
};

export function displayStateLabel(state: CharacterFieldDisplayState): string {
  switch (state) {
    case 'NOT_FORMED_AT_TERRITORY_STAGE':
      return 'Developed after territory selection';
    case 'MISSING_PROVIDER_OUTPUT':
      return 'Not generated by provider';
    case 'RECOVERABLE_PROVIDER_OUTPUT':
      return 'Recoverable from provider response';
    case 'DATA_PIPELINE_ERROR':
      return 'Pipeline error — data lost downstream';
    case 'NOT_EVALUATED':
      return 'Not evaluated';
    default:
      return '';
  }
}
