/**
 * AIO IFTA — interaction registry (sprint §23). Sources: contract sheet §05 (items 01–11), sprint examples, experience
 * contract interaction_grammar + operational actions, and the existing AIO reducers (fsbw src/ifta/iftaActions.ts — read
 * only). Each interaction names actor, trigger, target node, data effect (+ write contract), UI effect, success, failure,
 * permission and analytics event.
 *
 * Analytics: AIO has no product analytics pipeline for IFTA; events are the contract's ACTIVITY / audit events
 * (`ifta.*` names are the proposed analytics keys, emitted through the existing activity + audit trail).
 */
import type { InteractionContract } from '../../../tree.js';

const SHEET = 'PAGE_COMPONENT_INTERACTION_CONTRACT';
const X = (x: Omit<InteractionContract, 'status'> & { status?: InteractionContract['status'] }): InteractionContract => ({ status: 'DEFINED', ...x });

const CLIENT_UNLOCKED = 'CLIENT (own organisation) while the quarter is unlocked (COLLECTION states); locked in AIO review / filing (requireUnlocked)';
const STAFF = 'FOUNDER_STAFF (office role; assigned staff or founder)';

export const AIO_IFTA_INTERACTIONS: InteractionContract[] = [
  /* ── shell / navigation ── */
  X({ interaction_id: 'I.SWITCH_TAB', label: 'Switch tab', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'tap a tab pill', target: 'TAB_BAR → tab node', data_effect: 'none (read the tab’s own contracts)', ui_effect: 'active pill moves; hero title + metrics swap to the tab; body swaps to the tab’s modules; next-action rail updates', success: 'tab content shown; deep link updated', failure: 'tab read fails → UI.ERROR in the body only (shell stays)', permission: 'viewer of the quarter', analytics_event: 'ifta.tab_viewed', write_contract: null, state_transition: null, contract_refs: ['desktop_behavior (compartments as tabs of one packet)'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY', 'FUEL_PURCHASES_CHILD_PROOF'] }),
  X({ interaction_id: 'I.SWITCH_QUARTER', label: 'Switch quarter', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'quarter selector (desktop) / quarter history entry', target: 'QUARTER_SELECTOR', data_effect: 'none (read another quarter case of the organisation)', ui_effect: 'room re-renders for the chosen quarter; archived quarters read-only', success: 'chosen quarter shown', failure: 'quarter not found → UI.ERROR', permission: 'viewer of the organisation’s quarters', analytics_event: 'ifta.quarter_switched', write_contract: null, state_transition: null, contract_refs: ['cross_feature_relationships IFTA_ARCHIVED_OPENS_NEXT'], authority_refs: ['CLIENT_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.CONTINUE_NEXT_ACTION', label: 'Continue (next-action rail)', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'tap the dark next-action rail', target: 'NEXT_ACTION_RAIL → the node of the single next item', data_effect: 'none (navigation to the next item)', ui_effect: 'navigates to the tab / drawer that resolves the next item (e.g. REVIEW MILEAGE SUMMARY)', success: 'next item in view', failure: 'no next item → rail shows the state line (no dead CTA)', permission: 'viewer', analytics_event: 'ifta.next_action', write_contract: null, state_transition: null, contract_refs: ['composition_rules: exactly one primary action per state', 'nextItemLine()'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY', SHEET] }),
  X({ interaction_id: 'I.FILTER_SORT', label: 'Filter / sort', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'filter chips / column sort on a table', target: 'RECEIPT_ROW · MILEAGE_ROW · VEHICLE_ROW · FILE_ROW tables', data_effect: 'none (client-side view state)', ui_effect: 'rows re-ordered / filtered; counts stay visible', success: 'filtered view', failure: 'no rows → UI.EMPTY with clear-filter action', permission: 'viewer', analytics_event: 'ifta.filter', write_contract: null, state_transition: null, contract_refs: [], authority_refs: [SHEET + ' #04'] }),
  X({ interaction_id: 'I.OPEN_NOTIFICATIONS', label: 'Open notifications', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'bell in the top nav', target: 'TOP_NAV → notifications (cross-feature)', data_effect: 'none', ui_effect: 'opens the AIO notifications surface filtered to Tax & Fuel', success: 'notifications shown', failure: 'UI.ERROR', permission: 'signed-in user', analytics_event: null, write_contract: null, state_transition: null, contract_refs: ['notifications'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  X({ interaction_id: 'I.SEARCH', label: 'Search', actor: 'CLIENT · FOUNDER_STAFF · PUBLIC', trigger: 'search glyph in the top nav', target: 'TOP_NAV → search (cross-feature)', data_effect: 'none', ui_effect: 'opens portal / office / site search', success: 'results', failure: 'no results', permission: 'actor scope (public: public pages only)', analytics_event: null, write_contract: null, state_transition: null, contract_refs: [], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY', 'PUBLIC_TABLET_DESKTOP'] }),

  /* ── client: fuel purchases ── */
  X({ interaction_id: 'I.UPLOAD_RECEIPT', label: 'Upload receipt', actor: 'CLIENT', trigger: 'drag & drop or CHOOSE FILES in the upload zone (PDF, JPG, PNG, max 10MB each)', target: 'AIO.IFTA.CLIENT.ROOM.FUEL_PURCHASES.UPLOAD', data_effect: 'captureReceipts(method UPLOAD_FILES) → receipts parsed + classified (READY / NEEDS_YOU / DUPLICATE / UNREADABLE); quarter → COLLECTING', ui_effect: 'rows appear with status chips; RECEIPT STATUS counts and metrics update', success: '“{n} RECEIPTS ADDED” (UI.SUCCESS) + activity ACT_RECEIPTS_ADDED', failure: '“FILE COULD NOT BE PROCESSED. PLEASE CHECK AND TRY AGAIN.” — unreadable files kept as UNREADABLE with a retake request (never dropped)', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.receipts_uploaded', write_contract: 'FUEL.write.captureReceipts', state_transition: { from: 'QUARTER_OPEN', to: 'COLLECTING' }, contract_refs: ['interaction_grammar UPLOAD', 'required_inputs FUEL_RECEIPTS'], authority_refs: [SHEET + ' #01', 'FUEL_PURCHASES_CHILD_PROOF'] }),
  X({ interaction_id: 'I.TAKE_PHOTO', label: 'Take photo', actor: 'CLIENT', trigger: 'camera action in the upload zone (mobile)', target: 'AIO.IFTA.CLIENT.ROOM.FUEL_PURCHASES.UPLOAD', data_effect: 'captureReceipts(method TAKE_PHOTO)', ui_effect: 'captured receipt row appears with its chip', success: 'receipt added', failure: 'unreadable photo → UNREADABLE + retake', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.receipt_photo', write_contract: 'FUEL.write.captureReceipts', state_transition: { from: 'QUARTER_OPEN', to: 'COLLECTING' }, contract_refs: ['interaction_grammar TAKE PHOTO', 'mobile_behavior capture-first'], authority_refs: ['FUEL_PURCHASES_CHILD_PROOF'] }),
  X({ interaction_id: 'I.IMPORT_FROM_VAULT', label: 'Import from Vault', actor: 'CLIENT', trigger: 'IMPORT FROM VAULT in the upload flow', target: 'AIO.IFTA.CLIENT.ROOM.FUEL_PURCHASES.IMPORT_VAULT', data_effect: 'captureReceipts(method IMPORT_FROM_VAULT) with vaultDocumentId per receipt', ui_effect: 'pick tax_fuel documents dated in the quarter; rows appear', success: 'receipts linked to their Vault documents', failure: 'no matching documents → UI.EMPTY', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.receipts_imported_vault', write_contract: 'FUEL.write.captureReceipts', state_transition: null, contract_refs: ['interaction_grammar IMPORT', 'system_already_knows receipts in the Vault'], authority_refs: ['FUEL_PURCHASES_CHILD_PROOF'] }),
  X({ interaction_id: 'I.IMPORT_CSV', label: 'Import CSV', actor: 'CLIENT', trigger: 'IMPORT CSV (fuel card / fuel log export)', target: 'AIO.IFTA.CLIENT.ROOM.FUEL_PURCHASES.CSV_IMPORT', data_effect: 'map columns (date · vendor · state · gallons · amount · unit) → validate → captureReceipts per row', ui_effect: 'column-mapping modal with validation summary, then rows appear', success: '“{n} PURCHASES IMPORTED”', failure: 'unmapped / invalid rows listed; nothing imported until valid', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.csv_imported', write_contract: 'FUEL.write.importCsv', state_transition: null, contract_refs: ['optional_inputs FUEL_CARD_STATEMENT', 'sprint §12 FILE IMPORT'], authority_refs: [SHEET + ' #02'] }),
  X({ interaction_id: 'I.OPEN_RECEIPT', label: 'Open receipt', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'tap a receipt row', target: 'AIO.IFTA.CLIENT.ROOM.FUEL_PURCHASES.RECEIPT_DETAIL', data_effect: 'none', ui_effect: 'detail drawer: image, parsed fields, state, vehicle, flag reason + fix inline, history', success: 'drawer open', failure: 'receipt missing → UI.ERROR', permission: 'viewer of the quarter', analytics_event: 'ifta.receipt_opened', write_contract: null, state_transition: null, contract_refs: ['output_artifacts FUEL_RECEIPT view_behavior'], authority_refs: [SHEET + ' #03'] }),
  X({ interaction_id: 'I.EDIT_RECEIPT', label: 'Edit receipt', actor: 'CLIENT', trigger: 'answer the flag / correct the receipt in the detail drawer', target: 'AIO.IFTA.CLIENT.ROOM.FUEL_PURCHASES.RECEIPT_DETAIL', data_effect: 'resolveReceipt(TRUCK_FUEL | REEFER_FUEL | RETAKE | ADD_RECEIPT | NO_FUEL_PURCHASED | REMOVE_DUPLICATE | KEEP_BOTH) — free-form field edits are not supported', ui_effect: 'chip changes to PROCESSED; counts update', success: '“RECORD VERIFIED AND SAVED.”', failure: 'quarter locked → UI.LOCKED_IN_REVIEW message', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.receipt_edited', write_contract: 'FUEL.write.resolveReceipt', state_transition: { from: 'NEEDS_CLIENT', to: 'COLLECTING' }, contract_refs: ['output_artifacts FUEL_RECEIPT editable_by CLIENT (until submitted)'], authority_refs: [SHEET + ' #03'] }),
  X({ interaction_id: 'I.RESOLVE_FLAG', label: 'Resolve flag', actor: 'CLIENT', trigger: 'answer a NEEDS YOU / DUPLICATE / POSSIBLE MISSING / UNREADABLE flag', target: 'AIO.IFTA.CLIENT.ROOM.PROGRESS.NEEDS_YOU', data_effect: 'resolveReceipt(resolution) per flag; clientOpenItems() shrinks', ui_effect: 'flag card leaves the list; NEEDS YOU count drops; when zero the state returns to COLLECTING / READY FOR AIO', success: 'flag cleared', failure: 'invalid resolution → inline error', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.flag_resolved', write_contract: 'FUEL.write.resolveReceipt', state_transition: { from: 'NEEDS_CLIENT', to: 'COLLECTING' }, contract_refs: ['interaction_grammar RESOLVE FLAG'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  X({ interaction_id: 'I.RETAKE_UNREADABLE', label: 'Retake unreadable receipt', actor: 'CLIENT', trigger: 'RETAKE on an UNREADABLE row', target: 'AIO.IFTA.CLIENT.ROOM.FUEL_PURCHASES.RECEIPT_DETAIL', data_effect: 'resolveReceipt(RETAKE, fileName) — corrected receipt supersedes; original stays in history', ui_effect: 'row returns parsed', success: 'receipt readable', failure: 'still unreadable → stays UNREADABLE', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.receipt_retaken', write_contract: 'FUEL.write.resolveReceipt', state_transition: null, contract_refs: ['AIO_IFTA_RECEIPT_CLASSES UNREADABLE'], authority_refs: ['ICON_ASSET_SHEET'] }),

  /* ── client: mileage ── */
  X({ interaction_id: 'I.CHOOSE_MILEAGE_SOURCE', label: 'Choose mileage source', actor: 'CLIENT', trigger: 'ADD MILES on a vehicle without a source', target: 'AIO.IFTA.CLIENT.ROOM.MILEAGE.SOURCE_PICKER', data_effect: 'none (opens the source choice)', ui_effect: 'sheet (mobile) / panel: ELD / GPS IMPORT (not live) · ELD REPORT UPLOAD · MANUAL STATE ENTRY · SPREADSHEET · AIO ASSISTANCE', success: 'source chosen', failure: '—', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.mileage_source_opened', write_contract: null, state_transition: null, contract_refs: ['AIO_IFTA_MILEAGE_SOURCES', 'mobile_behavior mileage source picker as a sheet'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  X({ interaction_id: 'I.IMPORT_MILEAGE_REPORT', label: 'Import mileage report / CSV', actor: 'CLIENT', trigger: 'upload an ELD state-mileage report or spreadsheet', target: 'AIO.IFTA.CLIENT.ROOM.MILEAGE.REPORT_IMPORT', data_effect: 'addMileage(sourceId ELD_REPORT_UPLOAD | SPREADSHEET, fileName) → per-state entries; newer source supersedes', ui_effect: 'vehicle row shows miles by state with a source badge (VERIFIED / AWAITING VERIFICATION)', success: 'miles recorded', failure: 'unparseable report → UI.ERROR, retry', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.mileage_imported', write_contract: 'MILEAGE.write.addMileage', state_transition: null, contract_refs: ['required_inputs JURISDICTION_MILEAGE', 'sprint §13 FILE IMPORT / CSV REPORT IMPORT'], authority_refs: [SHEET + ' #02'] }),
  X({ interaction_id: 'I.ENTER_MILEAGE_MANUAL', label: 'Enter miles by state', actor: 'CLIENT', trigger: 'MANUAL STATE ENTRY', target: 'AIO.IFTA.CLIENT.ROOM.MILEAGE.MANUAL_ENTRY', data_effect: 'addMileage(sourceId MANUAL_STATE_ENTRY, entries[{state, miles}]) — verified only after staff review', ui_effect: 'entry rows per state; total updates; badge AWAITING VERIFICATION', success: 'miles saved', failure: 'invalid state / miles → inline validation', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.mileage_manual', write_contract: 'MILEAGE.write.addMileage', state_transition: null, contract_refs: ['AIO_IFTA_MILEAGE_SOURCES MANUAL_STATE_ENTRY'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  X({ interaction_id: 'I.CONNECT_ELD', label: 'Connect ELD / GPS', actor: 'CLIENT', trigger: 'ELD / GPS IMPORT in the source picker', target: 'AIO.IFTA.CLIENT.ROOM.MILEAGE.SOURCE_PICKER', data_effect: 'none — addMileage rejects ELD_GPS_IMPORT (“not live yet — upload the ELD report instead”)', ui_effect: 'shown as NOT LIVE YET with the report-upload alternative', success: '—', failure: 'routes to ELD report upload', permission: 'CLIENT', analytics_event: null, write_contract: null, state_transition: null, contract_refs: ['AIO_IFTA_MILEAGE_SOURCES ELD_GPS_IMPORT (integration roadmap)'], authority_refs: [], status: 'ROADMAP_NOT_SUPPORTED', note: 'Sprint §13 “ELD / GPS SOURCE IF SUPPORTED” — not supported today.' }),
  X({ interaction_id: 'I.OPEN_MILEAGE_RECORD', label: 'Open vehicle mileage', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'tap a vehicle mileage row', target: 'AIO.IFTA.CLIENT.ROOM.MILEAGE.VEHICLE_DETAIL', data_effect: 'none', ui_effect: 'drawer: miles by state, source badge, exceptions, fuel relationship, superseded sources', success: 'drawer open', failure: 'UI.ERROR', permission: 'viewer', analytics_event: 'ifta.mileage_opened', write_contract: null, state_transition: null, contract_refs: ['output_artifacts JURISDICTION_MILEAGE_RECORD view_behavior'], authority_refs: [SHEET + ' #03'] }),

  /* ── client: vehicles ── */
  X({ interaction_id: 'I.CONFIRM_VEHICLES', label: 'Confirm trucks that ran', actor: 'CLIENT', trigger: 'CONFIRM FLEET (pre-filled from the fleet profile)', target: 'AIO.IFTA.CLIENT.ROOM.VEHICLES.CONFIRM_FLEET', data_effect: 'confirmVehicles(operated map) — marks quarter participation; a truck that did not run is excluded', ui_effect: 'vehicle rows show RAN THIS QUARTER / DID NOT RUN; filing impact line updates', success: '“FLEET CONFIRMED — {n} TRUCKS RAN”', failure: 'quarter locked → UI.LOCKED_IN_REVIEW', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.fleet_confirmed', write_contract: 'VEHICLES.write.confirmVehicles', state_transition: null, contract_refs: ['required_inputs QUARTER_VEHICLES', 'interaction_grammar VERIFY'], authority_refs: [SHEET + ' #05'] }),
  X({ interaction_id: 'I.OPEN_VEHICLE', label: 'Open vehicle', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'tap a vehicle row', target: 'AIO.IFTA.CLIENT.ROOM.VEHICLES.VEHICLE_DETAIL', data_effect: 'none', ui_effect: 'drawer: unit, participation, fuel + miles this quarter, readiness, filing impact, prior-quarter MPG', success: 'drawer open', failure: 'UI.ERROR', permission: 'viewer', analytics_event: 'ifta.vehicle_opened', write_contract: null, state_transition: null, contract_refs: ['sprint §14 VEHICLE DETAIL'], authority_refs: [SHEET + ' #03'] }),
  X({ interaction_id: 'I.MANAGE_FLEET', label: 'Add / edit / deactivate a truck', actor: 'CLIENT', trigger: 'MANAGE FLEET link on the vehicles tab', target: 'Fleet profile (cross-feature)', data_effect: 'none in IFTA — the fleet profile owns units; the next quarter pre-fills from it', ui_effect: 'navigates to the fleet profile', success: 'fleet profile open', failure: '—', permission: 'CLIENT (fleet manager)', analytics_event: null, write_contract: null, state_transition: null, contract_refs: ['upstream_systems Fleet profile (vehicles)'], authority_refs: [SHEET], note: 'Contract-sheet VEHICLES “add, edit, deactivate” reconciled: the quarter only records participation.' }),

  /* ── client: jurisdictions + documents ── */
  X({ interaction_id: 'I.OPEN_JURISDICTION', label: 'Open jurisdiction', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'tap a jurisdiction (map, legend, table row)', target: 'AIO.IFTA.CLIENT.ROOM.JURISDICTIONS.STATE_DETAIL', data_effect: 'none', ui_effect: 'drawer: miles, gallons, allocation, net tax (from the return summary), exceptions, data quality, review status', success: 'drawer open', failure: 'UI.ERROR', permission: 'viewer', analytics_event: 'ifta.jurisdiction_opened', write_contract: null, state_transition: null, contract_refs: ['sprint §15 STATE DETAIL'], authority_refs: [SHEET + ' #03', 'CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  X({ interaction_id: 'I.OPEN_FILE', label: 'Open / preview file', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'tap a file row', target: 'AIO.IFTA.CLIENT.ROOM.DOCUMENTS.FILE_PREVIEW', data_effect: 'none', ui_effect: 'preview drawer with version history', success: 'preview', failure: 'file unavailable → UI.ERROR', permission: 'viewer', analytics_event: 'ifta.file_opened', write_contract: null, state_transition: null, contract_refs: ['output_artifacts view_behavior'], authority_refs: [SHEET + ' #03'] }),
  X({ interaction_id: 'I.DOWNLOAD_FILE', label: 'Download return / file', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'DOWNLOAD on a file row or the filed return', target: 'AIO.IFTA.CLIENT.ROOM.DOCUMENTS.FILE_PREVIEW', data_effect: 'read the Vault document', ui_effect: 'download starts', success: 'file saved', failure: 'UI.ERROR', permission: 'viewer', analytics_event: 'ifta.file_downloaded', write_contract: null, state_transition: null, contract_refs: ['output_artifacts FILED_RETURN view_behavior (PDF view / download)'], authority_refs: [SHEET] }),
  X({ interaction_id: 'I.SHARE_FILE', label: 'Share file', actor: 'CLIENT', trigger: 'SHARE on a file row', target: 'AIO.IFTA.CLIENT.ROOM.DOCUMENTS.FILE_PREVIEW', data_effect: 'create a share for a Vault document', ui_effect: 'share sheet', success: 'link / recipient recorded', failure: 'UI.ERROR', permission: 'CLIENT owner', analytics_event: 'ifta.file_shared', write_contract: 'DOCS.write.share', state_transition: null, contract_refs: [], authority_refs: [SHEET + ' §03 DOCUMENTS'] }),
  X({ interaction_id: 'I.OPEN_VAULT_RECORD', label: 'Open Vault record', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'VIEW IN VAULT', target: 'Vault › Tax & Fuel › IFTA › {YYYY} › Q{n} (cross-feature)', data_effect: 'none', ui_effect: 'navigates to the sealed packet in the Vault', success: 'Vault folder open', failure: 'not sealed yet → shows destination path', permission: 'CLIENT owner · staff', analytics_event: 'ifta.vault_opened', write_contract: null, state_transition: null, contract_refs: ['vault_destination', 'cross_feature_relationships IFTA_FILED_TO_VAULT'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),

  /* ── client: review + approval ── */
  X({ interaction_id: 'I.SEND_QUARTER_TO_AIO', label: 'Send quarter to AIO', actor: 'CLIENT', trigger: 'SEND QUARTER TO AIO (enabled when canSendToAio)', target: 'AIO.IFTA.CLIENT.ROOM.PROGRESS.SEND_CONFIRM', data_effect: 'sendQuarterToAio() — inputs lock; office work item / staff notice; activity ACT_SUBMITTED', ui_effect: 'confirm modal → state chip AIO REVIEWING; capture tools quiet', success: '“QUARTER SENT — AIO IS REVIEWING”', failure: 'blocked items listed (blockingItems) — nothing sent', permission: CLIENT_UNLOCKED, analytics_event: 'ifta.quarter_submitted', write_contract: 'QUARTER.write.sendQuarterToAio', state_transition: { from: 'COLLECTING', to: 'AIO_REVIEW' }, contract_refs: ['interaction_grammar SEND QUARTER TO AIO'], authority_refs: [SHEET + ' #10'] }),
  X({ interaction_id: 'I.REVIEW_DRAFT', label: 'Review draft return', actor: 'CLIENT', trigger: 'REVIEW YOUR RETURN (next-action rail in AWAITING_APPROVAL)', target: 'AIO.IFTA.CLIENT.ROOM.PROGRESS.RETURN_REVIEW', data_effect: 'none (read the return summary)', ui_effect: 'decision window: miles · gallons · MPG · tax due / credit by jurisdiction', success: 'summary shown', failure: 'no summary yet → PENDING AIO PREPARATION', permission: 'CLIENT owner', analytics_event: 'ifta.return_reviewed', write_contract: null, state_transition: null, contract_refs: ['client_approval_points CLIENT_APPROVES_RETURN'], authority_refs: [SHEET + ' #07'] }),
  X({ interaction_id: 'I.APPROVE_RETURN', label: 'Approve return', actor: 'CLIENT', trigger: 'APPROVE RETURN in the decision window', target: 'AIO.IFTA.CLIENT.ROOM.PROGRESS.RETURN_REVIEW.APPROVE_CONFIRM', data_effect: 'approveReturn() — approvedAt / approvedBy recorded; activity ACT_APPROVED; AIO may now file', ui_effect: 'confirm modal → chip APPROVED — AIO IS FILING', success: '“APPROVED — AIO WILL FILE YOUR RETURN”', failure: 'summary changed / not in AWAITING_APPROVAL → error, nothing approved', permission: 'CLIENT owner in AWAITING_APPROVAL', analytics_event: 'ifta.return_approved', write_contract: 'RETURN.write.approveReturn', state_transition: { from: 'AWAITING_APPROVAL', to: 'FILING' }, contract_refs: ['interaction_grammar APPROVE'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  X({ interaction_id: 'I.ASK_QUESTION', label: 'Ask a question about the return', actor: 'CLIENT', trigger: 'ASK A QUESTION in the decision window', target: 'AIO.IFTA.CLIENT.ROOM.PROGRESS.RETURN_REVIEW.ASK', data_effect: 'askQuestion(text) — returnSummary.clientQuestion; quarter back to RECONCILING; thread message', ui_effect: 'drawer with the question; chip AIO REVIEWING', success: '“QUESTION SENT TO AIO”', failure: 'empty text → validation', permission: 'CLIENT owner in AWAITING_APPROVAL', analytics_event: 'ifta.return_question', write_contract: 'RETURN.write.askQuestion', state_transition: { from: 'AWAITING_APPROVAL', to: 'RECONCILING' }, contract_refs: ['interaction_grammar ASK A QUESTION'], authority_refs: [SHEET + ' #07'] }),
  X({ interaction_id: 'I.MESSAGE_AIO', label: 'Message your AIO team', actor: 'CLIENT', trigger: 'NEED HELP? MESSAGE YOUR AIO TEAM (help rail)', target: 'AIO.IFTA.CLIENT.ROOM.MESSAGES', data_effect: 'postThread() on the quarter request thread (ensureThread)', ui_effect: 'thread drawer; message appended', success: 'message sent', failure: 'UI.ERROR, draft kept', permission: 'CLIENT owner', analytics_event: 'ifta.message_sent', write_contract: 'MSG.write.postThread', state_transition: null, contract_refs: ['optional_inputs NOTES_FOR_AIO (method MESSAGE)', 'project_room messages'], authority_refs: [SHEET + ' #08', 'CLIENT_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.START_NEXT_QUARTER', label: 'Go to next quarter', actor: 'CLIENT', trigger: 'START Q{n+1} on an archived / filed quarter', target: 'AIO.IFTA.CLIENT.ROOM.NEXT_QUARTER_OPEN', data_effect: 'none (successor opened by openNextQuarter — SYSTEM)', ui_effect: 'room switches to the new quarter (empty packet, fleet pre-filled)', success: 'Q{n+1} shown', failure: 'successor not open yet → shows when it opens', permission: 'CLIENT', analytics_event: 'ifta.next_quarter_viewed', write_contract: null, state_transition: null, contract_refs: ['visual_relationships ARCHIVED primary_cta START Q{n+1}'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  X({ interaction_id: 'I.SET_UP_FILING', label: 'Set up IFTA filing', actor: 'CLIENT', trigger: 'SET UP IFTA FILING (no service yet)', target: 'AIO.IFTA.CLIENT.NOT_ENROLLED', data_effect: 'service request (quote required) for ifta-filing; IFTA account prerequisite routes to ifta-reg', ui_effect: 'request form; status REQUESTED', success: 'request submitted', failure: 'service not available → shows status', permission: 'CLIENT', analytics_event: 'ifta.setup_requested', write_contract: 'ENROLL.write.requestService', state_transition: { from: 'NOT_ENROLLED', to: 'QUARTER_OPEN' }, contract_refs: ['visual_relationships NOT_ENROLLED primary_cta'], authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),

  /* ── office context (AIO OFFICE / CLIENT OFFICE — operating-environment model in the Experience Brain) ── */
  X({ interaction_id: 'I.SWITCH_WORKSPACE', label: 'Switch workspace', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'WORKSPACE_SWITCHER item', target: 'the chosen workspace for the SAME client (client office: the fixed session client)', data_effect: 'none — context re-resolves (resolveContext): active case, tabs, counts, alerts, tasks, documents, messages, activity, deadlines, actions, expansion suggestions, permissions, subcontext selector', ui_effect: 'workspace landing / case for the same client; inactive → staff WORKSPACE NOT ACTIVE · client NOT ACTIVE YET expansion state', success: 'new workspace shown with only its own client-scoped records (no stale state)', failure: 'workspace unknown → stays; context error shown in the body', permission: 'client: own organisation’s workspaces · staff: office role with access to the client (existing guards — not broadened)', analytics_event: 'office.workspace_switched', write_contract: null, state_transition: null, contract_refs: ['AIO_OFFICE_CONTEXT_MODEL switchers.WORKSPACE'], authority_refs: [] }),
  X({ interaction_id: 'I.SWITCH_CLIENT', label: 'Switch client', actor: 'FOUNDER_STAFF', trigger: 'CLIENT_SWITCHER item / client lookup', target: 'the SAME workspace for the chosen client', data_effect: 'none — context re-resolves for the new client; subcontext kept only if that client has the same case', ui_effect: 'IFTA case (or queue row) for the new client; workspace inactive for that client → WORKSPACE NOT ACTIVE FOR THIS CLIENT', success: 'new client shown in the same workspace', failure: 'client inactive in this workspace → truthful inactive state (never another client)', permission: 'AIO OFFICE only — CLIENT OFFICE has no client switcher (ContextError NO_CLIENT_SWITCHER)', analytics_event: 'office.client_switched', write_contract: null, state_transition: null, contract_refs: ['AIO_OFFICE_CONTEXT_MODEL switchers.CLIENT'], authority_refs: [] }),
  X({ interaction_id: 'I.RETURN_TO_HUB', label: 'Return to office hub', actor: 'CLIENT · FOUNDER_STAFF', trigger: 'AIO mark / OFFICE in the top nav', target: 'AIO OFFICE HUB (staff) · CLIENT OFFICE HUB (client)', data_effect: 'none', ui_effect: 'hub view for the environment', success: 'hub shown', failure: 'UI.ERROR in the body', permission: 'environment member', analytics_event: 'office.hub_opened', write_contract: null, state_transition: null, contract_refs: ['AIO_OFFICE_ARCHITECTURE hubs'], authority_refs: [] }),
  X({ interaction_id: 'I.OPEN_CLIENT_OVERVIEW', label: 'View client overview', actor: 'FOUNDER_STAFF', trigger: 'VIEW CLIENT OVERVIEW (client identity / inactive-workspace state)', target: 'AIO OFFICE client context (one client, every workspace)', data_effect: 'none', ui_effect: 'client overview with that client’s workspace states', success: 'client overview shown', failure: 'client not accessible → access error', permission: STAFF, analytics_event: 'office.client_overview_opened', write_contract: null, state_transition: null, contract_refs: ['AIO_OFFICE_CONTEXT_MODEL routes /office/clients/:clientId'], authority_refs: [] }),
  X({ interaction_id: 'I.RETURN_TO_QUEUE', label: 'Return to workspace queue', actor: 'FOUNDER_STAFF', trigger: 'RETURN TO FUEL TAX QUEUE', target: 'AIO.IFTA.STAFF.QUEUE', data_effect: 'none', ui_effect: 'cross-client IFTA queue', success: 'queue shown', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'office.queue_opened', write_contract: null, state_transition: null, contract_refs: ['AIO_OFFICE_CONTEXT_MODEL workspace_landing CROSS_CLIENT_QUEUE'], authority_refs: [] }),
  X({ interaction_id: 'I.VIEW_ELIGIBILITY', label: 'View eligibility', actor: 'FOUNDER_STAFF', trigger: 'VIEW ELIGIBILITY on WORKSPACE NOT ACTIVE', target: 'WORKSPACE_STATE_PANEL', data_effect: 'none — evaluates the workspace eligibility rule against recorded client signals (reasons listed; UNKNOWN when a signal is missing)', ui_effect: 'eligibility reasons beside the state panel', success: 'reasons shown', failure: 'signals missing → ELIGIBILITY UNKNOWN (never guessed)', permission: STAFF, analytics_event: null, write_contract: null, state_transition: null, contract_refs: ['WORKSPACE_AVAILABILITY_MODEL eligibility'], authority_refs: [] }),
  X({ interaction_id: 'I.EXPLORE_WORKSPACE', label: 'Explore a workspace', actor: 'CLIENT', trigger: 'AVAILABLE item in the workspace switcher / expansion card CTA', target: 'that workspace’s NOT ACTIVE YET expansion state', data_effect: 'none until the client requests the service', ui_effect: 'expansion state: name · not active yet · why it may matter · what AIO handles · what you provide · request', success: 'expansion state shown', failure: 'suppressed (not applicable / unavailable / eligibility unknown / critical state) → no surface', permission: 'CLIENT (own organisation)', analytics_event: 'office.expansion_opened', write_contract: null, state_transition: null, contract_refs: ['WORKSPACE_EXPANSION_CONTRACT'], authority_refs: [] }),

  /* ── staff ── */
  X({ interaction_id: 'I.OPEN_CASE', label: 'Open quarter case', actor: 'FOUNDER_STAFF', trigger: 'tap a client-quarter row in the fuel tax queue', target: 'AIO.IFTA.STAFF.CASE', data_effect: 'none', ui_effect: 'case file opens on OVERVIEW', success: 'case shown', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'ifta.case_opened', write_contract: null, state_transition: null, contract_refs: ['staff_cta OPEN QUARTER CASE'], authority_refs: [] }),
  X({ interaction_id: 'I.START_RECONCILIATION', label: 'Start reconciliation', actor: 'FOUNDER_STAFF', trigger: 'START RECONCILIATION (AIO_REVIEW)', target: 'AIO.IFTA.STAFF.CASE.OVERVIEW', data_effect: 'startReconciliation() — reviewStartedAt; discrepancies computed', ui_effect: 'chip ACTIVE REVIEW → RECONCILING; jurisdictions tab shows the reconciliation table', success: 'reconciling', failure: 'wrong state → error', permission: STAFF, analytics_event: 'ifta.reconciliation_started', write_contract: 'STAFF.write.startReconciliation', state_transition: { from: 'AIO_REVIEW', to: 'RECONCILING' }, contract_refs: ['interaction_grammar RECONCILE'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.REQUEST_CORRECTION', label: 'Request correction', actor: 'FOUNDER_STAFF', trigger: 'REQUEST CORRECTION (pick receipts / vehicles + templated message)', target: 'AIO.IFTA.STAFF.CASE.REQUEST_CORRECTION', data_effect: 'requestCorrection(receiptIds, vehicleIds, message) — IftaCorrectionRequest; client notice + thread', ui_effect: 'modal → chip AWAITING CLIENT — CORRECTION REQUESTED', success: 'client notified', failure: 'nothing selected → validation', permission: STAFF, analytics_event: 'ifta.correction_requested', write_contract: 'STAFF.write.requestCorrection', state_transition: { from: 'AIO_REVIEW', to: 'NEEDS_CLIENT' }, contract_refs: ['interaction_grammar REQUEST CORRECTION'], authority_refs: [SHEET + ' #06'] }),
  X({ interaction_id: 'I.NUDGE_CLIENT', label: 'Nudge client', actor: 'FOUNDER_STAFF', trigger: 'NUDGE CLIENT / REMIND CLIENT', target: 'AIO.IFTA.STAFF.CASE.OVERVIEW', data_effect: 'nudgeClient() — client notice + audit', ui_effect: 'toast; activity row', success: 'reminder sent', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'ifta.client_nudged', write_contract: 'STAFF.write.nudgeClient', state_transition: null, contract_refs: ['visual_relationships NEEDS_CLIENT staff primary_cta NUDGE CLIENT'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.STAFF_VERIFY_RECEIPT', label: 'Verify receipt', actor: 'FOUNDER_STAFF', trigger: 'VERIFY on a receipt under AIO review', target: 'AIO.IFTA.STAFF.CASE.FUEL_PURCHASES.RECEIPT_REVIEW', data_effect: 'verifyReceipt() — UNDER_AIO_REVIEW → READY + audit', ui_effect: 'chip PROCESSED', success: '“RECORD VERIFIED AND SAVED.”', failure: 'wrong class → error', permission: STAFF, analytics_event: 'ifta.receipt_verified', write_contract: 'STAFF.write.verifyReceipt', state_transition: null, contract_refs: ['human_review receipt classification review'], authority_refs: [SHEET + ' #05'] }),
  X({ interaction_id: 'I.RECLASSIFY_RECEIPT', label: 'Reclassify / edit parsed fields', actor: 'FOUNDER_STAFF', trigger: 'EDIT in the receipt review drawer', target: 'AIO.IFTA.STAFF.CASE.FUEL_PURCHASES.RECEIPT_REVIEW', data_effect: 'edit parsed fields + class with an audit note', ui_effect: 'fields editable; audit line', success: 'saved', failure: 'no note → validation', permission: STAFF, analytics_event: 'ifta.receipt_reclassified', write_contract: 'STAFF.write.reclassifyReceipt', state_transition: null, contract_refs: ['perspectives.founder_staff.corrections (reclassify receipt · edit parsed fields with audit note)'], authority_refs: [SHEET + ' #03'] }),
  X({ interaction_id: 'I.VERIFY_MILEAGE_SOURCE', label: 'Verify mileage source', actor: 'FOUNDER_STAFF', trigger: 'VERIFY on a manual / spreadsheet / assisted record', target: 'AIO.IFTA.STAFF.CASE.MILEAGE.SOURCE_VERIFY', data_effect: 'verifyMileage() — staffVerifiedAt; readiness recomputed', ui_effect: 'badge VERIFIED', success: 'verified', failure: 'already verified / estimate → error', permission: STAFF, analytics_event: 'ifta.mileage_verified', write_contract: 'STAFF.write.verifyMileage', state_transition: null, contract_refs: ['human_review mileage source verification'], authority_refs: [SHEET + ' #05'] }),
  X({ interaction_id: 'I.RESOLVE_DISCREPANCY', label: 'Resolve discrepancy (override with note)', actor: 'FOUNDER_STAFF', trigger: 'RESOLVE on a discrepancy (miles without fuel · MPG outlier · unverified mileage)', target: 'AIO.IFTA.STAFF.CASE.JURISDICTIONS.DISCREPANCY', data_effect: 'resolveDiscrepancy(note, override) — an override requires a note; audited', ui_effect: 'discrepancy leaves RISKS / FLAGS', success: 'resolved', failure: 'override without note → validation', permission: STAFF, analytics_event: 'ifta.discrepancy_resolved', write_contract: 'STAFF.write.resolveDiscrepancy', state_transition: null, contract_refs: ['founder_override_points ACCEPT_ESTIMATE_GAP'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.STAFF_MARK_NOT_OPERATED', label: 'Mark vehicle not operated (override)', actor: 'FOUNDER_STAFF', trigger: 'MARK NOT OPERATED on a vehicle', target: 'AIO.IFTA.STAFF.CASE.VEHICLES', data_effect: 'operated = false + notOperatedNote (audited)', ui_effect: 'vehicle row EXCLUDED — NOTE ON FILE', success: 'excluded', failure: 'no note → validation', permission: STAFF, analytics_event: 'ifta.vehicle_excluded', write_contract: 'STAFF.write.markNotOperated', state_transition: null, contract_refs: ['perspectives.founder_staff.overrides mark vehicle not operated'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.ENTER_WORKSHEET', label: 'Enter filing worksheet', actor: 'FOUNDER_STAFF', trigger: 'WORKSHEET in the return draft', target: 'AIO.IFTA.STAFF.CASE.RETURN_DRAFT', data_effect: 'staffWorksheet[{jurisdiction, netTax}] — staff-entered figures; no tax computed', ui_effect: 'per-jurisdiction net tax inputs', success: 'worksheet saved', failure: 'missing jurisdiction → validation', permission: STAFF, analytics_event: 'ifta.worksheet_saved', write_contract: 'STAFF.write.worksheet', state_transition: null, contract_refs: ['system_derivations RETURN_SUMMARY (staff-prepared)'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.PREPARE_RETURN_SUMMARY', label: 'Open / prepare return draft', actor: 'FOUNDER_STAFF', trigger: 'OPEN RETURN DRAFT (dark rail)', target: 'AIO.IFTA.STAFF.CASE.RETURN_DRAFT', data_effect: 'prepareReturnSummary() — only at READY_FOR_REPORTING with no open discrepancies and a worksheet', ui_effect: 'return draft page with per-jurisdiction lines', success: 'draft prepared', failure: 'blocked reasons listed (open discrepancies · receipts under review · readiness · worksheet missing)', permission: STAFF, analytics_event: 'ifta.return_prepared', write_contract: 'STAFF.write.prepareReturnSummary', state_transition: null, contract_refs: ['operational_actions PREPARE RETURN SUMMARY'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.SEND_FOR_APPROVAL', label: 'Send for client approval', actor: 'FOUNDER_STAFF', trigger: 'SEND FOR APPROVAL on the return draft', target: 'AIO.IFTA.STAFF.CASE.RETURN_DRAFT.SEND_CONFIRM', data_effect: 'sendForApproval() — sentForApprovalAt; client inbox IFTA_APPROVAL_REQUEST + notification', ui_effect: 'confirm modal → chip AWAITING CLIENT APPROVAL', success: 'client asked to approve', failure: 'no draft → error', permission: STAFF, analytics_event: 'ifta.sent_for_approval', write_contract: 'STAFF.write.sendForApproval', state_transition: { from: 'RECONCILING', to: 'AWAITING_APPROVAL' }, contract_refs: ['interaction_grammar SEND FOR APPROVAL'], authority_refs: [SHEET + ' #10'] }),
  X({ interaction_id: 'I.RECORD_FILING', label: 'File & confirm', actor: 'FOUNDER_STAFF', trigger: 'RECORD FILING CONFIRMATION (staff files with the base jurisdiction outside AIO)', target: 'AIO.IFTA.STAFF.CASE.RECORD_FILING', data_effect: 'recordFiling(confirmationNumber) — FILED; packet sealed to the Vault; inbox thread resolved; activity ACT_FILED', ui_effect: 'modal → chip FILED; documents show final return + confirmation', success: '“FILED — CONFIRMATION RECORDED”', failure: 'not approved / no confirmation number → validation', permission: STAFF, analytics_event: 'ifta.filed', write_contract: 'STAFF.write.recordFiling', state_transition: { from: 'FILING', to: 'FILED' }, contract_refs: ['interaction_grammar FILE', 'human_review_points STAFF_FILE'], authority_refs: [SHEET + ' #11'], note: 'Contract-sheet “electronic filing” is not true today: filing is a staff action recorded in AIO (no government integration).' }),
  X({ interaction_id: 'I.RECORD_PAYMENT', label: 'Record payment status', actor: 'FOUNDER_STAFF', trigger: 'RECORD PAYMENT STATUS (FILED)', target: 'AIO.IFTA.STAFF.CASE.RECORD_PAYMENT', data_effect: 'recordPayment(PAYMENT_PENDING | PAID | CREDIT_CARRIED | NO_TAX_DUE) — completes → ARCHIVED + next quarter', ui_effect: 'modal → chip COMPLETE', success: 'payment status recorded', failure: 'wrong state → error', permission: STAFF, analytics_event: 'ifta.payment_recorded', write_contract: 'STAFF.write.recordPayment', state_transition: { from: 'FILED', to: 'ARCHIVED' }, contract_refs: ['operational_actions RECORD PAYMENT STATUS'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.ESCALATE', label: 'Escalate deadline risk', actor: 'FOUNDER_STAFF', trigger: 'ESCALATE / CALL CLIENT (OVERDUE_RISK)', target: 'AIO.IFTA.STAFF.CASE.OVERVIEW', data_effect: 'escalation task + audit', ui_effect: 'risk flag ESCALATED', success: 'escalated', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'ifta.escalated', write_contract: 'STAFF.write.escalate', state_transition: null, contract_refs: ['founder_override_points EXTEND_DUE_HANDLING', 'human_tasks TASK_ESCALATE'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.OPEN_CORRECTION', label: 'Record rejection / open amendment', actor: 'FOUNDER_STAFF', trigger: 'jurisdiction returned the filing', target: 'AIO.IFTA.STAFF.CASE.AMENDMENT', data_effect: 'FILING → FILING_REJECTED → RECONCILING with reason', ui_effect: 'correction notice over the summary', success: 'amendment open', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'ifta.filing_rejected', write_contract: 'STAFF.write.recordRejection', state_transition: { from: 'FILING', to: 'FILING_REJECTED' }, contract_refs: ['transitions FILING → FILING_REJECTED → RECONCILING'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.REOPEN_QUARTER', label: 'Reopen archived quarter', actor: 'FOUNDER_STAFF', trigger: 'REOPEN on an archived quarter', target: 'AIO.IFTA.STAFF.CASE.REOPEN', data_effect: 'ARCHIVED → RECONCILING; new sealed version on completion', ui_effect: 'confirm modal with reason', success: 'reopened', failure: 'no reason → validation', permission: 'FOUNDER (override)', analytics_event: 'ifta.quarter_reopened', write_contract: 'STAFF.write.reopenQuarter', state_transition: { from: 'ARCHIVED', to: 'RECONCILING' }, contract_refs: ['founder_override_points REOPEN_QUARTER'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.EXPORT_REPORT', label: 'Export report', actor: 'FOUNDER_STAFF', trigger: 'EXPORT REPORT (tab bar)', target: 'AIO.IFTA.STAFF.CASE', data_effect: 'export the case (receipts · mileage · summary · audit) as a file', ui_effect: 'download', success: 'file saved', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'ifta.case_exported', write_contract: 'STAFF.write.exportReport', state_transition: null, contract_refs: [], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.OPEN_AUDIT_TRAIL', label: 'Open audit trail', actor: 'FOUNDER_STAFF', trigger: 'VIEW AUDIT TRAIL', target: 'AIO.IFTA.STAFF.CASE.AUDIT', data_effect: 'none', ui_effect: 'audit drawer (classification changes · overrides with note · approval · filing · amendments)', success: 'drawer open', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'ifta.audit_opened', write_contract: null, state_transition: null, contract_refs: ['perspectives.founder_staff.audit_history'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.MESSAGE_CLIENT', label: 'Message client', actor: 'FOUNDER_STAFF', trigger: 'MESSAGE in the case', target: 'AIO.IFTA.STAFF.CASE.THREAD', data_effect: 'postThread() on the quarter request thread', ui_effect: 'thread drawer', success: 'message sent', failure: 'UI.ERROR', permission: STAFF, analytics_event: 'ifta.staff_message', write_contract: 'MSG.write.postThread', state_transition: null, contract_refs: ['perspectives.founder_staff.communication'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.SAVE_NOTE', label: 'Save staff note', actor: 'FOUNDER_STAFF', trigger: 'ADD NOTE on the staff NOTES tab', target: 'AIO.IFTA.STAFF.CASE.NOTES', data_effect: 'append an internal note to the client-quarter case (no IFTA note model exists — NOTES.write MISSING)', ui_effect: 'note appended to the internal list; never visible to the client', success: 'note saved', failure: 'UI.ERROR, draft kept', permission: STAFF, analytics_event: 'ifta.staff_note_saved', write_contract: 'NOTES.write', state_transition: null, contract_refs: ['perspectives.founder_staff.audit_history', 'output_artifacts.DISCREPANCY_LOG'], authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'], note: 'D-NOTES-TAB (DECIDED): staff-only SECONDARY tab. The client has no NOTES tab — client notes travel through I.MESSAGE_AIO.' }),
  X({ interaction_id: 'I.FILTER_QUEUE', label: 'Filter / sort queue', actor: 'FOUNDER_STAFF', trigger: 'bucket chips / due-date sort', target: 'AIO.IFTA.STAFF.QUEUE', data_effect: 'none (sortStaffQueue · staffBucket)', ui_effect: 'queue regrouped by bucket', success: 'filtered', failure: 'UI.EMPTY', permission: STAFF, analytics_event: 'ifta.queue_filtered', write_contract: null, state_transition: null, contract_refs: ['hub_buckets'], authority_refs: [] }),

  /* ── public ── */
  X({ interaction_id: 'I.GET_STARTED', label: 'Get started (request filing)', actor: 'PUBLIC', trigger: 'GET STARTED (nav / explanation)', target: 'AIO.IFTA.PUBLIC.REQUEST_FILING', data_effect: 'none until submit', ui_effect: 'opens the request-filing flow', success: 'flow open', failure: '—', permission: 'anyone', analytics_event: 'ifta.public_get_started', write_contract: null, state_transition: null, contract_refs: ['public_cta REQUEST FILING'], authority_refs: ['PUBLIC_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.SEE_HOW_IT_WORKS', label: 'See how it works', actor: 'PUBLIC', trigger: 'SEE HOW IT WORKS (hero)', target: 'AIO.IFTA.PUBLIC.SERVICE.HOW_IT_WORKS', data_effect: 'none', ui_effect: 'scroll to the process section', success: 'section in view', failure: '—', permission: 'anyone', analytics_event: 'ifta.public_how_it_works', write_contract: null, state_transition: null, contract_refs: ['perspectives.public.how_it_works'], authority_refs: ['PUBLIC_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.PUBLIC_NAV', label: 'Section navigation', actor: 'PUBLIC', trigger: 'IFTA FILING ROOM · HOW IT WORKS · FEATURES · JURISDICTIONS · RESOURCES (desktop) / menu (mobile, tablet)', target: 'TOP_NAV (public)', data_effect: 'none', ui_effect: 'scroll to the section; active item underlined gold', success: 'section in view', failure: '—', permission: 'anyone', analytics_event: null, write_contract: null, state_transition: null, contract_refs: [], authority_refs: ['PUBLIC_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.SUBMIT_FILING_REQUEST', label: 'Submit filing request', actor: 'PUBLIC', trigger: 'REQUEST FILING form submit (company, contact, fleet size, base jurisdiction, IFTA account yes / no)', target: 'AIO.IFTA.PUBLIC.REQUEST_FILING', data_effect: 'service request for ifta-filing (quote required) through the AIO request engine', ui_effect: 'confirmation with what happens next', success: '“REQUEST RECEIVED — AIO WILL SEND YOUR QUOTE”', failure: 'validation errors inline; service not available → status shown truthfully', permission: 'anyone (account created / linked by the request flow)', analytics_event: 'ifta.public_request_submitted', write_contract: 'ENROLL.write.requestService', state_transition: { from: 'NOT_ENROLLED', to: 'QUARTER_OPEN' }, contract_refs: ['perspectives.public.pricing_relationship (quote required)', 'transitions NOT_ENROLLED → QUARTER_OPEN'], authority_refs: ['PUBLIC_TABLET_DESKTOP'] }),
  X({ interaction_id: 'I.START_IFTA_REGISTRATION', label: 'Get an IFTA account first', actor: 'PUBLIC', trigger: '“NO IFTA ACCOUNT YET?” in the request flow', target: 'AIO.IFTA.PUBLIC.REQUEST_FILING', data_effect: 'none (navigates to the IFTA registration service)', ui_effect: 'routes to ifta-reg service', success: 'registration page', failure: '—', permission: 'anyone', analytics_event: 'ifta.public_registration_link', write_contract: null, state_transition: null, contract_refs: ['information_hierarchy.PUBLIC.blocker (IFTA account first → IFTA registration)'], authority_refs: [] }),

  /* ── contract item 09: identity resolved by the founder; behaviour description not legible ── */
  X({ interaction_id: 'I.RUN_FAQS', label: 'Run FAQs', actor: 'NEEDS_CLARIFICATION — the contract sheet lists item 09 in the family-wide interaction set without naming the actor', trigger: 'RUN FAQS control (contract sheet §05 item 09; sequence 08 MESSAGE TEAM → 09 RUN FAQS → 10 SUBMIT FOR APPROVAL)', target: 'NEEDS_CLARIFICATION — family-level contract item; not bound to a material node until the behaviour is described', data_effect: 'NEEDS_CLARIFICATION', ui_effect: 'NEEDS_CLARIFICATION', success: 'NEEDS_CLARIFICATION', failure: 'NEEDS_CLARIFICATION', permission: 'NEEDS_CLARIFICATION', analytics_event: null, write_contract: null, state_transition: null, contract_refs: [], authority_refs: [SHEET + ' #09'], status: 'IDENTITY_RESOLVED_BEHAVIOR_PARTIAL', note: 'D-INTERACTION-09 (DECIDED): label “09 RUN FAQS” supplied by the founder; position + icon confirmed in the bundle image; no behaviour line is legible. Only the behaviour description needs clarification — nothing is invented. Bound to the client and staff page families (contract interaction set), never to a material node, so it blocks no unrelated node.' }),
];

/**
 * The contract sheet §05 interaction sequence (01–11), preserved verbatim. Item 09 is “RUN FAQS” (founder-supplied clearer
 * image, D-INTERACTION-09): identity known, behaviour description pending — it is kept, never dropped and never relabelled.
 */
export const AIO_IFTA_CONTRACT_INTERACTION_SEQUENCE = [
  ['01', 'UPLOAD RECEIPT'], ['02', 'IMPORT CSV'], ['03', 'OPEN DETAIL DRAWER'], ['04', 'FILTER / SORT'], ['05', 'VERIFY RECORD'],
  ['06', 'REQUEST CORRECTION'], ['07', 'REVIEW DRAFT'], ['08', 'MESSAGE TEAM'], ['09', 'RUN FAQS'], ['10', 'SUBMIT FOR APPROVAL'], ['11', 'FILE & CONFIRM'],
].map(([item, label]) => ({
  item, label,
  interactions: AIO_IFTA_INTERACTIONS.filter((x) => x.authority_refs.includes(`${SHEET} #${item}`)).map((x) => x.interaction_id),
  status: item === '09' ? 'IDENTITY_RESOLVED / BEHAVIOR_DESCRIPTION_PARTIAL' : 'DEFINED',
}));
