/**
 * AIO IFTA — state registry (three layers).
 *
 * QUARTER: the sprint's client state family (§18) mapped onto the experience contract's state machine, plus the contract
 *   states the sprint list does not name (never dropped). Every material client state carries its staff mirror (§19).
 * UI:      the contract-sheet states (default · loading · empty · success · warning / exception · error) plus blocked /
 *   locked-in-review / read-only.
 * RECORD:  receipt, mileage, vehicle, jurisdiction and document statuses (reference chips ↔ contract classes).
 *
 * Copy is UPPERCASE (typography rule). Derivations cite the existing AIO functional truth (fsbw src/ifta, read-only).
 */
import type { StateContract } from '../../../tree.js';

const Q = (x: Omit<StateContract, 'layer' | 'material'> & { material?: boolean }): StateContract => ({ layer: 'QUARTER', material: true, ...x });
const UI = (x: Omit<StateContract, 'layer' | 'maps_to'> & { maps_to?: string[] }): StateContract => ({ layer: 'UI', maps_to: [], material: false, ...x });
const R = (x: Omit<StateContract, 'layer'>): StateContract => ({ layer: 'RECORD', material: false, ...x });

const PARENT = ['CLIENT_MOBILE_PARENT_AUTHORITY'];
const CONTRACT_SHEET = ['PAGE_COMPONENT_INTERACTION_CONTRACT'];

export const AIO_IFTA_STATES: StateContract[] = [
  /* ── QUARTER layer: sprint §18 client state family ── */
  Q({ state_id: 'COLLECTING', label: 'Collecting', meaning: 'The quarter is open and fuel / miles are arriving.', maps_to: ['QUARTER_OPEN', 'COLLECTING'], derivation: 'effectiveState() ∈ {QUARTER_OPEN, COLLECTING} (QUARTER_OPEN = nothing received yet)', client_label: 'COLLECTING — {pct}% READY · DUE {due_date}', staff_mirror: 'RECORDS ARRIVING — {pct}% COMPLETE', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'NEEDS_YOU', label: 'Needs you', meaning: 'System flags only the client can answer (receipt questions, unreadable files, possible missing receipts, a truck without miles).', maps_to: ['NEEDS_CLIENT'], derivation: 'NEEDS_CLIENT with open client items from clientOpenItems() and no open staff correction request', client_label: 'NEEDS YOU — {n} RECEIPTS', staff_mirror: 'AWAITING CLIENT — {n} RECEIPT CORRECTIONS', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'READY_FOR_AIO', label: 'Ready to send to AIO', meaning: 'Every vehicle has fuel and a mileage source and nothing needs the client — the quarter can be sent.', maps_to: ['COLLECTING'], derivation: 'COLLECTING ∧ canSendToAio().ok', client_label: 'READY TO SEND TO AIO', staff_mirror: 'CLIENT READY TO SUBMIT', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'AIO_REVIEWING', label: 'AIO reviewing', meaning: 'AIO is checking records and reconciling fuel with miles.', maps_to: ['AIO_REVIEW', 'RECONCILING'], derivation: 'state ∈ {AIO_REVIEW, RECONCILING}', client_label: 'AIO REVIEWING', staff_mirror: 'ACTIVE REVIEW', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'CORRECTION_REQUIRED', label: 'Correction required', meaning: 'AIO sent specific items back to the client.', maps_to: ['NEEDS_CLIENT'], derivation: 'NEEDS_CLIENT ∧ an open IftaCorrectionRequest (requestCorrection)', client_label: 'CORRECTION REQUESTED — {n} ITEMS', staff_mirror: 'AWAITING CLIENT — CORRECTION REQUESTED ({n})', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'READY_FOR_CLIENT_REVIEW', label: 'Ready for your review', meaning: 'The return summary is issued and waiting for the client’s decision.', maps_to: ['AWAITING_APPROVAL'], derivation: 'AWAITING_APPROVAL ∧ now − returnSummary.sentForApprovalAt < 2 days', client_label: 'READY FOR YOUR REVIEW', staff_mirror: 'AWAITING CLIENT APPROVAL', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'CLIENT_APPROVAL_PENDING', label: 'Approval pending', meaning: 'The decision window has been open past the contract reminder (approval pending after 2 days).', maps_to: ['AWAITING_APPROVAL'], derivation: 'AWAITING_APPROVAL ∧ now − returnSummary.sentForApprovalAt ≥ 2 days (contract reminder “approval pending after 2 days”)', client_label: 'APPROVAL PENDING — AIO FILES AFTER YOU APPROVE', staff_mirror: 'AWAITING CLIENT APPROVAL — REMINDER DUE', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'APPROVED_FOR_FILING', label: 'Approved for filing', meaning: 'The client approved; AIO has not recorded the filing yet.', maps_to: ['FILING'], derivation: 'FILING ∧ returnSummary.approvedAt', client_label: 'APPROVED — AIO IS FILING', staff_mirror: 'READY TO FILE', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'FILING', label: 'Filing', meaning: 'Staff are filing with the base jurisdiction.', maps_to: ['FILING'], derivation: 'FILING — no separate “filing started” marker exists; the contract treats READY TO FILE and FILING IN PROGRESS as one state', client_label: 'AIO IS FILING YOUR RETURN', staff_mirror: 'FILING IN PROGRESS', data_status: 'PARTIAL', authority_refs: PARENT }),
  Q({ state_id: 'FILED', label: 'Filed', meaning: 'The filing confirmation is recorded.', maps_to: ['FILED'], derivation: 'state FILED ∧ filing.confirmationNumber (recordFiling)', client_label: 'FILED — CONFIRMATION IN YOUR VAULT', staff_mirror: 'FILED — CONFIRM PAYMENT STATUS', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'PAYMENT_PENDING', label: 'Payment pending', meaning: 'Filed with tax due; the carrier’s payment is not yet recorded. Applicable only when the return shows tax due (the tax is the carrier’s own liability, separate from AIO fees).', maps_to: ['FILED'], derivation: 'FILED ∧ payment.status = PAYMENT_PENDING (recordPayment)', applicability: 'CONTRACTUALLY APPLICABLE when returnSummary.netPosition > 0', client_label: 'FILED — PAYMENT PENDING', staff_mirror: 'PAYMENT PENDING — RECORD WHEN PAID', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'COMPLETE', label: 'Complete', meaning: 'Filed, payment status recorded and the packet sealed in the Vault.', maps_to: ['FILED', 'ARCHIVED'], derivation: 'FILED ∧ payment.status ∈ {PAID, CREDIT_CARRIED, NO_TAX_DUE} ∧ vault packet sealed (sealPacketToVault)', client_label: 'COMPLETE — PACKET IN YOUR VAULT', staff_mirror: 'COMPLETE — AUDIT TRAIL CLOSED', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'ARCHIVED', label: 'Archived', meaning: 'The quarter is history in the filing room.', maps_to: ['ARCHIVED'], derivation: 'state ARCHIVED', client_label: 'Q{n} {YYYY} FILED AND ARCHIVED', staff_mirror: 'CLOSED — AUDIT TRAIL COMPLETE', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'NEXT_QUARTER_OPEN', label: 'Next quarter open', meaning: 'The successor quarter is open with the fleet pre-filled.', maps_to: ['QUARTER_OPEN'], derivation: 'successor case from openNextQuarter() in QUARTER_OPEN (cross-feature IFTA_ARCHIVED_OPENS_NEXT)', client_label: 'Q{n+1} {YYYY} IS OPEN — START SENDING FUEL AND MILES', staff_mirror: 'COLLECTION WINDOW OPEN — NOTHING RECEIVED', data_status: 'EXISTING', authority_refs: PARENT }),

  /* ── QUARTER layer: contract states the sprint list does not name (never dropped) ── */
  Q({ state_id: 'NOT_ENROLLED', label: 'Not set up', meaning: 'No IFTA filing service for this client (public: the service offer).', maps_to: ['NOT_ENROLLED'], derivation: 'no quarter case for the organisation / service not activated', client_label: 'SET UP IFTA FILING', staff_mirror: 'CLIENT HAS NO IFTA FILING SERVICE', data_status: 'PARTIAL', authority_refs: ['PUBLIC_TABLET_DESKTOP'] }),
  Q({ state_id: 'OVERDUE_RISK', label: 'Due soon — incomplete', meaning: 'Due within 10 days and not ready.', maps_to: ['OVERDUE_RISK'], derivation: 'effectiveState() — due date within 10 days and readiness below READY_FOR_REPORTING', client_label: 'DUE {due_date} — FINISH THE QUARTER', staff_mirror: 'DEADLINE RISK — ESCALATE', data_status: 'EXISTING', authority_refs: PARENT }),
  Q({ state_id: 'FILING_REJECTED', label: 'Returned by jurisdiction', meaning: 'The base jurisdiction returned the filing; AIO is correcting it.', maps_to: ['FILING_REJECTED'], derivation: 'state FILING_REJECTED — the state exists in the contract; no AIO reducer records a rejection or opens an amendment yet', client_label: 'RETURNED BY JURISDICTION — AIO IS CORRECTING', staff_mirror: 'REJECTED — AMENDMENT REQUIRED', data_status: 'PARTIAL', authority_refs: PARENT }),

  /* ── UI layer (contract sheet §06 + sprint §17) ── */
  UI({ state_id: 'UI.DEFAULT', label: 'Default', meaning: 'Normal content with data present.', derivation: 'data loaded, no exception', authority_refs: CONTRACT_SHEET }),
  UI({ state_id: 'UI.LOADING', label: 'Loading', meaning: 'Skeletons in the panel slots; hero + tab bar stay stable.', derivation: 'read pending', authority_refs: CONTRACT_SHEET }),
  UI({ state_id: 'UI.EMPTY', label: 'Empty', meaning: 'Nothing captured yet; the panel shows the capture action.', derivation: 'zero records for the panel', client_label: 'NO FUEL PURCHASES YET. UPLOAD RECEIPTS OR IMPORT YOUR CSV FILE.', authority_refs: CONTRACT_SHEET }),
  UI({ state_id: 'UI.SUCCESS', label: 'Success', meaning: 'A write landed.', derivation: 'mutation resolved', client_label: 'RECORD VERIFIED AND SAVED.', authority_refs: CONTRACT_SHEET }),
  UI({ state_id: 'UI.WARNING', label: 'Warning / exception', meaning: 'Data outside the expected band (MPG outlier, miles without fuel, unverified source).', derivation: 'discrepancy / flag present', client_label: 'MILEAGE OUTSIDE EXPECTED RANGE. PLEASE REVIEW.', authority_refs: CONTRACT_SHEET }),
  UI({ state_id: 'UI.ERROR', label: 'Error', meaning: 'A file or write failed; nothing is dropped (unreadable files are kept with a retake request).', derivation: 'mutation / parse failure', client_label: 'FILE COULD NOT BE PROCESSED. PLEASE CHECK AND TRY AGAIN.', authority_refs: CONTRACT_SHEET }),
  UI({ state_id: 'UI.BLOCKED', label: 'Blocked', meaning: 'The next step is blocked by an upstream requirement (no IFTA account, items open, permission).', derivation: 'blockingItems() non-empty or permission denied', client_label: '{blocker}', authority_refs: PARENT }),
  UI({ state_id: 'UI.LOCKED_IN_REVIEW', label: 'Inputs locked', meaning: 'Capture tools quiet while AIO reviews / files (contract: review states quiet the inputs).', derivation: 'state ∈ INPUTS_LOCKED_STATES', client_label: 'AIO IS WORKING ON THIS — INPUTS ARE LOCKED', authority_refs: PARENT }),
  UI({ state_id: 'UI.READ_ONLY', label: 'Read only', meaning: 'Archived quarter or actor without write rights.', derivation: 'ARCHIVED or no write permission', authority_refs: PARENT }),

  /* ── RECORD layer: receipts (reference chips ↔ contract classes, decision D-RECEIPT-STATUS-MAP) ── */
  R({ state_id: 'RECEIPT.PROCESSED', label: 'Processed', meaning: 'Readable, in the quarter, jurisdiction + gallons parsed, matched to a vehicle.', maps_to: ['READY'], derivation: 'receiptClass READY (verified by staff after review)', client_label: 'PROCESSED', staff_mirror: 'READY', authority_refs: ['FUEL_PURCHASES_CHILD_PROOF', 'ICON_ASSET_SHEET'] }),
  R({ state_id: 'RECEIPT.NEEDS_REVIEW', label: 'Needs review', meaning: 'Parsed with low confidence — AIO is checking it.', maps_to: ['UNDER_AIO_REVIEW'], derivation: 'receiptClass UNDER_AIO_REVIEW', client_label: 'NEEDS REVIEW', staff_mirror: 'VERIFY', authority_refs: ['FUEL_PURCHASES_CHILD_PROOF'] }),
  R({ state_id: 'RECEIPT.MISSING_DETAILS', label: 'Missing details', meaning: 'Something only the client can answer (which truck, which state, reefer vs road fuel, missing gallons).', maps_to: ['NEEDS_YOU'], derivation: 'receiptClass NEEDS_YOU (flag.question / options)', client_label: 'MISSING DETAILS', staff_mirror: 'WAITING ON CLIENT', authority_refs: ['FUEL_PURCHASES_CHILD_PROOF'] }),
  R({ state_id: 'RECEIPT.DUPLICATE', label: 'Duplicate', meaning: 'Same station / date / amount / gallons as another receipt — held out of totals until confirmed.', maps_to: ['DUPLICATE'], derivation: 'receiptClass DUPLICATE (duplicateOfId)', client_label: 'DUPLICATE', staff_mirror: 'DUPLICATE — CONFIRM', authority_refs: ['ICON_ASSET_SHEET'] }),
  R({ state_id: 'RECEIPT.UNREADABLE', label: 'Unreadable', meaning: 'Could not be parsed — retake / re-upload requested; never dropped.', maps_to: ['UNREADABLE'], derivation: 'receiptClass UNREADABLE', client_label: 'UNREADABLE — RETAKE', staff_mirror: 'UNREADABLE — RETAKE REQUESTED', authority_refs: ['ICON_ASSET_SHEET'] }),
  R({ state_id: 'RECEIPT.POSSIBLE_MISSING', label: 'Possible missing receipt', meaning: 'Miles in a jurisdiction with no fuel, or a gap in a fueling pattern — a flag row, not a captured receipt.', maps_to: ['POSSIBLE_MISSING'], derivation: 'receiptClass POSSIBLE_MISSING with source SYSTEM_GAP · milesWithoutFuel()', client_label: 'POSSIBLE MISSING RECEIPT — {state}', staff_mirror: 'MILES WITHOUT FUEL — {state}', authority_refs: ['ICON_ASSET_SHEET'] }),

  /* ── RECORD layer: mileage (contract mileage sources) ── */
  R({ state_id: 'MILEAGE.VERIFIED', label: 'Verified', meaning: 'ELD-verified source, or staff-verified manual / spreadsheet / assisted miles.', maps_to: ['eld_verified', 'manual_verified (staffVerifiedAt)'], derivation: 'assessIftaReadiness verified-source rule', client_label: 'VERIFIED', staff_mirror: 'VERIFIED', authority_refs: ['ICON_ASSET_SHEET'] }),
  R({ state_id: 'MILEAGE.UNVERIFIED', label: 'Awaiting verification', meaning: 'Manual / spreadsheet / assisted miles waiting for staff verification.', maps_to: ['driver_reported', 'manual (no staffVerifiedAt)'], derivation: 'source needs staff verification', client_label: 'AWAITING AIO VERIFICATION', staff_mirror: 'VERIFY SOURCE', authority_refs: ['ICON_ASSET_SHEET'] }),
  R({ state_id: 'MILEAGE.ESTIMATED', label: 'Estimate', meaning: 'Load-derived estimate — visually distinct and never filed.', maps_to: ['loaded_miles'], derivation: 'LOAD_DERIVED_ESTIMATE source', client_label: 'ESTIMATE — ADD A VERIFIED SOURCE', staff_mirror: 'ESTIMATED ONLY', authority_refs: ['ICON_ASSET_SHEET'] }),
  R({ state_id: 'MILEAGE.EXCEPTION', label: 'Exception', meaning: 'Outside the expected range (MPG band) or miles without fuel.', maps_to: ['MPG_OUTLIER', 'MILES_WITHOUT_FUEL'], derivation: 'IftaDiscrepancy kinds MPG_OUTLIER · MILES_WITHOUT_FUEL', client_label: 'MILEAGE OUTSIDE EXPECTED RANGE', staff_mirror: 'DISCREPANCY — RESOLVE', authority_refs: CONTRACT_SHEET }),

  /* ── RECORD layer: vehicles ── */
  R({ state_id: 'VEHICLE.ACTIVE', label: 'In this quarter', meaning: 'Operated this quarter; needs fuel + verified miles.', maps_to: ['operated = true'], derivation: 'IftaVehicle.operated', client_label: 'RAN THIS QUARTER', staff_mirror: 'QUALIFIED', authority_refs: ['CLIENT_TABLET_DESKTOP'] }),
  R({ state_id: 'VEHICLE.NOT_OPERATED', label: 'Not operated / excluded', meaning: 'Excluded from the return (with note).', maps_to: ['operated = false'], derivation: 'IftaVehicle.operated = false + notOperatedNote', client_label: 'DID NOT RUN', staff_mirror: 'EXCLUDED — NOTE ON FILE', authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  R({ state_id: 'VEHICLE.MISSING_DATA', label: 'Missing data', meaning: 'Participation unconfirmed, or no fuel / no mileage source.', maps_to: ['operated = null', 'no mileage source'], derivation: 'vehicleReadiness()', client_label: 'NEEDS MILES', staff_mirror: 'MISSING VEHICLE DATA', authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),

  /* ── RECORD layer: jurisdictions ── */
  R({ state_id: 'JURISDICTION.OK', label: 'Data complete', meaning: 'Miles and fuel present and reconciled.', maps_to: ['no open discrepancy'], derivation: 'no open IftaDiscrepancy for the jurisdiction', client_label: 'LOOKS GOOD', staff_mirror: 'RECONCILED', authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  R({ state_id: 'JURISDICTION.EXCEPTION', label: 'Exception', meaning: 'Miles without fuel, MPG outlier or unverified mileage in this jurisdiction.', maps_to: ['open discrepancy'], derivation: 'open IftaDiscrepancy with jurisdiction', client_label: 'NEEDS ATTENTION', staff_mirror: 'REVIEW RECOMMENDED', authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),

  /* ── RECORD layer: documents ── */
  R({ state_id: 'DOC.SOURCE', label: 'Source file', meaning: 'Uploaded receipt / mileage report / CSV.', maps_to: ['receipt fileLabel', 'mileage fileLabel'], derivation: 'captured files', client_label: 'UPLOADED', staff_mirror: 'SOURCE', authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  R({ state_id: 'DOC.DRAFT', label: 'Draft return', meaning: 'Return summary prepared, not yet sent.', maps_to: ['returnSummary.preparedAt'], derivation: 'prepareReturnSummary', client_label: 'AIO PREPARING', staff_mirror: 'DRAFT', authority_refs: ['FOUNDER_STAFF_TABLET_DESKTOP'] }),
  R({ state_id: 'DOC.REVIEW_COPY', label: 'Client review copy', meaning: 'Return summary sent for approval.', maps_to: ['returnSummary.sentForApprovalAt'], derivation: 'sendForApproval', client_label: 'READY FOR YOUR REVIEW', staff_mirror: 'SENT FOR APPROVAL', authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  R({ state_id: 'DOC.APPROVED', label: 'Approved', meaning: 'Client approved the summary.', maps_to: ['returnSummary.approvedAt'], derivation: 'approveReturn', client_label: 'APPROVED', staff_mirror: 'APPROVED', authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  R({ state_id: 'DOC.FINAL', label: 'Final return + confirmation', meaning: 'Filed return and confirmation recorded.', maps_to: ['filing'], derivation: 'recordFiling', client_label: 'FILED', staff_mirror: 'FILED', authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  R({ state_id: 'DOC.SEALED', label: 'Sealed in the Vault', meaning: 'Quarter packet sealed at VAULT › TAX & FUEL › IFTA › {YYYY} › Q{n}.', maps_to: ['vault'], derivation: 'sealPacketToVault', client_label: 'IN YOUR VAULT', staff_mirror: 'SEALED', authority_refs: ['CLIENT_MOBILE_PARENT_AUTHORITY'] }),
  R({ state_id: 'DOC.SUPERSEDED', label: 'Superseded', meaning: 'A newer version replaced this record (corrected receipt, newer mileage source, revised summary, amended return).', maps_to: ['supersededById', 'revised summary'], derivation: 'IftaMileageRecord.supersededById · receipt resolution history', client_label: 'REPLACED BY NEWER VERSION', staff_mirror: 'SUPERSEDED', data_status: 'PARTIAL', authority_refs: ['PAGE_COMPONENT_INTERACTION_CONTRACT'] }),
];

/** Contract states every node tree must account for. */
export const AIO_IFTA_CONTRACT_STATE_IDS = ['NOT_ENROLLED', 'QUARTER_OPEN', 'COLLECTING', 'NEEDS_CLIENT', 'OVERDUE_RISK', 'AIO_REVIEW', 'RECONCILING', 'AWAITING_APPROVAL', 'FILING', 'FILED', 'ARCHIVED', 'FILING_REJECTED'] as const;

/** Sprint §18 client state family (order as written). */
export const AIO_IFTA_SPRINT_CLIENT_STATES = ['COLLECTING', 'NEEDS_YOU', 'READY_FOR_AIO', 'AIO_REVIEWING', 'CORRECTION_REQUIRED', 'READY_FOR_CLIENT_REVIEW', 'CLIENT_APPROVAL_PENDING', 'APPROVED_FOR_FILING', 'FILING', 'FILED', 'PAYMENT_PENDING', 'COMPLETE', 'ARCHIVED', 'NEXT_QUARTER_OPEN'] as const;

/** Reusable state bundles for nodes. */
export const QUARTER_ALL = AIO_IFTA_STATES.filter((s) => s.layer === 'QUARTER' && s.state_id !== 'NOT_ENROLLED').map((s) => s.state_id);
export const UI_CORE = ['UI.DEFAULT', 'UI.LOADING', 'UI.EMPTY', 'UI.SUCCESS', 'UI.WARNING', 'UI.ERROR'];
export const COLLECTION = ['COLLECTING', 'NEEDS_YOU', 'READY_FOR_AIO', 'CORRECTION_REQUIRED', 'OVERDUE_RISK'];
