/**
 * P0.5E.4A — Generic Founder Character Calibration constants.
 */

export const FOUNDER_CHARACTER_CALIBRATION_VERSION = 'FOUNDER_CHARACTER_CALIBRATION@P0.5E.4A' as const;

export const FOUNDER_CALIBRATION_REACTIONS = [
  'YES_THATS_HER',
  'ALMOST',
  'NO_NOT_HER',
  'IT_DEPENDS',
  'I_DONT_KNOW_YET',
] as const;

export const CALIBRATION_TRUTH_STATES = [
  'FOUNDER_CONFIRMED',
  'FOUNDER_REVISED',
  'FOUNDER_REJECTED',
  'FOUNDER_CONTEXTUAL',
  'FOUNDER_UNRESOLVED',
  'SYSTEM_INFERRED',
  'SYSTEM_HYPOTHESIS',
] as const;

export const CALIBRATION_MOMENT_TYPES = [
  'BEHAVIOR_PREDICTION',
  'INNER_THOUGHT',
  'SOCIAL_REACTION',
  'PRIVATE_MOMENT',
  'PUBLIC_REACTION',
  'VOICE_PREDICTION',
  'TEXT_MESSAGE',
  'MARGIN_NOTE',
  'BOOK_BEHAVIOR',
  'ERRATA_RESPONSE',
  'RABBIT_HOLE_BEHAVIOR',
  'RELATIONSHIP_DYNAMIC',
  'STYLE_EXPRESSION',
  'CULTURAL_BOUNDARY',
  'CONTRADICTION_TEST',
  'FLAW_STRESS_TEST',
  'SYNTHESIS_READ',
  'VISUAL_HYPOTHESIS',
] as const;

export const CALIBRATION_PROGRESS_LEVELS = ['EARLY', 'FORMING', 'STRONG'] as const;

export const CALIBRATION_PROGRESS_DOMAINS = [
  'PSYCHOLOGY',
  'VOICE',
  'CONTRADICTIONS',
  'PRIVATE_LIFE',
  'RELATIONSHIPS',
  'BOOK',
  'VISUAL_IDENTITY',
] as const;

export const FOUNDER_COGNITIVE_LOAD_MUST_REMAIN_LOW = true as const;

export const STUDIO_WORLD_GENERIC_CALIBRATION_IMPLEMENTED = true as const;
export const FOUNDER_DISCOVERY_IS_CALIBRATION_NOT_SURVEY = true as const;
export const SYSTEM_PROPOSES_BEFORE_FOUNDER_CREATES = true as const;
export const FOUNDER_COGNITIVE_LOAD_REDUCED = true as const;
export const ABSTRACT_TRAITS_NOT_PRIMARY_FOUNDER_QUESTIONS = true as const;
export const SYSTEM_SEEDED_METADATA_HIDDEN_FROM_PRIMARY_UX = true as const;
export const SCENARIOS_INCLUDE_SYSTEM_PREDICTION = true as const;
export const FOUNDER_REACTION_UPDATES_CHARACTER_MODEL = true as const;
export const FOUNDER_REVISION_AFFECTS_NEXT_PROPOSITION = true as const;
export const FOUNDER_REJECTION_AFFECTS_NEXT_PROPOSITION = true as const;
export const IT_DEPENDS_CREATES_CONTEXTUAL_TRUTH = true as const;
export const I_DONT_KNOW_PRESERVES_UNRESOLVED_STATE = true as const;
export const NEXT_BEST_QUESTION_IS_ADAPTIVE = true as const;
export const QUESTION_ORDER_IS_NOT_STATIC = true as const;
export const FOUNDER_FATIGUE_COST_IMPLEMENTED = true as const;
export const REDUNDANT_QUESTIONS_SUPPRESSED = true as const;
export const MULTI_DIMENSION_INFERENCE_IMPLEMENTED = true as const;
export const DIRECT_AND_INFERRED_TRUTH_REMAIN_DISTINCT = true as const;
export const FOUNDER_JUDGMENT_PROVENANCE_PRESERVED = true as const;
export const CONTRADICTIONS_DISCOVERED_BEHAVIORALLY = true as const;
export const FLAWS_DISCOVERED_BEHAVIORALLY = true as const;
export const INTELLIGENCE_DISCOVERED_BEHAVIORALLY = true as const;
export const VOICE_CALIBRATION_IMPLEMENTED = true as const;
export const BOOK_RELATIONSHIP_CALIBRATION_IMPLEMENTED = true as const;
export const VISUAL_HYPOTHESES_CLUSTERED_FOR_CALIBRATION = true as const;
export const CALIBRATION_MEMORY_PRESERVED = true as const;
export const SYSTEM_DOES_NOT_FORGET_FOUNDER_DISTINCTIONS = true as const;
export const DISCONFIRMING_SCENARIOS_SUPPORTED = true as const;
export const YES_MACHINE_CONVERGENCE_BLOCKED = true as const;
export const SHORT_CALIBRATION_SESSIONS_SUPPORTED = true as const;
export const CALIBRATION_STATE_VERSIONED = true as const;
export const SYNTHESIS_PREVIEW_HUMAN_READABLE = true as const;
export const FOUNDER_I_KNOW_HER_GATE_PRESERVED = true as const;
export const CASTING_NOT_AUTOMATICALLY_TRIGGERED = true as const;
export const FAL_GENERATION_NOT_TRIGGERED_BY_CALIBRATION = true as const;
