/**
 * Generic Studio World — campaign caption synthesis.
 */

export const CAMPAIGN_CAPTION_SYSTEM_V1 = 'CAMPAIGN_CAPTION_SYSTEM_V1' as const;

export const CAPTION_READINESS_STATES = [
  'NOT_READY',
  'DRAFT_ELIGIBLE',
  'FINAL_CAPTION_READY',
] as const;

export const CAPTION_LENGTHS = ['MICRO', 'SHORT', 'MEDIUM', 'LONG', 'SOURCE_HEAVY'] as const;

export const CAPTION_SHAPES = [
  'ONE_LINER',
  'SHORT_REACTION',
  'SHORT_WITH_AFTERTHOUGHT',
  'CONVERSATIONAL',
  'EVIDENCE_NOTE',
  'STORY_EXTENSION',
  'CALLBACK',
  'SELF_CORRECTION',
  'QUESTION',
  'LONGER_CONTEXT',
  'SOURCE_NOTE',
  'MIXED',
] as const;

export const CAPTION_OPENING_STRATEGIES = [
  'CONTINUE_THE_THOUGHT',
  'AFTERTHOUGHT',
  'SIDE_COMMENT',
  'CONTEXT_DROP',
  'REACTION',
  'CALLBACK',
  'QUESTION',
  'EVIDENCE_NOTE',
  'REPEAT_HEADLINE_ONLY_IF_STRATEGIC',
] as const;

export const CAPTION_CTA_OPTIONS = [
  'NO_CTA',
  'OPEN_QUESTION',
  'SPECIFIC_QUESTION',
  'SAVE_THIS',
  'SEND_THIS',
  'TELL_ME_IF_IM_WRONG',
  'WHAT_DID_I_MISS',
  'COMPARE_EXPERIENCE',
  'COME_BACK_LATER',
  'WATCH_THIS',
  'FOLLOW_THE_RECEIPT',
] as const;

export const CAPTION_APPROVAL_STATES = [
  'NOT_STARTED',
  'DRAFT',
  'FOUNDER_REVIEW',
  'APPROVED',
  'STALE_RECOMPILE_REQUIRED',
] as const;

export const CAPTION_FOUNDER_JUDGMENTS = [
  'THAT_SOUNDS_LIKE_ME',
  'LOVE_THE_CAPTION',
  'TOO_POLISHED',
  'TOO_BRAND_LIKE',
  'TOO_ANALYTICAL',
  'TOO_LONG',
  'TOO_SHORT',
  'TOO_SERIOUS',
  'TOO_TRY_HARD',
  'NOT_FUNNY_ENOUGH',
  'WRONG_JOKE',
  'TOO_MUCH_JOKE',
  'NEEDS_MORE_CONTEXT',
  'DONT_REPEAT_THE_SLIDES',
  'MAKE_IT_MORE_PERSONAL',
  'MAKE_IT_MORE_DIRECT',
  'WRONG_CTA',
  'NO_CTA',
  'NEEDS_SOURCES',
  'NOT_NDX',
] as const;

export const CAPTION_FAILURE_STATES = [
  'FAIL_CAPTION_SUMMARIZES_SLIDES',
  'FAIL_CAPTION_GENERIC_SOCIAL',
  'FAIL_CAPTION_WRONG_PERSON',
  'FAIL_CAPTION_WRONG_CHARACTER',
  'FAIL_CAPTION_REPEATS_HEADLINE',
  'FAIL_CAPTION_UNSUPPORTED_CLAIM',
  'FAIL_CAPTION_STALE_CURRENT_CONTEXT',
  'FAIL_CAPTION_GENERIC_CTA',
  'FAIL_CAPTION_ENGAGEMENT_BAIT',
  'FAIL_CAPTION_OVEREXPLAINS',
  'FAIL_CAPTION_NOT_READY',
] as const;

export const GENERIC_ENGAGEMENT_BAIT = [
  'COMMENT BELOW',
  'LIKE AND SHARE',
  'FOLLOW FOR MORE',
  'DOUBLE TAP',
  'TAG A FRIEND',
] as const;

export const CAMPAIGN_CAPTION_SYSTEM_IMPLEMENTED = true as const;
export const CAPTION_READINESS_IMPLEMENTED = true as const;
export const CAPTION_CHARACTER_AUTHORITY_IMPLEMENTED = true as const;
export const FOUNDER_LANGUAGE_CAPTION_AUTHORITY_IMPLEMENTED = true as const;
export const CAPTION_SEQUENCE_RELATIONSHIP_IMPLEMENTED = true as const;
export const CAPTION_CURRENTNESS_GATE_IMPLEMENTED = true as const;
export const CAPTION_CTA_SYSTEM_IMPLEMENTED = true as const;
export const CAPTION_REVISION_LINEAGE_IMPLEMENTED = true as const;
export const CROSS_PLATFORM_CAPTION_INDEPENDENCE_PRESERVED = true as const;
