/**
 * P0.VR.3D — SITE 00 manifest reconciliation constants.
 */

export const P0_VR_3D_LINEAGE = 'P0.VR.3D' as const;

/** Active manifest authority is v2+; P0.VR.3A v1 is historical only. */
export const P0_VR_3A_V1_ACTIVE_AUTHORITY = false as const;

export const P0_VR_3D_FAILURE_CODES = [
  'FAIL_SITE00_V1_MANIFEST_REACTIVATED',
  'FAIL_SITE00_V2_ROUTE_DATA_OVERWRITTEN',
  'FAIL_SITE00_SELF_AUDIT_DATA_DISCARDED',
  'FAIL_SITE00_ROUTE_COUNTS_CONFLATED',
  'FAIL_SITE00_PRIMARY_SCREEN_SET_HARDCODED',
  'FAIL_SITE00_HOST_TOOL_EXPOSED_AS_WEBSITE_PAGE',
  'FAIL_SITE00_MISSING_ROUTE_DUPLICATED',
  'FAIL_SITE00_VISUAL_STATE_DUPLICATED_AS_ROUTE',
  'FAIL_SITE00_BACKGROUND_COUNTED_AS_PAGE_REFERENCE',
  'FAIL_SITE00_RECONCILIATION_CONFLICT_SILENTLY_RESOLVED',
  'FAIL_P0_VR_3C_RECEIVES_CONFLICTING_SITE00_AUTHORITY',
] as const;
