"""Write src/projects/jurnl/runtime/layout/rootAuthorityLayout.ts from $ROOTS_WORK/layout/<screen>.json and <screen>_boxes.json."""
import json, os, sys
from refs import ROOT, WORK
SCREENS=sys.argv[1:] or ['today','money','plan','credit']
L=os.path.join(WORK,'layout')
OUT=os.path.join(ROOT,'src','projects','jurnl','runtime','layout','rootAuthorityLayout.ts')
def num(v): return int(v) if float(v).is_integer() else round(float(v),2)
def text(t):
    keys=['family','weight','size','ls','top','left','cx','right','rot','ink']
    parts=[]
    for k in keys:
        if k not in t: continue
        v=t[k]
        if k=='family': parts.append(f"family: '{v}'")
        elif k=='ink': parts.append(f"ink: [{', '.join(str(num(x)) for x in v)}]")
        else: parts.append(f'{k}: {num(v)}')
    return '{ '+', '.join(parts)+' }'
lines=['/* Generated by scripts/jurnl/root-authorities/emit_ts.py — do not edit by hand.',
       '   Measured type and marks of the four root references (JURNL/ROOT_PARENTS_REFERENCE_PLUS_SHELL1/REFERENCES).',
       '   Wall frames are reference px (941 × 1672). Object frames are the straightened copies in straight.py (local px). */',
       "import type { RefBox, RefType } from './referenceLayout';",'']
for s in SCREENS:
    tj=json.load(open(os.path.join(L,f'{s}.json'))); bj=json.load(open(os.path.join(L,f'{s}_boxes.json')))
    lines.append(f'export const RA_{s.upper()} = {{')
    for frame in tj:
        key=frame.replace(f'{s}_','') if frame!=s else 'wall'
        lines.append(f'  {key}: {{')
        lines.append('    box: {')
        for k,v in bj.get(frame,{}).items(): lines.append(f'      {k}: [{", ".join(str(num(x)) for x in v)}],')
        lines.append('    },')
        lines.append('    text: {')
        for k,v in tj[frame].items(): lines.append(f'      {k}: {text(v)},')
        lines.append('    },')
        lines.append('  },')
    lines.append('} as const satisfies Record<string, { box: Record<string, RefBox>; text: Record<string, RefType> }>;')
    lines.append('')
open(OUT,'w').write('\n'.join(lines))
print('wrote',OUT)
