/**
 * ENTRY v2 first seven pages: live layout measured from the approved authorities (frame 1008 × 1792).
 * Generated by scripts/jurnl/entry-v2/measure.py — do not edit by hand.
 */
import type { RefBox, RefType } from './referenceLayout';

export type EntrySurfaceId = string;
export type EntryType = RefType & { readonly surface?: EntrySurfaceId };

export const ENTRY_V2_WELCOME = {
  focal: [0.9, 0.5],
  ui: [64, 112, 733, 1716] as RefBox,
  surfaces: {},
  box: {
    sprig: [72, 112, 132, 178],
    rule: [72, 806, 385, 808],
    getStarted: [64, 1519, 373, 1608],
    signIn: [64, 1622, 373, 1716],
  } satisfies Record<string, RefBox>,
  text: {
    brand: { family: 'serif', weight: 400, size: 35, ls: 9.33, top: 118, left: 164, ink: [163, 125, 304, 156] },
    brandLine: { family: 'serif', weight: 400, size: 17.4, ls: 1.04, top: 181.8, left: 72, ink: [72, 185, 468, 202] },
    h1: { family: 'serif', weight: 400, size: 116, ls: -6.57, top: 243.5, left: 66, ink: [65, 266, 605, 353] },
    h2: { family: 'serif', weight: 400, size: 116, ls: -8.17, top: 349.5, left: 66, ink: [70, 372, 468, 471] },
    h3: { family: 'serif', weight: 400, size: 116, ls: -10.43, top: 451.5, left: 66, ink: [70, 474, 361, 560] },
    h4: { family: 'serif', weight: 400, size: 116, ls: -9.22, top: 556.5, left: 66, ink: [70, 579, 733, 664] },
    h5: { family: 'serif', weight: 400, size: 116, ls: -8.79, top: 657.5, left: 67, ink: [66, 680, 291, 765] },
    tag1: { family: 'serif', weight: 400, size: 30, ls: 6.56, top: 830, left: 72, ink: [73, 835, 321, 858] },
    tag2: { family: 'serif', weight: 400, size: 30, ls: 6.75, top: 870, left: 71, ink: [72, 875, 353, 898] },
    getStarted: { family: 'serif', weight: 400, size: 30.8, ls: 1.31, top: 1547.1, cx: 219.29, ink: [113, 1552, 324, 1574] },
    signIn: { family: 'serif', weight: 400, size: 31.2, ls: 1.09, top: 1652.4, cx: 218.56, ink: [160, 1658, 276, 1681] },
  } satisfies Record<string, EntryType>,
} as const;

export const ENTRY_V2_VALUE = {
  focal: [0.6, 0.5],
  ui: [34, 333, 766, 1630] as RefBox,
  surfaces: {},
  box: {
    cont: [65, 1525, 502, 1630],
  } satisfies Record<string, RefBox>,
  text: {
    h1: { family: 'serif', weight: 600, size: 217, ls: -10.58, top: 289, left: 62, ink: [59, 333, 671, 488] },
    h2: { family: 'serif', weight: 600, size: 217, ls: 4.87, top: 506, left: 39, ink: [34, 551, 712, 735] },
    h3: { family: 'serif', weight: 600, size: 217, ls: -15.48, top: 719, left: 53, ink: [60, 761, 699, 923] },
    b1: { family: 'serif', weight: 600, size: 51, ls: -2.01, top: 1088.5, left: 64, ws: 12, ink: [63, 1098, 573, 1137] },
    b2: { family: 'serif', weight: 600, size: 51, ls: -3.23, top: 1147.5, left: 60, ws: 12, ink: [62, 1157, 466, 1194] },
    b3: { family: 'serif', weight: 600, size: 51, ls: -3.01, top: 1209.5, left: 64, ws: 12, ink: [63, 1219, 670, 1257] },
    b4: { family: 'serif', weight: 600, size: 51, ls: -1.52, top: 1269.5, left: 63, ws: 12, ink: [62, 1279, 766, 1323] },
    b5: { family: 'serif', weight: 600, size: 51, ls: -2.57, top: 1330.5, left: 64, ws: 12, ink: [63, 1340, 467, 1379] },
    cont: { family: 'serif', weight: 600, size: 46.2, ls: 1.36, top: 1554.9, cx: 285.11, ink: [161, 1563, 408, 1596] },
  } satisfies Record<string, EntryType>,
} as const;

export const ENTRY_V2_BENEFITS = {
  focal: [0.5, 0.5],
  ui: [79, 88, 740, 1658] as RefBox,
  surfaces: {olive: 'matrix3d(0.98822838, 0.15298584, 0, 0, -0.15298584, 0.98822838, 0, 0, 0, 0, 1, 0, 75.082584, -75.785265, 0, 1)', slip1: 'matrix3d(0.99834182, 0.057564027, 0, 0, -0.057564027, 0.99834182, 0, 0, 0, 0, 1, 0, 40.564852, -28.213507, 0, 1)', slip2: 'matrix3d(0.99926292, -0.038387809, 0, 0, 0.038387809, 0.99926292, 0, 0, 0, 0, 1, 0, -33.781867, 20.617665, 0, 1)', slip3: 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)', slip4: 'matrix3d(0.99718513, -0.074978727, 0, 0, 0.074978727, 0.99718513, 0, 0, 0, 0, 1, 0, -95.774464, 38.885254, 0, 1)'},
  box: {
    cont: [298, 1515, 740, 1658],
  } satisfies Record<string, RefBox>,
  text: {
    brand: { family: 'serif', weight: 600, size: 125.8, ls: 4.3, top: 63.1, left: 82, ink: [79, 88, 478, 200] },
    o1: { family: 'serif', weight: 400, size: 49, ls: 3.64, top: 412, left: 357, surface: 'olive', ink: [356, 422, 686, 463] },
    o2: { family: 'serif', weight: 400, size: 49, ls: 2.06, top: 470, left: 358, surface: 'olive', ink: [360, 479, 736, 516] },
    s1a: { family: 'serif', weight: 500, size: 44.8, ls: 1.15, top: 633.1, left: 333, surface: 'slip1', ink: [335, 641, 616, 675] },
    s1b: { family: 'serif', weight: 500, size: 44.8, ls: 0.1, top: 686.1, left: 334, surface: 'slip1', ink: [336, 694, 678, 727] },
    s2a: { family: 'serif', weight: 500, size: 44.8, ls: 0.18, top: 844.1, left: 320, surface: 'slip2', ink: [321, 852, 609, 878] },
    s2b: { family: 'serif', weight: 500, size: 44.8, ls: 0.18, top: 892.1, left: 320, surface: 'slip2', ink: [319, 900, 725, 929] },
    s3a: { family: 'serif', weight: 500, size: 44.8, ls: 0.13, top: 1046.1, left: 302, surface: 'slip3', ink: [304, 1054, 709, 1088] },
    s3b: { family: 'serif', weight: 500, size: 44.8, ls: 1.25, top: 1097.1, left: 305, surface: 'slip3', ink: [304, 1106, 474, 1138] },
    s4a: { family: 'serif', weight: 500, size: 44.8, ls: -1.42, top: 1237.1, left: 283, surface: 'slip4', ink: [285, 1245, 470, 1277] },
    s4b: { family: 'serif', weight: 500, size: 44.8, ls: -1.11, top: 1284.1, left: 287, surface: 'slip4', ink: [288, 1292, 648, 1327] },
    cont: { family: 'serif', weight: 400, size: 35.7, ls: 6.19, top: 1557.15, cx: 514.46, ink: [400, 1564, 623, 1590] },
  } satisfies Record<string, EntryType>,
} as const;

export const ENTRY_V2_BEGIN = {
  focal: [0.62, 0.5],
  ui: [83, 252, 745, 1389] as RefBox,
  surfaces: {card: 'matrix3d(0.73656426, -0.21831803, 0, -0.00019967063, -0.0090879688, 0.86260504, 0, -1.4574731e-05, 0, 0, 1, 0, 83.65865, 133.71065, 0, 1)'},
  box: {
    getStarted: [472, 1212, 744, 1283],
    signIn: [472, 1302, 744, 1372],
  } satisfies Record<string, RefBox>,
  text: {
    brand: { family: 'serif', weight: 400, size: 35.6, ls: 25.74, top: 245.2, left: 84, ink: [83, 252, 291, 278] },
    h: { family: 'serif', weight: 500, size: 134, ls: 1.25, top: 365.5, left: 79, ink: [84, 391, 516, 490] },
    sub: { family: 'serif', weight: 400, size: 23.1, ls: 4.23, top: 520.95, left: 84, ink: [83, 525, 566, 542] },
    getStarted: { family: 'serif', weight: 400, size: 21.3, ls: 3.6, top: 1236.35, cx: 611, surface: 'card', ink: [523, 1240, 696, 1256] },
    signIn: { family: 'serif', weight: 400, size: 21.3, ls: 3.32, top: 1326.35, cx: 610.68, surface: 'card', ink: [562, 1330, 657, 1346] },
  } satisfies Record<string, EntryType>,
} as const;

export const ENTRY_V2_CREATE = {
  focal: [0.5, 0.5],
  ui: [158, 260, 903, 1640] as RefBox,
  surfaces: {sheet: 'matrix3d(0.99949554, -0.031759651, 0, 0, 0.031759651, 0.99949554, 0, 0, 0, 0, 1, 0, -28.316319, 17.286633, 0, 1)'},
  box: {
    firstRule: [165, 789, 865, 791],
    lastRule: [165, 906, 865, 908],
    emailRule: [165, 1022, 865, 1024],
    passwordRule: [165, 1139, 865, 1141],
    check: [167, 1184, 198, 1215],
    apple: [162, 1263, 512, 1348],
    appleIcon: [202, 1287, 230, 1322],
    google: [532, 1265, 883, 1350],
    googleIcon: [563, 1292, 598, 1326],
    submit: [162, 1375, 885, 1465],
  } satisfies Record<string, RefBox>,
  text: {
    brand: { family: 'serif', weight: 400, size: 34.4, ls: 18.19, top: 256.8, cx: 526.21, surface: 'sheet', ink: [429, 263, 604, 294] },
    h1: { family: 'serif', weight: 400, size: 85.6, ls: -0.86, top: 350.2, cx: 518.14, surface: 'sheet', ink: [364, 367, 674, 430] },
    h2a: { family: 'serif', weight: 400, size: 85.6, ls: -0.97, top: 438.2, left: 202, surface: 'sheet', ink: [201, 455, 426, 520] },
    h2b: { family: 'serif', weight: 400, size: 85.6, ls: -5.03, top: 433.2, left: 446, surface: 'sheet', ink: [445, 450, 829, 516] },
    sub1: { family: 'serif', weight: 400, size: 27, ls: 8.38, top: 558.5, cx: 523.48, surface: 'sheet', ink: [371, 563, 666, 584] },
    sub2: { family: 'serif', weight: 400, size: 27, ls: 8.97, top: 600.5, cx: 524.89, surface: 'sheet', ink: [345, 605, 695, 627] },
    first: { family: 'serif', weight: 400, size: 19.6, ls: 4.13, top: 719.2, left: 164, surface: 'sheet', ink: [164, 722, 313, 737] },
    last: { family: 'serif', weight: 400, size: 19.6, ls: 4.1, top: 836.2, left: 165, surface: 'sheet', ink: [165, 839, 303, 853] },
    email: { family: 'serif', weight: 400, size: 19.6, ls: 4.16, top: 951.2, left: 167, surface: 'sheet', ink: [167, 954, 366, 969] },
    password: { family: 'serif', weight: 400, size: 19.6, ls: 3.99, top: 1072.2, left: 166, surface: 'sheet', ink: [167, 1075, 403, 1090] },
    agree: { family: 'serif', weight: 400, size: 16.2, ls: 2.59, top: 1190.9, left: 223, surface: 'sheet', ink: [223, 1194, 793, 1208] },
    apple: { family: 'serif', weight: 400, size: 16.6, ls: 1.53, top: 1296.7, left: 257, surface: 'sheet', ink: [257, 1300, 470, 1313] },
    google: { family: 'serif', weight: 400, size: 16.6, ls: 1.59, top: 1299.7, left: 623, surface: 'sheet', ink: [623, 1303, 857, 1317] },
    submit: { family: 'serif', weight: 400, size: 24.6, ls: 4.09, top: 1410.2, cx: 520.18, surface: 'sheet', ink: [385, 1415, 652, 1436] },
    foot: { family: 'serif', weight: 400, size: 16.2, ls: 3.64, top: 1511.9, cx: 516.86, surface: 'sheet', ink: [308, 1514, 721, 1531] },
  } satisfies Record<string, EntryType>,
} as const;

export const ENTRY_V2_VERIFY = {
  focal: [0.7, 0.5],
  ui: [60, 94, 680, 800] as RefBox,
  surfaces: {},
  box: {
    open: [75, 535, 502, 622],
    resend: [75, 640, 502, 727],
    differentRule: [80, 781, 383, 783],
  } satisfies Record<string, RefBox>,
  text: {
    brand: { family: 'serif', weight: 400, size: 31, ls: 11.44, top: 87.5, left: 76, ink: [75, 94, 213, 117] },
    h1: { family: 'serif', weight: 500, size: 108, ls: -10.95, top: 183, left: 62, ink: [67, 204, 392, 282] },
    h2: { family: 'serif', weight: 500, size: 108, ls: -6.02, top: 280, left: 71, ink: [70, 301, 680, 380] },
    lead: { family: 'serif', weight: 400, size: 26.4, ls: 4.12, top: 410.8, left: 76, ink: [75, 415, 625, 434] },
    address: { family: 'serif', weight: 400, size: 26.4, ls: 3.96, top: 448.8, left: 76, ink: [75, 453, 431, 472] },
    open: { family: 'serif', weight: 400, size: 29.1, ls: 3.49, top: 563.45, cx: 288.75, ink: [150, 569, 425, 590] },
    resend: { family: 'serif', weight: 400, size: 27.1, ls: 3.23, top: 670.45, cx: 289.58, ink: [175, 675, 402, 695] },
    different: { family: 'serif', weight: 400, size: 21.9, ls: 2.39, top: 756.55, left: 81, ink: [81, 761, 383, 777] },
  } satisfies Record<string, EntryType>,
} as const;

export const ENTRY_V2_SIGNIN = {
  focal: [0.56, 0.5],
  ui: [292, 520, 836, 1420] as RefBox,
  surfaces: {card: 'matrix3d(0.91938791, -0.046789371, 0, -5.3497766e-05, -0.01123018, 0.93955425, 0, -1.8977384e-05, 0, 0, 1, 0, 25.80036, 39.392056, 0, 1)'},
  box: {
    emailRule: [296, 913, 828, 915],
    passwordRule: [296, 1028, 828, 1030],
    submit: [293, 1088, 834, 1208],
  } satisfies Record<string, RefBox>,
  text: {
    brand: { family: 'serif', weight: 400, size: 26.6, ls: 15.05, top: 513.7, cx: 570.84, surface: 'card', ink: [493, 519, 632, 540] },
    h1: { family: 'serif', weight: 400, size: 105, ls: -7.4, top: 575.5, cx: 570.77, surface: 'card', ink: [333, 596, 810, 674] },
    h2: { family: 'serif', weight: 400, size: 105, ls: -4.45, top: 671.5, cx: 573.51, surface: 'card', ink: [440, 692, 709, 769] },
    emailLabel: { family: 'sans', weight: 400, size: 18.8, ls: 4.94, top: 860.1, left: 297, surface: 'card', ink: [298, 862, 492, 877] },
    passwordLabel: { family: 'sans', weight: 400, size: 18.8, ls: 4.63, top: 977.1, left: 298, surface: 'card', ink: [299, 979, 429, 993] },
    submit: { family: 'serif', weight: 400, size: 30.2, ls: 9.4, top: 1129.4, cx: 569.86, surface: 'card', ink: [484, 1135, 647, 1158] },
    forgot: { family: 'sans', weight: 400, size: 18.3, ls: 4.69, top: 1254.35, cx: 567.44, surface: 'card', ink: [440, 1256, 691, 1270] },
    create: { family: 'sans', weight: 400, size: 18.3, ls: 5.36, top: 1317.35, cx: 566.93, surface: 'card', ink: [453, 1319, 676, 1333] },
  } satisfies Record<string, EntryType>,
} as const;
