/**
 * P0.5E.4B — Generic Embodied Character Voice constants.
 */

export const EMBODIED_CHARACTER_VOICE_VERSION = 'EMBODIED_CHARACTER_VOICE@P0.5E.4B.1' as const;

export const CHARACTER_VOICE_PROVIDER_AUTHORITY = [
  'DEV_PLACEHOLDER',
  'CALIBRATION_CAPABLE',
  'PRODUCTION_CANDIDATE',
  'CANONICAL_IDENTITY_CAPABLE',
  'UNSUPPORTED',
] as const;

export const VOICE_CASTING_MODES = ['NEURAL', 'DEV_PLACEHOLDER'] as const;

export const HUMAN_WOMAN_TEST_RESPONSES = [
  'YES_SOUNDS_HUMAN',
  'MOSTLY_HUMAN',
  'NO_SOUNDS_SYNTHETIC',
] as const;

export const NEURAL_NATURALNESS_FAILURES = [
  'FAIL_ROBOTIC_TTS',
  'FAIL_AI_ASSISTANT_VOICE',
  'FAIL_OVER_ENUNCIATED',
  'FAIL_SYNTHETIC_FEMININITY',
  'FAIL_UNNATURAL_PAUSES',
  'FAIL_FLAT_PROSODY',
  'FAIL_OVERACTED_PERFORMANCE',
] as const;

export const NEURAL_CASTING_SAME_LINE_OPTIONS = [
  'WAIT. NO, BECAUSE THAT ACTUALLY DOES NOT MAKE SENSE.',
  'GIRL... LOOK AT THIS.',
  'OKAY. I WAS WRONG. BUT WAIT UNTIL YOU SEE WHY.',
] as const;

export const DEFAULT_NEURAL_CASTING_LINE = NEURAL_CASTING_SAME_LINE_OPTIONS[0]!;

export const VOICE_CALIBRATION_ROUND_TYPES = [
  'BROAD_CASTING',
  'IDENTITY_NARROWING',
  'CADENCE_TEXTURE',
  'PERFORMANCE_RANGE',
  'UNSEEN_LINE_RECOGNITION',
  'PLATFORM_RECOGNITION',
  'FINAL_RECOGNITION',
] as const;

export const VOICE_CALIBRATION_ROUND_STATUSES = [
  'PENDING',
  'GENERATING',
  'READY_FOR_JUDGMENT',
  'JUDGMENTS_COMPLETE',
  'ADAPTED',
] as const;

export const FOUNDER_VOICE_JUDGMENTS = [
  'YES_THATS_HER',
  'CLOSE',
  'NO_NOT_HER',
  'SURPRISINGLY_YES',
  'TOO_YOUNG',
  'TOO_OLD',
  'TOO_POLISHED',
  'TOO_PERFORMATIVE',
  'TOO_INFLUENCER',
  'TOO_SERIOUS',
  'TOO_PLAYFUL',
  'TOO_SOFT',
  'TOO_HARD',
  'TOO_GENERIC',
  'TOO_FAST',
  'TOO_SLOW',
  'WRONG_ENERGY',
  'VOICE_RIGHT_PERFORMANCE_WRONG',
  'HUMAN_WRONG_CHARACTER',
  'RIGHT_CHARACTER_TOO_SYNTHETIC',
  'CUSTOM',
] as const;

export const PAIRWISE_VOICE_PREFERENCES = [
  'PREFER_A',
  'PREFER_B',
  'SOMETHING_BETWEEN',
  'EACH_HAS_SOMETHING',
  'A_VOICE_B_ENERGY',
  'B_VOICE_A_CADENCE',
  'CUSTOM',
] as const;

export const VOICE_TRUTH_EVIDENCE_TYPES = [
  'FOUNDER_SELECTED_AUDIO',
  'FOUNDER_REJECTED_AUDIO',
  'FOUNDER_CLOSE_AUDIO',
  'FOUNDER_COMMENT',
  'SYSTEM_INFERRED_VOCAL_TRAIT',
  'SYSTEM_HYPOTHESIS',
  'PROVIDER_SETTING',
  'VOICE_IDENTITY_CANON',
] as const;

export const VOICE_IDENTITY_STATUSES = [
  'FORMING',
  'EMERGING',
  'CANDIDATE',
  'APPROVED',
  'REJECTED',
  'MIGRATION_REVIEW',
] as const;

export const VOICE_PERFORMANCE_STATES = [
  'PLAYFUL',
  'SKEPTICAL',
  'ANNOYED',
  'AMUSED',
  'TRYING_NOT_TO_LAUGH',
  'GENUINELY_SURPRISED',
  'SERIOUS',
  'TIRED',
  'EXCITED',
  'EMBARRASSED',
  'SELF_CORRECTING',
  'CURIOUS',
  'QUIET',
  'DIRECT',
  'FRUSTRATED',
  'CONFIDENT',
  'VULNERABLE',
  'MATTER_OF_FACT',
  'NEUTRAL',
] as const;

export const VOICE_HYPOTHESIS_STATUSES = [
  'GENERATED',
  'JUDGED',
  'PROMOTED',
  'REJECTED',
  'ARCHIVED',
] as const;

export const VOICE_INFERRED_TRAITS = [
  'UNDERSTATED_CONFIDENCE',
  'DRY_AMUSEMENT',
  'NATURAL_CONVERSATIONAL_TEXTURE',
  'LOW_REGISTER_WARMTH',
  'MEDIUM_LOW_EXPRESSIVENESS',
  'MEASURED_CADENCE',
  'QUICK_COGNITIVE_RHYTHM',
  'HIGH_ENERGY_SOCIAL_HOST',
  'POLISHED_DELIVERY',
  'SOFT_PRESENCE',
  'ASSERTIVE_PRESENCE',
  'COOL_TONE',
  'WARM_TONE',
  'DRY_DELIVERY',
  'PLAYFUL_DELIVERY',
] as const;

export const VOICE_RECOGNITION_ANCHOR_TYPES = [
  'SENTENCE_ENTRY',
  'PAUSE_RHYTHM',
  'DRYNESS',
  'VOCAL_WARMTH',
  'CADENCE',
  'REGISTER',
  'REACTION_TIMING',
  'LAUGH_BEHAVIOR',
  'WORD_EMPHASIS',
  'SPEECH_ACCELERATION',
  'SENTENCE_FALLOFF',
  'CONVERSATIONAL_LOOSENESS',
] as const;

export const VOICE_PAUSE_BEHAVIORS = [
  'THOUGHT_PAUSE',
  'DISBELIEF_PAUSE',
  'COMEDIC_PAUSE',
  'SELF_CORRECTION_PAUSE',
  'SEARCHING_FOR_WORD_PAUSE',
  'EVIDENCE_REVIEW_PAUSE',
  'EMOTIONAL_PAUSE',
] as const;

export const VOICE_LAUGH_BEHAVIORS = [
  'QUIET_LAUGH',
  'SHORT_INCREDULOUS_LAUGH',
  'FULL_LAUGH',
  'LAUGH_WHILE_SPEAKING',
  'SUPPRESSED_LAUGH',
  'LAUGH_AFTER_WRONG',
  'NO_LAUGH_FACIAL_ONLY',
] as const;

export const VOICE_PROVIDER_ENDPOINT_CLASSES = [
  'VOICE_DESIGN',
  'TEXT_TO_SPEECH',
  'REFERENCE_VOICE',
  'VOICE_CONSISTENCY',
  'SPEECH_TO_SPEECH',
  'AUDIO_EDIT',
  'VOICE_TRAINING',
] as const;

export const VOICE_MIGRATION_OUTCOMES = [
  'EQUIVALENT',
  'CLOSE_FOUNDER_REVIEW_REQUIRED',
  'IDENTITY_DRIFT',
  'NO_SAFE_MIGRATION',
] as const;

export const VOICE_CONTINUITY_FAILURES = [
  'FAIL_VOICE_IDENTITY_DRIFT',
  'FAIL_VOCAL_AGE_DRIFT',
  'FAIL_REGISTER_DRIFT',
  'FAIL_CADENCE_DRIFT',
  'FAIL_ACCENT_DRIFT',
  'FAIL_PERFORMANCE_OUTSIDE_ENVELOPE',
  'FAIL_GENERIC_AI_NARRATOR',
  'FAIL_INFLUENCER_VOICE_COLLAPSE',
  'FAIL_CHARACTER_VOICE_NOT_RECOGNIZABLE',
  'FAIL_LANGUAGE_VOICE_CONFLATION',
  'FAIL_RANDOM_VOICE_PER_GENERATION',
  'FAIL_FINALIZED_FROM_SINGLE_LINE',
  'FAIL_FINALIZED_FROM_SINGLE_EMOTION',
  'FAIL_UNSEEN_LINE_RECOGNITION',
  'FAIL_CROSS_EMOTION_RECOGNITION',
  'FAIL_VOICE_IDENTITY_PERFORMANCE_CONFLATION',
  'FAIL_PROVIDER_CHANGE_RECAST',
  'FAIL_CULTURAL_CARICATURE',
  'FAIL_FORCED_DIALECT',
  'FAIL_REAL_PERSON_IMPERSONATION',
  'FAIL_UNAUTHORIZED_VOICE_CLONE',
  'FAIL_VOICE_NOT_PERSISTED',
  'FAIL_AUDIOVISUAL_CHARACTER_MISMATCH',
] as const;

export const FOUNDER_VOICE_RECOGNITION_RESPONSES = [
  'YES_THATS_HER_VOICE',
  'ALMOST_KEEP_CALIBRATING',
  'NO_WE_LOST_HER',
] as const;

export const UNSEEN_LINE_RECOGNITION_RESPONSES = [
  'YES_STILL_HER',
  'MOSTLY',
  'NO_SHE_DISAPPEARED',
] as const;

export const AUDIOVISUAL_COHERENCE_RESPONSES = [
  'THATS_HER',
  'VOICE_DOESNT_MATCH_FACE',
  'FACE_DOESNT_MATCH_VOICE',
  'PERFORMANCE_WRONG',
  'TOO_POLISHED',
  'TOO_INFLUENCER',
  'TOO_AI',
  'NOT_HER',
] as const;

export const VOICE_CALIBRATION_PROGRESS_DOMAINS = [
  'VOICE_IDENTITY',
  'CADENCE',
  'WARMTH',
  'HUMOR_DELIVERY',
  'SERIOUS_MODE',
  'EMOTIONAL_RANGE',
  'CROSS_LINE_IDENTITY',
] as const;

export const VOICE_CALIBRATION_PROGRESS_LEVELS = [
  'UNTESTED',
  'EARLY',
  'FORMING',
  'STRONG',
  'CONFIRMED',
] as const;

/** Initial broad casting candidate count */
export const INITIAL_VOICE_CANDIDATE_COUNT = 4 as const;
export const MIN_VOICE_CANDIDATE_COUNT = 3 as const;
export const MAX_VOICE_CANDIDATE_COUNT = 5 as const;

/** Success criteria — P0.5E.4B sprint */
export const CHARACTER_LANGUAGE_LAB_SEPARATED_FROM_VOICE_LAB = true as const;
export const AUDITORY_CHARACTER_VOICE_LAB_IMPLEMENTED = true as const;
export const ADAPTIVE_VOICE_CASTING_IMPLEMENTED = true as const;
export const SAME_LINE_VOICE_COMPARISON_IMPLEMENTED = true as const;
export const PAIRWISE_VOICE_PREFERENCE_IMPLEMENTED = true as const;
export const FOUNDER_VOICE_RECOGNITION_WORKFLOW_IMPLEMENTED = true as const;
export const FOUNDER_DOES_NOT_NEED_ACOUSTIC_PARAMETERS = true as const;
export const CHARACTER_VOICE_CALIBRATION_INFERENCE_IMPLEMENTED = true as const;
export const DIRECT_VS_INFERRED_VOICE_TRUTH_PRESERVED = true as const;
export const ADAPTIVE_VOICE_ROUNDS_IMPLEMENTED = true as const;
export const VOICE_IDENTITY_SEPARATE_FROM_PERFORMANCE = true as const;
export const CHARACTER_VOICE_PERFORMANCE_ENVELOPE_IMPLEMENTED = true as const;
export const CROSS_EMOTION_VOICE_TESTING_IMPLEMENTED = true as const;
export const UNSEEN_LINE_VOICE_RECOGNITION_IMPLEMENTED = true as const;
export const NONVERBAL_VOICE_BEHAVIOR_IMPLEMENTED = true as const;
export const PAUSE_BEHAVIOR_IMPLEMENTED = true as const;
export const LAUGH_BEHAVIOR_IMPLEMENTED = true as const;
export const CHARACTER_CODE_SWITCHING_IMPLEMENTED = true as const;
export const CULTURAL_VOICE_CARICATURE_BLOCKED = true as const;
export const FORCED_DIALECT_BLOCKED = true as const;
export const REAL_PERSON_VOICE_IMPERSONATION_BLOCKED = true as const;
export const UNAUTHORIZED_VOICE_CLONING_BLOCKED = true as const;
export const FAL_AUDIO_CAPABILITY_REGISTRY_IMPLEMENTED = true as const;
export const PROVIDER_AWARE_VOICE_COMPILER_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_GENERATION_CONTRACT_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_GENERATION_SNAPSHOT_IMPLEMENTED = true as const;
export const PERSISTENT_CHARACTER_VOICE_IDENTITY_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_REFERENCE_LIBRARY_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_VERSIONING_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_MIGRATION_EVALUATION_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_CONTINUITY_QA_IMPLEMENTED = true as const;
export const P0_5E_5_VOICE_PIPELINE_INTEGRATED = true as const;
export const CHARACTER_BIBLE_SUPPORTS_CANONICAL_VOICE = true as const;
export const AUDIO_VISUAL_CHARACTER_COHERENCE_ARCHITECTURE_IMPLEMENTED = true as const;
export const FINAL_AUDIOVISUAL_CHARACTER_LOCK_REQUIRES_FACE_AND_VOICE = true as const;
export const FOUNDER_CHARACTER_VOICE_CONFIRMED = false as const;
export const FINAL_CHARACTER_FACE_SELECTED = false as const;
export const FINAL_AUDIOVISUAL_CHARACTER_LOCKED = false as const;
export const AUTONOMOUS_PUBLISHING_ENABLED = false as const;
export const BRAND_CHARACTER_MUTATED = false as const;
export const BRAND_CANON_MUTATED = false as const;
export const PRODUCT_EXPRESSION_IMPLEMENTED = false as const;
export const WORLD_FORMATION_IMPLEMENTED = false as const;

/** Success criteria — P0.5E.4B.1 sprint */
export const NEURAL_VOICE_CASTING_PROVIDER_IMPLEMENTED = true as const;
export const NEURAL_VOICE_REVISION_LOOP_IMPLEMENTED = true as const;
export const NEURAL_VOICE_REGENERATE_REPLAY_SUPPORTED = true as const;
export const BROWSER_SPEECHSYNTHESIS_RETIRED_FROM_FOUNDER_CASTING = true as const;
export const BROWSER_SPEECHSYNTHESIS_RETAINED_FOR_DEV_TESTING = true as const;
export const PLACEHOLDER_VOICE_ASSETS_NON_CANONICAL = true as const;
export const FAL_NEURAL_VOICE_PROVIDER_DISCOVERY_IMPLEMENTED = true as const;
export const NEURAL_VOICE_MODEL_SELECTION_IMPLEMENTED = true as const;
export const PROVIDER_SCHEMA_VALIDATION_IMPLEMENTED = true as const;
export const NATURAL_CONVERSATIONAL_PERFORMANCE_CONTRACT_IMPLEMENTED = true as const;
export const SAME_LINE_DIFFERENT_WOMEN_NEURAL_AUDITION_IMPLEMENTED = true as const;
export const NEURAL_VOICE_CANDIDATE_PERSISTENCE_IMPLEMENTED = true as const;
export const CLOSE_REFINES_EXISTING_VOICE_IDENTITY = true as const;
export const NO_REJECTS_VOICE_REGION = true as const;
export const NEURAL_VOICE_NATURALNESS_QA_IMPLEMENTED = true as const;
export const HUMAN_WOMAN_AUDIT_IMPLEMENTED = true as const;
export const NATURALNESS_SEPARATE_FROM_CHARACTER_FIT = true as const;
export const ROBOTIC_TTS_BLOCKED = true as const;
export const AI_ASSISTANT_VOICE_BLOCKED = true as const;
export const ANNOUNCER_VOICE_BLOCKED = true as const;
export const INFLUENCER_VOICE_BLOCKED = true as const;
export const SYNTHETIC_FEMININITY_FAILURE_IMPLEMENTED = true as const;
export const BLIND_PROVIDER_BAKEOFF_IMPLEMENTED = true as const;
export const ADAPTIVE_NEURAL_SIBLING_ROUNDS_IMPLEMENTED = true as const;
export const VOICE_RIGHT_PERFORMANCE_WRONG_SUPPORTED = true as const;
export const CROSS_EMOTION_REQUIRES_NATURALNESS_PASS = true as const;
export const UNSEEN_LINE_RECOGNITION_PRESERVED = true as const;
export const CANONICAL_VOICE_REQUIRES_EXPLICIT_FOUNDER_APPROVAL = true as const;
export const CANONICAL_CHARACTER_VOICE_PERSISTS_PROVIDER_IDENTITY = true as const;
export const P0_5E_5_NEURAL_VOICE_INTEGRATION_IMPLEMENTED = true as const;
export const AUTOMATIC_AUDIO_GENERATION = false as const;
export const FINAL_CHARACTER_VOICE_CONFIRMED = false as const;
