/**
 * P0.5D — Content Operations + Performance Learning Engine
 */

export const CONTENT_OPERATIONS_V1 = 'CONTENT_OPERATIONS_V1' as const;
export const NDXBOOK_MARKET_TEST_01_V1 = 'NDXBOOK_MARKET_TEST_01_V1' as const;

export const NDXBOOK_CONTENT_OPERATIONS_RUN_ID = 'ndxbook-content-operations';
export const NDXBOOK_CONTENT_OPERATIONS_DB_ID = 'c4e1a2b3-0013-4000-8000-000000000001';
export const NDXBOOK_CONTENT_OPERATIONS_MODE = 'NDX_CONTENT_OPERATIONS' as const;

export const DEFAULT_OPERATING_MODE = 'ASSISTED_AUTONOMY' as const;

export const OPERATING_MODES = [
  'MANUAL',
  'ASSISTED_AUTONOMY',
  'CONDITIONALLY_AUTOMATED',
  'AUTONOMOUS_FUTURE',
] as const;

export const OPPORTUNITY_SOURCE_TYPES = [
  'EVERGREEN',
  'FOUNDER_SEED',
  'AUDIENCE_QUESTION',
  'CULTURAL_SIGNAL',
  'TREND',
  'NEWS',
  'HISTORICAL_CALLBACK',
  'DATA_SIGNAL',
  'PRODUCT_BEHAVIOR',
  'INDUSTRY_BEHAVIOR',
  'SOCIAL_PATTERN',
  'ARCHIVE_REVISIT',
  'SEASONAL',
  'COMMUNITY_SIGNAL',
  'PERFORMANCE_DERIVED',
  'UNRESOLVED_PRIOR_INVESTIGATION',
] as const;

export const OPPORTUNITY_FIT_RESULTS = [
  'STRONG_OPPORTUNITY',
  'PROMISING',
  'NEEDS_RESEARCH',
  'TOO_THIN',
  'TOO_REPETITIVE',
  'TOO_TREND_DEPENDENT',
  'TOO_OFF_BRAND',
  'TOO_RISKY',
  'NOT_NDX',
] as const;

export const CONTENT_SELECTION_STATUSES = [
  'SELECT_NOW',
  'QUEUE',
  'RESEARCH_FIRST',
  'SAVE_FOR_LATER',
  'WATCH',
  'REJECT',
  'MERGE_WITH_EXISTING',
  'CALLBACK_TO_EXISTING',
  'FOUNDER_DECISION_REQUIRED',
] as const;

export const SIMILARITY_RESULTS = [
  'NEW',
  'RELATED_BUT_DISTINCT',
  'FOLLOW_UP',
  'CALLBACK',
  'SELF_CORRECTION',
  'TOO_SIMILAR',
  'DUPLICATE',
] as const;

export const RESEARCH_DEPTHS = [
  'NONE_REQUIRED',
  'QUICK_VERIFY',
  'STANDARD',
  'DEEP',
  'INVESTIGATIVE',
] as const;

export const CLAIM_CONFIDENCE = ['HIGH', 'MEDIUM', 'LOW', 'UNVERIFIED'] as const;

export const CLAIM_STATUSES = [
  'FACT',
  'INTERPRETATION',
  'OPINION',
  'HYPOTHESIS',
  'QUESTION',
  'JOKE',
  'PREDICTION',
] as const;

export const EVIDENCE_CLASSES = [
  'PRIMARY_SOURCE',
  'OFFICIAL_DATA',
  'REPUTABLE_SECONDARY',
  'ARCHIVAL',
  'PUBLIC_STATEMENT',
  'SCREENSHOT',
  'USER_GENERATED',
  'FOUNDER_OBSERVATION',
  'COMMUNITY_SIGNAL',
  'INTERNAL_ANALYSIS',
  'CALCULATION',
  'HISTORICAL_SOURCE',
] as const;

export const EVIDENCE_LINEAGE = [
  'REAL_SOURCE',
  'FOUNDER_SUPPLIED',
  'PUBLIC_SOURCE',
  'CALCULATED',
  'GENERATED_ILLUSTRATION',
  'SIMULATED_EXAMPLE',
] as const;

export const CONTENT_CHANNELS = [
  'INSTAGRAM_FEED',
  'INSTAGRAM_STORY',
  'INSTAGRAM_REEL',
  'TIKTOK_FUTURE',
  'THREAD_FUTURE',
  'EMAIL',
  'LONG_FORM',
  'MULTI_CHANNEL',
  'HOLD',
] as const;

export const CONTENT_FORMATS = [
  'SINGLE_IMAGE',
  'CAROUSEL',
  'STORY_SEQUENCE',
  'REEL',
  'SHORT_VIDEO',
  'LONG_VIDEO_FUTURE',
  'TEXT_POST',
  'EMAIL',
  'ARTICLE',
  'INTERACTIVE_FUTURE',
] as const;

export const CALENDAR_STATUSES = [
  'IDEA',
  'WATCHING',
  'RESEARCH',
  'FORMULATING',
  'GENERATING',
  'FOUNDER_REVIEW',
  'APPROVED',
  'SCHEDULED',
  'PUBLISHED',
  'LEARNING',
  'REVISE',
  'ARCHIVED',
] as const;

export const PUBLISH_HANDOFF_STATUSES = [
  'READY_FOR_MANUAL_PUBLISH',
  'READY_FOR_CONNECTED_PUBLISH',
  'SCHEDULED',
  'PUBLISHED',
  'FAILED',
  'CANCELLED',
] as const;

export const RISK_LEVELS = ['LOW', 'MODERATE', 'HIGH', 'BLOCKED'] as const;

export const LEARNING_CONFIDENCE = ['INSUFFICIENT', 'LOW', 'MEDIUM', 'HIGH'] as const;

export const PERFORMANCE_EVIDENCE_CLASSES = [
  'PRODUCTION_SIGNAL',
  'AUDIENCE_SIGNAL',
  'TOPIC_SIGNAL',
  'FORMAT_SIGNAL',
  'CHANNEL_SIGNAL',
  'TIMING_SIGNAL',
  'BEHAVIORAL_MODE_SIGNAL',
  'VISUAL_SIGNAL',
  'CHARACTER_FIT_SIGNAL',
  'ANOMALY',
  'INSUFFICIENT_SAMPLE',
] as const;

export const CONNECTOR_CAPABILITY = [
  'NOT_CONNECTED',
  'TEST_VERIFIED',
  'LIVE_PATH_UNVERIFIED',
  'PRODUCTION_VERIFIED',
] as const;

export const CTA_OPTIONS = [
  'NONE',
  'SWIPE',
  'LOOK_CLOSER',
  'SAVE',
  'SHARE',
  'RESPOND',
  'VOTE',
  'ADD_EVIDENCE',
  'TELL_US_IF_YOU_REMEMBER',
  'COME_BACK_FOR_PART_2',
  'READ_SOURCE',
  'TRY_THIS',
  'QUESTION',
  'FOLLOW_THREAD',
] as const;

export const CAPTION_STYLES = [
  'ONE_LINE_REACTION',
  'SHORT_CONTEXT',
  'MEDIUM_EXPLANATION',
  'LONG_FORM_CAPTION',
  'SOURCE_NOTE',
  'QUESTION_ONLY',
] as const;

export const FOUNDER_OPPORTUNITY_ACTIONS = [
  'SELECT',
  'SAVE',
  'WATCH',
  'RESEARCH',
  'NOT_NDX',
  'WE_ALREADY_SAID_THIS',
  'TOO_TRENDY',
  'TOO_THIN',
  'DIFFERENT_ANGLE',
] as const;

export const FOUNDER_CONTENT_ACTIONS = [
  'APPROVE',
  'REVISE',
  'REJECT',
  'HOLD',
  'PUBLISH_LATER',
  'WRONG_CHARACTER',
  'WRONG_ANGLE',
  'WRONG_EVIDENCE',
  'WRONG_VISUAL',
  'TOO_LONG',
  'TOO_SHORT',
  'TOO_SERIOUS',
  'TOO_TRY_HARD',
  'NOT_NDX',
] as const;

export const AUDIENCE_RESPONSE_TYPES = [
  'UNDERSTOOD_THE_JOKE',
  'MISUNDERSTOOD',
  'CONNECTED_PERSONALLY',
  'ASKED_FOR_MORE',
  'DISAGREED_PRODUCTIVELY',
  'DISAGREED_NEGATIVELY',
  'FOUND_USEFUL',
  'FOUND_FUNNY',
  'FOUND_SMART',
  'FOUND_CONFUSING',
  'FOUND_MEAN',
  'FOUND_TRY_HARD',
  'FOUND_REPETITIVE',
  'RECOGNIZED_CALLBACK',
  'ENGAGED_WITH_EVIDENCE',
] as const;

export const EDITORIAL_BALANCE_FLAGS = [
  'TOO_MUCH_SNARK',
  'TOO_MUCH_FINANCE',
  'TOO_MUCH_NOSTALGIA',
  'TOO_MUCH_SERIOUSNESS',
  'TOO_MUCH_SAME_FORMAT',
  'TOO_MUCH_SAME_BEHAVIOR',
  'TOO_MANY_CONCLUSIONS',
  'TOO_FEW_OPEN_QUESTIONS',
  'TOO_FEW_SELF_CORRECTIONS',
  'TOO_FEW_HUMAN_MOMENTS',
  'TOO_MUCH_TREND_CHASING',
] as const;

export const CONTENT_OPERATIONS_SYSTEM_IMPLEMENTED = true as const;
export const ASSISTED_AUTONOMY_POLICY_IMPLEMENTED = true as const;
export const CONTENT_OPPORTUNITY_ENGINE_IMPLEMENTED = true as const;
export const EDITORIAL_STRATEGY_IMPLEMENTED = true as const;
export const EDITORIAL_MEMORY_IMPLEMENTED = true as const;
export const DUPLICATE_AND_CALLBACK_LOGIC_IMPLEMENTED = true as const;
export const CONTENT_OPPORTUNITY_RANKING_IMPLEMENTED = true as const;
export const WEEKLY_SLATE_IMPLEMENTED = true as const;
export const CHANNEL_SELECTION_IMPLEMENTED = true as const;
export const FORMAT_SELECTION_IMPLEMENTED = true as const;
export const RESEARCH_DEPTH_POLICY_IMPLEMENTED = true as const;
export const CONTENT_EVIDENCE_MODEL_IMPLEMENTED = true as const;
export const CLAIM_CONFIDENCE_IMPLEMENTED = true as const;
export const SOCIAL_CONTENT_PACKAGE_IMPLEMENTED = true as const;
export const CAROUSEL_SEQUENCE_INTEGRATED = true as const;
export const REEL_EXPRESSION_CONTRACT_IMPLEMENTED = true as const;
export const STORY_EXPRESSION_CONTRACT_IMPLEMENTED = true as const;
export const CAPTION_CONTRACT_IMPLEMENTED = true as const;
export const CTA_POLICY_IMPLEMENTED = true as const;
export const FOUNDER_APPROVAL_POLICY_IMPLEMENTED = true as const;
export const CONTENT_RISK_EVALUATION_IMPLEMENTED = true as const;
export const CONTENT_CALENDAR_IMPLEMENTED = true as const;
export const PUBLISHING_HANDOFF_IMPLEMENTED = true as const;
export const LIVE_PLATFORM_PUBLISHING_CLAIMED_WITHOUT_VERIFICATION = false as const;
export const CONTENT_PERFORMANCE_RECORD_IMPLEMENTED = true as const;
export const QUALITATIVE_AUDIENCE_RESPONSE_IMPLEMENTED = true as const;
export const PERFORMANCE_LEARNING_IMPLEMENTED = true as const;
export const PERFORMANCE_DOES_NOT_MUTATE_CHARACTER = true as const;
export const PERFORMANCE_DOES_NOT_MUTATE_CANON = true as const;
export const FALSE_LEARNING_GUARDS_IMPLEMENTED = true as const;
export const CONTROLLED_CONTENT_EXPERIMENTATION_IMPLEMENTED = true as const;
export const EDITORIAL_HEALTH_IMPLEMENTED = true as const;
export const CONTENT_PRODUCTION_BUDGET_IMPLEMENTED = true as const;
export const CONTENT_OPERATIONS_CONTROL_CENTER_IMPLEMENTED = true as const;
export const NDXBOOK_MARKET_TEST_01_READY = true as const;
export const AUTONOMOUS_PUBLISHING_ENABLED = false as const;
export const PRODUCT_EXPRESSION_BLOCKED = true as const;
export const WORLD_FORMATION_BLOCKED = true as const;
export const LIVE_SIGNAL_INGESTION_NOT_CONNECTED = false as const;
export const LIVE_CULTURAL_INTELLIGENCE_LAYER_IMPLEMENTED = true as const;
