/**
 * P0.E.FT3.1 — Full-bleed art contracts per Astral World scene (FAL-ready).
 */

import type { AstralSceneContract, AstralSceneId } from './types.js';

export const ASTRAL_SCENE_CONTRACTS: Record<AstralSceneId, AstralSceneContract> = {
  HOME_ARRIVAL: {
    sceneId: 'HOME_ARRIVAL',
    label: 'Astral World Arrival',
    backgroundCrop: 'ASTRAL_WORLD_HERO',
    backgroundCropMobile: 'ASTRAL_WORLD_HERO_MOBILE',
    assetSlotKey: 'ASTRAL_WORLD_HERO_DESKTOP',
    assetSlotKeyMobile: 'ASTRAL_WORLD_HERO_MOBILE',
    focalPoint: 'center 30%',
    overlaySafeZones: { top: 12, bottom: 28, left: 6, right: 6 },
    contentSafeRegion: { xPercent: 6, yPercent: 58, widthPercent: 88, heightPercent: 32 },
    fallbackCrop: 'ASTRAL_WORLD_HERO_MOBILE',
  },
  ASTREA_DISTRICT: {
    sceneId: 'ASTREA_DISTRICT',
    label: 'Astréa District',
    backgroundCrop: 'ASTREA_DISTRICT',
    backgroundCropMobile: 'ASTREA_DISTRICT_MOBILE',
    assetSlotKey: 'ASTREA_DISTRICT_PANORAMA_DESKTOP',
    assetSlotKeyMobile: 'ASTREA_DISTRICT_PANORAMA_MOBILE',
    focalPoint: 'center 40%',
    overlaySafeZones: { top: 8, bottom: 22, left: 4, right: 4 },
    contentSafeRegion: { xPercent: 4, yPercent: 68, widthPercent: 92, heightPercent: 24 },
    fallbackCrop: 'ASTREA_DISTRICT_MOBILE',
  },
  TAROT_SUITE: {
    sceneId: 'TAROT_SUITE',
    label: 'Tarot Suite',
    backgroundCrop: 'TAROT_SUITE',
    backgroundCropMobile: 'TAROT_SUITE_MOBILE',
    assetSlotKey: 'TAROT_SUITE_HERO_DESKTOP',
    assetSlotKeyMobile: 'TAROT_SUITE_HERO_MOBILE',
    focalPoint: 'center center',
    overlaySafeZones: { top: 10, bottom: 24, left: 5, right: 5 },
    contentSafeRegion: { xPercent: 5, yPercent: 62, widthPercent: 90, heightPercent: 30 },
    fallbackCrop: 'TAROT_SUITE_MOBILE',
  },
  ASTRAL_MALL: {
    sceneId: 'ASTRAL_MALL',
    label: 'Astral Mall',
    backgroundCrop: 'ASTRAL_MALL',
    backgroundCropMobile: 'ASTRAL_MALL_MOBILE',
    assetSlotKey: 'ASTRAL_MALL_HERO_DESKTOP',
    assetSlotKeyMobile: 'ASTRAL_MALL_HERO_MOBILE',
    focalPoint: 'center 45%',
    overlaySafeZones: { top: 8, bottom: 26, left: 4, right: 4 },
    contentSafeRegion: { xPercent: 4, yPercent: 65, widthPercent: 92, heightPercent: 28 },
    fallbackCrop: 'ASTRAL_MALL_MOBILE',
  },
  COFFEE_SHOP: {
    sceneId: 'COFFEE_SHOP',
    label: 'Coffee Shop',
    backgroundCrop: 'COFFEE_SHOP',
    backgroundCropMobile: 'COFFEE_SHOP_MOBILE',
    assetSlotKey: 'COFFEE_SHOP_HERO_DESKTOP',
    assetSlotKeyMobile: 'COFFEE_SHOP_HERO_MOBILE',
    focalPoint: 'center 50%',
    overlaySafeZones: { top: 6, bottom: 20, left: 3, right: 3 },
    contentSafeRegion: { xPercent: 3, yPercent: 55, widthPercent: 94, heightPercent: 38 },
    fallbackCrop: 'COFFEE_SHOP_MOBILE',
  },
  FIND_MY_READER: {
    sceneId: 'FIND_MY_READER',
    label: 'Find My Reader',
    backgroundCrop: 'SOCIAL_PRESENCE',
    backgroundCropMobile: 'FIND_MY_READER_MOBILE',
    assetSlotKey: 'CIRCLE_COMMUNITY_HERO',
    assetSlotKeyMobile: 'CIRCLE_COMMUNITY_HERO',
    focalPoint: 'top center',
    overlaySafeZones: { top: 14, bottom: 18, left: 4, right: 4 },
    contentSafeRegion: { xPercent: 4, yPercent: 72, widthPercent: 92, heightPercent: 22 },
    fallbackCrop: 'FIND_MY_READER_MOBILE',
  },
  FRIENDS_PRESENCE: {
    sceneId: 'FRIENDS_PRESENCE',
    label: 'Meet My Friends',
    backgroundCrop: 'SOCIAL_PRESENCE',
    backgroundCropMobile: 'SOCIAL_PRESENCE_MOBILE',
    assetSlotKey: 'CIRCLE_COMMUNITY_HERO',
    assetSlotKeyMobile: 'CIRCLE_COMMUNITY_HERO',
    focalPoint: 'center 35%',
    overlaySafeZones: { top: 10, bottom: 22, left: 5, right: 5 },
    contentSafeRegion: { xPercent: 5, yPercent: 60, widthPercent: 90, heightPercent: 34 },
    fallbackCrop: 'SOCIAL_PRESENCE_MOBILE',
  },
  JOURNAL_ARTIFACT: {
    sceneId: 'JOURNAL_ARTIFACT',
    label: 'Tarot Journal',
    backgroundCrop: 'JOURNAL',
    backgroundCropMobile: 'JOURNAL_MOBILE',
    assetSlotKey: 'JOURNAL_ARTIFACT',
    assetSlotKeyMobile: 'JOURNAL_ARTIFACT',
    focalPoint: 'center center',
    overlaySafeZones: { top: 8, bottom: 16, left: 4, right: 4 },
    contentSafeRegion: { xPercent: 8, yPercent: 48, widthPercent: 84, heightPercent: 44 },
    fallbackCrop: 'JOURNAL_MOBILE',
  },
  PROFILE_AVATAR: {
    sceneId: 'PROFILE_AVATAR',
    label: 'My Astral Self',
    backgroundCrop: 'CUSTOM_AVATAR',
    backgroundCropMobile: 'CUSTOM_AVATAR',
    assetSlotKey: 'CUSTOM_AVATAR_HERO',
    assetSlotKeyMobile: 'CUSTOM_AVATAR_HERO',
    focalPoint: 'center top',
    overlaySafeZones: { top: 12, bottom: 24, left: 6, right: 6 },
    contentSafeRegion: { xPercent: 6, yPercent: 52, widthPercent: 88, heightPercent: 40 },
    fallbackCrop: 'CUSTOM_AVATAR',
  },
};

export function getSceneContract(sceneId: AstralSceneId): AstralSceneContract {
  return ASTRAL_SCENE_CONTRACTS[sceneId];
}

export const ASTRAL_PRIMARY_SCENE_IDS: AstralSceneId[] = [
  'HOME_ARRIVAL',
  'ASTREA_DISTRICT',
  'TAROT_SUITE',
  'ASTRAL_MALL',
  'COFFEE_SHOP',
  'FIND_MY_READER',
  'FRIENDS_PRESENCE',
  'JOURNAL_ARTIFACT',
  'PROFILE_AVATAR',
];
