export const P0_VR_TWIN_V30R8M2_LINEAGE = 'P0.VR.TWINV3.0R8M2' as const;
export const MOBILE_TWIN_IMPL_COMPILER_GENERATION = 'R8M2' as const;
export const MOBILE_TWIN_IMPLEMENTATION_VERSION = 'mobile-twin-impl-v3' as const;

export const R8M1_CORRECTION_REQUIRED_REASON = 'IMPLEMENTATION_TRANSLATION_TOO_ABSTRACT' as const;

export const CRITICAL_IMPLEMENTATION_REGIONS = [
  'HOST_HEADER',
  'PROJECT_CONTEXT',
  'TARGET_VIEWPORT_STAGE',
  'HERO_WORKSPACE',
  'AUTHORITY_PANEL',
  'CANDIDATE_GALLERY',
  'STRUCTURED_OUTPUT',
  'READINESS',
  'CONCEPT_DATA',
  'BOTTOM_NAV',
] as const;

export type CriticalImplementationRegionId = (typeof CRITICAL_IMPLEMENTATION_REGIONS)[number];
