/**
 * Seed Studio World Acting Company — diverse casting roster (no provider spend).
 */

import type { ActorIdentityAuthority, StudioWorldActor, StudioWorldActorCatalogue } from './types.js';

function idAuth(
  actorId: string,
  catalogueNumber: string,
  face: string,
): ActorIdentityAuthority {
  const now = '2026-09-29T00:00:00.000Z';
  return {
    identityAuthorityId: `id-auth-${catalogueNumber}`,
    actorId,
    canonicalFaceDescription: face,
    facialProportions: 'Production-locked proportions from identity session',
    baselineSkinAppearance: 'Locked baseline — campaign makeup adapts, identity persists',
    baselineBodyProportions: 'Locked full-body silhouette anchor',
    baselineHairState: 'Natural baseline — era looks override in Campaign Look only',
    neutralExpressionNote: 'Neutral mouth, direct gaze, no performance exaggeration',
    views: [
      { view: 'FRONTAL', assetId: `asset-${catalogueNumber}-front`, storagePath: null, previewUrl: null },
      { view: 'THREE_QUARTER', assetId: `asset-${catalogueNumber}-34`, storagePath: null, previewUrl: null },
      { view: 'PROFILE', assetId: `asset-${catalogueNumber}-profile`, storagePath: null, previewUrl: null },
      { view: 'FULL_BODY', assetId: `asset-${catalogueNumber}-body`, storagePath: null, previewUrl: null },
    ],
    immutable: true,
    createdAt: now,
    updatedAt: now,
  };
}

function actor(partial: StudioWorldActor): StudioWorldActor {
  return partial;
}

const ACTORS: StudioWorldActor[] = [
  actor({
    actorId: 'sw-actor-017',
    catalogueNumber: 'SW-017',
    stageName: 'Maya Okonkwo',
    status: 'ACTIVE',
    identityAuthorityId: 'id-auth-SW-017',
    presentation: 'WOMAN',
    ageRange: '26–32',
    heightRange: '5\'6"–5\'8"',
    build: 'Athletic-medium',
    skinToneDescription: 'Deep brown, warm undertone',
    hairBaseline: 'Black, 4C coils, shoulder length',
    eyeDescription: 'Dark brown, almond',
    facialFeatures: 'High cheekbones, full lips, strong brow',
    distinguishingFeatures: 'Small gold nose stud (may be removed per look)',
    nationalityOrCulturalCastingTags: ['Nigerian-American', 'Southern US lived-in'],
    languages: ['English'],
    accentCapabilities: ['General American', 'Light Southern'],
    performanceProfile: ['EXPRESSIVE', 'EVERYDAY', 'RAW', 'VULNERABLE', 'CHARISMATIC'],
    personalityRange: ['Direct', 'Wry', 'Observant'],
    emotionalRange: ['Defiant', 'Nostalgic', 'Skeptical'],
    roleArchetypes: ['SUBJECT', 'INFLUENCER', 'FRIEND', 'SHOPPER'],
    occupationArchetypes: ['STUDENT', 'OFFICE_WORKER', 'INFLUENCER'],
    fashionRange: ['Street', '2016 IG era', 'Contemporary editorial'],
    wardrobeCompatibility: ['Athleisure', 'Y2K revival', 'Minimal luxury'],
    hairAdaptability: ['High — protective styles, straightened era looks'],
    makeupAdaptability: ['High — soft glam to bare'],
    periodAdaptability: ['2016', '2020s'],
    cinematicPresence: ['Lead-adjacent', 'Social proof subject'],
    commercialFit: ['Fashion', 'Platform culture'],
    editorialFit: ['Culture essay', 'Beauty archive'],
    comedicFit: ['Dry'],
    dramaticFit: ['Medium-high'],
    projectsUsed: ['ndxbook'],
    campaignsUsed: ['entry-002'],
    charactersPlayed: [],
    availabilityState: 'IN_CURRENT_PRODUCTION',
    continuityRisk: 'LOW',
    headshotPreviewUrl: null,
    createdAt: '2026-09-29T00:00:00.000Z',
    updatedAt: '2026-09-29T00:00:00.000Z',
  }),
  actor({
    actorId: 'sw-actor-044',
    catalogueNumber: 'SW-044',
    stageName: 'Jordan Reyes',
    status: 'ACTIVE',
    identityAuthorityId: 'id-auth-SW-044',
    presentation: 'NONBINARY',
    ageRange: '28–35',
    heightRange: '5\'9"–5\'11"',
    build: 'Slim',
    skinToneDescription: 'Olive tan',
    hairBaseline: 'Dark brown buzz with undercut',
    eyeDescription: 'Hazel',
    facialFeatures: 'Angular jaw, soft eyes',
    distinguishingFeatures: 'Cartilage piercing',
    nationalityOrCulturalCastingTags: ['Latine', 'East Coast'],
    languages: ['English', 'Spanish'],
    accentCapabilities: ['General American'],
    performanceProfile: ['UNDERSTATED', 'INTELLECTUAL', 'WARM', 'DETACHED'],
    personalityRange: ['Calm', 'Precise'],
    emotionalRange: ['Curious', 'Measured'],
    roleArchetypes: ['FRIEND', 'CREATIVE_DIRECTOR', 'DESIGNER'],
    occupationArchetypes: ['STYLIST', 'ARTIST'],
    fashionRange: ['Androgynous tailoring', 'Creative studio'],
    wardrobeCompatibility: ['Workwear', 'Gallery opening'],
    hairAdaptability: ['Medium'],
    makeupAdaptability: ['Low-neutral grooming'],
    periodAdaptability: ['2020s'],
    cinematicPresence: ['Supporting'],
    commercialFit: ['Creative tools'],
    editorialFit: ['Design culture'],
    comedicFit: ['Deadpan'],
    dramaticFit: ['Medium'],
    projectsUsed: [],
    campaignsUsed: [],
    charactersPlayed: [],
    availabilityState: 'AVAILABLE',
    continuityRisk: 'LOW',
    headshotPreviewUrl: null,
    createdAt: '2026-09-29T00:00:00.000Z',
    updatedAt: '2026-09-29T00:00:00.000Z',
  }),
  actor({
    actorId: 'sw-actor-008',
    catalogueNumber: 'SW-008',
    stageName: 'Helena Voss',
    status: 'ACTIVE',
    identityAuthorityId: 'id-auth-SW-008',
    presentation: 'WOMAN',
    ageRange: '42–50',
    heightRange: '5\'5"–5\'7"',
    build: 'Average',
    skinToneDescription: 'Fair with freckles',
    hairBaseline: 'Auburn wavy bob',
    eyeDescription: 'Green-grey',
    facialFeatures: 'Fine lines, expressive forehead',
    distinguishingFeatures: 'Reading glasses prop-friendly',
    nationalityOrCulturalCastingTags: ['German', 'Academic Europe'],
    languages: ['English', 'German'],
    accentCapabilities: ['Light German'],
    performanceProfile: ['AUTHORITATIVE', 'INTELLECTUAL', 'CONTROLLED', 'WARM'],
    personalityRange: ['Archivist', 'Patient explainer'],
    emotionalRange: ['Skeptical', 'Delighted discovery'],
    roleArchetypes: ['ARCHIVIST', 'RESEARCHER', 'TEACHER'],
    occupationArchetypes: ['DOCTOR', 'TEACHER'],
    fashionRange: ['Academic', 'Museum staff'],
    wardrobeCompatibility: ['Tweed', 'Lab coat', 'Quiet luxury'],
    hairAdaptability: ['Low — professional baseline'],
    makeupAdaptability: ['Minimal'],
    periodAdaptability: ['1990s–2020s'],
    cinematicPresence: ['Expert witness'],
    commercialFit: ['Institutional'],
    editorialFit: ['Long-form essay'],
    comedicFit: ['Dry academic'],
    dramaticFit: ['High'],
    projectsUsed: [],
    campaignsUsed: [],
    charactersPlayed: [],
    availabilityState: 'AVAILABLE',
    continuityRisk: 'LOW',
    headshotPreviewUrl: null,
    createdAt: '2026-09-29T00:00:00.000Z',
    updatedAt: '2026-09-29T00:00:00.000Z',
  }),
  actor({
    actorId: 'sw-actor-031',
    catalogueNumber: 'SW-031',
    stageName: 'Marcus Chen',
    status: 'ACTIVE',
    identityAuthorityId: 'id-auth-SW-031',
    presentation: 'MAN',
    ageRange: '32–40',
    heightRange: '5\'10"–6\'0"',
    build: 'Broad shoulders',
    skinToneDescription: 'East Asian tan',
    hairBaseline: 'Black straight, side part',
    eyeDescription: 'Dark brown',
    facialFeatures: 'Square jaw, calm mouth',
    distinguishingFeatures: 'None required on camera',
    nationalityOrCulturalCastingTags: ['Chinese-American'],
    languages: ['English', 'Mandarin'],
    accentCapabilities: ['General American'],
    performanceProfile: ['AUTHORITATIVE', 'LUXURY', 'CONTROLLED', 'ASPIRATIONAL'],
    personalityRange: ['Executive calm'],
    emotionalRange: ['Confident', 'Impatient'],
    roleArchetypes: ['EXECUTIVE', 'FOUNDER', 'CREATIVE_DIRECTOR'],
    occupationArchetypes: ['EXECUTIVE', 'FOUNDER'],
    fashionRange: ['Tailored', 'Tech founder casual'],
    wardrobeCompatibility: ['Suit', 'Premium knit'],
    hairAdaptability: ['Low'],
    makeupAdaptability: ['Grooming only'],
    periodAdaptability: ['2020s'],
    cinematicPresence: ['Authority figure'],
    commercialFit: ['B2B luxury'],
    editorialFit: ['Business profile'],
    comedicFit: ['Low'],
    dramaticFit: ['Medium'],
    projectsUsed: [],
    campaignsUsed: [],
    charactersPlayed: [],
    availabilityState: 'RESTING_RECENTLY_USED',
    continuityRisk: 'MEDIUM',
    headshotPreviewUrl: null,
    createdAt: '2026-09-29T00:00:00.000Z',
    updatedAt: '2026-09-29T00:00:00.000Z',
  }),
  actor({
    actorId: 'sw-actor-052',
    catalogueNumber: 'SW-052',
    stageName: 'Priya Nair',
    status: 'ACTIVE',
    identityAuthorityId: 'id-auth-SW-052',
    presentation: 'WOMAN',
    ageRange: '22–28',
    heightRange: '5\'3"–5\'5"',
    build: 'Petite',
    skinToneDescription: 'Medium brown, golden undertone',
    hairBaseline: 'Long black, wavy',
    eyeDescription: 'Dark brown',
    facialFeatures: 'Round face, bright smile',
    distinguishingFeatures: 'Bindi optional per look',
    nationalityOrCulturalCastingTags: ['South Asian', 'British South Asian'],
    languages: ['English', 'Hindi'],
    accentCapabilities: ['British', 'General American'],
    performanceProfile: ['COMEDIC', 'EXPRESSIVE', 'EVERYDAY', 'WARM'],
    personalityRange: ['Online native', 'Fast talker'],
    emotionalRange: ['Amused', 'Defensive'],
    roleArchetypes: ['INFLUENCER', 'COMMENTER', 'FRIEND'],
    occupationArchetypes: ['BARISTA', 'STUDENT'],
    fashionRange: ['Trend micro', '2016 throwback'],
    wardrobeCompatibility: ['Crop tops', 'Statement nails'],
    hairAdaptability: ['High'],
    makeupAdaptability: ['High glam'],
    periodAdaptability: ['2016', '2020s'],
    cinematicPresence: ['Ensemble energy'],
    commercialFit: ['Social platform'],
    editorialFit: ['Comment thread personification'],
    comedicFit: ['High'],
    dramaticFit: ['Low-medium'],
    projectsUsed: [],
    campaignsUsed: [],
    charactersPlayed: [],
    availabilityState: 'AVAILABLE',
    continuityRisk: 'LOW',
    headshotPreviewUrl: null,
    createdAt: '2026-09-29T00:00:00.000Z',
    updatedAt: '2026-09-29T00:00:00.000Z',
  }),
  actor({
    actorId: 'sw-actor-019',
    catalogueNumber: 'SW-019',
    stageName: 'Eleanor Marsh',
    status: 'ACTIVE',
    identityAuthorityId: 'id-auth-SW-019',
    presentation: 'WOMAN',
    ageRange: '55–65',
    heightRange: '5\'4"–5\'6"',
    build: 'Soft average',
    skinToneDescription: 'Light brown, sun-aged',
    hairBaseline: 'Salt-and-pepper locs, chin length',
    eyeDescription: 'Brown',
    facialFeatures: 'Laugh lines, kind eyes',
    distinguishingFeatures: 'Always reads as real-life mother figure',
    nationalityOrCulturalCastingTags: ['African-American Southern'],
    languages: ['English'],
    accentCapabilities: ['Southern US'],
    performanceProfile: ['WARM', 'EVERYDAY', 'VULNERABLE', 'DOCUMENTARY'],
    personalityRange: ['Plainspoken', 'Protective'],
    emotionalRange: ['Tired pride', 'Skeptical kindness'],
    roleArchetypes: ['MOTHER', 'NEIGHBOR', 'PASSERBY'],
    occupationArchetypes: ['RETAIL_WORKER', 'TEACHER'],
    fashionRange: ['Church casual', 'Grocery store real'],
    wardrobeCompatibility: ['Not fashion-polished'],
    hairAdaptability: ['Low — identity anchor'],
    makeupAdaptability: ['Minimal everyday'],
    periodAdaptability: ['Any contemporary'],
    cinematicPresence: ['Grounding ensemble'],
    commercialFit: ['Everyday retail'],
    editorialFit: ['Documentary realism'],
    comedicFit: ['Gentle'],
    dramaticFit: ['Medium'],
    projectsUsed: [],
    campaignsUsed: [],
    charactersPlayed: [],
    availabilityState: 'AVAILABLE',
    continuityRisk: 'LOW',
    headshotPreviewUrl: null,
    createdAt: '2026-09-29T00:00:00.000Z',
    updatedAt: '2026-09-29T00:00:00.000Z',
  }),
  actor({
    actorId: 'sw-actor-063',
    catalogueNumber: 'SW-063',
    stageName: 'Tomás Alvarez',
    status: 'ACTIVE',
    identityAuthorityId: 'id-auth-SW-063',
    presentation: 'MAN',
    ageRange: '24–30',
    heightRange: '5\'7"–5\'9"',
    build: 'Lean',
    skinToneDescription: 'Medium tan',
    hairBaseline: 'Dark curly top, fade',
    eyeDescription: 'Brown',
    facialFeatures: 'Youthful, mobile eyebrows',
    distinguishingFeatures: 'Forearm tattoo optional cover',
    nationalityOrCulturalCastingTags: ['Puerto Rican', 'NYC'],
    languages: ['English', 'Spanish'],
    accentCapabilities: ['NYC', 'Spanglish'],
    performanceProfile: ['COMEDIC', 'CHAOTIC', 'RAW', 'EVERYDAY'],
    personalityRange: ['Hot take guy'],
    emotionalRange: ['Mocking', 'Hyped'],
    roleArchetypes: ['COMMENTER', 'PASSERBY', 'FRIEND'],
    occupationArchetypes: ['SERVER', 'BARISTA'],
    fashionRange: ['Streetwear', '2016 hypebeast adjacent'],
    wardrobeCompatibility: ['Graphic tee', 'Timbs'],
    hairAdaptability: ['Medium'],
    makeupAdaptability: ['None'],
    periodAdaptability: ['2016', '2020s'],
    cinematicPresence: ['Background voice'],
    commercialFit: ['Youth culture'],
    editorialFit: ['Thread chorus'],
    comedicFit: ['High'],
    dramaticFit: ['Low'],
    projectsUsed: [],
    campaignsUsed: [],
    charactersPlayed: [],
    availabilityState: 'AVAILABLE',
    continuityRisk: 'LOW',
    headshotPreviewUrl: null,
    createdAt: '2026-09-29T00:00:00.000Z',
    updatedAt: '2026-09-29T00:00:00.000Z',
  }),
];

const IDENTITY_AUTHORITIES: ActorIdentityAuthority[] = ACTORS.map((a) =>
  idAuth(a.actorId, a.catalogueNumber, `${a.stageName}: ${a.facialFeatures}; ${a.skinToneDescription}; ${a.hairBaseline}`),
);

export function getStudioWorldActorCatalogue(): StudioWorldActorCatalogue {
  return {
    catalogueId: 'studio-world-acting-company',
    version: '1.0.0',
    actors: ACTORS,
    identityAuthorities: IDENTITY_AUTHORITIES,
    updatedAt: '2026-09-29T00:00:00.000Z',
  };
}

export function findActorByCatalogueNumber(catalogueNumber: string): StudioWorldActor | null {
  return ACTORS.find((a) => a.catalogueNumber === catalogueNumber) ?? null;
}

export function findActorById(actorId: string): StudioWorldActor | null {
  return ACTORS.find((a) => a.actorId === actorId) ?? null;
}

export function findIdentityAuthority(actorId: string): ActorIdentityAuthority | null {
  return IDENTITY_AUTHORITIES.find((i) => i.actorId === actorId) ?? null;
}
