/**
 * Experience Concept seeds — 3 isolated concepts per Concept Territory direction.
 * Each concept forms independently; no cross-concept visibility at formation time.
 */

import type { CanonicalNdxbookDirectionName } from '../canonicalCreativeRangeConstants.js';
import type { CreativeConceptTerritory, WorldExpressionSystem } from '../conceptTerritory/conceptTerritoryTypes.js';
import { EXPERIENCE_CONCEPT_COUNT } from './constants.js';
import type { ExperienceConcept } from './types.js';

type ConceptSeedPartial = Omit<
  ExperienceConcept,
  'experienceConceptId' | 'conceptIndex' | 'founderJudgment' | 'appetiteLineage' | 'formedInIsolation'
>;

function baseConcept(
  index: number,
  territory: CreativeConceptTerritory,
  partial: ConceptSeedPartial,
  appetiteLineage: string | null,
): ExperienceConcept {
  return {
    ...partial,
    experienceConceptId: `exp-concept-${territory.territoryId}-${index}`,
    conceptIndex: index,
    whyItBelongsToSelectedTerritory: partial.whyItBelongsToSelectedTerritory,
    founderJudgment: null,
    appetiteLineage,
    formedInIsolation: true,
  };
}

const TERRITORY_EXPERIENCE_SEEDS: Record<CanonicalNdxbookDirectionName, [ConceptSeedPartial, ConceptSeedPartial, ConceptSeedPartial]> = {
  'THE MARKED-UP COPY': [
    {
      name: 'THE RED PEN DESK',
      centralThesis: 'The project is a document under active correction — founder sees wrong claims replaced in place.',
      experienceMetaphor: 'Editorial desk with live markup',
      whyItBelongsToSelectedTerritory: 'Correction marks become the primary information behavior, not decorative UI.',
      whyItBelongsInsideSite00: 'Host glass surfaces hold the document; SITE 00 navigation remains the building.',
      viewerRole: 'Skeptical editor reviewing project truth',
      projectRelationship: 'The project is paperwork NDXBOOK is marking up for the founder',
      informationBehavior: 'Claims appear struck-through then replaced — status revealed through correction layers',
      interactionGrammar: 'INSPECT reveals evidence; APPROVE locks a correction; REVISE opens markup mode',
      navigationBehavior: 'Move between document sections like chapters — not sidebar tabs',
      hierarchyBehavior: 'URGENT = uncorrected dangerous claim; COMPLETE = locked correction',
      spatialBehavior: 'Single dominant document plane with margin proof zones',
      compositionBehavior: 'Dense editorial block — not equal-weight cards',
      hostClientRelationship: 'SITE 00 shell + bottom nav; NDXBOOK owns document surface and correction accent',
      responsivePhilosophy: 'Mobile: swipe between document sections; Desktop: margin proofs visible alongside',
      motionPhilosophy: 'Strike-through → replacement reveal on state change',
      keyExperienceMoments: ['First uncorrected claim', 'Founder approves correction', 'All critical claims locked'],
      genericTemplateAvoidanceStrategy: ['No KPI tiles', 'No equal section cards', 'Interpret command queue as markup queue'],
      risks: ['Could feel like PDF viewer if motion is weak'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'All routes remain as document chapters; actions map to review/approve flows',
    },
    {
      name: 'THE EVIDENCE TABLE',
      centralThesis: 'Project intelligence is physical evidence laid for inspection — founder walks the table.',
      experienceMetaphor: 'Examination table of proof objects',
      whyItBelongsToSelectedTerritory: 'Institutional copy becomes specimens to inspect, not dashboard fields.',
      whyItBelongsInsideSite00: 'Table sits inside SITE 00 spatial shell — host wayfinding unchanged.',
      viewerRole: 'Forensic reviewer arranging proof',
      projectRelationship: 'Each project phase is an artifact on the table',
      informationBehavior: 'Objects installed on table — tap to inspect lineage and status',
      interactionGrammar: 'OPEN specimen; COMPARE two proofs; PROMOTE to canon vault',
      navigationBehavior: 'Pan across table zones — formation, review, canon — not vertical stack',
      hierarchyBehavior: 'NEEDS FOUNDER = flagged specimen; EXPERIMENTAL = quarantined tray',
      spatialBehavior: 'Horizontal examination surface with depth layering',
      compositionBehavior: 'Objects at varied scale — hero specimen + peripheral context',
      hostClientRelationship: 'Host typography on labels; client world colors on specimen surfaces',
      responsivePhilosophy: 'Mobile: carousel of specimens with inspect drawer; Desktop: full table panorama',
      motionPhilosophy: 'Specimens slide in when forming; attention pulse on flagged items',
      keyExperienceMoments: ['New generation lands on table', 'Founder compares two directions', 'Canon promotion'],
      genericTemplateAvoidanceStrategy: ['Replace label/value rows with specimen cards at varied weight', 'No dashboard grid'],
      risks: ['Table metaphor needs strong spatial cues on mobile'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Each route opens a table zone; mutations via specimen actions',
    },
    {
      name: 'THE REVISION STAGE',
      centralThesis: 'The project is a live rehearsal of corrected narrative — founder directs what stays cut.',
      experienceMetaphor: 'Theater stage with projected copy revisions',
      whyItBelongsToSelectedTerritory: 'Correction becomes performance — audience sees the edit happen.',
      whyItBelongsInsideSite00: 'Stage exists inside SITE 00 location — curtains are client, architecture is host.',
      viewerRole: 'Director calling revisions between acts',
      projectRelationship: 'Acts map to project phases; lines map to status claims',
      informationBehavior: 'Lines appear on stage; bad lines dim; corrected lines spotlight',
      interactionGrammar: 'DISMISS bad line; EXPAND act; RETURN to previous act state',
      navigationBehavior: 'Act-based progression — not tab bar',
      hierarchyBehavior: 'ACTIVE = current act; BLOCKED = stuck line; CANONICAL = locked script',
      spatialBehavior: 'Stage depth with foreground attention and background context',
      compositionBehavior: 'Monumental active line + peripheral cast of statuses',
      hostClientRelationship: 'Host controls house lights and exits; client owns stage content',
      responsivePhilosophy: 'Mobile: single-act focus with swipe between acts; Desktop: stage + side script',
      motionPhilosophy: 'Curtain reveal on phase transition; line spotlight on founder selection',
      keyExperienceMoments: ['Phase transition curtain', 'Founder cuts a line', 'Canon script lock'],
      genericTemplateAvoidanceStrategy: ['No section cards — acts only', 'Command queue as cue sheet'],
      risks: ['Theatrical metaphor must not obscure functional routes'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Acts wrap existing routes; all mutations available from cue sheet inspector',
    },
  ],
  'THE COUNTDOWN ROOM': [
    {
      name: 'THE THRESHOLD LOBBY',
      centralThesis: 'Founder stands in a lobby where every project state has a visible window before consequence.',
      experienceMetaphor: 'Threshold lobby with deadline panels',
      whyItBelongsToSelectedTerritory: 'Temporal meters drive hierarchy — not decorative countdown widgets.',
      whyItBelongsInsideSite00: 'Lobby is a room inside SITE 00 — host nav is the building exit.',
      viewerRole: 'Operator inside a finite window',
      projectRelationship: 'Each blocker is a door with a visible threshold',
      informationBehavior: 'Thresholds installed on walls — urgency scales with proximity',
      interactionGrammar: 'ENTER room for detail; DISMISS expired window; APPROVE before threshold',
      navigationBehavior: 'Move between threshold doors — spatial, not tabs',
      hierarchyBehavior: 'URGENT = threshold < 24h; WAITING = open window; COMPLETE = sealed door',
      spatialBehavior: 'Monumental threshold at center; peripheral meters on walls',
      compositionBehavior: 'Single dominant countdown + satellite status meters',
      hostClientRelationship: 'Host shell persistent; client owns meter typography and threshold color',
      responsivePhilosophy: 'Mobile: one threshold fullscreen; Desktop: lobby panorama with multiple meters',
      motionPhilosophy: 'Tick pulse on active threshold; seal animation on complete',
      keyExperienceMoments: ['Threshold enters red zone', 'Founder opens formation room', 'Window sealed'],
      genericTemplateAvoidanceStrategy: ['No KPI row — meters only', 'Replace status rows with threshold panels'],
      risks: ['Countdown anxiety if every field gets a timer'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'Routes map to rooms; all actions available before threshold crosses',
    },
    {
      name: 'THE METER WALL',
      centralThesis: 'Project health is read from a wall of instruments — founder scans gauges, not spreadsheets.',
      experienceMetaphor: 'Industrial meter wall',
      whyItBelongsToSelectedTerritory: 'Measurement-native world expression becomes UI grammar.',
      whyItBelongsInsideSite00: 'Wall mounted in SITE 00 project location.',
      viewerRole: 'Technician reading project instruments',
      projectRelationship: 'Each experiment/generation is a gauge cluster',
      informationBehavior: 'Gauges animate to current values — raw fields in inspector drawer',
      interactionGrammar: 'INSPECT gauge; FILTER cluster; EXPAND meter group',
      navigationBehavior: 'Scroll wall horizontally on mobile; scan zones on desktop',
      hierarchyBehavior: 'NEEDS FOUNDER = needle in red; FORMING = oscillating; BLOCKED = stalled needle',
      spatialBehavior: 'Wall grid with variable gauge scale — not equal tiles',
      compositionBehavior: 'Hero gauge for primary focus; secondary cluster for experiments',
      hostClientRelationship: 'Host labels gauge metadata; client palette on gauge faces',
      responsivePhilosophy: 'Mobile: priority gauge stack; Desktop: full instrument wall',
      motionPhilosophy: 'Needle sweep on update; attention blink on founder-required gauge',
      keyExperienceMoments: ['Generation gauge spikes', 'Blocked needle stalls', 'Canon gauge locks'],
      genericTemplateAvoidanceStrategy: ['No card grid — gauges at varied diameters', 'No SaaS analytics layout'],
      risks: ['Too many gauges recreates dashboard'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Each gauge links to route; inspector holds raw values',
    },
    {
      name: 'THE WINDOW SEAT',
      centralThesis: 'Founder sits at a window watching project time pass — calm urgency, not alarm.',
      experienceMetaphor: 'Window seat with temporal horizon',
      whyItBelongsToSelectedTerritory: 'Countdown as contemplative horizon, not panic UI.',
      whyItBelongsInsideSite00: 'Seat inside SITE 00 with view to project horizon.',
      viewerRole: 'Observer planning the next move inside the window',
      projectRelationship: 'Horizon line shows phase progression; clouds mark blockers',
      informationBehavior: 'States appear as weather on horizon — inspect for detail',
      interactionGrammar: 'OPEN horizon detail; NAVIGATE to next clearing; DISMISS passed cloud',
      navigationBehavior: 'Pan horizon left/right between phases',
      hierarchyBehavior: 'ACTIVE = nearest clearing; EXPERIMENTAL = distant cloud',
      spatialBehavior: 'Foreground seat + background horizon depth',
      compositionBehavior: 'Wide cinematic horizon — not stacked modules',
      hostClientRelationship: 'Host frame around window; client sky and meter palette',
      responsivePhilosophy: 'Mobile: cropped horizon with swipe; Desktop: full vista + seat context',
      motionPhilosophy: 'Slow cloud drift; horizon brightens on phase complete',
      keyExperienceMoments: ['Blocker cloud appears', 'Clearing opens for founder action', 'Phase sunset'],
      genericTemplateAvoidanceStrategy: ['No vertical report scroll as primary', 'Interpret data as weather metaphors'],
      risks: ['Abstract horizon may need inspector fallback'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Horizon markers link to routes; inspector exposes raw timeline',
    },
  ],
  'THE PERSONAL ARCHIVE': [
    {
      name: 'THE DRAWER INDEX',
      centralThesis: 'Project intelligence lives in labeled drawers — founder pulls what matters now.',
      experienceMetaphor: 'Archive drawer index',
      whyItBelongsToSelectedTerritory: 'Personal saved-fragment logic scales to project artifact drawers.',
      whyItBelongsInsideSite00: 'Archive furniture inside SITE 00 project room.',
      viewerRole: 'Archivist opening the right drawer',
      projectRelationship: 'Drawers for formation, review, canon, experiments',
      informationBehavior: 'Drawers closed by default — open reveals fragments',
      interactionGrammar: 'OPEN drawer; INSPECT fragment; RETURN drawer to index',
      navigationBehavior: 'Drawer index grid — not sidebar',
      hierarchyBehavior: 'NEEDS FOUNDER = drawer ajar; HISTORICAL = locked drawer',
      spatialBehavior: 'Tactile furniture grid with depth on open',
      compositionBehavior: 'Open drawer dominates; index recedes',
      hostClientRelationship: 'Host handles room; client texture on drawer labels',
      responsivePhilosophy: 'Mobile: one drawer fullscreen; Desktop: index + open drawer side by side',
      motionPhilosophy: 'Drawer slide; fragment lift on inspect',
      keyExperienceMoments: ['New fragment filed', 'Founder opens review drawer', 'Canon drawer lock'],
      genericTemplateAvoidanceStrategy: ['No equal cards — drawers at varied prominence', 'No dashboard KPIs'],
      risks: ['Many drawers could feel like nested menus'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'Each drawer maps to route group; all data in fragments',
    },
    {
      name: 'THE BEDSIDE BOX',
      centralThesis: 'Intimate scatter of kept project moments — founder recognizes their own work patterns.',
      experienceMetaphor: 'Bedside box of kept fragments',
      whyItBelongsToSelectedTerritory: 'Personal archive intimacy — not corporate dashboard.',
      whyItBelongsInsideSite00: 'Box on nightstand inside SITE 00 project space.',
      viewerRole: 'Owner revisiting kept project moments',
      projectRelationship: 'Each generation/review is a kept object in the box',
      informationBehavior: 'Objects scattered with personal scale — pick up to read',
      interactionGrammar: 'PICK UP object; COMPARE two kept items; ARCHIVE to deep storage',
      navigationBehavior: 'Scatter field navigation — pinch/zoom on mobile',
      hierarchyBehavior: 'ACTIVE = object on top; SUPERSEDED = buried beneath',
      spatialBehavior: 'Intimate scatter — overlapping objects with depth',
      compositionBehavior: 'Hero object + intimate cluster',
      hostClientRelationship: 'Host room lighting; client material on objects',
      responsivePhilosophy: 'Mobile: stack of 3 hero objects; Desktop: full scatter field',
      motionPhilosophy: 'Object lift on select; settle on dismiss',
      keyExperienceMoments: ['New object added to box', 'Compare two experiments', 'Archive superseded'],
      genericTemplateAvoidanceStrategy: ['Avoid grid uniformity', 'Personal scale not enterprise table'],
      risks: ['Scatter can obscure blockers without attention signal'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Objects link to assets/routes; inspector lists all items',
    },
    {
      name: 'THE EVIDENCE VAULT',
      centralThesis: 'Canon and experiments stored in a vault — founder retrieves with provenance intact.',
      experienceMetaphor: 'Personal evidence vault',
      whyItBelongsToSelectedTerritory: 'Archive behavior → retrieval navigation with lineage.',
      whyItBelongsInsideSite00: 'Vault room inside SITE 00 — host security chrome on doors.',
      viewerRole: 'Custodian retrieving evidence with keys',
      projectRelationship: 'Vault sections for canon, experimental, historical',
      informationBehavior: 'Retrieval slots with lineage stamps — not flat lists',
      interactionGrammar: 'RETRIEVE slot; INSPECT lineage; PROMOTE to canon shelf',
      navigationBehavior: 'Vault aisle navigation between sections',
      hierarchyBehavior: 'CANONICAL = sealed shelf; EXPERIMENTAL = temp slot',
      spatialBehavior: 'Aisle depth with retrieval lighting',
      compositionBehavior: 'Retrieval spotlight + aisle context',
      hostClientRelationship: 'Host typography on vault metadata; client on artifact surfaces',
      responsivePhilosophy: 'Mobile: one aisle; Desktop: vault map with aisles',
      motionPhilosophy: 'Slot illuminate on approach; seal on canon',
      keyExperienceMoments: ['Retrieve experiment asset', 'Lineage inspect', 'Canon seal'],
      genericTemplateAvoidanceStrategy: ['No table rows as primary', 'Lineage as physical stamp'],
      risks: ['Vault could feel like file browser without metaphor strength'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'Slots map to content library and routes',
    },
  ],
  'THE ANNOTATED COPY': [
    {
      name: 'THE MARGIN DESK',
      centralThesis: 'Project knowledge accumulates in margins — layers of founder and system notes.',
      experienceMetaphor: 'Margin annotation desk',
      whyItBelongsToSelectedTerritory: 'Accumulation grammar — not destructive correction.',
      whyItBelongsInsideSite00: 'Desk inside SITE 00; margins are client expressive zone.',
      viewerRole: 'Reader accumulating margin notes',
      projectRelationship: 'Central project brief with growing margin layers',
      informationBehavior: 'Layers stack in margins — expand to read thread',
      interactionGrammar: 'EXPAND margin thread; DISMISS note; APPROVE layer',
      navigationBehavior: 'Scroll document with sticky margin columns on desktop',
      hierarchyBehavior: 'ACTIVE = latest margin thread; HISTORICAL = collapsed layers',
      spatialBehavior: 'Central column + flanking margin depth',
      compositionBehavior: 'Document center; margins as secondary depth',
      hostClientRelationship: 'Host UI on document chrome; client handwriting in margins',
      responsivePhilosophy: 'Mobile: margin threads as bottom sheets; Desktop: dual margin columns',
      motionPhilosophy: 'Layer peel on expand; thread collapse on dismiss',
      keyExperienceMoments: ['New annotation layer', 'Thread comparison', 'Approve margin canon'],
      genericTemplateAvoidanceStrategy: ['No card stack — margin threads only', 'Avoid KPI tiles'],
      risks: ['Margin density on mobile'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'Document sections map to routes; threads hold status detail',
    },
    {
      name: 'THE COMMENTARY STACK',
      centralThesis: 'Each project phase is a sheet in a stack — commentary accumulates between sheets.',
      experienceMetaphor: 'Stacked sheets with interleaved notes',
      whyItBelongsToSelectedTerritory: 'Annotation accumulation as physical stack behavior.',
      whyItBelongsInsideSite00: 'Stack on SITE 00 work surface.',
      viewerRole: 'Reviewer flipping annotated sheets',
      projectRelationship: 'Sheets = phases; notes = status and judgments',
      informationBehavior: 'Flip to next sheet; notes visible between layers',
      interactionGrammar: 'FLIP sheet; INSPECT interleave; REVISE note',
      navigationBehavior: 'Stack flip — not vertical scroll sections',
      hierarchyBehavior: 'FORMING = top sheet animating; COMPLETE = sheet filed',
      spatialBehavior: 'Stack depth with interleave shadows',
      compositionBehavior: 'Top sheet dominant; stack edge visible',
      hostClientRelationship: 'Host frame; client note styling',
      responsivePhilosophy: 'Mobile: single sheet + flip gesture; Desktop: stack + preview edge',
      motionPhilosophy: 'Sheet flip transition; note fade-in between',
      keyExperienceMoments: ['Phase sheet added', 'Founder revises note', 'Stack filed to canon'],
      genericTemplateAvoidanceStrategy: ['Replace section cards with sheets', 'No equal-weight tiles'],
      risks: ['Flip gesture discoverability'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Sheets cover all routes; inspector shows flat data',
    },
    {
      name: 'THE THREAD WALL',
      centralThesis: 'Living commentary threads pin to a wall — founder follows conversation, not fields.',
      experienceMetaphor: 'Pinned commentary thread wall',
      whyItBelongsToSelectedTerritory: 'Social annotation → spatial thread retrieval.',
      whyItBelongsInsideSite00: 'Wall inside SITE 00 project gallery.',
      viewerRole: 'Participant following pinned threads',
      projectRelationship: 'Threads for experiments, reviews, blockers',
      informationBehavior: 'Threads pin by urgency — unspool to read',
      interactionGrammar: 'UNSPOOL thread; FILTER by topic; PROMOTE pin to canon',
      navigationBehavior: 'Pan wall; tap pin for thread',
      hierarchyBehavior: 'NEEDS FOUNDER = red pin; EXPERIMENTAL = yellow pin',
      spatialBehavior: 'Wall collage — varied pin scale',
      compositionBehavior: 'Hero pin + satellite threads',
      hostClientRelationship: 'Host pin metadata; client thread visual',
      responsivePhilosophy: 'Mobile: priority pin list becoming wall on tablet+',
      motionPhilosophy: 'Pin pulse; thread unspool animation',
      keyExperienceMoments: ['New thread pinned', 'Blocker pin escalates', 'Canon pin sealed'],
      genericTemplateAvoidanceStrategy: ['No status table', 'Threads not rows'],
      risks: ['Wall could become chaotic without filter'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Pins link to routes and assets',
    },
  ],
  'THE ROOM WHERE IT HAPPENS': [
    {
      name: 'THE FORMATION FLOOR',
      centralThesis: 'Creative work happens on an open floor — founder walks active production zones.',
      experienceMetaphor: 'Open formation floor with live zones',
      whyItBelongsToSelectedTerritory: 'Process room — where generation actually happens.',
      whyItBelongsInsideSite00: 'Floor inside SITE 00 industrial shell.',
      viewerRole: 'Floor manager walking active zones',
      projectRelationship: 'Zones for formation, review, canon staging',
      informationBehavior: 'Live zones show active processes — static in inspector',
      interactionGrammar: 'ENTER zone; INSPECT run; APPROVE output',
      navigationBehavior: 'Walk floor plan — spatial zones',
      hierarchyBehavior: 'ACTIVE = lit zone; BLOCKED = dark zone with alert',
      spatialBehavior: 'Floor plan with zone lighting',
      compositionBehavior: 'Active zone spotlight; peripheral dormant zones dim',
      hostClientRelationship: 'Host floor infrastructure; client lighting in zones',
      responsivePhilosophy: 'Mobile: one zone fullscreen; Desktop: floor plan overview',
      motionPhilosophy: 'Zone lights pulse when forming; approval brightens zone',
      keyExperienceMoments: ['Formation starts in zone', 'Founder enters review zone', 'Canon staging'],
      genericTemplateAvoidanceStrategy: ['No dashboard modules — zones only', 'Process metaphor not cards'],
      risks: ['Floor metaphor needs clear zone labels'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'Zones map to formation/review routes',
    },
    {
      name: 'THE BACKSTAGE PASS',
      centralThesis: 'Founder holds backstage access — see process behind the public project face.',
      experienceMetaphor: 'Backstage corridor with labeled doors',
      whyItBelongsToSelectedTerritory: 'Room/access behavior → spatial navigation to process.',
      whyItBelongsInsideSite00: 'Backstage within SITE 00 — public shell vs backstage doors.',
      viewerRole: 'Backstage visitor with pass',
      projectRelationship: 'Doors to formation, experiments, lineage',
      informationBehavior: 'Doors show live/rehearsal/complete states on placard',
      interactionGrammar: 'OPEN door; PEEK without entering; RETURN to corridor',
      navigationBehavior: 'Corridor walk — doors on sides',
      hierarchyBehavior: 'LIVE = door open with light; WAITING = closed placard',
      spatialBehavior: 'Corridor depth with door rhythm',
      compositionBehavior: 'Corridor perspective — next door draws eye',
      hostClientRelationship: 'Host corridor architecture; client placards',
      responsivePhilosophy: 'Mobile: one door at a time; Desktop: corridor perspective',
      motionPhilosophy: 'Door light spill; placard flip on state change',
      keyExperienceMoments: ['Live formation door opens', 'Founder peeks review', 'Corridor return'],
      genericTemplateAvoidanceStrategy: ['No tab nav — doors only', 'Avoid SaaS sidebar'],
      risks: ['Corridor could feel like menu list'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'Each door is a route; corridor always reachable',
    },
    {
      name: 'THE LIVE STUDIO',
      centralThesis: 'Project home is a studio with live feeds — founder watches work happen.',
      experienceMetaphor: 'Live studio with feeds and worktables',
      whyItBelongsToSelectedTerritory: 'Process visibility as studio broadcast behavior.',
      whyItBelongsInsideSite00: 'Studio inside SITE 00 location.',
      viewerRole: 'Studio director monitoring feeds',
      projectRelationship: 'Feeds for generation, review queue, canon output',
      informationBehavior: 'Live feeds update; tables hold artifacts in progress',
      interactionGrammar: 'TUNE feed; INSPECT table; CUT to review',
      navigationBehavior: 'Switch feeds — not page sections',
      hierarchyBehavior: 'LIVE = feed active; FORMING = table work in progress',
      spatialBehavior: 'Studio with feed wall + work tables',
      compositionBehavior: 'Hero feed + secondary tables',
      hostClientRelationship: 'Host studio infrastructure; client set dressing',
      responsivePhilosophy: 'Mobile: single feed focus; Desktop: feed wall + tables',
      motionPhilosophy: 'Feed tick; table spotlight on founder select',
      keyExperienceMoments: ['Generation feed live', 'Switch to review', 'Canon output table'],
      genericTemplateAvoidanceStrategy: ['No KPI dashboard', 'Feeds not metric tiles'],
      risks: ['Live metaphor needs idle state handling'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Feeds link to async jobs and routes',
    },
  ],
  'THE INDEX': [
    {
      name: 'THE TAXONOMY ATLAS',
      centralThesis: 'Project knowledge mapped as explorable taxonomy — founder navigates by classification.',
      experienceMetaphor: 'Taxonomy atlas with zoomable regions',
      whyItBelongsToSelectedTerritory: 'Index/taxonomy behavior → information architecture navigation.',
      whyItBelongsInsideSite00: 'Atlas table inside SITE 00 research room.',
      viewerRole: 'Cartographer navigating project taxonomy',
      projectRelationship: 'Regions for concepts, assets, canon, experiments',
      informationBehavior: 'Zoom region to reveal entries — list in inspector only',
      interactionGrammar: 'ZOOM region; FILTER taxonomy; JUMP to entry',
      navigationBehavior: 'Pan/zoom atlas — not vertical sections',
      hierarchyBehavior: 'CANONICAL = locked region; EXPERIMENTAL = dotted border region',
      spatialBehavior: 'Map plane with labeled regions',
      compositionBehavior: 'Active region expanded; context regions visible',
      hostClientRelationship: 'Host atlas frame; client region color from world palette',
      responsivePhilosophy: 'Mobile: region stack with drill-down; Desktop: full atlas',
      motionPhilosophy: 'Zoom transition; region highlight on founder task',
      keyExperienceMoments: ['Drill into concept region', 'Jump to asset entry', 'Canon region lock'],
      genericTemplateAvoidanceStrategy: ['No data grid primary', 'Map not card dashboard'],
      risks: ['Atlas complexity on small screens'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Regions aggregate routes; entries link to detail',
    },
    {
      name: 'THE CARD CATALOG',
      centralThesis: 'Every project artifact has a catalog card — founder pulls cards, not rows.',
      experienceMetaphor: 'Library card catalog drawers',
      whyItBelongsToSelectedTerritory: 'Index as physical catalog retrieval — justified card primitive.',
      whyItBelongsInsideSite00: 'Catalog furniture in SITE 00 library room.',
      viewerRole: 'Researcher pulling catalog cards',
      projectRelationship: 'Cards for territories, assets, judgments, phases',
      informationBehavior: 'Search catalog → pull card → inspect detail sheet',
      interactionGrammar: 'SEARCH; PULL card; RETURN to catalog',
      navigationBehavior: 'Catalog drawers by category',
      hierarchyBehavior: 'NEEDS FOUNDER = flagged card edge; SUPERSEDED = archived drawer',
      spatialBehavior: 'Catalog cabinet with pull animation',
      compositionBehavior: 'Pulled card central; cabinet recedes',
      hostClientRelationship: 'Host catalog labels; client card typography',
      responsivePhilosophy: 'Mobile: search-first card results; Desktop: cabinet + pulled card',
      motionPhilosophy: 'Card pull; drawer close on return',
      keyExperienceMoments: ['Search experiment card', 'Pull review card', 'Archive superseded'],
      genericTemplateAvoidanceStrategy: ['Cards as catalog objects not dashboard tiles', 'Varied card sizes'],
      risks: ['Catalog could feel retro without concept commitment'],
      implementationFeasibility: 'HIGH',
      functionalPreservationRationale: 'Cards index all entities; routes on detail sheet',
    },
    {
      name: 'THE REGISTRY HALL',
      centralThesis: 'Canonical registry hall — founder walks registers of what is official vs experimental.',
      experienceMetaphor: 'Registry hall with bound volumes',
      whyItBelongsToSelectedTerritory: 'Index canon vs experimental classification at architectural scale.',
      whyItBelongsInsideSite00: 'Hall inside SITE 00 institutional wing.',
      viewerRole: 'Registrar verifying official records',
      projectRelationship: 'Volumes for canon, experiments, lineage',
      informationBehavior: 'Volumes on shelves — open to read registry page',
      interactionGrammar: 'OPEN volume; STAMP approval; COMPARE registry entries',
      navigationBehavior: 'Walk hall between volume shelves',
      hierarchyBehavior: 'CANONICAL = sealed volume; EXPERIMENTAL = open folio',
      spatialBehavior: 'Hall perspective with shelf rhythm',
      compositionBehavior: 'Open volume foreground; hall depth behind',
      hostClientRelationship: 'Host hall architecture; client volume binding colors',
      responsivePhilosophy: 'Mobile: one volume; Desktop: hall with open volume desk',
      motionPhilosophy: 'Volume open; stamp on canon approve',
      keyExperienceMoments: ['Open experiment folio', 'Compare registry entries', 'Seal canon volume'],
      genericTemplateAvoidanceStrategy: ['No SaaS table view primary', 'Registry not spreadsheet'],
      risks: ['Hall needs strong mobile volume focus'],
      implementationFeasibility: 'MEDIUM',
      functionalPreservationRationale: 'Volumes wrap content library and canon routes',
    },
  ],
};

export function buildExperienceConceptsForTerritory(params: {
  territory: CreativeConceptTerritory;
  world: WorldExpressionSystem;
  appetiteLineage: string | null;
  conceptIndex?: 1 | 2 | 3;
}): ExperienceConcept[] {
  const seeds = TERRITORY_EXPERIENCE_SEEDS[params.territory.directionName as CanonicalNdxbookDirectionName];
  if (!seeds) {
    throw new Error(`No experience concept seeds for territory ${params.territory.directionName}`);
  }

  if (params.conceptIndex) {
    const idx = params.conceptIndex - 1;
    return [baseConcept(params.conceptIndex, params.territory, seeds[idx], params.appetiteLineage)];
  }

  return seeds.slice(0, EXPERIENCE_CONCEPT_COUNT).map((seed, i) =>
    baseConcept((i + 1) as 1 | 2 | 3, params.territory, seed, params.appetiteLineage),
  );
}

export function experienceConceptIsolationValid(concepts: ExperienceConcept[]): boolean {
  return concepts.every((c) => c.formedInIsolation === true) && concepts.length === EXPERIENCE_CONCEPT_COUNT;
}
