/**
 * P0.5C.5A — Generic Studio World Generation Authority constants.
 */

export const GENERATION_AUTHORITY_MODEL_V1 = 'GENERATION_AUTHORITY_MODEL_V1' as const;

export const GENERATION_MODES = ['REGENERATE_CURRENT', 'REPLAY_GENERATION'] as const;

export const PROMPT_FRESHNESS_STATES = [
  'CURRENT',
  'STALE_CONTRACT',
  'STALE_METHODOLOGY',
  'STALE_FOUNDER_REVISION',
  'STALE_GOVERNANCE',
  'LEGACY_UNKNOWN',
  'INVALID',
] as const;

export const LEGACY_SNAPSHOT_CLASSIFICATIONS = [
  'CURRENT',
  'STALE_C4A',
  'STALE_C4B',
  'STALE_C5',
  'STALE_PUBLIC_COPY',
  'LEGACY_UNKNOWN',
] as const;

export const GENERATION_CONTRACT_COVERAGE_LAYERS = [
  'CHARACTER',
  'EDITORIAL_DECISION',
  'FIRST_SLIDE_INFORMATION_ARCHITECTURE',
  'TYPOGRAPHIC_GOVERNANCE',
  'CULTURAL_IMAGE_PARTICIPATION',
  'VISUAL_SUBJECT_MATTER',
  'HUMOR_CHARACTER_RETENTION',
  'ART_BOARD_MATERIALITY',
  'CANVAS_AS_OBJECT',
  'HUMAN_MADE_MARKS',
  'SIGNATURE_LIME',
  'PUBLIC_AUTHORSHIP',
  'INTERNAL_LABEL_QUARANTINE',
  'CURRENT_COPY',
  'NEGATIVE_CONSTRAINTS',
] as const;

export const PUBLIC_AUTHORSHIP_FAILURE_STATES = [
  'FAIL_THIRD_PERSON_NDX',
  'FAIL_ANALYTICAL_DISTANCE',
  'FAIL_INTERNAL_LABEL_LEAK',
  'FAIL_PRODUCTION_METADATA_AS_COPY',
  'FAIL_CHARACTER_DESCRIBED_FROM_OUTSIDE',
  'FAIL_CORPORATE_EDITORIAL_VOICE',
  'FAIL_AI_ANALYST_VOICE',
] as const;

export const GENERATION_AUTHORITY_MODEL_IMPLEMENTED = true as const;
export const PROMPT_SNAPSHOT_IMMUTABILITY_IMPLEMENTED = true as const;
export const PROMPT_FRESHNESS_EVALUATION_IMPLEMENTED = true as const;
export const CONTRACT_MUTATION_INVALIDATES_PROMPT = true as const;
export const GENERATION_CONTRACT_COVERAGE_GATE_IMPLEMENTED = true as const;
export const STALE_PROMPT_GENERATION_BLOCKED = true as const;
export const AUTOMATIC_FAL_REGENERATION = false as const;
export const V2_4_CREATED = false as const;
export const BRAND_CHARACTER_MUTATED = false as const;
export const BRAND_CANON_MUTATED = false as const;
export const PRODUCT_EXPRESSION_IMPLEMENTED = false as const;
export const WORLD_FORMATION_IMPLEMENTED = false as const;
