/**
 * Deterministic Creative Concept Territory seeds for canonical six directions.
 * Concept-first formation — visual systems derive afterward, not before.
 */

import type { CanonicalNdxbookDirectionName } from '../canonicalCreativeRangeConstants.js';
import { CONCEPT_TERRITORY_METHODOLOGY_VERSION } from './conceptTerritoryConstants.js';
import type { CreativeConceptTerritory, WorldExpressionSystem } from './conceptTerritoryTypes.js';

const ts = () => new Date().toISOString();

type SeedPair = {
  territory: Omit<CreativeConceptTerritory, 'territoryId' | 'createdAt' | 'methodologyVersion' | 'version'>;
  expression: Omit<
    WorldExpressionSystem,
    'expressionSystemId' | 'territoryId' | 'createdAt' | 'methodologyVersion' | 'version'
  >;
};

const SEEDS: Record<CanonicalNdxbookDirectionName, SeedPair> = {
  'THE MARKED-UP COPY': {
    territory: {
      brandSlug: 'ndxbook',
      sourceDirectionId: 'dir-marked-up-copy',
      directionName: 'THE MARKED-UP COPY',
      name: 'Destructive Editorial Revision',
      centralConcept: 'Credit truth arrives through visible correction — the document is wrong until marked right.',
      bigCreativeIdea: 'Financial literacy as editorial surgery on official language.',
      worldPremise: 'A reader inherits a flawed official statement and must see exactly what was corrected.',
      conceptualMetaphor: 'Red-pen autopsy of institutional copy',
      viewerRole: 'Skeptical editor inheriting bad paperwork',
      audienceExperience: 'Watch confidence transfer from wrong claim to corrected claim',
      brandRole: 'The friend who marks up the nonsense before you sign',
      emotionalMechanism: 'Relief through visible correction',
      culturalMechanism: 'Institutional language deserves public markup',
      contentMechanism: 'Strike-through → replacement → proof',
      whatMakesThisAWorld: 'Correction marks are the narrative engine, not decoration',
      whyThisBelongsToBrand: 'NDXBOOK challenges lazy financial assumptions with evidence',
      whyThisIsNotJustAStyle: 'Without correction behavior, this is just typography on paper',
      primaryVisualMechanism: 'Destructive revision marks on official copy',
      secondaryVisualMechanisms: ['evidence callouts', 'margin arguments'],
      primaryArtifactFamily: 'official statements under revision',
      contentBehavior: 'Each post removes one dangerous assumption',
      requiredSignals: ['visible correction', 'institutional copy under challenge'],
      forbiddenSignals: ['passive annotation without stakes', 'decorative highlights'],
      ownedVisualMechanisms: ['destructive revision', 'strike-through authority'],
      antiCousinRules: [
        'Never accumulate commentary layers — that belongs to THE ANNOTATED COPY',
        'Never index or catalog — that belongs to THE INDEX',
      ],
      antiCloneRules: ['Do not reuse annotated-copy accumulation grammar'],
      conceptualDistanceFromSiblingTerritories: [
        'Correction-first vs accumulation-first vs countdown-first vs archive-first',
      ],
      sourceLineage: ['canonical-six', 'concept-territory-v1-seed'],
    },
    expression: {
      directionName: 'THE MARKED-UP COPY',
      typographySystem: 'Condensed grotesk display for institutional copy; monospace for corrected values',
      paletteSystem: 'Warm paper field, black authority text, red correction, single functional accent',
      materialSystem: 'Printed institutional document — not scrapbook, not interface',
      imagerySystem: 'Document fragments and typographic evidence — no lifestyle photography',
      compositionSystem: 'Dense editorial block with surgical correction zones',
      graphicGrammar: 'Strike-through, replacement arrows, margin proof marks',
      artifactSystem: 'Statements, notices, forms under revision',
      motionSystem: 'Correction reveals in sequence',
      socialBehavior: 'Saveable proof-of-correction posts',
      recognitionMechanisms: ['red correction on official copy'],
      signatureBehaviors: ['one dangerous line corrected per slide'],
      forbiddenSiblingBehaviors: ['layered annotation stacks', 'countdown numerics as hero'],
      derivationEvidence: ['Concept requires destructive revision — palette follows correction semantics'],
      conceptAlignment: 'HIGH',
      orthogonalityEvidence: ['Owns correction grammar; cousins forbidden from strike-through authority'],
      nativeProofFormat: 'CAROUSEL_SEQUENCE',
    },
  },
  'THE COUNTDOWN ROOM': {
    territory: {
      brandSlug: 'ndxbook',
      sourceDirectionId: 'dir-countdown-room',
      directionName: 'THE COUNTDOWN ROOM',
      name: 'Temporal Pressure Chamber',
      centralConcept: 'Credit behavior is a countdown — time and thresholds create urgency without panic.',
      bigCreativeIdea: 'Financial decisions as rooms where the clock is always visible.',
      worldPremise: 'The audience stands inside a measurable window before consequence.',
      conceptualMetaphor: 'Deadline room with visible meters',
      viewerRole: 'Person inside a finite window',
      audienceExperience: 'Feel time compress around a single credit decision',
      brandRole: 'Calm operator of the countdown — not alarmist, precise',
      emotionalMechanism: 'Focused urgency',
      culturalMechanism: 'Adult relationship with deadlines',
      contentMechanism: 'Threshold → window → action',
      whatMakesThisAWorld: 'Temporal meters drive every layout',
      whyThisBelongsToBrand: 'NDXBOOK respects intelligence — urgency without hype',
      whyThisIsNotJustAStyle: 'Remove the countdown and the concept disappears',
      primaryVisualMechanism: 'Visible temporal meters and threshold markers',
      secondaryVisualMechanisms: ['room-scale spatial framing'],
      primaryArtifactFamily: 'timers, meters, threshold panels',
      contentBehavior: 'Each post names one window that matters',
      requiredSignals: ['countdown or threshold legibility'],
      forbiddenSignals: ['static document markup', 'scrapbook accumulation'],
      ownedVisualMechanisms: ['countdown numerics', 'threshold rooms'],
      antiCousinRules: [
        'Never use editorial correction marks — belongs to MARKED-UP COPY',
        'Never stage process rooms — belongs to ROOM WHERE IT HAPPENS',
      ],
      antiCloneRules: ['No paper-document default'],
      conceptualDistanceFromSiblingTerritories: ['Time-native vs document-native vs archive-native'],
      sourceLineage: ['canonical-six', 'concept-territory-v1-seed'],
    },
    expression: {
      directionName: 'THE COUNTDOWN ROOM',
      typographySystem: 'Monumental numeric display + restrained sans supporting copy',
      paletteSystem: 'Cool industrial field, high-contrast meter accents, amber threshold warnings',
      materialSystem: 'Spatial/environmental — painted walls, panels, physical meters',
      imagerySystem: 'Environmental stills of measurement — not documents',
      compositionSystem: 'Monumental single-statement with peripheral meters',
      graphicGrammar: 'Threshold lines, meter ticks, window brackets',
      artifactSystem: 'Timers, gauges, deadline panels',
      motionSystem: 'Tick-down emphasis',
      socialBehavior: 'Hook-first urgency tiles',
      recognitionMechanisms: ['large countdown numerics'],
      signatureBehaviors: ['one threshold per execution'],
      forbiddenSiblingBehaviors: ['handwritten margin notes', 'index taxonomy grids'],
      derivationEvidence: ['Concept is time-native — paper is optional, not default'],
      conceptAlignment: 'HIGH',
      orthogonalityEvidence: ['Owns countdown numerics'],
      nativeProofFormat: 'FEED_TILE',
    },
  },
  'THE PERSONAL ARCHIVE': {
    territory: {
      brandSlug: 'ndxbook',
      sourceDirectionId: 'dir-personal-archive',
      directionName: 'THE PERSONAL ARCHIVE',
      name: 'Intimate Saved Evidence',
      centralConcept: 'Credit wisdom lives in what you kept — fragments of your own financial life.',
      bigCreativeIdea: 'The feed as a personal archive drawer, not a brand magazine.',
      worldPremise: 'The viewer curates their own evidence of money behavior.',
      conceptualMetaphor: 'Bedside archive box of kept receipts and notes',
      viewerRole: 'Archivist of personal financial life',
      audienceExperience: 'Recognize your own kept objects and habits',
      brandRole: 'Curator who respects private financial life',
      emotionalMechanism: 'Intimate recognition',
      culturalMechanism: 'Personal finance is private, not performative',
      contentMechanism: 'Found object → meaning → habit',
      whatMakesThisAWorld: 'Personal saved fragments are the primary artifacts',
      whyThisBelongsToBrand: 'NDXBOOK meets people in real life, not abstraction',
      whyThisIsNotJustAStyle: 'Without personal saved logic, this becomes generic collage',
      primaryVisualMechanism: 'Intimate scatter of personally kept fragments',
      secondaryVisualMechanisms: ['handwritten personal notes', ' worn paper edges'],
      primaryArtifactFamily: 'saved receipts, cards, notes, screenshots',
      contentBehavior: 'One kept object unlocks one habit insight',
      requiredSignals: ['personal scale', 'saved-fragment logic'],
      forbiddenSignals: ['institutional statement markup', 'public index taxonomy'],
      ownedVisualMechanisms: ['personal scatter archive', 'intimate scale'],
      antiCousinRules: [
        'Never build public taxonomies — belongs to THE INDEX',
        'Never stage countdown rooms',
      ],
      antiCloneRules: ['No dense institutional tables'],
      conceptualDistanceFromSiblingTerritories: ['Private scatter vs public index vs editorial correction'],
      sourceLineage: ['canonical-six', 'concept-territory-v1-seed'],
    },
    expression: {
      directionName: 'THE PERSONAL ARCHIVE',
      typographySystem: 'Humanist sans + handwritten personal voice for notes',
      paletteSystem: 'Muted domestic tones, soft paper, ink black, one warm accent',
      materialSystem: 'Worn paper, desk surfaces, personal ephemera',
      imagerySystem: 'Still life of kept objects — not environments or UI',
      compositionSystem: 'Personal scatter with focal object',
      graphicGrammar: 'Circles on personal notes, underlines on kept copy — not institutional red pen',
      artifactSystem: 'Receipts, cards, phone screenshots, sticky notes',
      motionSystem: 'Gentle reveal of kept object',
      socialBehavior: 'Story frames and saveable personal references',
      recognitionMechanisms: ['intimate object scatter'],
      signatureBehaviors: ['one personal artifact per post'],
      forbiddenSiblingBehaviors: ['public catalog grids', 'countdown meters'],
      derivationEvidence: ['Concept requires personal scale — not institutional document'],
      conceptAlignment: 'HIGH',
      orthogonalityEvidence: ['Owns intimate scatter'],
      nativeProofFormat: 'STORY_FRAME',
    },
  },
  'THE ANNOTATED COPY': {
    territory: {
      brandSlug: 'ndxbook',
      sourceDirectionId: 'dir-annotated-copy',
      directionName: 'THE ANNOTATED COPY',
      name: 'Accumulated Commentary Layer',
      centralConcept: 'Understanding deepens through layers of commentary on shared text — not destruction of it.',
      bigCreativeIdea: 'Reading credit content like a seminar margin that keeps growing.',
      worldPremise: 'The same passage accumulates human commentary over time.',
      conceptualMetaphor: 'Seminar margin that fills with insight',
      viewerRole: 'Reader joining an ongoing annotated conversation',
      audienceExperience: 'Depth through accumulated notes, not single correction',
      brandRole: 'Facilitator of layered sense-making',
      emotionalMechanism: 'Curiosity through accumulation',
      culturalMechanism: 'Collective reading behavior',
      contentMechanism: 'Passage → note → deeper note → insight',
      whatMakesThisAWorld: 'Layered annotation is the narrative mechanic',
      whyThisBelongsToBrand: 'NDXBOOK rewards second-read intelligence',
      whyThisIsNotJustAStyle: 'Single strike-through correction belongs elsewhere',
      primaryVisualMechanism: 'Accumulated annotation layers on shared copy',
      secondaryVisualMechanisms: ['sticky note stacks', 'highlight bands'],
      primaryArtifactFamily: 'shared passages with growing margin commentary',
      contentBehavior: 'Each slide adds a commentary layer',
      requiredSignals: ['layer accumulation', 'shared base copy'],
      forbiddenSignals: ['destructive strike-through authority', 'countdown meters'],
      ownedVisualMechanisms: ['annotation accumulation', 'highlight layering'],
      antiCousinRules: [
        'Never use destructive correction as primary — belongs to MARKED-UP COPY',
        'Never replace passage with new headline — accumulation requires stable base text',
      ],
      antiCloneRules: ['No single-red-pen correction hero'],
      conceptualDistanceFromSiblingTerritories: ['Accumulation vs correction vs countdown'],
      sourceLineage: ['canonical-six', 'concept-territory-v1-seed'],
    },
    expression: {
      directionName: 'THE ANNOTATED COPY',
      typographySystem: 'Serif passage voice + handwritten margin + sans metadata',
      paletteSystem: 'Cool white field, blue handwriting, yellow highlight bands, black passage text',
      materialSystem: 'Textbook/paper seminar — layered, not torn',
      imagerySystem: 'Typographic passage as hero — minimal photography',
      compositionSystem: 'Stable passage block with expanding margin bands',
      graphicGrammar: 'Highlights, margin arrows, sticky notes, circles — not strike-through',
      artifactSystem: 'Passages, margin notes, sticky stacks',
      motionSystem: 'Layer-add transitions',
      socialBehavior: 'Carousel sequence adding commentary depth',
      recognitionMechanisms: ['blue handwriting on stable passage'],
      signatureBehaviors: ['base copy persists while notes accumulate'],
      forbiddenSiblingBehaviors: ['destructive red correction', 'index taxonomy'],
      derivationEvidence: ['Concept requires accumulation — palette supports highlight layering'],
      conceptAlignment: 'HIGH',
      orthogonalityEvidence: ['Distinct from correction-first cousin'],
      nativeProofFormat: 'CAROUSEL_SEQUENCE',
    },
  },
  'THE ROOM WHERE IT HAPPENS': {
    territory: {
      brandSlug: 'ndxbook',
      sourceDirectionId: 'dir-room-where-it-happens',
      directionName: 'THE ROOM WHERE IT HAPPENS',
      name: 'Process Access Theater',
      centralConcept: 'Credit outcomes happen in rooms — the audience witnesses process, not just results.',
      bigCreativeIdea: 'Pull back the wall and show the room where the decision gets made.',
      worldPremise: 'Financial behavior is spatial — you enter, observe, leave changed.',
      conceptualMetaphor: 'Behind-the-wall process room',
      viewerRole: 'Witness granted access to the process room',
      audienceExperience: 'Spatial access to how a credit outcome happens',
      brandRole: 'Guide who opens the door without sensationalism',
      emotionalMechanism: 'Insider clarity',
      culturalMechanism: 'Demystify without dumbing down',
      contentMechanism: 'Room → process → visible outcome',
      whatMakesThisAWorld: 'Spatial process access is non-negotiable',
      whyThisBelongsToBrand: 'NDXBOOK explains mechanisms, not vibes',
      whyThisIsNotJustAStyle: 'Without spatial process, this collapses into generic editorial',
      primaryVisualMechanism: 'Spatial staging of process and access',
      secondaryVisualMechanisms: ['doorway framing', 'workflow artifacts in situ'],
      primaryArtifactFamily: 'rooms, desks, doors, process artifacts in space',
      contentBehavior: 'Each post reveals one step inside the room',
      requiredSignals: ['spatial access', 'process visibility'],
      forbiddenSignals: ['abstract document-only layouts', 'pure countdown meters without space'],
      ownedVisualMechanisms: ['process room staging', 'access framing'],
      antiCousinRules: [
        'Never use abstract countdown chamber without spatial narrative — belongs to COUNTDOWN ROOM',
        'Never use personal bedside scatter — belongs to PERSONAL ARCHIVE',
      ],
      antiCloneRules: ['No pure typographic document default'],
      conceptualDistanceFromSiblingTerritories: ['Spatial process vs temporal meter vs personal scatter'],
      sourceLineage: ['canonical-six', 'concept-territory-v1-seed'],
    },
    expression: {
      directionName: 'THE ROOM WHERE IT HAPPENS',
      typographySystem: 'Bold sans signage + editorial subheads; no monospace institution voice',
      paletteSystem: 'Warm interior tones, practical neutrals, one access accent (not lime-default)',
      materialSystem: 'Interior surfaces — wood, paint, glass — not paper-first',
      imagerySystem: 'Environmental photography of process spaces',
      compositionSystem: 'Cinematic doorway / wall-dominant staging',
      graphicGrammar: 'Directional signage, floor markers, access labels',
      artifactSystem: 'Desks, doors, whiteboards, in-room tools',
      motionSystem: 'Door-open / walk-in reveals',
      socialBehavior: 'Reel-friendly spatial hooks',
      recognitionMechanisms: ['doorway/process staging'],
      signatureBehaviors: ['one process reveal per execution'],
      forbiddenSiblingBehaviors: ['countdown-only numerics', 'margin annotation stacks'],
      derivationEvidence: ['Concept is spatial-process-native'],
      conceptAlignment: 'HIGH',
      orthogonalityEvidence: ['Distinct from countdown chamber cousin'],
      nativeProofFormat: 'REEL_HOOK',
    },
  },
  'THE INDEX': {
    territory: {
      brandSlug: 'ndxbook',
      sourceDirectionId: 'dir-the-index',
      directionName: 'THE INDEX',
      name: 'Public Taxonomy of Credit Behavior',
      centralConcept: 'Credit knowledge becomes navigable through rigorous public indexing — not personal scrapbooks.',
      bigCreativeIdea: 'The brand as a living index you consult, not a magazine you flip through.',
      worldPremise: 'Every post adds or refines an entry in a shared taxonomy.',
      conceptualMetaphor: 'Library index card wall for credit behavior',
      viewerRole: 'Researcher consulting a public index',
      audienceExperience: 'Clarity through classification and lookup',
      brandRole: 'Indexer who respects structure',
      emotionalMechanism: 'Competence through organization',
      culturalMechanism: 'Shared reference culture',
      contentMechanism: 'Entry → cross-reference → implication',
      whatMakesThisAWorld: 'Taxonomic index structure drives layout',
      whyThisBelongsToBrand: 'NDXBOOK turns complexity into usable structure',
      whyThisIsNotJustAStyle: 'Without taxonomy logic, this is just grids',
      primaryVisualMechanism: 'Index taxonomy and cross-reference structure',
      secondaryVisualMechanisms: ['catalog numbers', 'entry cards'],
      primaryArtifactFamily: 'index cards, catalog entries, reference tables',
      contentBehavior: 'One index entry per post with cross-links',
      requiredSignals: ['taxonomy legibility', 'lookup behavior'],
      forbiddenSignals: ['intimate personal scatter', 'destructive correction drama'],
      ownedVisualMechanisms: ['index taxonomy', 'catalog cross-reference'],
      antiCousinRules: [
        'Never use personal bedside scatter — belongs to PERSONAL ARCHIVE',
        'Never use seminar margin accumulation as primary',
      ],
      antiCloneRules: ['No red-pen document correction hero'],
      conceptualDistanceFromSiblingTerritories: ['Public taxonomy vs private archive vs correction'],
      sourceLineage: ['canonical-six', 'concept-territory-v1-seed'],
    },
    expression: {
      directionName: 'THE INDEX',
      typographySystem: 'Neutral grotesk system + tabular numerics + small caps metadata',
      paletteSystem: 'Cool gray field, black type, one catalog accent (teal-leaning, not lime-default)',
      materialSystem: 'Card catalog / reference table — digital-native allowed',
      imagerySystem: 'Typography-first with optional object specimens as entries',
      compositionSystem: 'Strict modular catalog grid with deliberate breaks',
      graphicGrammar: 'Entry numbers, cross-ref arrows, bracket groups',
      artifactSystem: 'Index cards, catalog entries, reference tables',
      motionSystem: 'Entry flip / cross-ref highlight',
      socialBehavior: 'Saveable reference posts',
      recognitionMechanisms: ['catalog entry structure'],
      signatureBehaviors: ['one taxonomy entry per execution'],
      forbiddenSiblingBehaviors: ['personal scatter', 'countdown rooms'],
      derivationEvidence: ['Concept requires taxonomy — not paper-editorial default'],
      conceptAlignment: 'HIGH',
      orthogonalityEvidence: ['Owns public index grammar'],
      nativeProofFormat: 'SAVEABLE_REFERENCE_POST',
    },
  },
};

export function buildConceptTerritorySeed(
  directionName: CanonicalNdxbookDirectionName,
): { territory: CreativeConceptTerritory; expression: WorldExpressionSystem } {
  const seed = SEEDS[directionName];
  const territoryId = `territory-${seed.territory.sourceDirectionId}`;
  const territory: CreativeConceptTerritory = {
    ...seed.territory,
    territoryId,
    methodologyVersion: CONCEPT_TERRITORY_METHODOLOGY_VERSION,
    version: 1,
    createdAt: ts(),
  };
  const expression: WorldExpressionSystem = {
    ...seed.expression,
    expressionSystemId: `expression-${seed.territory.sourceDirectionId}`,
    territoryId,
    methodologyVersion: CONCEPT_TERRITORY_METHODOLOGY_VERSION,
    version: 1,
    createdAt: ts(),
  };
  return { territory, expression };
}

export function buildAllConceptTerritorySeeds(): {
  territories: CreativeConceptTerritory[];
  expressionSystems: WorldExpressionSystem[];
} {
  const territories: CreativeConceptTerritory[] = [];
  const expressionSystems: WorldExpressionSystem[] = [];
  for (const name of Object.keys(SEEDS) as CanonicalNdxbookDirectionName[]) {
    const { territory, expression } = buildConceptTerritorySeed(name);
    territories.push(territory);
    expressionSystems.push(expression);
  }
  return { territories, expressionSystems };
}
