/**
 * P0.5E.5 — Generic Character Continuity Pipeline constants.
 */

export const CHARACTER_CONTINUITY_PIPELINE_VERSION = 'CHARACTER_CONTINUITY_PIPELINE@P0.5E.5' as const;

export const BIBLE_STATUSES = [
  'BIBLE_NOT_INGESTED',
  'BIBLE_PARTIAL',
  'BIBLE_CHARACTER_READY',
  'BIBLE_VISUAL_READY',
  'BIBLE_IMAGE_GENERATION_READY',
  'BIBLE_VIDEO_GENERATION_READY',
  'BIBLE_VOICE_READY',
  'BIBLE_FULL_CONTINUITY_READY',
  'BIBLE_BLOCKED',
] as const;

export const BIBLE_SOURCE_TYPES = [
  'STRUCTURED_RECORD',
  'JSON_EXPORT',
  'DOCUMENT_TEXT',
  'DISCOVERY_SYNTHESIS',
  'CONTINUITY_RECORD',
  'FOUNDER_AMENDMENT',
  'MOCK_FIXTURE',
] as const;

export const ANCHOR_CLASSES = [
  'FACE_GEOMETRY',
  'SKIN_CHARACTERISTICS',
  'AGE',
  'BODY_PROPORTIONS',
  'DISTINGUISHING_FEATURE',
  'HAIRLINE',
  'EYE_CHARACTERISTICS',
  'NOSE_CHARACTERISTICS',
  'LIP_CHARACTERISTICS',
  'JAW_CHARACTERISTICS',
  'BROW_CHARACTERISTICS',
  'VOICE_IDENTITY',
  'GESTURE_SIGNATURE',
  'MOVEMENT_SIGNATURE',
] as const;

export const VARIATION_CLASSES = [
  'LOCKED',
  'TIGHT_RANGE',
  'CONTROLLED_RANGE',
  'FREE_WITHIN_CHARACTER',
  'SCENE_DEPENDENT',
  'WARDROBE_DEPENDENT',
  'HAIR_DEPENDENT',
  'EMOTIONAL_DEPENDENT',
] as const;

export const NEGATIVE_CONSTRAINT_CATEGORIES = [
  'FACE_DRIFT',
  'AGE_DRIFT',
  'SKIN_TONE_DRIFT',
  'BODY_DRIFT',
  'HAIR_OUTSIDE_APPROVED_RANGE',
  'WARDROBE_OUTSIDE_TASTE',
  'GLAM_COLLAPSE',
  'INFLUENCER_COLLAPSE',
  'GENERIC_AI_HOST',
  'WRONG_JEWELRY',
  'WRONG_MAKEUP',
  'WRONG_CAMERA_ENERGY',
  'WRONG_EMOTIONAL_TEMPERATURE',
  'WRONG_GESTURE_BEHAVIOR',
  'WRONG_VOICE_BEHAVIOR',
] as const;

export const REFERENCE_TYPES = [
  'MASTER_HEADSHOT_FRONT',
  'MASTER_HEADSHOT_3_4',
  'MASTER_PROFILE',
  'MASTER_FULL_BODY',
  'NEUTRAL_EXPRESSION',
  'SMILE',
  'LAUGH',
  'SKEPTICAL',
  'ANNOYED',
  'CURIOUS',
  'SERIOUS',
  'TIRED',
  'EXCITED',
  'WRONG_EMBARRASSED',
  'APPROVED_HAIR_VARIANT',
  'APPROVED_WARDROBE_VARIANT',
  'APPROVED_MOTION_REFERENCE',
  'APPROVED_VOICE_REFERENCE',
] as const;

export const REFERENCE_AUTHORITY_LEVELS = [
  'IDENTITY_HIGH',
  'IDENTITY_MEDIUM',
  'STYLE_ONLY',
  'EXPRESSION_ONLY',
  'HAIR_ONLY',
  'WARDROBE_ONLY',
  'GESTURE_ONLY',
  'CAMERA_ONLY',
  'CALIBRATION_ONLY',
] as const;

export const REFERENCE_PACK_READINESS = [
  'NONE',
  'PARTIAL',
  'IMAGE_READY',
  'VIDEO_READY',
  'MULTI_SCENE_READY',
  'TRAINING_READY',
] as const;

export const CONTINUITY_CATEGORIES = [
  'IDENTITY',
  'FACE',
  'SKIN',
  'BODY',
  'HAIR',
  'WARDROBE',
  'BEAUTY',
  'JEWELRY',
  'NAILS',
  'ACCESSORIES',
  'VOICE',
  'EXPRESSION',
  'GESTURE',
  'MOVEMENT',
  'CAMERA_RELATIONSHIP',
  'ENVIRONMENT_INTERACTION',
  'PROP_INTERACTION',
  'LIGHTING_TOLERANCE',
  'AGE_CONTINUITY',
  'NEGATIVE_IDENTITY_CONSTRAINTS',
] as const;

export const GENERATION_CONTINUITY_MODES = [
  'PROSE_ONLY_EXPLORATION',
  'REFERENCE_GUIDED',
  'IDENTITY_BOUND',
  'TRAINED_IDENTITY',
] as const;

export const SCHEMA_SUPPORT_STATES = [
  'SUPPORTED_VERIFIED',
  'SUPPORTED_PARTIAL',
  'SCHEMA_REVIEW_REQUIRED',
  'UNSUPPORTED',
  'DEPRECATED',
  'UNAVAILABLE',
] as const;

export const CONTINUITY_QA_RESULTS = [
  'PASS',
  'PASS_WITH_MINOR_VARIATION',
  'FOUNDER_REVIEW_REQUIRED',
  'FAIL_IDENTITY_DRIFT',
  'FAIL_FACE_DRIFT',
  'FAIL_SKIN_DRIFT',
  'FAIL_AGE_DRIFT',
  'FAIL_BODY_DRIFT',
  'FAIL_HAIR_OUT_OF_RANGE',
  'FAIL_WARDROBE_OUT_OF_CHARACTER',
  'FAIL_BEAUTY_OUT_OF_CHARACTER',
  'FAIL_GESTURE_OUT_OF_CHARACTER',
  'FAIL_MOVEMENT_OUT_OF_CHARACTER',
  'FAIL_CAMERA_RELATIONSHIP',
  'FAIL_AI_PRESENTER',
  'FAIL_INFLUENCER_COLLAPSE',
  'FAIL_CHARACTER_NOT_RECOGNIZABLE',
] as const;

export const BIBLE_INVALIDATION_OUTCOMES = [
  'UNAFFECTED',
  'SOFT_REVIEW_REQUIRED',
  'PROMPT_RECOMPILE_REQUIRED',
  'REFERENCE_RESELECT_REQUIRED',
  'FULL_REGENERATION_RECOMMENDED',
  'IDENTITY_INVALIDATED',
] as const;

export const FALLBACK_POLICY_OUTCOMES = [
  'FALLBACK_AVAILABLE',
  'FALLBACK_REQUIRES_FOUNDER_APPROVAL',
  'NO_SAFE_FALLBACK',
] as const;

export const PIPELINE_FAILURE_STATES = [
  'FAIL_BIBLE_NOT_APPROVED',
  'FAIL_BIBLE_INCOMPLETE',
  'FAIL_VISUAL_IDENTITY_NOT_CAST',
  'FAIL_REFERENCE_PACK_MISSING',
  'FAIL_REFERENCE_NOT_APPROVED',
  'FAIL_IDENTITY_ANCHORS_MISSING',
  'FAIL_PROVIDER_CAPABILITY_MISMATCH',
  'FAIL_UNSUPPORTED_PROVIDER_FIELD',
  'FAIL_PROMPT_ONLY_CONTINUITY_ASSUMED_SAFE',
  'FAIL_REFERENCE_AUTHORITY_CONFLICT',
  'FAIL_CHARACTER_BIBLE_VERSION_MISMATCH',
  'FAIL_SCENE_CONTRACT_STALE',
  'FAIL_REFERENCE_PACK_STALE',
  'FAIL_PROVIDER_SCHEMA_STALE',
  'FAIL_IDENTITY_DRIFT',
  'FAIL_CHARACTER_BEHAVIOR_DRIFT',
  'FAIL_VIDEO_FRAME_IDENTITY_DRIFT',
  'FAIL_MULTI_SCENE_CONTINUITY',
  'FAIL_AI_PRESENTER',
  'FAIL_INFLUENCER_COLLAPSE',
  'FAIL_AUTOMATIC_TRAINING',
  'FAIL_AUTOMATIC_GENERATION',
] as const;

/** Success criteria — P0.5E.5 sprint */
export const CHARACTER_BIBLE_INGESTION_PIPELINE_IMPLEMENTED = true as const;
export const CHARACTER_BIBLE_AUDIT_IMPLEMENTED = true as const;
export const CHARACTER_TRUTH_VS_VISUAL_READINESS_SEPARATED = true as const;
export const CHARACTER_CONTINUITY_BIBLE_IMPLEMENTED = true as const;
export const CHARACTER_IDENTITY_ANCHOR_SYSTEM_IMPLEMENTED = true as const;
export const CHARACTER_VARIATION_GOVERNANCE_IMPLEMENTED = true as const;
export const NEGATIVE_IDENTITY_CONSTRAINTS_IMPLEMENTED = true as const;
export const CHARACTER_REFERENCE_PACK_IMPLEMENTED = true as const;
export const REFERENCE_AUTHORITY_EVALUATION_IMPLEMENTED = true as const;
export const REFERENCE_PACK_READINESS_IMPLEMENTED = true as const;
export const CHARACTER_SCENE_CONTRACT_IMPLEMENTED = true as const;
export const CHARACTER_SCENE_COMPILER_IMPLEMENTED = true as const;
export const FAL_CHARACTER_CAPABILITY_REGISTRY_IMPLEMENTED = true as const;
export const FAL_MODEL_SCHEMA_DISCOVERY_SUPPORTED = true as const;
export const CHARACTER_GENERATION_MODEL_SELECTION_IMPLEMENTED = true as const;
export const PROVIDER_CHARACTER_GENERATION_CONTRACT_IMPLEMENTED = true as const;
export const MODEL_AWARE_CHARACTER_COMPILER_IMPLEMENTED = true as const;
export const REFERENCE_TO_VIDEO_SUPPORTED = true as const;
export const IMAGE_TO_VIDEO_SUPPORTED = true as const;
export const MULTI_REFERENCE_CHARACTER_SUPPORT = true as const;
export const IDENTITY_BINDING_SUPPORT = true as const;
export const PROMPT_ONLY_CONTINUITY_CLASSIFIED_AS_INSUFFICIENT_FOR_PRODUCTION = true as const;
export const PRE_CASTING_PIPELINE_MODE_IMPLEMENTED = true as const;
export const PRODUCTION_GENERATION_BLOCKED_UNTIL_CAST = true as const;
export const CHARACTER_CONTINUITY_QA_IMPLEMENTED = true as const;
export const IDENTITY_FIDELITY_EVALUATION_IMPLEMENTED = true as const;
export const CHARACTER_BEHAVIOR_FIDELITY_EVALUATION_IMPLEMENTED = true as const;
export const VIDEO_CONTINUITY_EVALUATION_IMPLEMENTED = true as const;
export const MULTI_SCENE_CONTINUITY_IMPLEMENTED = true as const;
export const CHARACTER_SCENE_STATE_IMPLEMENTED = true as const;
export const BOOK_CONTINUITY_CONTRACT_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_PIPELINE_ARCHITECTURE_IMPLEMENTED = true as const;
export const CHARACTER_BIBLE_VERSIONING_IMPLEMENTED = true as const;
export const CHARACTER_BIBLE_INVALIDATION_IMPLEMENTED = true as const;
export const CHARACTER_GENERATION_SNAPSHOT_IMPLEMENTED = true as const;
export const PROVIDER_FALLBACK_POLICY_IMPLEMENTED = true as const;
export const MODEL_BAKEOFF_ARCHITECTURE_IMPLEMENTED = true as const;
export const TRAINED_IDENTITY_ARCHITECTURE_IMPLEMENTED = true as const;
export const CHARACTER_TRAINING_READINESS_IMPLEMENTED = true as const;
export const CHARACTER_CONTINUITY_REVIEW_UX_IMPLEMENTED = true as const;
export const STUDIO_WORLD_GENERIC_CHARACTER_CONTINUITY_PIPELINE_IMPLEMENTED = true as const;
export const READY_TO_INGEST_APPROVED_CHARACTER_BIBLE = true as const;
export const READY_TO_ATTACH_CHARACTER_REFERENCE_PACK = true as const;
export const READY_FOR_PRODUCTION_CHARACTER_GENERATION = false as const;
export const FINAL_CHARACTER_FACE_SELECTED = false as const;
export const FINAL_CHARACTER_VISUAL_IDENTITY_FINALIZED = false as const;
export const CHARACTER_TRAINING_EXECUTED = false as const;
export const CHARACTER_PRODUCTION_GENERATION_EXECUTED = false as const;
export const FAL_REQUESTS_FOR_CHARACTER_GENERATION = 0 as const;
export const BRAND_CHARACTER_MUTATED = false as const;
export const BRAND_CANON_MUTATED = false as const;
export const PRODUCT_EXPRESSION_IMPLEMENTED = false as const;
export const WORLD_FORMATION_IMPLEMENTED = false as const;
export const AUTONOMOUS_PUBLISHING_ENABLED = false as const;
