#!/usr/bin/env npx tsx
/**
 * P0.UI.3E — Generate canonical V3 SVG files + asset manifest from reference geometry.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  NDX_ICON_GEOMETRY_V3,
  type RawReferenceLockedTrace,
} from '../../shared/site00-studio-world-ui/icons/p0ui3d/geometry/ndxIconGeometryV3ReferenceLocked.js';
import { P0_UI_3D_TARGET_ICONS } from '../../shared/site00-studio-world-ui/icons/p0ui3d/constants.js';
import type { NDXIconName } from '../../shared/site00-studio-world-ui/icons/types.js';

const ROOT = join(import.meta.dirname, '../..');
const SVG_DIR = join(ROOT, 'shared/site00-studio-world-ui/icons/ndx/v3');
const PUBLIC_DIR = join(ROOT, 'public/icons/ndx/v3');
const MANIFEST_PATH = join(ROOT, 'shared/site00-studio-world-ui/icons/p0ui3e/manifest.generated.json');

/** Registry icon name → canonical SVG filename */
export const NDX_V3_SVG_FILENAME: Record<string, string> = {
  overview: 'overview.svg',
  campaigns: 'campaigns.svg',
  content_ops: 'content-ops.svg',
  lab: 'lab.svg',
  more: 'more.svg',
  notifications: 'notifications.svg',
  ellipsis: 'project-menu.svg',
  project_overview: 'project-overview.svg',
  project_settings: 'project-settings.svg',
  back_to_projects: 'back-to-projects.svg',
  return_to_origin: 'return-to-origin.svg',
  inspect: 'inspect.svg',
  help: 'help.svg',
};

function buildSvg(raw: RawReferenceLockedTrace): string {
  const strokeWidth = raw.strokeWidth ?? 1.4;
  const paths = raw.paths.map((d) => `  <path d="${d}"/>`).join('\n');
  const circles = (raw.circles ?? [])
    .map((c) => {
      const fill = c.fill === 'currentColor' ? 'currentColor' : 'none';
      return `  <circle cx="${c.cx}" cy="${c.cy}" r="${c.r}" fill="${fill}"/>`;
    })
    .join('\n');
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round" data-ndx-canon="v3">`,
    paths,
    circles,
    '</svg>',
    '',
  ].join('\n');
}

function parseSvg(svg: string): { paths: string[]; circles: Array<{ cx: number; cy: number; r: number; fill?: 'currentColor' | 'none' }>; strokeWidth: number } {
  const paths: string[] = [];
  for (const m of svg.matchAll(/<path d="([^"]+)"/g)) paths.push(m[1]!);
  const circles: Array<{ cx: number; cy: number; r: number; fill?: 'currentColor' | 'none' }> = [];
  for (const m of svg.matchAll(/<circle cx="([^"]+)" cy="([^"]+)" r="([^"]+)"(?: fill="([^"]+)")?/g)) {
    circles.push({
      cx: Number(m[1]),
      cy: Number(m[2]),
      r: Number(m[3]),
      fill: m[4] === 'currentColor' ? 'currentColor' : undefined,
    });
  }
  const strokeMatch = svg.match(/stroke-width="([^"]+)"/);
  return { paths, circles, strokeWidth: strokeMatch ? Number(strokeMatch[1]) : 1.4 };
}

function emitAssetRegistry(manifest: typeof manifest extends infer T ? T : never) {
  const entries = manifest.icons.map((entry) => {
    const svg = readFileSync(join(SVG_DIR, entry.filename), 'utf8');
    const parsed = parseSvg(svg);
    return { entry, parsed };
  });

  const lines = [
    '/** AUTO-GENERATED by scripts/icons/generateNdxV3SvgCanon.ts — do not edit */',
    "import type { NDXIconName } from '../types.js';",
    'export type V3AssetRegistryEntry = {',
    '  iconName: NDXIconName;',
    "  version: 'v3';",
    '  sourcePath: string;',
    '  publicPath: string;',
    '  sourceHash: string;',
    '  referenceId: string;',
    '  filename: string;',
    '  paths: string[];',
    '  circles: Array<{ cx: number; cy: number; r: number; fill?: "currentColor" | "none" }>;',
    '  strokeWidth: number;',
    '};',
    'export const NDX_V3_ASSET_REGISTRY: Record<string, V3AssetRegistryEntry> = {',
  ];
  for (const { entry, parsed } of entries) {
    lines.push(`  ${entry.iconName}: ${JSON.stringify({ ...entry, ...parsed, iconName: entry.iconName }, null, 2).replace(/^/gm, '  ').trim()},`);
  }
  lines.push('};', '');
  writeFileSync(join(ROOT, 'shared/site00-studio-world-ui/icons/p0ui3e/v3AssetRegistry.generated.ts'), lines.join('\n'));
}

function main() {
  mkdirSync(SVG_DIR, { recursive: true });
  mkdirSync(PUBLIC_DIR, { recursive: true });
  mkdirSync(join(ROOT, 'shared/site00-studio-world-ui/icons/p0ui3e'), { recursive: true });

  const manifest: Array<{
    iconName: string;
    version: 'v3';
    sourcePath: string;
    publicPath: string;
    sourceHash: string;
    referenceId: string;
    filename: string;
  }> = [];

  for (const iconName of P0_UI_3D_TARGET_ICONS) {
    const filename = NDX_V3_SVG_FILENAME[iconName];
    if (!filename) throw new Error(`Missing filename mapping for ${iconName}`);
    const raw = NDX_ICON_GEOMETRY_V3[iconName as NDXIconName];
    const svg = buildSvg(raw);
    const sourcePath = `shared/site00-studio-world-ui/icons/ndx/v3/${filename}`;
    const absPath = join(SVG_DIR, filename);
    writeFileSync(absPath, svg, 'utf8');

    const hash = createHash('sha256').update(svg).digest('hex');
    const hash8 = hash.slice(0, 8);
    const versionedName = filename.replace('.svg', `.${hash8}.svg`);
    const publicRel = `icons/ndx/v3/${versionedName}`;
    writeFileSync(join(PUBLIC_DIR, versionedName), svg, 'utf8');
    writeFileSync(join(PUBLIC_DIR, filename), svg, 'utf8');

    manifest.push({
      iconName,
      version: 'v3',
      sourcePath,
      publicPath: `/${publicRel}`,
      sourceHash: `sha256:${hash}`,
      referenceId: `ndx-icon-reference-sheet-p0ui3d:${iconName}`,
      filename,
    });
    console.log('wrote', filename, hash8);
  }

  writeFileSync(MANIFEST_PATH, JSON.stringify({ generatedAt: new Date().toISOString(), icons: manifest }, null, 2));
  emitAssetRegistry({ generatedAt: new Date().toISOString(), icons: manifest });
  console.log('manifest', MANIFEST_PATH);
}

main();
