import type { StudioWorldResidentDossier } from './types.js';

const FSBW_PATHS = [
  'src/studio-os-core/studio-world-residents/season1-ensemble/',
  'docs/studio-world/STUDIO_WORLD_SEASON1_CORE_ENSEMBLE_CANON_BIBLE.md',
  'docs/studio-world/residents/season-1/season1-ensemble-canonical.json',
] as const;

function auth(residentId: string): StudioWorldResidentDossier['sourceAuthority'] {
  return {
    repo: 'fsbw',
    canon: 'STUDIO_WORLD_SEASON1_CORE_ENSEMBLE',
    residentId,
    version: 'season1-v1',
    fsbwPaths: FSBW_PATHS,
  };
}

/** Canonical eight — order matches ensemble roster. */
export const STUDIO_WORLD_SEASON1_RESIDENTS: readonly StudioWorldResidentDossier[] = [
  {
    sourceResidentId: 'SW-RESIDENT-001',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'ETTA VALE',
    aliases: ['Etta'],
    studioWorldRole: 'Founding Presence · Creative Director',
    productionCapabilities: ['Creative direction', 'Taste authority', 'Campaign vision'],
    personalitySummary: 'Exact, poised, emotionally intelligent, quietly funny, creative authority.',
    visualIdentitySummary: 'Sophisticated Fashionista',
    naturalWardrobeSummary: 'Refined editorial fashion — precise silhouette, luxury restraint.',
    cameraBehavior: 'Mostly ignores camera — does not perform for lens unless intentional.',
    castingNotes: 'Lead creative presence; not a generic CEO stock woman.',
    identityConstraints: ['Do not replace face or body for role styling', 'Authority reads through precision not volume'],
    antiFlatteningRules: ['Not CEO stock woman', 'Not generic boss archetype'],
    protectedOpenFields: ['ettaCurrentPartner'],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-001'),
    sunSign: 'Virgo',
    moonSign: 'Leo',
    risingSign: 'Scorpio',
    presentation: 'WOMAN',
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
  {
    sourceResidentId: 'SW-RESIDENT-002',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'ZURI XU',
    aliases: ['Zuri'],
    studioWorldRole: 'Strategy Director · Client Intelligence · Office Guide',
    productionCapabilities: ['Strategy', 'Client intelligence', 'Office navigation'],
    personalitySummary: 'Perceptive, unflustered, reserved, fashion-obsessed, strategic.',
    visualIdentitySummary: 'Architectural Fashion Strategist',
    naturalWardrobeSummary: 'Architectural tailoring — strategic minimalism.',
    cameraBehavior: 'Speaks when worthwhile — economical on-camera presence.',
    castingNotes: 'Canonical surname XU only — HALE is superseded and must not appear.',
    identityConstraints: ['Chinese / Chinese-diaspora identity locked', 'Lesbian identity is canon — not erased for cast'],
    antiFlatteningRules: ['Not generic Asian businesswoman', 'Not interchangeable analyst stock'],
    protectedOpenFields: ['zuriPartnerIdentity'],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-002'),
    sunSign: 'Capricorn',
    moonSign: 'Aquarius',
    risingSign: 'Virgo',
    presentation: 'WOMAN',
    sexuality: 'Lesbian',
    culturalContext: ['Chinese', 'Chinese-diaspora'],
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
  {
    sourceResidentId: 'SW-RESIDENT-003',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'JULES MERCER',
    aliases: ['Jules'],
    studioWorldRole: 'Front Office · Concierge · Tenant Relations',
    productionCapabilities: ['Hospitality', 'Tenant relations', 'Social routing'],
    personalitySummary: 'Warm, charismatic, socially agile, emotionally perceptive, hospitality-driven.',
    visualIdentitySummary: 'Relaxed Romantic — long locs, linen, wine trousers',
    naturalWardrobeSummary: 'Relaxed romantic — locs, linen, wine trousers.',
    cameraBehavior: 'Plays to camera — social warmth reads on lens.',
    castingNotes: 'Social glue of the ensemble.',
    identityConstraints: ['Long locs identity anchor', 'Not reduced to model/player stereotype'],
    antiFlatteningRules: ['Not attractive Black male model/player shorthand', 'Not generic concierge'],
    protectedOpenFields: [],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-003'),
    sunSign: 'Libra',
    moonSign: 'Cancer',
    risingSign: 'Leo',
    presentation: 'MAN',
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
  {
    sourceResidentId: 'SW-RESIDENT-004',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'NOA KLINE',
    aliases: ['Noa'],
    studioWorldRole: 'Systems Architect · Studio OS Liaison',
    productionCapabilities: ['Systems architecture', 'Studio OS liaison', 'Technical continuity'],
    personalitySummary: 'Minimal, cerebral, deadpan, loyal, family-soft underneath.',
    visualIdentitySummary: 'Understated Systems Dad',
    naturalWardrobeSummary: 'Understated practical layers — systems dad energy.',
    cameraBehavior: 'Dislikes camera — avoid forced performance.',
    castingNotes: 'Japanese with strong Okinawan/Ryukyuan roots; married with wife and two daughters (identities OPEN).',
    identityConstraints: ['Okinawan/Ryukyuan roots must survive projection', 'Family context is canon without inventing names'],
    antiFlatteningRules: ['Not Asian tech archetype', 'Not emotionless engineer stock'],
    protectedOpenFields: ['noaFamilyIdentities'],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-004'),
    sunSign: 'Capricorn',
    moonSign: 'Cancer',
    risingSign: 'Virgo',
    presentation: 'MAN',
    culturalContext: ['Japanese', 'Okinawan', 'Ryukyuan'],
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
  {
    sourceResidentId: 'SW-RESIDENT-005',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'CASPIAN REED',
    aliases: ['Caspian'],
    studioWorldRole: 'World Director · Environmental Storyteller',
    productionCapabilities: ['World direction', 'Environmental narrative', 'Atmosphere design'],
    personalitySummary: 'Cinematic, dramatic, sensual, visionary, emotionally atmospheric.',
    visualIdentitySummary: 'Decadent Bohemian Aristocrat',
    naturalWardrobeSummary: 'Decadent bohemian aristocrat layers.',
    cameraBehavior: 'Composes for camera — aware of frame.',
    castingNotes: 'Sexuality fluid — not flattened to binary trope.',
    identityConstraints: ['Fluid sexuality is canon'],
    antiFlatteningRules: ['Not European fashion-model/vampire shorthand', 'Not generic dramatic gay villain'],
    protectedOpenFields: ['caspianCurrentPartner'],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-005'),
    sunSign: 'Pisces',
    moonSign: 'Leo',
    risingSign: 'Scorpio',
    presentation: 'MAN',
    sexuality: 'Fluid',
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
  {
    sourceResidentId: 'SW-RESIDENT-006',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'IONA WELLS',
    aliases: ['Iona'],
    studioWorldRole: 'Fabrication Lead · Character Lab · Image Construction',
    productionCapabilities: ['Fabrication', 'Character lab', 'Image construction'],
    personalitySummary: 'Technical, obsessive, tactile, specific, awkward, brilliant.',
    visualIdentitySummary: 'Precision Utilitarian (primary) — full-glam is contextual alternate mode only',
    naturalWardrobeSummary: 'Precision utilitarian workwear — glam is event/context mode not default.',
    cameraBehavior: 'Forgets camera exists — absorbed in craft.',
    castingNotes: 'Full-glam Iona is contextual alternate mode — NOT permanent makeover.',
    identityConstraints: ['Default identity is utilitarian precision', 'Glam mode must be explicitly flagged per role'],
    antiFlatteningRules: ['Not frumpy nerd makeover arc', 'Not makeover-girl default'],
    protectedOpenFields: ['ionaFutureRelationship'],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-006'),
    sunSign: 'Virgo',
    moonSign: 'Aquarius',
    risingSign: 'Gemini',
    presentation: 'WOMAN',
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
  {
    sourceResidentId: 'SW-RESIDENT-007',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'MARLOWE SAINT',
    aliases: ['Marlowe'],
    studioWorldRole: 'Casting Director · Performance Design · Persona Mapping',
    productionCapabilities: ['Casting direction', 'Performance design', 'Persona mapping'],
    personalitySummary: 'Grand, witty, culturally encyclopedic, psychologically sharp, socially seasoned.',
    visualIdentitySummary: 'Off-Duty Cultural Icon hybrid',
    naturalWardrobeSummary: 'Off-duty cultural icon — substantial presence, not slim youth default.',
    cameraBehavior: 'Always knows where camera is.',
    castingNotes: 'Age 54; gay; married to husband (identity OPEN). Larger-bodied — substantial face, broad chest/shoulders.',
    identityConstraints: [
      'Age 54 locked',
      'Larger-bodied / fuller face / broad chest and shoulders — not slim flamboyant youth stereotype',
    ],
    antiFlatteningRules: ['Not young/slim flamboyant stereotype', 'Not generic sassy best friend'],
    protectedOpenFields: ['marloweHusbandIdentity'],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-007'),
    sunSign: 'Leo',
    moonSign: 'Scorpio',
    risingSign: 'Libra',
    presentation: 'MAN',
    agePresentation: '54',
    sexuality: 'Gay',
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
  {
    sourceResidentId: 'SW-RESIDENT-008',
    sourceSystem: 'STUDIO_WORLD',
    canonicalName: 'ELIO "EV" VAHN',
    aliases: ['EV', 'Elio'],
    studioWorldRole: 'Tenancy · Expansion · Business Development',
    productionCapabilities: ['Tenancy', 'Expansion', 'Business development'],
    personalitySummary: 'Controlled, strategic, persuasive, luxurious, private, leverage-oriented.',
    visualIdentitySummary: 'Private Club Strategist',
    naturalWardrobeSummary: 'Private club strategist — luxe restraint.',
    cameraBehavior: 'Manages his image deliberately.',
    castingNotes: 'Signature sign-off: “Regards, EV”. Sexuality OPEN / unresolved — do not infer.',
    identityConstraints: ['Sexuality and partner remain OPEN', 'Not mafia/billionaire trope'],
    antiFlatteningRules: ['Not mafia boss', 'Not generic billionaire villain'],
    protectedOpenFields: ['evSexuality', 'evPartner'],
    canonVersion: 'season1-v1',
    sourceAuthority: auth('SW-RESIDENT-008'),
    sunSign: 'Taurus',
    moonSign: 'Scorpio',
    risingSign: 'Capricorn',
    presentation: 'MAN',
    sexuality: 'OPEN',
    castingEligibility: 'AVAILABLE',
    visualAssetManifestRef: null,
  },
];

export function getStudioWorldSeason1ResidentDossiers(): readonly StudioWorldResidentDossier[] {
  return STUDIO_WORLD_SEASON1_RESIDENTS;
}

export function findResidentDossierById(sourceResidentId: string): StudioWorldResidentDossier | null {
  return STUDIO_WORLD_SEASON1_RESIDENTS.find((r) => r.sourceResidentId === sourceResidentId) ?? null;
}
