/**
 * P0.VR.7 — Reference fidelity contract constants.
 */

import { P0_VR_7_LINEAGE } from './types.js';

export { P0_VR_7_LINEAGE };

export const SYSTEM_FIDELITY_INSTRUCTION = [
  'KEEP THE FUNCTION.',
  'REBUILD THE LOOK.',
  'DO NOT PROTECT INCORRECT CURRENT VISUALS.',
  'COPY THE REFERENCE EXACTLY.',
  'REFERENCE = DESIGN AUTHORITY.',
].join(' ');

export const DEFAULT_DESIGN_AUTHORITY_MODE = 'DESIGN_AUTHORITY' as const;
export const DEFAULT_FIDELITY_MODE = 'EXACT' as const;

export const IMPLEMENTATION_ORDER = [
  'REFERENCE_ANALYSIS',
  'GLOBAL_GEOMETRY',
  'PARENT_CONTAINERS',
  'MAJOR_COMPONENT_GEOMETRY',
  'ASSET_SLOTS',
  'TYPOGRAPHY',
  'SPACING',
  'MATERIAL_COLOR',
  'INTERACTIVE_STATES',
  'RESPONSIVE_BEHAVIOR',
  'SCREENSHOT_QA',
  'MICRO_CORRECTIONS',
] as const;

export const SYSTEM_FIDELITY_PRESET_IDS = {
  REPLICATE_PAGE_EXACTLY: 'preset-replicate-page-exactly',
  REPLICATE_MOBILE_EXACTLY: 'preset-replicate-mobile-screen-exactly',
  REPLICATE_DESKTOP_EXACTLY: 'preset-replicate-desktop-screen-exactly',
  EXTRACT_REPLACE_ASSETS_EXACTLY: 'preset-extract-replace-assets-exactly',
} as const;

export const P0_VR_7_FAILURE_CODES = [
  'REFERENCE_TREATED_AS_INSPIRATION',
  'REFERENCE_AUTHORITY_MISSING',
  'REFERENCE_FIDELITY_MODE_MISSING',
  'REFERENCE_GEOMETRY_NOT_ANALYZED',
  'REFERENCE_ASSET_MANIFEST_MISSING',
  'REFERENCE_IMPLEMENTATION_PLAN_MISSING',
  'REFERENCE_SCREENSHOT_QA_SKIPPED',
  'REFERENCE_FALSE_PASS',
  'REFERENCE_GLOBAL_GEOMETRY_DRIFT',
  'REFERENCE_COMPONENT_GEOMETRY_DRIFT',
  'REFERENCE_TYPOGRAPHY_DRIFT',
  'REFERENCE_SPACING_DRIFT',
  'REFERENCE_ASSET_DRIFT',
  'REFERENCE_RESPONSIVE_AUTHORITY_MISSING',
  'REFERENCE_EXECUTION_CONTRACT_LOST',
] as const;

export type P0VR7FailureCode = (typeof P0_VR_7_FAILURE_CODES)[number];

/** Mobile design workspace reference canvas (authority for decomposition heuristics). */
export const DESIGN_WORKSPACE_REFERENCE_CANVAS = { width: 390, height: 844 } as const;
