export const P0_VR_TWIN_V30R8M2R2_LINEAGE = 'P0.VR.TWINV3.0R8M2R2' as const;
export const MOBILE_TWIN_IMPL_COMPILER_GENERATION_R8M2R2 = 'R8M2R2' as const;
export const MOBILE_TWIN_IMPLEMENTATION_VERSION_TRANSLATION = 'mobile-twin-impl-v4-translation-brief' as const;
export const IMPLEMENTATION_TRANSLATION_BRIEF_VERSION = 'implementation-translation-brief-v1' as const;
export const VISUAL_IMPLEMENTATION_CODING_PROMPT_VERSION = 'visual-implementation-coding-prompt-v1' as const;

export const R8M2R1_CORRECTION_REQUIRED_REASON =
  'IMPLEMENTATION_MISSING_WRITTEN_TRANSLATION_BRIEF' as const;

export const TRANSLATION_BRIEF_NOT_CONSUMED = 'TRANSLATION_BRIEF_NOT_CONSUMED' as const;

export const CRITICAL_TRANSLATION_SECTIONS = [
  'GLOBAL_PAGE_CHARACTER',
  'HOST_SHELL',
  'PROJECT_CONTEXT',
  'HERO_WORKSPACE',
  'AUTHORITY_PANEL',
  'CANDIDATE_GALLERY',
  'DECISION_BAR',
  'STRUCTURED_OUTPUT',
  'READINESS',
  'CONCEPT_DATA_HISTORY',
  'BOTTOM_NAV',
  'TYPOGRAPHY',
  'COLOR_MATERIAL',
  'ASSET',
  'CONTROL_HIERARCHY',
  'INTERACTION',
  'RESPONSIVE',
  'DO_NOT_DO',
] as const;

export type CriticalTranslationSectionId = (typeof CRITICAL_TRANSLATION_SECTIONS)[number];
