/** P0.CB.1 — Founder creative ingestion constants */

export const FOUNDER_CREATIVE_INGESTION_VERSION = 'FOUNDER_CREATIVE_INGESTION@P0.CB.1A' as const;

export const CREATIVE_ORIGIN_TYPES = [
  'FOUNDER_CREATED',
  'FOUNDER_CURATED',
  'STUDIO_WORLD_GENERATED',
  'EXTERNAL_REFERENCE',
  'IMPORTED_PRODUCTION_ASSET',
] as const;

export const CREATIVE_AUTHORITY_TYPES = [
  'FOUNDER_APPROVED',
  'FOUNDER_DRAFT',
  'SYSTEM_INFERRED',
] as const;

export const GENERATION_PROVENANCE_TYPES = [
  'EXTERNAL_CHATGPT_CREATIVE_SESSION',
  'STUDIO_WORLD_GENERATION',
  'FOUNDER_UPLOAD',
  'UNKNOWN',
] as const;

export const CREATIVE_CANON_STATUS = [
  'CAMPAIGN_APPROVED_CREATIVE',
  'DRAFT',
  'EXPERIMENTAL',
] as const;

export const LEARNING_PERMISSION_TYPES = [
  'CREATIVE_SIGNAL_ALLOWED',
  'NO_LEARNING',
] as const;

export const ASSET_KIND_TYPES = ['REFERENCE_IMAGE', 'PRODUCTION_ASSET'] as const;

export const INGESTION_WORKFLOW_STEPS = [
  'REFERENCE',
  'DECOMPOSE',
  'RECONSTRUCT',
  'REVIEW',
  'SEQUENCE',
  'CAMPAIGN',
] as const;

export const PHOTOGRAPHY_SOURCE_MODES = [
  'REFERENCE_ONLY',
  'GENERATE_FROM_REFERENCE',
  'UPLOAD_HQ',
  'USE_EXISTING_ASSET',
  'REPLACE',
  'LOCK_CANONICAL',
] as const;

export const RECONSTRUCTION_REVIEW_JUDGMENTS = [
  'MATCH',
  'CLOSE_REVISE',
  'WRONG_INTERPRETATION',
  'REPLACE_PHOTO',
  'EDIT_COPY',
  'EDIT_PROMPT',
  'REGENERATE_PHOTO',
  'APPROVE_SLIDE',
] as const;

export const CREATIVE_SEQUENCE_ROLES = [
  'CHARACTER_WORLD',
  'POINT_OF_VIEW',
  'CONTENT_FRANCHISE',
] as const;

export const DEFAULT_TARGET_ASPECT_RATIO = '4:5' as const;
export const DEFAULT_TARGET_RESOLUTION = '2160x2700' as const;
export const ESTIMATED_STILL_GENERATION_COST_USD = 0.08;

export const NDX_LAUNCH_ROW_01_CAMPAIGN_ID = 'ndxbook-launch-row-01' as const;
