/**
 * Brand Character Readiness + Conditional Deepening — P0.5B.2
 */

export const BRAND_CHARACTER_READINESS_METHODOLOGY_V1 = 'BRAND_CHARACTER_READINESS_V1' as const;

export const NDXBOOK_CHARACTER_READINESS_DB_ID = 'c4e1a2b3-0010-4000-8000-000000000001';

export const BRAND_CHARACTER_READINESS_STATES = [
  'CHARACTER_READY',
  'CHARACTER_PARTIAL',
  'CHARACTER_INSUFFICIENT',
  'CHARACTER_BLOCKED',
  'CHARACTER_NOT_EVALUATED',
] as const;

export const CHARACTER_EVIDENCE_STRENGTHS = [
  'STRONG_EVIDENCE',
  'SUFFICIENT_EVIDENCE',
  'THIN_EVIDENCE',
  'MISSING_EVIDENCE',
  'CONFLICTING_EVIDENCE',
  'NOT_APPLICABLE',
  'NOT_EVALUATED',
] as const;

export const CHARACTER_EVIDENCE_GAP_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const;

export const CHARACTER_EVIDENCE_CONFIDENCE_LEVELS = [
  'DIRECT_FOUNDER_EVIDENCE',
  'VALIDATED_CARRY_FORWARD',
  'MULTIPLE_SUPPORTING_SIGNALS',
  'SYNTHESIZED_HIGH_CONFIDENCE',
  'SYNTHESIZED_LOW_CONFIDENCE',
  'MODEL_INFERENCE_ONLY',
] as const;

export const CHARACTER_READINESS_DOMAINS = [
  'WORLDVIEW_ORIENTATION',
  'INTERNAL_TENSION',
  'INTELLECTUAL_BEHAVIOR',
  'SOCIAL_BEHAVIOR',
  'AUDIENCE_RELATIONSHIP',
  'HUMOR_WIT',
  'CULTURAL_INTELLIGENCE',
  'EMOTIONAL_RANGE',
  'LANGUAGE_BEHAVIOR',
  'TASTE_JUDGMENT',
  'ARTIFACT_MAKER_BEHAVIOR',
  'HARD_BOUNDARIES',
] as const;

export const CRITICAL_CHARACTER_DOMAINS = [
  'WORLDVIEW_ORIENTATION',
  'AUDIENCE_RELATIONSHIP',
  'HARD_BOUNDARIES',
] as const;

export const EXISTING_EVIDENCE_SEARCH_RESULTS = [
  'ANSWER_ALREADY_EXISTS',
  'PARTIAL_ANSWER_EXISTS',
  'CONFLICTING_ANSWER_EXISTS',
  'NO_RELEVANT_EVIDENCE',
] as const;

export const FORMATION_INPUT_READINESS = [
  'READY',
  'PARTIAL',
  'INSUFFICIENT',
  'NOT_EVALUATED',
] as const;
