/**
 * Character question library — reusable, domain-organized, generic (not NDXBOOK-specific).
 */

import type { BrandCharacterDeepeningQuestion, CharacterReadinessDomain } from './types.js';

const LIBRARY_VERSION = 'BRAND_CHARACTER_QUESTION_LIBRARY_V1';

type LibraryEntry = Omit<BrandCharacterDeepeningQuestion, 'evidenceGapId' | 'whyAsked' | 'customGenerated'>;

const ENTRIES: LibraryEntry[] = [
  {
    questionId: 'humor-native-vs-forced',
    domain: 'HUMOR_WIT',
    purpose: 'Identify native humor mechanism',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'What does this brand find funny that other brands in its category probably would not?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'humor-natural-joke',
    domain: 'HUMOR_WIT',
    purpose: 'Humor naturalness boundary',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'What kind of joke would feel completely natural coming from this brand?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'humor-embarrassing',
    domain: 'HUMOR_WIT',
    purpose: 'Humor anti-pattern',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What kind of joke would feel embarrassing or try-hard for this brand?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'humor-mechanism',
    domain: 'HUMOR_WIT',
    purpose: 'Humor mechanism specificity',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'Does it tease, exaggerate, understate, deadpan, roast, observe, or avoid humor entirely?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'cultural-native-references',
    domain: 'CULTURAL_INTELLIGENCE',
    purpose: 'Cultural fluency depth',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'What cultural references feel native to this brand rather than borrowed?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'cultural-shaping',
    domain: 'CULTURAL_INTELLIGENCE',
    purpose: 'Cultural formation context',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What communities, eras, media, or cultural experiences shaped its taste?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'cultural-cringe',
    domain: 'CULTURAL_INTELLIGENCE',
    purpose: 'Cultural anti-pattern',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What cultural behavior makes you cringe when brands try too hard?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'social-never-say',
    domain: 'SOCIAL_BEHAVIOR',
    purpose: 'Social distinctiveness',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'What would this brand say that another brand in its industry would probably never say?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'social-room-presence',
    domain: 'SOCIAL_BEHAVIOR',
    purpose: 'Social energy signature',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What kind of person does this brand become in a room full of people?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'emotional-excites',
    domain: 'EMOTIONAL_RANGE',
    purpose: 'Emotional delight',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What genuinely excites this brand?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'emotional-irritates',
    domain: 'EMOTIONAL_RANGE',
    purpose: 'Emotional irritation',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What irritates it?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'taste-beautiful',
    domain: 'TASTE_JUDGMENT',
    purpose: 'Taste positive pole',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'What does this brand think is beautiful?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'taste-corny',
    domain: 'TASTE_JUDGMENT',
    purpose: 'Taste negative pole',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What feels corny or too polished to this brand?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'artifact-instinct',
    domain: 'ARTIFACT_MAKER_BEHAVIOR',
    purpose: 'Artifact behavioral trace',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'If this brand handled a page, image, or object, what would it instinctively do to it?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'artifact-trace',
    domain: 'ARTIFACT_MAKER_BEHAVIOR',
    purpose: 'Maker trace without logo',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What trace would tell you this brand had been here even if the logo were removed?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'worldview-wrong',
    domain: 'WORLDVIEW_ORIENTATION',
    purpose: 'Worldview distinctiveness',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'What does this brand believe that its industry commonly gets wrong?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'tension-important',
    domain: 'INTERNAL_TENSION',
    purpose: 'Governing contradiction',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: true,
    prompt: 'What contradiction inside the brand is actually important — not a flaw to eliminate?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'language-verbatim',
    domain: 'LANGUAGE_BEHAVIOR',
    purpose: 'Founder language capture',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'In your own words, how would this brand talk about something it cares deeply about?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'boundaries-never',
    domain: 'HARD_BOUNDARIES',
    purpose: 'Hard character boundaries',
    questionType: 'DEEPENING',
    answerMode: 'BOUNDARY',
    required: true,
    prompt: 'What must this brand never become, even if it would get more attention?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'intellectual-change-mind',
    domain: 'INTELLECTUAL_BEHAVIOR',
    purpose: 'Intellectual flexibility',
    questionType: 'DEEPENING',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'What does this brand believe strongly but remain willing to change its mind about?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
  {
    questionId: 'audience-relationship',
    domain: 'AUDIENCE_RELATIONSHIP',
    purpose: 'Audience relationship specificity',
    questionType: 'CLARIFICATION',
    answerMode: 'FREE_TEXT',
    required: false,
    prompt: 'How does this brand relate to its audience when they know less — or more — than the brand?',
    sourceVersion: LIBRARY_VERSION,
    provenance: 'BRAND_CHARACTER_QUESTION_LIBRARY',
  },
];

export function getQuestionsForDomain(domain: CharacterReadinessDomain): LibraryEntry[] {
  return ENTRIES.filter((e) => e.domain === domain);
}

export function getQuestionById(questionId: string): LibraryEntry | undefined {
  return ENTRIES.find((e) => e.questionId === questionId);
}

export function brandCharacterQuestionLibraryVersion(): string {
  return LIBRARY_VERSION;
}

export function questionLibraryHasDomain(domain: CharacterReadinessDomain): boolean {
  return ENTRIES.some((e) => e.domain === domain);
}
