/**
 * P0.5E.4B — NDX voice calibration constants.
 */

export const NDX_VOICE_CALIBRATION_RUN_ID = 'ndx-voice-calibration-p05e4b' as const;

export const NDX_BOOK_COMPARISON_LINE =
  'OKAY, SO... THAT CANNOT BE RIGHT. SOMEBODY WOULD HAVE SAID SOMETHING BY NOW.' as const;

export const NDX_VOICE_EMOTION_TEST_LINES = {
  PLAYFUL: "BE SERIOUS. YOU MEAN TO TELL ME WE'VE BEEN DOING THIS THE WHOLE TIME?",
  SKEPTICAL: "WAIT. THAT DOESN'T LINE UP.",
  RABBIT_HOLE: 'I ONLY OPENED THIS BECAUSE I WANTED TO CHECK ONE THING.',
  SELF_CORRECTION: 'OKAY. I WAS WRONG. BUT LOOK AT WHY I WAS WRONG.',
  SERIOUS: 'NO JOKE FOR A SECOND. THIS PART ACTUALLY MATTERS.',
  FRIEND_TEXT: 'GIRL. LOOK AT THIS.',
  QUIET_DISCOVERY: "...THAT'S INTERESTING.",
} as const;
