import { BUSINESS_GROWTH_CATALOG_VERSION } from './version.js';
import type { BusinessGrowthServiceDefinition, BusinessGrowthServiceId } from './types.js';

const catalog: BusinessGrowthServiceDefinition[] = [
  {
    service_id: 'BGI.VISIBILITY_AUDIT',
    family_id: 'VISIBILITY',
    display_name: 'Business Visibility Audit',
    description:
      'Documented findings on how the business appears in search, listings, and contact consistency — with a prioritized action plan.',
    deliverables: [
      'Company-name and listing consistency review',
      'Search discoverability notes',
      'Domain and contact-information consistency check',
      'Prioritized action plan report',
    ],
    intake_requirements: ['Business legal or trade name', 'Primary market geography', 'Known web or listing URLs if any'],
    eligibility_criteria: ['Operating business or credible launch plan'],
    exclusions: ['Guaranteed search rankings', 'Paid ad management', 'Reputation management campaigns'],
    pricing_basis: 'Fixed fee range (founder approval required before checkout)',
    commercial_status: 'PROPOSED_NOT_ACTIVE',
    proposed_price_min_minor: 15_000,
    proposed_price_max_minor: 30_000,
    proposed_currency: 'USD',
    delivery: {
      estimated_min_business_days: 3,
      estimated_max_business_days: 7,
      delivery_unit: 'BUSINESS_DAYS',
      min_duration_business_days: 3,
      max_duration_business_days: 7,
      prerequisites: ['Intake complete'],
      client_dependencies: ['Access to known listings or URLs'],
      external_dependencies: [],
      parallelizable_with_foundation: true,
      required_review_steps: ['Founder or delivery lead review of report'],
      capacity_assumption: 'Standard analyst capacity',
      confidence: 'MEDIUM',
      time_policy_version: 'bgi-time-v1',
    },
    dependencies: [],
    execution_owner: 'SITE00_DIRECT',
    approval_requirements: ['Founder commercial rate approval'],
    client_facing_status: 'DISCOVERABLE',
    catalog_version: BUSINESS_GROWTH_CATALOG_VERSION,
  },
  {
    service_id: 'BGI.PRESENCE_LAUNCH',
    family_id: 'PRESENCE',
    display_name: 'Presence Launch',
    description:
      'Professional digital location scoped through the canonical BLDR estimator — not a Foundation technical add-on.',
    deliverables: [
      'Scoped BLDR proposal for company/service presentation',
      'Mobile-ready experience plan',
      'Inquiry capture approach',
      'Search visibility foundations within build scope',
    ],
    intake_requirements: ['Business Ambition goals', 'BLDR configuration session'],
    eligibility_criteria: ['Client accepts separate BLDR engagement'],
    exclusions: ['2–3 day Foundation delivery window for full website build'],
    pricing_basis: 'Canonical BLDR estimator (separate quote)',
    commercial_status: 'BLDR_ESTIMATOR_AUTHORITY',
    proposed_price_min_minor: null,
    proposed_price_max_minor: null,
    proposed_currency: 'USD',
    delivery: {
      estimated_min_business_days: null,
      estimated_max_business_days: null,
      delivery_unit: 'MONTHS',
      min_duration_business_days: null,
      max_duration_business_days: null,
      prerequisites: ['Foundation readiness recommended', 'BLDR intake'],
      client_dependencies: ['Brand and content decisions'],
      external_dependencies: [],
      parallelizable_with_foundation: false,
      required_review_steps: ['BLDR blueprint review', 'Founder commercial approval on build quote'],
      capacity_assumption: 'BLDR production schedule',
      confidence: 'PENDING_SCOPE_REVIEW',
      time_policy_version: 'bldr-estimator-v1',
    },
    dependencies: [],
    execution_owner: 'SITE00_DIRECT',
    approval_requirements: ['BLDR quote acceptance separate from Foundation checkout'],
    client_facing_status: 'DISCOVERABLE',
    catalog_version: BUSINESS_GROWTH_CATALOG_VERSION,
  },
  {
    service_id: 'BGI.OPPORTUNITY_READINESS',
    family_id: 'OPPORTUNITY',
    display_name: 'Opportunity Readiness Assessment',
    description:
      'Business-specific readiness report for grants, contracts, certifications, and documentation gaps — without promising funding.',
    deliverables: [
      'Growth goals alignment summary',
      'Grant and contract readiness notes',
      'Documentation gap list',
      'Specialist referral recommendations when needed',
    ],
    intake_requirements: ['Business Ambition goals', 'Industry and geography'],
    eligibility_criteria: ['Client acknowledges no funding guarantee'],
    exclusions: ['Guaranteed grant awards', 'Fabricated program listings'],
    pricing_basis: 'Fixed fee range (founder approval required)',
    commercial_status: 'PROPOSED_NOT_ACTIVE',
    proposed_price_min_minor: 25_000,
    proposed_price_max_minor: 50_000,
    proposed_currency: 'USD',
    delivery: {
      estimated_min_business_days: 5,
      estimated_max_business_days: 15,
      delivery_unit: 'BUSINESS_DAYS',
      min_duration_business_days: 5,
      max_duration_business_days: 15,
      prerequisites: ['Intake complete'],
      client_dependencies: ['Business history and documentation availability'],
      external_dependencies: ['Official program verification when cited'],
      parallelizable_with_foundation: true,
      required_review_steps: ['Human review of eligibility statements'],
      capacity_assumption: 'Analyst + founder spot-check',
      confidence: 'MEDIUM',
      time_policy_version: 'bgi-time-v1',
    },
    dependencies: [],
    execution_owner: 'SITE00_DIRECT',
    approval_requirements: ['Founder commercial rate approval'],
    client_facing_status: 'DISCOVERABLE',
    catalog_version: BUSINESS_GROWTH_CATALOG_VERSION,
  },
  {
    service_id: 'BGI.APPLICATION_PROCUREMENT_SUPPORT',
    family_id: 'OPPORTUNITY',
    display_name: 'Application / Procurement Support',
    description:
      'Defined support package for organizing applications, registrations, and submissions — human-reviewed, no award guarantee.',
    deliverables: [
      'Eligibility verification checklist',
      'Document assembly plan',
      'Capabilities statement support where in scope',
      'Deadline tracking',
    ],
    intake_requirements: ['Specific opportunity or program identified', 'Signed scope for support package'],
    eligibility_criteria: ['Verified program requirements'],
    exclusions: ['Guaranteed contract or grant award', 'Implying mandatory third-party registration fees'],
    pricing_basis: 'Custom fixed fee',
    commercial_status: 'CUSTOM_QUOTE_REQUIRED',
    proposed_price_min_minor: null,
    proposed_price_max_minor: null,
    proposed_currency: 'USD',
    delivery: {
      estimated_min_business_days: null,
      estimated_max_business_days: null,
      delivery_unit: 'CUSTOM',
      min_duration_business_days: null,
      max_duration_business_days: null,
      prerequisites: ['Opportunity Readiness recommended', 'Verified opportunity source'],
      client_dependencies: ['Timely document supply', 'Authorized submissions'],
      external_dependencies: ['Issuing organization timelines'],
      parallelizable_with_foundation: false,
      required_review_steps: ['Founder custom quote', 'Specialist review when regulated'],
      capacity_assumption: 'Case-by-case',
      confidence: 'PENDING_SCOPE_REVIEW',
      time_policy_version: 'bgi-time-v1',
    },
    dependencies: ['BGI.OPPORTUNITY_READINESS'],
    execution_owner: 'QUALIFIED_SPECIALIST',
    approval_requirements: ['Custom quote', 'Founder approval'],
    client_facing_status: 'DISCOVERABLE',
    catalog_version: BUSINESS_GROWTH_CATALOG_VERSION,
  },
  {
    service_id: 'BGI.GROWTH_OPERATIONS',
    family_id: 'GROWTH_OPERATIONS',
    display_name: 'Growth Operations',
    description:
      'Recurring operational support for leads, CRM, follow-up, and measurement — not activated in V1 commerce.',
    deliverables: [
      'Scope-defined CRM and workflow configuration',
      'Conversion measurement plan',
      'Ongoing improvement cadence (when activated)',
    ],
    intake_requirements: ['Approved recurring commercial model', 'Capacity plan'],
    eligibility_criteria: ['Founder-approved scope and support terms'],
    exclusions: ['Automatic subscription activation in V1'],
    pricing_basis: 'Monthly planning range — future',
    commercial_status: 'FUTURE_NOT_ACTIVE',
    proposed_price_min_minor: 20_000,
    proposed_price_max_minor: 75_000,
    proposed_currency: 'USD',
    delivery: {
      estimated_min_business_days: null,
      estimated_max_business_days: null,
      delivery_unit: 'RECURRING',
      min_duration_business_days: null,
      max_duration_business_days: null,
      prerequisites: ['Founder recurring product approval'],
      client_dependencies: ['Ongoing collaboration'],
      external_dependencies: [],
      parallelizable_with_foundation: true,
      required_review_steps: ['Founder commercial activation'],
      capacity_assumption: 'Not scheduled in V1',
      confidence: 'PENDING_SCOPE_REVIEW',
      time_policy_version: 'bgi-time-v1',
    },
    dependencies: [],
    execution_owner: 'SITE00_DIRECT',
    approval_requirements: ['Recurring product approval', 'Support terms'],
    client_facing_status: 'FUTURE',
    catalog_version: BUSINESS_GROWTH_CATALOG_VERSION,
  },
  {
    service_id: 'BGI.BUSINESS_GROWTH_PACKAGE',
    family_id: 'GROWTH_OPERATIONS',
    display_name: 'Business Growth Package',
    description: 'Optional bundled configuration — contents and discount rules require founder approval.',
    deliverables: ['Bundle-defined deliverables per included services'],
    intake_requirements: ['Individual service scopes approved'],
    eligibility_criteria: ['Founder-approved bundle configuration'],
    exclusions: ['Unlimited services under one price'],
    pricing_basis: 'Sum of approved service rates with optional bundle discount',
    commercial_status: 'PROPOSED_NOT_ACTIVE',
    proposed_price_min_minor: null,
    proposed_price_max_minor: null,
    proposed_currency: 'USD',
    delivery: {
      estimated_min_business_days: null,
      estimated_max_business_days: null,
      delivery_unit: 'CUSTOM',
      min_duration_business_days: null,
      max_duration_business_days: null,
      prerequisites: ['Component services defined'],
      client_dependencies: [],
      external_dependencies: [],
      parallelizable_with_foundation: true,
      required_review_steps: ['Founder bundle approval'],
      capacity_assumption: 'Derived from included services',
      confidence: 'PENDING_SCOPE_REVIEW',
      time_policy_version: 'bgi-time-v1',
    },
    dependencies: [],
    execution_owner: 'SITE00_DIRECT',
    approval_requirements: ['Founder bundle pricing'],
    client_facing_status: 'HIDDEN',
    catalog_version: BUSINESS_GROWTH_CATALOG_VERSION,
  },
];

export function getBusinessGrowthCatalog(): BusinessGrowthServiceDefinition[] {
  return catalog.map((s) => ({ ...s, deliverables: [...s.deliverables], dependencies: [...s.dependencies] }));
}

export function findGrowthService(serviceId: BusinessGrowthServiceId): BusinessGrowthServiceDefinition | undefined {
  return catalog.find((s) => s.service_id === serviceId);
}

export function listGrowthServiceFamilies(): BusinessGrowthServiceDefinition['family_id'][] {
  return ['VISIBILITY', 'PRESENCE', 'OPPORTUNITY', 'SALES_SYSTEMS', 'GROWTH_OPERATIONS'];
}
