import type {
  ClientReviewObject,
  ClientReviewVersion,
  ClientDecisionHistoryEvent,
  ApprovalConsequence,
} from './types.js';
import { clientReviewStatusLabel } from './translators.js';

export const PREVIEW_REVIEW_PROJECT_SLUG = 'preview-client-room';
export const PREVIEW_REVIEW_PROJECT_ID = 'preview';

const IDENTITY_CONSEQUENCES: ApprovalConsequence = {
  label: 'This direction will become the visual authority for the next phase.',
  items: ['Brand palette', 'Typography direction', 'Photography language', 'Homepage art direction'],
};

const HOMEPAGE_CONSEQUENCES: ApprovalConsequence = {
  label: 'This homepage direction will guide the next design phase.',
  items: ['Hero composition', 'Page hierarchy', 'Visual tone', 'Mobile adaptation'],
};

function iso(daysAgo: number): string {
  const d = new Date('2026-08-26T12:00:00Z');
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export const PREVIEW_REVIEW_VERSIONS: Record<string, ClientReviewVersion> = {
  'rv-id-dir-v04': {
    versionId: 'rv-id-dir-v04',
    reviewId: 'review-identity-direction-02',
    label: 'V04',
    createdAt: iso(0),
    clientSummary: 'Current presentation',
    previewAssetUrl: null,
    previewAssetAlt: 'Identity direction 02 preview',
    availableViewports: ['MOBILE', 'TABLET', 'DESKTOP'],
    status: 'READY_FOR_REVIEW',
    isCurrent: true,
    isApproved: false,
    isSuperseded: false,
  },
  'rv-id-dir-v03': {
    versionId: 'rv-id-dir-v03',
    reviewId: 'review-identity-direction-02',
    label: 'V03',
    createdAt: iso(1),
    clientSummary: 'Typography refinement',
    previewAssetUrl: null,
    previewAssetAlt: 'Identity direction 02 v03',
    availableViewports: ['MOBILE', 'TABLET', 'DESKTOP'],
    status: 'SUPERSEDED',
    isCurrent: false,
    isApproved: false,
    isSuperseded: true,
  },
  'rv-id-dir-v02': {
    versionId: 'rv-id-dir-v02',
    reviewId: 'review-identity-direction-02',
    label: 'V02',
    createdAt: iso(2),
    clientSummary: 'Composition update',
    previewAssetUrl: null,
    previewAssetAlt: 'Identity direction 02 v02',
    availableViewports: ['DESKTOP', 'TABLET'],
    status: 'SUPERSEDED',
    isCurrent: false,
    isApproved: false,
    isSuperseded: true,
  },
  'rv-id-dir-v01': {
    versionId: 'rv-id-dir-v01',
    reviewId: 'review-identity-direction-02',
    label: 'V01',
    createdAt: iso(3),
    clientSummary: 'First presentation',
    previewAssetUrl: null,
    previewAssetAlt: 'Identity direction 02 v01',
    availableViewports: ['DESKTOP'],
    status: 'SUPERSEDED',
    isCurrent: false,
    isApproved: false,
    isSuperseded: true,
  },
  'rv-id-dir-01-v01': {
    versionId: 'rv-id-dir-01-v01',
    reviewId: 'review-identity-direction-02',
    label: 'DIRECTION 01',
    createdAt: iso(4),
    clientSummary: 'Alternate direction for compare',
    previewAssetUrl: null,
    previewAssetAlt: 'Identity direction 01',
    availableViewports: ['MOBILE', 'TABLET', 'DESKTOP'],
    status: 'SUPERSEDED',
    isCurrent: false,
    isApproved: false,
    isSuperseded: false,
  },
  'rv-home-v03': {
    versionId: 'rv-home-v03',
    reviewId: 'review-homepage-direction',
    label: 'V03',
    createdAt: iso(1),
    clientSummary: 'Mobile layout refinement',
    previewAssetUrl: null,
    previewAssetAlt: 'Homepage direction v03',
    availableViewports: ['MOBILE', 'TABLET', 'DESKTOP'],
    status: 'REVISION_IN_PROGRESS',
    isCurrent: true,
    isApproved: false,
    isSuperseded: false,
  },
  'rv-home-v02': {
    versionId: 'rv-home-v02',
    reviewId: 'review-homepage-direction',
    label: 'V02',
    createdAt: iso(5),
    clientSummary: 'Previous homepage iteration',
    previewAssetUrl: null,
    previewAssetAlt: 'Homepage direction v02',
    availableViewports: ['MOBILE', 'TABLET', 'DESKTOP'],
    status: 'SUPERSEDED',
    isCurrent: false,
    isApproved: false,
    isSuperseded: true,
  },
};

export const PREVIEW_REVIEW_OBJECTS: ClientReviewObject[] = [
  {
    reviewId: 'review-identity-direction-02',
    projectId: PREVIEW_REVIEW_PROJECT_ID,
    projectSlug: PREVIEW_REVIEW_PROJECT_SLUG,
    phaseId: 'identity',
    phaseLabel: 'IDENTITY',
    objectType: 'IDENTITY_DIRECTION',
    title: 'IDENTITY DIRECTION 02',
    subtitle: 'Three directions prepared — Direction 02 is ready for your decision',
    status: 'READY_FOR_REVIEW',
    statusLabel: clientReviewStatusLabel('READY_FOR_REVIEW'),
    currentVersionId: 'rv-id-dir-v04',
    availableVersionIds: ['rv-id-dir-v04', 'rv-id-dir-v03', 'rv-id-dir-v02', 'rv-id-dir-v01', 'rv-id-dir-01-v01'],
    availableViewports: ['MOBILE', 'TABLET', 'DESKTOP'],
    referenceAvailable: false,
    compareAvailable: true,
    compareMode: 'DIRECTION_DIRECTION',
    compareLeftLabel: 'DIRECTION 01',
    compareRightLabel: 'DIRECTION 02',
    compareLeftVersionId: 'rv-id-dir-01-v01',
    compareRightVersionId: 'rv-id-dir-v04',
    commentingAllowed: true,
    annotationAllowed: true,
    approvalAllowed: true,
    revisionAllowed: true,
    declineAllowed: true,
    approvalConsequences: IDENTITY_CONSEQUENCES,
    thumbnailUrl: null,
    readyAt: iso(0),
    updatedAt: iso(0),
    actionRequired: true,
    versionLabel: 'V04',
  },
  {
    reviewId: 'review-homepage-direction',
    projectId: PREVIEW_REVIEW_PROJECT_ID,
    projectSlug: PREVIEW_REVIEW_PROJECT_SLUG,
    phaseId: 'website',
    phaseLabel: 'WEBSITE',
    objectType: 'HOMEPAGE_DIRECTION',
    title: 'HOMEPAGE DIRECTION',
    subtitle: 'Revision in progress after your feedback',
    status: 'REVISION_IN_PROGRESS',
    statusLabel: clientReviewStatusLabel('REVISION_IN_PROGRESS'),
    currentVersionId: 'rv-home-v03',
    availableVersionIds: ['rv-home-v03', 'rv-home-v02'],
    availableViewports: ['MOBILE', 'TABLET', 'DESKTOP'],
    referenceAvailable: true,
    compareAvailable: true,
    compareMode: 'PREVIOUS_CURRENT',
    compareLeftLabel: 'PREVIOUS',
    compareRightLabel: 'CURRENT',
    compareLeftVersionId: 'rv-home-v02',
    compareRightVersionId: 'rv-home-v03',
    commentingAllowed: true,
    annotationAllowed: true,
    approvalAllowed: false,
    revisionAllowed: false,
    declineAllowed: false,
    approvalConsequences: HOMEPAGE_CONSEQUENCES,
    thumbnailUrl: null,
    readyAt: iso(5),
    updatedAt: iso(1),
    actionRequired: false,
    versionLabel: 'V03',
  },
  {
    reviewId: 'review-brand-system',
    projectId: PREVIEW_REVIEW_PROJECT_ID,
    projectSlug: PREVIEW_REVIEW_PROJECT_SLUG,
    phaseId: 'identity',
    phaseLabel: 'IDENTITY',
    objectType: 'BRAND_SYSTEM',
    title: 'BRAND SYSTEM',
    subtitle: 'Approved Aug 25',
    status: 'APPROVED',
    statusLabel: clientReviewStatusLabel('APPROVED'),
    currentVersionId: 'rv-id-dir-v03',
    availableVersionIds: ['rv-id-dir-v03'],
    availableViewports: ['DESKTOP'],
    referenceAvailable: false,
    compareAvailable: false,
    compareMode: null,
    compareLeftLabel: null,
    compareRightLabel: null,
    compareLeftVersionId: null,
    compareRightVersionId: null,
    commentingAllowed: false,
    annotationAllowed: false,
    approvalAllowed: false,
    revisionAllowed: false,
    declineAllowed: false,
    approvalConsequences: null,
    thumbnailUrl: null,
    readyAt: iso(10),
    updatedAt: iso(2),
    actionRequired: false,
    versionLabel: 'V03',
  },
];

export function getPreviewVersionsForReview(reviewId: string): ClientReviewVersion[] {
  const review = PREVIEW_REVIEW_OBJECTS.find((r) => r.reviewId === reviewId);
  if (!review) return [];
  return review.availableVersionIds.map((id) => PREVIEW_REVIEW_VERSIONS[id]).filter(Boolean);
}

export const PREVIEW_DECISION_HISTORY: ClientDecisionHistoryEvent[] = [
  { id: 'dh1', dateLabel: 'AUG 24', summary: 'Review opened for identity directions', type: 'OPENED' },
  { id: 'dh2', dateLabel: 'AUG 25', summary: 'Direction 02 was approved for brand system exploration', type: 'APPROVAL' },
];
