export const P0_VR_TWIN_V23R1_BUILD = 'v374' as const;

export const RENDER_PRIMITIVES = [
  'DOM_TEXT',
  'DOM_CONTROL',
  'DOM_STRUCTURE',
  'CSS_GRAPHIC',
  'SVG_GRAPHIC',
  'IMAGE_ASSET',
  'MEDIA_ASSET',
] as const;

export const FORBIDDEN_RASTER_ROLES = [
  'TEXT',
  'NAVIGATION',
  'BUTTONS',
  'METRICS',
  'STATUS_LABELS',
  'PROGRESS_BARS',
  'DIVIDERS',
  'SECTION_TITLES',
  'ACTIVITY_ROWS',
  'PAGE_SHELL',
  'PROJECT_MASTHEAD',
  'FUNCTION_LABELS',
  'TABLES',
  'FORM_CONTROLS',
] as const;

export const MAX_CLIENT_RASTER_COVERAGE = 0.35;

export const TWIN_V23R1_ERROR_CODES = [
  'TWIN_V2_NON_IMAGE_RASTERIZATION',
  'TWIN_V2_DEBUG_COPY_LEAK',
  'TWIN_V2_OBJECT_TRANSLATION_FAILED',
  'TWIN_V2_IMAGE_SLOT_UI_CONTAMINATION',
  'TWIN_V2_FULL_AUTHORITY_RASTER_USAGE',
] as const;
