/**
 * Machine-readable service inventory snapshot for audits.
 */

import type { ServiceInventoryEntry } from './types.js';

/** Discovered customer-facing monetizable surfaces (2026-09-29 audit). */
export const SITE00_SERVICE_INVENTORY: readonly ServiceInventoryEntry[] = [
  {
    serviceId: 'services-hub-branding',
    serviceName: 'Branding & Identity (hub)',
    publicRoute: '/services',
    servicePageRoute: '/idnty',
    packageSource: 'src/site00/config/identity.ts (IDNTY_INVESTMENT_TIERS)',
    pricingSource: 'Hardcoded display tiers (not evolve-commercial)',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'None — intake submit only',
    intakeRoute: '/idnty/:stateSlug/* → /api/site00/intakes (IDENTITY)',
    projectType: 'IDENTITY (on admin conversion)',
    fulfillmentSystem: 'Project identity module + brand/lore pipelines',
    clientWorkspaceRoute: '/projects/:slug/identity',
    deliveryDestination: 'Identity system assets / project library',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'CUSTOM_QUOTE',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'idnty-investment-tiers',
    serviceName: 'IDNTY state investment tiers (4 states)',
    publicRoute: '/idnty/state',
    servicePageRoute: '/idnty/:stateSlug',
    packageSource: 'IDNTY_INVESTMENT_TIERS',
    pricingSource: 'React config display FROM $X',
    ctaType: 'ASSESSMENT',
    purchaseEntryPoint: 'None',
    intakeRoute: 'Assessment → optional intake API',
    projectType: 'IDENTITY',
    fulfillmentSystem: 'Manual founder conversion',
    clientWorkspaceRoute: '/account/intakes',
    deliveryDestination: 'FOUNDER_DEFINITION_REQUIRED',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'bldr-site-class',
    serviceName: 'BLDR SITE (simple property scale)',
    publicRoute: '/bldr/state',
    servicePageRoute: '/bldr/site/*',
    packageSource: 'BLDR_IMMERSIVE_PORTALS id=site',
    pricingSource: 'FROM $4K+ display (bldr-classification.ts)',
    ctaType: 'INTAKE',
    purchaseEntryPoint: '/api/site00/client-production activate-project (manual/demo)',
    intakeRoute: '/bldr/:classSlug → BUILDER intake API',
    projectType: 'SITE / build_class SITE',
    fulfillmentSystem: 'Studio + design workspace + provisioning',
    clientWorkspaceRoute: '/studio/:projectSlug',
    deliveryDestination: 'Published site / studio deliverables',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'bldr-world-class',
    serviceName: 'BLDR WORLD (custom experience scale)',
    publicRoute: '/bldr/state',
    servicePageRoute: '/bldr/world/*',
    packageSource: 'BLDR scale WORLD portal',
    pricingSource: 'FROM $10K+ display',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'Same as SITE — payment_state on project',
    intakeRoute: 'BUILDER intake (world phases)',
    projectType: 'WORLD / experience_class',
    fulfillmentSystem: 'Design workspace + Studio World capable paths',
    clientWorkspaceRoute: '/projects/design/:projectSlug',
    deliveryDestination: 'Experience / world deliverables',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'bldr-enterprise-class',
    serviceName: 'BLDR ENTERPRISE',
    publicRoute: '/bldr/state',
    servicePageRoute: '/bldr/enterprise/*',
    packageSource: 'BLDR enterprise portal',
    pricingSource: 'FROM $25K+ display',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'Manual / demo activation',
    intakeRoute: 'BUILDER intake',
    projectType: 'WORLD / enterprise recipes',
    fulfillmentSystem: 'Studio + custom production',
    clientWorkspaceRoute: '/studio/:projectSlug',
    deliveryDestination: 'FOUNDER_DEFINITION_REQUIRED',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'CUSTOM_QUOTE',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'evolve-path-refine',
    serviceName: 'EVOLVE path REFINE',
    publicRoute: '/evolve/state',
    servicePageRoute: '/evolve/refine/*',
    packageSource: 'evolve-assessment.ts',
    pricingSource: 'None on path pages',
    ctaType: 'ASSESSMENT',
    purchaseEntryPoint: 'None',
    intakeRoute: 'Path assessment only',
    projectType: 'Existing project EVOLVE tab',
    fulfillmentSystem: 'Project /evolve modules',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'Project evolution deliverables',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'DISPLAY_ONLY',
  },
  {
    serviceId: 'evolve-path-install',
    serviceName: 'EVOLVE path INSTALL',
    publicRoute: '/evolve/state',
    servicePageRoute: '/evolve/install/*',
    packageSource: 'evolve-assessment.ts',
    pricingSource: 'None',
    ctaType: 'ASSESSMENT',
    purchaseEntryPoint: 'None',
    intakeRoute: 'Assessment',
    projectType: 'EVOLVE project scope',
    fulfillmentSystem: 'Project EVOLVE OS',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'FOUNDER_DEFINITION_REQUIRED',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'DISPLAY_ONLY',
  },
  {
    serviceId: 'evolve-path-transform',
    serviceName: 'EVOLVE path TRANSFORM',
    publicRoute: '/evolve/state',
    servicePageRoute: '/evolve/transform/*',
    packageSource: 'evolve-assessment.ts',
    pricingSource: 'None',
    ctaType: 'ASSESSMENT',
    purchaseEntryPoint: 'None',
    intakeRoute: 'Assessment',
    projectType: 'EVOLVE project',
    fulfillmentSystem: 'Project EVOLVE OS',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'FOUNDER_DEFINITION_REQUIRED',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'DISPLAY_ONLY',
  },
  {
    serviceId: 'evolve-pricing-ui-self-directed',
    serviceName: 'EVOLVE Pricing UI (self-directed SaaS-style)',
    publicRoute: '/evolve/plans',
    servicePageRoute: '/evolve/plans',
    packageSource: 'shared/site00-evolve-pricing/catalog.ts',
    pricingSource: 'evolve-pricing catalog ($39–$179/mo, project pass)',
    ctaType: 'SIGN_IN',
    purchaseEntryPoint: '/origin/sign-in?plan=… or /contact?offer=…',
    intakeRoute: 'None',
    projectType: 'None automatic',
    fulfillmentSystem: 'None wired',
    clientWorkspaceRoute: null,
    deliveryDestination: null,
    billingClass: 'SUBSCRIPTION',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'DISPLAY_ONLY',
  },
  {
    serviceId: 'evolve-commercial-foundation',
    serviceName: 'EVOLVE Foundation activation',
    publicRoute: 'ORPHAN (EvolveCommercialPage unrouted)',
    servicePageRoute: 'N/A — use admin/API',
    packageSource: 'shared/site00-evolve-commercial/catalog.ts',
    pricingSource: 'Canonical catalog ($1,500 one-time)',
    ctaType: 'NONE',
    purchaseEntryPoint: 'Admin setEvolveCommercialPlan / metadata',
    intakeRoute: 'EVOLVE OS onboarding (project-scoped)',
    projectType: 'Organization marketing profile',
    fulfillmentSystem: 'EVOLVE OS + governance',
    clientWorkspaceRoute: '/control/evolve-operations',
    deliveryDestination: 'Foundation intelligence artifacts',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'ORPHANED',
  },
  {
    serviceId: 'evolve-recurring-essential',
    serviceName: 'EVOLVE Essential plan',
    publicRoute: 'ORPHAN public page / admin only',
    servicePageRoute: 'Admin evolve orchestration',
    packageSource: 'evolve-commercial catalog evolve_essential',
    pricingSource: 'Canonical catalog $1,250/mo',
    ctaType: 'NONE',
    purchaseEntryPoint: 'Admin plan assignment',
    intakeRoute: 'Foundation + EVOLVE OS',
    projectType: 'Org + active campaigns',
    fulfillmentSystem: 'EVOLVE OS production modules',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'Monthly assets / campaigns',
    billingClass: 'RETAINER',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'evolve-recurring-growth',
    serviceName: 'EVOLVE Growth plan',
    publicRoute: 'ORPHAN public page',
    servicePageRoute: 'Admin',
    packageSource: 'evolve-commercial evolve_growth',
    pricingSource: 'Catalog $2,500/mo',
    ctaType: 'NONE',
    purchaseEntryPoint: 'Admin',
    intakeRoute: 'EVOLVE OS',
    projectType: 'Org campaigns',
    fulfillmentSystem: 'EVOLVE OS',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'Campaign + asset outputs',
    billingClass: 'RETAINER',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'evolve-recurring-studio',
    serviceName: 'EVOLVE Studio plan',
    publicRoute: 'ORPHAN public page',
    servicePageRoute: 'Admin',
    packageSource: 'evolve-commercial evolve_studio',
    pricingSource: 'Catalog $4,500/mo',
    ctaType: 'NONE',
    purchaseEntryPoint: 'Admin',
    intakeRoute: 'EVOLVE OS',
    projectType: 'Multi-campaign org',
    fulfillmentSystem: 'EVOLVE OS + Studio World capable',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'FOUNDER_DEFINITION_REQUIRED',
    billingClass: 'RETAINER',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'evolve-recurring-private',
    serviceName: 'EVOLVE Private plan',
    publicRoute: 'ORPHAN public page',
    servicePageRoute: 'Admin',
    packageSource: 'evolve-commercial evolve_private',
    pricingSource: 'Catalog from $7,500/mo',
    ctaType: 'CONTACT',
    purchaseEntryPoint: 'Custom scope / admin',
    intakeRoute: 'EVOLVE OS',
    projectType: 'Dedicated org',
    fulfillmentSystem: 'EVOLVE OS',
    clientWorkspaceRoute: '/control/evolve-operations',
    deliveryDestination: 'FOUNDER_DEFINITION_REQUIRED',
    billingClass: 'CUSTOM_QUOTE',
    paymentReadiness: 'CUSTOM_QUOTE',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'evolve-project-creative-direction-intensive',
    serviceName: 'Creative Direction Intensive',
    publicRoute: 'Catalog only',
    servicePageRoute: 'Admin / project services',
    packageSource: 'evolve-commercial project services',
    pricingSource: 'Catalog project-scoped cents',
    ctaType: 'CONTACT',
    purchaseEntryPoint: 'Admin / quote',
    intakeRoute: 'Project EVOLVE brief',
    projectType: 'Project service engagement',
    fulfillmentSystem: 'Creative direction pipeline',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'CD territories / approvals',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'CUSTOM_QUOTE',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'evolve-project-launch-campaign',
    serviceName: 'Launch Campaign (EVOLVE project service)',
    publicRoute: 'Catalog only',
    servicePageRoute: 'Admin',
    packageSource: 'evolve-commercial launch_campaign',
    pricingSource: 'Catalog',
    ctaType: 'CONTACT',
    purchaseEntryPoint: 'Admin',
    intakeRoute: 'Campaign brief',
    projectType: 'Campaign project',
    fulfillmentSystem: 'EVOLVE + possible Studio World overlap',
    clientWorkspaceRoute: '/projects/:slug/evolve',
    deliveryDestination: 'Campaign deliverables',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'CUSTOM_QUOTE',
    wiringStatus: 'DUPLICATED',
  },
  {
    serviceId: 'marketing-social-content',
    serviceName: 'Marketing — Social Content',
    publicRoute: '/evolve/marketing',
    servicePageRoute: '/evolve/marketing/services → intake/social-content',
    packageSource: 'serviceTaxonomy + entitlementTemplates',
    pricingSource: 'No public dollar SKUs — FOUNDER_PRICING_REQUIRED for add-ons',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'confirm-payment on engagement (simulated)',
    intakeRoute: '/evolve/marketing/intake/social-content',
    projectType: 'Marketing engagement (+ optional project_id)',
    fulfillmentSystem: 'Studio World adapter + commercial pipeline',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'Engagement deliverables + vault links',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'marketing-product-campaign',
    serviceName: 'Marketing — Product Campaign',
    publicRoute: '/evolve/marketing',
    servicePageRoute: '/evolve/marketing/intake/product-campaign',
    packageSource: 'serviceTaxonomy',
    pricingSource: 'Intake',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'confirm-payment',
    intakeRoute: '/evolve/marketing/intake/product-campaign',
    projectType: 'Engagement',
    fulfillmentSystem: 'Studio World',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'Product campaign assets',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'marketing-brand-film',
    serviceName: 'Marketing — Brand Film',
    publicRoute: '/evolve/marketing',
    servicePageRoute: '/evolve/marketing/intake/brand-film',
    packageSource: 'serviceTaxonomy',
    pricingSource: 'Intake',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'confirm-payment',
    intakeRoute: '/evolve/marketing/intake/brand-film',
    projectType: 'Engagement',
    fulfillmentSystem: 'Studio World',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'Film deliverables',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'marketing-ugc-style',
    serviceName: 'Marketing — UGC-Style',
    publicRoute: '/evolve/marketing',
    servicePageRoute: '/evolve/marketing/intake/ugc-style',
    packageSource: 'serviceTaxonomy',
    pricingSource: 'Intake',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'confirm-payment',
    intakeRoute: '/evolve/marketing/intake/ugc-style',
    projectType: 'Engagement',
    fulfillmentSystem: 'Studio World',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'UGC-style cuts',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'marketing-campaign',
    serviceName: 'Marketing — Campaign',
    publicRoute: '/evolve/marketing',
    servicePageRoute: '/evolve/marketing/intake/campaign',
    packageSource: 'serviceTaxonomy',
    pricingSource: 'Intake/scope — no fixed checkout price',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'marketing-engagements confirm-payment',
    intakeRoute: '/evolve/marketing/intake/campaign',
    projectType: 'Marketing engagement',
    fulfillmentSystem: 'Studio World + NME/casting (operational)',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'Campaign assets / deliverables',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'marketing-launch-campaign',
    serviceName: 'Marketing — Launch Campaign',
    publicRoute: '/evolve/marketing',
    servicePageRoute: '/evolve/marketing/intake/launch-campaign',
    packageSource: 'serviceTaxonomy',
    pricingSource: 'Intake',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'confirm-payment',
    intakeRoute: '/evolve/marketing/intake/launch-campaign',
    projectType: 'Engagement',
    fulfillmentSystem: 'Studio World',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'Launch creative set',
    billingClass: 'ONE_TIME',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'marketing-content-system',
    serviceName: 'Marketing — Content System',
    publicRoute: '/evolve/marketing',
    servicePageRoute: '/evolve/marketing/intake/content-system',
    packageSource: 'serviceTaxonomy',
    pricingSource: 'Intake',
    ctaType: 'INTAKE',
    purchaseEntryPoint: 'confirm-payment',
    intakeRoute: '/evolve/marketing/intake/content-system',
    projectType: 'Engagement',
    fulfillmentSystem: 'Studio World + entitlements',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'Recurring content outputs',
    billingClass: 'RETAINER',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
  {
    serviceId: 'control-ongoing-support',
    serviceName: 'Ongoing Support (hub copy)',
    publicRoute: '/support',
    servicePageRoute: '/support',
    packageSource: 'SITE00_SUPPORT_TOPICS_SEED',
    pricingSource: 'None',
    ctaType: 'CONTACT',
    purchaseEntryPoint: 'None',
    intakeRoute: null,
    projectType: null,
    fulfillmentSystem: 'None',
    clientWorkspaceRoute: '/control',
    deliveryDestination: null,
    billingClass: 'SUBSCRIPTION',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'DISPLAY_ONLY',
  },
  {
    serviceId: 'control-billing-shell',
    serviceName: 'Control Room billing module',
    publicRoute: '/control/billing',
    servicePageRoute: '/control/billing',
    packageSource: 'Placeholder UI',
    pricingSource: 'None',
    ctaType: 'NONE',
    purchaseEntryPoint: 'None',
    intakeRoute: null,
    projectType: null,
    fulfillmentSystem: 'None',
    clientWorkspaceRoute: '/control/billing',
    deliveryDestination: null,
    billingClass: 'SUBSCRIPTION',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'DISPLAY_ONLY',
  },
  {
    serviceId: 'studio-world-add-ons',
    serviceName: 'Studio World modular add-ons (16 types)',
    publicRoute: 'Engagement workspace / production UI',
    servicePageRoute: 'N/A',
    packageSource: 'modular-production-engine ADD_ON_TYPES',
    pricingSource: 'FOUNDER_PRICING_REQUIRED',
    ctaType: 'NONE',
    purchaseEntryPoint: 'commercial-test-addon (EXTRA_CHARACTER, NEW_ACTOR only)',
    intakeRoute: 'N/A',
    projectType: 'Marketing engagement commercial_state',
    fulfillmentSystem: 'runProductionAction',
    clientWorkspaceRoute: '/evolve/marketing/engagement/:id',
    deliveryDestination: 'Entitlement credit → resume action',
    billingClass: 'ADD_ON',
    paymentReadiness: 'NOT_PAYMENT_READY',
    wiringStatus: 'PARTIALLY_WIRED',
  },
] as const;

export const SERVICE_COUNT = SITE00_SERVICE_INVENTORY.length;
