import type { ServiceWiringMatrixRow } from './types.js';

/** Summary matrix — see docs/SITE_00_ALL_SERVICES_COMMERCIAL_WIRING_AUDIT1.md for narrative. */
export const SERVICE_WIRING_MATRIX: readonly ServiceWiringMatrixRow[] = [
  {
    service: 'IDNTY',
    publicPage: 'PASS',
    package: 'PARTIAL',
    purchase: 'FAIL',
    intake: 'PASS',
    project: 'PARTIAL',
    pipeline: 'PARTIAL',
    entitlement: 'MISSING',
    clientStatus: 'PARTIAL',
    deliverable: 'PARTIAL',
    paymentReady: 'FAIL',
  },
  {
    service: 'BLDR SITE/WORLD/ENTERPRISE',
    publicPage: 'PASS',
    package: 'PARTIAL',
    purchase: 'PARTIAL',
    intake: 'PASS',
    project: 'PASS',
    pipeline: 'PASS',
    entitlement: 'FAIL',
    clientStatus: 'PARTIAL',
    deliverable: 'PARTIAL',
    paymentReady: 'FAIL',
  },
  {
    service: 'EVOLVE paths (refine/install/transform)',
    publicPage: 'PASS',
    package: 'MISSING',
    purchase: 'FAIL',
    intake: 'PARTIAL',
    project: 'PARTIAL',
    pipeline: 'PASS',
    entitlement: 'FAIL',
    clientStatus: 'PARTIAL',
    deliverable: 'PARTIAL',
    paymentReady: 'FAIL',
  },
  {
    service: 'EVOLVE /evolve/plans (pricing UI)',
    publicPage: 'PASS',
    package: 'PASS',
    purchase: 'FAIL',
    intake: 'FAIL',
    project: 'FAIL',
    pipeline: 'FAIL',
    entitlement: 'FAIL',
    clientStatus: 'FAIL',
    deliverable: 'FAIL',
    paymentReady: 'FAIL',
  },
  {
    service: 'EVOLVE commercial catalog (managed SKUs)',
    publicPage: 'FAIL',
    package: 'PASS',
    purchase: 'PARTIAL',
    intake: 'PARTIAL',
    project: 'PASS',
    pipeline: 'PASS',
    entitlement: 'PARTIAL',
    clientStatus: 'PARTIAL',
    deliverable: 'PARTIAL',
    paymentReady: 'FAIL',
  },
  {
    service: 'Marketing & Content (7 categories)',
    publicPage: 'PASS',
    package: 'PARTIAL',
    purchase: 'PARTIAL',
    intake: 'PASS',
    project: 'PASS',
    pipeline: 'PARTIAL',
    entitlement: 'PARTIAL',
    clientStatus: 'PARTIAL',
    deliverable: 'PARTIAL',
    paymentReady: 'FAIL',
  },
  {
    service: 'Control / Support / Maintenance',
    publicPage: 'PASS',
    package: 'FAIL',
    purchase: 'FAIL',
    intake: 'FAIL',
    project: 'FAIL',
    pipeline: 'FAIL',
    entitlement: 'FAIL',
    clientStatus: 'FAIL',
    deliverable: 'FAIL',
    paymentReady: 'FAIL',
  },
  {
    service: 'Studio World add-ons',
    publicPage: 'MISSING',
    package: 'PARTIAL',
    purchase: 'PARTIAL',
    intake: 'MISSING',
    project: 'PASS',
    pipeline: 'PARTIAL',
    entitlement: 'PARTIAL',
    clientStatus: 'PARTIAL',
    deliverable: 'PARTIAL',
    paymentReady: 'FAIL',
  },
];
