/**
 * Sprint B4.9R — Deterministic 16-panel storyboard manifest for Entry 002.
 */

import type { FinalCinematicStoryboardPanelManifestEntry } from '../../../shared/site00-expression-engine/finalCinematicStoryboardTypes.js';
import {
  buildEntry002FinalCinematicStoryboardPanelAssetId,
  buildEntry002FinalCinematicStoryboardPanelId,
  ENTRY_002_FINAL_CINEMATIC_STORYBOARD_003_ID,
} from '../../../shared/site00-expression-engine/finalCinematicStoryboardIds.js';
import { ENTRY_002_PRE_STORYBOARD_FOUNDER_APPROVALS } from './entry002PreStoryboardFounderApproval.js';

const AUTH = {
  ndxPresence: 'NDX-ENTRY-002-PRE-SBA-NDX-PRESENCE-001',
  subjectDualEra: 'NDX-ENTRY-002-PRE-SBA-SUBJECT-DUAL-ERA-001',
  ndxHands: 'NDX-ENTRY-002-PRE-SBA-NDX-HANDS-001',
  subjectFashion: 'NDX-ENTRY-002-PRE-SBA-FASHION-CONTINUITY-001',
  phoneGlitch: 'NDX-ENTRY-002-PRE-SBA-PHONE-GLITCH-001',
} as const;

type ManifestSeed = Omit<
  FinalCinematicStoryboardPanelManifestEntry,
  'panelId' | 'assetId' | 'generationStatus' | 'qaStatus' | 'storagePath' | 'previewUrl' | 'contentHash' | 'provider' | 'providerRequestId' | 'panelVersion' | 'previousPanelAssetId'
>;

function manifestEntry(panelNumber: number, seed: ManifestSeed): FinalCinematicStoryboardPanelManifestEntry {
  const storyboardId = ENTRY_002_FINAL_CINEMATIC_STORYBOARD_003_ID;
  const panelVersion = '001';
  return {
    panelId: buildEntry002FinalCinematicStoryboardPanelId(storyboardId, panelNumber),
    assetId: buildEntry002FinalCinematicStoryboardPanelAssetId(storyboardId, panelNumber, panelVersion),
    panelVersion,
    generationStatus: 'PENDING',
    qaStatus: 'PENDING',
    storagePath: null,
    previewUrl: null,
    contentHash: null,
    provider: null,
    providerRequestId: null,
    previousPanelAssetId: panelNumber > 1
      ? buildEntry002FinalCinematicStoryboardPanelAssetId(storyboardId, panelNumber - 1, panelVersion)
      : null,
    ...seed,
  };
}

export function compileEntry002FinalCinematicStoryboardPanelManifest(): FinalCinematicStoryboardPanelManifestEntry[] {
  return [
    manifestEntry(1, {
      panelNumber: 1,
      beatId: 'DISCOVERY',
      storyFunction: 'CLAIM begins — NDX discovers 2026 praised post',
      description: 'Over-shoulder NDX observes phone. Subject woman FULL BODY in 2026 post.',
      cameraFraming: 'over-shoulder',
      cameraAngle: 'observer partial',
      subjectVisibility: 'full-body in phone post',
      ndxVisibility: 'partial shoulder/bun silhouette only',
      phoneState: '2026 praised post visible',
      era: '2026',
      environmentState: 'present-day observer space',
      requiredAuthorityIds: [AUTH.ndxPresence, AUTH.ndxHands, AUTH.subjectDualEra, AUTH.subjectFashion],
      continuityRequirements: ['NDX lime nails', 'subject French tips', 'full-body not portrait'],
      requiredText: null,
      transitionIn: 'cold open',
      transitionOut: 'praise accelerates',
    }),
    manifestEntry(2, {
      panelNumber: 2,
      beatId: 'PRAISE_ARRIVES',
      storyFunction: '2026 praise recognition beat',
      description: 'Closer phone shot. Praise: 2016 WAS ICONIC / TAKE ME BACK. NDX lime nail pauses.',
      cameraFraming: 'phone insert macro',
      cameraAngle: 'close interaction',
      subjectVisibility: 'full-body outfit-led post',
      ndxVisibility: 'macro hand only',
      phoneState: 'live praise accumulating',
      era: '2026',
      environmentState: 'present',
      requiredAuthorityIds: [AUTH.ndxHands, AUTH.phoneGlitch, AUTH.subjectFashion],
      continuityRequirements: ['short lime nails', 'wait recognition energy'],
      requiredText: '2016 WAS ICONIC',
      transitionIn: 'from discovery',
      transitionOut: 'profile tap',
    }),
    manifestEntry(3, {
      panelNumber: 3,
      beatId: 'PROFILE_TAP',
      storyFunction: 'NDX enters subject profile',
      description: 'Macro profile tap. Lime nails. NDX separate from subject woman.',
      cameraFraming: 'macro hand on phone',
      cameraAngle: 'top-down interaction',
      subjectVisibility: 'profile thumbnail hint',
      ndxVisibility: 'hand/macro only',
      phoneState: 'profile button tap',
      era: '2026',
      environmentState: 'present',
      requiredAuthorityIds: [AUTH.ndxHands, AUTH.phoneGlitch],
      continuityRequirements: ['lime nails not French tips'],
      requiredText: null,
      transitionIn: 'from praise',
      transitionOut: 'profile grid opens',
    }),
    manifestEntry(4, {
      panelNumber: 4,
      beatId: 'PROFILE_GRID',
      storyFunction: 'Varied full-body profile grid',
      description: 'Same subject woman grid — mirror, nightlife, side angle, walking, seated — no repeated face pose.',
      cameraFraming: 'phone profile grid insert',
      cameraAngle: 'straight-on screen',
      subjectVisibility: 'varied full-body posts',
      ndxVisibility: 'absent or edge hand',
      phoneState: 'profile grid open',
      era: '2026',
      environmentState: 'present',
      requiredAuthorityIds: [AUTH.subjectDualEra, AUTH.subjectFashion, AUTH.phoneGlitch],
      continuityRequirements: ['pose variation required', 'same woman identity'],
      requiredText: null,
      transitionIn: 'profile opened',
      transitionOut: 'scroll begins',
    }),
    manifestEntry(5, {
      panelNumber: 5,
      beatId: 'SCROLL_BEGINS',
      storyFunction: 'Aggressive backward scroll starts',
      description: 'NDX scrolls profile backward. Movement subtle at first.',
      cameraFraming: 'hand driving scroll',
      cameraAngle: 'macro scroll',
      subjectVisibility: 'archive thumbnails streaking',
      ndxVisibility: 'hand only',
      phoneState: 'profile scroll active',
      era: 'TRANSITION',
      environmentState: 'temporal breach beginning',
      requiredAuthorityIds: [AUTH.ndxHands, AUTH.phoneGlitch],
      continuityRequirements: ['physically grounded hand'],
      requiredText: null,
      transitionIn: 'from grid',
      transitionOut: 'years collapse',
    }),
    manifestEntry(6, {
      panelNumber: 6,
      beatId: 'YEARS_COLLAPSE',
      storyFunction: 'Temporal acceleration 2026→2017',
      description: 'Years streak: 2026 2025 2024 2023 2022 2021 2020 2019 2018 2017 compress visually.',
      cameraFraming: 'phone scroll tunnel',
      cameraAngle: 'dynamic motion',
      subjectVisibility: 'content streaking through years',
      ndxVisibility: 'hand accelerating scroll',
      phoneState: 'temporal smear UI',
      era: 'TRANSITION',
      environmentState: 'memory tunnel',
      requiredAuthorityIds: [AUTH.ndxHands, AUTH.phoneGlitch],
      continuityRequirements: ['not generic cyberpunk portal'],
      requiredText: null,
      transitionIn: 'scroll acceleration',
      transitionOut: '2016 lock-in',
    }),
    manifestEntry(7, {
      panelNumber: 7,
      beatId: '2016_LANDING',
      storyFunction: 'Phone resolves to 2016 Instagram',
      description: 'Old IG UI. SAME WOMAN full body mirror selfie. Same outfit family. Older capture quality.',
      cameraFraming: 'phone screen full',
      cameraAngle: 'straight-on old IG',
      subjectVisibility: 'full-body 2016 mirror selfie',
      ndxVisibility: 'partial edge observer',
      phoneState: '2016 post grid/post',
      era: '2016',
      environmentState: 'mid-2010s social framing',
      requiredAuthorityIds: [AUTH.subjectDualEra, AUTH.subjectFashion, AUTH.phoneGlitch],
      continuityRequirements: ['same woman not different person', '2016 IG language'],
      requiredText: null,
      transitionIn: 'temporal collapse ends',
      transitionOut: 'recognition pause',
    }),
    manifestEntry(8, {
      panelNumber: 8,
      beatId: 'RECOGNITION',
      storyFunction: 'NDX recognition — THERE IT IS',
      description: 'Quiet beat. Lime fingertip hovering over 2016 post.',
      cameraFraming: 'macro hover',
      cameraAngle: 'close shallow depth',
      subjectVisibility: '2016 full-body frozen on screen',
      ndxVisibility: 'macro hand partial',
      phoneState: '2016 post selected hover',
      era: '2016',
      environmentState: 'stillness before tap',
      requiredAuthorityIds: [AUTH.ndxHands, AUTH.phoneGlitch],
      continuityRequirements: ['lime nails', 'recognition energy'],
      requiredText: null,
      transitionIn: 'from 2016 landing',
      transitionOut: 'tap fracture',
    }),
    manifestEntry(9, {
      panelNumber: 9,
      beatId: 'TAP_FRACTURE',
      storyFunction: 'First cultural glitch on tap',
      description: 'NDX taps 2016 post. UI distorts around full-body image. Not RGB chaos.',
      cameraFraming: 'tap contact macro',
      cameraAngle: 'phone fracture',
      subjectVisibility: '2016 image destabilizing',
      ndxVisibility: 'lime-nailed tap',
      phoneState: 'glitch fracture onset',
      era: '2016',
      environmentState: 'cultural memory distortion',
      requiredAuthorityIds: [AUTH.ndxHands, AUTH.phoneGlitch, AUTH.subjectDualEra],
      continuityRequirements: ['cultural glitch not sci-fi portal'],
      requiredText: null,
      transitionIn: 'recognition',
      transitionOut: 'memory lifts',
    }),
    manifestEntry(10, {
      panelNumber: 10,
      beatId: 'MEMORY_LIFTS',
      storyFunction: '2016 image rises from phone dimensionally',
      description: 'Full-body 2016 image lifts as tangible photograph plane from device.',
      cameraFraming: 'dimensional memory shot',
      cameraAngle: 'low angle lift',
      subjectVisibility: 'same woman on rising memory plane',
      ndxVisibility: 'hands guiding extraction',
      phoneState: 'source plane rupture',
      era: '2016',
      environmentState: 'memory becoming physical',
      requiredAuthorityIds: [AUTH.phoneGlitch, AUTH.subjectDualEra, AUTH.ndxHands],
      continuityRequirements: ['phone remains origin', 'dimensional not hologram cliché'],
      requiredText: null,
      transitionIn: 'fracture',
      transitionOut: 'receipts surface',
    }),
    manifestEntry(11, {
      panelNumber: 11,
      beatId: 'RECEIPTS_SURFACE',
      storyFunction: '2016 negative receipts attach to memory',
      description: 'TACKY BASIC OVERDONE DOING TOO MUCH PLAYED OUT on evidence object.',
      cameraFraming: 'memory object with receipts',
      cameraAngle: 'evidence cluster',
      subjectVisibility: 'same woman on lifted memory',
      ndxVisibility: 'partial observer shadow',
      phoneState: 'receipt origin context',
      era: '2016',
      environmentState: 'evidence not comment graveyard',
      requiredAuthorityIds: [AUTH.subjectDualEra, AUTH.phoneGlitch],
      continuityRequirements: ['receipts tied to evidence'],
      requiredText: 'TACKY · BASIC · OVERDONE',
      transitionIn: 'memory lifted',
      transitionOut: 'ndx takes evidence',
    }),
    manifestEntry(12, {
      panelNumber: 12,
      beatId: 'NDX_TAKES_EVIDENCE',
      storyFunction: 'NDX manipulates extracted memory in edit suite',
      description: 'NDX hands on physical memory. Edit suite materials: tape, strips, light table.',
      cameraFraming: 'hands on evidence',
      cameraAngle: 'top-down tactile',
      subjectVisibility: 'archive print of subject',
      ndxVisibility: 'hands stitching — lime nails',
      phoneState: 'secondary evidence anchor',
      era: 'EDIT_SUITE',
      environmentState: 'nostalgia edit suite emerging',
      requiredAuthorityIds: [AUTH.ndxPresence, AUTH.ndxHands, AUTH.subjectFashion],
      continuityRequirements: ['short lime nails', 'edit suite supports not replaces phone story'],
      requiredText: null,
      transitionIn: 'receipts surfaced',
      transitionOut: 'contradiction stitch',
    }),
    manifestEntry(13, {
      panelNumber: 13,
      beatId: 'CONTRADICTION_STITCH',
      storyFunction: 'Align 2016 mockery with 2026 praise',
      description: 'NDX aligns negative 2016 receipts with 2026 praise. Same woman, same fashion.',
      cameraFraming: 'split comparison',
      cameraAngle: 'light-table alignment',
      subjectVisibility: 'both era framings visible',
      ndxVisibility: 'hands assembling comparison',
      phoneState: 'comparison evidence',
      era: 'EDIT_SUITE',
      environmentState: 'contradiction assembly',
      requiredAuthorityIds: [AUTH.ndxHands, AUTH.subjectDualEra, AUTH.subjectFashion],
      continuityRequirements: ['same woman both eras', 'opposite cultural labels'],
      requiredText: null,
      transitionIn: 'evidence taken',
      transitionOut: 'full contradiction',
    }),
    manifestEntry(14, {
      panelNumber: 14,
      beatId: 'FULL_CONTRADICTION',
      storyFunction: 'Contradiction payoff — mocked vs celebrated',
      description: '2016 mocked vs 2026 celebrated. Same woman, same style family. NDX partial investigator.',
      cameraFraming: 'cinematic payoff wide',
      cameraAngle: 'evidence tableau',
      subjectVisibility: 'dual-era same woman visible',
      ndxVisibility: 'partial assembler silhouette',
      phoneState: 'evidence anchor',
      era: 'EDIT_SUITE',
      environmentState: 'contradiction visible',
      requiredAuthorityIds: [AUTH.ndxPresence, AUTH.subjectDualEra, AUTH.subjectFashion],
      continuityRequirements: ['CONTRADICTION → LENS'],
      requiredText: null,
      transitionIn: 'stitch beat',
      transitionOut: 'interjection',
    }),
    manifestEntry(15, {
      panelNumber: 15,
      beatId: 'INTERJECTION',
      storyFunction: 'Mandatory NDX interjection',
      description: 'Decisive interjection beat with visual weight on phone/evidence surface.',
      cameraFraming: 'interjection hero',
      cameraAngle: 'decisive frontal evidence',
      subjectVisibility: 'fashion evidence behind line',
      ndxVisibility: 'partial reflection/silhouette',
      phoneState: 'interjection surface',
      era: 'EDIT_SUITE',
      environmentState: 'decisive beat',
      requiredAuthorityIds: [AUTH.ndxPresence, AUTH.phoneGlitch, AUTH.subjectFashion],
      continuityRequirements: ['mandatory exact line'],
      requiredText: 'THE CLOTHES NEVER GOT AN APOLOGY. JUST A REBRAND.',
      transitionIn: 'contradiction payoff',
      transitionOut: 'snap-back',
    }),
    manifestEntry(16, {
      panelNumber: 16,
      beatId: 'SNAP_BACK',
      storyFunction: 'Phone crack / reality interruption',
      description: 'Phone cracks, signal fails. NDX snapped back to present. Unresolved continuation.',
      cameraFraming: 'interruption close',
      cameraAngle: 'snap-back shock',
      subjectVisibility: 'memory collapsing',
      ndxVisibility: 'partial seated/over-shoulder return',
      phoneState: 'cracked interrupted device',
      era: 'PRESENT',
      environmentState: 'abrupt return to present',
      requiredAuthorityIds: [AUTH.ndxPresence, AUTH.ndxHands, AUTH.phoneGlitch],
      continuityRequirements: ['do not invent next entry', 'mystery preserved'],
      requiredText: null,
      transitionIn: 'interjection',
      transitionOut: 'unresolved handoff',
    }),
  ];
}

export function getEntry002StoryboardAuthorityIds(): string[] {
  return ENTRY_002_PRE_STORYBOARD_FOUNDER_APPROVALS.map((a) => a.authorityId);
}
