/**
 * P0.5E.4 — Generic Embodied Character Founder Discovery constants.
 */

export const EMBODIED_CHARACTER_FOUNDER_DISCOVERY_VERSION =
  'EMBODIED_CHARACTER_FOUNDER_DISCOVERY@P0.5E.4' as const;

export const TRAIT_AUTHORITY_STATES = [
  'SYSTEM_SEEDED',
  'FOUNDER_CONFIRMED',
  'FOUNDER_REVISED',
  'FOUNDER_REJECTED',
  'FOUNDER_ADDED',
  'INFERRED_PENDING_CONFIRMATION',
  'CONTRADICTORY_EVIDENCE',
  'UNRESOLVED',
] as const;

export const CHARACTER_TRUTH_CONFIDENCE_STATES = [
  'CANON',
  'STRONG',
  'EMERGING',
  'HYPOTHESIS',
  'CONTRADICTORY',
  'UNRESOLVED',
  'REJECTED',
] as const;

export const DISCOVERY_DOMAIN_IDS = [
  'CORE_TEMPERAMENT',
  'INTELLIGENCE',
  'HUMOR',
  'EMOTIONAL_LIFE',
  'CONTRADICTIONS',
  'FLAWS',
  'PRIVATE_HUMANITY',
  'FRIENDSHIPS',
  'ROMANCE_ATTRACTION',
  'FAMILY_HISTORY',
  'MONEY_AMBITION',
  'WORK_DISCIPLINE',
  'CULTURAL_LIFE',
  'TASTE',
  'DIGITAL_LIFE',
  'HOME_ENVIRONMENT',
  'SOCIAL_BEHAVIOR',
  'CONFLICT',
  'INSECURITY',
  'CONFIDENCE',
  'CURIOSITY',
  'MORAL_BOUNDARIES',
  'BOOK_RELATIONSHIP',
  'PUBLIC_VS_PRIVATE',
  'PHYSICAL_HABITS',
  'STYLE_BEAUTY',
  'CAMERA_PRESENCE',
  'GROWTH_CAPACITY',
] as const;

export const FOUNDER_DISCOVERY_JUDGMENTS = [
  'YES_EXACTLY',
  'CLOSE_BUT',
  'NO',
  'ABSOLUTELY_NOT',
  'SOMETIMES',
  'DEPENDS',
  'SURPRISINGLY_YES',
  'TOO_POLISHED',
  'TOO_BRAND_LIKE',
  'TOO_COOL',
  'TOO_GENERIC',
  'TOO_PERFECT',
  'TOO_MEAN',
  'TOO_SOFT',
  'TOO_ANALYTICAL',
  'TOO_INFLUENCER',
  'NOT_HUMAN_ENOUGH',
  'NONE_OF_THESE',
  'SOMETHING_ELSE',
  'IT_DEPENDS',
  'I_DONT_KNOW_YET',
  'CUSTOM',
] as const;

export const SCENARIO_ESCAPE_OPTIONS = ['NONE_OF_THESE', 'SOMETHING_ELSE', 'IT_DEPENDS', 'I_DONT_KNOW_YET'] as const;

export const FLAW_CATEGORIES = [
  'CHARMING_FLAW',
  'ACTUAL_FLAW',
  'BLIND_SPOT',
  'ANNOYING_TRAIT',
  'SELF_SABOTAGING_BEHAVIOR',
  'SOCIAL_WEAKNESS',
  'INTELLECTUAL_WEAKNESS',
  'EMOTIONAL_WEAKNESS',
] as const;

export const SECRETLY_FLATTERING_FLAW_PATTERNS = [
  'CARES TOO MUCH',
  'TOO PASSIONATE',
  'TOO INTELLIGENT',
  'TOO HARDWORKING',
  'TOO HONEST',
  'TOO PERFECT',
  'TOO CARING',
] as const;

export const GENERIC_ADJECTIVE_CONTRADICTIONS = [
  'SMART BUT FUN',
  'SERIOUS BUT PLAYFUL',
  'CONFIDENT BUT HUMBLE',
  'COOL BUT WARM',
  'EDGY BUT APPROACHABLE',
] as const;

export const INTELLIGENCE_DIMENSIONS = [
  'CONTRADICTION_DETECTION',
  'PATTERN_RECOGNITION',
  'CULTURAL_MEMORY',
  'SOCIAL_INTELLIGENCE',
  'EMOTIONAL_INTELLIGENCE',
  'ACADEMIC_KNOWLEDGE',
  'PRACTICAL_PROBLEM_SOLVING',
  'FINANCIAL_REASONING',
  'MEDIA_LITERACY',
  'VISUAL_INTELLIGENCE',
  'TECHNICAL_REASONING',
  'RELATIONSHIP_JUDGMENT',
  'SELF_AWARENESS',
  'SPATIAL_REASONING',
  'MEMORY',
  'RESEARCH_SKILL',
] as const;

export const HUMOR_MECHANISMS = [
  'THE_LOOK',
  'THE_PAUSE',
  'DEADPAN',
  'UNDERSTATEMENT',
  'OVERSTATEMENT',
  'CALLBACK',
  'SELF_DRAG',
  'PETTY_OBSERVATION',
  'ABSURD_COMPARISON',
  'VISUAL_JOKE',
  'SILENT_REACTION',
  'REWIND',
  'ZOOM',
  'CIRCLE_THE_RECEIPT',
  'WALK_AWAY',
  'TEXT_MESSAGE_REACTION',
  'ACCIDENTAL_COMEDY',
] as const;

export const RELATIONSHIP_CLASSES = [
  'BEST_FRIEND',
  'CLOSE_FRIEND',
  'GROUP_CHAT',
  'SIBLING',
  'PARENT',
  'EXTENDED_FAMILY',
  'ROMANTIC_INTEREST',
  'EX',
  'COWORKER',
  'ACQUAINTANCE',
  'RIVAL',
  'PERSON_SHE_ADMIRES',
  'PERSON_WHO_ANNOYS_HER',
] as const;

export const CULTURAL_KNOWLEDGE_LEVELS = [
  'LIVED_FLUENCY',
  'COMMUNITY_KNOWLEDGE',
  'OBSERVED_KNOWLEDGE',
  'RESEARCHED_KNOWLEDGE',
  'OUTSIDE_EXPERIENCE',
  'UNCERTAIN',
  'DO_NOT_PRETEND',
] as const;

export const VOICE_LAB_CHANNELS = [
  'INNER_THOUGHT',
  'SPOKEN_THOUGHT',
  'MARGIN',
  'TIKTOK',
  'BOOK_IN_MOTION',
  'PAGE',
  'CAPTION',
  'TEXT_TO_FRIEND',
] as const;

export const VISUAL_HYPOTHESIS_JUDGMENTS = [
  'YES',
  'NO',
  'MAYBE',
  'DEPENDS',
  'KEEP_EXPLORING',
  'MISREAD_MY_REFERENCE',
] as const;

export const STYLE_REASON_CATEGORIES = [
  'PERSONAL_TASTE',
  'COMFORT',
  'CULTURAL_REFERENCE',
  'FUNCTION',
  'HABIT',
  'STATUS',
  'SELF_EXPRESSION',
  'PROTECTION',
  'MOOD',
  'CAMERA_AWARENESS',
] as const;

export const FOUNDER_RECOGNITION_RESPONSES = [
  'YES_I_KNOW_HER',
  'ALMOST',
  'SHE_IS_STILL_TOO_CONCEPTUAL',
  'SHE_FEELS_LIKE_A_BRAND',
  'SHE_FEELS_TOO_PERFECT',
  'SHE_FEELS_TOO_MUCH_LIKE_ME',
  'SHE_FEELS_GENERIC',
  'SOMETHING_IS_MISSING',
] as const;

export const CASTING_READINESS_STATES_P05E4 = [
  'BLOCKED_FOUNDER_DISCOVERY_REQUIRED',
  'BLOCKED_HUMANITY_EVALUATION',
  'BLOCKED_FOUNDER_RECOGNITION',
  'READY_FOR_CHARACTER_SYNTHESIS',
  'READY_FOR_CHARACTER_CASTING_EXPLORATION',
] as const;

export const HUMANITY_FAILURE_STATES = [
  'FAIL_TOO_PERFECT',
  'FAIL_SECRETLY_FLATTERING_FLAWS',
  'FAIL_OMNISCIENT',
  'FAIL_GENERIC_COOL_GIRL',
  'FAIL_BRAND_MASCOT',
  'FAIL_FOUNDER_CLONE',
  'FAIL_INFLUENCER_COLLAPSE',
  'FAIL_NO_PRIVATE_LIFE',
  'FAIL_NO_RELATIONSHIPS',
  'FAIL_NO_REAL_CONTRADICTIONS',
  'FAIL_MARKETING_PERSONALITY',
  'FAIL_CULTURAL_OMNISCIENCE',
  'FAIL_PREDICTABLE_CHARACTER',
] as const;

/** Success criteria — P0.5E.4 sprint */
export const FOUNDER_CHARACTER_DISCOVERY_ROOM_IMPLEMENTED = true as const;
export const CHARACTER_DISCOVERY_DOMAINS_IMPLEMENTED = true as const;
export const SCENARIO_BASED_CHARACTER_DISCOVERY_IMPLEMENTED = true as const;
export const NONE_OF_THESE_SUPPORTED = true as const;
export const SOMETHING_ELSE_SUPPORTED = true as const;
export const IT_DEPENDS_SUPPORTED = true as const;
export const UNRESOLVED_CHARACTER_TRUTH_SUPPORTED = true as const;
export const FOUNDER_CHARACTER_JUDGMENT_IMPLEMENTED = true as const;
export const CHARACTER_CONTRADICTION_ENGINE_IMPLEMENTED = true as const;
export const NON_FLATTERING_FLAW_DISCOVERY_IMPLEMENTED = true as const;
export const UNEVEN_INTELLIGENCE_DISCOVERY_IMPLEMENTED = true as const;
export const CHARACTER_HUMOR_DISCOVERY_IMPLEMENTED = true as const;
export const PRIVATE_HUMANITY_DISCOVERY_IMPLEMENTED = true as const;
export const CHARACTER_RELATIONSHIP_DISCOVERY_IMPLEMENTED = true as const;
export const CULTURAL_KNOWLEDGE_BOUNDARY_IMPLEMENTED = true as const;
export const PUBLIC_PRIVATE_CHARACTER_DIFFERENCE_IMPLEMENTED = true as const;
export const CHARACTER_VOICE_LAB_IMPLEMENTED = true as const;
export const BOOK_RELATIONSHIP_DISCOVERY_IMPLEMENTED = true as const;
export const FOUNDER_VISUAL_HYPOTHESIS_REVIEW_IMPLEMENTED = true as const;
export const NORTH_STAR_IMAGES_REMAIN_NON_CANON = true as const;
export const STYLE_EMERGES_FROM_CHARACTER = true as const;
export const CHARACTER_DISCOVERY_LEDGER_IMPLEMENTED = true as const;
export const CHARACTER_TRUTH_CONFIDENCE_IMPLEMENTED = true as const;
export const EMBODIED_CHARACTER_HUMANITY_EVALUATION_EXTENDED = true as const;
export const TOO_PERFECT_CHARACTER_BLOCKED = true as const;
export const SECRETLY_FLATTERING_FLAWS_BLOCKED = true as const;
export const CULTURAL_OMNISCIENCE_BLOCKED = true as const;
export const GENERIC_COOL_GIRL_COLLAPSE_BLOCKED = true as const;
export const BRAND_MASCOT_COLLAPSE_BLOCKED = true as const;
export const FOUNDER_CLONE_COLLAPSE_BLOCKED = true as const;
export const INFLUENCER_COLLAPSE_BLOCKED = true as const;
export const CHARACTER_SYNTHESIS_PREVIEW_IMPLEMENTED = true as const;
export const FOUNDER_I_KNOW_HER_GATE_IMPLEMENTED = true as const;
export const FOUNDER_I_KNOW_HER_CONFIRMED = false as const;
export const READY_FOR_CHARACTER_SYNTHESIS = false as const;
export const READY_FOR_CHARACTER_CASTING_EXPLORATION = false as const;
export const FINAL_CHARACTER_FACE_SELECTED = false as const;
export const FINAL_CHARACTER_VISUAL_IDENTITY_FINALIZED = false as const;
export const FINAL_CHARACTER_GENERATION_PERFORMED = false as const;
export const FAL_REQUESTS = 0 as const;
export const CASTING_IMAGES_GENERATED = 0 as const;
export const STUDIO_WORLD_GENERIC_CHARACTER_DISCOVERY_IMPLEMENTED = true as const;
export const NDX_CHARACTER_DISCOVERY_ADAPTER_IMPLEMENTED = true as const;
export const BRAND_CHARACTER_MUTATED = false as const;
export const BRAND_CANON_MUTATED = false as const;
export const PRODUCT_EXPRESSION_IMPLEMENTED = false as const;
export const WORLD_FORMATION_IMPLEMENTED = false as const;
