import type { DigitalFoundationAddon, DigitalFoundationCommercialConfig } from './types.js';
import { defaultDigitalFoundationCommercialConfig } from './commercialConfig.js';

function addon(partial: DigitalFoundationAddon): DigitalFoundationAddon {
  return partial;
}

/** Configurable add-on catalog (V1 defaults). */
export function buildDefaultAddonCatalog(_config?: DigitalFoundationCommercialConfig): DigitalFoundationAddon[] {
  const currency = _config?.base_currency ?? defaultDigitalFoundationCommercialConfig().base_currency;
  return [
    addon({
      addon_id: 'ADDITIONAL_MAILBOX',
      label: 'Additional mailbox',
      client_description: 'Extra professional mailbox beyond the base package.',
      internal_description: 'Provision additional primary mailbox.',
      price_minor_units: 7_500,
      currency,
      workload_modifier: 1,
      timeline_modifier_business_days: 0,
      requires_manual_review: false,
      dependencies: [],
      active: true,
      display_order: 10,
      version: 1,
      quantity_unit: true,
    }),
    addon({
      addon_id: 'ADDITIONAL_DOMAIN',
      label: 'Additional domain',
      client_description: 'Register or connect an extra domain.',
      internal_description: 'Second domain registration or connection.',
      price_minor_units: 10_000,
      currency,
      workload_modifier: 1,
      timeline_modifier_business_days: 1,
      requires_manual_review: false,
      dependencies: [],
      active: true,
      display_order: 20,
      version: 1,
    }),
    addon({
      addon_id: 'DOMAIN_TRANSFER',
      label: 'Domain transfer',
      client_description: 'Transfer an existing domain into your controlled registrar account.',
      internal_description: 'Registrar transfer workflow.',
      price_minor_units: 10_000,
      currency,
      workload_modifier: 2,
      timeline_modifier_business_days: 2,
      requires_manual_review: false,
      dependencies: [],
      active: true,
      display_order: 30,
      version: 1,
    }),
    addon({
      addon_id: 'DOMAIN_RECOVERY',
      label: 'Domain recovery',
      client_description: 'Recover access when domain ownership or registrar access is unclear.',
      internal_description: 'May escalate to custom quote.',
      price_minor_units: 15_000,
      currency,
      workload_modifier: 4,
      timeline_modifier_business_days: 5,
      requires_manual_review: true,
      dependencies: [],
      active: true,
      display_order: 40,
      version: 1,
    }),
    addon({
      addon_id: 'LEGACY_EMAIL_MIGRATION',
      label: 'Legacy email migration',
      client_description: 'Migrate mail from a previous provider or personal inbox.',
      internal_description: 'Migration scope reviewed at intake.',
      price_minor_units: 20_000,
      currency,
      workload_modifier: 3,
      timeline_modifier_business_days: 2,
      requires_manual_review: true,
      dependencies: [],
      active: true,
      display_order: 50,
      version: 1,
    }),
    addon({
      addon_id: 'MULTI_USER_WORKSPACE_SETUP',
      label: 'Multi-user workspace setup',
      client_description: 'Configure workspace for multiple team members.',
      internal_description: 'Google/Microsoft multi-user baseline.',
      price_minor_units: 15_000,
      currency,
      workload_modifier: 2,
      timeline_modifier_business_days: 1,
      requires_manual_review: true,
      dependencies: [],
      active: true,
      display_order: 60,
      version: 1,
    }),
    addon({
      addon_id: 'ADVANCED_EMAIL_ROUTING',
      label: 'Advanced email routing',
      client_description: 'Routing rules, shared inboxes, or forwarders beyond base aliases.',
      internal_description: 'Advanced routing configuration.',
      price_minor_units: 10_000,
      currency,
      workload_modifier: 2,
      timeline_modifier_business_days: 1,
      requires_manual_review: false,
      dependencies: [],
      active: true,
      display_order: 70,
      version: 1,
    }),
    addon({
      addon_id: 'STAFF_SIGNATURE_SYSTEM',
      label: 'Staff signature system',
      client_description: 'Consistent signatures for multiple staff mailboxes.',
      internal_description: 'Template + rollout for team.',
      price_minor_units: 15_000,
      currency,
      workload_modifier: 2,
      timeline_modifier_business_days: 1,
      requires_manual_review: true,
      dependencies: ['MULTI_USER_WORKSPACE_SETUP'],
      active: true,
      display_order: 80,
      version: 1,
    }),
    addon({
      addon_id: 'ADDITIONAL_DEVICE_SETUP',
      label: 'Additional device setup',
      client_description: 'Guidance for an extra phone or computer beyond the first device.',
      internal_description: 'Per-device setup session.',
      price_minor_units: 5_000,
      currency,
      workload_modifier: 1,
      timeline_modifier_business_days: 0,
      requires_manual_review: false,
      dependencies: [],
      active: true,
      display_order: 90,
      version: 1,
      quantity_unit: true,
    }),
    addon({
      addon_id: 'ADVANCED_DNS_CLEANUP',
      label: 'Advanced DNS cleanup',
      client_description: 'Untangle conflicting DNS from prior hosts or email providers.',
      internal_description: 'DNS audit + remediation.',
      price_minor_units: 15_000,
      currency,
      workload_modifier: 3,
      timeline_modifier_business_days: 2,
      requires_manual_review: true,
      dependencies: [],
      active: true,
      display_order: 100,
      version: 1,
    }),
    addon({
      addon_id: 'EXISTING_SITE_DOMAIN_CONFLICT',
      label: 'Existing site / domain conflict',
      client_description: 'Your domain already points at a live site or conflicting service.',
      internal_description: 'Coordination with existing property.',
      price_minor_units: 15_000,
      currency,
      workload_modifier: 3,
      timeline_modifier_business_days: 2,
      requires_manual_review: true,
      dependencies: [],
      active: true,
      display_order: 110,
      version: 1,
    }),
    addon({
      addon_id: 'EXPEDITED_FOUNDATION',
      label: 'Expedited foundation',
      client_description: 'Priority scheduling when operations capacity allows.',
      internal_description: 'Founder-configured premium.',
      price_minor_units: 0,
      currency,
      workload_modifier: 1,
      timeline_modifier_business_days: -1,
      requires_manual_review: true,
      dependencies: [],
      active: true,
      display_order: 120,
      version: 1,
    }),
    addon({
      addon_id: 'CUSTOM_FOUNDATION_WORK',
      label: 'Custom foundation work',
      client_description: 'Scope outside the standard catalog — quoted after review.',
      internal_description: 'Manual quote line.',
      price_minor_units: 0,
      currency,
      workload_modifier: 5,
      timeline_modifier_business_days: 5,
      requires_manual_review: true,
      dependencies: [],
      active: true,
      display_order: 130,
      version: 1,
    }),
  ];
}

export function getActiveAddonCatalog(config?: DigitalFoundationCommercialConfig): DigitalFoundationAddon[] {
  return buildDefaultAddonCatalog(config).filter((a) => a.active).sort((a, b) => a.display_order - b.display_order);
}

export function findAddon(addonId: string, config?: DigitalFoundationCommercialConfig): DigitalFoundationAddon | undefined {
  return buildDefaultAddonCatalog(config).find((a) => a.addon_id === addonId);
}
