/**
 * P0.UI.2 — Complete NDXBOOK founder workspace route inventory.
 */

import { SITE00_ROUTES } from '../../../../src/site00/config/routes.js';
import type { MigrationStatus, NdxWorkspaceRouteEntry } from './types.js';

function entry(
  routeId: string,
  path: string,
  component: string,
  overrides: Partial<NdxWorkspaceRouteEntry> & Pick<NdxWorkspaceRouteEntry, 'migrationStatus'>,
): NdxWorkspaceRouteEntry {
  return {
    routeId,
    path,
    component,
    parentLayout: 'EcosystemShell',
    workspaceShell: 'EcosystemShell',
    visualGeneration: 'LEGACY_LORE_CALIBRATION',
    primarySurface: 'site00-project-lore-calibration',
    responsiveModel: 'LEGACY_DOCUMENT',
    projectAccentSource: 'MISSING',
    localNav: 'ProjectExperimentsHubNav',
    inspectSupport: false,
    loadingState: 'RAW_TEXT',
    emptyState: 'RAW_TEXT',
    errorState: 'RAW_TEXT',
    legacyDependencies: ['site00-project-lore-calibration', 'ProjectExperimentsHubNav'],
    isNested: path.split('/').length > 4,
    ...overrides,
  };
}

/** Canonical FWS routes — full workspace contract. */
const CANONICAL_ROUTES: NdxWorkspaceRouteEntry[] = [
  entry('content-operations', SITE00_ROUTES.projectContentOperations, 'ProjectContentOperationsPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'WORKSPACE_CANVAS',
    isTopLevel: true,
  }),
  entry('campaign-board', SITE00_ROUTES.projectContentOperationsCampaignBoard, 'ProjectContentOperationsCampaignBoardPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-campaign-wall',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'HORIZONTAL_LANE',
    isNested: true,
  }),
  entry('archive', SITE00_ROUTES.projectFounderWorkspaceArchive, 'ProjectFounderWorkspaceArchivePage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'WORKSPACE_CANVAS',
    isTopLevel: true,
  }),
  entry('overview', SITE00_ROUTES.projectDetail, 'ProjectDetailPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: false,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'WORKSPACE_CANVAS',
    isTopLevel: true,
  }),
  entry('daily-plan', SITE00_ROUTES.projectContentOperationsDailyPlan, 'ProjectContentOperationsDailyPlanPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'TAB_PANEL',
    isNested: true,
  }),
  entry('ci-sources', SITE00_ROUTES.projectCulturalIntelligenceSources, 'ProjectCulturalIntelligenceSourcesPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'WORKSPACE_CANVAS',
    isNested: true,
  }),
  entry('ci-weekly-forecast', SITE00_ROUTES.projectCulturalIntelligenceWeeklyForecast, 'ProjectCulturalIntelligenceWeeklyForecastPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'WORKSPACE_CANVAS',
    isNested: true,
  }),
  entry('character-continuity', SITE00_ROUTES.projectCharacterContinuity, 'ProjectCharacterContinuityPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'REVIEW_MODAL',
    isNested: true,
  }),
  entry('character-continuity-review', SITE00_ROUTES.projectCharacterContinuityReview, 'ProjectCharacterContinuityPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'REVIEW_MODAL',
    isNested: true,
  }),
  entry('motion-character', SITE00_ROUTES.projectMotionCharacter, 'ProjectMotionCharacterPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'WORKSPACE_CANVAS',
    isNested: true,
  }),
  entry('marketing-expression', SITE00_ROUTES.projectBrandMarketingExpression, 'ProjectBrandMarketingExpressionPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'WORKSPACE_CANVAS',
    isNested: true,
  }),
  entry('content-library', SITE00_ROUTES.projectContentLibrary, 'ProjectContentLibraryPage', {
    migrationStatus: 'CANONICAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-panel',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: [],
    scrollModel: 'BOARD',
    isNested: true,
  }),
];

/** Partial — FWS shell but legacy operate/inspect content remains. */
const PARTIAL_ROUTES: NdxWorkspaceRouteEntry[] = [
  entry('experiments-hub', SITE00_ROUTES.projectExperiments, 'ProjectExperimentsHubPage', {
    migrationStatus: 'PARTIAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: ['ProjectExperimentsHubNav'],
    scrollModel: 'WORKSPACE_CANVAS',
    isTopLevel: true,
  }),
  entry('cultural-intelligence', SITE00_ROUTES.projectCulturalIntelligence, 'ProjectCulturalIntelligencePage', {
    migrationStatus: 'PARTIAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: ['site00-project-lore-calibration'],
    scrollModel: 'WORKSPACE_CANVAS',
    isTopLevel: true,
  }),
  entry('performance', SITE00_ROUTES.projectContentOperationsPerformance, 'ProjectContentOperationsPerformancePage', {
    migrationStatus: 'PARTIAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: ['site00-project-lore-calibration'],
    scrollModel: 'WORKSPACE_CANVAS',
    isNested: true,
  }),
  entry('embodied-character', SITE00_ROUTES.projectEmbodiedCharacterDiscovery, 'ProjectEmbodiedCharacterDiscoveryPage', {
    migrationStatus: 'PARTIAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'FOUNDER_WORKSPACE_V1',
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'DESKTOP_RAIL_MOBILE_BOTTOM',
    projectAccentSource: 'NDX_LIME',
    localNav: 'WORKSPACE_RAIL',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: ['site00-experiment-g__panel'],
    scrollModel: 'WORKSPACE_CANVAS',
    isNested: true,
  }),
  entry('character-discovery', SITE00_ROUTES.projectFounderCharacterDiscovery, 'ProjectFounderCharacterDiscoveryPage', {
    migrationStatus: 'PARTIAL',
    workspaceShell: 'FounderWorkspaceShell',
    visualGeneration: 'MIXED' as NdxWorkspaceRouteEntry['visualGeneration'],
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'MIXED',
    projectAccentSource: 'NDX_LIME',
    localNav: 'DUPLICATE',
    inspectSupport: true,
    loadingState: 'WORKSPACE_NATIVE',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'WORKSPACE_NATIVE',
    legacyDependencies: ['site00-project-lore-calibration', 'ProjectExperimentsHubNav', 'site00-experiment-g__panel'],
    scrollModel: 'WORKSPACE_CANVAS',
    isTopLevel: true,
  }),
  entry('experiment-01', SITE00_ROUTES.projectBrandMarketingExpressionExperiment01, 'ProjectBrandMarketingExpressionExperiment01Page', {
    migrationStatus: 'PARTIAL',
    workspaceShell: 'CONDITIONAL',
    visualGeneration: 'MIXED' as NdxWorkspaceRouteEntry['visualGeneration'],
    primarySurface: 'site00-fws-canvas',
    responsiveModel: 'MIXED',
    projectAccentSource: 'NDX_LIME',
    localNav: 'DUPLICATE',
    inspectSupport: true,
    loadingState: 'RAW_TEXT',
    emptyState: 'WORKSPACE_NATIVE',
    errorState: 'RAW_TEXT',
    legacyDependencies: ['site00-project-lore-calibration', 'ProjectExperimentsHubNav'],
    scrollModel: 'BOARD',
    isNested: true,
  }),
  entry('personality-replay', SITE00_ROUTES.projectPersonalityReplay, 'ProjectPersonalityReplayPage', {
    migrationStatus: 'LEGACY',
    workspaceShell: 'EcosystemShell',
    visualGeneration: 'LEGACY_LORE_CALIBRATION',
    primarySurface: 'site00-project-lore-calibration',
    responsiveModel: 'LEGACY_DOCUMENT',
    projectAccentSource: 'MISSING',
    localNav: 'ProjectExperimentsHubNav',
    inspectSupport: false,
    loadingState: 'RAW_TEXT',
    emptyState: 'RAW_TEXT',
    errorState: 'RAW_TEXT',
    legacyDependencies: ['site00-project-lore-calibration', 'ProjectExperimentsHubNav'],
    scrollModel: 'NATIVE_DOCUMENT',
    isNested: true,
  }),
  entry('personality-replay-step', SITE00_ROUTES.projectPersonalityReplayStep, 'ProjectPersonalityReplayPage', {
    migrationStatus: 'LEGACY',
    workspaceShell: 'EcosystemShell',
    visualGeneration: 'LEGACY_LORE_CALIBRATION',
    primarySurface: 'site00-project-lore-calibration',
    responsiveModel: 'LEGACY_DOCUMENT',
    projectAccentSource: 'MISSING',
    localNav: 'ProjectExperimentsHubNav',
    inspectSupport: false,
    loadingState: 'RAW_TEXT',
    emptyState: 'RAW_TEXT',
    errorState: 'RAW_TEXT',
    legacyDependencies: ['site00-project-lore-calibration', 'ProjectExperimentsHubNav'],
    scrollModel: 'NATIVE_DOCUMENT',
    isNested: true,
  }),
];

/** Legacy experiment spine + setup routes — isolated for inspect/migration wrapper. */
const LEGACY_ROUTES: NdxWorkspaceRouteEntry[] = [
  entry('setup', SITE00_ROUTES.projectSetup, 'ProjectSetupPage', { migrationStatus: 'LEGACY', parentLayout: 'NONE', workspaceShell: 'NONE', localNav: 'NONE', legacyDependencies: ['site00-label-red'] }),
  entry('evolve', SITE00_ROUTES.projectEvolve, 'ProjectEvolvePage', { migrationStatus: 'LEGACY', visualGeneration: 'LEGACY_PROJECT_COMMAND', primarySurface: 'site00-projects', legacyDependencies: ['site00-projects', 'site00-label-red'] }),
  entry('creative-direction', SITE00_ROUTES.projectCreativeDirection, 'ProjectCreativeDirectionPage', { migrationStatus: 'LEGACY', localNav: 'NONE', legacyDependencies: [] }),
  entry('lore-calibration', SITE00_ROUTES.projectLoreCalibration, 'ProjectLoreCalibrationPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('creative-appetite', SITE00_ROUTES.projectCreativeAppetite, 'ProjectCreativeAppetitePage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('personality-replay-consistency', SITE00_ROUTES.projectPersonalityReplayConsistency, 'ProjectSixDirectionConsistencyPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('canonical-creative-range', SITE00_ROUTES.projectCanonicalCreativeRange, 'ProjectCanonicalCreativeRangePage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('canonical-carousel-expansion', SITE00_ROUTES.projectCanonicalCarouselExpansion, 'ProjectCanonicalCarouselExpansionPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('experiment-d', SITE00_ROUTES.projectExperimentD, 'ProjectExperimentDPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('experiment-f', SITE00_ROUTES.projectExperimentF, 'ProjectExperimentFPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('experiment-g', SITE00_ROUTES.projectExperimentG, 'ProjectExperimentGPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('experiment-g-directions', SITE00_ROUTES.projectExperimentGDirections, 'ProjectExperimentGDirectionsPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT', isNested: true }),
  entry('experiment-g-finalists', SITE00_ROUTES.projectExperimentGFinalists, 'ProjectExperimentGFinalistsPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT', isNested: true }),
  entry('experiment-h', SITE00_ROUTES.projectExperimentH, 'ProjectExperimentHPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('brand-character-development', SITE00_ROUTES.projectBrandCharacterDevelopment, 'ProjectExperimentHDevelopmentPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('brand-character-readiness', SITE00_ROUTES.projectBrandCharacterReadiness, 'ProjectBrandCharacterReadinessPage', { migrationStatus: 'LEGACY', legacyDependencies: ['site00-experiment-g__panel'] }),
  entry('brand-character-deepening', SITE00_ROUTES.projectBrandCharacterDeepening, 'ProjectBrandCharacterDeepeningPage', { migrationStatus: 'LEGACY', legacyDependencies: ['site00-experiment-g__panel', 'site00-label-red'] }),
  entry('brand-character-synthesis', SITE00_ROUTES.projectBrandCharacterSynthesis, 'ProjectBrandCharacterSynthesisPage', { migrationStatus: 'LEGACY', legacyDependencies: ['site00-experiment-g__panel'] }),
  entry('brand-character-artifact-proofs', SITE00_ROUTES.projectBrandCharacterArtifactProofs, 'ProjectBrandCharacterArtifactProofsPage', { migrationStatus: 'LEGACY', legacyDependencies: ['site00-experiment-g__panel'] }),
  entry('experience-expression', SITE00_ROUTES.projectExperimentE, 'ProjectExperimentEPage', { migrationStatus: 'LEGACY', scrollModel: 'NATIVE_DOCUMENT' }),
  entry('visual-development', SITE00_ROUTES.projectExperimentEVisualDevelopment, 'ProjectWorkspaceVisualDevelopmentPage', { migrationStatus: 'LEGACY', primarySurface: 'site00-vd', localNav: 'ProjectExperimentsHubNav', legacyDependencies: ['ProjectExperimentsHubNav'], scrollModel: 'BOARD' }),
];

export const NDX_WORKSPACE_ROUTE_INVENTORY: readonly NdxWorkspaceRouteEntry[] = [
  ...CANONICAL_ROUTES,
  ...PARTIAL_ROUTES,
  ...LEGACY_ROUTES,
];

export type NdxWorkspaceRouteInventory = typeof NDX_WORKSPACE_ROUTE_INVENTORY;

export function getRouteInventoryEntry(routeId: string): NdxWorkspaceRouteEntry | undefined {
  return NDX_WORKSPACE_ROUTE_INVENTORY.find((r) => r.routeId === routeId);
}

export function getRoutesByMigrationStatus(status: MigrationStatus): NdxWorkspaceRouteEntry[] {
  return NDX_WORKSPACE_ROUTE_INVENTORY.filter((r) => r.migrationStatus === status);
}

export function summarizeRouteInventory(): {
  total: number;
  topLevel: number;
  nested: number;
  canonical: number;
  partial: number;
  legacy: number;
  broken: number;
} {
  const all = NDX_WORKSPACE_ROUTE_INVENTORY;
  return {
    total: all.length,
    topLevel: all.filter((r) => r.isTopLevel).length,
    nested: all.filter((r) => r.isNested).length,
    canonical: all.filter((r) => r.migrationStatus === 'CANONICAL').length,
    partial: all.filter((r) => r.migrationStatus === 'PARTIAL').length,
    legacy: all.filter((r) => r.migrationStatus === 'LEGACY').length,
    broken: all.filter((r) => r.migrationStatus === 'BROKEN').length,
  };
}

export const ALL_MIGRATION_STATUSES: MigrationStatus[] = [
  'CANONICAL',
  'PARTIAL',
  'LEGACY',
  'BROKEN',
  'DUPLICATE_SHELL',
  'MISSING_WORKSPACE_WRAPPER',
  'INCONSISTENT_THEME',
  'INCONSISTENT_NAV',
  'INCONSISTENT_RESPONSIVE',
  'UNKNOWN',
];
