import type { EmailArchetype, EmailClassification, EmailDebugStatus, EmailFamily, EmailTemplateDefinition, EmailTemplateVars } from '../types.js';

function subject(text: string) {
  return (_v: EmailTemplateVars) => text;
}

function pre(text: string) {
  return (_v: EmailTemplateVars) => text;
}

function head(text: string | ((v: EmailTemplateVars) => string)) {
  return typeof text === 'string' ? (_v: EmailTemplateVars) => text : text;
}

function sub(text: string | ((v: EmailTemplateVars) => string)) {
  return typeof text === 'string' ? (_v: EmailTemplateVars) => text : text;
}

type Tpl = {
  num: number;
  id: string;
  name: string;
  family: EmailFamily;
  familyLabel: string;
  event: string;
  archetype: EmailArchetype;
  classification: EmailClassification;
  subject: (v: EmailTemplateVars) => string;
  preheader: (v: EmailTemplateVars) => string;
  headline: (v: EmailTemplateVars) => string;
  subheadline?: (v: EmailTemplateVars) => string;
  ctaLabel: string;
  debugStatus?: EmailDebugStatus;
  enabled?: boolean;
  notes?: string;
  defaultTheme?: 'light' | 'dark';
  varsForPreview?: Partial<EmailTemplateVars>;
};

function tpl(c: Tpl): EmailTemplateDefinition {
  return {
    ...c,
    debugStatus: c.debugStatus ?? 'needs-review',
    enabled: c.enabled ?? true,
  };
}

export const EMAIL_TEMPLATES: EmailTemplateDefinition[] = [
  // ACCESS / ACCOUNT
  tpl({
    num: 1,
    id: 'access-credential-issued',
    name: 'ACCESS CREDENTIAL ISSUED',
    family: 'access',
    familyLabel: 'ACCESS',
    event: 'ACCOUNT_CREATED',
    archetype: 'access-credential',
    classification: 'transactional',
    subject: subject('Your SITE 00 access has been issued.'),
    preheader: pre('Your digital credential into SITE 00 is ready.'),
    headline: head('SITE 00'),
    subheadline: sub('YOUR SITE 00 IDENTITY HAS BEEN RECOGNIZED.'),
    ctaLabel: 'ENTER SITE 00 →',
    defaultTheme: 'dark',
    varsForPreview: { accentScript: 'Welcome to', theme: 'dark', clientName: 'MEMBER', clientInitials: 'NK', memberId: '00-0147' },
  }),
  tpl({
    num: 2,
    id: 'verify-email',
    name: 'VERIFY EMAIL',
    family: 'access',
    familyLabel: 'ACCESS',
    event: 'EMAIL_VERIFICATION_REQUIRED',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Verify your SITE 00 access.'),
    preheader: pre('Confirm your email to continue.'),
    headline: head('VERIFY YOUR ACCESS.'),
    ctaLabel: 'VERIFY YOUR ACCESS →',
    notes: 'Supabase Auth may own this send — use simplified variant if provider-limited.',
  }),
  tpl({
    num: 3,
    id: 'sign-in-link',
    name: 'SIGN-IN LINK',
    family: 'access',
    familyLabel: 'ACCESS',
    event: 'MAGIC_LINK_REQUESTED',
    archetype: 'access-credential',
    classification: 'transactional',
    subject: subject('Your SITE 00 sign-in link.'),
    preheader: pre('Secure one-time access to SITE 00.'),
    headline: head('SITE 00'),
    subheadline: sub('YOUR SITE 00 IDENTITY HAS BEEN RECOGNIZED.'),
    ctaLabel: 'ENTER SITE 00 →',
    defaultTheme: 'dark',
    enabled: true,
    notes: 'Only send when magic-link auth is active.',
    varsForPreview: { accentScript: 'WELCOME TO', theme: 'dark' },
  }),
  tpl({
    num: 4,
    id: 'password-reset',
    name: 'PASSWORD RESET',
    family: 'access',
    familyLabel: 'ACCESS',
    event: 'PASSWORD_RESET_REQUESTED',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Reset your SITE 00 password.'),
    preheader: pre('Secure password reset request.'),
    headline: head('RESET PASSWORD.'),
    subheadline: sub('THIS LINK EXPIRES FOR YOUR SECURITY.'),
    ctaLabel: 'RESET PASSWORD →',
    notes: 'Supabase Auth template — strongest compatible SITE 00 variant.',
  }),
  tpl({
    num: 5,
    id: 'security-change-recorded',
    name: 'SECURITY CHANGE RECORDED',
    family: 'access',
    familyLabel: 'ACCESS',
    event: 'SECURITY_CHANGE_RECORDED',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('A security change was recorded on your account.'),
    preheader: pre('Account security update notification.'),
    headline: head('SECURITY CHANGE RECORDED.'),
    ctaLabel: 'REVIEW ACCOUNT →',
    enabled: false,
    notes: 'Enable when security change events are tracked.',
  }),
  tpl({
    num: 6,
    id: 'unusual-access',
    name: 'UNUSUAL ACCESS',
    family: 'access',
    familyLabel: 'ACCESS',
    event: 'UNUSUAL_ACCESS_DETECTED',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('New sign-in to your SITE 00 account.'),
    preheader: pre('Review recent account activity.'),
    headline: head('NEW SESSION RECORDED.'),
    ctaLabel: 'REVIEW SECURITY →',
    enabled: false,
    notes: 'Enable when session monitoring exists.',
  }),

  // IDENTITY
  tpl({
    num: 7,
    id: 'identity-path-received',
    name: 'IDENTITY PATH RECEIVED',
    family: 'identity',
    familyLabel: 'IDENTITY',
    event: 'IDENTITY_PATH_SELECTED',
    archetype: 'project-record',
    classification: 'operational',
    subject: (v) => `Identity signal received — ${v.buildClass ?? 'path selected'}.`,
    preheader: pre('Your identity path is recorded.'),
    headline: head('IDENTITY SIGNAL RECEIVED.'),
    subheadline: (v) => `PATH: ${(v.buildClass ?? 'STARTING AT ZERO').toUpperCase()}`,
    ctaLabel: 'CONTINUE IDENTITY →',
  }),
  tpl({
    num: 8,
    id: 'identity-input-saved',
    name: 'IDENTITY INPUT SAVED',
    family: 'identity',
    familyLabel: 'IDENTITY',
    event: 'IDENTITY_INPUT_SAVED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Your identity input has been saved.'),
    preheader: pre('Continue when you are ready.'),
    headline: head('INPUT SAVED.'),
    ctaLabel: 'CONTINUE IDENTITY →',
    enabled: false,
  }),
  tpl({
    num: 9,
    id: 'identity-calibration-complete',
    name: 'IDENTITY CALIBRATION COMPLETE',
    family: 'identity',
    familyLabel: 'IDENTITY',
    event: 'IDENTITY_COMPLETE',
    archetype: 'milestone-artifact',
    classification: 'operational',
    subject: subject('Identity input complete.'),
    preheader: pre('Your foundation has a signal.'),
    headline: head('IDENTITY INPUT COMPLETE.'),
    subheadline: sub('YOUR FOUNDATION HAS A SIGNAL.'),
    ctaLabel: 'VIEW NEXT STEP →',
  }),
  tpl({
    num: 10,
    id: 'identity-review-ready',
    name: 'IDENTITY REVIEW READY',
    family: 'identity',
    familyLabel: 'IDENTITY',
    event: 'IDENTITY_REVIEW_READY',
    archetype: 'review-dossier',
    classification: 'production',
    subject: subject('Your identity review is ready.'),
    preheader: pre('Review your identity deliverables.'),
    headline: head('IDENTITY REVIEW IS READY.'),
    ctaLabel: 'ENTER REVIEW →',
    enabled: false,
  }),
  tpl({
    num: 11,
    id: 'identity-foundation-locked',
    name: 'IDENTITY FOUNDATION LOCKED',
    family: 'identity',
    familyLabel: 'IDENTITY',
    event: 'IDENTITY_FOUNDATION_LOCKED',
    archetype: 'milestone-artifact',
    classification: 'production',
    subject: subject('Identity foundation locked.'),
    preheader: pre('Foundation recorded and locked.'),
    headline: head('IDENTITY FOUNDATION LOCKED.'),
    ctaLabel: 'VIEW PROJECT →',
  }),

  // BUILDER / PROJECT START
  tpl({
    num: 12,
    id: 'build-type-identified',
    name: 'BUILD CLASS IDENTIFIED',
    family: 'project',
    familyLabel: 'PROJECT',
    event: 'BUILD_TYPE_SELECTED',
    archetype: 'project-record',
    classification: 'operational',
    subject: (v) => `Build class identified — ${v.buildClass ?? 'SITE'}.`,
    preheader: pre('Your build path is recorded.'),
    headline: head('BUILD CLASS IDENTIFIED.'),
    subheadline: (v) => (v.buildClass ?? 'SITE').toUpperCase(),
    ctaLabel: 'CONTINUE TO SCOPE →',
  }),
  tpl({
    num: 13,
    id: 'project-initialized',
    name: 'PROJECT INITIATED',
    family: 'project',
    familyLabel: 'PROJECT',
    event: 'PROJECT_CREATED',
    archetype: 'project-record',
    classification: 'transactional',
    subject: (v) => `Project ${v.projectId ?? '00-0000'} is active.`,
    preheader: pre('Your project record has been created.'),
    headline: head('PROJECT INITIATED.'),
    subheadline: (v) => `PROJECT ${v.projectId ?? '00-0000'}`,
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 14,
    id: 'project-scope-ready',
    name: 'PROJECT SCOPE READY',
    family: 'project',
    familyLabel: 'PROJECT',
    event: 'SCOPE_READY',
    archetype: 'project-record',
    classification: 'operational',
    subject: subject('Your scope is ready.'),
    preheader: pre('Review your project scope.'),
    headline: head('YOUR SCOPE IS READY.'),
    ctaLabel: 'REVIEW SCOPE →',
  }),
  tpl({
    num: 15,
    id: 'scope-approved',
    name: 'SCOPE APPROVED',
    family: 'project',
    familyLabel: 'PROJECT',
    event: 'SCOPE_APPROVED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Scope approved.'),
    preheader: pre('Project scope has been accepted.'),
    headline: head('SCOPE APPROVED.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 16,
    id: 'payment-authorization-ready',
    name: 'PRODUCTION AWAITS AUTHORIZATION',
    family: 'project',
    familyLabel: 'PROJECT',
    event: 'PAYMENT_REQUIRED',
    archetype: 'action-required',
    classification: 'transactional',
    subject: subject('Production awaits authorization.'),
    preheader: pre('Authorize your project to begin production.'),
    headline: head('PRODUCTION AWAITS AUTHORIZATION.'),
    ctaLabel: 'AUTHORIZE PROJECT →',
  }),
  tpl({
    num: 17,
    id: 'payment-initiated',
    name: 'STUDIO ACCESS PENDING',
    family: 'project',
    familyLabel: 'STUDIO',
    event: 'PAYMENT_INITIATED',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Studio access pending.'),
    preheader: pre('Payment is being processed.'),
    headline: head('STUDIO ACCESS PENDING.'),
    subheadline: sub('CONFIRMATION FOLLOWS WHEN PAYMENT CLEARS.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 18,
    id: 'payment-confirmed-studio-access',
    name: 'STUDIO ACCESS GRANTED',
    family: 'studio',
    familyLabel: 'STUDIO',
    event: 'PAYMENT_CONFIRMED',
    archetype: 'studio-portal',
    classification: 'transactional',
    subject: subject('Studio access granted.'),
    preheader: pre('Payment confirmed. Your project has entered the production environment.'),
    headline: head('STUDIO ACCESS GRANTED.'),
    subheadline: sub('PAYMENT CONFIRMED. YOUR PROJECT HAS ENTERED THE PRODUCTION ENVIRONMENT.'),
    ctaLabel: 'ENTER STUDIO →',
    defaultTheme: 'dark',
    varsForPreview: { theme: 'dark', ctaUrl: 'https://site00.com/studio/preview-project' },
  }),

  // STUDIO / PRODUCTION
  tpl({
    num: 19,
    id: 'studio-activated',
    name: 'STUDIO ACTIVATED',
    family: 'studio',
    familyLabel: 'STUDIO',
    event: 'STUDIO_ACTIVATED',
    archetype: 'studio-portal',
    classification: 'operational',
    subject: subject('Studio is active for your project.'),
    preheader: pre('Your production environment is online.'),
    headline: head('STUDIO ACTIVATED.'),
    ctaLabel: 'ENTER STUDIO →',
    defaultTheme: 'dark',
  }),
  tpl({
    num: 20,
    id: 'client-input-required',
    name: 'CLIENT INPUT REQUIRED',
    family: 'input',
    familyLabel: 'INPUT',
    event: 'CLIENT_INPUT_REQUIRED',
    archetype: 'action-required',
    classification: 'production',
    subject: (v) => `Production is waiting on ${v.requiredInputCount ?? 1} input${(v.requiredInputCount ?? 1) === 1 ? '' : 's'}.`,
    preheader: pre('Your input is needed to keep production moving.'),
    headline: head('PRODUCTION IS WAITING ON YOU.'),
    ctaLabel: 'OPEN INPUT →',
  }),
  tpl({
    num: 21,
    id: 'client-input-received',
    name: 'INPUT RECEIVED',
    family: 'input',
    familyLabel: 'INPUT',
    event: 'CLIENT_INPUT_RECEIVED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Input received.'),
    preheader: pre('SITE 00 is moving again.'),
    headline: head('INPUT RECEIVED.'),
    subheadline: sub('SITE 00 IS MOVING AGAIN.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 22,
    id: 'production-resumed',
    name: 'PRODUCTION RESUMED',
    family: 'studio',
    familyLabel: 'STUDIO',
    event: 'PRODUCTION_RESUMED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Production has resumed.'),
    preheader: pre('Blocker resolved — production continues.'),
    headline: head('PRODUCTION RESUMED.'),
    ctaLabel: 'ENTER STUDIO →',
  }),
  tpl({
    num: 23,
    id: 'production-paused',
    name: 'PRODUCTION PAUSED',
    family: 'studio',
    familyLabel: 'STUDIO',
    event: 'PRODUCTION_BLOCKED',
    archetype: 'action-required',
    classification: 'production',
    subject: subject('Production is paused.'),
    preheader: pre('One input is holding this operation.'),
    headline: head('PRODUCTION IS PAUSED.'),
    subheadline: sub('ONE INPUT IS HOLDING THIS OPERATION.'),
    ctaLabel: 'OPEN INPUT →',
  }),
  tpl({
    num: 24,
    id: 'production-stage-started',
    name: 'PRODUCTION STAGE STARTED',
    family: 'studio',
    familyLabel: 'STUDIO',
    event: 'STAGE_STARTED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: (v) => `${v.milestoneName ?? 'Production stage'} started.`,
    preheader: pre('A new production stage has begun.'),
    headline: (v) => `${(v.milestoneName ?? 'PRODUCTION STAGE').toUpperCase()} STARTED.`,
    ctaLabel: 'ENTER STUDIO →',
  }),
  tpl({
    num: 25,
    id: 'production-stage-completed',
    name: 'PRODUCTION STAGE COMPLETED',
    family: 'studio',
    familyLabel: 'STUDIO',
    event: 'STAGE_COMPLETED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: (v) => `${v.milestoneName ?? 'Production stage'} completed.`,
    preheader: pre('Stage complete — production continues.'),
    headline: (v) => `${(v.milestoneName ?? 'PRODUCTION STAGE').toUpperCase()} COMPLETE.`,
    ctaLabel: 'ENTER STUDIO →',
  }),

  // REVIEW
  tpl({
    num: 26,
    id: 'blueprint-directions-ready',
    name: 'BLUEPRINT DIRECTIONS READY',
    family: 'review',
    familyLabel: 'REVIEW',
    event: 'BLUEPRINT_REVIEW_READY',
    archetype: 'review-dossier',
    classification: 'production',
    subject: (v) => `${v.directionCount ?? 3} direction${(v.directionCount ?? 3) === 1 ? '' : 's'} ready for review.`,
    preheader: pre('Your blueprint review is ready.'),
    headline: (v) => `${v.directionCount ?? 3} DIRECTION${(v.directionCount ?? 3) === 1 ? '' : 'S'} HAVE ENTERED REVIEW.`,
    subheadline: (v) => (v.reviewName ?? 'BLUEPRINT / HOMEPAGE').toUpperCase(),
    ctaLabel: 'ENTER REVIEW →',
    defaultTheme: 'dark',
    varsForPreview: { theme: 'dark', directionCount: 3 },
  }),
  tpl({
    num: 27,
    id: 'review-ready',
    name: 'REVIEW READY',
    family: 'review',
    familyLabel: 'REVIEW',
    event: 'REVIEW_READY',
    archetype: 'review-dossier',
    classification: 'production',
    subject: subject('Your next review is ready.'),
    preheader: pre('A deliverable is ready for your review.'),
    headline: head('YOUR NEXT REVIEW IS READY.'),
    subheadline: (v) => (v.reviewName ?? 'REVIEW').toUpperCase(),
    ctaLabel: 'ENTER REVIEW →',
    defaultTheme: 'dark',
  }),
  tpl({
    num: 28,
    id: 'review-reminder',
    name: 'REVIEW REMINDER',
    family: 'review',
    familyLabel: 'REVIEW',
    event: 'REVIEW_REMINDER',
    archetype: 'action-required',
    classification: 'operational',
    subject: subject('Your review is still waiting.'),
    preheader: pre('Reminder — review pending.'),
    headline: head('REVIEW STILL PENDING.'),
    ctaLabel: 'ENTER REVIEW →',
    enabled: false,
    notes: 'Enable with meaningful delay cadence only.',
  }),
  tpl({
    num: 29,
    id: 'revision-received',
    name: 'REVISION RECEIVED',
    family: 'review',
    familyLabel: 'REVIEW',
    event: 'REVISION_RECEIVED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Revision received.'),
    preheader: pre('We are incorporating your feedback.'),
    headline: head('REVISION RECEIVED.'),
    subheadline: sub("WE'RE INCORPORATING YOUR FEEDBACK."),
    ctaLabel: 'VIEW REVIEW →',
  }),
  tpl({
    num: 30,
    id: 'revision-ready',
    name: 'REVISION READY',
    family: 'review',
    familyLabel: 'REVIEW',
    event: 'REVISION_READY',
    archetype: 'review-dossier',
    classification: 'production',
    subject: subject('Your revision is ready.'),
    preheader: pre('Updated deliverable ready for review.'),
    headline: head('YOUR REVISION IS READY.'),
    ctaLabel: 'ENTER REVIEW →',
  }),
  tpl({
    num: 31,
    id: 'approval-recorded',
    name: 'APPROVAL RECORDED',
    family: 'review',
    familyLabel: 'REVIEW',
    event: 'APPROVAL_RECEIVED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Approval recorded.'),
    preheader: pre('Your approval has been logged.'),
    headline: head('APPROVAL RECORDED.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 32,
    id: 'direction-locked',
    name: 'DIRECTION LOCKED',
    family: 'review',
    familyLabel: 'REVIEW',
    event: 'DIRECTION_LOCKED',
    archetype: 'milestone-artifact',
    classification: 'production',
    subject: (v) => `Direction ${v.directionLabel ?? 'B'} is locked.`,
    preheader: pre('System state transition recorded.'),
    headline: head('DIRECTION LOCKED.'),
    subheadline: (v) => `${(v.directionLabel ?? 'B').toUpperCase()} · NEXT: ASSET PRODUCTION`,
    ctaLabel: 'VIEW PROJECT →',
  }),

  // ASSETS
  tpl({
    num: 33,
    id: 'assets-required',
    name: 'ASSETS REQUIRED',
    family: 'assets',
    familyLabel: 'ASSETS',
    event: 'ASSETS_REQUIRED',
    archetype: 'action-required',
    classification: 'production',
    subject: subject('Assets required for your project.'),
    preheader: pre('Uploads needed to continue.'),
    headline: head('ASSETS REQUIRED.'),
    ctaLabel: 'OPEN INPUT →',
  }),
  tpl({
    num: 34,
    id: 'asset-vault-updated',
    name: 'VAULT UPDATED',
    family: 'assets',
    familyLabel: 'ASSETS',
    event: 'ASSET_VAULT_UPDATED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: (v) => `${v.requiredInputCount ?? 12} new assets in your vault.`,
    preheader: pre('Your asset vault has been updated.'),
    headline: head('VAULT UPDATED.'),
    subheadline: (v) => `${v.requiredInputCount ?? 12} NEW ASSETS HAVE ENTERED YOUR PROJECT.`,
    ctaLabel: 'VIEW VAULT →',
    varsForPreview: { requiredInputCount: 12 },
  }),
  tpl({
    num: 35,
    id: 'assets-ready-for-review',
    name: 'ASSET REVIEW OPEN',
    family: 'assets',
    familyLabel: 'ASSETS',
    event: 'ASSET_REVIEW_READY',
    archetype: 'review-dossier',
    classification: 'production',
    subject: subject('Asset review is open.'),
    preheader: pre('Review generated assets.'),
    headline: head('ASSET REVIEW OPEN.'),
    ctaLabel: 'ENTER REVIEW →',
  }),
  tpl({
    num: 36,
    id: 'asset-approval-recorded',
    name: 'ASSET APPROVAL RECORDED',
    family: 'assets',
    familyLabel: 'ASSETS',
    event: 'ASSET_APPROVED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Asset approval recorded.'),
    preheader: pre('Asset approved and logged.'),
    headline: head('ASSET APPROVAL RECORDED.'),
    ctaLabel: 'VIEW VAULT →',
  }),
  tpl({
    num: 37,
    id: 'asset-production-complete',
    name: 'ASSET PRODUCTION COMPLETE',
    family: 'assets',
    familyLabel: 'ASSETS',
    event: 'ASSET_PRODUCTION_COMPLETE',
    archetype: 'milestone-artifact',
    classification: 'production',
    subject: subject('Asset production complete.'),
    preheader: pre('Asset package stage complete.'),
    headline: head('ASSET PRODUCTION COMPLETE.'),
    ctaLabel: 'VIEW VAULT →',
  }),

  // MILESTONE
  tpl({
    num: 38,
    id: 'milestone-recorded',
    name: 'MILESTONE RECORDED',
    family: 'milestone',
    familyLabel: 'MILESTONE',
    event: 'MILESTONE_RECORDED',
    archetype: 'milestone-artifact',
    classification: 'production',
    subject: (v) => `Milestone recorded — ${v.milestoneName ?? 'progress'}.`,
    preheader: pre('An important production milestone was recorded.'),
    headline: head('MILESTONE RECORDED.'),
    subheadline: (v) => (v.milestoneName ?? 'PRODUCTION MILESTONE').toUpperCase(),
    ctaLabel: 'VIEW MILESTONES →',
  }),
  tpl({
    num: 39,
    id: 'major-progress',
    name: 'MAJOR PROGRESS',
    family: 'milestone',
    familyLabel: 'MILESTONE',
    event: 'MAJOR_PROGRESS',
    archetype: 'milestone-artifact',
    classification: 'operational',
    subject: subject('Major project progress recorded.'),
    preheader: pre('Significant production progress.'),
    headline: head('MAJOR PROGRESS RECORDED.'),
    ctaLabel: 'VIEW PROJECT →',
    enabled: false,
    notes: 'Only enable with meaningful real progress data.',
  }),

  // QA / LAUNCH
  tpl({
    num: 40,
    id: 'qa-started',
    name: 'FINAL SYSTEM CHECK',
    family: 'launch',
    familyLabel: 'QA',
    event: 'QA_STARTED',
    archetype: 'system-check',
    classification: 'production',
    subject: subject('Final system check has started.'),
    preheader: pre('QA phase underway.'),
    headline: head('FINAL SYSTEM CHECK.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 41,
    id: 'qa-client-input',
    name: 'QA INPUT REQUIRED',
    family: 'launch',
    familyLabel: 'QA',
    event: 'QA_CLIENT_INPUT_REQUIRED',
    archetype: 'action-required',
    classification: 'production',
    subject: subject('QA needs your input.'),
    preheader: pre('Client input required during QA.'),
    headline: head('QA NEEDS YOUR INPUT.'),
    ctaLabel: 'OPEN INPUT →',
    enabled: false,
  }),
  tpl({
    num: 42,
    id: 'qa-passed',
    name: 'FINAL SYSTEM CHECK PASSED',
    family: 'launch',
    familyLabel: 'QA',
    event: 'QA_PASSED',
    archetype: 'system-check',
    classification: 'production',
    subject: subject('Final system check passed.'),
    preheader: pre('Next: launch authorization.'),
    headline: head('FINAL SYSTEM CHECK PASSED.'),
    subheadline: sub('NEXT: LAUNCH AUTHORIZATION'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 43,
    id: 'launch-authorization-required',
    name: 'LAUNCH SEQUENCE READY',
    family: 'launch',
    familyLabel: 'LAUNCH',
    event: 'LAUNCH_AUTH_REQUIRED',
    archetype: 'launch-authorization',
    classification: 'production',
    subject: subject('Launch authorization is ready.'),
    preheader: pre('Your approval is required to launch.'),
    headline: head('LAUNCH SEQUENCE READY.'),
    subheadline: sub('YOUR APPROVAL IS REQUIRED.'),
    ctaLabel: 'AUTHORIZE LAUNCH →',
    defaultTheme: 'dark',
    varsForPreview: { theme: 'dark' },
  }),
  tpl({
    num: 44,
    id: 'launch-authorized',
    name: 'LAUNCH AUTHORIZED',
    family: 'launch',
    familyLabel: 'LAUNCH',
    event: 'LAUNCH_AUTHORIZED',
    archetype: 'status-notice',
    classification: 'production',
    subject: subject('Launch authorized.'),
    preheader: pre('Deployment queued.'),
    headline: head('LAUNCH AUTHORIZED.'),
    subheadline: sub('DEPLOYMENT QUEUED.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 45,
    id: 'deployment-started',
    name: 'DEPLOYMENT STARTED',
    family: 'launch',
    familyLabel: 'LAUNCH',
    event: 'DEPLOYMENT_STARTED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Deployment has started.'),
    preheader: pre('Your launch deployment is in progress.'),
    headline: head('DEPLOYMENT STARTED.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 46,
    id: 'location-live',
    name: 'LOCATION NOW LIVE',
    family: 'property',
    familyLabel: 'PROPERTY',
    event: 'LOCATION_LIVE',
    archetype: 'location-live',
    classification: 'transactional',
    subject: subject('Your location is now live.'),
    preheader: pre('Your site is published.'),
    headline: head('YOUR SITE IS NOW LIVE.'),
    subheadline: (v) => (v.liveUrl ?? 'YOUR PROPERTY').toUpperCase(),
    ctaLabel: 'VIEW LIVE SITE →',
    varsForPreview: { accentScript: 'Congratulations!', liveUrl: 'preview-project.site00.com' },
  }),
  tpl({
    num: 47,
    id: 'launch-failed',
    name: 'LAUNCH ACTION REQUIRED',
    family: 'launch',
    familyLabel: 'LAUNCH',
    event: 'LAUNCH_ACTION_REQUIRED',
    archetype: 'action-required',
    classification: 'production',
    subject: subject('Launch needs your attention.'),
    preheader: pre('Action required to continue launch.'),
    headline: head('LAUNCH ACTION REQUIRED.'),
    ctaLabel: 'VIEW PROJECT →',
    enabled: false,
    notes: 'Client-facing only when client action is required.',
  }),

  // COMPLETION / POST-LAUNCH
  tpl({
    num: 48,
    id: 'production-complete',
    name: 'PRODUCTION RECORD CLOSED',
    family: 'property',
    familyLabel: 'PROPERTY',
    event: 'PRODUCTION_COMPLETE',
    archetype: 'production-complete',
    classification: 'transactional',
    subject: subject('Production record closed.'),
    preheader: pre('Your property is active.'),
    headline: head('PRODUCTION RECORD CLOSED.'),
    subheadline: sub('YOUR PROPERTY IS ACTIVE.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 49,
    id: 'final-deliverables-ready',
    name: 'FINAL DELIVERABLES READY',
    family: 'property',
    familyLabel: 'PROPERTY',
    event: 'FINAL_DELIVERABLES_READY',
    archetype: 'project-record',
    classification: 'operational',
    subject: subject('Final deliverables are ready.'),
    preheader: pre('Download and review final deliverables.'),
    headline: head('FINAL DELIVERABLES READY.'),
    ctaLabel: 'VIEW DELIVERABLES →',
    enabled: false,
  }),
  tpl({
    num: 50,
    id: 'studio-record-available',
    name: 'STUDIO RECORD AVAILABLE',
    family: 'studio',
    familyLabel: 'STUDIO',
    event: 'STUDIO_RECORD_AVAILABLE',
    archetype: 'studio-portal',
    classification: 'operational',
    subject: subject('Your production record remains open.'),
    preheader: pre('Milestones, approvals, assets, history.'),
    headline: head('YOUR PRODUCTION RECORD REMAINS OPEN.'),
    subheadline: sub('MILESTONES · APPROVALS · ASSETS · HISTORY'),
    ctaLabel: 'ENTER STUDIO →',
  }),
  tpl({
    num: 51,
    id: 'post-launch-checkin',
    name: 'POST-LAUNCH CHECK-IN',
    family: 'property',
    familyLabel: 'PROPERTY',
    event: 'POST_LAUNCH_CHECKIN',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Checking in on your live property.'),
    preheader: pre('Post-launch follow-up.'),
    headline: head('POST-LAUNCH CHECK-IN.'),
    ctaLabel: 'VIEW LIVE SITE →',
    enabled: false,
  }),
  tpl({
    num: 52,
    id: 'evolve-invitation',
    name: 'EVOLVE INVITATION',
    family: 'property',
    familyLabel: 'PROPERTY',
    event: 'EVOLVE_INVITATION',
    archetype: 'project-record',
    classification: 'marketing',
    subject: subject('Your property can keep moving.'),
    preheader: pre('Explore Evolve optimization.'),
    headline: head('YOUR PROPERTY CAN KEEP MOVING.'),
    ctaLabel: 'EXPLORE EVOLVE →',
    enabled: false,
  }),

  // BILLING
  tpl({
    num: 53,
    id: 'payment-receipt',
    name: 'PAYMENT RECEIPT',
    family: 'billing',
    familyLabel: 'BILLING',
    event: 'PAYMENT_RECEIPT',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Payment confirmed.'),
    preheader: pre('SITE 00 payment acknowledgment.'),
    headline: head('PAYMENT CONFIRMED.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 54,
    id: 'payment-failed',
    name: 'PAYMENT NEEDS ATTENTION',
    family: 'billing',
    familyLabel: 'BILLING',
    event: 'PAYMENT_FAILED',
    archetype: 'action-required',
    classification: 'transactional',
    subject: subject('Payment needs attention.'),
    preheader: pre('Resolve payment to continue production.'),
    headline: head('PAYMENT NEEDS ATTENTION.'),
    ctaLabel: 'RESOLVE PAYMENT →',
  }),
  tpl({
    num: 55,
    id: 'upcoming-payment',
    name: 'UPCOMING PAYMENT',
    family: 'billing',
    familyLabel: 'BILLING',
    event: 'UPCOMING_PAYMENT',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Upcoming payment reminder.'),
    preheader: pre('Installment due soon.'),
    headline: head('UPCOMING PAYMENT.'),
    ctaLabel: 'VIEW BILLING →',
    enabled: false,
  }),
  tpl({
    num: 56,
    id: 'invoice-ready',
    name: 'INVOICE READY',
    family: 'billing',
    familyLabel: 'BILLING',
    event: 'INVOICE_READY',
    archetype: 'project-record',
    classification: 'transactional',
    subject: subject('Your invoice is ready.'),
    preheader: pre('Invoice available for review.'),
    headline: head('INVOICE READY.'),
    ctaLabel: 'VIEW INVOICE →',
    enabled: false,
  }),
  tpl({
    num: 57,
    id: 'refund-recorded',
    name: 'REFUND RECORDED',
    family: 'billing',
    familyLabel: 'BILLING',
    event: 'REFUND_RECORDED',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Refund recorded.'),
    preheader: pre('Credit or refund processed.'),
    headline: head('REFUND RECORDED.'),
    ctaLabel: 'VIEW BILLING →',
    enabled: false,
  }),

  // DOMAIN / SYSTEM
  tpl({
    num: 58,
    id: 'domain-connection-required',
    name: 'DOMAIN CONNECTION REQUIRED',
    family: 'domain',
    familyLabel: 'DOMAIN',
    event: 'DOMAIN_REQUIRED',
    archetype: 'action-required',
    classification: 'production',
    subject: subject('Your location needs an address.'),
    preheader: pre('Connect your domain to continue.'),
    headline: head('YOUR LOCATION NEEDS AN ADDRESS.'),
    ctaLabel: 'CONNECT DOMAIN →',
  }),
  tpl({
    num: 59,
    id: 'domain-connected',
    name: 'DOMAIN CONNECTED',
    family: 'domain',
    familyLabel: 'DOMAIN',
    event: 'DOMAIN_CONNECTED',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Domain connected.'),
    preheader: pre('Your domain is linked.'),
    headline: head('DOMAIN CONNECTED.'),
    ctaLabel: 'VIEW PROJECT →',
  }),
  tpl({
    num: 60,
    id: 'integration-action-required',
    name: 'INTEGRATION ACTION REQUIRED',
    family: 'domain',
    familyLabel: 'SYSTEM',
    event: 'INTEGRATION_ACTION_REQUIRED',
    archetype: 'action-required',
    classification: 'production',
    subject: subject('Integration action required.'),
    preheader: pre('A provider connection needs your attention.'),
    headline: head('INTEGRATION ACTION REQUIRED.'),
    ctaLabel: 'OPEN INPUT →',
    enabled: false,
  }),

  // SUPPORT
  tpl({
    num: 61,
    id: 'support-request-received',
    name: 'SUPPORT REQUEST RECEIVED',
    family: 'support',
    familyLabel: 'SUPPORT',
    event: 'SUPPORT_REQUEST_RECEIVED',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Support request received.'),
    preheader: pre('We received your message.'),
    headline: head('SUPPORT REQUEST RECEIVED.'),
    ctaLabel: 'VIEW SUPPORT →',
    enabled: false,
  }),
  tpl({
    num: 62,
    id: 'support-response-available',
    name: 'SUPPORT RESPONSE AVAILABLE',
    family: 'support',
    familyLabel: 'SUPPORT',
    event: 'SUPPORT_RESPONSE_AVAILABLE',
    archetype: 'status-notice',
    classification: 'transactional',
    subject: subject('Support response available.'),
    preheader: pre('A response is ready.'),
    headline: head('SUPPORT RESPONSE AVAILABLE.'),
    ctaLabel: 'VIEW RESPONSE →',
    enabled: false,
  }),
  tpl({
    num: 63,
    id: 'project-message',
    name: 'IMPORTANT PROJECT MESSAGE',
    family: 'support',
    familyLabel: 'SUPPORT',
    event: 'PROJECT_MESSAGE',
    archetype: 'status-notice',
    classification: 'operational',
    subject: subject('Important project message.'),
    preheader: pre('Message from your SITE 00 team.'),
    headline: head('IMPORTANT PROJECT MESSAGE.'),
    ctaLabel: 'VIEW MESSAGE →',
    enabled: false,
  }),

  // MARKETING / SIGNAL
  tpl({
    num: 64,
    id: 'site00-signal-newsletter',
    name: 'SITE 00 SIGNAL',
    family: 'signal',
    familyLabel: 'SIGNAL',
    event: 'NEWSLETTER',
    archetype: 'signal-editorial',
    classification: 'marketing',
    subject: subject('SITE 00 Signal — Issue 004'),
    preheader: pre('Intelligence from the SITE 00 operating environment.'),
    headline: head('SITE 00 SIGNAL'),
    ctaLabel: 'READ SIGNAL →',
  }),
  tpl({
    num: 65,
    id: 'case-study-spotlight',
    name: 'BUILD SPOTLIGHT',
    family: 'signal',
    familyLabel: 'SIGNAL',
    event: 'CASE_STUDY',
    archetype: 'signal-editorial',
    classification: 'marketing',
    subject: subject('Built inside SITE 00.'),
    preheader: pre('Featured build spotlight.'),
    headline: head('BUILT INSIDE SITE 00.'),
    ctaLabel: 'READ SPOTLIGHT →',
    varsForPreview: {
      signalModules: [{ num: '01', title: 'BUILD SPOTLIGHT', excerpt: 'A property built through the SITE 00 production environment.' }],
    },
  }),
  tpl({
    num: 66,
    id: 'system-update',
    name: 'SYSTEM UPDATE',
    family: 'signal',
    familyLabel: 'SIGNAL',
    event: 'SYSTEM_UPDATE',
    archetype: 'signal-editorial',
    classification: 'marketing',
    subject: subject('System update from SITE 00.'),
    preheader: pre('New capability and system improvements.'),
    headline: head('SYSTEM UPDATE.'),
    ctaLabel: 'READ UPDATE →',
  }),
  tpl({
    num: 67,
    id: 're-engagement',
    name: 'RETURN TO SITE 00',
    family: 'signal',
    familyLabel: 'SIGNAL',
    event: 'RE_ENGAGEMENT',
    archetype: 'project-record',
    classification: 'marketing',
    subject: subject('Your signal is still here.'),
    preheader: pre('Return to SITE 00.'),
    headline: head('YOUR SIGNAL IS STILL HERE.'),
    ctaLabel: 'ENTER SITE 00 →',
    enabled: false,
    notes: 'Requires marketing consent.',
  }),
  tpl({
    num: 68,
    id: 'abandoned-intake',
    name: 'YOUR BUILD IS WAITING',
    family: 'signal',
    familyLabel: 'SIGNAL',
    event: 'ABANDONED_INTAKE',
    archetype: 'project-record',
    classification: 'marketing',
    subject: subject('Your build is waiting.'),
    preheader: pre('Continue where you left off.'),
    headline: head('YOUR BUILD IS WAITING.'),
    ctaLabel: 'CONTINUE BUILD →',
    enabled: false,
    notes: 'Requires marketing consent.',
  }),

  // INTERNAL
  tpl({
    num: 69,
    id: 'internal-new-client',
    name: 'NEW CLIENT / ACCOUNT',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_ACCOUNT_CREATED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: subject('[INTERNAL] New client account created.'),
    preheader: pre('Operator notification.'),
    headline: head('NEW CLIENT ACCOUNT CREATED.'),
    ctaLabel: 'OPEN CONTROL →',
    varsForPreview: { ctaUrl: 'https://site00.com/admin/site00' },
  }),
  tpl({
    num: 70,
    id: 'internal-payment-confirmed',
    name: 'PAYMENT CONFIRMED / PROJECT READY',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_PAYMENT_CONFIRMED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: (v) => `[INTERNAL] Payment confirmed — ${v.projectName ?? 'project'}.`,
    preheader: pre('Project ready for production.'),
    headline: head('PAYMENT CONFIRMED — PROJECT READY.'),
    ctaLabel: 'OPEN MISSION CONTROL →',
  }),
  tpl({
    num: 71,
    id: 'internal-client-input',
    name: 'CLIENT INPUT RECEIVED',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_CLIENT_INPUT_RECEIVED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: (v) => `[INTERNAL] Client input received — ${v.projectName ?? 'project'}.`,
    preheader: pre('Production can resume.'),
    headline: head('CLIENT INPUT RECEIVED.'),
    ctaLabel: 'OPEN MISSION CONTROL →',
  }),
  tpl({
    num: 72,
    id: 'internal-review-submitted',
    name: 'CLIENT REVIEW SUBMITTED',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_CLIENT_REVIEW_SUBMITTED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: (v) => `[INTERNAL] Client review submitted — ${v.reviewName ?? 'review'}.`,
    preheader: pre('Client action on review.'),
    headline: head('CLIENT REVIEW SUBMITTED.'),
    ctaLabel: 'OPEN REVIEWS →',
  }),
  tpl({
    num: 73,
    id: 'internal-revision-requested',
    name: 'REVISION REQUESTED',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_REVISION_REQUESTED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: subject('[INTERNAL] Revision requested by client.'),
    preheader: pre('Operator action needed.'),
    headline: head('REVISION REQUESTED.'),
    ctaLabel: 'OPEN REVIEWS →',
  }),
  tpl({
    num: 74,
    id: 'internal-approval-received',
    name: 'CLIENT APPROVAL RECEIVED',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_CLIENT_APPROVAL',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: subject('[INTERNAL] Client approval received.'),
    preheader: pre('Advance production as permitted.'),
    headline: head('CLIENT APPROVAL RECEIVED.'),
    ctaLabel: 'OPEN MISSION CONTROL →',
  }),
  tpl({
    num: 75,
    id: 'internal-project-blocked',
    name: 'PROJECT BLOCKED',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_PROJECT_BLOCKED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: (v) => `[INTERNAL] Project blocked — ${v.projectName ?? 'project'}.`,
    preheader: pre('Blocker requires attention.'),
    headline: head('PROJECT BLOCKED.'),
    ctaLabel: 'OPEN MISSION CONTROL →',
  }),
  tpl({
    num: 76,
    id: 'internal-review-required',
    name: 'INTERNAL REVIEW REQUIRED',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_REVIEW_REQUIRED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: subject('[INTERNAL] Internal review required.'),
    preheader: pre('Output awaiting internal gate.'),
    headline: head('INTERNAL REVIEW REQUIRED.'),
    ctaLabel: 'OPEN REVIEWS →',
  }),
  tpl({
    num: 77,
    id: 'internal-automation-failed',
    name: 'FAILED AUTOMATION',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_AUTOMATION_FAILED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: subject('[INTERNAL] Automation failure — action required.'),
    preheader: pre('Failed job needs operator attention.'),
    headline: head('FAILED AUTOMATION / ACTION REQUIRED.'),
    ctaLabel: 'OPEN AUTOMATION →',
  }),
  tpl({
    num: 78,
    id: 'internal-launch-ready',
    name: 'LAUNCH READY',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_LAUNCH_READY',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: (v) => `[INTERNAL] Launch ready — ${v.projectName ?? 'project'}.`,
    preheader: pre('Launch prerequisites met.'),
    headline: head('LAUNCH READY.'),
    ctaLabel: 'OPEN LAUNCH QUEUE →',
  }),
  tpl({
    num: 79,
    id: 'internal-launch-completed',
    name: 'LAUNCH COMPLETED',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_LAUNCH_COMPLETED',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: (v) => `[INTERNAL] Launch completed — ${v.projectName ?? 'project'}.`,
    preheader: pre('Deployment completed.'),
    headline: head('LAUNCH COMPLETED.'),
    ctaLabel: 'OPEN MISSION CONTROL →',
  }),
  tpl({
    num: 80,
    id: 'internal-system-incident',
    name: 'SYSTEM INCIDENT',
    family: 'internal',
    familyLabel: 'INTERNAL',
    event: 'INTERNAL_SYSTEM_INCIDENT',
    archetype: 'internal-notice',
    classification: 'internal',
    subject: subject('[INTERNAL] System incident recorded.'),
    preheader: pre('Operator incident notification.'),
    headline: head('SYSTEM INCIDENT.'),
    ctaLabel: 'OPEN SYSTEMS →',
  }),
];

export function getTemplateById(id: string): EmailTemplateDefinition | undefined {
  return EMAIL_TEMPLATES.find((t) => t.id === id);
}

export const EMAIL_TEMPLATE_MAP = Object.fromEntries(EMAIL_TEMPLATES.map((t) => [t.id, t]));

export type EmailFamilyFilter = EmailFamily | 'all' | 'launch-qa';

export function filterTemplates(params: {
  family?: EmailFamilyFilter;
  status?: EmailDebugStatus | 'all';
  classification?: EmailClassification | 'all';
}): EmailTemplateDefinition[] {
  return EMAIL_TEMPLATES.filter((t) => {
    if (params.family && params.family !== 'all') {
      if (params.family === 'launch-qa') {
        if (t.family !== 'launch') return false;
      } else if (t.family !== params.family) {
        return false;
      }
    }
    if (params.status && params.status !== 'all' && t.debugStatus !== params.status) return false;
    if (params.classification && params.classification !== 'all' && t.classification !== params.classification) return false;
    return true;
  });
}

export function emailPackSummary(debugStatuses: Record<string, EmailDebugStatus>) {
  const total = EMAIL_TEMPLATES.length;
  const approved = EMAIL_TEMPLATES.filter((t) => (debugStatuses[t.id] ?? t.debugStatus) === 'approved').length;
  const needsReview = total - approved;
  const countFamily = (f: EmailFamily) => EMAIL_TEMPLATES.filter((t) => t.family === f).length;
  return {
    total,
    approved,
    needsReview,
    transactional: EMAIL_TEMPLATES.filter((t) => t.classification === 'transactional').length,
    production: EMAIL_TEMPLATES.filter((t) => t.classification === 'production' || t.classification === 'operational').length,
    marketing: EMAIL_TEMPLATES.filter((t) => t.classification === 'marketing').length,
    access: countFamily('access'),
    identity: countFamily('identity'),
    project: countFamily('project'),
    studio: countFamily('studio'),
    review: countFamily('review'),
    property: countFamily('property'),
    billing: countFamily('billing'),
    launch: countFamily('launch'),
    signal: countFamily('signal'),
  };
}
