export const P0_VR_TWIN_V30R8M3_LINEAGE = 'P0.VR.TWINV3.0R8M3' as const;
export const MOBILE_TWIN_IMPL_COMPILER_GENERATION_R8M3 = 'R8M3' as const;
export const MOBILE_TWIN_IMPLEMENTATION_VERSION_FORENSIC_INGESTION =
  'mobile-twin-impl-v8-forensic-ingestion' as const;
/** Bumps local twin implementation cache when ingestion compile ships. */
export const MOBILE_TWIN_IMPLEMENTATION_CLIENT_CACHE_EPOCH = 3 as const;

export const FORENSIC_CSS_PREFIX_FM3 = 'site00-twin-fm3' as const;

export const R8M2R5_CORRECTION_REQUIRED_REASON =
  'FORENSIC_BLUEPRINT_NOT_INGESTED_AS_IMPLEMENTATION_SPEC' as const;

export const FORENSIC_BLUEPRINT_MISSING = 'FORENSIC_BLUEPRINT_MISSING' as const;
export const FORENSIC_BLUEPRINT_INGESTION_FAILED = 'FORENSIC_BLUEPRINT_INGESTION_FAILED' as const;
export const FORENSIC_OBJECT_MAP_EXTRACTION_FAILED = 'FORENSIC_OBJECT_MAP_EXTRACTION_FAILED' as const;
export const FORENSIC_OBJECT_MAP_VALIDATION_FAILED = 'FORENSIC_OBJECT_MAP_VALIDATION_FAILED' as const;
export const FORENSIC_EVIDENCE_NOT_CONSUMED = 'FORENSIC_EVIDENCE_NOT_CONSUMED' as const;
export const FORENSIC_RECONSTRUCTION_GENERIC_FALLBACK = 'FORENSIC_RECONSTRUCTION_GENERIC_FALLBACK' as const;
export const FORENSIC_RECONSTRUCTION_NO_MATERIAL_IMPROVEMENT = 'FORENSIC_RECONSTRUCTION_NO_MATERIAL_IMPROVEMENT' as const;

export const MAX_UNRESOLVED_CRITICAL_OBJECTS = 3 as const;
