/**
 * P0.EXPERIENCE.MODULE-WIRING1 — software / tool stack registry (honest connection states).
 */

import type { ExperienceTool } from './types.js';

function tool(partial: ExperienceTool): ExperienceTool {
  return partial;
}

/** Never mark CONNECTED unless verified — all fixtures start NOT_CONFIGURED / UNKNOWN. */
export const EXPERIENCE_TOOL_REGISTRY: readonly ExperienceTool[] = [
  tool({
    toolId: 'astra',
    name: 'Astra',
    category: 'AI / ORCHESTRATION',
    vendor: 'SITE 00',
    integrationType: 'AGENT',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['experience direction', 'scene reasoning', 'build vs target review'],
    supportedAssetTypes: ['REFERENCE', 'BUILD_CAPTURE'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: 'Requires explicit founder action to invoke.',
  }),
  tool({
    toolId: 'codex',
    name: 'Codex',
    category: 'AI / ORCHESTRATION',
    vendor: 'SITE 00',
    integrationType: 'AGENT',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['Maya Python', 'Blender Python', 'Unreal automation', 'validators'],
    supportedAssetTypes: ['MESH', 'ANIMATION', 'MATERIAL'],
    supportsAutomation: true,
    supportsCli: false,
    supportsPython: true,
    supportsPlugin: false,
    notes: 'Automation gated by ExperienceTask approval.',
  }),
  tool({
    toolId: 'maya',
    name: 'Autodesk Maya',
    category: 'DCC / MODELING',
    vendor: 'Autodesk',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: [
      'modeling',
      'rigging',
      'animation',
      'UV',
      'Python',
      'XGen',
      'Arnold integration',
      'FBX export',
      'USD export',
      'Alembic export',
    ],
    supportedAssetTypes: ['MESH', 'SKELETAL_MESH', 'GROOM', 'ANIMATION'],
    supportsAutomation: true,
    supportsCli: false,
    supportsPython: true,
    supportsPlugin: true,
    notes: 'XGen represented as Maya-integrated groom.',
  }),
  tool({
    toolId: 'blender',
    name: 'Blender',
    category: 'DCC / MODELING',
    vendor: 'Blender Foundation',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['modeling', 'procedural', 'scripting', 'geometry nodes', 'baking', 'FBX', 'USD', 'Alembic'],
    supportedAssetTypes: ['MESH', 'PROP', 'ENVIRONMENT'],
    supportsAutomation: true,
    supportsCli: true,
    supportsPython: true,
    supportsPlugin: true,
    notes: '',
  }),
  tool({
    toolId: 'zbrush',
    name: 'ZBrush',
    category: 'DCC / MODELING',
    vendor: 'Maxon',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['sculpting', 'high-detail mesh'],
    supportedAssetTypes: ['MESH'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'xgen',
    name: 'XGen',
    category: 'GROOM / HAIR',
    vendor: 'Autodesk',
    integrationType: 'MAYA_PLUGIN',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['groom authoring', 'hair curves'],
    supportedAssetTypes: ['GROOM', 'HAIR_CARD'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: true,
    supportsPlugin: true,
    notes: 'Maya-integrated; not a standalone app.',
  }),
  tool({
    toolId: 'photoshop',
    name: 'Adobe Photoshop',
    category: 'TEXTURE / MATERIAL',
    vendor: 'Adobe',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['texture editing', 'masks', 'alpha creation', 'decal prep', 'compositing'],
    supportedAssetTypes: ['TEXTURE', 'DECAL', 'REFERENCE'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: true,
    notes: '',
  }),
  tool({
    toolId: 'substance_painter',
    name: 'Substance 3D Painter',
    category: 'TEXTURE / MATERIAL',
    vendor: 'Adobe',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['texture painting', 'PBR material creation', 'baking support'],
    supportedAssetTypes: ['MATERIAL', 'TEXTURE'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'substance_designer',
    name: 'Substance 3D Designer',
    category: 'TEXTURE / MATERIAL',
    vendor: 'Adobe',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['procedural materials', 'material graph authoring'],
    supportedAssetTypes: ['MATERIAL'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'marvelous_designer',
    name: 'Marvelous Designer',
    category: 'CLOTHING',
    vendor: 'CLO Virtual Fashion',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['garment creation', 'cloth simulation'],
    supportedAssetTypes: ['MESH', 'PROP'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'rizomuv',
    name: 'RizomUV',
    category: 'UV / TOPOLOGY',
    vendor: 'Rizom Lab',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['UV unwrap', 'UV packing'],
    supportedAssetTypes: ['MESH'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'wrap4d',
    name: 'Wrap / Wrap4D',
    category: 'UV / TOPOLOGY',
    vendor: 'R3DS',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['topology transfer', 'scan wrapping', 'head/face transfer'],
    supportedAssetTypes: ['MESH', 'SKELETAL_MESH'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'houdini',
    name: 'Houdini',
    category: 'PROCEDURAL / WORLD',
    vendor: 'SideFX',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['procedural geometry', 'terrain', 'VFX', 'scattering', 'environment generation'],
    supportedAssetTypes: ['ENVIRONMENT', 'PROP', 'MESH'],
    supportsAutomation: true,
    supportsCli: true,
    supportsPython: true,
    supportsPlugin: true,
    notes: '',
  } as ExperienceTool),
  tool({
    toolId: 'speedtree',
    name: 'SpeedTree',
    category: 'PROCEDURAL / WORLD',
    vendor: 'Unity',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['foliage', 'procedural vegetation'],
    supportedAssetTypes: ['ENVIRONMENT', 'PROP'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'unreal',
    name: 'Unreal Engine',
    category: 'REALTIME / RUNTIME',
    vendor: 'Epic Games',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: [
      'realtime runtime',
      'Blueprint',
      'C++',
      'materials',
      'Niagara',
      'PCG',
      'animation',
      'groom',
      'packaging',
    ],
    supportedAssetTypes: ['BUILD_CAPTURE', 'ENVIRONMENT', 'SKELETAL_MESH', 'MATERIAL'],
    supportsAutomation: true,
    supportsCli: true,
    supportsPython: false,
    supportsPlugin: true,
    notes: 'Open runtime actions are blocked until configured.',
  }),
  tool({
    toolId: 'arnold',
    name: 'Arnold',
    category: 'RENDER / LOOKDEV / VALIDATION',
    vendor: 'Autodesk',
    integrationType: 'RENDERER',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['offline rendering', 'physically based lookdev', 'render validation'],
    supportedAssetTypes: ['REFERENCE', 'BUILD_CAPTURE'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: true,
    notes: 'Often integrated into Maya.',
  }),
  tool({
    toolId: 'marmoset',
    name: 'Marmoset Toolbag',
    category: 'RENDER / LOOKDEV / VALIDATION',
    vendor: 'Marmoset',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['baking', 'lookdev', 'asset validation', 'presentation'],
    supportedAssetTypes: ['REFERENCE', 'BUILD_CAPTURE', 'MATERIAL'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'mari',
    name: 'Mari',
    category: 'TEXTURE / MATERIAL',
    vendor: 'Foundry',
    integrationType: 'DESKTOP',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['high-resolution texture painting'],
    supportedAssetTypes: ['TEXTURE'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: '',
  }),
  tool({
    toolId: 'fab',
    name: 'Fab',
    category: 'ASSET LIBRARY / SOURCE',
    vendor: 'Epic Games',
    integrationType: 'LIBRARY',
    installationState: 'UNKNOWN',
    connectionState: 'NOT_CONFIGURED',
    executablePath: null,
    version: null,
    capabilities: ['asset discovery', 'asset acquisition', 'Megascans library'],
    supportedAssetTypes: ['ENVIRONMENT', 'PROP', 'MATERIAL', 'REFERENCE'],
    supportsAutomation: false,
    supportsCli: false,
    supportsPython: false,
    supportsPlugin: false,
    notes: 'Megascans modeled under Fab sourcing.',
  }),
];

export function getExperienceTool(toolId: string): ExperienceTool | null {
  return EXPERIENCE_TOOL_REGISTRY.find((t) => t.toolId === toolId) ?? null;
}

export function assertNoUnverifiedConnectedTools(): boolean {
  return !EXPERIENCE_TOOL_REGISTRY.some((t) => t.connectionState === 'CONNECTED');
}
