/**
 * AIO business formation, road-readiness and compliance services (F03 · F04 · F06 permits-taxes-compliance ·
 * safety-drivers). Each contract is grounded in serviceCatalog.ts ids, ROAD_READY_SYSTEM.md, RENEWAL_SYSTEM.md and
 * SERVICE_ACTIVATION_MATRIX (activation states quoted verbatim). AIO is a service-assistance office — never a
 * government system, law firm or registered agent unless the catalog / activation matrix says so.
 */
import type { ExperienceContract } from '../../schema.js';
import { aioFeature, ih } from './kit.js';

const RR_DISCLAIMER = 'Road Ready is business organisation and service assistance — not legal advice and not a government system.';

export const AIO_BUSINESS_FORMATION = aioFeature({
  id: 'AIO.BUSINESS_FORMATION',
  name: 'Start Your Business — LLC / INC / EIN',
  family: 'F03 START YOUR BUSINESS',
  purpose: 'Form the carrier’s business entity (LLC or corporation) and get its EIN so every later registration has a legal owner.',
  promise: 'AIO prepares and coordinates formation and EIN so your trucking business exists properly before the first authority filing.',
  value: 'One guided intake instead of separate state and IRS processes; formation documents land in the Vault and unlock USDOT.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['State filing office (external)', 'IRS (EIN, external)'],
  entries: {
    public: ['Start Your Business service pages', 'start-your-business/*', 'Get Started intake / homepage pathway “Start my trucking business”'],
    client: ['Start Your Business journey in My Business', 'portal/business (journey) · portal/requests', 'Get Started roadmap item or service request'],
    staff: ['Office formation queue', 'office/* formation division', 'service request submitted (business-formation workflow)'],
    system: ['Service request engine', 'formation request submitted'],
  },
  states: [
    ['NOT_STARTED', 'Not started', 'EMPTY', 'Start your business', 'No formation request', { CLIENT: 'START MY BUSINESS', PUBLIC: 'START INTAKE' }],
    ['INTAKE', 'Intake', 'ACTIVE', 'Tell AIO about your business', 'Intake in progress'],
    ['NAME_CHECK', 'Name check', 'ACTIVE', 'Checking your business name', 'Name availability check'],
    ['WAITING_ON_YOU', 'Waiting on you', 'BLOCKED', 'AIO needs a detail or signature', 'Waiting on customer'],
    ['AIO_PREPARING', 'AIO preparing', 'REVIEW', 'AIO is preparing your filing', 'Preparing filing'],
    ['FILED_WITH_STATE', 'Filed with state', 'REVIEW', 'Filed — waiting on the state', 'Waiting externally'],
    ['FORMED', 'Formed', 'COMPLETE', 'Your business is formed', 'Complete — documents issued'],
    ['EIN_ISSUED', 'EIN issued', 'ARCHIVED', 'EIN received — next: USDOT', 'Closed; USDOT unlocked'],
    ['REJECTED', 'Needs correction', 'ERROR', 'The state returned the filing — AIO is correcting it', 'Rejected by state'],
  ],
  transitions: [
    ['NOT_STARTED', 'INTAKE', 'client starts intake', 'CLIENT'],
    ['INTAKE', 'NAME_CHECK', 'intake submitted', 'CLIENT'],
    ['NAME_CHECK', 'WAITING_ON_YOU', 'name unavailable / detail missing', 'FOUNDER_STAFF'],
    ['WAITING_ON_YOU', 'NAME_CHECK', 'client answers', 'CLIENT'],
    ['NAME_CHECK', 'AIO_PREPARING', 'name clear + details complete', 'FOUNDER_STAFF'],
    ['AIO_PREPARING', 'FILED_WITH_STATE', 'AIO files', 'FOUNDER_STAFF'],
    ['FILED_WITH_STATE', 'FORMED', 'state approval recorded', 'FOUNDER_STAFF'],
    ['FILED_WITH_STATE', 'REJECTED', 'state rejects', 'FOUNDER_STAFF'],
    ['REJECTED', 'AIO_PREPARING', 'correction prepared', 'FOUNDER_STAFF'],
    ['FORMED', 'EIN_ISSUED', 'EIN recorded', 'FOUNDER_STAFF'],
  ],
  anchors: { start: 'INTAKE', success: 'FORMED', blocked: 'WAITING_ON_YOU', errors: ['REJECTED'], empty: 'NOT_STARTED', complete: 'EIN_ISSUED' },
  inputs: [
    ['ENTITY_CHOICE', 'Entity type (LLC / corporation)', ['GUIDED CHOICE', 'ASK AIO'], 'what is formed'],
    ['BUSINESS_NAME', 'Business name + alternates', ['ENTER'], 'state filing'],
    ['OWNERS', 'Owners / members + addresses', ['ENTER'], 'formation + EIN'],
    ['ID_DOCS', 'Owner ID', ['TAKE PHOTO', 'UPLOAD FILES'], 'identity verification'],
  ],
  derivations: [['FORMATION_PATH', 'filing checklist for the state', ['ENTITY_CHOICE', 'state'], 'workflow template business-formation'], ['NEXT_UNLOCK', 'USDOT readiness', ['FORMED', 'EIN'], 'journey dependency formation → USDOT']],
  reviews: [['NAME_REVIEW', 'NAME_CHECK', 'Is the name usable?', ['CLEAR', 'ASK CLIENT FOR ALTERNATE']], ['FILING_REVIEW', 'AIO_PREPARING', 'Is the filing complete?', ['FILE', 'REQUEST DETAIL']]],
  approvals: [['APPROVE_FILING_DETAILS', 'AIO_PREPARING', 'Confirm the details AIO will file', ['CONFIRM', 'EDIT']]],
  overrides: [['MANUAL_COMPLETE', 'FILED_WITH_STATE', 'Mark formed from external evidence', ['MARK FORMED WITH DOCUMENT']]],
  artifacts: [['ARTICLES', 'Articles of organization / incorporation', 'DOCUMENT', 'state approval', 'VAULT › Business & Formation'], ['EIN_LETTER', 'EIN confirmation', 'DOCUMENT', 'IRS confirmation', 'VAULT › Business & Formation'], ['OPERATING_AGREEMENT', 'Operating agreement / bylaws (if prepared)', 'DOCUMENT', 'AIO template', 'VAULT › Business & Formation']],
  vault: 'VAULT › Business & Formation',
  inbox: [['WAITING_ON_YOU', 'AIO needs a detail to form your business'], ['FORMED', 'Your business is formed — documents in your Vault']],
  activity: [['INTAKE', 'Formation intake submitted'], ['FORMED', 'Business formed'], ['EIN_ISSUED', 'EIN issued']],
  notify: [['FORMED', 'Your business is formed'], ['EIN_ISSUED', 'Your EIN is ready — next step: USDOT']],
  tasks: [['NAME_CHECK', 'Check name availability for {client}'], ['AIO_PREPARING', 'Prepare and file formation for {client}']],
  next: 'USDOT registration unlocks (journey dependency formation → USDOT); Road Ready shows the entity as complete.',
  upstream: ['AIO.GET_STARTED (intake / roadmap)'],
  downstream: ['AIO.AUTHORITIES (USDOT / MC)', 'AIO.ROAD_READY', 'AIO.VAULT', 'AIO.BOOKKEEPING (entity for books)'],
  relationships: [
    ['AIO.AUTHORITIES', 'EIN_ISSUED', 'UNLOCKS', 'USDOT step becomes READY in the journey', 'USDOT work item can start', { JOURNEY: 'USDOT item READY' }, 'next journey stop lights up'],
    ['AIO.VAULT', 'FORMED', 'ARCHIVES_TO', 'formation documents appear in Vault', 'documents verified', { VAULT: 'Business & Formation documents' }, 'formation card seals and files'],
    ['AIO.ROAD_READY', 'FORMED', 'UPDATES_STATUS', 'Road Ready entity item complete', 'profile updated', { ROAD_READY: 'entity requirement verified' }, 'checklist line completes'],
  ],
  public: {
    discovery: ['homepage pathway “Start my trucking business”', 'services › Start My Business', 'Get Started roadmap'],
    must_understand: ['which entity fits (LLC vs corporation) at a plain-language level', 'formation comes before USDOT / MC', 'AIO prepares and coordinates; the state approves'],
    who_its_for: 'New owner-operators and fleets that have not formed a business yet.',
    what_we_handle: ['name check', 'formation filing preparation + submission', 'EIN assistance', 'storing the documents'],
    what_client_provides: ['owner details', 'business name ideas', 'ID'],
    how_it_works: ['Intake', 'Name check', 'AIO prepares + you confirm', 'AIO files', 'State approves', 'EIN issued'],
    outcome: 'A formed entity with articles + EIN in your Vault and USDOT ready to start.',
    timing: 'Depends on state processing time.',
    pricing_relationship: 'Service fee per catalog (quote / fixed by service); state fees separate.',
    cta: 'Start My Business',
    workspace_continuity: 'The same journey route (formation → USDOT → authority) the public page shows is the client’s journey timeline.',
  },
  client: {
    entry_point: 'Start Your Business journey card (My Business) or Get Started roadmap item',
    primary_task: 'Give AIO what it needs to form the business and confirm the details.',
    sees_first: 'The journey route with Formation as the current stop and what AIO needs now.',
    must_provide: ['entity choice', 'name + alternates', 'owners', 'ID'],
    input_methods: ['GUIDED QUESTIONS', 'TAKE PHOTO', 'UPLOAD FILES'],
    system_already_knows: ['intake answers from Get Started', 'state of operation'],
    ready_signals: ['intake complete', 'name clear'],
    needs_you: ['missing details', 'alternate name', 'confirmation of filing details'],
    under_review: ['name availability', 'filing preparation', 'state processing'],
    approves: ['filing details'],
    completion_looks_like: 'Formed + EIN issued; documents in Vault; USDOT stop unlocked.',
    artifacts_received: ['Articles', 'EIN confirmation', 'Operating agreement (if prepared)'],
    what_happens_next: 'USDOT registration starts.',
  },
  staff: {
    client_context: ['owner + state', 'journey position', 'quote status'],
    work_queue: 'Formation division queue (OfficeWorkItem)',
    status_model: [],
    blockers: ['waiting on client detail', 'name unavailable', 'state processing'],
    missing_inputs: ['ID', 'owner info', 'name alternates'],
    system_flags: ['incomplete intake', 'duplicate org'],
    human_review: ['name check', 'filing completeness'],
    corrections: ['request detail', 'correct filing after rejection'],
    approval: ['client confirmation of filing details'],
    overrides: ['mark formed from external evidence (note required)'],
    operational_actions: ['FILE WITH STATE', 'RECORD APPROVAL', 'RECORD EIN', 'REQUEST DETAIL'],
    artifact_generation: ['filing package', 'document upload to vault'],
    completion: 'Formed + EIN recorded; journey advanced.',
    hub_buckets: { AWAITING_CLIENT: ['WAITING_ON_YOU'], NEEDS_REVIEW: ['NAME_CHECK'], READY_TO_FILE: ['AIO_PREPARING'], AWAITING_PROVIDER: ['FILED_WITH_STATE'], COMPLETE: ['FORMED', 'EIN_ISSUED'] },
    mirror_not_copy: 'Staff see a CASE FILE per client filing with state processing status and the formation checklist, not the guided journey.',
  },
  system: {
    ingestion: ['intake answers', 'uploaded ID'],
    validation: ['required fields', 'duplicate organisation check'],
    derivation: ['state filing checklist', 'journey dependency unlocks'],
    state_transitions: ['NOT_STARTED → INTAKE → NAME_CHECK → AIO_PREPARING → FILED_WITH_STATE → FORMED → EIN_ISSUED'],
    next_cycle_creation: 'Annual report / registered agent reminders tracked in Renewals where applicable; journey moves to USDOT.',
    failure_handling: ['state rejection → REJECTED with correction path', 'missing details → WAITING_ON_YOU'],
  },
  metaphor: 'FOUNDING DESK',
  metaphor2: 'the first stop on the business route',
  archetype: ['ROUTE', 'CASE_FILE'],
  object: 'THE BUSINESS ENTITY (name, type, status on the route)',
  objects: ['journey route', 'documents', 'EIN'],
  composition: ['The route shows formation as the first stop with later stops visibly locked.', 'One open question at a time in intake.', 'Formed state seals the entity and lights the next stop (USDOT).'],
  hierarchy: {
    CLIENT: ih('Is my business formed yet, and what do you need from me?', 'Formation stage on the route', 'Answer intake / confirm details', 'Name check · state processing', 'Missing detail / name conflict', 'The single open question', 'Articles + EIN in Vault'),
    FOUNDER_STAFF: ih('What is holding this formation?', 'Case stage × days waiting', 'Prepare and file', 'Waiting on client vs state', 'Missing detail / rejection', 'FILE · RECORD APPROVAL · RECORD EIN', 'Documents verified + USDOT unlocked'),
    PUBLIC: ih('How do I start a trucking business properly?', 'Formation → USDOT → authority route', 'Understand the order of steps', 'What AIO handles', 'none', 'START MY BUSINESS', 'Formed entity + EIN'),
  },
  grammar: [['ANSWER', 'CLIENT', 'answer an intake question', 'INTAKE'], ['CONFIRM DETAILS', 'CLIENT', 'confirm filing details', 'AIO_PREPARING'], ['FILE', 'FOUNDER_STAFF', 'file with the state', 'FILED_WITH_STATE'], ['RECORD APPROVAL', 'FOUNDER_STAFF', 'record state approval', 'FORMED']],
  emotion: { PUBLIC: 'I know where to begin.', CLIENT: 'My business is being set up correctly and I know what is next.', FOUNDER_STAFF: 'I can see every formation and what is holding it.' },
  density: 'SPARSE',
  viewports: { mobile: ['one question per screen', 'route header → question → continue'], tablet: ['intake + route side by side', 'two columns'], desktop: ['case view with route, details and documents', 'three regions'] },
  ctas: { public: 'START MY BUSINESS', client: 'CONTINUE SETUP', staff: 'OPEN FORMATION CASE' },
  avoid: ['legal advice framing', 'implying AIO is the state', 'long forms on one page'],
  e2e: {
    journey: 'PUBLIC → INTAKE → NAME CHECK → CONFIRM → FILED → FORMED → EIN → VAULT → USDOT',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'start-your-business', 'open the service page', ['entity choice explained', 'formation → USDOT order shown', 'START MY BUSINESS']],
      CLIENT_ENTRY: ['CLIENT', 'portal/business', 'open the journey', ['formation is the current stop', 'later stops locked']],
      CLIENT_ACTION: ['CLIENT', 'intake', 'complete intake + upload ID', ['one question at a time', 'progress saved']],
      SYSTEM_PROCESSING: ['SYSTEM', 'service request engine', 'create request + work item', ['formation work item in queue']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office formation queue', 'name check + prepare', ['case shows checklist + waiting-on']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/requests', 'confirm filing details', ['confirmation recorded']],
      ARTIFACT_CREATION: ['FOUNDER_STAFF', 'office case', 'record approval + upload articles + EIN', ['documents attached']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'journey · road ready · vault', 'propagate FORMED', ['USDOT stop READY', 'Road Ready entity verified']],
      COMPLETION: ['CLIENT', 'portal/business', 'view journey', ['Formation complete']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open Business & Formation', ['articles + EIN present']],
      NEXT_STEP: ['CLIENT', 'portal/business', 'see next stop', ['USDOT ready to start']],
    },
  },
  structure: { routes: [['PUBLIC', 'start-your-business/*'], ['CLIENT', 'portal/business · portal/requests'], ['FOUNDER_STAFF', 'office/* formation']], data: ['serviceCatalog: llc-formation, corp-formation, ein, startup, business-consult', 'ServiceJourney (workflowTypes.ts)'], evidence: ['src/services/catalog/serviceCatalog.ts:7-120', 'docs/SERVICE_JOURNEYS.md'] },
  functional_pct: 55,
  activation: 'formation ACTIVE (SERVICE_ACTIVATION_MATRIX)',
  code: ['src/journeys/startBusinessJourneyConfig.ts', 'src/business-formation/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.GET_STARTED', 'AIO.AUTHORITIES', 'AIO.ROAD_READY'],
});

export const AIO_ROAD_READY = aioFeature({
  id: 'AIO.ROAD_READY',
  name: 'Road Ready',
  family: 'F04 ROAD READY',
  purpose: 'Keep a persistent business-readiness profile: what is set up, what AIO has verified, what needs attention or renewal, and what to do next.',
  promise: 'Always know where your business stands and what to do next to stay road ready.',
  value: 'One profile replaces scattered checklists; setup progress and verified progress are kept honestly separate.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['Compliance specialists'],
  entries: {
    public: ['Road Ready explainer', 'road-ready', 'homepage pathway / Get Started recommendation'],
    client: ['My Business › Road Ready', 'portal/road-ready', 'My Office next action / attention item'],
    staff: ['Office compliance view', 'office/* road ready verification', 'document uploaded / item needs verification'],
    system: ['Road Ready rule engine', 'profile / fleet / document change'],
  },
  states: [
    ['NO_PROFILE', 'No profile', 'EMPTY', 'Set up your Road Ready profile', 'No profile'],
    ['SETTING_UP', 'Setting up', 'ACTIVE', 'Items to set up', 'Setup in progress'],
    ['NEEDS_ATTENTION', 'Needs attention', 'BLOCKED', 'Items need your attention', 'Client action required'],
    ['IN_VERIFICATION', 'Being verified', 'REVIEW', 'AIO is verifying items', 'Verification queue'],
    ['ROAD_READY', 'Road Ready', 'COMPLETE', 'All tracked items verified', 'Verified'],
    ['RENEWAL_DUE', 'Renewal coming', 'ARCHIVED', 'A renewal is coming up', 'Renewal window open'],
    ['VERIFICATION_REJECTED', 'Document rejected', 'ERROR', 'A document was rejected — replace it', 'Rejected document'],
  ],
  transitions: [
    ['NO_PROFILE', 'SETTING_UP', 'profile created', 'CLIENT'],
    ['SETTING_UP', 'NEEDS_ATTENTION', 'item missing / expiring', 'SYSTEM'],
    ['NEEDS_ATTENTION', 'SETTING_UP', 'client acts', 'CLIENT'],
    ['SETTING_UP', 'IN_VERIFICATION', 'documents uploaded', 'CLIENT'],
    ['IN_VERIFICATION', 'ROAD_READY', 'all items verified', 'FOUNDER_STAFF'],
    ['IN_VERIFICATION', 'VERIFICATION_REJECTED', 'document rejected', 'FOUNDER_STAFF'],
    ['VERIFICATION_REJECTED', 'SETTING_UP', 'replacement uploaded', 'CLIENT'],
    ['ROAD_READY', 'RENEWAL_DUE', 'expiration window', 'SYSTEM'],
    ['RENEWAL_DUE', 'SETTING_UP', 'renewal started', 'CLIENT'],
  ],
  anchors: { start: 'SETTING_UP', success: 'ROAD_READY', blocked: 'NEEDS_ATTENTION', errors: ['VERIFICATION_REJECTED'], empty: 'NO_PROFILE', complete: 'ROAD_READY' },
  inputs: [['BUSINESS_PROFILE', 'Business profile (operation type, interstate / intrastate, cargo)', ['GUIDED QUESTIONS'], 'which requirements apply'], ['FLEET', 'Fleet units', ['ENTER', 'IMPORT FROM FLEET'], 'unit-level items'], ['REQUIREMENT_DOCS', 'Requirement documents', ['TAKE PHOTO', 'UPLOAD FILES', 'IMPORT FROM VAULT'], 'verification']],
  derivations: [['APPLICABILITY', 'applicable requirement items', ['BUSINESS_PROFILE', 'FLEET'], 'roadReadyRules.ts (rule version 2026.08)'], ['SCORES', 'setup progress vs verified progress', ['items'], 'roadReadyScoring.ts — single source of truth'], ['NEXT_BEST', 'next best action', ['items'], 'roadReadyPriority.ts']],
  reviews: [['VERIFY_ITEM', 'IN_VERIFICATION', 'Is the document valid for the requirement?', ['VERIFY', 'REJECT WITH REASON']]],
  overrides: [['MARK_NOT_APPLICABLE', 'SETTING_UP', 'Mark a requirement not applicable with reason', ['OVERRIDE']]],
  artifacts: [['RR_PROFILE', 'Road Ready profile summary', 'REPORT', 'rule engine', null], ['VERIFIED_DOCS', 'Verified requirement documents', 'DOCUMENT', 'client uploads verified by staff', 'VAULT › Registration & Permits / Compliance']],
  vault: 'VAULT › (per requirement category)',
  inbox: [['NEEDS_ATTENTION', 'Road Ready items need your attention'], ['VERIFICATION_REJECTED', 'A Road Ready document was rejected']],
  activity: [['IN_VERIFICATION', 'Road Ready document submitted'], ['ROAD_READY', 'Road Ready item verified']],
  notify: [['RENEWAL_DUE', 'A Road Ready item is expiring soon']],
  tasks: [['IN_VERIFICATION', 'Verify Road Ready document for {client}']],
  next: 'Recommended next step is always visible; renewals flow into the Renewal Center.',
  upstream: ['AIO.GET_STARTED', 'AIO.BUSINESS_FORMATION', 'fleet profile'],
  downstream: ['AIO.SERVICES (service requests for unmet items)', 'AIO.RENEWALS', 'AIO.MY_OFFICE (attention)', 'AIO.VAULT'],
  relationships: [
    ['AIO.SERVICES', 'NEEDS_ATTENTION', 'HANDS_OFF_TO', 'GET HELP opens a pre-filled service request for the unmet item', 'request lands in division queue', { SERVICES: 'service request pre-filled with the requirement' }, 'item shows “AIO is working” badge'],
    ['AIO.RENEWALS', 'RENEWAL_DUE', 'OPENS', 'renewal appears in Renewal Center', 'renewal work item', { RENEWALS: 'renewal opened from expiring item' }, 'item moves from complete to attention'],
    ['AIO.MY_OFFICE', 'NEEDS_ATTENTION', 'UPDATES_STATUS', 'My Office attention list includes the item', 'client 360 risk', { MY_OFFICE: 'attention item' }, 'attention count increments'],
  ],
  automations: [['AUTO_RULES', 'profile / fleet / document change', 'recompute applicable items + scores', 'staff override with reason']],
  public: {
    discovery: ['homepage pathway', 'Get Started recommendation'],
    must_understand: ['Road Ready tracks your setup, what AIO verified, and what is due', RR_DISCLAIMER],
    who_its_for: 'Any carrier — new or established — that wants one place to see its operating readiness.',
    what_we_handle: ['tracking requirements that apply to you', 'verifying documents you upload', 'recommending next steps', 'helping with any unmet item as a service'],
    what_client_provides: ['business profile answers', 'fleet units', 'documents'],
    how_it_works: ['Answer a few questions', 'See what applies', 'Upload what you have', 'AIO verifies', 'Get help with the rest'],
    outcome: 'A Road Ready profile with setup progress, items verified, and next steps.',
    timing: 'Ongoing — the profile stays live.',
    pricing_relationship: 'Profile included with the portal; individual items fulfilled as priced services.',
    cta: 'Get Road Ready',
    workspace_continuity: 'The public explainer uses the same checklist language (Setup Progress, Items Verified, Recommended Next Steps) as the portal.',
  },
  client: {
    entry_point: 'My Business › Road Ready (or My Office next action)',
    primary_task: 'Close the next requirement and keep everything current.',
    sees_first: 'Setup progress vs items verified, and the recommended next step.',
    must_provide: ['profile answers', 'fleet', 'requirement documents'],
    input_methods: ['GUIDED QUESTIONS', 'TAKE PHOTO', 'UPLOAD FILES', 'IMPORT FROM VAULT', 'GET HELP (service request)'],
    system_already_knows: ['formation + authority records', 'fleet units', 'vault documents'],
    ready_signals: ['items verified count', 'setup progress'],
    needs_you: ['missing documents', 'rejected documents', 'expiring items'],
    under_review: ['documents awaiting verification'],
    approves: [],
    completion_looks_like: 'All applicable items verified; nothing needs attention.',
    artifacts_received: ['verified documents in Vault', 'Road Ready profile summary'],
    what_happens_next: 'Renewals and new requirements surface automatically.',
  },
  staff: {
    client_context: ['operation type', 'fleet', 'items by status'],
    work_queue: 'Compliance verification queue',
    status_model: [],
    blockers: ['missing docs', 'rejected docs', 'expired items'],
    missing_inputs: ['unanswered profile questions'],
    system_flags: ['expiring within window', 'conflicting data'],
    human_review: ['document verification'],
    corrections: ['reject with reason', 'request replacement'],
    approval: ['verification sign-off'],
    overrides: ['not applicable with reason'],
    operational_actions: ['VERIFY', 'REJECT', 'OPEN SERVICE REQUEST'],
    artifact_generation: ['verification record'],
    completion: 'Items verified; profile ROAD_READY.',
    hub_buckets: { NEEDS_REVIEW: ['IN_VERIFICATION'], AWAITING_CLIENT: ['NEEDS_ATTENTION', 'VERIFICATION_REJECTED'], COMPLETE: ['ROAD_READY'] },
    mirror_not_copy: 'Staff see a verification QUEUE across clients with document evidence, not the client checklist.',
  },
  system: {
    ingestion: ['profile answers', 'fleet', 'document uploads'],
    validation: ['rule version', 'document type vs requirement'],
    derivation: ['applicability', 'setup vs verified scores', 'next best action'],
    state_transitions: ['scores recompute on every change'],
    next_cycle_creation: 'Expiring items open renewals; rule version changes re-evaluate the profile.',
    failure_handling: ['upload ≠ verification — never auto-verify', 'unknown requirement → needs review'],
  },
  metaphor: 'ACTIVATION PATH',
  metaphor2: 'a pre-trip inspection for the business',
  archetype: ['CHECKLIST', 'ROUTE'],
  object: 'THE ROAD READY PROFILE (setup progress vs items verified)',
  objects: ['requirement items', 'next best action', 'renewals'],
  composition: ['Two honest meters: setup progress and items verified — never merged.', 'Next best action leads.', 'Items grouped by category with status per line.'],
  hierarchy: {
    CLIENT: ih('Where does my business stand, and what next?', 'Setup progress vs verified', 'Close the next item', 'Items by category', 'Missing / rejected / expiring item', 'Recommended next step', 'All applicable items verified'),
    FOUNDER_STAFF: ih('What needs verification?', 'Queue size × age', 'Verify documents', 'Clients at risk', 'Rejected / expired', 'VERIFY · REJECT', 'Verification recorded'),
  },
  grammar: [['UPLOAD', 'CLIENT', 'upload a requirement document', 'IN_VERIFICATION'], ['GET HELP', 'CLIENT', 'request AIO to handle an item'], ['VERIFY', 'FOUNDER_STAFF', 'verify a document', 'ROAD_READY'], ['REJECT', 'FOUNDER_STAFF', 'reject with reason', 'VERIFICATION_REJECTED']],
  emotion: { PUBLIC: 'I can see exactly what being road ready means for me.', CLIENT: 'I know where I stand and what to do next.', FOUNDER_STAFF: 'I see every unverified item and who is at risk.' },
  density: 'BALANCED',
  viewports: { mobile: ['next item first', 'meters → next action → categories'], tablet: ['categories with detail panel', 'two columns'], desktop: ['full checklist with evidence panel', 'three regions'] },
  ctas: { public: 'GET ROAD READY', client: 'NEXT STEP', staff: 'VERIFY' },
  avoid: ['claiming legal / federal compliance', 'merging setup and verified into one score', 'government seal imagery'],
  e2e: {
    journey: 'PUBLIC → PROFILE → UPLOAD → VERIFY → ROAD READY → RENEWAL',
    not_applicable: { CLIENT_APPROVAL: 'verification is a staff decision; the client approves nothing here' },
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'road-ready', 'read the explainer', ['setup vs verified explained', 'not a government system disclaimer']],
      CLIENT_ENTRY: ['CLIENT', 'portal/road-ready', 'open profile', ['two meters', 'next best action']],
      CLIENT_ACTION: ['CLIENT', 'portal/road-ready', 'upload a document', ['item moves to being verified', 'setup progress increases, verified does not']],
      SYSTEM_PROCESSING: ['SYSTEM', 'rule engine', 'recompute', ['scores recomputed', 'verification work item created']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office verification queue', 'verify', ['verified progress increases']],
      ARTIFACT_CREATION: ['SYSTEM', 'vault', 'store verified doc', ['document marked verified']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'my office · renewals', 'propagate', ['attention cleared', 'expiry tracked']],
      COMPLETION: ['CLIENT', 'portal/road-ready', 'view', ['all applicable items verified']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open category', ['verified documents present']],
      NEXT_STEP: ['CLIENT', 'portal/renewals', 'see renewal', ['expiring item appears in Renewal Center']],
    },
  },
  structure: { routes: [['PUBLIC', 'road-ready'], ['CLIENT', 'portal/road-ready'], ['FOUNDER_STAFF', 'office/* compliance']], data: ['roadReadyTypes.ts', 'roadReadyRules.ts', 'roadReadyScoring.ts', 'roadReadyPriority.ts'], evidence: ['docs/ROAD_READY_SYSTEM.md', 'src/road-ready/roadReadyConfig.ts'] },
  functional_pct: 64,
  activation: 'authorities ACTIVE · Road Ready profile live (demo persistence)',
  code: ['src/road-ready/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.SERVICES', 'AIO.RENEWALS', 'AIO.IFTA', 'AIO.AUTHORITIES'],
});

/** Shared shape for the request-driven filing services (authorities, BOC-3, registrations, permits, road tax). */
function filingService(o: {
  id: string;
  name: string;
  family: string;
  catalog: string[];
  activation: string;
  purpose: string;
  promise: string;
  object: string;
  metaphor: string;
  provides: string[];
  handles: string[];
  external: string;
  vault: string;
  artifacts: [string, string][];
  cadence: string;
  next: string;
  downstream: string[];
  relationships: Parameters<typeof aioFeature>[0]['relationships'];
  publicCta: string;
  evidence: string[];
  functional: number | null;
  declared: 'EXPERIENCE_COMPLETE' | 'EXPERIENCE_DRAFTED';
  partner?: boolean;
  open_questions?: string[];
}): ExperienceContract {
  const waitingExternal = o.partner ? 'Waiting on partner' : `Waiting on ${o.external}`;
  return aioFeature({
    id: o.id,
    name: o.name,
    family: o.family,
    purpose: o.purpose,
    promise: o.promise,
    value: `One request, AIO prepares and tracks it, and the result lands in the Vault and in Road Ready.`,
    actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
    secondary: [o.external],
    entries: {
      public: [`${o.name} service page`, `services/${o.catalog[0]}`, 'Services hub / Road Ready recommendation'],
      client: [`${o.name} request`, 'portal/services · portal/requests', 'Road Ready GET HELP or Services catalog'],
      staff: [`${o.name} division queue`, 'office/* permitting / compliance queue', 'service request submitted'],
      system: ['Service request engine', 'request submitted / document uploaded'],
    },
    states: [
      ['NOT_REQUESTED', 'Not requested', 'EMPTY', `Request ${o.name}`, 'No request', { CLIENT: o.publicCta.toUpperCase(), PUBLIC: o.publicCta.toUpperCase() }],
      ['REQUESTED', 'Requested', 'ACTIVE', 'Request received — add what AIO needs', 'New request'],
      ['WAITING_ON_YOU', 'Waiting on you', 'BLOCKED', 'AIO needs documents or details', 'Waiting on customer'],
      ['AIO_WORKING', 'All In One is working', 'REVIEW', 'AIO is preparing it', 'In progress'],
      ['WAITING_EXTERNALLY', 'Waiting externally', 'REVIEW', `Submitted — ${waitingExternal.toLowerCase()}`, waitingExternal],
      ['COMPLETE', 'Complete', 'COMPLETE', 'Done — your documents are in the Vault', 'Completed'],
      ['ON_FILE', 'On file', 'ARCHIVED', `On file — ${o.cadence}`, 'Closed; renewal tracked'],
      ['RETURNED', 'Needs correction', 'ERROR', 'It came back with a problem — AIO is fixing it', 'Rejected / returned'],
    ],
    transitions: [
      ['NOT_REQUESTED', 'REQUESTED', 'client requests (quote accepted where required)', 'CLIENT'],
      ['REQUESTED', 'WAITING_ON_YOU', 'documents / details missing', 'FOUNDER_STAFF'],
      ['WAITING_ON_YOU', 'AIO_WORKING', 'client provides', 'CLIENT'],
      ['REQUESTED', 'AIO_WORKING', 'complete request', 'FOUNDER_STAFF'],
      ['AIO_WORKING', 'WAITING_EXTERNALLY', 'submitted', 'FOUNDER_STAFF'],
      ['WAITING_EXTERNALLY', 'COMPLETE', 'result recorded', 'FOUNDER_STAFF'],
      ['WAITING_EXTERNALLY', 'RETURNED', 'returned / rejected', 'FOUNDER_STAFF'],
      ['RETURNED', 'AIO_WORKING', 'correction prepared', 'FOUNDER_STAFF'],
      ['COMPLETE', 'ON_FILE', 'documents verified in Vault', 'SYSTEM'],
    ],
    anchors: { start: 'REQUESTED', success: 'COMPLETE', blocked: 'WAITING_ON_YOU', errors: ['RETURNED'], empty: 'NOT_REQUESTED', complete: 'ON_FILE' },
    inputs: o.provides.map((p, i) => [`INPUT_${i + 1}`, p, ['UPLOAD FILES', 'TAKE PHOTO', 'IMPORT FROM VAULT', 'ENTER'], o.name]),
    derivations: [['CHECKLIST', 'request checklist + completeness', ['inputs'], 'workflow template for the service'], ['CUSTOMER_STATE', 'customer-friendly state', ['workflow state'], 'SERVICE_JOURNEYS customer states (raw states never shown)']],
    reviews: [['COMPLETENESS', 'REQUESTED', 'Is the request complete?', ['START WORK', 'REQUEST DOCUMENTS']], ['RESULT', 'WAITING_EXTERNALLY', 'Record the external result', ['COMPLETE', 'RETURNED']]],
    approvals: [['CONFIRM_SUBMISSION', 'AIO_WORKING', 'Confirm the details AIO will submit', ['CONFIRM', 'EDIT']]],
    overrides: [['MANUAL_RESULT', 'WAITING_EXTERNALLY', 'Record result from external evidence', ['RECORD WITH NOTE']]],
    artifacts: o.artifacts.map(([id, name]) => [id, name, 'DOCUMENT', `${o.external} result recorded by staff`, o.vault] as [string, string, 'DOCUMENT', string, string]),
    vault: o.vault,
    inbox: [['WAITING_ON_YOU', `AIO needs documents for ${o.name}`], ['COMPLETE', `${o.name} complete — documents in your Vault`]],
    activity: [['REQUESTED', `${o.name} requested`], ['COMPLETE', `${o.name} complete`]],
    notify: [['COMPLETE', `${o.name} complete`], ['ON_FILE', `${o.name} renewal reminder (${o.cadence})`]],
    tasks: [['REQUESTED', `Review ${o.name} request for {client}`], ['WAITING_EXTERNALLY', `Follow up ${o.external} on {client}`]],
    next: o.next,
    upstream: ['AIO.SERVICES (request)', 'AIO.ROAD_READY (unmet item)', 'AIO.BUSINESS_FORMATION'],
    downstream: o.downstream,
    relationships: o.relationships,
    public: {
      discovery: ['Services hub', 'Road Ready recommendation', 'search'],
      must_understand: [`what ${o.name} is`, `AIO prepares and submits; ${o.external} decides`, 'what you need to provide'],
      who_its_for: 'Carriers that need this registration / filing.',
      what_we_handle: o.handles,
      what_client_provides: o.provides,
      how_it_works: ['Request', 'Send what AIO needs', 'AIO prepares + you confirm', `AIO submits to ${o.external}`, 'Result in your Vault'],
      outcome: `${o.name} on file, documents in your Vault, Road Ready updated.`,
      timing: `Depends on ${o.external}; ${o.cadence}.`,
      pricing_relationship: 'Per catalog pricing model (quote required for most); government / partner fees separate.',
      cta: o.publicCta,
      workspace_continuity: 'The page shows the same request steps the client tracks in the portal (customer-friendly states).',
    },
    client: {
      entry_point: 'Services catalog / Road Ready GET HELP → request',
      primary_task: 'Give AIO what it needs and confirm the submission.',
      sees_first: `${o.object} with its current customer-friendly state and what AIO needs.`,
      must_provide: o.provides,
      input_methods: ['UPLOAD FILES', 'TAKE PHOTO', 'IMPORT FROM VAULT', 'ENTER DETAILS'],
      system_already_knows: ['business entity + USDOT / MC where on file', 'fleet units', 'documents already in the Vault'],
      ready_signals: ['checklist completeness'],
      needs_you: ['missing documents / details', 'submission confirmation'],
      under_review: ['AIO preparing', `${o.external} processing`],
      approves: ['submission details'],
      completion_looks_like: `${o.object} COMPLETE with documents in the Vault and Road Ready updated.`,
      artifacts_received: o.artifacts.map((a) => a[1]),
      what_happens_next: o.next,
    },
    staff: {
      client_context: ['entity + DOT / MC', 'fleet', 'Road Ready position', 'quote status'],
      work_queue: `${o.family} division queue (OfficeWorkItem, waitingOn customer / government / partner)`,
      status_model: [],
      blockers: ['waiting on customer', `waiting on ${o.external}`],
      missing_inputs: o.provides,
      system_flags: ['incomplete checklist', 'expiring related item'],
      human_review: ['request completeness', 'external result'],
      corrections: ['request documents', 'correct after return'],
      approval: ['client confirmation of submission'],
      overrides: ['record result from external evidence (note)'],
      operational_actions: ['START WORK', 'REQUEST DOCUMENTS', 'SUBMIT', 'RECORD RESULT'],
      artifact_generation: ['submission package', 'result document to vault'],
      completion: 'Result recorded, documents verified, Road Ready updated.',
      hub_buckets: { AWAITING_CLIENT: ['WAITING_ON_YOU'], NEEDS_REVIEW: ['REQUESTED'], READY_TO_FILE: ['AIO_WORKING'], AWAITING_PROVIDER: ['WAITING_EXTERNALLY'], BLOCKED: ['RETURNED'], COMPLETE: ['COMPLETE', 'ON_FILE'] },
      mirror_not_copy: 'Staff see a QUEUE of requests with waitingOn and due follow-ups, plus the submission package — not the client request card.',
    },
    system: {
      ingestion: ['request fields', 'uploaded documents'],
      validation: ['checklist completeness', 'document type'],
      derivation: ['customer-friendly state', 'Road Ready item status'],
      state_transitions: ['REQUESTED → AIO_WORKING → WAITING_EXTERNALLY → COMPLETE → ON_FILE'],
      next_cycle_creation: `Renewal / next period tracked (${o.cadence}).`,
      failure_handling: ['external return → RETURNED with correction path', 'no direct government integration unless activated — staff records results'],
    },
    metaphor: o.metaphor,
    metaphor2: 'a request that moves through the office and comes back filed',
    archetype: ['CASE_FILE', 'CHECKLIST'],
    object: o.object,
    objects: ['checklist', 'documents', 'external status'],
    composition: ['The request object with its customer-friendly state leads.', 'Checklist of what AIO needs sits under it.', 'External waiting is shown as AIO’s responsibility, not the client’s.'],
    hierarchy: {
      CLIENT: ih(`Where is my ${o.name}, and do you need anything?`, 'Customer-friendly state', 'Provide documents / confirm', 'Checklist', 'Missing document', 'The single next item', 'Documents in Vault + Road Ready updated'),
      FOUNDER_STAFF: ih(`What is holding this ${o.name}?`, 'waitingOn × age', 'Prepare, submit, record', 'Follow-ups due', 'Customer / external wait', 'SUBMIT · RECORD RESULT', 'Result recorded + documents verified'),
    },
    grammar: [['UPLOAD', 'CLIENT', 'send a required document', 'AIO_WORKING'], ['CONFIRM', 'CLIENT', 'confirm submission details'], ['SUBMIT', 'FOUNDER_STAFF', `submit to ${o.external}`, 'WAITING_EXTERNALLY'], ['RECORD RESULT', 'FOUNDER_STAFF', 'record the outcome', 'COMPLETE']],
    emotion: { PUBLIC: `I understand what AIO does for ${o.name}.`, CLIENT: 'I know what AIO needs and that it is being handled.', FOUNDER_STAFF: 'I see every open request and what it is waiting on.' },
    density: 'BALANCED',
    viewports: { mobile: ['state + one next item', 'state header → needs → upload'], tablet: ['request + checklist', 'two columns'], desktop: ['case with checklist, documents and messages', 'three regions'] },
    ctas: { public: o.publicCta.toUpperCase(), client: 'CONTINUE REQUEST', staff: 'OPEN REQUEST' },
    avoid: ['raw workflow states to the client', 'implying AIO is the government agency', 'legal advice framing'],
    e2e: {
      journey: `PUBLIC → REQUEST → DOCUMENTS → AIO SUBMITS → RESULT → VAULT → ROAD READY`,
      expect: {
        PUBLIC_DISCOVERY: ['PUBLIC', `services/${o.catalog[0]}`, 'open the service page', ['what it is + what AIO handles + what you provide', `${o.publicCta} CTA`]],
        CLIENT_ENTRY: ['CLIENT', 'portal/services', 'request the service', ['request created with customer-friendly state']],
        CLIENT_ACTION: ['CLIENT', 'portal/requests', 'upload documents', ['checklist completes']],
        SYSTEM_PROCESSING: ['SYSTEM', 'service request engine', 'create work item', ['work item in division queue']],
        STAFF_REVIEW: ['FOUNDER_STAFF', 'office queue', 'review + submit', ['waitingOn shown', 'submission recorded']],
        CLIENT_APPROVAL: ['CLIENT', 'portal/requests', 'confirm submission details', ['confirmation recorded']],
        ARTIFACT_CREATION: ['FOUNDER_STAFF', 'office queue', 'record result + upload documents', ['result documents attached']],
        DOWNSTREAM_MOVEMENT: ['SYSTEM', 'road ready · vault · renewals', 'propagate', ['Road Ready item updated']],
        COMPLETION: ['CLIENT', 'portal/requests', 'view', ['COMPLETE state']],
        ARCHIVE: ['CLIENT', 'portal/vault', 'open category', ['documents present']],
        NEXT_STEP: ['CLIENT', 'portal/renewals', 'see next', [o.next]],
      },
    },
    structure: { routes: [['PUBLIC', `services/${o.catalog[0]}`], ['CLIENT', 'portal/services · portal/requests'], ['FOUNDER_STAFF', 'office/* queue']], data: [`serviceCatalog: ${o.catalog.join(', ')}`, 'service request engine', 'OfficeWorkItem'], evidence: o.evidence },
    functional_pct: o.functional,
    activation: o.activation,
    code: ['src/services/catalog/serviceCatalog.ts', 'src/workflow/*'],
    declared: o.declared,
    related: ['AIO.ROAD_READY', 'AIO.SERVICES', 'AIO.VAULT', 'AIO.RENEWALS'],
    open_questions: o.open_questions,
  });
}

const rr = (name: string): Parameters<typeof aioFeature>[0]['relationships'][number] => ['AIO.ROAD_READY', 'COMPLETE', 'UPDATES_STATUS', `Road Ready ${name} item complete`, 'profile verified', { ROAD_READY: `${name} requirement verified` }, 'checklist line completes'];
const vaultRel = (cat: string): Parameters<typeof aioFeature>[0]['relationships'][number] => ['AIO.VAULT', 'COMPLETE', 'ARCHIVES_TO', `documents appear in Vault › ${cat}`, 'documents verified', { VAULT: cat }, 'request card seals and files'];
const renewRel = (what: string): Parameters<typeof aioFeature>[0]['relationships'][number] => ['AIO.RENEWALS', 'ON_FILE', 'OPENS', `${what} renewal tracked in Renewal Center`, 'renewal scheduled', { RENEWALS: `${what} renewal` }, 'renewal appears on the horizon'];

export const AIO_AUTHORITIES = filingService({
  id: 'AIO.AUTHORITIES',
  name: 'Authorities — USDOT / MC / MCS-150',
  family: 'F06 SERVICES (get-road-ready) · F04 ROAD READY',
  catalog: ['usdot-registration', 'operating-authority-assistance', 'authority-maintenance', 'mcs-150-biennial-update'],
  activation: 'authorities ACTIVE',
  purpose: 'Get and keep the carrier’s USDOT number and MC operating authority, including biennial MCS-150 updates.',
  promise: 'AIO prepares your USDOT and authority filings and keeps them current.',
  object: 'THE AUTHORITY (USDOT / MC numbers and status)',
  metaphor: 'AUTHORITY DESK',
  provides: ['entity documents', 'business address + contacts', 'operation type + cargo', 'fleet count'],
  handles: ['USDOT registration', 'MC / operating authority', 'MCS-150 biennial updates', 'authority maintenance'],
  external: 'FMCSA',
  vault: 'VAULT › Registration & Permits',
  artifacts: [['USDOT_RECORD', 'USDOT number record'], ['MC_GRANT', 'Operating authority grant']],
  cadence: 'MCS-150 biennial update',
  next: 'BOC-3 and insurance filings follow; MCS-150 biennial update is scheduled.',
  downstream: ['AIO.BOC3', 'AIO.INSURANCE', 'AIO.ROAD_READY', 'AIO.VAULT', 'AIO.RENEWALS'],
  relationships: [rr('USDOT / MC'), vaultRel('Registration & Permits'), renewRel('MCS-150'), ['AIO.BOC3', 'COMPLETE', 'UNLOCKS', 'BOC-3 becomes the next journey stop', 'BOC-3 work item can start', { JOURNEY: 'BOC-3 READY' }, 'next stop lights up']],
  publicCta: 'Request Assistance',
  evidence: ['src/services/catalog/serviceCatalog.ts:124-198,394-418'],
  functional: 57,
  declared: 'EXPERIENCE_COMPLETE',
});

export const AIO_BOC3 = filingService({
  id: 'AIO.BOC3',
  name: 'BOC-3 Process Agent Filing',
  family: 'F06 SERVICES (get-road-ready)',
  catalog: ['boc-3-assistance'],
  activation: 'boc3 PARTNER_PENDING — partner / manual workflow until provider is activated',
  purpose: 'Get the carrier’s BOC-3 process-agent designation filed so the operating authority can activate.',
  promise: 'AIO coordinates your BOC-3 through a process-agent partner.',
  object: 'THE BOC-3 FILING',
  metaphor: 'PARTNER HANDOFF DESK',
  provides: ['USDOT / MC number', 'entity details'],
  handles: ['partner coordination', 'confirmation tracking', 'storing the filing'],
  external: 'process-agent partner',
  vault: 'VAULT › Registration & Permits',
  artifacts: [['BOC3_CONFIRMATION', 'BOC-3 filing confirmation']],
  cadence: 'kept with the authority',
  next: 'Operating authority activation can proceed once insurance is on file.',
  downstream: ['AIO.AUTHORITIES', 'AIO.ROAD_READY', 'AIO.VAULT'],
  relationships: [rr('BOC-3'), vaultRel('Registration & Permits')],
  publicCta: 'Request Information',
  evidence: ['src/services/catalog/serviceCatalog.ts:199-221', 'src/infrastructure/serviceActivation.ts (boc3 PARTNER_PENDING)'],
  functional: 57,
  declared: 'EXPERIENCE_DRAFTED',
  partner: true,
  open_questions: [
    'Process-agent partner is not activated (PARTNER_PENDING): partner turnaround, confirmation format and who files are unknown — the client / staff handoff moment cannot be authored precisely.',
  ],
});

export const AIO_IFTA_REGISTRATION = filingService({
  id: 'AIO.IFTA_REGISTRATION',
  name: 'IFTA Account Registration',
  family: 'F06 SERVICES (get-road-ready)',
  catalog: ['ifta-fuel-tax-assistance'],
  activation: 'ifta-reg LIMITED_PILOT',
  purpose: 'Set up the carrier’s IFTA account and decals so quarterly filing can begin.',
  promise: 'AIO sets up your IFTA account so the quarterly filing room can open.',
  object: 'THE IFTA ACCOUNT (license + decals)',
  metaphor: 'ACCOUNT SETUP DESK',
  provides: ['entity + USDOT', 'base jurisdiction address', 'qualified vehicles'],
  handles: ['application preparation', 'base jurisdiction submission', 'decal tracking'],
  external: 'base jurisdiction',
  vault: 'VAULT › Registration & Permits (tax_fuel)',
  artifacts: [['IFTA_LICENSE', 'IFTA license'], ['IFTA_DECALS', 'IFTA decal record']],
  cadence: 'annual license / decal renewal',
  next: 'The first IFTA quarter opens (AIO.IFTA).',
  downstream: ['AIO.IFTA', 'AIO.ROAD_READY', 'AIO.RENEWALS'],
  relationships: [rr('IFTA'), ['AIO.IFTA', 'COMPLETE', 'OPENS', 'first IFTA quarter card appears', 'quarter work item created', { IFTA: 'first quarter collection window opens' }, 'account seal → quarter bench'], renewRel('IFTA license / decals')],
  publicCta: 'Request Assistance',
  evidence: ['src/services/catalog/serviceCatalog.ts:323-347'],
  functional: 57,
  declared: 'EXPERIENCE_COMPLETE',
});

export const AIO_PERMITTING = filingService({
  id: 'AIO.PERMITTING',
  name: 'Permitting — UCR / Trip / Temporary & Specialty Permits',
  family: 'F06 SERVICES (permits-taxes-compliance)',
  catalog: ['trip-permits', 'temporary-permits', 'ucr-registration', 'ucr-renewal'],
  activation: 'permitting ACTIVE',
  purpose: 'Get the permits a carrier needs to run a route or a year — UCR, trip and temporary / specialty permits.',
  promise: 'Tell AIO where you are going; AIO gets the permits.',
  object: 'THE PERMIT (jurisdiction, validity window)',
  metaphor: 'READINESS / REQUIREMENT ROOM',
  provides: ['unit + plate', 'route / jurisdictions + dates', 'UCR fleet size bracket'],
  handles: ['permit application', 'UCR registration + renewal', 'permit storage + expiry tracking'],
  external: 'issuing jurisdiction',
  vault: 'VAULT › Registration & Permits',
  artifacts: [['PERMIT', 'Permit document'], ['UCR_RECEIPT', 'UCR registration receipt']],
  cadence: 'UCR annual; trip permits per trip',
  next: 'UCR renewal is scheduled; trip permits expire with their window.',
  downstream: ['AIO.ROAD_READY', 'AIO.VAULT', 'AIO.RENEWALS'],
  relationships: [rr('permit'), vaultRel('Registration & Permits'), renewRel('UCR')],
  publicCta: 'Request Permit',
  evidence: ['src/services/catalog/serviceCatalog.ts:222-271,571-614'],
  functional: 57,
  declared: 'EXPERIENCE_COMPLETE',
});

export const AIO_TAGS_REGISTRATION = filingService({
  id: 'AIO.TAGS_REGISTRATION',
  name: 'Tags / Registration — IRP / Plates / Titles',
  family: 'F06 SERVICES (get-road-ready)',
  catalog: ['irp-apportioned-registration', 'tag-services', 'title-services'],
  activation: 'tags ACTIVE',
  purpose: 'Register the carrier’s units — apportioned (IRP) plates, tags and titles.',
  promise: 'AIO handles plates, IRP and titles for every truck.',
  object: 'THE UNIT REGISTRATION (truck, plate, jurisdictions)',
  metaphor: 'UNIT REGISTRATION BAY',
  provides: ['title / bill of sale', 'VIN + unit details', 'insurance proof', 'HVUT proof (2290) where required'],
  handles: ['IRP application', 'plate / tag services', 'title transfers', 'cab card storage'],
  external: 'registration office',
  vault: 'VAULT › Registration & Permits',
  artifacts: [['CAB_CARD', 'IRP cab card'], ['REGISTRATION', 'Registration / plate record'], ['TITLE', 'Title record']],
  cadence: 'annual registration renewal',
  next: 'Registration renewal scheduled per unit.',
  downstream: ['AIO.ROAD_READY', 'AIO.VAULT', 'AIO.RENEWALS', 'AIO.IFTA (qualified vehicles)'],
  relationships: [rr('registration'), vaultRel('Registration & Permits'), renewRel('IRP / registration')],
  publicCta: 'Request Assistance',
  evidence: ['src/services/catalog/serviceCatalog.ts:298-322,419-467'],
  functional: 57,
  declared: 'EXPERIENCE_COMPLETE',
});

export const AIO_ROAD_TAX = filingService({
  id: 'AIO.ROAD_TAX',
  name: 'Road / Highway Use Tax — HVUT 2290 & Road / Use Taxes',
  family: 'F06 SERVICES (permits-taxes-compliance)',
  catalog: ['hvut-form-2290', 'road-tax-assistance'],
  activation: 'road-tax INTERNAL_ONLY — staff workflow',
  purpose: 'File heavy vehicle use tax (Form 2290) and state road / use taxes for qualifying units.',
  promise: 'AIO files your highway use tax and keeps the stamped proof.',
  object: 'THE TAX PERIOD (units, amount, stamped proof)',
  metaphor: 'ANNUAL TAX WINDOW',
  provides: ['units + taxable gross weight', 'first-use month', 'payment method'],
  handles: ['2290 preparation + filing', 'state road / use tax filing', 'stamped Schedule 1 storage'],
  external: 'tax authority',
  vault: 'VAULT › Tax & Financial',
  artifacts: [['SCHEDULE_1', 'Stamped Schedule 1 (2290)'], ['ROAD_TAX_RETURN', 'Road / use tax return']],
  cadence: 'annual tax period',
  next: 'Next tax period is tracked; Schedule 1 feeds IRP registration.',
  downstream: ['AIO.TAGS_REGISTRATION', 'AIO.VAULT', 'AIO.RENEWALS'],
  relationships: [vaultRel('Tax & Financial'), ['AIO.TAGS_REGISTRATION', 'COMPLETE', 'FEEDS', 'Schedule 1 available for IRP', 'registration can proceed', { TAGS: 'HVUT proof on file' }, 'proof badge appears on the unit'], renewRel('HVUT period')],
  publicCta: 'Request Assistance',
  evidence: ['src/services/catalog/serviceCatalog.ts:272-297,371-393', 'src/infrastructure/serviceActivation.ts (road-tax INTERNAL_ONLY)'],
  functional: 57,
  declared: 'EXPERIENCE_COMPLETE',
});

export const AIO_COMPLIANCE_SAFETY = filingService({
  id: 'AIO.COMPLIANCE_SAFETY',
  name: 'Compliance & Safety — DOT compliance, DQ files, D&A, Clearinghouse, ELD, audits',
  family: 'F06 SERVICES (safety-drivers)',
  catalog: ['dot-compliance-support', 'driver-qualification-files', 'drug-alcohol-consortium', 'fmcsa-clearinghouse-assistance', 'eld-services', 'dot-audit-support', 'new-entrant-audit', 'safety-programs'],
  activation: 'catalog-listed; activation per service (not in SERVICE_ACTIVATION_MATRIX)',
  purpose: 'Keep the carrier’s safety program and driver files audit-ready.',
  promise: 'AIO organises your safety program so an audit is a review, not a scramble.',
  object: 'THE SAFETY FILE (program + driver files)',
  metaphor: 'AUDIT-READY CABINET',
  provides: ['driver documents', 'program enrolment details', 'ELD provider'],
  handles: ['DQ file assembly', 'consortium enrolment', 'clearinghouse queries', 'audit preparation'],
  external: 'FMCSA / consortium / auditor',
  vault: 'VAULT › Safety & Drivers',
  artifacts: [['DQ_FILE', 'Driver qualification file'], ['AUDIT_PACKET', 'Audit preparation packet']],
  cadence: 'annual reviews + audit events',
  next: 'Annual driver reviews and expiring credentials are tracked.',
  downstream: ['AIO.ROAD_READY', 'AIO.DRIVERLINK', 'AIO.VAULT'],
  relationships: [rr('safety'), vaultRel('Safety & Drivers')],
  publicCta: 'Request Assistance',
  evidence: ['src/services/catalog/serviceCatalog.ts:495-570,660-775'],
  functional: null,
  // a bundle of distinct services with different lifecycles — each needs its own contract before screen generation
  declared: 'EXPERIENCE_DRAFTED',
  open_questions: [
    'Bundles 8 catalog services (DOT compliance, DQ files, D&A consortium, Clearinghouse, ELD services, DOT audit, new-entrant audit, safety programs) with different lifecycles — split into one contract per service.',
    'Activation state per service is not in SERVICE_ACTIVATION_MATRIX.',
  ],
});

export const AIO_RENEWALS = aioFeature({
  id: 'AIO.RENEWALS',
  name: 'Renewals',
  family: 'F04 ROAD READY · F06 SERVICES (renewals)',
  purpose: 'Answer “what are we doing about upcoming expirations?” — and start each renewal before it lapses.',
  promise: 'AIO watches every expiration and starts the renewal with you.',
  value: 'No expired authority, plate, insurance or permit by surprise.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['issuing agencies / partners'],
  entries: {
    public: ['Renewals service page', 'services/renewals', 'Services hub'],
    client: ['Renewal Center', 'portal/renewals', 'expiring item notification / Road Ready'],
    staff: ['Office Renewal Center', 'office/renewals', 'renewal window opened'],
    system: ['renewal eligibility engine', 'document expiration date approaching'],
  },
  states: [
    ['NONE_DUE', 'Nothing due', 'EMPTY', 'Nothing is expiring soon', 'No renewals in window'],
    ['UPCOMING', 'Upcoming', 'ACTIVE', 'Coming up — decide how to renew', 'In window'],
    ['DECISION_NEEDED', 'Decide', 'APPROVAL', 'Renew with AIO or self-manage?', 'Awaiting client decision', { CLIENT: 'RENEW WITH AIO', FOUNDER_STAFF: 'REMIND' }],
    ['WITH_AIO', 'Renewing with AIO', 'REVIEW', 'AIO is renewing it', 'Service request open'],
    ['OVERDUE', 'Expired / overdue', 'BLOCKED', 'This has expired — act now', 'Lapsed'],
    ['RENEWED', 'Renewed', 'COMPLETE', 'Renewed — new document in Vault', 'Completed'],
    ['SELF_MANAGED', 'Self-managed', 'ARCHIVED', 'You are renewing this yourself', 'Client self-manages'],
    ['RENEWAL_FAILED', 'Renewal problem', 'ERROR', 'The renewal hit a problem — AIO is on it', 'Rejected'],
  ],
  transitions: [
    ['NONE_DUE', 'UPCOMING', 'expiration enters window', 'SYSTEM'],
    ['UPCOMING', 'DECISION_NEEDED', 'decision requested', 'SYSTEM'],
    ['DECISION_NEEDED', 'WITH_AIO', 'start with AIO', 'CLIENT'],
    ['DECISION_NEEDED', 'SELF_MANAGED', 'self-managed', 'CLIENT'],
    ['UPCOMING', 'OVERDUE', 'expiration passes', 'SYSTEM'],
    ['OVERDUE', 'WITH_AIO', 'start with AIO', 'CLIENT'],
    ['WITH_AIO', 'RENEWED', 'renewal recorded', 'FOUNDER_STAFF'],
    ['WITH_AIO', 'RENEWAL_FAILED', 'renewal rejected', 'FOUNDER_STAFF'],
    ['RENEWAL_FAILED', 'WITH_AIO', 'correction', 'FOUNDER_STAFF'],
  ],
  anchors: { start: 'UPCOMING', success: 'RENEWED', blocked: 'OVERDUE', errors: ['RENEWAL_FAILED'], empty: 'NONE_DUE', complete: 'RENEWED' },
  inputs: [['RENEWAL_DECISION', 'Renew with AIO or self-manage', ['DECIDE'], 'who renews'], ['RENEWAL_DOCS', 'Updated documents', ['UPLOAD FILES', 'TAKE PHOTO', 'IMPORT FROM VAULT'], 'renewal submission']],
  derivations: [['ELIGIBILITY', 'renewal items from document expirations', ['vault documents'], 'renewalService.ts build from documents + dedupe']],
  reviews: [['RENEWAL_RESULT', 'WITH_AIO', 'Record renewal result', ['RENEWED', 'FAILED']]],
  approvals: [['RENEW_DECISION', 'DECISION_NEEDED', 'Renew with AIO?', ['RENEW WITH AIO', 'SELF-MANAGE']]],
  overrides: [['MARK_COMPLETE', 'SELF_MANAGED', 'Record self-managed renewal from document', ['RECORD']]],
  artifacts: [['RENEWED_DOC', 'Renewed document', 'DOCUMENT', 'renewal result', 'VAULT › (category of the renewed item)']],
  vault: 'VAULT › (category of the renewed item)',
  inbox: [['DECISION_NEEDED', '{item} expires {date} — renew with AIO?'], ['RENEWED', '{item} renewed']],
  activity: [['WITH_AIO', 'Renewal started with AIO'], ['RENEWED', 'Renewal complete']],
  notify: [['UPCOMING', '{item} expires in {d} days'], ['OVERDUE', '{item} has expired']],
  tasks: [['WITH_AIO', 'Renew {item} for {client}']],
  next: 'The renewed item’s next expiration is tracked automatically.',
  upstream: ['AIO.VAULT (expiration dates)', 'AIO.ROAD_READY', 'AIO.INSURANCE'],
  downstream: ['AIO.SERVICES (renewal reuses the service request engine)', 'AIO.VAULT', 'AIO.ROAD_READY'],
  relationships: [['AIO.ROAD_READY', 'RENEWED', 'UPDATES_STATUS', 'Road Ready item current again', 'profile current', { ROAD_READY: 'item verified' }, 'attention → complete'], ['AIO.VAULT', 'RENEWED', 'ARCHIVES_TO', 'renewed document in Vault (old one superseded)', 'supersede recorded', { VAULT: 'new version supersedes' }, 'document card swaps version']],
  public: {
    discovery: ['Services hub', 'Road Ready'],
    must_understand: ['AIO tracks expirations from your documents', 'you choose to renew with AIO or yourself'],
    who_its_for: 'Any carrier with authorities, plates, permits, insurance or credentials that expire.',
    what_we_handle: ['tracking expirations', 'starting renewals as service requests', 'storing renewed documents'],
    what_client_provides: ['the decision', 'updated documents'],
    how_it_works: ['AIO spots an expiration', 'You decide', 'AIO renews', 'New document in Vault'],
    outcome: 'Renewed items with no lapse.',
    timing: 'Windows per item type.',
    pricing_relationship: 'Each renewal priced as its service.',
    cta: 'See Renewals',
    workspace_continuity: 'The Renewal Center shows the same horizon of upcoming expirations described on the page.',
  },
  client: {
    entry_point: 'Renewal Center (or expiring notification)',
    primary_task: 'Decide how each upcoming renewal is handled.',
    sees_first: 'The renewal horizon — what expires next and when.',
    must_provide: ['decision', 'updated documents'],
    input_methods: ['DECIDE', 'UPLOAD FILES', 'IMPORT FROM VAULT'],
    system_already_knows: ['expiration dates from verified documents'],
    ready_signals: ['days until expiration'],
    needs_you: ['renewal decisions', 'expired items'],
    under_review: ['renewals AIO is working'],
    approves: ['renew with AIO'],
    completion_looks_like: 'Item renewed; new document in Vault.',
    artifacts_received: ['Renewed document'],
    what_happens_next: 'Next expiration tracked.',
  },
  staff: {
    client_context: ['items expiring by client', 'lapse risk'],
    work_queue: 'Office Renewal Center',
    status_model: [],
    blockers: ['awaiting client decision', 'overdue items'],
    missing_inputs: ['updated documents'],
    system_flags: ['expired', 'expiring within 30 days'],
    human_review: ['renewal result'],
    corrections: ['request documents'],
    approval: ['client decision recorded'],
    overrides: ['record self-managed renewal'],
    operational_actions: ['REMIND', 'START RENEWAL', 'RECORD RESULT'],
    artifact_generation: ['renewed document upload'],
    completion: 'Renewal recorded; supersede old document.',
    hub_buckets: { AWAITING_CLIENT: ['DECISION_NEEDED'], BLOCKED: ['OVERDUE', 'RENEWAL_FAILED'], NEEDS_REVIEW: ['WITH_AIO'], COMPLETE: ['RENEWED'] },
    mirror_not_copy: 'Staff see a lapse-risk QUEUE across clients, not one client’s horizon.',
  },
  system: {
    ingestion: ['document expiration dates'],
    validation: ['dedupe renewals'],
    derivation: ['renewal items + windows'],
    state_transitions: ['window → decision → with AIO → renewed'],
    next_cycle_creation: 'Renewed document’s expiration creates the next renewal item.',
    failure_handling: ['missing expiration date → staff task', 'lapse → OVERDUE escalation'],
  },
  metaphor: 'EXPIRATION HORIZON',
  metaphor2: 'a calendar that acts',
  archetype: ['HORIZON', 'QUEUE'],
  object: 'THE NEXT EXPIRATION (item, date, decision)',
  objects: ['renewal horizon', 'decisions', 'renewed documents'],
  composition: ['A horizon ordered by days-to-expiry; the nearest leads.', 'Each renewal carries one decision.', 'Expired items break the horizon visually.'],
  hierarchy: {
    CLIENT: ih('What is expiring, and how is it being renewed?', 'Next expiration + days', 'Decide renew with AIO / self', 'Upcoming list', 'Expired item', 'Decision on the nearest item', 'Renewed document in Vault'),
    FOUNDER_STAFF: ih('Which clients are about to lapse?', 'Lapse risk', 'Remind / renew', 'Decisions pending', 'Overdue', 'START RENEWAL', 'Renewal recorded'),
  },
  grammar: [['RENEW WITH AIO', 'CLIENT', 'start a renewal request', 'WITH_AIO'], ['SELF-MANAGE', 'CLIENT', 'handle it yourself', 'SELF_MANAGED'], ['RECORD RESULT', 'FOUNDER_STAFF', 'record renewal', 'RENEWED']],
  emotion: { PUBLIC: 'Nothing will expire on me by surprise.', CLIENT: 'I see what is coming and it is handled.', FOUNDER_STAFF: 'I see lapse risk before it happens.' },
  density: 'BALANCED',
  viewports: { mobile: ['nearest expiration first', 'horizon list'], tablet: ['horizon + detail', 'two columns'], desktop: ['horizon timeline + queue', 'timeline over table'] },
  ctas: { public: 'SEE RENEWALS', client: 'DECIDE', staff: 'START RENEWAL' },
  avoid: ['calendar-only view without decisions', 'alarm styling for items months away'],
  e2e: {
    journey: 'EXPIRATION → DECISION → RENEW WITH AIO → RENEWED → VAULT',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'services/renewals', 'open page', ['tracking + decision explained']],
      CLIENT_ENTRY: ['CLIENT', 'portal/renewals', 'open Renewal Center', ['nearest expiration leads']],
      CLIENT_ACTION: ['CLIENT', 'portal/renewals', 'upload updated document', ['document attached']],
      SYSTEM_PROCESSING: ['SYSTEM', 'renewal engine', 'build renewals from documents', ['deduped renewal item']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/renewals', 'renew', ['work item open']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/renewals', 'RENEW WITH AIO', ['decision recorded']],
      ARTIFACT_CREATION: ['FOUNDER_STAFF', 'office/renewals', 'record renewed document', ['new version stored']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'road ready · vault', 'propagate', ['Road Ready current', 'old version superseded']],
      COMPLETION: ['CLIENT', 'portal/renewals', 'view', ['RENEWED']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open document', ['renewed version current']],
      NEXT_STEP: ['CLIENT', 'portal/renewals', 'horizon', ['next expiration listed']],
    },
  },
  structure: { routes: [['CLIENT', 'portal/renewals'], ['CLIENT', 'portal/insurance/renewals'], ['FOUNDER_STAFF', 'office/renewals']], data: ['renewalTypes.ts', 'renewalConfig.ts', 'renewalService.ts'], evidence: ['docs/RENEWAL_SYSTEM.md', 'src/renewals/renewalConfig.ts'] },
  functional_pct: null,
  activation: 'renewals in catalog (permits-taxes-compliance)',
  code: ['src/renewals/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.ROAD_READY', 'AIO.VAULT', 'AIO.INSURANCE', 'AIO.IFTA_REGISTRATION'],
});
