/**
 * AIO CLIENT MIGRATION + CLIENT ACTIVATION — experience contracts for the bridge from "known to AIO" to "active
 * digital client" (P0.AIO.CLIENT-MIGRATION-ACTIVATION-AND-OFFICE-PROVISIONING-ARCHITECTURE1).
 *
 * Existing-client onboarding is NOT account creation: it is reconciliation between AIO's existing knowledge and the
 * client's current business truth. The generic mechanics live in ../../client-lifecycle.ts; the AIO mapping onto
 * existing records lives in ./client-migration.ts. No page is implemented by this contract.
 */
import { aioFeature, ih } from './kit.js';

export const AIO_CLIENT_MIGRATION = aioFeature({
  id: 'AIO.CLIENT_MIGRATION',
  name: 'Client Migration Intake + Review (founder / staff)',
  family: 'AIO OFFICE role projection (office/clients/*)',
  purpose: 'Turn an existing client’s physical and digital file into a reviewed, provenance-traced client profile and Vault — without the client rebuilding anything and without any unreviewed fact becoming truth.',
  promise: 'Everything AIO already knows about a client is organised once, checked by a person, and traceable to the page it came from.',
  value: 'Existing clients start from what AIO knows; staff never re-key a folder by hand; no duplicate businesses.',
  actors: ['FOUNDER_STAFF', 'SYSTEM', 'CLIENT'],
  secondary: ['founder (approves migrations)', 'staff (uploads + reviews)', 'existing client (confirms later, in AIO.CLIENT_ACTIVATION)'],
  entries: {
    public: { applicable: false, reason: 'Internal office workflow; clients never see migration intake.' },
    client: ['(later) Activation invitation — “Your AIO office is ready”', 'portal activation route (AIO.CLIENT_ACTIVATION)', 'invitation link'],
    staff: ['Client Migration Intake', 'office/clients/migration (proposed)', 'NEW MIGRATION BATCH from the client list or Client 360'],
    system: ['migration pipeline', 'batch upload complete'],
  },
  states: [
    ['KNOWN_UNMIGRATED', 'Known — not migrated', 'EMPTY', '—', 'Known to AIO; no digital file yet', { FOUNDER_STAFF: 'START MIGRATION' }],
    ['MIGRATION_IN_PROGRESS', 'Migrating', 'ACTIVE', '—', 'Files uploading / processing'],
    ['PARTIAL_BATCH', 'Partial batch', 'BLOCKED', '—', 'Some files failed — review the rest or re-upload', { FOUNDER_STAFF: 'SEE FAILED FILES' }],
    ['AMBIGUOUS_MATCH', 'Which business is this?', 'BLOCKED', '—', 'Identity is ambiguous — staff must choose', { FOUNDER_STAFF: 'RESOLVE MATCH' }],
    ['MIGRATION_REVIEW_REQUIRED', 'Review required', 'REVIEW', '—', 'Facts, conflicts and stale items wait for a decision', { FOUNDER_STAFF: 'REVIEW MIGRATION' }],
    ['READY_TO_APPROVE', 'Ready to approve', 'APPROVAL', '—', 'Every fact decided; identity resolved', { FOUNDER_STAFF: 'APPROVE MIGRATION' }],
    ['PREBUILT', 'Prebuilt — not active', 'COMPLETE', 'Your AIO office is being prepared', 'Profile prepared; client confirmation still required'],
    ['MIGRATION_FAILED', 'Migration failed', 'ERROR', '—', 'Nothing usable extracted — rescan or enter facts by hand'],
    ['SUPERSEDED_BATCH', 'Batch closed', 'ARCHIVED', '—', 'Batch closed into the client’s history'],
  ],
  transitions: [
    ['KNOWN_UNMIGRATED', 'MIGRATION_IN_PROGRESS', 'staff creates a batch and uploads the folder', 'FOUNDER_STAFF'],
    ['MIGRATION_IN_PROGRESS', 'PARTIAL_BATCH', 'some files fail ingest / extraction', 'SYSTEM'],
    ['MIGRATION_IN_PROGRESS', 'AMBIGUOUS_MATCH', 'identity signals disagree', 'SYSTEM'],
    ['MIGRATION_IN_PROGRESS', 'MIGRATION_REVIEW_REQUIRED', 'processing complete', 'SYSTEM'],
    ['PARTIAL_BATCH', 'MIGRATION_REVIEW_REQUIRED', 'staff continues with the readable files', 'FOUNDER_STAFF'],
    ['AMBIGUOUS_MATCH', 'MIGRATION_REVIEW_REQUIRED', 'staff matches to an existing client or creates a new one', 'FOUNDER_STAFF'],
    ['MIGRATION_REVIEW_REQUIRED', 'READY_TO_APPROVE', 'every fact decided, no open conflict', 'FOUNDER_STAFF'],
    ['READY_TO_APPROVE', 'PREBUILT', 'APPROVE MIGRATION (commit gate)', 'FOUNDER_STAFF'],
    ['MIGRATION_IN_PROGRESS', 'MIGRATION_FAILED', 'no file processed', 'SYSTEM'],
    ['MIGRATION_FAILED', 'MIGRATION_IN_PROGRESS', 'staff re-uploads', 'FOUNDER_STAFF'],
    ['PREBUILT', 'SUPERSEDED_BATCH', 'batch closed after commit', 'SYSTEM'],
  ],
  anchors: { start: 'MIGRATION_IN_PROGRESS', success: 'PREBUILT', blocked: 'AMBIGUOUS_MATCH', errors: ['MIGRATION_FAILED'], empty: 'KNOWN_UNMIGRATED', complete: 'SUPERSEDED_BATCH' },
  inputs: [
    ['CLIENT_FILE', 'The client’s whole file (scanned paper, PDFs, photos, old digital folders)', ['UPLOAD FOLDER', 'MULTI-FILE UPLOAD', 'DRAG AND DROP'], 'extraction + Vault'],
    ['CLIENT_SELECTION', 'Which business the batch belongs to (or unknown)', ['SELECT CLIENT', 'UNKNOWN CLIENT'], 'matching'],
    ['STAFF_DECISIONS', 'A decision on every proposed fact', ['CONFIRM', 'EDIT', 'IGNORE', 'MARK STALE', 'NEEDS CLIENT CONFIRMATION', 'RECLASSIFY', 'REJECT EXTRACTION'], 'commit gate'],
  ],
  optional: [['STAFF_KNOWLEDGE', 'Facts staff know without a document (recorded with who supplied them)', ['ADD KNOWN FACT'], 'profile completeness']],
  derivations: [
    ['DUPLICATE', 'duplicate documents', ['sha256', 'client vault hashes'], 'markDuplicates — never re-extracted'],
    ['MATCH', 'client match class', ['DOT', 'MC', 'EIN', 'VIN', 'name / phone / email / address'], 'proposeClientMatch — never MATCH_CONFIRMED without staff'],
    ['CONFLICTS', 'conflicting values per field', ['proposed facts'], 'analyzeConflicts'],
    ['STALENESS', 'stale / possibly stale evidence', ['expiration date', 'document date', 'freshness window'], 'assessStaleness'],
    ['COMMIT_PLAN', 'canonical writes', ['decided facts', 'field registry'], 'planMigrationCommit — PREBUILT, never ACTIVE'],
  ],
  reviews: [
    ['FACT_REVIEW', 'MIGRATION_REVIEW_REQUIRED', 'Is each proposed fact true today?', ['CONFIRM', 'EDIT', 'IGNORE', 'MARK STALE', 'NEEDS CLIENT CONFIRMATION', 'REJECT EXTRACTION']],
    ['MATCH_REVIEW', 'AMBIGUOUS_MATCH', 'Which business is this?', ['MATCH TO EXISTING', 'CREATE NEW CLIENT']],
    ['APPROVAL', 'READY_TO_APPROVE', 'Approve the migration into a prebuilt office?', ['APPROVE MIGRATION', 'RETURN TO REVIEW']],
  ],
  overrides: [['CREATE_DESPITE_MATCH', 'AMBIGUOUS_MATCH', 'Create a new business although a likely match exists (reason required)', ['CREATE WITH REASON']]],
  artifacts: [
    ['MIGRATED_DOCUMENTS', 'Classified source documents with lineage', 'DOCUMENT', 'migration batch', 'Vault › by document class', ['FOUNDER_STAFF', 'CLIENT']],
    ['MIGRATION_RECORD', 'Batch record: files, decisions, reviewer, approval', 'RECORD', 'migration review', null, ['FOUNDER_STAFF']],
  ],
  vault: 'Vault › document class folders (company, authority, vehicles, drivers, insurance, tax & fuel, permits …)',
  inbox: [['PREBUILT', 'none — the client is told only by the activation invitation (AIO.CLIENT_ACTIVATION)']],
  activity: [['MIGRATION_REVIEW_REQUIRED', 'Migration batch ready for review (staff)'], ['PREBUILT', 'Client prebuilt (staff)']],
  notify: [['MIGRATION_REVIEW_REQUIRED', 'Migration review waiting (staff)'], ['MIGRATION_FAILED', 'Migration failed (staff)']],
  tasks: [['MIGRATION_REVIEW_REQUIRED', 'Review migration batch'], ['AMBIGUOUS_MATCH', 'Resolve client match'], ['PREBUILT', 'Invite client to activate']],
  next: 'PREBUILT client appears in PREBUILT NOT INVITED; staff send the activation invitation (AIO.CLIENT_ACTIVATION).',
  upstream: ['physical / scanned client files', 'staff knowledge', 'existing client records'],
  downstream: ['AIO.VAULT (documents with lineage)', 'AIO.CLIENT_ACTIVATION (invite)', 'client profile + fleet + people records', 'workspace provisioning (PENDING_SETUP)'],
  relationships: [
    ['AIO.VAULT', 'PREBUILT', 'ARCHIVES_TO', 'documents appear in the Vault once the client is active', 'documents filed by class with lineage', { VAULT: 'migrated documents with source batch' }, 'batch → cabinet drawers'],
    ['AIO.CLIENT_ACTIVATION', 'PREBUILT', 'UNLOCKS', 'invitation “Your AIO office is ready” can be sent', 'client moves to PREBUILT NOT INVITED', { OFFICE: 'invite task' }, 'prebuilt office → invitation'],
    ['AIO.OFFICE_OPERATIONS', 'MIGRATION_REVIEW_REQUIRED', 'FEEDS', 'none', 'migration review appears in the founder hub', { OFFICE: 'MIGRATION REVIEW bucket' }, 'batch → review queue'],
  ],
  automations: [['PIPELINE', 'batch upload complete', 'hash · duplicate check · classify · extract · match · stale · conflict · score · propose', 'staff classify and enter facts by hand (STAFF_ENTRY provenance)']],
  public: { applicable: false, reason: 'Internal office workflow; clients never see migration intake.' },
  client: {
    entry_point: 'None during migration — the client meets the result in AIO.CLIENT_ACTIVATION.',
    primary_task: 'None during migration.',
    sees_first: 'Nothing until invited.',
    must_provide: ['nothing during migration'],
    input_methods: ['none'],
    system_already_knows: ['everything staff confirmed from the file'],
    ready_signals: ['activation invitation'],
    needs_you: ['none during migration'],
    under_review: ['AIO is preparing your office (only if invited early)'],
    approves: [],
    completion_looks_like: 'An invitation to review what AIO already knows.',
    artifacts_received: ['none until activation'],
    what_happens_next: 'You are invited to review and confirm.',
  },
  staff: {
    client_context: ['client 360', 'migration batch', 'existing records for the matched business'],
    work_queue: 'Founder hub MIGRATION REVIEW + MIGRATION FAILED / NEEDS REVIEW buckets',
    status_model: [],
    blockers: ['ambiguous identity', 'unresolved conflicts', 'undecided facts', 'unreadable / failed files'],
    missing_inputs: ['current-truth fields not found in the file (shown as missing, never guessed)'],
    system_flags: ['duplicate document', 'stale (expired) evidence', 'conflicting values', 'low confidence'],
    human_review: ['every proposed fact', 'identity match', 'document class'],
    corrections: ['edit value', 'reclassify document', 'reject extraction'],
    approval: ['APPROVE MIGRATION (founder / authorised staff)'],
    overrides: ['create new business despite a likely match (reason recorded)'],
    operational_actions: ['NEW BATCH', 'UPLOAD', 'CONFIRM', 'EDIT', 'IGNORE', 'MARK STALE', 'NEEDS CLIENT CONFIRMATION', 'RECLASSIFY', 'MATCH TO EXISTING', 'CREATE NEW CLIENT', 'REJECT EXTRACTION', 'APPROVE MIGRATION'],
    artifact_generation: ['vault lineage records', 'migration record'],
    completion: 'Client PREBUILT with every committed field traceable to its source.',
    hub_buckets: { NEEDS_REVIEW: ['MIGRATION_REVIEW_REQUIRED', 'READY_TO_APPROVE'], BLOCKED: ['AMBIGUOUS_MATCH', 'PARTIAL_BATCH', 'MIGRATION_FAILED'], COMPLETE: ['PREBUILT'] },
    mirror_not_copy: 'Migration is staff-only; the client sees the reviewed result as a short review flow, never the batch.',
  },
  system: {
    ingestion: ['folder / multi-file upload; PDF · JPG · JPEG · PNG (+ office documents where the stack supports them)', 'sha256 per file'],
    validation: ['file policy (type, size)', 'duplicate hash', 'provenance completeness per fact'],
    derivation: ['document class', 'facts with page / region', 'match class', 'conflicts', 'staleness', 'confidence', 'proposed mutations'],
    state_transitions: ['batch states CREATED → UPLOADING → PROCESSING → (PARTIAL) → REVIEW_REQUIRED → APPROVED', 'client lifecycle KNOWN_UNMIGRATED → MIGRATION_IN_PROGRESS → MIGRATION_REVIEW_REQUIRED → PREBUILT'],
    next_cycle_creation: 'Historical archive keeps migrating in later batches; current truth first.',
    failure_handling: ['UNREADABLE_DOCUMENT', 'DUPLICATE_DOCUMENT', 'AMBIGUOUS_CLIENT_MATCH', 'CONFLICTING_FACTS', 'UNSUPPORTED_DOCUMENT', 'EXTRACTION_FAILED', 'PARTIAL_BATCH — each listed, none silent'],
    parsing: ['document class detection + field / entity extraction proposals only — no mutation before review'],
  },
  metaphor: 'THE CLIENT FILE ON THE DESK',
  metaphor2: 'sorting a folder into a verified cabinet',
  archetype: ['PIPELINE', 'MATCHING_BOARD', 'CASE_FILE'],
  object: 'THE MIGRATION BATCH (client file → proposed facts → decisions)',
  objects: ['source documents with class + lineage', 'proposed facts with confidence', 'conflict groups', 'match candidates'],
  composition: ['Header: client / candidate · batch · processing status · match status · document count.', 'Summary: profile facts · vehicles · drivers · services · documents · conflicts · stale · unresolved.', 'One primary completion: APPROVE MIGRATION.'],
  hierarchy: {
    CLIENT: ih('(none during migration)', 'not visible', 'none', 'none', 'none', 'none', 'invitation received later'),
    FOUNDER_STAFF: ih('Is this client’s file reviewed and safe to prepare?', 'Batch status + match status', 'Decide every proposed fact', 'Conflicts · stale · unresolved counts', 'Ambiguous identity / open conflicts', 'APPROVE MIGRATION', 'PREBUILT with full lineage'),
  },
  grammar: [['UPLOAD', 'FOUNDER_STAFF', 'add the client file', 'MIGRATION_IN_PROGRESS'], ['CONFIRM', 'FOUNDER_STAFF', 'accept a fact'], ['MATCH TO EXISTING', 'FOUNDER_STAFF', 'resolve identity', 'MIGRATION_REVIEW_REQUIRED'], ['APPROVE MIGRATION', 'FOUNDER_STAFF', 'commit verified facts', 'PREBUILT']],
  emotion: { FOUNDER_STAFF: 'The whole folder is in, sorted, and nothing becomes truth until I say so.' , CLIENT: 'AIO already knows my business.' },
  density: 'DENSE',
  viewports: { mobile: ['review triage: conflicts first', 'stacked fact cards'], tablet: ['documents | facts', 'two columns'], desktop: ['document viewer + fact table + match panel', 'three columns'] },
  ctas: { public: null, client: 'ACTIVATE YOUR OFFICE (via the invitation, AIO.CLIENT_ACTIVATION)', staff: 'APPROVE MIGRATION' },
  avoid: ['auto-committing extraction', 'auto-merging uncertain identities', 'creating a duplicate business', 'deleting historical files', 'treating an empty vault as an empty profile', 'requiring the full archive before activation'],
  e2e: {
    journey: 'CLIENT FOLDER → UPLOAD BATCH → PIPELINE → MATCH → REVIEW → APPROVE MIGRATION → PREBUILT → INVITE',
    not_applicable: { PUBLIC_DISCOVERY: 'internal office workflow', CLIENT_ENTRY: 'the client is not involved until activation (AIO.CLIENT_ACTIVATION)', CLIENT_ACTION: 'the client is not involved until activation', CLIENT_APPROVAL: 'client confirmation happens in AIO.CLIENT_ACTIVATION' },
    expect: {
      SYSTEM_PROCESSING: ['SYSTEM', 'migration pipeline', 'hash, classify, extract, match, score', ['documents classified', 'facts proposed with provenance', 'no canonical write']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'Client Migration Review', 'decide every fact; resolve identity', ['no PENDING fact', 'no open conflict', 'MATCH_CONFIRMED']],
      ARTIFACT_CREATION: ['SYSTEM', 'Vault', 'file documents with lineage', ['vault lineage per document', 'superseded documents kept']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'client records', 'commit verified facts', ['writes carry fact id + reviewer', 'workspaces PENDING_SETUP']],
      COMPLETION: ['FOUNDER_STAFF', 'Client Migration Review', 'APPROVE MIGRATION', ['lifecycle PREBUILT', 'not counted active']],
      ARCHIVE: ['SYSTEM', 'migration record', 'close batch', ['batch closed into history']],
      NEXT_STEP: ['FOUNDER_STAFF', 'founder hub', 'invite client', ['PREBUILT NOT INVITED bucket']],
    },
  },
  structure: { routes: [['FOUNDER_STAFF', 'office/clients/migration (proposed)']], data: ['migration batch / source document / extracted fact / review decision (proposed tables)', 'Vault documents', 'client / organisation records'], evidence: ['docs/aio/client-migration/AIO_CLIENT_MIGRATION_ARCHITECTURE.md (SITE00)'] },
  functional_pct: null,
  activation: 'architecture only (no route, no pipeline in AIO yet)',
  code: [],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.CLIENT_ACTIVATION', 'AIO.VAULT', 'AIO.OFFICE_OPERATIONS', 'AIO.MY_OFFICE'],
});

export const AIO_CLIENT_ACTIVATION = aioFeature({
  id: 'AIO.CLIENT_ACTIVATION',
  name: 'Client Activation — review what AIO knows, confirm, enter the office',
  family: 'F18 ACCOUNT · F05 MY OFFICE threshold',
  purpose: 'Let an existing client activate their prebuilt office by reviewing what AIO already knows, reporting what changed, and confirming — instead of rebuilding their business from zero.',
  promise: 'We already know your business. Check it, tell us what changed, and your office is ready.',
  value: 'Minutes of review instead of a blank onboarding; AIO starts from verified truth.',
  actors: ['CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['existing client (prebuilt)', 'new client (converges at confirmation)', 'staff (invite + reconcile changes)'],
  entries: {
    public: { applicable: false, reason: 'Invitation-only: the activation link is the entry; there is no public page.' },
    client: ['Activation invitation — ACTIVATE YOUR OFFICE', 'portal activation route (proposed)', 'secure single-use link'],
    staff: ['Client 360 / founder hub — SEND INVITATION', 'office/clients/:clientId', 'PREBUILT NOT INVITED bucket'],
    system: ['activation service', 'invitation accepted'],
  },
  states: [
    ['PREBUILT', 'Prebuilt', 'EMPTY', '—', 'Prebuilt — invite when ready', { FOUNDER_STAFF: 'SEND INVITATION' }],
    ['INVITED', 'Invitation sent', 'ACTIVE', 'Activate your office', 'Invitation sent', { CLIENT: 'ACTIVATE YOUR OFFICE', FOUNDER_STAFF: 'RESEND' }],
    ['CLIENT_REVIEW', 'Reviewing', 'ACTIVE', 'Here’s what AIO already knows', 'Client reviewing', { CLIENT: 'CONTINUE' }],
    ['WHAT_CHANGED', 'What changed?', 'ACTIVE', 'Tell us what changed', 'Client reporting changes', { CLIENT: 'NOTHING CHANGED' }],
    ['CLIENT_CONFIRMATION_REQUIRED', 'Confirm', 'APPROVAL', 'Confirm and enter your office', 'Waiting for client', { CLIENT: 'CONFIRM & ENTER MY OFFICE' }],
    ['ACTIVE', 'Active', 'COMPLETE', 'Your AIO office', 'Active client'],
    ['CHANGES_AWAITING_STAFF', 'Changes being reconciled', 'REVIEW', 'AIO is updating what you told us', 'Reconcile client changes'],
    ['ACTIVATION_EXPIRED', 'Link expired', 'ERROR', 'This link expired — ask AIO for a new one', 'Re-invite'],
    ['INVITE_DELIVERY_FAILED', 'Invitation not delivered', 'BLOCKED', '—', 'Fix the email and resend', { FOUNDER_STAFF: 'FIX EMAIL' }],
    ['PAUSED', 'Paused', 'ARCHIVED', 'Your office is paused', 'Paused'],
  ],
  transitions: [
    ['PREBUILT', 'INVITED', 'staff sends the invitation', 'FOUNDER_STAFF'],
    ['INVITED', 'INVITE_DELIVERY_FAILED', 'bounce / undeliverable', 'SYSTEM'],
    ['INVITE_DELIVERY_FAILED', 'INVITED', 'staff fixes the email and resends', 'FOUNDER_STAFF'],
    ['INVITED', 'ACTIVATION_EXPIRED', 'link expires unused', 'SYSTEM'],
    ['ACTIVATION_EXPIRED', 'INVITED', 'staff re-invites (new token)', 'FOUNDER_STAFF'],
    ['INVITED', 'CLIENT_REVIEW', 'client verifies the link and sets a password', 'CLIENT'],
    ['CLIENT_REVIEW', 'WHAT_CHANGED', 'sections reviewed', 'CLIENT'],
    ['WHAT_CHANGED', 'CLIENT_CONFIRMATION_REQUIRED', 'changes captured (or nothing changed)', 'CLIENT'],
    ['CLIENT_CONFIRMATION_REQUIRED', 'ACTIVE', 'CONFIRM & ENTER MY OFFICE', 'CLIENT'],
    ['ACTIVE', 'CHANGES_AWAITING_STAFF', 'client-reported changes need staff', 'SYSTEM'],
    ['CHANGES_AWAITING_STAFF', 'ACTIVE', 'staff reconciled', 'FOUNDER_STAFF'],
    ['ACTIVE', 'PAUSED', 'relationship paused', 'FOUNDER_STAFF'],
  ],
  anchors: { start: 'INVITED', success: 'ACTIVE', blocked: 'INVITE_DELIVERY_FAILED', errors: ['ACTIVATION_EXPIRED'], empty: 'PREBUILT', complete: 'ACTIVE' },
  inputs: [
    ['ACTIVATION', 'Verify the invitation and set your own password (or sign in by magic link)', ['SET PASSWORD', 'MAGIC LINK'], 'auth identity'],
    ['SECTION_REVIEW', 'Company · People · Vehicles · Active services · Documents', ['LOOKS RIGHT', 'NEEDS AN UPDATE', 'I’M NOT SURE'], 'client review'],
    ['WHAT_CHANGED', 'What changed since AIO last saw your file', ['BOUGHT A TRUCK', 'SOLD A TRUCK', 'ADDED A DRIVER', 'REMOVED A DRIVER', 'ADDRESS CHANGED', 'INSURANCE CHANGED', 'OWNERSHIP CHANGED', 'CONTACT INFO CHANGED', 'NOTHING CHANGED', 'SOMETHING ELSE'], 'current truth'],
    ['CONSENTS', 'Required acknowledgements', ['ACCEPT'], 'activation'],
  ],
  derivations: [
    ['COMPLETENESS', 'business profile · document vault · client review (three separate measures)', ['confirmed facts', 'vault lineage', 'section answers'], 'computeCompleteness'],
    ['ACTIVATION_GATE', 'can the client be counted active?', ['eight activation conditions'], 'evaluateActivation / isCountedActive'],
    ['WORKSPACES', 'workspace states after activation', ['staff-confirmed service relationships'], 'provisionWorkspaces'],
  ],
  reviews: [['CHANGE_RECONCILIATION', 'CHANGES_AWAITING_STAFF', 'Apply the client’s reported change?', ['APPLY', 'ASK CLIENT', 'DECLINE WITH NOTE']]],
  approvals: [['CLIENT_CONFIRMATION', 'CLIENT_CONFIRMATION_REQUIRED', 'Is this your business today?', ['CONFIRM & ENTER MY OFFICE', 'GO BACK']]],
  overrides: [['RESEND', 'INVITE_DELIVERY_FAILED', 'Fix the address and resend', ['RESEND']]],
  artifacts: [['ACTIVATION_RECORD', 'Activation record (confirmed sections, reported changes, consents, timestamps)', 'RECORD', 'activation', null, ['FOUNDER_STAFF', 'CLIENT']]],
  vault: null,
  inbox: [['CHANGES_AWAITING_STAFF', 'AIO is updating what you told us'], ['ACTIVE', 'Welcome to your AIO office']],
  activity: [['ACTIVE', 'Client activated'], ['WHAT_CHANGED', 'Client reported a change']],
  notify: [['INVITED', 'Your AIO office is ready (company name · AIO client ID · secure link — nothing else)'], ['ACTIVATION_EXPIRED', 'Activation link expired (staff)']],
  tasks: [['CHANGES_AWAITING_STAFF', 'Reconcile client-reported change'], ['INVITE_DELIVERY_FAILED', 'Fix client email'], ['ACTIVATION_EXPIRED', 'Re-invite client']],
  next: 'Client enters YOUR AIO OFFICE: ACTIVE WITH AIO · WE ALSO KNOW ABOUT · WORKSPACES THAT MAY HELP.',
  upstream: ['AIO.CLIENT_MIGRATION (prebuilt profile)', 'new-client intake (AIO.GET_STARTED)'],
  downstream: ['AIO.MY_OFFICE (client office hub)', 'workspaces (PENDING_SETUP → ACTIVE)', 'founder hub (ACTIVE count)', 'workspace expansion (after activation)'],
  relationships: [
    ['AIO.MY_OFFICE', 'ACTIVE', 'OPENS', 'YOUR AIO OFFICE opens with active workspaces', 'client counted active', { MY_OFFICE: 'ACTIVE WITH AIO · WE ALSO KNOW ABOUT · WORKSPACES THAT MAY HELP' }, 'review → office'],
    ['AIO.OFFICE_OPERATIONS', 'CHANGES_AWAITING_STAFF', 'FEEDS', 'AIO is updating', 'reconciliation work item', { OFFICE: 'client change queue' }, 'change → work item'],
    ['AIO.ACCOUNT', 'INVITED', 'DEPENDS_ON', 'set your own password', 'auth identity linked to the business', { ACCOUNT: 'login email + password set by the client' }, 'link → account'],
  ],
  public: { applicable: false, reason: 'Invitation-only: the activation link is the entry; there is no public page.' },
  client: {
    entry_point: 'Activation invitation link',
    primary_task: 'Check what AIO already knows, say what changed, confirm.',
    sees_first: 'WELCOME — HERE’S WHAT AIO ALREADY KNOWS (company name, AIO client ID).',
    must_provide: ['own password (set by the client)', 'a response per section', 'what changed', 'required acknowledgements'],
    input_methods: ['LOOKS RIGHT / NEEDS AN UPDATE / I’M NOT SURE per section', 'what-changed shortcuts'],
    system_already_knows: ['company identity', 'people', 'vehicles', 'active services', 'documents on file'],
    ready_signals: ['every section answered', 'changes captured'],
    needs_you: ['sections not yet answered', 'updates requested but not described'],
    under_review: ['changes AIO is reconciling'],
    approves: ['CONFIRM & ENTER MY OFFICE'],
    completion_looks_like: 'YOUR AIO OFFICE — ACTIVE WITH AIO.',
    artifacts_received: ['activation record'],
    what_happens_next: 'Your workspaces open; AIO applies the changes you reported.',
  },
  staff: {
    client_context: ['prebuilt profile', 'invitation status', 'section answers', 'reported changes'],
    work_queue: 'Founder hub: PREBUILT NOT INVITED · INVITATION SENT · WAITING FOR CLIENT · ACTIVE',
    status_model: [],
    blockers: ['missing login email', 'undelivered invitation', 'expired link'],
    missing_inputs: ['client email', 'client answers'],
    system_flags: ['link expired', 'delivery failed', 'client unsure about a section', 'client disputes a fact'],
    human_review: ['client-reported changes that are not low-risk'],
    corrections: ['apply / ask / decline a reported change'],
    approval: ['none — the client confirms their own truth'],
    overrides: ['resend / re-invite'],
    operational_actions: ['SEND INVITATION', 'RESEND', 'RECONCILE CHANGE'],
    artifact_generation: ['activation record'],
    completion: 'Client ACTIVE and counted active.',
    hub_buckets: { AWAITING_CLIENT: ['INVITED', 'CLIENT_REVIEW', 'WHAT_CHANGED', 'CLIENT_CONFIRMATION_REQUIRED'], NEEDS_REVIEW: ['CHANGES_AWAITING_STAFF'], BLOCKED: ['INVITE_DELIVERY_FAILED', 'ACTIVATION_EXPIRED'], COMPLETE: ['ACTIVE'] },
    mirror_not_copy: 'Staff see the invitation and confirmation status and the changes to reconcile, not the client’s review screens.',
  },
  system: {
    ingestion: ['invitation acceptance', 'section answers', 'reported changes', 'consents'],
    validation: ['single-use token (hash stored), expiry', 'every required section answered', 'NEEDS AN UPDATE carries a change', 'consents accepted'],
    derivation: ['completeness (three measures)', 'activation conditions'],
    state_transitions: ['lifecycle PREBUILT → INVITED → CLIENT_CONFIRMATION_REQUIRED → ACTIVE'],
    next_cycle_creation: 'Reported changes create reconciliation work; workspaces move PENDING_SETUP → ACTIVE.',
    failure_handling: ['INVITE_DELIVERY_FAILED', 'CLIENT_EMAIL_MISSING', 'ACTIVATION_EXPIRED', 'CLIENT_DECLINES_FACT — none silent'],
  },
  metaphor: 'THE KEYS TO A PREPARED OFFICE',
  metaphor2: 'a short walk-through before you move in',
  archetype: ['THRESHOLD', 'CHECKLIST', 'DECISION_WINDOW'],
  object: 'WHAT AIO ALREADY KNOWS (the prepared office)',
  objects: ['section cards (company · people · vehicles · services · documents)', 'what-changed shortcuts', 'the confirm action'],
  composition: ['One section per screen on mobile; each section is a summary with three answers, never a form.', 'Confirm is the single decision; expansion appears only after entering the office.'],
  hierarchy: {
    CLIENT: ih('Is this still my business?', 'Section checklist', 'Answer each section', 'Documents AIO has', 'Updates not yet described', 'CONFIRM & ENTER MY OFFICE', 'YOUR AIO OFFICE'),
    FOUNDER_STAFF: ih('Has the client confirmed?', 'Invitation + confirmation status', 'Unblock invitations; reconcile changes', 'Reported changes', 'Delivery failed / expired', 'RESEND / RECONCILE', 'Client counted active'),
  },
  grammar: [['ACTIVATE', 'CLIENT', 'verify the link and set a password', 'CLIENT_REVIEW'], ['LOOKS RIGHT', 'CLIENT', 'accept a section'], ['NEEDS AN UPDATE', 'CLIENT', 'report a change'], ['CONFIRM & ENTER MY OFFICE', 'CLIENT', 'confirm current truth', 'ACTIVE']],
  emotion: { CLIENT: 'They already know my business — I just check it.', FOUNDER_STAFF: 'I know exactly who is active and who is still waiting.' },
  density: 'SPARSE',
  viewports: { mobile: ['one section per screen', 'stacked'], tablet: ['section list + current section', 'two columns'], desktop: ['section rail + section summary', 'two columns'] },
  ctas: { public: null, client: 'CONFIRM & ENTER MY OFFICE', staff: 'SEND INVITATION' },
  avoid: ['blank onboarding forms for existing clients', 'field-by-field editing when a section is right', 'fake completeness', 'profile data in the invitation email', 'emailed or texted passwords', 'upsell cards inside the review'],
  e2e: {
    journey: 'PREBUILT → INVITE → ACTIVATE (own password) → REVIEW → WHAT CHANGED → CONFIRM → ACTIVE → YOUR AIO OFFICE',
    not_applicable: { PUBLIC_DISCOVERY: 'invitation-only', ARCHIVE: 'the activation record stays with the client (no archive step)' },
    expect: {
      CLIENT_ENTRY: ['CLIENT', 'activation link', 'verify + set password', ['auth identity linked', 'no password ever sent']],
      CLIENT_ACTION: ['CLIENT', 'review flow', 'answer sections + what changed', ['every required section answered']],
      SYSTEM_PROCESSING: ['SYSTEM', 'activation service', 'route changes; compute completeness', ['low-risk changes applied with history', 'others awaiting staff']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'client change queue', 'reconcile changes', ['changes reconciled']],
      CLIENT_APPROVAL: ['CLIENT', 'confirm', 'CONFIRM & ENTER MY OFFICE', ['CLIENT_CONFIRMED + CLIENT_ACTIVATED events']],
      ARTIFACT_CREATION: ['SYSTEM', 'activation record', 'record answers + consents', ['activation record']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'workspaces', 'PENDING_SETUP → ACTIVE', ['WORKSPACE_PROVISIONED events']],
      COMPLETION: ['CLIENT', 'YOUR AIO OFFICE', 'enter office', ['lifecycle ACTIVE', 'counted active']],
      NEXT_STEP: ['CLIENT', 'office hub', 'see active workspaces + relevant ones', ['expansion only after activation']],
    },
  },
  structure: { routes: [['CLIENT', 'portal activation (proposed)'], ['FOUNDER_STAFF', 'office/clients/:clientId']], data: ['activation invitation (token hash, expiry, state)', 'client review answers', 'client changes', 'consents', 'client lifecycle'], evidence: ['docs/aio/client-migration/AIO_EXISTING_CLIENT_FIRST_LOGIN.md (SITE00)'] },
  functional_pct: null,
  activation: 'architecture only (no activation route or invitation service in AIO yet)',
  code: [],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.CLIENT_MIGRATION', 'AIO.ACCOUNT', 'AIO.MY_OFFICE', 'AIO.GET_STARTED'],
});
