/**
 * AIO money families (F10 FINANCES · F11 FACTORING · F12 INSURANCE · F13 BOOKKEEPING). Boundaries quoted from
 * source: separate financial domains are never combined (CLIENT_COMMAND_CENTER.md); factoring is assistance /
 * partner — `directFactoringEnabled = false` (FACTORING_SYSTEM.md); insurance is assistance / referral — AIO does not
 * bind, collect premiums or issue COIs (INSURANCE_SYSTEM.md); bookkeeping is not a CPA / tax preparer and IFTA
 * bookkeeping support ≠ IFTA filing (BOOKKEEPING_SERVICE.md).
 */
import { aioFeature, ih } from './kit.js';

export const AIO_FINANCES = aioFeature({
  id: 'AIO.FINANCES',
  name: 'Finances — Money / Billing / Quotes',
  family: 'F10 FINANCES',
  purpose: 'Show the client what they owe AIO for services, quotes awaiting acceptance, and payments — as one honest service-fee ledger, separate from freight, factoring and brokerage money.',
  promise: 'Always know what AIO services cost and what is paid.',
  value: 'Quotes, invoices and payments in one place without mixing freight or factoring money.',
  actors: ['CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['payment provider'],
  entries: {
    public: { applicable: false, reason: 'Pricing is shown on each public service page; the ledger itself is authenticated.' },
    client: ['Money', 'portal/money · portal/billing/* · portal/quotes/*', 'quote ready / invoice due'],
    staff: ['Office billing', 'office/* billing', 'quote / invoice issued'],
    system: ['billing engine', 'service accepted / completed'],
  },
  states: [
    ['NOTHING_DUE', 'Nothing due', 'EMPTY', 'You are all paid up', 'No open items'],
    ['QUOTE_PENDING', 'Quote to review', 'APPROVAL', 'Accept your quote to start the service', 'Awaiting acceptance', { CLIENT: 'ACCEPT QUOTE', FOUNDER_STAFF: 'FOLLOW UP' }],
    ['INVOICE_OPEN', 'Invoice open', 'ACTIVE', 'Invoice due {date}', 'Open invoice'],
    ['OVERDUE', 'Overdue', 'BLOCKED', 'An invoice is overdue', 'Overdue'],
    ['PAYMENT_PROCESSING', 'Processing', 'REVIEW', 'Payment processing', 'Processing'],
    ['PAID', 'Paid', 'COMPLETE', 'Paid — receipt available', 'Paid'],
    ['ARCHIVED', 'Archived', 'ARCHIVED', 'Past invoices', 'Closed'],
    ['PAYMENT_FAILED', 'Payment failed', 'ERROR', 'Payment failed — update method', 'Failed'],
  ],
  transitions: [
    ['NOTHING_DUE', 'QUOTE_PENDING', 'quote issued', 'FOUNDER_STAFF'],
    ['QUOTE_PENDING', 'INVOICE_OPEN', 'quote accepted / service billed', 'CLIENT'],
    ['INVOICE_OPEN', 'PAYMENT_PROCESSING', 'client pays', 'CLIENT'],
    ['INVOICE_OPEN', 'OVERDUE', 'due date passes', 'SYSTEM'],
    ['OVERDUE', 'PAYMENT_PROCESSING', 'client pays', 'CLIENT'],
    ['PAYMENT_PROCESSING', 'PAID', 'payment confirmed', 'SYSTEM'],
    ['PAYMENT_PROCESSING', 'PAYMENT_FAILED', 'payment fails', 'SYSTEM'],
    ['PAYMENT_FAILED', 'INVOICE_OPEN', 'method updated', 'CLIENT'],
    ['PAID', 'ARCHIVED', 'period closes', 'SYSTEM'],
  ],
  anchors: { start: 'QUOTE_PENDING', success: 'PAID', blocked: 'OVERDUE', errors: ['PAYMENT_FAILED'], empty: 'NOTHING_DUE', complete: 'ARCHIVED' },
  inputs: [['QUOTE_ACCEPTANCE', 'Quote acceptance', ['ACCEPT', 'ASK A QUESTION'], 'service start'], ['PAYMENT', 'Payment', ['PAY NOW', 'SAVED METHOD'], 'invoice settlement']],
  derivations: [['TOTALS', 'service-fee balance', ['invoices', 'payments'], 'billingCalculator.ts (money in minor units)'], ['PRICING', 'service price', ['service', 'plan'], 'servicePricingConfig.ts']],
  reviews: [['QUOTE_PREP', 'QUOTE_PENDING', 'Issue quote', ['ISSUE', 'REVISE']]],
  approvals: [['ACCEPT_QUOTE', 'QUOTE_PENDING', 'Accept quote?', ['ACCEPT', 'ASK']]],
  overrides: [['CREDIT', 'INVOICE_OPEN', 'Apply credit / waive', ['CREDIT WITH NOTE']]],
  artifacts: [['QUOTE', 'Service quote', 'DOCUMENT', 'billing', 'VAULT › Tax & Financial › Billing'], ['INVOICE', 'Service invoice', 'INVOICE', 'billing', 'VAULT › Tax & Financial › Billing'], ['RECEIPT', 'Payment receipt', 'RECEIPT', 'payment provider', 'VAULT › Tax & Financial › Billing']],
  vault: 'VAULT › Tax & Financial › Billing',
  inbox: [['QUOTE_PENDING', 'Quote ready for {service}'], ['OVERDUE', 'Invoice overdue']],
  activity: [['INVOICE_OPEN', 'Quote accepted'], ['PAID', 'Payment received']],
  notify: [['INVOICE_OPEN', 'Invoice due {date}'], ['PAYMENT_FAILED', 'Payment failed']],
  tasks: [['OVERDUE', 'Follow up overdue invoice for {client}']],
  next: 'Accepted quotes start their service; paid invoices archive by period.',
  upstream: ['every priced AIO service (quotes / completions)'],
  downstream: ['AIO.SERVICES (accepted quote starts service)', 'AIO.VAULT', 'AIO.BOOKKEEPING'],
  relationships: [['AIO.SERVICES', 'INVOICE_OPEN', 'UNLOCKS', 'the quoted service starts', 'work item can begin', { SERVICES: 'request moves to in progress' }, 'quote card turns into service progress']],
  public: { applicable: false, reason: 'Pricing relationships are defined on each service’s public perspective.' },
  client: {
    entry_point: 'Money',
    primary_task: 'Accept quotes and pay AIO invoices.',
    sees_first: 'Balance due and any quote awaiting acceptance.',
    must_provide: ['quote acceptance', 'payment'],
    input_methods: ['ACCEPT', 'PAY NOW', 'SAVED METHOD'],
    system_already_knows: ['services in progress', 'payment methods'],
    ready_signals: ['balance', 'due dates'],
    needs_you: ['quotes to accept', 'overdue invoices', 'failed payments'],
    under_review: ['payment processing'],
    approves: ['quotes'],
    completion_looks_like: 'Paid with receipt.',
    artifacts_received: ['Service quote', 'Service invoice', 'Payment receipt'],
    what_happens_next: 'Accepted quote starts the service.',
  },
  staff: {
    client_context: ['services + quotes', 'payment history'],
    work_queue: 'Billing queue',
    status_model: [],
    blockers: ['unaccepted quotes', 'overdue'],
    missing_inputs: ['payment method'],
    system_flags: ['failed payment', 'overdue'],
    human_review: ['quote preparation'],
    corrections: ['revise quote', 'credit'],
    approval: ['client quote acceptance'],
    overrides: ['credit / waive with note'],
    operational_actions: ['ISSUE QUOTE', 'SEND INVOICE', 'APPLY CREDIT'],
    artifact_generation: ['quotes', 'invoices'],
    completion: 'Paid.',
    hub_buckets: { AWAITING_CLIENT: ['QUOTE_PENDING', 'INVOICE_OPEN'], BLOCKED: ['OVERDUE', 'PAYMENT_FAILED'], COMPLETE: ['PAID'] },
    mirror_not_copy: 'Staff see receivables across clients; clients see their own ledger.',
  },
  system: {
    ingestion: ['quotes', 'service completions', 'payments'],
    validation: ['money in minor units', 'domain separation (no freight / factoring / brokerage money)'],
    derivation: ['balances'],
    state_transitions: ['quote → invoice → paid → archived'],
    next_cycle_creation: 'Recurring plans (e.g. bookkeeping) invoice each period.',
    failure_handling: ['failed payment → PAYMENT_FAILED + retry'],
  },
  metaphor: 'SERVICE LEDGER',
  metaphor2: 'one honest bill',
  archetype: ['LEDGER', 'DECISION_WINDOW'],
  object: 'THE BALANCE (service fees due)',
  objects: ['quotes', 'invoices', 'receipts'],
  composition: ['Balance leads; quotes awaiting acceptance appear as decisions.', 'Freight / factoring / brokerage money never appears here.'],
  hierarchy: {
    CLIENT: ih('What do I owe AIO, and what needs accepting?', 'Balance due', 'Accept / pay', 'Upcoming invoices', 'Overdue / failed', 'ACCEPT QUOTE / PAY', 'Paid with receipt'),
    FOUNDER_STAFF: ih('What is outstanding?', 'Receivables', 'Quote / invoice / follow up', 'Ageing', 'Overdue', 'SEND INVOICE', 'Paid'),
  },
  grammar: [['ACCEPT QUOTE', 'CLIENT', 'accept a quote', 'INVOICE_OPEN'], ['PAY', 'CLIENT', 'pay an invoice', 'PAYMENT_PROCESSING'], ['ISSUE QUOTE', 'FOUNDER_STAFF', 'issue', 'QUOTE_PENDING']],
  emotion: { CLIENT: 'I know exactly what I am paying AIO for.', FOUNDER_STAFF: 'I see every open balance.' },
  density: 'BALANCED',
  viewports: { mobile: ['balance + next decision', 'stacked'], tablet: ['ledger + detail', 'two columns'], desktop: ['ledger table', 'table + panel'] },
  ctas: { public: null, client: 'PAY NOW', staff: 'SEND INVOICE' },
  avoid: ['combining freight / factoring / brokerage money with service fees', 'hidden fees'],
  e2e: {
    journey: 'QUOTE → ACCEPT → INVOICE → PAY → RECEIPT',
    not_applicable: { PUBLIC_DISCOVERY: 'no public ledger (pricing on service pages)' },
    expect: {
      CLIENT_ENTRY: ['CLIENT', 'portal/money', 'open', ['balance leads']],
      CLIENT_ACTION: ['CLIENT', 'portal/billing', 'pay invoice', ['processing']],
      SYSTEM_PROCESSING: ['SYSTEM', 'billing engine', 'record payment', ['balance updated']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office billing', 'issue quote', ['quote sent']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/quotes', 'accept quote', ['service starts']],
      ARTIFACT_CREATION: ['SYSTEM', 'billing', 'receipt', ['receipt available']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'services', 'start service', ['request in progress']],
      COMPLETION: ['CLIENT', 'portal/money', 'view', ['PAID']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'billing folder', ['invoice + receipt filed']],
      NEXT_STEP: ['CLIENT', 'portal/money', 'view', ['next invoice / nothing due']],
    },
  },
  structure: { routes: [['CLIENT', 'portal/money · portal/billing/* · portal/quotes/*'], ['FOUNDER_STAFF', 'office/* billing']], data: ['billingTypes.ts', 'billingCalculator.ts', 'servicePricingConfig.ts'], evidence: ['docs/BILLING_SYSTEM.md', 'docs/CLIENT_COMMAND_CENTER.md (separate financial domains)'] },
  functional_pct: 55,
  activation: 'billing live in demo; payment provider abstraction',
  code: ['src/billing/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.SERVICES', 'AIO.BOOKKEEPING'],
});

export const AIO_FACTORING = aioFeature({
  id: 'AIO.FACTORING',
  name: 'Factoring (assistance / partner)',
  family: 'F11 FACTORING',
  purpose: 'Turn completed-load invoices into cash through AIO’s factoring assistance and partner handoff — enrolment, packaging, specialist review, partner submission.',
  promise: 'From delivered load to funded invoice — AIO packages it and hands it to the factoring partner.',
  value: 'Complete invoice packets the first time; funding status visible (staff-entered from the partner).',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['factoring partner (external funder)'],
  entries: {
    public: ['Factoring page', 'services/invoice-factoring', 'Finances / dispatch cross-sell'],
    client: ['Factoring', 'portal/factoring/*', 'load complete → FACTOR THIS LOAD'],
    staff: ['Office factoring', 'office/factoring/*', 'invoice submitted for review'],
    system: ['factoring workflow', 'freight invoice created'],
  },
  states: [
    ['NOT_ENROLLED', 'Not enrolled', 'EMPTY', 'Enrol in factoring', 'not_enrolled / interested', { CLIENT: 'START ENROLMENT', PUBLIC: 'SEE IF IT FITS' }],
    ['DOCUMENTS_NEEDED', 'Documents needed', 'BLOCKED', 'Add documents to finish enrolment / invoice', 'documents_needed'],
    ['UNDER_REVIEW', 'Under review', 'REVIEW', 'AIO specialist reviewing', 'under_review'],
    ['PARTNER_REVIEW', 'Partner review', 'REVIEW', 'With the factoring partner', 'partner_review'],
    ['ACTIVE', 'Active', 'ACTIVE', 'Factor completed loads', 'active'],
    ['FUNDED', 'Funded', 'COMPLETE', 'Funding reported by partner', 'funded (staff-entered)'],
    ['CLOSED', 'Closed', 'ARCHIVED', 'Invoice closed', 'collected / closed'],
    ['DECLINED', 'Declined', 'ERROR', 'The partner declined — here is why', 'declined'],
  ],
  transitions: [
    ['NOT_ENROLLED', 'DOCUMENTS_NEEDED', 'application started', 'CLIENT'],
    ['DOCUMENTS_NEEDED', 'UNDER_REVIEW', 'documents complete', 'CLIENT'],
    ['UNDER_REVIEW', 'PARTNER_REVIEW', 'specialist approves packet', 'FOUNDER_STAFF'],
    ['PARTNER_REVIEW', 'ACTIVE', 'partner approves enrolment', 'FOUNDER_STAFF'],
    ['PARTNER_REVIEW', 'DECLINED', 'partner declines', 'FOUNDER_STAFF'],
    ['ACTIVE', 'UNDER_REVIEW', 'invoice submitted', 'CLIENT'],
    ['PARTNER_REVIEW', 'FUNDED', 'funding reported', 'FOUNDER_STAFF'],
    ['FUNDED', 'CLOSED', 'collection closed', 'FOUNDER_STAFF'],
  ],
  anchors: { start: 'DOCUMENTS_NEEDED', success: 'FUNDED', blocked: 'DOCUMENTS_NEEDED', errors: ['DECLINED'], empty: 'NOT_ENROLLED', complete: 'CLOSED' },
  inputs: [['ENROLMENT_DOCS', 'Enrolment documents (W-9, authority, NOA)', ['UPLOAD FILES', 'IMPORT FROM VAULT'], 'enrolment'], ['INVOICE_PACKET', 'Invoice + rate con + BOL + POD', ['FROM COMPLETED LOAD', 'UPLOAD FILES'], 'invoice submission']],
  derivations: [['PACKET_COMPLETENESS', 'invoice packet completeness', ['load documents'], 'documentCompleteness.ts'], ['FUNDING_ESTIMATE', 'estimated advance (demo label)', ['invoice'], 'staff-entered partner reports only']],
  reviews: [['SPECIALIST_REVIEW', 'UNDER_REVIEW', 'Is the packet complete and clean?', ['SUBMIT TO PARTNER', 'REQUEST DOCUMENTS']]],
  approvals: [['CONFIRM_SUBMISSION', 'UNDER_REVIEW', 'Submit this invoice for factoring?', ['SUBMIT', 'HOLD']]],
  overrides: [['MANUAL_STATUS', 'PARTNER_REVIEW', 'Record partner status manually', ['RECORD']]],
  artifacts: [['FREIGHT_INVOICE', 'Freight invoice (HF-*)', 'INVOICE', 'completed load', 'VAULT › Tax & Financial › Factoring'], ['FUNDING_REPORT', 'Partner funding report', 'REPORT', 'partner (staff-entered)', 'VAULT › Tax & Financial › Factoring']],
  vault: 'VAULT › Tax & Financial › Factoring',
  inbox: [['DOCUMENTS_NEEDED', 'Factoring needs documents'], ['FUNDED', 'Invoice {#} funded']],
  activity: [['UNDER_REVIEW', 'Invoice submitted'], ['FUNDED', 'Funding reported']],
  notify: [['FUNDED', 'Funding reported for invoice {#}']],
  tasks: [['UNDER_REVIEW', 'Review factoring packet for {client}']],
  next: 'Next completed load can be factored in one tap.',
  upstream: ['AIO.DISPATCH_OPERATIONS (completed loads)', 'AIO.BROKERAGE (carrier payables flags)'],
  downstream: ['AIO.BOOKKEEPING (factoring fees)', 'AIO.VAULT'],
  relationships: [['AIO.BOOKKEEPING', 'FUNDED', 'FEEDS', 'factoring fee appears in monthly close', 'fee categorised', { BOOKKEEPING: 'factoring fee line' }, 'none'], ['AIO.VAULT', 'CLOSED', 'ARCHIVES_TO', 'invoice + report filed', 'closed record', { VAULT: 'factoring folder' }, 'invoice seals']],
  public: {
    discovery: ['Finances services', 'dispatch cross-sell'],
    must_understand: ['AIO packages invoices and works with a factoring partner', 'AIO does not fund invoices itself', 'funding comes from the partner'],
    who_its_for: 'Carriers who want faster cash on delivered loads.',
    what_we_handle: ['enrolment packaging', 'invoice packets', 'partner submission', 'status tracking'],
    what_client_provides: ['enrolment documents', 'load documents'],
    how_it_works: ['Enrol', 'Complete a load', 'Factor this load', 'AIO reviews', 'Partner funds', 'Closed'],
    outcome: 'Funded invoices through the partner with clean packets.',
    timing: 'Per invoice; partner timing.',
    pricing_relationship: 'Partner fees per partner agreement; AIO assistance fees per catalog.',
    cta: 'See if Factoring Fits',
    workspace_continuity: 'FACTOR THIS LOAD on completed loads is the same flow the page explains.',
  },
  client: {
    entry_point: 'Factoring (or FACTOR THIS LOAD on a completed load)',
    primary_task: 'Get delivered loads funded.',
    sees_first: 'Invoices by stage and enrolment status.',
    must_provide: ['enrolment documents', 'load documents'],
    input_methods: ['FROM COMPLETED LOAD', 'UPLOAD FILES', 'IMPORT FROM VAULT'],
    system_already_knows: ['completed loads + documents'],
    ready_signals: ['packet completeness'],
    needs_you: ['missing documents'],
    under_review: ['specialist review', 'partner review'],
    approves: ['invoice submission'],
    completion_looks_like: 'Funding reported; invoice closed.',
    artifacts_received: ['Freight invoice (HF-*)', 'Partner funding report'],
    what_happens_next: 'Factor the next load.',
  },
  staff: {
    client_context: ['enrolment status', 'invoice history', 'partner'],
    work_queue: 'Factoring specialist queue',
    status_model: [],
    blockers: ['documents needed', 'partner review'],
    missing_inputs: ['NOA', 'POD'],
    system_flags: ['packet incomplete', 'direct factoring disabled'],
    human_review: ['packet review'],
    corrections: ['request documents'],
    approval: ['client submission confirmation'],
    overrides: ['manual partner status'],
    operational_actions: ['SUBMIT TO PARTNER', 'RECORD FUNDING', 'REQUEST DOCUMENTS'],
    artifact_generation: ['freight invoice', 'funding report entry'],
    completion: 'Funding recorded; closed.',
    hub_buckets: { AWAITING_CLIENT: ['DOCUMENTS_NEEDED'], NEEDS_REVIEW: ['UNDER_REVIEW'], AWAITING_PROVIDER: ['PARTNER_REVIEW'], COMPLETE: ['FUNDED', 'CLOSED'] },
    mirror_not_copy: 'Staff see packets, partner status and staff-entered funding figures; clients see invoice progress.',
  },
  system: {
    ingestion: ['completed loads', 'documents'],
    validation: ['packet completeness', 'directFactoringEnabled = false'],
    derivation: ['packet status', 'estimate labels'],
    state_transitions: ['enrolment statuses: not_enrolled → … → active'],
    next_cycle_creation: 'Each completed load offers FACTOR THIS LOAD.',
    failure_handling: ['declined → reasons + alternatives', 'never show AIO as funder'],
  },
  metaphor: 'INVOICE-TO-CASH FLOW',
  metaphor2: 'packet out, cash back',
  archetype: ['PIPELINE', 'PACKET_BUILDER'],
  object: 'THE INVOICE (load, amount, stage)',
  objects: ['packet', 'partner status', 'funding report'],
  composition: ['Invoices flow through stages; the packet shows completeness.', 'Funding figures labelled partner-reported.'],
  hierarchy: {
    CLIENT: ih('When do I get paid for this load?', 'Invoice stage', 'Complete packet / submit', 'Partner status', 'Documents needed', 'FACTOR THIS LOAD', 'Funding reported'),
    FOUNDER_STAFF: ih('Which packets are ready for the partner?', 'Queue by stage', 'Review / submit', 'Partner status', 'Missing docs', 'SUBMIT TO PARTNER', 'Funding recorded'),
  },
  grammar: [['FACTOR THIS LOAD', 'CLIENT', 'create invoice packet from a load', 'UNDER_REVIEW'], ['SUBMIT TO PARTNER', 'FOUNDER_STAFF', 'hand to partner', 'PARTNER_REVIEW'], ['RECORD FUNDING', 'FOUNDER_STAFF', 'enter partner report', 'FUNDED']],
  emotion: { PUBLIC: 'I understand who funds and what AIO does.', CLIENT: 'My delivered loads turn into cash without paperwork chaos.', FOUNDER_STAFF: 'Every packet is clean before the partner sees it.' },
  density: 'BALANCED',
  viewports: { mobile: ['invoice cards by stage', 'stacked'], tablet: ['pipeline + packet', 'two columns'], desktop: ['pipeline board + packet detail', 'columns + panel'] },
  ctas: { public: 'SEE IF FACTORING FITS', client: 'FACTOR THIS LOAD', staff: 'SUBMIT TO PARTNER' },
  avoid: ['presenting AIO as the funder', 'real-money language on demo / staff-entered figures', 'combining with service-fee billing'],
  e2e: {
    journey: 'ENROL → LOAD COMPLETE → FACTOR → REVIEW → PARTNER → FUNDED',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'services/invoice-factoring', 'open', ['partner model + AIO is not the funder']],
      CLIENT_ENTRY: ['CLIENT', 'portal/factoring', 'open', ['invoice stages']],
      CLIENT_ACTION: ['CLIENT', 'portal/dispatch/:load', 'FACTOR THIS LOAD', ['packet created from load docs']],
      SYSTEM_PROCESSING: ['SYSTEM', 'factoring workflow', 'completeness', ['missing docs flagged']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/factoring', 'review + submit', ['partner review']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/factoring', 'confirm submission', ['confirmation recorded']],
      ARTIFACT_CREATION: ['FOUNDER_STAFF', 'office/factoring', 'record funding report', ['report attached (partner-reported label)']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'bookkeeping · vault', 'propagate', ['fee to bookkeeping']],
      COMPLETION: ['CLIENT', 'portal/factoring', 'view', ['FUNDED']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'factoring folder', ['invoice + report filed']],
      NEXT_STEP: ['CLIENT', 'portal/operations', 'next load', ['FACTOR THIS LOAD available']],
    },
  },
  structure: { routes: [['PUBLIC', 'services/invoice-factoring'], ['CLIENT', 'portal/factoring/*'], ['FOUNDER_STAFF', 'office/factoring/*']], data: ['FactoringProfile', 'enrolment statuses', 'freight invoice HF-*'], evidence: ['docs/FACTORING_SYSTEM.md', 'src/factoring/*'] },
  functional_pct: 68,
  activation: 'factoring PARTNER_PENDING — partner referral, not direct funding',
  code: ['src/factoring/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.DISPATCH_OPERATIONS', 'AIO.BOOKKEEPING'],
});

export const AIO_INSURANCE = aioFeature({
  id: 'AIO.INSURANCE',
  name: 'Insurance (assistance / referral)',
  family: 'F12 INSURANCE',
  purpose: 'Help carriers get and keep the right commercial coverage: needs intake, partner referral, quotes reported by licensed partners, policy records, COI coordination, renewals.',
  promise: 'AIO coordinates your insurance with licensed partners and keeps every policy and certificate organised.',
  value: 'Coverage decisions with clear options and a policy record that feeds Road Ready and renewals.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['licensed insurance partner / producer'],
  entries: {
    public: ['Insurance page', 'services/commercial-auto-liability', 'Road Ready insurance item'],
    client: ['Insurance', 'portal/insurance/*', 'coverage request / renewal'],
    staff: ['Office insurance', 'office/insurance/*', 'request submitted'],
    system: ['insurance workflow', 'capability gate + request'],
  },
  states: [
    ['NO_POLICY', 'No policy on file', 'EMPTY', 'Add a policy or request coverage help', 'No record', { CLIENT: 'REQUEST COVERAGE HELP', PUBLIC: 'GET COVERAGE HELP' }],
    ['INTAKE', 'Coverage needs', 'ACTIVE', 'Tell AIO about your operation', 'Intake'],
    ['REFERRED', 'With partner', 'REVIEW', 'A licensed partner is preparing options', 'Partner referral'],
    ['OPTIONS_READY', 'Options ready', 'APPROVAL', 'Review coverage options', 'Awaiting customer selection', { CLIENT: 'REVIEW OPTIONS', FOUNDER_STAFF: 'FOLLOW UP' }],
    ['POLICY_SETUP', 'Policy setup', 'REVIEW', 'Setting up your policy record', 'Evidence-based setup'],
    ['ACTIVE_POLICY', 'Active policy', 'COMPLETE', 'Covered — policy on file', 'Active record'],
    ['RENEWAL_WINDOW', 'Renewal coming', 'ARCHIVED', 'Renewal coming up', 'Renewal'],
    ['DOCUMENTS_NEEDED', 'Documents needed', 'BLOCKED', 'Upload your policy / declarations', 'Waiting on customer'],
    ['LAPSE_RISK', 'Lapse risk', 'ERROR', 'Coverage may lapse — act now', 'Lapse risk'],
  ],
  transitions: [
    ['NO_POLICY', 'INTAKE', 'request coverage help', 'CLIENT'],
    ['INTAKE', 'REFERRED', 'internal review → referral', 'FOUNDER_STAFF'],
    ['REFERRED', 'OPTIONS_READY', 'partner-reported quotes entered', 'FOUNDER_STAFF'],
    ['OPTIONS_READY', 'POLICY_SETUP', 'customer selects externally', 'CLIENT'],
    ['POLICY_SETUP', 'DOCUMENTS_NEEDED', 'evidence missing', 'FOUNDER_STAFF'],
    ['DOCUMENTS_NEEDED', 'POLICY_SETUP', 'documents uploaded', 'CLIENT'],
    ['POLICY_SETUP', 'ACTIVE_POLICY', 'policy verified', 'FOUNDER_STAFF'],
    ['ACTIVE_POLICY', 'RENEWAL_WINDOW', 'expiration window', 'SYSTEM'],
    ['RENEWAL_WINDOW', 'LAPSE_RISK', 'no renewal near expiry', 'SYSTEM'],
    ['LAPSE_RISK', 'INTAKE', 'renewal help requested', 'CLIENT'],
  ],
  anchors: { start: 'INTAKE', success: 'ACTIVE_POLICY', blocked: 'DOCUMENTS_NEEDED', errors: ['LAPSE_RISK'], empty: 'NO_POLICY', complete: 'ACTIVE_POLICY' },
  inputs: [['OPERATION', 'Operation + cargo + units + drivers', ['GUIDED QUESTIONS'], 'partner referral'], ['POLICY_DOCS', 'Policy / declarations', ['UPLOAD FILES', 'IMPORT FROM VAULT'], 'policy record']],
  derivations: [['COVERAGE_NEEDS', 'coverage checklist', ['operation'], 'insurance config'], ['EXPIRY', 'renewal window', ['policy dates'], 'renewal engine']],
  reviews: [['INTERNAL_REVIEW', 'INTAKE', 'Ready to refer?', ['REFER', 'NEED INFO']], ['POLICY_VERIFY', 'POLICY_SETUP', 'Is the policy evidence valid?', ['VERIFY', 'REQUEST DOCS']]],
  approvals: [['SELECT_OPTION', 'OPTIONS_READY', 'Which option will you take (with the partner)?', ['SELECTED EXTERNALLY', 'NONE']]],
  overrides: [['MANUAL_POLICY', 'POLICY_SETUP', 'Record policy from customer-supplied record', ['RECORD']]],
  artifacts: [['POLICY_RECORD', 'Policy record + declarations', 'DOCUMENT', 'customer / partner', 'VAULT › Insurance'], ['COI', 'Certificate of insurance (from partner)', 'CERTIFICATE', 'partner', 'VAULT › Insurance']],
  vault: 'VAULT › Insurance',
  inbox: [['OPTIONS_READY', 'Coverage options ready'], ['LAPSE_RISK', 'Your coverage may lapse']],
  activity: [['REFERRED', 'Referred to partner'], ['ACTIVE_POLICY', 'Policy on file']],
  notify: [['RENEWAL_WINDOW', 'Insurance renewal coming up']],
  tasks: [['INTAKE', 'Review coverage needs for {client}'], ['POLICY_SETUP', 'Verify policy for {client}']],
  next: 'Renewal tracked in Insurance Renewals; Road Ready insurance item stays current.',
  upstream: ['AIO.AUTHORITIES (authority requires insurance)', 'fleet profile'],
  downstream: ['AIO.ROAD_READY', 'AIO.RENEWALS', 'AIO.VAULT'],
  relationships: [['AIO.ROAD_READY', 'ACTIVE_POLICY', 'UPDATES_STATUS', 'Road Ready insurance item verified', 'profile updated', { ROAD_READY: 'insurance verified' }, 'checklist line completes'], ['AIO.RENEWALS', 'RENEWAL_WINDOW', 'OPENS', 'insurance renewal in Renewal Center', 'renewal work item', { RENEWALS: 'insurance renewal' }, 'horizon item appears']],
  public: {
    discovery: ['Services hub', 'Road Ready'],
    must_understand: ['AIO is not an insurer or agency', 'licensed partners quote and bind', 'AIO coordinates and keeps your records'],
    who_its_for: 'Carriers needing commercial trucking coverage.',
    what_we_handle: ['needs intake', 'partner referral', 'organising quotes', 'policy records', 'COI coordination', 'renewal help'],
    what_client_provides: ['operation details', 'policy documents'],
    how_it_works: ['Tell AIO your needs', 'Partner prepares options', 'You choose with the partner', 'AIO records the policy', 'Renewal help'],
    outcome: 'Coverage chosen with a licensed partner and on file with AIO.',
    timing: 'Per policy term.',
    pricing_relationship: 'Premiums paid to the insurer / partner — never AIO revenue.',
    cta: 'Get Coverage Help',
    workspace_continuity: 'The disclosure on the page is the same disclosure on every insurance screen.',
  },
  client: {
    entry_point: 'Insurance',
    primary_task: 'Get covered and keep the policy on file.',
    sees_first: 'Coverage status per policy and what is needed.',
    must_provide: ['operation details', 'policy documents'],
    input_methods: ['GUIDED QUESTIONS', 'UPLOAD FILES', 'IMPORT FROM VAULT'],
    system_already_knows: ['authority + fleet'],
    ready_signals: ['policy active + expiry'],
    needs_you: ['option selection', 'policy documents'],
    under_review: ['partner preparing options', 'policy verification'],
    approves: ['option selection (with the partner)'],
    completion_looks_like: 'Active policy on file.',
    artifacts_received: ['Policy record + declarations', 'Certificate of insurance (from partner)'],
    what_happens_next: 'Renewal tracked.',
  },
  staff: {
    client_context: ['operation profile', 'policies', 'partner'],
    work_queue: 'Insurance division queue',
    status_model: [],
    blockers: ['awaiting partner', 'documents needed', 'lapse risk'],
    missing_inputs: ['declarations page'],
    system_flags: ['expiring policy', 'capability gate demo'],
    human_review: ['internal review', 'policy verification'],
    corrections: ['request documents'],
    approval: ['customer selection recorded'],
    overrides: ['record policy from customer record'],
    operational_actions: ['REFER', 'ENTER PARTNER QUOTES', 'VERIFY POLICY', 'COORDINATE COI'],
    artifact_generation: ['policy record'],
    completion: 'Active policy recorded.',
    hub_buckets: { NEEDS_REVIEW: ['INTAKE', 'POLICY_SETUP'], AWAITING_PROVIDER: ['REFERRED'], AWAITING_CLIENT: ['OPTIONS_READY', 'DOCUMENTS_NEEDED'], BLOCKED: ['LAPSE_RISK'], COMPLETE: ['ACTIVE_POLICY'] },
    mirror_not_copy: 'Staff see referral status and lapse risk across clients; clients see their coverage.',
  },
  system: {
    ingestion: ['intake', 'partner-reported quotes', 'policy documents'],
    validation: ['capability gate', 'isPremiumAllInOneServiceRevenue() always false'],
    derivation: ['coverage checklist', 'renewal windows'],
    state_transitions: ['intake → referral → options → setup → active → renewal'],
    next_cycle_creation: 'Renewal window opens before expiry.',
    failure_handling: ['lapse risk → urgent client + staff alerts'],
  },
  metaphor: 'COVERAGE DECISION + DOCUMENT PROGRESSION',
  metaphor2: 'a coverage file kept current',
  archetype: ['DECISION_WINDOW', 'DOCUMENT_TABLE'],
  object: 'THE POLICY (coverage, carrier, term)',
  objects: ['options', 'certificates', 'renewal'],
  composition: ['Policy status leads with the disclosure always present.', 'Options shown as a decision window, partner-attributed.'],
  hierarchy: {
    CLIENT: ih('Am I covered, and what do I need to do?', 'Policy status + expiry', 'Select option / upload docs', 'Partner progress', 'Lapse risk', 'REVIEW OPTIONS', 'Active policy on file'),
    FOUNDER_STAFF: ih('Who is at lapse risk or waiting on a partner?', 'Queue', 'Refer / verify', 'Partner status', 'Lapse risk', 'VERIFY POLICY', 'Policy recorded'),
  },
  grammar: [['REQUEST HELP', 'CLIENT', 'start intake', 'INTAKE'], ['REVIEW OPTIONS', 'CLIENT', 'review partner options', 'POLICY_SETUP'], ['VERIFY POLICY', 'FOUNDER_STAFF', 'verify evidence', 'ACTIVE_POLICY']],
  emotion: { PUBLIC: 'I know AIO coordinates and partners insure.', CLIENT: 'My coverage is handled and never a surprise.', FOUNDER_STAFF: 'No client lapses unnoticed.' },
  density: 'BALANCED',
  viewports: { mobile: ['status + next action', 'stacked'], tablet: ['policies + detail', 'two columns'], desktop: ['policy table + options', 'table + panel'] },
  ctas: { public: 'GET COVERAGE HELP', client: 'REVIEW OPTIONS', staff: 'VERIFY POLICY' },
  avoid: ['implying AIO binds coverage or issues COIs', 'premium as AIO revenue', 'missing disclosure'],
  e2e: {
    journey: 'INTAKE → REFERRAL → OPTIONS → SELECT → POLICY ON FILE → RENEWAL',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'services/commercial-auto-liability', 'open', ['not an insurer disclosure']],
      CLIENT_ENTRY: ['CLIENT', 'portal/insurance', 'open', ['coverage status + disclosure']],
      CLIENT_ACTION: ['CLIENT', 'portal/insurance/request', 'intake', ['request created']],
      SYSTEM_PROCESSING: ['SYSTEM', 'insurance workflow', 'capability gate', ['demo label shown']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/insurance', 'refer + enter partner quotes', ['options attributed to partner']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/insurance', 'select option', ['selection recorded']],
      ARTIFACT_CREATION: ['FOUNDER_STAFF', 'office/insurance', 'verify policy', ['policy record stored']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'road ready · renewals', 'propagate', ['Road Ready verified']],
      COMPLETION: ['CLIENT', 'portal/insurance', 'view', ['ACTIVE POLICY']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'insurance folder', ['policy + COI']],
      NEXT_STEP: ['CLIENT', 'portal/insurance/renewals', 'view', ['renewal tracked']],
    },
  },
  structure: { routes: [['PUBLIC', 'services/commercial-auto-liability'], ['CLIENT', 'portal/insurance/*'], ['FOUNDER_STAFF', 'office/insurance/*']], data: ['insuranceConfig.ts (DEFAULT_INSURANCE_CAPABILITY demo, INSURANCE_DISCLOSURE)'], evidence: ['docs/INSURANCE_SYSTEM.md', 'docs/INSURANCE_REGULATORY_BOUNDARIES.md'] },
  functional_pct: 65,
  activation: 'insurance PARTNER_PENDING — assistance / referral, no bind without licensing',
  code: ['src/insurance/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.ROAD_READY', 'AIO.RENEWALS', 'AIO.AUTHORITIES'],
});

export const AIO_BOOKKEEPING = aioFeature({
  id: 'AIO.BOOKKEEPING',
  name: 'Bookkeeping',
  family: 'F13 BOOKKEEPING',
  purpose: 'Keep a carrier’s books monthly — categorised around trucking (fuel, tolls, permits, factoring fees, dispatch fees, truck payments) — and close each month.',
  promise: 'Bookkeeping built for trucking: AIO closes your month, you answer a few questions.',
  value: 'Monthly books that reflect how a trucking business actually spends and earns.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['CPA / tax preparer (external)'],
  entries: {
    public: ['Bookkeeping page', 'services/bookkeeping', 'plan recommendation'],
    client: ['Bookkeeping', 'portal/bookkeeping', 'monthly close request / plan'],
    staff: ['Office bookkeeping', 'office/bookkeeping/*', 'month open'],
    system: ['bookkeeping autopilot', 'month boundary'],
  },
  states: [
    ['NO_PLAN', 'No plan', 'EMPTY', 'Choose a bookkeeping plan', 'No subscription', { CLIENT: 'CHOOSE A PLAN', PUBLIC: 'SEE PLANS' }],
    ['MONTH_OPEN', 'Month open', 'ACTIVE', 'Sending statements for {month}', 'Collecting'],
    ['QUESTIONS', 'Questions for you', 'BLOCKED', 'A few transactions need your answer', 'Waiting on client'],
    ['CLOSING', 'Closing', 'REVIEW', 'AIO is closing {month}', 'Reconciling / closing'],
    ['REVIEW_READY', 'Review ready', 'APPROVAL', 'Review your month', 'Awaiting client review', { CLIENT: 'REVIEW MONTH', FOUNDER_STAFF: 'REMIND' }],
    ['CLOSED', 'Closed', 'COMPLETE', '{month} closed — reports ready', 'Closed'],
    ['ARCHIVED', 'Archived', 'ARCHIVED', 'Past months', 'Archived'],
    ['RESCUE_NEEDED', 'Books need rescue', 'ERROR', 'Your books are behind — Books Rescue recommended', 'Backlog'],
  ],
  transitions: [
    ['NO_PLAN', 'MONTH_OPEN', 'plan started', 'CLIENT'],
    ['MONTH_OPEN', 'QUESTIONS', 'uncategorised transactions', 'SYSTEM'],
    ['QUESTIONS', 'CLOSING', 'answers received', 'CLIENT'],
    ['MONTH_OPEN', 'CLOSING', 'statements complete', 'SYSTEM'],
    ['CLOSING', 'REVIEW_READY', 'month reconciled', 'FOUNDER_STAFF'],
    ['REVIEW_READY', 'CLOSED', 'client confirms', 'CLIENT'],
    ['CLOSED', 'ARCHIVED', 'next month opens', 'SYSTEM'],
    ['MONTH_OPEN', 'RESCUE_NEEDED', 'backlog detected', 'SYSTEM'],
    ['RESCUE_NEEDED', 'MONTH_OPEN', 'Books Rescue complete', 'FOUNDER_STAFF'],
  ],
  anchors: { start: 'MONTH_OPEN', success: 'CLOSED', blocked: 'QUESTIONS', errors: ['RESCUE_NEEDED'], empty: 'NO_PLAN', complete: 'ARCHIVED' },
  inputs: [['STATEMENTS', 'Bank / card statements', ['UPLOAD FILES', 'IMPORT FROM VAULT'], 'transactions'], ['ANSWERS', 'Transaction answers', ['ANSWER'], 'categorisation']],
  derivations: [['CATEGORISE', 'trucking categories', ['transactions'], 'autopilot chartOfAccounts.ts'], ['PLAN_FIT', 'plan recommendation', ['business size'], 'bookkeepingRecommendation.ts']],
  reviews: [['CLOSE_REVIEW', 'CLOSING', 'Is the month reconciled?', ['SEND FOR REVIEW', 'ASK CLIENT']]],
  approvals: [['CONFIRM_MONTH', 'REVIEW_READY', 'Confirm the month', ['CONFIRM', 'ASK']]],
  overrides: [['RECATEGORISE', 'CLOSING', 'Recategorise with note', ['RECATEGORISE']]],
  artifacts: [['PNL', 'Monthly P&L', 'REPORT', 'close', 'VAULT › Tax & Financial › Bookkeeping'], ['BALANCE_SHEET', 'Balance sheet', 'REPORT', 'close', 'VAULT › Tax & Financial › Bookkeeping']],
  vault: 'VAULT › Tax & Financial › Bookkeeping › {YYYY-MM}',
  inbox: [['QUESTIONS', '{n} transactions need your answer'], ['REVIEW_READY', '{month} is ready for review']],
  activity: [['CLOSING', 'Statements received'], ['CLOSED', 'Month closed']],
  notify: [['MONTH_OPEN', 'Send statements for {month}']],
  tasks: [['CLOSING', 'Close {month} for {client}']],
  next: 'Next month opens; year-end package goes to the client’s CPA (AIO does not prepare tax returns).',
  upstream: ['AIO.DISPATCH_OPERATIONS', 'AIO.FACTORING', 'AIO.IFTA (fuel tax payment)', 'AIO.BROKERAGE (handoff)', 'AIO.FINANCES'],
  downstream: ['AIO.VAULT', 'external CPA'],
  relationships: [['AIO.VAULT', 'CLOSED', 'ARCHIVES_TO', 'monthly reports filed', 'close recorded', { VAULT: 'month folder' }, 'month card seals']],
  public: {
    discovery: ['Services hub › Finances', 'plan recommendation'],
    must_understand: ['bookkeeping built for trucking', 'AIO is not a CPA / tax preparer', 'IFTA bookkeeping support is not IFTA filing'],
    who_its_for: 'Owner-operators and fleets needing monthly books.',
    what_we_handle: ['categorising transactions', 'monthly close', 'reports'],
    what_client_provides: ['statements', 'answers'],
    how_it_works: ['Pick a plan', 'Send statements', 'Answer questions', 'AIO closes', 'Review + confirm'],
    outcome: 'Closed months with P&L and balance sheet.',
    timing: 'Monthly.',
    pricing_relationship: 'Essentials $249/mo · Plus $449/mo · All In One $749/mo; Books Rescue from $749 one-time.',
    cta: 'See Plans',
    workspace_continuity: 'The month card in the portal follows the five public steps.',
  },
  client: {
    entry_point: 'Bookkeeping',
    primary_task: 'Send statements and answer questions so the month closes.',
    sees_first: 'The current month and what it needs.',
    must_provide: ['statements', 'answers'],
    input_methods: ['UPLOAD FILES', 'IMPORT FROM VAULT', 'ANSWER'],
    system_already_knows: ['loads, factoring fees, AIO fees, fuel tax payments'],
    ready_signals: ['statements received'],
    needs_you: ['questions', 'month review'],
    under_review: ['closing'],
    approves: ['month confirmation'],
    completion_looks_like: 'Month closed with reports.',
    artifacts_received: ['Monthly P&L', 'Balance sheet'],
    what_happens_next: 'Next month opens.',
  },
  staff: {
    client_context: ['plan', 'months status', 'connected sources'],
    work_queue: 'Monthly close queue',
    status_model: [],
    blockers: ['missing statements', 'unanswered questions'],
    missing_inputs: ['statements'],
    system_flags: ['uncategorised', 'backlog'],
    human_review: ['close review'],
    corrections: ['recategorise'],
    approval: ['client month confirmation'],
    overrides: ['recategorise with note'],
    operational_actions: ['CLOSE MONTH', 'ASK CLIENT', 'SEND REPORTS'],
    artifact_generation: ['P&L', 'balance sheet'],
    completion: 'Month closed.',
    hub_buckets: { AWAITING_CLIENT: ['MONTH_OPEN', 'QUESTIONS', 'REVIEW_READY'], NEEDS_REVIEW: ['CLOSING'], BLOCKED: ['RESCUE_NEEDED'], COMPLETE: ['CLOSED'] },
    mirror_not_copy: 'Staff see the close calendar across clients; clients see their month.',
  },
  system: {
    ingestion: ['statements', 'AIO domain events (loads, fees, fuel tax)'],
    validation: ['statement period coverage'],
    derivation: ['trucking categories', 'plan fit'],
    state_transitions: ['open → questions → closing → review → closed'],
    next_cycle_creation: 'Next month opens at the boundary.',
    failure_handling: ['backlog → RESCUE_NEEDED (Books Rescue)'],
  },
  metaphor: 'MONTHLY CLOSE WORKSPACE',
  metaphor2: 'the month on the desk',
  archetype: ['WORKBENCH', 'LEDGER'],
  object: 'THE MONTH (period, close status)',
  objects: ['transactions', 'questions', 'reports'],
  composition: ['The month is the bench object; questions lead when open.', 'Reports appear only when closed.'],
  hierarchy: {
    CLIENT: ih('Is my month closed, and what do you need?', 'Month status', 'Send statements / answer', 'Categories', 'Questions open', 'ANSWER QUESTIONS', 'Closed reports'),
    FOUNDER_STAFF: ih('Which months are behind?', 'Close calendar', 'Close', 'Backlogs', 'Missing statements', 'CLOSE MONTH', 'Reports sent'),
  },
  grammar: [['UPLOAD', 'CLIENT', 'send statements', 'MONTH_OPEN'], ['ANSWER', 'CLIENT', 'answer a transaction question', 'CLOSING'], ['CLOSE MONTH', 'FOUNDER_STAFF', 'close', 'REVIEW_READY']],
  emotion: { PUBLIC: 'Books that understand trucking.', CLIENT: 'My month closes without me living in spreadsheets.', FOUNDER_STAFF: 'Every client month is on schedule.' },
  density: 'BALANCED',
  viewports: { mobile: ['questions one at a time', 'month card → questions'], tablet: ['month + transactions', 'two columns'], desktop: ['month workbench', 'transactions table + reports'] },
  ctas: { public: 'SEE PLANS', client: 'ANSWER QUESTIONS', staff: 'CLOSE MONTH' },
  avoid: ['generic small-business bookkeeping framing', 'tax return promises', 'calling IFTA bookkeeping a filing'],
  e2e: {
    journey: 'PLAN → MONTH OPEN → STATEMENTS → QUESTIONS → CLOSE → REVIEW → CLOSED',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'services/bookkeeping', 'open', ['plans + not-a-CPA boundary']],
      CLIENT_ENTRY: ['CLIENT', 'portal/bookkeeping', 'open', ['current month leads']],
      CLIENT_ACTION: ['CLIENT', 'portal/bookkeeping', 'upload statements + answer', ['questions resolved']],
      SYSTEM_PROCESSING: ['SYSTEM', 'autopilot', 'categorise', ['trucking categories applied']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/bookkeeping', 'close month', ['review ready']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/bookkeeping', 'confirm month', ['closed']],
      ARTIFACT_CREATION: ['SYSTEM', 'reports', 'P&L + balance sheet', ['reports generated']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'vault', 'file reports', ['month folder']],
      COMPLETION: ['CLIENT', 'portal/bookkeeping', 'view', ['CLOSED']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'bookkeeping folder', ['reports present']],
      NEXT_STEP: ['CLIENT', 'portal/bookkeeping', 'view', ['next month open']],
    },
  },
  structure: { routes: [['PUBLIC', 'services/bookkeeping'], ['CLIENT', 'portal/bookkeeping'], ['FOUNDER_STAFF', 'office/bookkeeping/*']], data: ['bookkeepingPlans.ts', 'autopilot/chartOfAccounts.ts'], evidence: ['docs/services/BOOKKEEPING_SERVICE.md', 'src/bookkeeping/bookkeepingConfig.ts'] },
  functional_pct: 69,
  activation: 'bookkeeping in catalog (plans priced)',
  code: ['src/bookkeeping/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.FACTORING', 'AIO.IFTA', 'AIO.DISPATCH_OPERATIONS'],
});
