/**
 * AIO operations families (F07 OPERATIONS · F08 LOAD BOARD · F09 BROKERAGE · F14 FLEETCARE · F15 DRIVERLINK) with
 * their role projections (SHIPPER, DRIVER, FLEETCARE PROVIDER, AIO OFFICE). Lifecycles quoted from DISPATCH_SYSTEM.md,
 * BROKERAGE_SYSTEM.md, fleetcareTypes.ts (FleetCareTicketStatus) and driverlinkTypes.ts. Dispatch ≠ Brokerage
 * (separate customers, queues, revenue); shippers never see carrier pay / margin.
 */
import { aioFeature, ih } from './kit.js';

export const AIO_DISPATCH_OPERATIONS = aioFeature({
  id: 'AIO.DISPATCH_OPERATIONS',
  name: 'Dispatch / Operations',
  family: 'F07 OPERATIONS',
  purpose: 'AIO dispatchers find, review and book loads for enrolled carrier clients and see each load through to POD.',
  promise: 'Your trucks stay loaded — AIO dispatch finds and books freight, you approve, AIO tracks it to delivery.',
  value: 'Less time on boards and phones; every load approved by the carrier and documented for billing and factoring.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['DRIVER (executes the load)', 'Broker / shipper (external load source)'],
  entries: {
    public: ['Dispatch service page', 'services/dispatch', 'Services hub › Operations'],
    client: ['Operations', 'portal/operations · portal/dispatch', 'load offer awaiting approval / dispatch enrolment'],
    staff: ['Office dispatch board', 'office/dispatch/*', 'carrier truck available / load opportunity'],
    system: ['dispatch engine', 'enrolment active / load status change'],
  },
  states: [
    ['NOT_ENROLLED', 'Not enrolled', 'EMPTY', 'Get dispatch service', 'No enrolment', { CLIENT: 'REQUEST DISPATCH', PUBLIC: 'REQUEST DISPATCH' }],
    ['ONBOARDING', 'Onboarding', 'ACTIVE', 'Finish dispatch onboarding', 'Onboarding (agreement / truck profile)'],
    ['SEARCHING', 'Finding loads', 'ACTIVE', 'AIO is finding loads for {truck}', 'Truck available — searching'],
    ['OFFER_PENDING', 'Load offer', 'APPROVAL', 'Approve this load?', 'Awaiting carrier approval', { CLIENT: 'APPROVE LOAD', FOUNDER_STAFF: 'NUDGE CARRIER' }],
    ['BOOKED', 'Booked', 'ACTIVE', 'Booked — pickup {date}', 'Booked'],
    ['IN_TRANSIT', 'In transit', 'REVIEW', 'On the road', 'Pickup → in transit → delivery'],
    ['POD_NEEDED', 'POD needed', 'BLOCKED', 'Upload the POD to get paid', 'Waiting on POD'],
    ['LOAD_COMPLETE', 'Load complete', 'COMPLETE', 'Delivered — ready to invoice / factor', 'Complete'],
    ['SETTLED', 'Settled', 'ARCHIVED', 'Paid and filed', 'Settled + documents archived'],
    ['LOAD_PROBLEM', 'Load problem', 'ERROR', 'Something went wrong with this load — AIO is handling it', 'TONU / cancellation / claim'],
  ],
  transitions: [
    ['NOT_ENROLLED', 'ONBOARDING', 'dispatch request accepted', 'FOUNDER_STAFF'],
    ['ONBOARDING', 'SEARCHING', 'agreement accepted + truck active', 'CLIENT'],
    ['SEARCHING', 'OFFER_PENDING', 'dispatcher proposes a reviewed load', 'FOUNDER_STAFF'],
    ['OFFER_PENDING', 'BOOKED', 'carrier approves', 'CLIENT'],
    ['OFFER_PENDING', 'SEARCHING', 'carrier declines', 'CLIENT'],
    ['BOOKED', 'IN_TRANSIT', 'pickup confirmed', 'FOUNDER_STAFF'],
    ['IN_TRANSIT', 'POD_NEEDED', 'delivered without POD', 'SYSTEM'],
    ['POD_NEEDED', 'LOAD_COMPLETE', 'POD uploaded', 'CLIENT'],
    ['IN_TRANSIT', 'LOAD_COMPLETE', 'delivered with POD', 'FOUNDER_STAFF'],
    ['IN_TRANSIT', 'LOAD_PROBLEM', 'problem reported', 'FOUNDER_STAFF'],
    ['LOAD_COMPLETE', 'SETTLED', 'invoice paid / factored and recorded', 'SYSTEM'],
  ],
  anchors: { start: 'ONBOARDING', success: 'LOAD_COMPLETE', blocked: 'POD_NEEDED', errors: ['LOAD_PROBLEM'], empty: 'NOT_ENROLLED', complete: 'SETTLED' },
  inputs: [['TRUCK_PROFILE', 'Truck + lanes + preferences', ['ENTER', 'IMPORT FROM FLEET'], 'load matching'], ['LOAD_APPROVAL', 'Approve / decline offered loads', ['APPROVE', 'DECLINE'], 'booking'], ['POD', 'Proof of delivery + BOL', ['TAKE PHOTO', 'UPLOAD FILES'], 'invoice / factoring']],
  derivations: [['LOAD_SCORE', 'load score band + reasons', ['rate', 'miles'], 'loadScoreEngine.ts'], ['DOC_COMPLETENESS', 'load document completeness', ['BOL', 'POD', 'rate con'], 'documentCompleteness.ts'], ['IFTA_MILES', 'estimated miles per state', ['loaded + deadhead miles'], 'milesFromLoadFields → AIO.IFTA (estimate only)']],
  reviews: [['LOAD_REVIEW', 'SEARCHING', 'Is this load good for this carrier?', ['OFFER TO CARRIER', 'PASS']]],
  approvals: [['CARRIER_APPROVES_LOAD', 'OFFER_PENDING', 'Take this load?', ['APPROVE', 'DECLINE']]],
  overrides: [['MANUAL_LOAD', 'SEARCHING', 'Enter a carrier-provided load manually', ['ADD MANUAL LOAD']]],
  artifacts: [['RATE_CON', 'Rate confirmation', 'DOCUMENT', 'broker / shipper', 'VAULT › Loads'], ['BOL', 'Bill of lading', 'DOCUMENT', 'pickup', 'VAULT › Loads'], ['POD_DOC', 'Proof of delivery', 'DOCUMENT', 'delivery', 'VAULT › Loads']],
  vault: 'VAULT › Loads › {load #}',
  inbox: [['OFFER_PENDING', 'New load offer for {truck} — approve?'], ['POD_NEEDED', 'Upload POD for load {#}']],
  activity: [['BOOKED', 'Load {#} booked'], ['LOAD_COMPLETE', 'Load {#} complete']],
  notify: [['OFFER_PENDING', 'Load offer waiting'], ['POD_NEEDED', 'POD needed']],
  tasks: [['SEARCHING', 'Find loads for {truck}'], ['IN_TRANSIT', 'Check call {load #}']],
  next: 'Completed loads flow to invoice / factoring; the truck goes back to SEARCHING.',
  upstream: ['AIO.ROAD_READY (authority active)', 'AIO.LOAD_BOARD (opportunities)', 'fleet profile'],
  downstream: ['AIO.FACTORING (freight invoice)', 'AIO.FINANCES (dispatch fee)', 'AIO.IFTA (estimated miles)', 'AIO.VAULT', 'AIO.BOOKKEEPING'],
  relationships: [
    ['AIO.FACTORING', 'LOAD_COMPLETE', 'FEEDS', 'FACTOR THIS LOAD offered on the completed load', 'freight invoice ready for factoring review', { FACTORING: 'freight invoice HF-* created from the load' }, 'load card shows invoice ready'],
    ['AIO.FINANCES', 'LOAD_COMPLETE', 'FEEDS', 'dispatch fee appears in Money (AIO service fees)', 'fee billable', { FINANCES: 'dispatch fee line' }, 'none on the load'],
    ['AIO.IFTA', 'LOAD_COMPLETE', 'FEEDS', 'load miles appear as ESTIMATES in the IFTA quarter', 'estimated miles visible', { IFTA: 'estimated jurisdiction miles' }, 'estimate badge in the quarter'],
    ['AIO.VAULT', 'LOAD_COMPLETE', 'ARCHIVES_TO', 'load documents filed under the load', 'documents complete', { VAULT: 'rate con, BOL, POD' }, 'load folder seals'],
  ],
  public: {
    discovery: ['Services hub › Operations', 'homepage pathway “Keep my truck loaded”'],
    must_understand: ['AIO dispatchers work for the carrier', 'you approve every load', 'dispatch is a service fee, not brokerage'],
    who_its_for: 'Owner-operators and small fleets with active authority.',
    what_we_handle: ['finding and reviewing loads', 'booking after your approval', 'check calls', 'collecting documents for billing'],
    what_client_provides: ['truck + lane preferences', 'load approvals', 'POD'],
    how_it_works: ['Enrol', 'AIO finds loads', 'You approve', 'AIO books + tracks', 'You upload POD', 'Invoice / factor'],
    outcome: 'Booked loads with complete paperwork, ready to get paid.',
    timing: 'Continuous while enrolled.',
    pricing_relationship: 'Dispatch fee (service revenue) — separate from freight pay.',
    cta: 'Request Dispatch',
    workspace_continuity: 'The page’s approve-every-load promise is the portal’s load offer decision window.',
  },
  client: {
    entry_point: 'Operations (or load offer notification)',
    primary_task: 'Approve good loads and close each load with a POD.',
    sees_first: 'Each truck’s status and any load offer waiting for approval.',
    must_provide: ['truck preferences', 'approvals', 'POD'],
    input_methods: ['APPROVE / DECLINE', 'TAKE PHOTO', 'UPLOAD FILES'],
    system_already_knows: ['authority status', 'fleet', 'lane history'],
    ready_signals: ['load score band', 'document completeness'],
    needs_you: ['load approvals', 'POD uploads'],
    under_review: ['loads being searched / reviewed'],
    approves: ['each load offer'],
    completion_looks_like: 'Load complete with POD; invoice / factoring ready.',
    artifacts_received: ['Rate confirmation', 'BOL', 'POD'],
    what_happens_next: 'Truck returns to searching; invoice / factoring proceeds.',
  },
  staff: {
    client_context: ['carrier + trucks + lanes', 'enrolment + agreement status', 'load history'],
    work_queue: 'Dispatch board (trucks × loads)',
    status_model: [],
    blockers: ['awaiting carrier approval', 'missing POD', 'load problems'],
    missing_inputs: ['truck preferences', 'documents'],
    system_flags: ['low load score', 'document incomplete'],
    human_review: ['load review before offering'],
    corrections: ['update load details', 'request documents'],
    approval: ['carrier approval recorded per load'],
    overrides: ['manual load entry (carrier-provided)'],
    operational_actions: ['OFFER LOAD', 'BOOK', 'CHECK CALL', 'MARK DELIVERED', 'LOG PROBLEM'],
    artifact_generation: ['rate con capture', 'document completeness'],
    completion: 'Load complete; documents complete; fee billable.',
    hub_buckets: { AWAITING_CLIENT: ['OFFER_PENDING', 'POD_NEEDED'], NEEDS_REVIEW: ['SEARCHING'], READY_TO_SEND: ['BOOKED'], BLOCKED: ['LOAD_PROBLEM'], COMPLETE: ['LOAD_COMPLETE', 'SETTLED'] },
    mirror_not_copy: 'Dispatchers see a CONTROL ROOM board across trucks and loads with check calls and exceptions; carriers see their trucks and the next decision.',
  },
  system: {
    ingestion: ['load opportunities', 'status updates', 'documents'],
    validation: ['authority active', 'document completeness'],
    derivation: ['load score', 'estimated IFTA miles', 'invoice readiness'],
    state_transitions: ['offer → booked → in transit → complete → settled'],
    next_cycle_creation: 'Truck re-enters SEARCHING after LOAD_COMPLETE.',
    failure_handling: ['problem → LOAD_PROBLEM with owner', 'missing POD → POD_NEEDED reminders'],
  },
  metaphor: 'DISPATCH DESK',
  metaphor2: 'every truck on a lane, every load a decision',
  archetype: ['CONTROL_ROOM', 'DECISION_WINDOW', 'PIPELINE'],
  object: 'THE LOAD (lane, rate, pickup / delivery, status)',
  objects: ['trucks', 'load offers', 'documents'],
  composition: ['Client: trucks with their current load; a pending offer opens as a decision window.', 'Staff: board of trucks × loads with exceptions raised.', 'Documents attach to the load, never a separate list.'],
  hierarchy: {
    CLIENT: ih('Are my trucks loaded, and do I need to approve anything?', 'Truck status + current load', 'Approve offers, upload POD', 'Upcoming pickups', 'POD missing / problem', 'APPROVE LOAD / UPLOAD POD', 'Load complete + invoice ready'),
    FOUNDER_STAFF: ih('Which trucks need loads and which loads need attention?', 'Board exceptions', 'Find, offer, book, track', 'Check calls due', 'Approval pending / problem', 'OFFER · BOOK · CHECK CALL', 'Load complete with documents'),
  },
  grammar: [['APPROVE LOAD', 'CLIENT', 'accept an offered load', 'BOOKED'], ['DECLINE', 'CLIENT', 'decline an offer', 'SEARCHING'], ['UPLOAD POD', 'CLIENT', 'close the load', 'LOAD_COMPLETE'], ['OFFER LOAD', 'FOUNDER_STAFF', 'propose a reviewed load', 'OFFER_PENDING'], ['CHECK CALL', 'FOUNDER_STAFF', 'log in-transit status']],
  emotion: { PUBLIC: 'AIO works for my truck, and I stay in control.', CLIENT: 'My trucks are moving and I only decide what matters.', FOUNDER_STAFF: 'I can see every truck and every exception.' },
  density: 'DENSE',
  viewports: { mobile: ['decision-first: offer cards and POD capture', 'truck list → offer window'], tablet: ['trucks + load detail', 'two columns'], desktop: ['board of trucks × loads', 'control room grid'] },
  ctas: { public: 'REQUEST DISPATCH', client: 'APPROVE LOAD', staff: 'OFFER LOAD' },
  avoid: ['load board clutter in the client view', 'mixing brokerage margin into dispatch', 'GPS-tracker framing'],
  e2e: {
    journey: 'PUBLIC → ENROL → OFFER → APPROVE → BOOKED → DELIVERED → POD → INVOICE / FACTOR',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'services/dispatch', 'open page', ['approve-every-load promise', 'fee vs freight pay explained']],
      CLIENT_ENTRY: ['CLIENT', 'portal/operations', 'open operations', ['truck status visible']],
      CLIENT_ACTION: ['CLIENT', 'portal/dispatch', 'upload POD', ['load moves to complete']],
      SYSTEM_PROCESSING: ['SYSTEM', 'dispatch engine', 'score + completeness', ['load score + reasons', 'document completeness']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/dispatch', 'review + offer load', ['offer created']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/dispatch', 'approve offer', ['booked']],
      ARTIFACT_CREATION: ['SYSTEM', 'load', 'attach rate con / BOL / POD', ['documents on the load']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'factoring · finances · ifta', 'propagate completion', ['invoice ready', 'dispatch fee', 'estimated miles']],
      COMPLETION: ['CLIENT', 'portal/dispatch', 'view load', ['LOAD COMPLETE']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open load folder', ['documents filed']],
      NEXT_STEP: ['CLIENT', 'portal/operations', 'truck status', ['truck back to finding loads']],
    },
  },
  structure: { routes: [['PUBLIC', 'services/dispatch'], ['CLIENT', 'portal/operations · portal/dispatch/*'], ['FOUNDER_STAFF', 'office/dispatch/*']], data: ['dispatchEnrollments', 'canonical Load', 'loadScoreEngine.ts', 'documentCompleteness.ts'], evidence: ['docs/DISPATCH_SYSTEM.md', 'src/dispatch/*'] },
  functional_pct: 71,
  activation: 'dispatch ACTIVE — manual load entry supported without load board',
  code: ['src/dispatch/*', 'src/freight/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.LOAD_BOARD', 'AIO.FACTORING', 'AIO.IFTA', 'AIO.FINANCES'],
});

export const AIO_LOAD_BOARD = aioFeature({
  id: 'AIO.LOAD_BOARD',
  name: 'Load Board',
  family: 'F08 LOAD BOARD',
  purpose: 'Show carriers published load opportunities (brokerage publication projection) to consider, negotiate and book.',
  promise: 'See real opportunities that fit your truck and book them through AIO.',
  value: 'Opportunities pre-filtered for fit, with rate and miles visible, without shipper-side pricing leakage.',
  actors: ['CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['CARRIER role projection', 'AIO brokerage (publisher)'],
  entries: {
    public: { applicable: false, reason: 'Authenticated carrier surface — opportunities are not published publicly.' },
    client: ['Load Board', 'portal/load-board/*', 'Operations › find loads'],
    staff: ['Office brokerage coverage', 'office/brokerage/*', 'load published for coverage'],
    system: ['publication projection', 'brokerage load published'],
  },
  states: [
    ['NO_MATCHES', 'No matching loads', 'EMPTY', 'No loads fit your truck right now', 'No eligible loads'],
    ['BROWSING', 'Opportunities', 'ACTIVE', 'Loads that fit your truck', 'Published loads'],
    ['NEGOTIATING', 'Offer sent', 'REVIEW', 'Your offer is with AIO', 'Carrier offer received'],
    ['OFFER_DECISION', 'Counter received', 'APPROVAL', 'Accept the counter?', 'Awaiting carrier', { CLIENT: 'ACCEPT', FOUNDER_STAFF: 'SEND COUNTER' }],
    ['BOOKED', 'Booked', 'COMPLETE', 'Booked — rate con in your load', 'Covered'],
    ['CLOSED', 'Closed', 'ARCHIVED', 'Load filled', 'Filled / expired'],
    ['NOT_ELIGIBLE', 'Not eligible', 'BLOCKED', 'Complete Road Ready items to book', 'Carrier not eligible'],
    ['PUBLISH_ERROR', 'Unavailable', 'ERROR', 'This load is no longer available', 'Withdrawn'],
  ],
  transitions: [
    ['NO_MATCHES', 'BROWSING', 'eligible loads published', 'SYSTEM'],
    ['BROWSING', 'NEGOTIATING', 'carrier sends offer / requests load', 'CLIENT'],
    ['NEGOTIATING', 'OFFER_DECISION', 'counter offered', 'FOUNDER_STAFF'],
    ['OFFER_DECISION', 'BOOKED', 'carrier accepts', 'CLIENT'],
    ['NEGOTIATING', 'BOOKED', 'offer accepted', 'FOUNDER_STAFF'],
    ['BROWSING', 'NOT_ELIGIBLE', 'eligibility check fails', 'SYSTEM'],
    ['BROWSING', 'PUBLISH_ERROR', 'load withdrawn', 'SYSTEM'],
    ['BOOKED', 'CLOSED', 'load delivered / closed', 'SYSTEM'],
  ],
  anchors: { start: 'BROWSING', success: 'BOOKED', blocked: 'NOT_ELIGIBLE', errors: ['PUBLISH_ERROR'], empty: 'NO_MATCHES', complete: 'CLOSED' },
  inputs: [['CARRIER_OFFER', 'Offer / rate request', ['ENTER RATE', 'ACCEPT POSTED'], 'negotiation']],
  derivations: [['FIT', 'fit score vs truck + lanes', ['load', 'truck profile'], 'loadScoreEngine.ts'], ['PROJECTION', 'carrier-safe load fields', ['brokerage load'], 'publication projection without shipper rate fields']],
  reviews: [['COVERAGE', 'NEGOTIATING', 'Accept carrier offer?', ['ACCEPT', 'COUNTER', 'DECLINE']]],
  approvals: [['CARRIER_ACCEPTS_COUNTER', 'OFFER_DECISION', 'Accept counter rate?', ['ACCEPT', 'DECLINE']]],
  artifacts: [['RATE_CON_LB', 'Rate confirmation', 'DOCUMENT', 'AIO brokerage', 'VAULT › Loads']],
  vault: 'VAULT › Loads',
  inbox: [['OFFER_DECISION', 'Counter offer on load {#}']],
  activity: [['BOOKED', 'Load {#} booked from Load Board']],
  notify: [['BROWSING', 'New loads match your lanes']],
  tasks: [['NEGOTIATING', 'Review carrier offer on {load}']],
  next: 'Booked load continues in Operations / brokerage carrier payables.',
  upstream: ['AIO.BROKERAGE (publisher)', 'AIO.ROAD_READY (eligibility)'],
  downstream: ['AIO.BROKERAGE (coverage)', 'AIO.DISPATCH_OPERATIONS', 'AIO.VAULT'],
  relationships: [['AIO.BROKERAGE', 'BOOKED', 'HANDS_OFF_TO', 'load appears in Operations with rate con', 'load covered in brokerage', { BROKERAGE: 'coverage recorded' }, 'opportunity card becomes a booked load']],
  public: { applicable: false, reason: 'Authenticated carrier surface; publicly described only inside Dispatch / Operations marketing.' },
  client: {
    entry_point: 'Operations › Load Board',
    primary_task: 'Find a fitting load and book it.',
    sees_first: 'Best-fit opportunities for the truck with rate, miles and pickup.',
    must_provide: ['offer / acceptance'],
    input_methods: ['FILTER', 'SEND OFFER', 'ACCEPT'],
    system_already_knows: ['truck + lanes', 'eligibility'],
    ready_signals: ['fit score'],
    needs_you: ['counter decisions'],
    under_review: ['offers with AIO'],
    approves: ['counter offers'],
    completion_looks_like: 'Load booked with rate con.',
    artifacts_received: ['Rate confirmation'],
    what_happens_next: 'Load runs in Operations.',
  },
  staff: {
    client_context: ['carrier eligibility + history'],
    work_queue: 'Brokerage coverage queue',
    status_model: [],
    blockers: ['ineligible carrier'],
    missing_inputs: ['carrier documents'],
    system_flags: ['rate below floor', 'eligibility gaps'],
    human_review: ['carrier offer review'],
    corrections: ['withdraw / republish load'],
    approval: ['offer acceptance'],
    overrides: ['manual coverage'],
    operational_actions: ['ACCEPT OFFER', 'COUNTER', 'PUBLISH', 'WITHDRAW'],
    artifact_generation: ['rate confirmation'],
    completion: 'Load covered.',
    hub_buckets: { NEEDS_REVIEW: ['NEGOTIATING'], AWAITING_CLIENT: ['OFFER_DECISION'], COMPLETE: ['BOOKED'] },
    mirror_not_copy: 'Staff see coverage across loads with margin; carriers never see shipper pricing.',
  },
  system: {
    ingestion: ['published brokerage loads'],
    validation: ['carrier eligibility', 'projection strips shipper rate fields'],
    derivation: ['fit score'],
    state_transitions: ['published → offer → booked → closed'],
    next_cycle_creation: 'New matches notify as loads publish.',
    failure_handling: ['withdrawn load → unavailable state'],
  },
  metaphor: 'OPPORTUNITY BOARD',
  metaphor2: 'negotiation at the counter',
  archetype: ['MATCHING_BOARD', 'DECISION_WINDOW'],
  object: 'THE OPPORTUNITY (lane, rate, fit)',
  objects: ['offers', 'fit score'],
  composition: ['Best fit leads; each opportunity shows lane, rate, miles, pickup.', 'Negotiation opens as a decision window on the opportunity.'],
  hierarchy: {
    CLIENT: ih('Is there a load that fits my truck?', 'Best-fit opportunities', 'Offer / book', 'Fit reasons', 'Not eligible', 'SEND OFFER', 'Booked with rate con'),
    FOUNDER_STAFF: ih('Which loads need coverage?', 'Uncovered loads', 'Review offers', 'Margin', 'Ineligible carriers', 'ACCEPT · COUNTER', 'Covered'),
  },
  grammar: [['SEND OFFER', 'CLIENT', 'request a load at a rate', 'NEGOTIATING'], ['ACCEPT', 'CLIENT', 'accept a counter', 'BOOKED'], ['COUNTER', 'FOUNDER_STAFF', 'counter a carrier offer', 'OFFER_DECISION']],
  emotion: { CLIENT: 'I can find good freight fast.', FOUNDER_STAFF: 'I can cover loads with eligible carriers.' },
  density: 'DENSE',
  viewports: { mobile: ['card list of best fits', 'filters as a sheet'], tablet: ['list + detail', 'two columns'], desktop: ['board with filters and detail', 'table + panel'] },
  ctas: { public: null, client: 'SEND OFFER', staff: 'ACCEPT OFFER' },
  avoid: ['shipper rate leakage', 'generic load board noise without fit'],
  e2e: {
    journey: 'CARRIER → LOAD BOARD → OFFER → COUNTER → BOOKED → OPERATIONS',
    not_applicable: { PUBLIC_DISCOVERY: 'authenticated surface' },
    expect: {
      CLIENT_ENTRY: ['CLIENT', 'portal/load-board', 'open board', ['best-fit loads', 'no shipper rate fields']],
      CLIENT_ACTION: ['CLIENT', 'portal/load-board/:id', 'send offer', ['offer pending']],
      SYSTEM_PROCESSING: ['SYSTEM', 'publication projection', 'eligibility + projection', ['ineligible carriers blocked']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/brokerage', 'counter', ['counter sent']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/load-board/:id', 'accept counter', ['booked']],
      ARTIFACT_CREATION: ['SYSTEM', 'load', 'issue rate con', ['rate con attached']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'operations', 'hand off', ['load appears in Operations']],
      COMPLETION: ['CLIENT', 'portal/operations', 'view', ['booked load']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open load', ['rate con filed']],
      NEXT_STEP: ['CLIENT', 'portal/load-board', 'browse', ['more matches']],
    },
  },
  structure: { routes: [['CLIENT', 'portal/load-board/*'], ['FOUNDER_STAFF', 'office/brokerage/*']], data: ['publication projection (projectCarrierLoadResult)', 'canonical Load'], evidence: ['docs/structural-completion/AIO_CANONICAL_PRODUCT_GRAPH.md (F08: 1 material node)', 'docs/structural-completion/AIO_ROLE_PROJECTION_MAP.md'] },
  functional_pct: 68,
  activation: 'tied to brokerage — PAUSED (business activation required)',
  code: ['src/freight/*'],
  // 1 material node in the graph and brokerage paused: negotiation rules are not yet sourced
  declared: 'EXPERIENCE_DRAFTED',
  related: ['AIO.BROKERAGE', 'AIO.DISPATCH_OPERATIONS'],
  open_questions: ['Negotiation policy (counter rules, rate floors), carrier eligibility criteria and publication cadence are not in source.', 'Depends on brokerage business activation (PAUSED).'],
});

export const AIO_BROKERAGE = aioFeature({
  id: 'AIO.BROKERAGE',
  name: 'Brokerage (Shipper)',
  family: 'F09 BROKERAGE',
  purpose: 'Arrange freight for shippers: request → quote → booked load → carrier coverage → delivery → billing.',
  promise: 'Ship with AIO: one request, a quote, a covered load, and visibility to delivery.',
  value: 'A single desk for freight with honest status and documents; shippers never see carrier pay.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['SHIPPER (client projection)', 'network carriers (offers / payables)'],
  entries: {
    public: ['Shipper services page', 'services/shipper-services', 'freight quote CTA'],
    client: ['Shipper portal', 'shipper/*', 'shipment request / quote'],
    staff: ['Office brokerage', 'office/brokerage/*', 'shipment request received'],
    system: ['brokerage workflow', 'capability gate + request'],
  },
  states: [
    ['NOT_ONBOARDED', 'Not set up', 'EMPTY', 'Set up shipping with AIO', 'No shipper profile'],
    ['REQUESTED', 'Shipment requested', 'ACTIVE', 'Request received', 'Quote needed'],
    ['QUOTE_READY', 'Quote ready', 'APPROVAL', 'Accept your quote', 'Awaiting shipper', { CLIENT: 'ACCEPT QUOTE', FOUNDER_STAFF: 'FOLLOW UP' }],
    ['COVERING', 'Covering', 'REVIEW', 'AIO is assigning a carrier', 'Coverage in progress'],
    ['IN_TRANSIT', 'In transit', 'REVIEW', 'On the way', 'In transit'],
    ['DELIVERED', 'Delivered', 'COMPLETE', 'Delivered — POD available', 'Delivered'],
    ['BILLED', 'Billed', 'ARCHIVED', 'Invoice issued', 'Shipper billed'],
    ['EXCEPTION', 'Exception', 'BLOCKED', 'Your shipment needs attention', 'Exception'],
    ['CANCELLED', 'Cancelled', 'ERROR', 'Shipment cancelled', 'Cancelled'],
  ],
  transitions: [
    ['NOT_ONBOARDED', 'REQUESTED', 'shipper onboarded + request', 'CLIENT'],
    ['REQUESTED', 'QUOTE_READY', 'quote issued', 'FOUNDER_STAFF'],
    ['QUOTE_READY', 'COVERING', 'quote accepted → canonical load', 'CLIENT'],
    ['COVERING', 'IN_TRANSIT', 'carrier booked + picked up', 'FOUNDER_STAFF'],
    ['IN_TRANSIT', 'EXCEPTION', 'delay / issue', 'FOUNDER_STAFF'],
    ['EXCEPTION', 'IN_TRANSIT', 'resolved', 'FOUNDER_STAFF'],
    ['IN_TRANSIT', 'DELIVERED', 'POD received', 'FOUNDER_STAFF'],
    ['DELIVERED', 'BILLED', 'invoice issued', 'SYSTEM'],
    ['QUOTE_READY', 'CANCELLED', 'declined / expired', 'CLIENT'],
  ],
  anchors: { start: 'REQUESTED', success: 'DELIVERED', blocked: 'EXCEPTION', errors: ['CANCELLED'], empty: 'NOT_ONBOARDED', complete: 'BILLED' },
  inputs: [['SHIPMENT', 'Shipment details (lane, dates, freight)', ['ENTER', 'REPEAT SHIPMENT'], 'quote'], ['QUOTE_ACCEPTANCE', 'Quote acceptance', ['ACCEPT', 'DECLINE'], 'booking']],
  derivations: [['QUOTE', 'shipper quote', ['shipment'], 'brokerageCalculations.ts'], ['MARGIN', 'gross margin (staff only)', ['shipper charge', 'carrier pay'], 'separate brokerage financial domain']],
  reviews: [['QUOTE_REVIEW', 'REQUESTED', 'Issue quote?', ['ISSUE QUOTE', 'NEED INFO']], ['COVERAGE', 'COVERING', 'Assign carrier', ['BOOK CARRIER']]],
  approvals: [['ACCEPT_QUOTE', 'QUOTE_READY', 'Accept quote?', ['ACCEPT', 'DECLINE']]],
  overrides: [['MANUAL_COVERAGE', 'COVERING', 'Assign carrier manually', ['ASSIGN']]],
  artifacts: [['QUOTE_DOC', 'Freight quote', 'DOCUMENT', 'brokerage', 'VAULT › Shipments', ['CLIENT', 'FOUNDER_STAFF']], ['SHIPPER_POD', 'Proof of delivery', 'DOCUMENT', 'carrier', 'VAULT › Shipments'], ['SHIPPER_INVOICE', 'Shipper invoice', 'INVOICE', 'brokerage billing', 'VAULT › Shipments']],
  vault: 'VAULT › Shipments',
  inbox: [['QUOTE_READY', 'Your quote is ready'], ['EXCEPTION', 'Shipment {#} needs attention']],
  activity: [['COVERING', 'Quote accepted'], ['DELIVERED', 'Shipment delivered']],
  notify: [['IN_TRANSIT', 'Shipment picked up'], ['DELIVERED', 'Shipment delivered']],
  tasks: [['REQUESTED', 'Quote shipment for {shipper}'], ['COVERING', 'Cover load {#}']],
  next: 'Repeat or recurring freight can be requested from the delivered shipment.',
  upstream: ['brokerage capability gate (business activation)'],
  downstream: ['AIO.LOAD_BOARD (publication)', 'AIO.FACTORING (carrier payables flags)', 'AIO.BOOKKEEPING (brokerage handoff)', 'AIO.VAULT'],
  relationships: [['AIO.LOAD_BOARD', 'COVERING', 'FEEDS', 'none (shipper sees “assigning a carrier”)', 'load published to carriers', { LOAD_BOARD: 'carrier-safe publication' }, 'shipper status: covering'], ['AIO.BOOKKEEPING', 'BILLED', 'FEEDS', 'invoice in shipper billing', 'brokerage bookkeeping handoff', { BOOKKEEPING: 'brokerageBookkeepingHandoff' }, 'none']],
  public: {
    discovery: ['Shipper services', 'freight quote CTA'],
    must_understand: ['AIO arranges carriers for your freight', 'you get a quote first', 'status and POD in your portal'],
    who_its_for: 'Shippers with truckload freight.',
    what_we_handle: ['quoting', 'carrier coverage', 'tracking', 'documents + invoice'],
    what_client_provides: ['shipment details', 'quote acceptance'],
    how_it_works: ['Request', 'Quote', 'Accept', 'AIO covers', 'Delivered', 'Invoice'],
    outcome: 'Delivered freight with POD and invoice.',
    timing: 'Per shipment.',
    pricing_relationship: 'Quoted per shipment.',
    cta: 'Get a Freight Quote',
    workspace_continuity: 'Shipper portal mirrors the six public steps.',
  },
  client: {
    entry_point: 'Shipper portal',
    primary_task: 'Request, accept the quote, follow the shipment.',
    sees_first: 'Active shipments and any quote awaiting acceptance.',
    must_provide: ['shipment details', 'acceptance'],
    input_methods: ['ENTER', 'REPEAT SHIPMENT', 'ACCEPT'],
    system_already_knows: ['shipper profile', 'past lanes'],
    ready_signals: ['quote ready'],
    needs_you: ['quote acceptance', 'exceptions'],
    under_review: ['coverage', 'in transit'],
    approves: ['quote'],
    completion_looks_like: 'Delivered with POD; invoice issued.',
    artifacts_received: ['Freight quote', 'Proof of delivery', 'Shipper invoice'],
    what_happens_next: 'Repeat shipment offered.',
  },
  staff: {
    client_context: ['shipper profile', 'lanes', 'credit / billing'],
    work_queue: 'Brokerage desk (shipments × coverage)',
    status_model: [],
    blockers: ['quote pending', 'uncovered load', 'exceptions'],
    missing_inputs: ['shipment details'],
    system_flags: ['margin below floor', 'capability gate'],
    human_review: ['quote', 'carrier assignment'],
    corrections: ['re-quote', 'reassign carrier'],
    approval: ['shipper quote acceptance'],
    overrides: ['manual coverage'],
    operational_actions: ['ISSUE QUOTE', 'PUBLISH', 'BOOK CARRIER', 'LOG EXCEPTION', 'INVOICE'],
    artifact_generation: ['quote', 'rate con', 'invoice'],
    completion: 'Delivered, billed, carrier payable recorded.',
    hub_buckets: { NEEDS_REVIEW: ['REQUESTED'], AWAITING_CLIENT: ['QUOTE_READY'], AWAITING_PROVIDER: ['COVERING'], BLOCKED: ['EXCEPTION'], COMPLETE: ['DELIVERED', 'BILLED'] },
    mirror_not_copy: 'Staff see shipper charge, carrier pay and margin per load — never exposed to shippers or carriers.',
  },
  system: {
    ingestion: ['shipment requests'],
    validation: ['capability gate', 'shipper privacy projection'],
    derivation: ['quote', 'margin', 'canonical load'],
    state_transitions: ['request → quote → covered → in transit → delivered → billed'],
    next_cycle_creation: 'Recurring freight requests can repeat a delivered shipment.',
    failure_handling: ['exception owner + shipper message', 'capability gate closed → paused notice'],
  },
  metaphor: 'SHIPMENT LIFECYCLE',
  metaphor2: 'from request to delivered',
  archetype: ['PIPELINE', 'DECISION_WINDOW'],
  object: 'THE SHIPMENT (lane, dates, status)',
  objects: ['quote', 'carrier coverage', 'POD', 'invoice'],
  composition: ['Shipment lifecycle as a horizontal pipeline; current stage leads.', 'Quote acceptance is a decision window.'],
  hierarchy: {
    CLIENT: ih('Where is my freight?', 'Shipment stage', 'Accept quote / follow', 'ETA', 'Exception', 'ACCEPT QUOTE', 'Delivered + POD'),
    FOUNDER_STAFF: ih('Which shipments need quoting, coverage or attention?', 'Pipeline stage counts', 'Quote / cover / resolve', 'Margin', 'Exception', 'ISSUE QUOTE · BOOK CARRIER', 'Billed + payable'),
  },
  grammar: [['REQUEST', 'CLIENT', 'request a shipment', 'REQUESTED'], ['ACCEPT QUOTE', 'CLIENT', 'accept', 'COVERING'], ['ISSUE QUOTE', 'FOUNDER_STAFF', 'send quote', 'QUOTE_READY'], ['BOOK CARRIER', 'FOUNDER_STAFF', 'cover the load', 'IN_TRANSIT']],
  emotion: { PUBLIC: 'I can hand AIO my freight with confidence.', CLIENT: 'I always know where my shipment is.', FOUNDER_STAFF: 'I see every shipment and its margin.' },
  density: 'BALANCED',
  viewports: { mobile: ['shipment status + quote decision', 'list → detail'], tablet: ['pipeline + detail', 'two columns'], desktop: ['pipeline board', 'stages as columns'] },
  ctas: { public: 'GET A FREIGHT QUOTE', client: 'ACCEPT QUOTE', staff: 'ISSUE QUOTE' },
  avoid: ['exposing carrier pay / margin to shippers', 'merging dispatch and brokerage queues'],
  e2e: {
    journey: 'PUBLIC → QUOTE → ACCEPT → COVERED → DELIVERED → BILLED',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'services/shipper-services', 'open page', ['quote CTA', 'six steps']],
      CLIENT_ENTRY: ['CLIENT', 'shipper/*', 'open portal', ['shipments + quotes']],
      CLIENT_ACTION: ['CLIENT', 'shipper/request', 'request shipment', ['request created']],
      SYSTEM_PROCESSING: ['SYSTEM', 'brokerage workflow', 'canonical load', ['shipper projection hides carrier pay']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/brokerage', 'quote + cover', ['margin visible to staff only']],
      CLIENT_APPROVAL: ['CLIENT', 'shipper/quotes', 'accept', ['load created']],
      ARTIFACT_CREATION: ['SYSTEM', 'shipment', 'POD + invoice', ['documents attached']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'load board · bookkeeping', 'propagate', ['published to carriers', 'bookkeeping handoff']],
      COMPLETION: ['CLIENT', 'shipper/*', 'view', ['DELIVERED']],
      ARCHIVE: ['CLIENT', 'shipper documents', 'open', ['POD + invoice filed']],
      NEXT_STEP: ['CLIENT', 'shipper/*', 'repeat', ['repeat shipment available']],
    },
  },
  structure: { routes: [['PUBLIC', 'services/shipper-services'], ['SHIPPER', 'shipper/*'], ['CLIENT', 'portal/brokerage/* (carrier offers / payables)'], ['FOUNDER_STAFF', 'office/brokerage/*']], data: ['brokerageTypes.ts', 'brokerageWorkflow.ts', 'shipperProfiles'], evidence: ['docs/BROKERAGE_SYSTEM.md', 'src/brokerage/*'] },
  functional_pct: 68,
  activation: 'brokerage PAUSED — BUSINESS ACTIVATION REQUIRED (not publicly enabled)',
  code: ['src/brokerage/*', 'src/shipper/*'],
  // public page cannot go live until business activation; the public perspective is drafted against that gate
  declared: 'EXPERIENCE_DRAFTED',
  related: ['AIO.LOAD_BOARD', 'AIO.BOOKKEEPING', 'AIO.FACTORING'],
  open_questions: ['Brokerage is PAUSED pending business activation (authority / bond / licensing) — the public experience cannot be finalised.', 'Shipper credit terms and quote validity rules are not in source.'],
});

export const AIO_FLEETCARE = aioFeature({
  id: 'AIO.FLEETCARE',
  name: 'FleetCare',
  family: 'F14 FLEETCARE',
  purpose: 'Get a broken-down or due-for-service truck to a verified provider, through estimate and repair, into the vehicle record.',
  promise: 'Truck down? AIO finds a verified provider and tracks the repair to done.',
  value: 'Fewer hours down, verified providers, and a maintenance record per truck.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['FLEETCARE PROVIDER (role projection)', 'DRIVER'],
  entries: {
    public: ['FleetCare page', 'fleetcare', 'Services hub / provider sign-up'],
    client: ['FleetCare', 'portal/fleetcare/*', 'breakdown / service need'],
    staff: ['Office FleetCare', 'office/fleetcare/*', 'ticket submitted'],
    system: ['FleetCare matching', 'ticket submitted'],
  },
  states: [
    ['NO_TICKETS', 'No open tickets', 'EMPTY', 'Report a breakdown or book service', 'No tickets', { CLIENT: 'REPORT AN ISSUE', PUBLIC: 'LEARN ABOUT FLEETCARE' }],
    ['SUBMITTED', 'Submitted', 'ACTIVE', 'Finding a provider', 'Searching / matched'],
    ['PROVIDER_REVIEWING', 'Provider reviewing', 'REVIEW', 'A provider is reviewing', 'Provider reviewing'],
    ['ESTIMATE_DECISION', 'Estimate ready', 'APPROVAL', 'Approve the estimate?', 'Awaiting estimate approval', { CLIENT: 'APPROVE ESTIMATE', FOUNDER_STAFF: 'FOLLOW UP' }],
    ['IN_REPAIR', 'In repair', 'REVIEW', 'Repair in progress', 'In repair'],
    ['NO_PROVIDER', 'No provider yet', 'BLOCKED', 'AIO is still looking for a provider', 'Declined / no match'],
    ['COMPLETED', 'Repair complete', 'COMPLETE', 'Truck repaired — record saved', 'Job complete'],
    ['RECORDED', 'In vehicle record', 'ARCHIVED', 'Saved to the truck’s record', 'Closed; referral fee tracked'],
    ['DISPUTED', 'Disputed', 'ERROR', 'There is a problem with this job — AIO is mediating', 'Dispute'],
  ],
  transitions: [
    ['NO_TICKETS', 'SUBMITTED', 'client submits ticket', 'CLIENT'],
    ['SUBMITTED', 'PROVIDER_REVIEWING', 'matched provider reviewing', 'SYSTEM'],
    ['PROVIDER_REVIEWING', 'NO_PROVIDER', 'provider declined / none', 'SYSTEM'],
    ['NO_PROVIDER', 'PROVIDER_REVIEWING', 'manual assignment', 'FOUNDER_STAFF'],
    ['PROVIDER_REVIEWING', 'ESTIMATE_DECISION', 'estimate submitted', 'SYSTEM'],
    ['ESTIMATE_DECISION', 'IN_REPAIR', 'client approves', 'CLIENT'],
    ['IN_REPAIR', 'COMPLETED', 'provider completes job', 'SYSTEM'],
    ['IN_REPAIR', 'DISPUTED', 'dispute raised', 'CLIENT'],
    ['COMPLETED', 'RECORDED', 'service record written', 'SYSTEM'],
  ],
  anchors: { start: 'SUBMITTED', success: 'COMPLETED', blocked: 'NO_PROVIDER', errors: ['DISPUTED'], empty: 'NO_TICKETS', complete: 'RECORDED' },
  inputs: [['ISSUE', 'What is wrong + where + drivable?', ['DESCRIBE', 'TAKE PHOTO', 'SHARE LOCATION'], 'matching'], ['ESTIMATE_APPROVAL', 'Estimate approval', ['APPROVE', 'DECLINE'], 'repair start']],
  derivations: [['MATCH', 'provider shortlist', ['issue', 'location'], 'verified providers (ProviderVerificationStatus aio_verified)'], ['MAINT_INTEL', 'last service mileage / next due', ['service records'], 'fleetcareLoadIntelligence.ts']],
  reviews: [['ASSIGN', 'NO_PROVIDER', 'Assign a provider manually', ['ASSIGN']]],
  approvals: [['APPROVE_ESTIMATE', 'ESTIMATE_DECISION', 'Approve the estimate?', ['APPROVE', 'DECLINE']]],
  overrides: [['WAIVE_FEE', 'RECORDED', 'Waive / refund referral fee', ['WAIVE', 'REFUND']]],
  artifacts: [['ESTIMATE', 'Repair estimate', 'DOCUMENT', 'provider', 'VAULT › Vehicles › {unit}'], ['WORK_SUMMARY', 'Work summary + invoice', 'INVOICE', 'provider', 'VAULT › Vehicles › {unit}'], ['SERVICE_RECORD', 'Vehicle service record', 'RECORD', 'system', 'VAULT › Vehicles › {unit}']],
  vault: 'VAULT › Vehicles › {unit}',
  inbox: [['ESTIMATE_DECISION', 'Estimate ready for {unit}'], ['COMPLETED', '{unit} repair complete']],
  activity: [['SUBMITTED', 'FleetCare ticket submitted'], ['COMPLETED', 'Repair completed']],
  notify: [['PROVIDER_REVIEWING', 'Provider found'], ['ESTIMATE_DECISION', 'Approve estimate']],
  tasks: [['NO_PROVIDER', 'Find provider for {client} {unit}']],
  next: 'Next service due date is tracked from the record.',
  upstream: ['fleet profile', 'provider verification'],
  downstream: ['AIO.VAULT (vehicle record)', 'AIO.DISPATCH_OPERATIONS (truck availability)', 'AIO.FINANCES (referral fee — provider side)'],
  relationships: [['AIO.DISPATCH_OPERATIONS', 'IN_REPAIR', 'UPDATES_STATUS', 'truck shows “in repair” in Operations', 'truck unavailable on the board', { OPERATIONS: 'truck unavailable' }, 'truck chip greys'], ['AIO.VAULT', 'RECORDED', 'ARCHIVES_TO', 'service record under the truck', 'record complete', { VAULT: 'vehicle service record' }, 'ticket seals into vehicle record']],
  public: {
    discovery: ['Services hub', 'provider network page'],
    must_understand: ['AIO matches you with verified providers', 'you approve every estimate', 'records are kept per truck'],
    who_its_for: 'Carriers needing repairs / service; providers wanting AIO jobs.',
    what_we_handle: ['finding providers', 'coordinating estimate + repair', 'keeping service records'],
    what_client_provides: ['issue + location', 'estimate approval'],
    how_it_works: ['Report', 'Match', 'Estimate', 'Approve', 'Repair', 'Record'],
    outcome: 'Repaired truck with a record.',
    timing: 'Per job.',
    pricing_relationship: 'Provider bills the repair; AIO referral fee on the provider side.',
    cta: 'Report an Issue',
    workspace_continuity: 'Ticket screen follows the same six steps.',
  },
  client: {
    entry_point: 'FleetCare (or breakdown CTA)',
    primary_task: 'Get the truck fixed.',
    sees_first: 'The open ticket and its current step.',
    must_provide: ['issue details', 'location', 'estimate approval'],
    input_methods: ['DESCRIBE', 'TAKE PHOTO', 'SHARE LOCATION', 'APPROVE'],
    system_already_knows: ['truck + last service', 'preferred providers'],
    ready_signals: ['provider matched'],
    needs_you: ['estimate approval'],
    under_review: ['provider reviewing', 'repair'],
    approves: ['estimate'],
    completion_looks_like: 'Repair complete; record saved.',
    artifacts_received: ['Repair estimate', 'Work summary + invoice', 'Vehicle service record'],
    what_happens_next: 'Next service tracked.',
  },
  staff: {
    client_context: ['carrier + unit + location', 'provider history'],
    work_queue: 'FleetCare office queue',
    status_model: [],
    blockers: ['no provider', 'estimate pending'],
    missing_inputs: ['location / drivable status'],
    system_flags: ['provider documents expired', 'dispute'],
    human_review: ['manual provider assignment', 'dispute mediation'],
    corrections: ['reassign provider'],
    approval: ['client estimate approval'],
    overrides: ['waive / refund referral fee'],
    operational_actions: ['ASSIGN PROVIDER', 'MEDIATE', 'CLOSE'],
    artifact_generation: ['service record'],
    completion: 'Job complete; referral fee status recorded.',
    hub_buckets: { AWAITING_PROVIDER: ['PROVIDER_REVIEWING', 'IN_REPAIR'], AWAITING_CLIENT: ['ESTIMATE_DECISION'], BLOCKED: ['NO_PROVIDER', 'DISPUTED'], COMPLETE: ['COMPLETED', 'RECORDED'] },
    mirror_not_copy: 'Staff see provider network health, referral fees and disputes across tickets.',
  },
  system: {
    ingestion: ['tickets', 'provider estimates / completion'],
    validation: ['provider verification status'],
    derivation: ['matching', 'maintenance intelligence'],
    state_transitions: ['FleetCareTicketStatus: draft → submitted → searching → matched → provider_reviewing → … → completed'],
    next_cycle_creation: 'Next service due recommendation from mileage.',
    failure_handling: ['no provider → staff task', 'dispute → DISPUTED'],
  },
  metaphor: 'INCIDENT → PROVIDER → REPAIR → RECORD',
  metaphor2: 'roadside rescue with a paper trail',
  archetype: ['ROUTE', 'CASE_FILE'],
  object: 'THE TICKET (unit, issue, step)',
  objects: ['provider', 'estimate', 'service record'],
  composition: ['The ticket’s four-stage route leads; current stage emphasised.', 'Estimate approval is a decision window.'],
  hierarchy: {
    CLIENT: ih('When will my truck be fixed?', 'Ticket stage', 'Approve estimate', 'Provider + ETA', 'No provider yet', 'APPROVE ESTIMATE', 'Repair complete + record'),
    FOUNDER_STAFF: ih('Which tickets are stuck?', 'Tickets by stage', 'Assign / mediate', 'Provider health', 'No provider / dispute', 'ASSIGN PROVIDER', 'Closed with record'),
  },
  grammar: [['REPORT', 'CLIENT', 'submit ticket', 'SUBMITTED'], ['APPROVE ESTIMATE', 'CLIENT', 'approve', 'IN_REPAIR'], ['ASSIGN PROVIDER', 'FOUNDER_STAFF', 'manual match', 'PROVIDER_REVIEWING']],
  emotion: { PUBLIC: 'If my truck breaks, AIO has a plan.', CLIENT: 'My truck is being handled and I approve the cost.', FOUNDER_STAFF: 'No ticket is left without a provider.' },
  density: 'BALANCED',
  viewports: { mobile: ['emergency-first: report + status', 'big report CTA'], tablet: ['ticket + provider', 'two columns'], desktop: ['ticket board', 'columns per stage'] },
  ctas: { public: 'REPORT AN ISSUE', client: 'REPORT AN ISSUE', staff: 'ASSIGN PROVIDER' },
  avoid: ['marketplace shopping UI during a breakdown', 'hiding cost until after work'],
  e2e: {
    journey: 'REPORT → MATCH → ESTIMATE → APPROVE → REPAIR → RECORD',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'fleetcare', 'open page', ['six steps', 'verified providers']],
      CLIENT_ENTRY: ['CLIENT', 'portal/fleetcare', 'open', ['report CTA prominent']],
      CLIENT_ACTION: ['CLIENT', 'portal/fleetcare/new', 'report issue with photo + location', ['ticket submitted']],
      SYSTEM_PROCESSING: ['SYSTEM', 'matching', 'match provider', ['only verified providers']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/fleetcare', 'monitor / assign', ['stuck tickets surfaced']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/fleetcare/:id', 'approve estimate', ['repair starts']],
      ARTIFACT_CREATION: ['CLIENT', 'provider/fleetcare (FLEETCARE_PROVIDER projection)', 'complete job with summary', ['work summary attached']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'operations · vault', 'propagate', ['truck availability updated']],
      COMPLETION: ['CLIENT', 'portal/fleetcare/:id', 'view', ['complete']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open truck record', ['service record present']],
      NEXT_STEP: ['CLIENT', 'portal/fleetcare', 'view', ['next service due']],
    },
  },
  structure: { routes: [['PUBLIC', 'fleetcare'], ['CLIENT', 'portal/fleetcare/*'], ['FLEETCARE_PROVIDER', 'provider/fleetcare/* (guard gap)'], ['FOUNDER_STAFF', 'office/fleetcare/*']], data: ['fleetcareTypes.ts: FleetCareTicketStatus, ProviderVerificationStatus, ReferralFeeStatus'], evidence: ['src/fleetcare/fleetcareTypes.ts', 'docs/structural-completion/AIO_ROLE_PROJECTION_MAP.md'] },
  functional_pct: 61,
  activation: 'demo store (provider route guard is a known gap)',
  code: ['src/fleetcare/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.DISPATCH_OPERATIONS', 'AIO.VAULT'],
});

export const AIO_DRIVERLINK = aioFeature({
  id: 'AIO.DRIVERLINK',
  name: 'DriverLink',
  family: 'F15 DRIVERLINK',
  purpose: 'Match carriers with credentialed drivers: candidate → credential → approval → match → hire.',
  promise: 'Find drivers whose credentials AIO has checked, and hire with confidence.',
  value: 'Verified credentials and a clear hiring pipeline for both sides.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['DRIVER (role projection)', 'COMPANY (carrier client)'],
  entries: {
    public: ['DriverLink page', 'driverlink', 'driver sign-up / carrier hiring CTA'],
    client: ['DriverLink (company)', 'portal/driverlink/*', 'job posted / candidate matched'],
    staff: ['Office DriverLink', 'office/driverlink/*', 'credential uploaded / application'],
    system: ['DriverLink matching', 'profile / job change'],
  },
  states: [
    ['NO_JOBS', 'No openings', 'EMPTY', 'Post a driver opening', 'No jobs', { CLIENT: 'POST A JOB', PUBLIC: 'JOIN DRIVERLINK' }],
    ['PUBLISHED', 'Job published', 'ACTIVE', 'Matching drivers', 'Job published'],
    ['CREDENTIALS_PENDING', 'Credentials pending', 'BLOCKED', 'Candidates waiting on credential checks', 'Credential review'],
    ['CANDIDATES_READY', 'Candidates ready', 'APPROVAL', 'Review matched drivers', 'Awaiting company decision', { CLIENT: 'REVIEW CANDIDATES', FOUNDER_STAFF: 'NUDGE COMPANY' }],
    ['IN_PROCESS', 'In process', 'REVIEW', 'Interview / offer in progress', 'Application in progress'],
    ['HIRED', 'Hired', 'COMPLETE', 'Driver hired', 'Filled'],
    ['CLOSED', 'Closed', 'ARCHIVED', 'Job closed', 'Archived'],
    ['CREDENTIAL_REJECTED', 'Credential problem', 'ERROR', 'A candidate’s credential failed verification', 'Rejected / expired credential'],
  ],
  transitions: [
    ['NO_JOBS', 'PUBLISHED', 'job posted', 'CLIENT'],
    ['PUBLISHED', 'CREDENTIALS_PENDING', 'matches need verification', 'SYSTEM'],
    ['CREDENTIALS_PENDING', 'CANDIDATES_READY', 'credentials verified', 'FOUNDER_STAFF'],
    ['CREDENTIALS_PENDING', 'CREDENTIAL_REJECTED', 'credential rejected', 'FOUNDER_STAFF'],
    ['CANDIDATES_READY', 'IN_PROCESS', 'company invites', 'CLIENT'],
    ['IN_PROCESS', 'HIRED', 'offer accepted', 'CLIENT'],
    ['HIRED', 'CLOSED', 'job filled / closed', 'SYSTEM'],
  ],
  anchors: { start: 'PUBLISHED', success: 'HIRED', blocked: 'CREDENTIALS_PENDING', errors: ['CREDENTIAL_REJECTED'], empty: 'NO_JOBS', complete: 'CLOSED' },
  inputs: [['JOB', 'Job details', ['ENTER'], 'matching'], ['DRIVER_CREDENTIALS', 'Driver CDL / medical / MVR (driver side)', ['TAKE PHOTO', 'UPLOAD FILES'], 'verification']],
  derivations: [['MATCH_SCORE', 'candidate fit', ['job', 'driver profile'], 'DriverLink matching'], ['CREDENTIAL_STATUS', 'verification state', ['credentials'], 'DriverCredentialVerificationStatus']],
  reviews: [['VERIFY_CREDENTIAL', 'CREDENTIALS_PENDING', 'Is the credential valid?', ['VERIFY', 'REJECT']]],
  approvals: [['COMPANY_SELECTS', 'CANDIDATES_READY', 'Invite this driver?', ['INVITE', 'PASS']]],
  overrides: [['MANUAL_MATCH', 'PUBLISHED', 'Manually match a driver', ['MATCH']]],
  artifacts: [['CREDENTIAL_RECORD', 'Verified credential record', 'RECORD', 'staff verification', 'VAULT › Safety & Drivers'], ['OFFER', 'Offer / hire record', 'RECORD', 'company', 'VAULT › Safety & Drivers']],
  vault: 'VAULT › Safety & Drivers',
  inbox: [['CANDIDATES_READY', '{n} verified drivers match your job'], ['HIRED', 'Driver hired']],
  activity: [['PUBLISHED', 'Job published'], ['HIRED', 'Driver hired']],
  notify: [['CANDIDATES_READY', 'Candidates ready']],
  tasks: [['CREDENTIALS_PENDING', 'Verify credentials for {driver}']],
  next: 'Hired driver’s DQ file continues in Compliance & Safety.',
  upstream: ['driver profiles'],
  downstream: ['AIO.COMPLIANCE_SAFETY (DQ file)', 'AIO.VAULT'],
  relationships: [['AIO.COMPLIANCE_SAFETY', 'HIRED', 'HANDS_OFF_TO', 'DQ file started for the new driver', 'DQ work item', { COMPLIANCE: 'driver qualification file opened' }, 'candidate card becomes a driver file']],
  public: {
    discovery: ['DriverLink page', 'driver sign-up'],
    must_understand: ['drivers are credential-checked by AIO', 'companies post jobs and invite'],
    who_its_for: 'Carriers hiring drivers; CDL drivers looking for work.',
    what_we_handle: ['credential verification', 'matching', 'hiring pipeline'],
    what_client_provides: ['job details (company)', 'credentials (driver)'],
    how_it_works: ['Post / sign up', 'Verify', 'Match', 'Invite', 'Hire'],
    outcome: 'A hired, credentialed driver.',
    timing: 'Per job.',
    pricing_relationship: 'Not specified in current source — to be confirmed.',
    cta: 'Join DriverLink',
    workspace_continuity: 'Pipeline steps match the public explainer.',
  },
  client: {
    entry_point: 'DriverLink (company view)',
    primary_task: 'Hire a verified driver.',
    sees_first: 'Open jobs and verified candidates.',
    must_provide: ['job details', 'candidate decisions'],
    input_methods: ['ENTER', 'INVITE', 'PASS'],
    system_already_knows: ['company profile'],
    ready_signals: ['verified badge'],
    needs_you: ['candidate decisions'],
    under_review: ['credential checks'],
    approves: ['invites / hires'],
    completion_looks_like: 'Driver hired.',
    artifacts_received: ['Verified credential record', 'Offer / hire record'],
    what_happens_next: 'DQ file in Compliance & Safety.',
  },
  staff: {
    client_context: ['company + jobs', 'driver credentials'],
    work_queue: 'Credential verification queue',
    status_model: [],
    blockers: ['credentials pending'],
    missing_inputs: ['credential documents'],
    system_flags: ['expiring credentials', 'suspended driver'],
    human_review: ['credential verification'],
    corrections: ['request credential update'],
    approval: ['credential verification sign-off'],
    overrides: ['manual match'],
    operational_actions: ['VERIFY', 'REJECT', 'MATCH'],
    artifact_generation: ['credential record'],
    completion: 'Driver hired; DQ handoff.',
    hub_buckets: { NEEDS_REVIEW: ['CREDENTIALS_PENDING'], AWAITING_CLIENT: ['CANDIDATES_READY'], COMPLETE: ['HIRED'] },
    mirror_not_copy: 'Staff see credential queues across drivers; companies see candidates.',
  },
  system: {
    ingestion: ['jobs', 'driver profiles', 'credentials'],
    validation: ['credential verification status'],
    derivation: ['match score'],
    state_transitions: ['JobOpportunityStatus + DriverApplicationStatus'],
    next_cycle_creation: 'Expiring credentials re-enter verification.',
    failure_handling: ['rejected credential → candidate hidden + driver notified'],
  },
  metaphor: 'CANDIDATE → CREDENTIAL → APPROVAL → MATCH',
  metaphor2: 'a hiring pipeline with a verified gate',
  archetype: ['PIPELINE', 'MATCHING_BOARD'],
  object: 'THE JOB (opening, matched verified drivers)',
  objects: ['candidates', 'credentials'],
  composition: ['Pipeline by stage; verified gate visually distinct.', 'Candidates as a matching board.'],
  hierarchy: {
    CLIENT: ih('Do I have verified drivers for my job?', 'Pipeline stage', 'Review / invite', 'Credential status', 'Credentials pending', 'REVIEW CANDIDATES', 'Driver hired'),
    FOUNDER_STAFF: ih('Which credentials need verification?', 'Queue', 'Verify', 'Expiring', 'Rejected', 'VERIFY', 'Credential recorded'),
  },
  grammar: [['POST JOB', 'CLIENT', 'publish an opening', 'PUBLISHED'], ['INVITE', 'CLIENT', 'invite candidate', 'IN_PROCESS'], ['VERIFY', 'FOUNDER_STAFF', 'verify credential', 'CANDIDATES_READY']],
  emotion: { PUBLIC: 'Drivers here are checked.', CLIENT: 'I am choosing from verified drivers.', FOUNDER_STAFF: 'No unverified driver reaches a company.' },
  density: 'BALANCED',
  viewports: { mobile: ['candidate cards', 'swipe-free list'], tablet: ['pipeline + detail', 'two columns'], desktop: ['pipeline board', 'columns'] },
  ctas: { public: 'JOIN DRIVERLINK', client: 'REVIEW CANDIDATES', staff: 'VERIFY' },
  avoid: ['showing unverified candidates as hire-ready', 'dating-app swipe metaphors'],
  e2e: {
    journey: 'POST JOB → VERIFY → MATCH → INVITE → HIRE → DQ FILE',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'driverlink', 'open page', ['verified gate explained']],
      CLIENT_ENTRY: ['CLIENT', 'portal/driverlink', 'open', ['jobs + candidates']],
      CLIENT_ACTION: ['CLIENT', 'portal/driverlink/jobs/new', 'post job', ['published']],
      SYSTEM_PROCESSING: ['SYSTEM', 'matching', 'match', ['only verified candidates shown as ready']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/driverlink', 'verify credentials', ['verified']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/driverlink', 'invite', ['in process']],
      ARTIFACT_CREATION: ['SYSTEM', 'records', 'credential + hire record', ['records stored']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'compliance', 'DQ handoff', ['DQ file opened']],
      COMPLETION: ['CLIENT', 'portal/driverlink', 'view', ['HIRED']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open Safety & Drivers', ['records present']],
      NEXT_STEP: ['CLIENT', 'portal/driverlink', 'view', ['job closed; DQ file next']],
    },
  },
  structure: { routes: [['PUBLIC', 'driverlink'], ['CLIENT', 'portal/driverlink/*'], ['DRIVER', 'driver/driverlink/* (guard gap)'], ['FOUNDER_STAFF', 'office/driverlink/*']], data: ['driverlinkTypes.ts'], evidence: ['src/driverlink/driverlinkTypes.ts'] },
  functional_pct: 61,
  activation: 'demo store (driver route guard is a known gap)',
  code: ['src/driverlink/*'],
  // pricing for DriverLink is not sourced; the public pricing relationship stays an explicit gap
  declared: 'EXPERIENCE_DRAFTED',
  related: ['AIO.COMPLIANCE_SAFETY'],
  open_questions: ['Pricing model (who pays — company, driver, placement fee) is not in source.', 'The DRIVER projection needs its own client-side perspective (driver onboarding, credential upload, job applications); driver route guard is a known gap.'],
});
