/**
 * AIO platform families (F01 ENTRY · F02 GET STARTED · F05 MY OFFICE · F06 SERVICES · F16 VAULT · F17 INBOX ·
 * F18 ACCOUNT) and the AIO OFFICE role projection. These are the shared surfaces every service contract lands in
 * (vault, inbox, activity, attention, founder hub) — so their experience contracts define how cross-feature effects
 * are SEEN. Sources: CLIENT_COMMAND_CENTER.md, DOCUMENT_VAULT_SYSTEM.md, OFFICE_WORK_MODEL.md, NOTIFICATION_SYSTEM.md.
 */
import { aioFeature, ih } from './kit.js';

export const AIO_ENTRY = aioFeature({
  id: 'AIO.ENTRY',
  name: 'Entry — Home / About / Contact',
  family: 'F01 ENTRY',
  purpose: 'Show a carrier in seconds that AIO is the business office behind the truck, and route them into the right pathway.',
  promise: 'WHERE BUSINESS MEETS THE ROAD — from startup to every mile after.',
  value: 'A prospect finds their pathway (start, get road ready, keep running, get paid) without reading a services catalogue.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['shippers', 'drivers', 'providers (pathway routing)'],
  entries: {
    public: ['Homepage', '/', 'search / referral / social'],
    client: ['Sign in → My Office', 'portal', 'returning client'],
    staff: ['CRM lead capture', 'office CRM', 'contact form / pathway selection'],
    system: ['CRM lead capture', 'contact submitted / pathway chosen'],
  },
  states: [
    ['FIRST_VISIT', 'First visit', 'EMPTY', 'Find your pathway', 'Anonymous visitor', { PUBLIC: 'GET STARTED' }],
    ['PATHWAY_CHOSEN', 'Pathway chosen', 'ACTIVE', 'Your pathway', 'Lead with pathway'],
    ['CONTACTED', 'Contacted', 'REVIEW', 'AIO will reach out', 'Lead in CRM'],
    ['CONVERTED', 'Signed up', 'COMPLETE', 'Welcome — continue in your portal', 'Converted'],
    ['RETURNING', 'Returning client', 'ARCHIVED', 'Welcome back', 'Client'],
    ['UNAVAILABLE', 'Unavailable', 'ERROR', 'We could not load this — contact us', 'Error'],
    ['FOLLOW_UP_NEEDED', 'Follow-up needed', 'BLOCKED', 'We need a way to reach you', 'Incomplete contact'],
    ['CALL_BOOKED', 'Call booked', 'APPROVAL', 'Confirm your call time', 'Appointment pending'],
  ],
  transitions: [
    ['FIRST_VISIT', 'PATHWAY_CHOSEN', 'pathway selected', 'PUBLIC'],
    ['PATHWAY_CHOSEN', 'CONTACTED', 'contact submitted', 'PUBLIC'],
    ['CONTACTED', 'FOLLOW_UP_NEEDED', 'contact incomplete', 'SYSTEM'],
    ['CONTACTED', 'CALL_BOOKED', 'appointment proposed', 'FOUNDER_STAFF'],
    ['CALL_BOOKED', 'CONVERTED', 'sign up', 'PUBLIC'],
    ['PATHWAY_CHOSEN', 'CONVERTED', 'sign up', 'PUBLIC'],
    ['CONVERTED', 'RETURNING', 'next visit', 'CLIENT'],
  ],
  anchors: { start: 'FIRST_VISIT', success: 'CONVERTED', blocked: 'FOLLOW_UP_NEEDED', errors: ['UNAVAILABLE'], empty: 'FIRST_VISIT', complete: 'RETURNING' },
  inputs: [['PATHWAY', 'Pathway choice', ['TAP PATHWAY'], 'routing'], ['CONTACT', 'Contact details', ['ENTER'], 'follow-up']],
  derivations: [['LEAD_SCORE', 'lead routing', ['pathway', 'answers'], 'CRM conversion engine']],
  reviews: [['LEAD_TRIAGE', 'CONTACTED', 'Route lead to the right division', ['ROUTE', 'CALL']]],
  approvals: [['CONFIRM_CALL', 'CALL_BOOKED', 'Confirm call time', ['CONFIRM', 'RESCHEDULE']]],
  artifacts: [['LEAD', 'Lead record', 'RECORD', 'CRM', null, ['FOUNDER_STAFF']]],
  vault: null,
  inbox: [['CALL_BOOKED', 'Your call with AIO is booked']],
  activity: [['CONVERTED', 'Account created']],
  notify: [['CALL_BOOKED', 'Call reminder']],
  tasks: [['CONTACTED', 'Call lead {name}']],
  next: 'Get Started intake / roadmap.',
  upstream: ['marketing'],
  downstream: ['AIO.GET_STARTED', 'CRM'],
  relationships: [['AIO.GET_STARTED', 'PATHWAY_CHOSEN', 'HANDS_OFF_TO', 'pathway pre-fills Get Started', 'lead tagged with pathway', { GET_STARTED: 'intake pre-filled' }, 'pathway card expands into intake']],
  public: {
    discovery: ['search', 'referral', 'social', 'truck-stop / industry presence'],
    must_understand: ['AIO is the business office behind the truck', 'it covers startup, compliance, operations, money', 'you start from your situation'],
    who_its_for: 'New and established carriers, owner-operators, small fleets; also shippers, drivers, providers.',
    what_we_handle: ['business setup', 'road readiness', 'operations', 'finances'],
    what_client_provides: ['your situation (pathway)'],
    how_it_works: ['Pick your pathway', 'Get a roadmap', 'AIO takes it from there'],
    outcome: 'A clear next step into Get Started.',
    timing: 'Immediate.',
    pricing_relationship: 'Pathways lead to priced services and plans.',
    cta: 'Get Started',
    workspace_continuity: 'Pathways map directly to Get Started and the client’s My Office journey.',
  },
  client: {
    entry_point: 'Sign in from the homepage',
    primary_task: 'Get back to My Office.',
    sees_first: 'Sign-in and their pathway context.',
    must_provide: ['credentials'],
    input_methods: ['SIGN IN'],
    system_already_knows: ['account'],
    ready_signals: ['signed in'],
    needs_you: ['nothing beyond sign-in'],
    under_review: ['none'],
    approves: [],
    completion_looks_like: 'In My Office.',
    artifacts_received: ['none (entry surface)'],
    what_happens_next: 'My Office next action.',
  },
  staff: {
    client_context: ['lead pathway + answers'],
    work_queue: 'CRM lead queue',
    status_model: [],
    blockers: ['incomplete contact'],
    missing_inputs: ['phone / email'],
    system_flags: ['duplicate lead'],
    human_review: ['lead triage'],
    corrections: ['merge duplicates'],
    approval: ['appointment confirmation'],
    overrides: ['manual routing'],
    operational_actions: ['CALL', 'ROUTE', 'BOOK APPOINTMENT'],
    artifact_generation: ['lead record'],
    completion: 'Lead converted.',
    hub_buckets: { NEEDS_REVIEW: ['CONTACTED'], AWAITING_CLIENT: ['CALL_BOOKED', 'FOLLOW_UP_NEEDED'], COMPLETE: ['CONVERTED'] },
    mirror_not_copy: 'Staff see a lead pipeline, not the homepage.',
  },
  system: {
    ingestion: ['pathway', 'contact form'],
    validation: ['contact completeness', 'dedupe'],
    derivation: ['lead routing'],
    state_transitions: ['visit → pathway → contact → convert'],
    next_cycle_creation: 'Converted lead becomes an organisation with Get Started.',
    failure_handling: ['page error → contact fallback'],
  },
  metaphor: 'THE ROADSIDE OFFICE DOOR',
  metaphor2: 'pick your road',
  archetype: ['THRESHOLD', 'SHOWCASE'],
  object: 'THE PATHWAY (start · road ready · run · get paid)',
  objects: ['brand promise', 'pathways'],
  composition: ['Cinematic trucking context with the tagline; pathways are the only choices above the fold.'],
  hierarchy: {
    PUBLIC: ih('Is AIO for me?', 'Business office behind the truck', 'Pick a pathway', 'What AIO covers', 'none', 'GET STARTED', 'Pathway into Get Started'),
    CLIENT: ih('How do I get back to my office?', 'Signed in', 'Sign in', 'none', 'none', 'SIGN IN', 'In My Office'),
    FOUNDER_STAFF: ih('Which leads need contact?', 'Lead pipeline', 'Triage', 'Pathway mix', 'Incomplete contact', 'CALL', 'Converted'),
  },
  grammar: [['CHOOSE PATHWAY', 'PUBLIC', 'pick a pathway', 'PATHWAY_CHOSEN'], ['CONTACT', 'PUBLIC', 'submit contact', 'CONTACTED'], ['CALL', 'FOUNDER_STAFF', 'call lead']],
  emotion: { PUBLIC: 'This is the office I have needed behind my truck.', CLIENT: 'I am one tap from my office.', FOUNDER_STAFF: 'Every lead reaches the right desk.' },
  density: 'SPARSE',
  viewports: { mobile: ['tagline + pathway stack', 'hero → pathways'], tablet: ['hero + pathway grid', 'two rows'], desktop: ['cinematic hero + pathway row', 'full-bleed'] },
  ctas: { public: 'GET STARTED', client: 'SIGN IN', staff: 'CALL LEAD' },
  avoid: ['services wall above the fold', 'stock smiles', 'Frontal Slayer typography'],
  e2e: {
    journey: 'HOMEPAGE → PATHWAY → GET STARTED / CONTACT → CONVERTED',
    not_applicable: { ARCHIVE: 'entry creates no archived artifact' },
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', '/', 'open homepage', ['tagline', 'pathways above the fold']],
      CLIENT_ENTRY: ['CLIENT', '/ → portal', 'sign in', ['lands in My Office']],
      CLIENT_ACTION: ['PUBLIC', '/', 'choose pathway', ['routes to Get Started']],
      SYSTEM_PROCESSING: ['SYSTEM', 'CRM', 'capture lead', ['lead with pathway']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office CRM', 'triage', ['routed']],
      CLIENT_APPROVAL: ['PUBLIC', 'appointment', 'confirm call', ['confirmed']],
      ARTIFACT_CREATION: ['SYSTEM', 'CRM', 'lead record', ['record exists']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'get started', 'pre-fill', ['intake pre-filled']],
      COMPLETION: ['PUBLIC', 'signup', 'sign up', ['organisation created']],
      NEXT_STEP: ['CLIENT', 'get-started', 'continue', ['roadmap']],
    },
  },
  structure: { routes: [['PUBLIC', '/ · about · contact']], data: ['homePathways.ts', 'publicNavigation.ts', 'CRM lead capture'], evidence: ['src/data/homePathways.ts', 'docs/CRM_LEAD_CAPTURE.md'] },
  functional_pct: 55,
  activation: 'public live (demo persistence)',
  code: ['src/pages/*', 'src/data/homePathways.ts'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.GET_STARTED'],
});

export const AIO_GET_STARTED = aioFeature({
  id: 'AIO.GET_STARTED',
  name: 'Get Started — Intake / Roadmap / Service Plan',
  family: 'F02 GET STARTED',
  purpose: 'Turn a prospect’s situation into a personal roadmap and service plan, and create their organisation.',
  promise: 'Answer a few questions; AIO builds your roadmap.',
  value: 'A clear, honest list of what applies to you and what AIO will do — before paying for anything.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: [],
  entries: {
    public: ['Get Started', 'get-started', 'homepage pathway'],
    client: ['Roadmap', 'roadmap · service-plan', 'after intake'],
    staff: ['Intake review', 'office intake / CRM', 'request/submit'],
    system: ['roadmap engine', 'intake answers'],
  },
  states: [
    ['NOT_STARTED', 'Not started', 'EMPTY', 'Tell AIO about your business', 'No intake', { PUBLIC: 'GET STARTED' }],
    ['ANSWERING', 'Answering', 'ACTIVE', 'A few questions', 'Intake in progress'],
    ['ROADMAP_READY', 'Roadmap ready', 'APPROVAL', 'Review your roadmap and plan', 'Awaiting plan acceptance', { CLIENT: 'START MY PLAN', FOUNDER_STAFF: 'CALL' }],
    ['UNSURE_ITEMS', 'Needs a quick review', 'BLOCKED', 'Some answers need AIO’s review', 'Uncertain answers'],
    ['AIO_REVIEWING', 'AIO reviewing', 'REVIEW', 'AIO is reviewing your plan', 'Intake review'],
    ['PLAN_STARTED', 'Plan started', 'COMPLETE', 'Your plan is underway', 'Converted to requests'],
    ['IN_MY_OFFICE', 'In My Office', 'ARCHIVED', 'Track everything in My Office', 'Onboarded'],
    ['SUBMIT_FAILED', 'Submission problem', 'ERROR', 'We could not submit — try again', 'Error'],
  ],
  transitions: [
    ['NOT_STARTED', 'ANSWERING', 'start', 'PUBLIC'],
    ['ANSWERING', 'ROADMAP_READY', 'answers complete', 'SYSTEM'],
    ['ANSWERING', 'UNSURE_ITEMS', 'unsure answers', 'SYSTEM'],
    ['UNSURE_ITEMS', 'AIO_REVIEWING', 'submitted for review', 'PUBLIC'],
    ['AIO_REVIEWING', 'ROADMAP_READY', 'reviewed', 'FOUNDER_STAFF'],
    ['ROADMAP_READY', 'PLAN_STARTED', 'plan accepted', 'CLIENT'],
    ['PLAN_STARTED', 'IN_MY_OFFICE', 'onboarding complete', 'SYSTEM'],
    ['ANSWERING', 'SUBMIT_FAILED', 'submit error', 'SYSTEM'],
  ],
  anchors: { start: 'ANSWERING', success: 'PLAN_STARTED', blocked: 'UNSURE_ITEMS', errors: ['SUBMIT_FAILED'], empty: 'NOT_STARTED', complete: 'IN_MY_OFFICE' },
  inputs: [['SITUATION', 'Business situation answers', ['GUIDED QUESTIONS', 'NOT SURE'], 'roadmap']],
  derivations: [['ROADMAP', 'roadmap items + reasons', ['answers'], 'roadmapEngine.ts (e.g. “You were not sure about IFTA — this may need review”)'], ['PLAN', 'service plan + pricing', ['roadmap'], 'service catalog + pricing config']],
  reviews: [['INTAKE_REVIEW', 'AIO_REVIEWING', 'Resolve unsure answers', ['CONFIRM ROADMAP', 'CALL']]],
  approvals: [['ACCEPT_PLAN', 'ROADMAP_READY', 'Start this plan?', ['START', 'ADJUST']]],
  artifacts: [['ROADMAP_DOC', 'Personal roadmap', 'REPORT', 'roadmap engine', 'VAULT › Business & Formation'], ['SERVICE_PLAN', 'Service plan', 'DOCUMENT', 'plan builder', 'VAULT › Business & Formation']],
  vault: 'VAULT › Business & Formation',
  inbox: [['ROADMAP_READY', 'Your AIO roadmap is ready']],
  activity: [['PLAN_STARTED', 'Plan started']],
  notify: [['ROADMAP_READY', 'Roadmap ready']],
  tasks: [['AIO_REVIEWING', 'Review intake for {name}']],
  next: 'Accepted plan items become service requests tracked in My Office.',
  upstream: ['AIO.ENTRY'],
  downstream: ['AIO.SERVICES (requests)', 'AIO.ROAD_READY (profile seeded)', 'AIO.FINANCES (quotes)', 'AIO.MY_OFFICE'],
  relationships: [['AIO.SERVICES', 'PLAN_STARTED', 'OPENS', 'plan items appear as requests', 'requests in division queues', { SERVICES: 'requests created' }, 'roadmap items turn into tracked services'], ['AIO.ROAD_READY', 'PLAN_STARTED', 'FEEDS', 'Road Ready profile seeded from answers', 'profile created', { ROAD_READY: 'profile seeded' }, 'profile appears with progress']],
  public: {
    discovery: ['homepage pathways', 'service pages CTA'],
    must_understand: ['answers build a personal roadmap', '“not sure” is fine — AIO reviews it', 'nothing is purchased until you start a plan'],
    who_its_for: 'Anyone starting or reorganising a trucking business.',
    what_we_handle: ['building the roadmap', 'recommending services', 'reviewing unsure answers'],
    what_client_provides: ['answers'],
    how_it_works: ['Answer', 'See roadmap', 'Choose plan', 'AIO starts'],
    outcome: 'A roadmap + service plan.',
    timing: 'Minutes.',
    pricing_relationship: 'Plan shows prices / quote-required items before starting.',
    cta: 'Get Started',
    workspace_continuity: 'Roadmap items become the My Office service progress the client tracks.',
  },
  client: {
    entry_point: 'Roadmap after intake',
    primary_task: 'Review the roadmap and start the plan.',
    sees_first: 'The roadmap with reasons per item.',
    must_provide: ['answers', 'plan acceptance'],
    input_methods: ['GUIDED QUESTIONS', 'NOT SURE', 'ACCEPT'],
    system_already_knows: ['pathway'],
    ready_signals: ['roadmap complete'],
    needs_you: ['plan acceptance'],
    under_review: ['unsure answers'],
    approves: ['service plan'],
    completion_looks_like: 'Plan started; requests open.',
    artifacts_received: ['Personal roadmap', 'Service plan'],
    what_happens_next: 'Track in My Office.',
  },
  staff: {
    client_context: ['answers', 'unsure items'],
    work_queue: 'Intake review queue',
    status_model: [],
    blockers: ['unsure answers'],
    missing_inputs: ['incomplete answers'],
    system_flags: ['high-complexity intake'],
    human_review: ['intake review'],
    corrections: ['adjust roadmap'],
    approval: ['plan acceptance'],
    overrides: ['manual roadmap item'],
    operational_actions: ['CONFIRM ROADMAP', 'CALL'],
    artifact_generation: ['roadmap', 'plan'],
    completion: 'Plan started.',
    hub_buckets: { NEEDS_REVIEW: ['AIO_REVIEWING'], AWAITING_CLIENT: ['ROADMAP_READY'], READY_TO_LAUNCH: ['PLAN_STARTED'] },
    mirror_not_copy: 'Staff see intakes needing judgement, not the questionnaire.',
  },
  system: {
    ingestion: ['answers'],
    validation: ['required answers'],
    derivation: ['roadmap', 'plan'],
    state_transitions: ['answering → roadmap → plan started'],
    next_cycle_creation: 'Roadmap re-evaluates as the business changes.',
    failure_handling: ['submit failure → retry with saved answers'],
  },
  metaphor: 'ROADMAP BUILDER',
  metaphor2: 'your route from here',
  archetype: ['ROUTE', 'CONSULTATION'],
  object: 'THE ROADMAP (items with reasons)',
  objects: ['questions', 'plan'],
  composition: ['One question at a time; roadmap builds visibly as answers arrive.'],
  hierarchy: {
    PUBLIC: ih('What does my business need?', 'Roadmap progress', 'Answer', 'Items so far', '“Not sure” items', 'CONTINUE', 'Roadmap + plan'),
    CLIENT: ih('What is my plan?', 'Roadmap ready', 'Start plan', 'Items + prices', 'Unsure items', 'START MY PLAN', 'Plan started'),
    FOUNDER_STAFF: ih('Which intakes need judgement?', 'Review queue', 'Review', 'Complexity', 'Unsure answers', 'CONFIRM ROADMAP', 'Plan started'),
  },
  grammar: [['ANSWER', 'PUBLIC', 'answer a question', 'ANSWERING'], ['NOT SURE', 'PUBLIC', 'flag for review', 'UNSURE_ITEMS'], ['START MY PLAN', 'CLIENT', 'accept plan', 'PLAN_STARTED']],
  emotion: { PUBLIC: 'Someone finally laid out what I need.', CLIENT: 'I know exactly what AIO will do first.', FOUNDER_STAFF: 'I only touch intakes that need judgement.' },
  density: 'SPARSE',
  viewports: { mobile: ['one question per screen', 'progress → question'], tablet: ['question + roadmap preview', 'two columns'], desktop: ['questions + live roadmap', 'split'] },
  ctas: { public: 'GET STARTED', client: 'START MY PLAN', staff: 'CONFIRM ROADMAP' },
  avoid: ['long forms', 'upsell walls', 'legal conclusions'],
  e2e: {
    journey: 'PUBLIC → INTAKE → ROADMAP → PLAN → MY OFFICE',
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'get-started', 'open', ['nothing purchased until plan']],
      CLIENT_ENTRY: ['CLIENT', 'roadmap', 'open roadmap', ['items with reasons']],
      CLIENT_ACTION: ['PUBLIC', 'get-started', 'answer incl. not sure', ['roadmap builds']],
      SYSTEM_PROCESSING: ['SYSTEM', 'roadmap engine', 'derive', ['reasons per item']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office intake', 'review unsure', ['roadmap confirmed']],
      CLIENT_APPROVAL: ['CLIENT', 'service-plan', 'start plan', ['requests created']],
      ARTIFACT_CREATION: ['SYSTEM', 'vault', 'roadmap + plan stored', ['documents present']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'services · road ready', 'propagate', ['requests + profile']],
      COMPLETION: ['CLIENT', 'portal', 'view', ['plan underway']],
      ARCHIVE: ['CLIENT', 'portal/vault', 'open', ['roadmap filed']],
      NEXT_STEP: ['CLIENT', 'portal', 'next action', ['first service next action']],
    },
  },
  structure: { routes: [['PUBLIC', 'get-started · roadmap · service-plan · request/submit']], data: ['roadmapEngine.ts', 'roadmapTypes.ts', 'serviceNeedRecommendation.ts'], evidence: ['src/roadmap/roadmapEngine.ts', 'src/services/catalog/serviceNeedRecommendation.ts'] },
  functional_pct: 55,
  activation: 'live (demo persistence)',
  code: ['src/roadmap/*', 'src/intake/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.ENTRY', 'AIO.SERVICES', 'AIO.ROAD_READY'],
});

export const AIO_MY_OFFICE = aioFeature({
  id: 'AIO.MY_OFFICE',
  name: 'My Office — Client Command Center',
  family: 'F05 MY OFFICE',
  purpose: 'The client’s home: what to do next, what needs attention, and how the business is doing — without false confidence.',
  promise: 'Open AIO and know your next move.',
  value: 'One deterministic next action and a deduplicated attention list instead of a flat dashboard.',
  actors: ['CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['SHIPPER (slim slice)'],
  entries: {
    public: { applicable: false, reason: 'Authenticated home; publicly represented by the Entry pathways.' },
    client: ['My Office', 'portal', 'sign in'],
    staff: ['Client 360', 'office client view', 'client selected'],
    system: ['attention engine', 'any domain event'],
  },
  states: [
    ['NEW_CLIENT', 'Welcome', 'EMPTY', 'Your first steps', 'New org'],
    ['NEXT_ACTION', 'Next action', 'ACTIVE', 'Do this next', 'Active'],
    ['NEEDS_YOU', 'Needs you', 'BLOCKED', 'Items need you', 'Client-owed items'],
    ['AIO_WORKING', 'AIO is working', 'REVIEW', 'AIO is on it', 'Internal work'],
    ['DECISION_WAITING', 'Decision waiting', 'APPROVAL', 'A decision is waiting', 'Approval pending'],
    ['ALL_CLEAR', 'All clear', 'COMPLETE', 'Nothing needs you right now', 'Healthy'],
    ['QUIET_PERIOD', 'Quiet', 'ARCHIVED', 'Everything filed', 'No open work'],
    ['DATA_UNAVAILABLE', 'Data unavailable', 'ERROR', 'Some information could not load', 'Degraded'],
  ],
  transitions: [
    ['NEW_CLIENT', 'NEXT_ACTION', 'plan started', 'SYSTEM'],
    ['NEXT_ACTION', 'NEEDS_YOU', 'client-owed items', 'SYSTEM'],
    ['NEEDS_YOU', 'NEXT_ACTION', 'items resolved', 'CLIENT'],
    ['NEXT_ACTION', 'AIO_WORKING', 'nothing owed by client', 'SYSTEM'],
    ['AIO_WORKING', 'DECISION_WAITING', 'approval requested', 'SYSTEM'],
    ['DECISION_WAITING', 'AIO_WORKING', 'decided', 'CLIENT'],
    ['AIO_WORKING', 'ALL_CLEAR', 'work complete', 'SYSTEM'],
    ['ALL_CLEAR', 'QUIET_PERIOD', 'no upcoming work', 'SYSTEM'],
    ['NEXT_ACTION', 'DATA_UNAVAILABLE', 'source failed', 'SYSTEM'],
  ],
  anchors: { start: 'NEXT_ACTION', success: 'ALL_CLEAR', blocked: 'NEEDS_YOU', errors: ['DATA_UNAVAILABLE'], empty: 'NEW_CLIENT', complete: 'QUIET_PERIOD' },
  inputs: [['ACT_ON_ITEM', 'Act on the next item', ['TAP THROUGH'], 'routing to the owning feature']],
  derivations: [['NEXT_BEST', 'deterministic next action', ['all features'], 'ClientCommandCenterService'], ['ATTENTION', 'deduplicated attention list', ['all features'], 'CLIENT_ATTENTION_ENGINE']],
  reviews: [['CLIENT_360', 'AIO_WORKING', 'Is anything stuck for this client?', ['ESCALATE', 'NONE']]],
  approvals: [['ROUTE_TO_DECISION', 'DECISION_WAITING', 'Open the waiting decision', ['OPEN']]],
  artifacts: [['ACTIVITY_LOG', 'Activity log', 'RECORD', 'all features', null]],
  vault: null,
  inbox: [['NEEDS_YOU', '{n} items need you']],
  activity: [['*', 'all feature activity events (aggregated)']],
  notify: [['NEEDS_YOU', 'Digest of items needing you']],
  tasks: [['AIO_WORKING', 'Client 360 stuck-item review']],
  next: 'Always the single next best action from any feature.',
  upstream: ['every AIO feature (attention + activity events)'],
  downstream: ['owning features (deep links)'],
  relationships: [['AIO.INBOX', 'NEEDS_YOU', 'UPDATES_STATUS', 'Needs You mirrors Inbox action threads', 'client 360 owed items', { INBOX: 'action threads' }, 'attention count matches inbox']],
  public: { applicable: false, reason: 'Authenticated home.' },
  client: {
    entry_point: 'Sign in → My Office',
    primary_task: 'Do the next thing.',
    sees_first: 'The next action hero, then attention, then health.',
    must_provide: ['action on items'],
    input_methods: ['TAP THROUGH TO FEATURE'],
    system_already_knows: ['everything across features'],
    ready_signals: ['attention count', 'health summaries'],
    needs_you: ['aggregated client-owed items'],
    under_review: ['aggregated AIO-working items'],
    approves: ['decisions routed to features'],
    completion_looks_like: 'All clear.',
    artifacts_received: ['none directly (links to Vault)'],
    what_happens_next: 'Next action updates as features move.',
  },
  staff: {
    client_context: ['Client 360 across all features'],
    work_queue: 'Client 360 view',
    status_model: [],
    blockers: ['client-owed items aged'],
    missing_inputs: ['aggregated'],
    system_flags: ['stuck items', 'degraded sources'],
    human_review: ['stuck item review'],
    corrections: ['re-route work'],
    approval: ['n/a — decisions live in features'],
    overrides: ['escalate'],
    operational_actions: ['ESCALATE', 'MESSAGE CLIENT'],
    artifact_generation: ['none'],
    completion: 'Client healthy.',
    hub_buckets: { AWAITING_CLIENT: ['NEEDS_YOU', 'DECISION_WAITING'], NEEDS_REVIEW: ['AIO_WORKING'], COMPLETE: ['ALL_CLEAR'] },
    mirror_not_copy: 'Staff see a CONTROL ROOM per client (Client 360) with ageing and risk.',
  },
  system: {
    ingestion: ['all feature events'],
    validation: ['dedupe'],
    derivation: ['next action', 'attention', 'health'],
    state_transitions: ['recomputed on every event'],
    next_cycle_creation: 'n/a — continuous.',
    failure_handling: ['source failure → partial data with honest notice (no false confidence)'],
  },
  metaphor: 'THE OFFICE DESK',
  metaphor2: 'one next move',
  archetype: ['CONTROL_ROOM', 'QUEUE'],
  object: 'THE NEXT ACTION',
  objects: ['attention list', 'health summaries'],
  composition: ['Next action hero → attention → health; never a flat tile dashboard.'],
  hierarchy: {
    CLIENT: ih('What should I do next?', 'Next action', 'Do it', 'Attention + health', 'Items needing you', 'NEXT ACTION', 'All clear'),
    FOUNDER_STAFF: ih('Is this client stuck anywhere?', 'Client 360 risk', 'Unstick', 'Ageing items', 'Stuck', 'ESCALATE', 'Healthy'),
  },
  grammar: [['DO NEXT', 'CLIENT', 'open the next action'], ['ESCALATE', 'FOUNDER_STAFF', 'escalate a stuck item']],
  emotion: { CLIENT: 'I know my next move the moment I open AIO.', FOUNDER_STAFF: 'I see where any client is stuck.' },
  density: 'BALANCED',
  viewports: { mobile: ['next action first', 'hero → list'], tablet: ['hero + attention', 'two columns'], desktop: ['hero, attention, health', 'three regions'] },
  ctas: { public: null, client: 'NEXT ACTION', staff: 'ESCALATE' },
  avoid: ['flat dashboard of equal tiles', 'false confidence scores', 'combining financial domains'],
  e2e: {
    journey: 'SIGN IN → NEXT ACTION → FEATURE → ALL CLEAR',
    not_applicable: { PUBLIC_DISCOVERY: 'authenticated home', ARCHIVE: 'no artifacts of its own' },
    expect: {
      CLIENT_ENTRY: ['CLIENT', 'portal', 'open', ['next action hero']],
      CLIENT_ACTION: ['CLIENT', 'portal', 'tap next action', ['deep link to feature']],
      SYSTEM_PROCESSING: ['SYSTEM', 'attention engine', 'recompute', ['deduplicated attention']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'client 360', 'review', ['stuck items visible']],
      CLIENT_APPROVAL: ['CLIENT', 'portal', 'open decision', ['routes to the feature decision']],
      ARTIFACT_CREATION: ['SYSTEM', 'activity', 'log', ['activity entry']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'inbox', 'sync', ['needs-you matches inbox']],
      COMPLETION: ['CLIENT', 'portal', 'view', ['all clear']],
      NEXT_STEP: ['CLIENT', 'portal', 'view', ['next action updates']],
    },
  },
  structure: { routes: [['CLIENT', 'portal · activity · search'], ['FOUNDER_STAFF', 'office client 360']], data: ['ClientCommandCenterService', 'CLIENT_ATTENTION_ENGINE'], evidence: ['docs/CLIENT_COMMAND_CENTER.md', 'docs/CLIENT_ATTENTION_ENGINE.md'] },
  functional_pct: 68,
  activation: 'demo complete',
  code: ['src/portal/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.INBOX', 'AIO.VAULT'],
});

export const AIO_SERVICES = aioFeature({
  id: 'AIO.SERVICES',
  name: 'Services — Catalog / Requests',
  family: 'F06 SERVICES',
  purpose: 'Let a client discover any AIO service and request it, and track every request in customer-friendly states.',
  promise: 'Every AIO service in one place, with one way to request and track it.',
  value: 'Consistent request tracking (NOT STARTED · READY · IN PROGRESS · WAITING ON YOU · ALL IN ONE IS WORKING · WAITING EXTERNALLY · COMPLETE).',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: [],
  entries: {
    public: ['Services hub', 'services/*', 'navigation'],
    client: ['Services / Requests', 'portal/services · portal/requests', 'Road Ready GET HELP / roadmap'],
    staff: ['Division queues', 'office/* queues', 'request submitted'],
    system: ['service request engine', 'request submitted'],
  },
  states: [
    ['NO_REQUESTS', 'No requests', 'EMPTY', 'Browse services', 'None'],
    ['IN_PROGRESS', 'In progress', 'ACTIVE', 'Your requests', 'Open'],
    ['WAITING_ON_YOU', 'Waiting on you', 'BLOCKED', 'Requests need you', 'Waiting on customer'],
    ['ALL_IN_ONE_IS_WORKING', 'All In One is working', 'REVIEW', 'AIO is working', 'Internal'],
    ['QUOTE_DECISION', 'Quote decision', 'APPROVAL', 'Accept the quote to start', 'Quote pending', { CLIENT: 'ACCEPT QUOTE', FOUNDER_STAFF: 'FOLLOW UP' }],
    ['COMPLETE', 'Complete', 'COMPLETE', 'Done', 'Completed'],
    ['HISTORY', 'History', 'ARCHIVED', 'Past requests', 'Archived'],
    ['NOT_AVAILABLE', 'Not available', 'ERROR', 'This service is not available in your area yet', 'Jurisdiction unavailable / paused'],
  ],
  transitions: [
    ['NO_REQUESTS', 'QUOTE_DECISION', 'quote-required request', 'CLIENT'],
    ['NO_REQUESTS', 'IN_PROGRESS', 'request submitted', 'CLIENT'],
    ['QUOTE_DECISION', 'IN_PROGRESS', 'quote accepted', 'CLIENT'],
    ['IN_PROGRESS', 'WAITING_ON_YOU', 'needs client', 'FOUNDER_STAFF'],
    ['WAITING_ON_YOU', 'ALL_IN_ONE_IS_WORKING', 'client responds', 'CLIENT'],
    ['IN_PROGRESS', 'ALL_IN_ONE_IS_WORKING', 'work started', 'FOUNDER_STAFF'],
    ['ALL_IN_ONE_IS_WORKING', 'COMPLETE', 'completed', 'FOUNDER_STAFF'],
    ['COMPLETE', 'HISTORY', 'archived', 'SYSTEM'],
    ['NO_REQUESTS', 'NOT_AVAILABLE', 'jurisdiction / activation gate', 'SYSTEM'],
  ],
  anchors: { start: 'IN_PROGRESS', success: 'COMPLETE', blocked: 'WAITING_ON_YOU', errors: ['NOT_AVAILABLE'], empty: 'NO_REQUESTS', complete: 'HISTORY' },
  inputs: [['REQUEST', 'Service request details', ['ENTER', 'UPLOAD FILES'], 'service start']],
  derivations: [['AVAILABILITY', 'service availability', ['catalog', 'jurisdiction', 'activation'], 'serviceCatalog + SERVICE_ACTIVATION_MATRIX'], ['CUSTOMER_STATE', 'customer-friendly state', ['workflow state'], 'SERVICE_JOURNEYS mapping']],
  reviews: [['TRIAGE', 'IN_PROGRESS', 'Route to division', ['ROUTE']]],
  approvals: [['ACCEPT_QUOTE', 'QUOTE_DECISION', 'Accept quote?', ['ACCEPT', 'DECLINE']]],
  artifacts: [['REQUEST_RECORD', 'Service request record', 'RECORD', 'request engine', null]],
  vault: null,
  inbox: [['WAITING_ON_YOU', 'A request needs you']],
  activity: [['IN_PROGRESS', 'Service requested'], ['COMPLETE', 'Service complete']],
  notify: [['COMPLETE', 'Service complete']],
  tasks: [['IN_PROGRESS', 'Triage request from {client}']],
  next: 'Completed services update Road Ready and the Vault through their own contracts.',
  upstream: ['AIO.GET_STARTED', 'AIO.ROAD_READY'],
  downstream: ['every service contract', 'AIO.FINANCES (quotes)'],
  relationships: [['AIO.FINANCES', 'QUOTE_DECISION', 'DEPENDS_ON', 'quote shown in Money too', 'quote billable once accepted', { FINANCES: 'quote' }, 'quote card mirrors Money']],
  public: {
    discovery: ['navigation', 'search'],
    must_understand: ['what each service does', 'availability can depend on location', 'pricing model per service'],
    who_its_for: 'Carriers looking for a specific service.',
    what_we_handle: ['the catalogued services'],
    what_client_provides: ['request details'],
    how_it_works: ['Find', 'Request', 'Track'],
    outcome: 'A tracked request.',
    timing: 'Per service.',
    pricing_relationship: 'quote_required / fixed / plan per catalog entry.',
    cta: 'Request Assistance',
    workspace_continuity: 'Public service pages and portal requests share the same service ids and steps.',
  },
  client: {
    entry_point: 'Services / Requests',
    primary_task: 'Request and track services.',
    sees_first: 'Requests grouped by customer-friendly state.',
    must_provide: ['request details'],
    input_methods: ['ENTER', 'UPLOAD FILES'],
    system_already_knows: ['profile, Road Ready gaps'],
    ready_signals: ['availability'],
    needs_you: ['waiting-on-you requests'],
    under_review: ['AIO working'],
    approves: ['quotes'],
    completion_looks_like: 'Request complete.',
    artifacts_received: ['Service request record'],
    what_happens_next: 'The service’s own next step.',
  },
  staff: {
    client_context: ['org', 'request history'],
    work_queue: 'Division queues (OfficeWorkItem)',
    status_model: [],
    blockers: ['waiting on customer / external'],
    missing_inputs: ['request details'],
    system_flags: ['unavailable jurisdiction', 'paused service'],
    human_review: ['triage'],
    corrections: ['re-route'],
    approval: ['quote acceptance'],
    overrides: ['manual availability'],
    operational_actions: ['ROUTE', 'START', 'COMPLETE'],
    artifact_generation: ['request record'],
    completion: 'Completed.',
    hub_buckets: { NEEDS_REVIEW: ['IN_PROGRESS'], AWAITING_CLIENT: ['WAITING_ON_YOU', 'QUOTE_DECISION'], COMPLETE: ['COMPLETE'] },
    mirror_not_copy: 'Staff see division queues with waitingOn, not the catalog.',
  },
  system: {
    ingestion: ['requests'],
    validation: ['availability gates'],
    derivation: ['customer-friendly states'],
    state_transitions: ['raw workflow states mapped; never shown raw'],
    next_cycle_creation: 'Recurring services (renewals, quarterly filings) recreate requests.',
    failure_handling: ['unavailable → NOT_AVAILABLE with alternatives'],
  },
  metaphor: 'SERVICE COUNTER',
  metaphor2: 'one window for every service',
  archetype: ['INDEX', 'QUEUE'],
  object: 'THE REQUEST (service, customer-friendly state)',
  objects: ['catalog', 'requests'],
  composition: ['Requests by state lead for clients with open work; catalog leads when empty.'],
  hierarchy: {
    PUBLIC: ih('Does AIO do what I need?', 'Service list', 'Find + request', 'Availability', 'Not available', 'REQUEST', 'Request created'),
    CLIENT: ih('Where are my requests?', 'Requests by state', 'Act on waiting items', 'Quotes', 'Waiting on you', 'OPEN REQUEST', 'Complete'),
    FOUNDER_STAFF: ih('What is in my division queue?', 'Queue', 'Work requests', 'Waiting on', 'Customer wait', 'START', 'Completed'),
  },
  grammar: [['REQUEST', 'CLIENT', 'request a service', 'IN_PROGRESS'], ['ACCEPT QUOTE', 'CLIENT', 'accept', 'IN_PROGRESS'], ['ROUTE', 'FOUNDER_STAFF', 'route to division']],
  emotion: { PUBLIC: 'AIO covers what I need.', CLIENT: 'Every request is visible and moving.', FOUNDER_STAFF: 'My queue is clear and prioritised.' },
  density: 'BALANCED',
  viewports: { mobile: ['requests by state', 'stacked'], tablet: ['catalog + requests', 'two columns'], desktop: ['catalog index + request table', 'split'] },
  ctas: { public: 'REQUEST ASSISTANCE', client: 'OPEN REQUEST', staff: 'START' },
  avoid: ['raw workflow states', 'catalog wall when the client has open work'],
  e2e: {
    journey: 'CATALOG → REQUEST → QUOTE → TRACK → COMPLETE',
    not_applicable: { ARCHIVE: 'artifacts archive via the specific service contract' },
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'services/*', 'browse', ['availability + pricing model']],
      CLIENT_ENTRY: ['CLIENT', 'portal/services', 'open', ['requests by state']],
      CLIENT_ACTION: ['CLIENT', 'portal/requests', 'request', ['request created']],
      SYSTEM_PROCESSING: ['SYSTEM', 'request engine', 'gate + route', ['work item in division']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office queue', 'start', ['AIO working']],
      CLIENT_APPROVAL: ['CLIENT', 'portal/quotes', 'accept quote', ['in progress']],
      ARTIFACT_CREATION: ['SYSTEM', 'request', 'record', ['request record']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'service contract', 'hand off', ['service lifecycle begins']],
      COMPLETION: ['CLIENT', 'portal/requests', 'view', ['COMPLETE']],
      NEXT_STEP: ['CLIENT', 'portal', 'next action', ['service next step']],
    },
  },
  structure: { routes: [['PUBLIC', 'services/*'], ['CLIENT', 'portal/services · portal/requests'], ['FOUNDER_STAFF', 'office/* division queues']], data: ['serviceCatalog.ts (≈50 services)', 'SERVICE_ACTIVATION_MATRIX', 'ServiceJourney'], evidence: ['src/services/catalog/serviceCatalog.ts', 'docs/SERVICE_JOURNEYS.md'] },
  functional_pct: 57,
  activation: 'per service',
  code: ['src/services/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.GET_STARTED', 'AIO.FINANCES'],
});

export const AIO_VAULT = aioFeature({
  id: 'AIO.VAULT',
  name: 'Vault',
  family: 'F16 VAULT',
  purpose: 'The client’s secure business document hub — every requested, uploaded, verified and filed document, organised by the canonical taxonomy.',
  promise: 'Every document your business runs on, verified and findable.',
  value: 'Upload once; AIO verifies; every feature reads from the same record.',
  actors: ['CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: [],
  entries: {
    public: { applicable: false, reason: 'Private document hub.' },
    client: ['Vault', 'portal/vault · portal/documents', 'artifact filed / document requested'],
    staff: ['Office Document Center', 'office/documents', 'document uploaded'],
    system: ['vault storage + taxonomy', 'upload / artifact sealed'],
  },
  states: [
    ['EMPTY_VAULT', 'Empty', 'EMPTY', 'Add your first document', 'No documents'],
    ['ORGANISED', 'Organised', 'ACTIVE', 'Your documents', 'Normal'],
    ['REQUESTED', 'Requested', 'BLOCKED', 'AIO requested documents', 'Requested docs outstanding'],
    ['PENDING_VERIFICATION', 'Pending verification', 'REVIEW', 'AIO is verifying', 'Verification queue'],
    ['VERIFIED', 'Verified', 'COMPLETE', 'Verified', 'Verified'],
    ['SUPERSEDED', 'Superseded', 'ARCHIVED', 'Older version kept in history', 'Superseded'],
    ['REJECTED', 'Rejected', 'ERROR', 'Rejected — reason + replace', 'Rejected'],
    ['EXPIRING', 'Expiring', 'APPROVAL', 'Expiring — renew?', 'Expiring', { CLIENT: 'RENEW', FOUNDER_STAFF: 'REMIND' }],
  ],
  transitions: [
    ['EMPTY_VAULT', 'PENDING_VERIFICATION', 'upload', 'CLIENT'],
    ['ORGANISED', 'REQUESTED', 'document requested', 'FOUNDER_STAFF'],
    ['REQUESTED', 'PENDING_VERIFICATION', 'uploaded', 'CLIENT'],
    ['PENDING_VERIFICATION', 'VERIFIED', 'verified', 'FOUNDER_STAFF'],
    ['PENDING_VERIFICATION', 'REJECTED', 'rejected', 'FOUNDER_STAFF'],
    ['REJECTED', 'PENDING_VERIFICATION', 'replacement', 'CLIENT'],
    ['VERIFIED', 'EXPIRING', 'expiration window', 'SYSTEM'],
    ['VERIFIED', 'SUPERSEDED', 'newer version verified', 'SYSTEM'],
    ['VERIFIED', 'ORGANISED', 'filed', 'SYSTEM'],
  ],
  anchors: { start: 'ORGANISED', success: 'VERIFIED', blocked: 'REQUESTED', errors: ['REJECTED'], empty: 'EMPTY_VAULT', complete: 'VERIFIED' },
  inputs: [['DOCUMENT', 'Document', ['TAKE PHOTO', 'UPLOAD FILES'], 'records']],
  derivations: [['CATEGORY', 'taxonomy category + group', ['document type'], 'vaultTaxonomy.ts'], ['EXPIRY', 'expiration + renewal', ['document dates'], 'renewalService.ts']],
  reviews: [['VERIFY_DOC', 'PENDING_VERIFICATION', 'Verify document', ['VERIFY', 'REJECT']]],
  overrides: [['RECATEGORISE', 'ORGANISED', 'Recategorise document', ['RECATEGORISE']]],
  artifacts: [['DOCUMENT_RECORD', 'Document record (versions)', 'DOCUMENT', 'client / features', 'VAULT › {category}']],
  vault: 'VAULT (self)',
  inbox: [['REQUESTED', 'AIO requested {document}'], ['REJECTED', '{document} was rejected']],
  activity: [['VERIFIED', '{document} verified']],
  notify: [['EXPIRING', '{document} expiring']],
  tasks: [['PENDING_VERIFICATION', 'Verify {document} for {client}']],
  next: 'Verified documents feed Road Ready; expiring ones open renewals.',
  upstream: ['every feature that seals artifacts (e.g. AIO.IFTA quarter packets)'],
  downstream: ['AIO.ROAD_READY', 'AIO.RENEWALS', 'every feature that imports from the Vault'],
  relationships: [['AIO.ROAD_READY', 'VERIFIED', 'UPDATES_STATUS', 'Road Ready item verified', 'verification counts', { ROAD_READY: 'verified status' }, 'checklist completes'], ['AIO.RENEWALS', 'EXPIRING', 'OPENS', 'renewal appears', 'renewal item', { RENEWALS: 'renewal' }, 'expiring badge']],
  public: { applicable: false, reason: 'Private document hub.' },
  client: {
    entry_point: 'Vault',
    primary_task: 'Find, add and keep documents current.',
    sees_first: 'Taxonomy groups with requested / expiring items on top.',
    must_provide: ['requested documents'],
    input_methods: ['TAKE PHOTO', 'UPLOAD FILES'],
    system_already_knows: ['all sealed artifacts from features'],
    ready_signals: ['verified badges'],
    needs_you: ['requested', 'rejected', 'expiring'],
    under_review: ['pending verification'],
    approves: ['renewal decisions (routed)'],
    completion_looks_like: 'Everything verified and current.',
    artifacts_received: ['all feature artifacts'],
    what_happens_next: 'Renewals as items expire.',
  },
  staff: {
    client_context: ['documents by status'],
    work_queue: 'Office Document Center',
    status_model: [],
    blockers: ['requested docs outstanding'],
    missing_inputs: ['requested documents'],
    system_flags: ['expiring', 'file policy violations'],
    human_review: ['verification'],
    corrections: ['reject with reason'],
    approval: ['verification'],
    overrides: ['recategorise'],
    operational_actions: ['REQUEST', 'VERIFY', 'REJECT', 'SUPERSEDE'],
    artifact_generation: ['verification record'],
    completion: 'Verified.',
    hub_buckets: { NEEDS_REVIEW: ['PENDING_VERIFICATION'], AWAITING_CLIENT: ['REQUESTED', 'REJECTED'], COMPLETE: ['VERIFIED'] },
    mirror_not_copy: 'Staff see a verification DOCUMENT TABLE across clients.',
  },
  system: {
    ingestion: ['uploads', 'feature-sealed artifacts'],
    validation: ['file policy', 'type'],
    derivation: ['category', 'expiry'],
    state_transitions: ['upload ≠ verification'],
    next_cycle_creation: 'Expiry → renewal.',
    failure_handling: ['rejected → reason + replace', 'policy violation → blocked upload'],
  },
  metaphor: 'STRUCTURED RECORD ARCHIVE',
  metaphor2: 'the filing cabinet behind the office',
  archetype: ['CABINET', 'ARCHIVE', 'DOCUMENT_TABLE'],
  object: 'THE DOCUMENT (category, status, version)',
  objects: ['taxonomy groups', 'sealed packets (e.g. IFTA quarters)'],
  composition: ['Cabinet drawers by taxonomy group; requested / expiring float to the top.', 'Sealed packets (IFTA quarter) render as one folder object.'],
  hierarchy: {
    CLIENT: ih('Where is my document, and is it current?', 'Requested / expiring count', 'Upload / replace', 'Groups', 'Rejected / requested', 'UPLOAD', 'Verified + current'),
    FOUNDER_STAFF: ih('What needs verification?', 'Queue', 'Verify', 'Expiring', 'Requested outstanding', 'VERIFY', 'Verified'),
  },
  grammar: [['UPLOAD', 'CLIENT', 'add a document', 'PENDING_VERIFICATION'], ['VERIFY', 'FOUNDER_STAFF', 'verify', 'VERIFIED'], ['REJECT', 'FOUNDER_STAFF', 'reject', 'REJECTED']],
  emotion: { CLIENT: 'Everything is safe and findable.', FOUNDER_STAFF: 'Verification never piles up.' },
  density: 'BALANCED',
  viewports: { mobile: ['search + groups', 'list'], tablet: ['groups + preview', 'two columns'], desktop: ['cabinet + table + preview', 'three regions'] },
  ctas: { public: null, client: 'UPLOAD', staff: 'VERIFY' },
  avoid: ['generic file manager', 'implying upload = verified'],
  e2e: {
    journey: 'REQUEST → UPLOAD → VERIFY → FILED → EXPIRY → RENEWAL',
    not_applicable: { PUBLIC_DISCOVERY: 'private hub', CLIENT_APPROVAL: 'verification is a staff decision' },
    expect: {
      CLIENT_ENTRY: ['CLIENT', 'portal/vault', 'open', ['requested items first']],
      CLIENT_ACTION: ['CLIENT', 'portal/vault', 'upload', ['pending verification']],
      SYSTEM_PROCESSING: ['SYSTEM', 'vault', 'categorise', ['taxonomy applied']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/documents', 'verify', ['verified']],
      ARTIFACT_CREATION: ['SYSTEM', 'vault', 'version', ['version recorded']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'road ready', 'update', ['verified status']],
      COMPLETION: ['CLIENT', 'portal/vault/:id', 'view', ['VERIFIED']],
      ARCHIVE: ['SYSTEM', 'vault', 'supersede', ['old version in history']],
      NEXT_STEP: ['CLIENT', 'portal/renewals', 'view', ['expiring item renewal']],
    },
  },
  structure: { routes: [['CLIENT', 'portal/vault/* · portal/documents'], ['FOUNDER_STAFF', 'office/documents/vault/*']], data: ['vaultTypes.ts', 'vaultTaxonomy.ts', 'vaultConfig.ts'], evidence: ['docs/DOCUMENT_VAULT_SYSTEM.md', 'src/vault/vaultTaxonomy.ts'] },
  functional_pct: 66,
  activation: 'live (demo + storage abstraction)',
  code: ['src/vault/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.ROAD_READY', 'AIO.RENEWALS', 'AIO.IFTA'],
});

export const AIO_INBOX = aioFeature({
  id: 'AIO.INBOX',
  name: 'Inbox — Messages / Notifications / Appointments',
  family: 'F17 INBOX',
  purpose: 'Every conversation, request thread, notification and appointment between the client and AIO — action items first.',
  promise: 'Every conversation with AIO in one place, and you always know which ones need you.',
  value: 'Feature request threads resolve themselves when the work completes.',
  actors: ['CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: [],
  entries: {
    public: { applicable: false, reason: 'Private correspondence.' },
    client: ['Inbox', 'portal/messages · notifications · appointments', 'notification'],
    staff: ['Office inbox', 'office/inbox', 'client message'],
    system: ['communication + notification engines', 'feature events'],
  },
  states: [
    ['EMPTY_INBOX', 'Empty', 'EMPTY', 'No messages', 'None'],
    ['ACTION_THREADS', 'Needs you', 'BLOCKED', 'Threads need your reply / action', 'Awaiting client'],
    ['CONVERSATION', 'Conversation', 'ACTIVE', 'Messages', 'Open'],
    ['AIO_REPLYING', 'AIO replying', 'REVIEW', 'AIO will reply', 'Awaiting staff'],
    ['APPOINTMENT_PROPOSED', 'Appointment', 'APPROVAL', 'Confirm the appointment', 'Proposed', { CLIENT: 'CONFIRM', FOUNDER_STAFF: 'PROPOSE TIME' }],
    ['RESOLVED', 'Resolved', 'COMPLETE', 'Resolved', 'Closed by work completion'],
    ['ARCHIVED', 'Archived', 'ARCHIVED', 'Archived threads', 'Archived'],
    ['DELIVERY_FAILED', 'Delivery failed', 'ERROR', 'We could not reach you — update contact', 'Bounce'],
  ],
  transitions: [
    ['EMPTY_INBOX', 'CONVERSATION', 'message', 'CLIENT'],
    ['CONVERSATION', 'ACTION_THREADS', 'action requested by feature', 'SYSTEM'],
    ['ACTION_THREADS', 'AIO_REPLYING', 'client acts', 'CLIENT'],
    ['CONVERSATION', 'AIO_REPLYING', 'client message', 'CLIENT'],
    ['AIO_REPLYING', 'CONVERSATION', 'staff replies', 'FOUNDER_STAFF'],
    ['CONVERSATION', 'APPOINTMENT_PROPOSED', 'appointment proposed', 'FOUNDER_STAFF'],
    ['APPOINTMENT_PROPOSED', 'CONVERSATION', 'confirmed', 'CLIENT'],
    ['ACTION_THREADS', 'RESOLVED', 'feature work completes', 'SYSTEM'],
    ['RESOLVED', 'ARCHIVED', 'aged', 'SYSTEM'],
    ['CONVERSATION', 'DELIVERY_FAILED', 'bounce', 'SYSTEM'],
  ],
  anchors: { start: 'CONVERSATION', success: 'RESOLVED', blocked: 'ACTION_THREADS', errors: ['DELIVERY_FAILED'], empty: 'EMPTY_INBOX', complete: 'ARCHIVED' },
  inputs: [['MESSAGE', 'Message / reply', ['TYPE', 'ATTACH FILE'], 'conversation']],
  derivations: [['THREADING', 'feature request threads', ['feature events'], 'communication engine'], ['PREFS', 'channel preferences + consent', ['account'], 'COMMUNICATION_PREFERENCES_AND_CONSENT']],
  reviews: [['STAFF_REPLY', 'AIO_REPLYING', 'Reply / route', ['REPLY', 'ROUTE']]],
  approvals: [['CONFIRM_APPOINTMENT', 'APPOINTMENT_PROPOSED', 'Confirm time', ['CONFIRM', 'RESCHEDULE']]],
  artifacts: [['THREAD', 'Message thread', 'MESSAGE', 'communication engine', null]],
  vault: null,
  inbox: [['ACTION_THREADS', 'aggregated feature action requests']],
  activity: [['RESOLVED', 'Thread resolved']],
  notify: [['ACTION_THREADS', 'New message / action']],
  tasks: [['AIO_REPLYING', 'Reply to {client}']],
  next: 'Resolved threads archive; new feature events open threads.',
  upstream: ['every feature (inbox events)'],
  downstream: ['AIO.MY_OFFICE (needs you)'],
  relationships: [['AIO.MY_OFFICE', 'ACTION_THREADS', 'UPDATES_STATUS', 'Needs You count', 'client owed items', { MY_OFFICE: 'attention' }, 'count badge']],
  public: { applicable: false, reason: 'Private correspondence.' },
  client: {
    entry_point: 'Inbox (or notification)',
    primary_task: 'Clear what needs you.',
    sees_first: 'Action threads first, then conversations.',
    must_provide: ['replies / actions'],
    input_methods: ['TYPE', 'ATTACH FILE', 'CONFIRM'],
    system_already_knows: ['feature context per thread'],
    ready_signals: ['unread / action counts'],
    needs_you: ['action threads', 'appointments'],
    under_review: ['awaiting AIO reply'],
    approves: ['appointments'],
    completion_looks_like: 'No action threads.',
    artifacts_received: ['Message thread'],
    what_happens_next: 'Threads resolve as work completes.',
  },
  staff: {
    client_context: ['client + thread feature'],
    work_queue: 'Office inbox',
    status_model: [],
    blockers: ['unanswered client messages'],
    missing_inputs: ['contact info'],
    system_flags: ['bounce', 'consent missing'],
    human_review: ['reply'],
    corrections: ['update contact'],
    approval: ['appointment confirmation'],
    overrides: ['manual resolve'],
    operational_actions: ['REPLY', 'PROPOSE TIME', 'RESOLVE'],
    artifact_generation: ['templated messages'],
    completion: 'Thread resolved.',
    hub_buckets: { NEEDS_REVIEW: ['AIO_REPLYING'], AWAITING_CLIENT: ['ACTION_THREADS', 'APPOINTMENT_PROPOSED'], COMPLETE: ['RESOLVED'] },
    mirror_not_copy: 'Staff see SLA-ordered queue across clients.',
  },
  system: {
    ingestion: ['feature events', 'messages'],
    validation: ['consent + preferences'],
    derivation: ['threads', 'resolution'],
    state_transitions: ['feature completion resolves threads'],
    next_cycle_creation: 'n/a — event driven.',
    failure_handling: ['bounce → DELIVERY_FAILED', 'provider failover'],
  },
  metaphor: 'ACTION / CORRESPONDENCE QUEUE',
  metaphor2: 'the office mail tray',
  archetype: ['QUEUE'],
  object: 'THE THREAD (feature, needs-you, resolution)',
  objects: ['notifications', 'appointments'],
  composition: ['Action threads first; each thread carries its feature context and resolves when the work completes.'],
  hierarchy: {
    CLIENT: ih('What needs my reply?', 'Action threads count', 'Reply / act', 'Conversations', 'Unanswered action', 'OPEN THREAD', 'All resolved'),
    FOUNDER_STAFF: ih('Who is waiting on us?', 'SLA queue', 'Reply', 'Ageing', 'Overdue reply', 'REPLY', 'Resolved'),
  },
  grammar: [['REPLY', 'CLIENT', 'reply', 'AIO_REPLYING'], ['CONFIRM', 'CLIENT', 'confirm appointment', 'CONVERSATION'], ['RESOLVE', 'SYSTEM', 'resolve on completion', 'RESOLVED']],
  emotion: { CLIENT: 'I know which messages need me.', FOUNDER_STAFF: 'No client waits on us unseen.' },
  density: 'BALANCED',
  viewports: { mobile: ['action threads first', 'list → thread'], tablet: ['list + thread', 'two columns'], desktop: ['three-pane mail', 'list + thread + context'] },
  ctas: { public: null, client: 'OPEN THREAD', staff: 'REPLY' },
  avoid: ['email-client clutter', 'notifications without feature context'],
  e2e: {
    journey: 'FEATURE EVENT → THREAD → ACTION → RESOLVED',
    not_applicable: { PUBLIC_DISCOVERY: 'private', ARCHIVE: 'threads archive in place (no vault artifact)' },
    expect: {
      CLIENT_ENTRY: ['CLIENT', 'portal/messages', 'open', ['action threads first']],
      CLIENT_ACTION: ['CLIENT', 'portal/messages/:id', 'reply', ['awaiting AIO']],
      SYSTEM_PROCESSING: ['SYSTEM', 'communication engine', 'thread feature event', ['thread created with context']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/inbox', 'reply', ['reply delivered']],
      CLIENT_APPROVAL: ['CLIENT', 'appointments', 'confirm', ['confirmed']],
      ARTIFACT_CREATION: ['SYSTEM', 'thread', 'store', ['thread history']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'my office', 'sync', ['needs-you count']],
      COMPLETION: ['SYSTEM', 'feature', 'work completes', ['thread resolved']],
      NEXT_STEP: ['CLIENT', 'portal/messages', 'view', ['inbox clear']],
    },
  },
  structure: { routes: [['CLIENT', 'portal/messages/* · notifications · appointments/*'], ['FOUNDER_STAFF', 'office/inbox']], data: ['communicationTypes.ts', 'notification engine', 'appointmentTypes.ts'], evidence: ['docs/COMMUNICATIONS_SYSTEM.md', 'docs/NOTIFICATION_SYSTEM.md'] },
  functional_pct: 62,
  activation: 'live (provider abstraction)',
  code: ['src/communications/*', 'src/notifications/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.MY_OFFICE'],
});

export const AIO_ACCOUNT = aioFeature({
  id: 'AIO.ACCOUNT',
  name: 'Account — Settings / Team / Auth',
  family: 'F18 ACCOUNT',
  purpose: 'Sign up, sign in, manage the organisation, team members, roles and communication preferences.',
  promise: 'Your office, your team, your preferences.',
  value: 'The right people see the right parts of the business.',
  actors: ['PUBLIC', 'CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['team members'],
  entries: {
    public: ['Sign up', 'auth routes', 'Get Started conversion'],
    client: ['Settings', 'portal/settings/* · team', 'profile menu'],
    staff: ['Office account admin', 'office/* org admin', 'support request'],
    system: ['auth + RLS', 'sign up / role change'],
  },
  states: [
    ['NO_ACCOUNT', 'No account', 'EMPTY', 'Create your account', 'None', { PUBLIC: 'CREATE ACCOUNT' }],
    ['ACTIVE', 'Active', 'ACTIVE', 'Your account', 'Active'],
    ['INVITE_PENDING', 'Invite pending', 'APPROVAL', 'Accept the team invite', 'Pending', { CLIENT: 'ACCEPT INVITE', FOUNDER_STAFF: 'RESEND' }],
    ['VERIFY_EMAIL', 'Verify email', 'BLOCKED', 'Verify your email', 'Unverified'],
    ['SUPPORT_REVIEW', 'Support reviewing', 'REVIEW', 'AIO support is reviewing your request', 'Support'],
    ['UPDATED', 'Saved', 'COMPLETE', 'Changes saved', 'Saved'],
    ['DEACTIVATED', 'Deactivated', 'ARCHIVED', 'Account deactivated', 'Deactivated'],
    ['AUTH_ERROR', 'Sign-in problem', 'ERROR', 'We could not sign you in', 'Auth failure'],
  ],
  transitions: [
    ['NO_ACCOUNT', 'VERIFY_EMAIL', 'sign up', 'PUBLIC'],
    ['VERIFY_EMAIL', 'ACTIVE', 'verified', 'CLIENT'],
    ['ACTIVE', 'INVITE_PENDING', 'member invited', 'CLIENT'],
    ['INVITE_PENDING', 'ACTIVE', 'accepted', 'CLIENT'],
    ['ACTIVE', 'UPDATED', 'settings saved', 'CLIENT'],
    ['UPDATED', 'ACTIVE', 'continue', 'CLIENT'],
    ['ACTIVE', 'SUPPORT_REVIEW', 'support request', 'CLIENT'],
    ['SUPPORT_REVIEW', 'ACTIVE', 'resolved', 'FOUNDER_STAFF'],
    ['ACTIVE', 'DEACTIVATED', 'deactivated', 'FOUNDER_STAFF'],
    ['ACTIVE', 'AUTH_ERROR', 'auth failure', 'SYSTEM'],
  ],
  anchors: { start: 'ACTIVE', success: 'UPDATED', blocked: 'VERIFY_EMAIL', errors: ['AUTH_ERROR'], empty: 'NO_ACCOUNT', complete: 'DEACTIVATED' },
  inputs: [['PROFILE', 'Org + user profile', ['ENTER'], 'account'], ['TEAM', 'Team members + roles', ['INVITE'], 'access'], ['PREFERENCES', 'Communication preferences', ['TOGGLE'], 'notifications']],
  derivations: [['ACCESS', 'route access by role', ['roles'], 'routeAccess.ts + RLS']],
  reviews: [['SUPPORT', 'SUPPORT_REVIEW', 'Resolve support request', ['RESOLVE']]],
  approvals: [['ACCEPT_INVITE', 'INVITE_PENDING', 'Join the organisation?', ['ACCEPT', 'DECLINE']]],
  overrides: [['DEACTIVATE', 'ACTIVE', 'Deactivate account', ['DEACTIVATE']]],
  artifacts: [['AUDIT', 'Account audit log', 'RECORD', 'auth', null, ['FOUNDER_STAFF']]],
  vault: null,
  inbox: [['INVITE_PENDING', 'You were invited to {org}']],
  activity: [['UPDATED', 'Settings updated']],
  notify: [['VERIFY_EMAIL', 'Verify your email']],
  tasks: [['SUPPORT_REVIEW', 'Support request from {client}']],
  next: 'Back to My Office.',
  upstream: ['AIO.GET_STARTED (conversion)'],
  downstream: ['every authenticated surface (roles)', 'AIO.INBOX (preferences)'],
  relationships: [['AIO.INBOX', 'UPDATED', 'UPDATES_STATUS', 'notification preferences applied', 'consent updated', { INBOX: 'preferences' }, 'none']],
  public: {
    discovery: ['Get Started conversion', 'sign-in link'],
    must_understand: ['one account per business with team roles'],
    who_its_for: 'New clients.',
    what_we_handle: ['secure sign-in', 'team access'],
    what_client_provides: ['email', 'password'],
    how_it_works: ['Sign up', 'Verify email', 'Invite team'],
    outcome: 'An active account.',
    timing: 'Minutes.',
    pricing_relationship: 'Account included.',
    cta: 'Create Account',
    workspace_continuity: 'Sign-up lands directly in My Office with the Get Started plan.',
  },
  client: {
    entry_point: 'Settings',
    primary_task: 'Manage the organisation and team.',
    sees_first: 'Profile, team, preferences.',
    must_provide: ['profile', 'team invites'],
    input_methods: ['ENTER', 'INVITE', 'TOGGLE'],
    system_already_knows: ['org + roles'],
    ready_signals: ['verified email'],
    needs_you: ['email verification', 'invite acceptance'],
    under_review: ['support requests'],
    approves: ['invites'],
    completion_looks_like: 'Saved settings.',
    artifacts_received: ['none (records only)'],
    what_happens_next: 'Back to My Office.',
  },
  staff: {
    client_context: ['org + members + roles'],
    work_queue: 'Support queue',
    status_model: [],
    blockers: ['unverified email'],
    missing_inputs: ['org details'],
    system_flags: ['suspicious sign-in'],
    human_review: ['support'],
    corrections: ['role fixes'],
    approval: ['invite acceptance'],
    overrides: ['deactivate'],
    operational_actions: ['RESET ACCESS', 'DEACTIVATE'],
    artifact_generation: ['audit log'],
    completion: 'Resolved.',
    hub_buckets: { NEEDS_REVIEW: ['SUPPORT_REVIEW'], AWAITING_CLIENT: ['VERIFY_EMAIL', 'INVITE_PENDING'], COMPLETE: ['UPDATED'] },
    mirror_not_copy: 'Staff see org admin + audit, not personal settings.',
  },
  system: {
    ingestion: ['sign up', 'role changes'],
    validation: ['auth', 'RLS'],
    derivation: ['route access'],
    state_transitions: ['sign up → verify → active'],
    next_cycle_creation: 'n/a.',
    failure_handling: ['auth error → recovery flow'],
  },
  metaphor: 'THE OFFICE KEYRING',
  metaphor2: 'who holds which key',
  archetype: ['DOCUMENT_TABLE', 'CHECKLIST'],
  object: 'THE ORGANISATION (members, roles)',
  objects: ['profile', 'team', 'preferences'],
  composition: ['Quiet settings surface; team and roles as a table.'],
  hierarchy: {
    PUBLIC: ih('How do I get in?', 'Sign up', 'Create account', 'none', 'Unverified', 'CREATE ACCOUNT', 'Active account'),
    CLIENT: ih('Who has access?', 'Team', 'Manage', 'Preferences', 'Pending invites', 'INVITE', 'Saved'),
    FOUNDER_STAFF: ih('Is this account healthy?', 'Org status', 'Support', 'Audit', 'Auth issues', 'RESET ACCESS', 'Resolved'),
  },
  grammar: [['INVITE', 'CLIENT', 'invite a member', 'INVITE_PENDING'], ['SAVE', 'CLIENT', 'save settings', 'UPDATED']],
  emotion: { PUBLIC: 'Getting in is easy.', CLIENT: 'The right people have the right access.', FOUNDER_STAFF: 'Accounts are secure and supported.' },
  density: 'SPARSE',
  viewports: { mobile: ['settings list', 'stacked'], tablet: ['settings + detail', 'two columns'], desktop: ['settings + team table', 'split'] },
  ctas: { public: 'CREATE ACCOUNT', client: 'INVITE', staff: 'RESET ACCESS' },
  avoid: ['loud styling on settings', 'exposing staff roles to clients'],
  e2e: {
    journey: 'SIGN UP → VERIFY → INVITE → ACTIVE',
    not_applicable: { ARCHIVE: 'no vault artifacts' },
    expect: {
      PUBLIC_DISCOVERY: ['PUBLIC', 'auth', 'open sign-up', ['clear account creation']],
      CLIENT_ENTRY: ['CLIENT', 'portal/settings', 'open', ['profile + team']],
      CLIENT_ACTION: ['CLIENT', 'team', 'invite member', ['invite pending']],
      SYSTEM_PROCESSING: ['SYSTEM', 'auth', 'role access', ['RLS enforced']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office admin', 'support', ['resolved']],
      CLIENT_APPROVAL: ['CLIENT', 'invite', 'accept', ['member active']],
      ARTIFACT_CREATION: ['SYSTEM', 'audit', 'log', ['audit entry']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'inbox', 'preferences', ['applied']],
      COMPLETION: ['CLIENT', 'settings', 'save', ['saved']],
      NEXT_STEP: ['CLIENT', 'portal', 'return', ['My Office']],
    },
  },
  structure: { routes: [['PUBLIC', 'auth routes'], ['CLIENT', 'portal/settings/* · team']], data: ['authService.ts', 'routeAccess.ts', 'RLS helpers'], evidence: ['docs/AUTHORIZATION_MATRIX.md', 'src/auth/routeAccess.ts'] },
  functional_pct: 55,
  activation: 'live (Supabase auth partial)',
  code: ['src/auth/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.INBOX'],
});

export const AIO_OFFICE_OPERATIONS = aioFeature({
  id: 'AIO.OFFICE_OPERATIONS',
  name: 'AIO Office Operations (founder / staff)',
  family: 'AIO OFFICE role projection (office/*) across F05–F17',
  purpose: 'Run the business office: every client’s work as OfficeWorkItems in division queues, with handoffs, approvals, escalations and management metrics.',
  promise: 'Nothing a client is owed falls through the cracks.',
  value: 'One operating model for every division; founder sees exceptions, not noise.',
  actors: ['CLIENT', 'FOUNDER_STAFF', 'SYSTEM'],
  secondary: ['divisions: permitting, compliance, insurance, dispatch, factoring, bookkeeping, brokerage'],
  entries: {
    public: { applicable: false, reason: 'Internal-only office.' },
    client: ['(indirect) every client surface shows the result of office work', 'portal', 'client sees AIO IS WORKING states'],
    staff: ['Office command center', 'office/*', 'sign in (OfficeRouteGuard)'],
    system: ['office work model', 'any work-creating event'],
  },
  states: [
    ['NEW', 'New', 'EMPTY', '—', 'New work item'],
    ['ASSIGNED', 'Assigned', 'ACTIVE', 'AIO is working', 'Assigned'],
    ['WAITING_ON_CUSTOMER', 'Waiting on customer', 'BLOCKED', 'Needs you', 'Waiting on customer'],
    ['READY_FOR_REVIEW', 'Ready for review', 'REVIEW', 'AIO is reviewing', 'Ready for review'],
    ['AWAITING_APPROVAL', 'Awaiting approval', 'APPROVAL', 'Decision waiting', 'Internal / client approval'],
    ['COMPLETED', 'Completed', 'COMPLETE', 'Done', 'Completed'],
    ['CLOSED', 'Closed', 'ARCHIVED', '—', 'Closed / audited'],
    ['ESCALATED', 'Escalated', 'ERROR', 'AIO is escalating', 'Escalated'],
  ],
  transitions: [
    ['NEW', 'ASSIGNED', 'assignment', 'FOUNDER_STAFF'],
    ['ASSIGNED', 'WAITING_ON_CUSTOMER', 'needs client', 'FOUNDER_STAFF'],
    ['WAITING_ON_CUSTOMER', 'ASSIGNED', 'client responds', 'CLIENT'],
    ['ASSIGNED', 'READY_FOR_REVIEW', 'work done', 'FOUNDER_STAFF'],
    ['READY_FOR_REVIEW', 'AWAITING_APPROVAL', 'handoff for approval', 'FOUNDER_STAFF'],
    ['AWAITING_APPROVAL', 'COMPLETED', 'approved', 'FOUNDER_STAFF'],
    ['ASSIGNED', 'ESCALATED', 'escalation', 'FOUNDER_STAFF'],
    ['ESCALATED', 'ASSIGNED', 'resolved', 'FOUNDER_STAFF'],
    ['COMPLETED', 'CLOSED', 'audit closed', 'SYSTEM'],
  ],
  anchors: { start: 'ASSIGNED', success: 'COMPLETED', blocked: 'WAITING_ON_CUSTOMER', errors: ['ESCALATED'], empty: 'NEW', complete: 'CLOSED' },
  inputs: [['WORK_UPDATES', 'Work updates, notes, decisions', ['UPDATE STATUS', 'NOTE', 'HANDOFF'], 'work progress']],
  derivations: [['PRIORITY', 'queue priority', ['dueAt', 'waitingOn', 'priority'], 'OfficeWorkItem'], ['METRICS', 'management metrics', ['work items'], 'MANAGEMENT_METRIC_REGISTRY']],
  reviews: [['REVIEW', 'READY_FOR_REVIEW', 'Is the work correct?', ['APPROVE', 'RETURN']]],
  approvals: [['CLIENT_DECISION', 'AWAITING_APPROVAL', 'Client approvals routed from the owning feature', ['APPROVED', 'DECLINED']]],
  overrides: [['REASSIGN', 'ASSIGNED', 'Reassign / reprioritise', ['REASSIGN']]],
  artifacts: [['WORK_AUDIT', 'Work item audit trail', 'RECORD', 'office work model', null, ['FOUNDER_STAFF']]],
  vault: null,
  inbox: [['WAITING_ON_CUSTOMER', 'client-facing request (via owning feature)']],
  activity: [['COMPLETED', 'Work completed (client-visible via feature)']],
  notify: [['ESCALATED', 'Escalation (staff)']],
  tasks: [['NEW', 'Assign new work item'], ['ESCALATED', 'Resolve escalation']],
  next: 'Founder hub buckets refresh; completed work updates client surfaces through feature contracts.',
  upstream: ['every feature (work items)'],
  downstream: ['every feature (status)', 'management reporting'],
  relationships: [['AIO.MY_OFFICE', 'COMPLETED', 'UPDATES_STATUS', 'client sees the feature complete', 'client 360 updated', { MY_OFFICE: 'attention cleared' }, 'AIO IS WORKING → complete']],
  public: { applicable: false, reason: 'Internal-only office.' },
  client: {
    entry_point: 'Indirect — client feature surfaces',
    primary_task: 'None directly; client sees outcomes.',
    sees_first: '“All In One is working” states on their features.',
    must_provide: ['responses when work waits on them'],
    input_methods: ['via feature surfaces'],
    system_already_knows: ['all work items'],
    ready_signals: ['customer-friendly states'],
    needs_you: ['waiting-on-customer items (via features)'],
    under_review: ['AIO working'],
    approves: ['feature-level approvals'],
    completion_looks_like: 'Feature complete.',
    artifacts_received: ['feature artifacts'],
    what_happens_next: 'Feature next steps.',
  },
  staff: {
    client_context: ['client 360', 'division'],
    work_queue: 'Division queues + founder command center',
    status_model: [],
    blockers: ['waiting on customer / external / internal'],
    missing_inputs: ['per work item'],
    system_flags: ['overdue dueAt', 'unassigned', 'escalated'],
    human_review: ['ready-for-review work'],
    corrections: ['return work'],
    approval: ['internal approvals + handoffs (OFFICE_HANDOFFS_APPROVALS_ESCALATIONS)'],
    overrides: ['reassign', 'reprioritise'],
    operational_actions: ['ASSIGN', 'HANDOFF', 'APPROVE', 'ESCALATE', 'CLOSE'],
    artifact_generation: ['audit trail'],
    completion: 'Work completed + audited.',
    hub_buckets: { NEEDS_REVIEW: ['READY_FOR_REVIEW'], BLOCKED: ['ESCALATED'], AWAITING_CLIENT: ['WAITING_ON_CUSTOMER'], READY_TO_SEND: ['AWAITING_APPROVAL'], COMPLETE: ['COMPLETED'] },
    mirror_not_copy: 'This IS the founder / staff mirror for every feature: queues, exceptions, audit — never the client UI.',
  },
  system: {
    ingestion: ['work-creating events from all features'],
    validation: ['optimistic concurrency on assignment (version)'],
    derivation: ['priority', 'metrics'],
    state_transitions: ['OfficeWorkItem status model'],
    next_cycle_creation: 'Recurring work (quarters, renewals, closes) recreated by features.',
    failure_handling: ['overdue → escalation', 'assignment conflict → retry'],
  },
  metaphor: 'THE BUSINESS OFFICE',
  metaphor2: 'the control room behind every truck',
  archetype: ['CONTROL_ROOM', 'QUEUE'],
  object: 'THE WORK ITEM (client, division, waitingOn, due)',
  objects: ['division queues', 'founder hub buckets', 'metrics'],
  composition: ['Founder hub: buckets (NEEDS REVIEW · BLOCKED · AWAITING CLIENT · AWAITING PROVIDER · READY TO FILE · READY TO SEND · READY TO LAUNCH · COMPLETE) with exceptions first.'],
  hierarchy: {
    CLIENT: ih('Is AIO working on my business?', 'AIO IS WORKING states', 'none', 'none', 'Waiting on me', 'via features', 'Feature complete'),
    FOUNDER_STAFF: ih('What needs me right now across every client?', 'Hub buckets', 'Unblock / approve', 'Division load', 'Escalations', 'OPEN TOP ITEM', 'Work closed + audited'),
  },
  grammar: [['ASSIGN', 'FOUNDER_STAFF', 'assign', 'ASSIGNED'], ['HANDOFF', 'FOUNDER_STAFF', 'hand off for approval', 'AWAITING_APPROVAL'], ['ESCALATE', 'FOUNDER_STAFF', 'escalate', 'ESCALATED']],
  emotion: { CLIENT: 'AIO is working, and I am told when I am needed.', FOUNDER_STAFF: 'I see exceptions across the whole office, not noise.' },
  density: 'DENSE',
  viewports: { mobile: ['founder triage: top exceptions', 'bucket list'], tablet: ['buckets + item', 'two columns'], desktop: ['control room', 'buckets × divisions grid'] },
  ctas: { public: null, client: 'SEE WHAT AIO IS WORKING ON', staff: 'OPEN TOP ITEM' },
  avoid: ['copying client UI for staff', 'vanity metrics over exceptions'],
  e2e: {
    journey: 'EVENT → WORK ITEM → ASSIGN → REVIEW → APPROVE → COMPLETE → CLIENT UPDATED',
    not_applicable: { PUBLIC_DISCOVERY: 'internal-only', ARCHIVE: 'audit trail stays in the office (feature artifacts archive via their contracts)' },
    expect: {
      CLIENT_ENTRY: ['CLIENT', 'portal', 'view feature', ['AIO IS WORKING state']],
      CLIENT_ACTION: ['CLIENT', 'feature surface', 'respond to waiting item', ['work item resumes']],
      SYSTEM_PROCESSING: ['SYSTEM', 'office work model', 'create work item', ['queued with priority']],
      STAFF_REVIEW: ['FOUNDER_STAFF', 'office/*', 'assign + review', ['ready for review']],
      CLIENT_APPROVAL: ['CLIENT', 'feature surface', 'approve', ['approval recorded']],
      ARTIFACT_CREATION: ['SYSTEM', 'audit', 'log', ['audit trail']],
      DOWNSTREAM_MOVEMENT: ['SYSTEM', 'feature', 'complete', ['client surface updated']],
      COMPLETION: ['FOUNDER_STAFF', 'office/*', 'close', ['COMPLETE bucket']],
      NEXT_STEP: ['FOUNDER_STAFF', 'office/*', 'next item', ['buckets refresh']],
    },
  },
  structure: { routes: [['FOUNDER_STAFF', 'office/*']], data: ['OfficeWorkItem (OFFICE_WORK_MODEL.md)', 'OFFICE_HANDOFFS_APPROVALS_ESCALATIONS'], evidence: ['docs/OFFICE_WORK_MODEL.md', 'docs/MANAGEMENT_COMMAND_CENTER.md'] },
  functional_pct: null,
  activation: 'live (OfficeRouteGuard; demo + office modules)',
  code: ['src/office/*', 'src/office-core/*'],
  declared: 'EXPERIENCE_COMPLETE',
  related: ['AIO.MY_OFFICE', 'AIO.INBOX'],
});
