/**
 * GENERATED by the sprint evidence step from the fsbw evidence folder AIO_PUBLIC_MIGRATION_READINESS/ — do not edit by hand.
 * The measured side of public-migration.ts: QA, the current app's renders, page lengths before and after, a11y/performance.
 */
export const AIO_PM_EVIDENCE = {
  "generated_from": "fsbw df825419 · AIO_PUBLIC_MIGRATION_READINESS/ (qa-summary.json, scroll.json, current-app/metrics.json) — generated, do not edit",
  "qa": {
    "pass": 119,
    "fail": 0,
    "pages": 92,
    "sizes": [
      "s360",
      "phone",
      "tablet",
      "tabletL",
      "desktop",
      "wide"
    ],
    "checks": [
      "pages · s360 · all 92 pages draw without errors",
      "pages · s360 · every page is a designed page (none fall to 404)",
      "pages · s360 · no sideways scroll",
      "text · s360 · every letter uppercase",
      "text · s360 · nothing under 9 px",
      "text · s360 · buttons, chips, tabs and links stay on one line",
      "text · s360 · nothing clipped by its box",
      "pages · s360 · every image loads",
      "controls · s360 · every button has a handler (or says it is disabled)",
      "pages · phone · all 92 pages draw without errors",
      "pages · phone · every page is a designed page (none fall to 404)",
      "pages · phone · no sideways scroll",
      "text · phone · every letter uppercase",
      "text · phone · nothing under 9 px",
      "text · phone · buttons, chips, tabs and links stay on one line",
      "text · phone · nothing clipped by its box",
      "pages · phone · every image loads",
      "controls · phone · every button has a handler (or says it is disabled)",
      "pages · tablet · all 92 pages draw without errors",
      "pages · tablet · every page is a designed page (none fall to 404)",
      "pages · tablet · no sideways scroll",
      "text · tablet · every letter uppercase",
      "text · tablet · nothing under 9 px",
      "text · tablet · buttons, chips, tabs and links stay on one line",
      "text · tablet · nothing clipped by its box",
      "pages · tablet · every image loads",
      "controls · tablet · every button has a handler (or says it is disabled)",
      "pages · tabletL · all 92 pages draw without errors",
      "pages · tabletL · every page is a designed page (none fall to 404)",
      "pages · tabletL · no sideways scroll",
      "text · tabletL · every letter uppercase",
      "text · tabletL · nothing under 9 px",
      "text · tabletL · buttons, chips, tabs and links stay on one line",
      "text · tabletL · nothing clipped by its box",
      "pages · tabletL · every image loads",
      "controls · tabletL · every button has a handler (or says it is disabled)",
      "pages · desktop · all 92 pages draw without errors",
      "pages · desktop · every page is a designed page (none fall to 404)",
      "pages · desktop · no sideways scroll",
      "text · desktop · every letter uppercase",
      "text · desktop · nothing under 9 px",
      "text · desktop · buttons, chips, tabs and links stay on one line",
      "text · desktop · nothing clipped by its box",
      "pages · desktop · every image loads",
      "controls · desktop · every button has a handler (or says it is disabled)",
      "pages · wide · all 92 pages draw without errors",
      "pages · wide · every page is a designed page (none fall to 404)",
      "pages · wide · no sideways scroll",
      "text · wide · every letter uppercase",
      "text · wide · nothing under 9 px",
      "text · wide · buttons, chips, tabs and links stay on one line",
      "text · wide · nothing clipped by its box",
      "pages · wide · every image loads",
      "controls · wide · every button has a handler (or says it is disabled)",
      "links · all 126 internal links land on a page of the tree",
      "images · all 9 photographs behind the pages exist",
      "honesty · no price on any page",
      "honesty · no client counts, approval rates or round-the-clock claims",
      "honesty · no testimonials or reviews",
      "honesty · the retired identity never appears (Perfect Choice, Frontal Slayer)",
      "honesty · the brand lines are the founder’s: tagline, positioning, promise",
      "honesty · every service shows its status from the matrices (52 services)",
      "honesty · placeholders are labelled, not shown as contact details",
      "brokerage · shown as PAUSED, its start actions disabled, no route into get-started from the page",
      "brokerage · a freight service page says PAUSED and offers no start",
      "nav · SERVICES opens the mega menu with all seven families",
      "nav · Esc closes the menu",
      "nav · SOLUTIONS opens, and a choice opens its page (ROAD READY™)",
      "search · typing IFTA finds the IFTA services",
      "search · a result opens its page and closes the search",
      "home · SEE HOW IT WORKS scrolls to WHICH ONE ARE YOU (start · operate · maintain)",
      "home · the WHAT CAN WE HELP YOU DO selector shows the chosen road (RUN MY OPERATION) with its services",
      "home · choosing OPERATE shows that stage and its first step (WHERE TO BEGIN)",
      "home · a service family on the road opens its page",
      "services · the catalog index lists every service by family; a family narrows it to cards, the filter narrows again",
      "family · picking a service on the left shows it on the right (who it is for, what you provide, next step)",
      "service · the page answers who, what you provide, how, after and questions, with an ON THIS PAGE bar",
      "service · ON THIS PAGE jumps to the section",
      "service · ADD TO MY PLAN (the live service plan) puts the service in MY SERVICE PLAN",
      "guide · the compliance guide shows one family at a time",
      "journey · picking a stage of Start Your Business shows it in place (REGISTER)",
      "finder · choosing GETTING MY AUTHORITY recommends USDOT, MC and BOC-3",
      "get started · CONTINUE asks for the required answer first",
      "get started · the MOVE FREIGHT goal is shown PAUSED and cannot be chosen (Brokerage paused)",
      "get started · the live Smart Intake, section by section (7 for START MY TRUCKING BUSINESS), ends at the roadmap",
      "forms · sending says NOTHING WAS SENT (design review)",
      "account · log in has no site header (focused), and links to forgot password and create account",
      "interactions · no errors on desktop",
      "phone · the menu opens, SERVICES lists all families, a choice navigates and closes it",
      "phone · the four pathways swipe sideways (snap), inside their row only",
      "phone · START / OPERATE / MAINTAIN switch the stage",
      "phone · a long family shows six services, then SHOW ALL opens the rest in place",
      "phone · the first screen shows the truck, the headline and GET STARTED",
      "interactions · no errors on the phone",
      "motion · nothing loops",
      "motion · the hero settles in once (photo and words), under two seconds",
      "motion · sections rise into view once as they arrive",
      "motion · reduced motion shows everything at once (no rising, no hero zoom, no panel fades)",
      "review · it opens on START HERE: A, B, C, then the connected site",
      "review · A lists every capability with its fate, the eight issues and the current-app captures",
      "review · B shows six pages at phone · tablet · desktop · ultra-wide",
      "review · a B picture opens that page live in that frame",
      "review · C shows the before → after lengths and the before/after pages",
      "review · THE CONNECTED SITE shows the five curated groups as cards",
      "review · a card opens the page in the device frame",
      "review · s360 frame is 360 wide and the site composes at 360",
      "review · phone frame is 390 wide and the site composes at 390",
      "review · tablet frame is 834 wide and the site composes at 834",
      "review · tabletL frame is 1194 wide and the site composes at 1194",
      "review · desktop frame is 1440 wide and the site composes at 1440",
      "review · wide frame is 2560 wide and the site composes at 2560",
      "review · the homepage shows panel 04 beside it",
      "review · the reference can be put away",
      "review · a service page shows the approved IFTA public page beside it",
      "review · clicking inside the site navigates inside the frame",
      "review · the page tree lists every page (92)",
      "review · reference & recovery shows the brand board, the IFTA authority and what was not found",
      "review · no errors",
      "review · at 390 the review has no sideways scroll and opens on the phone frame"
    ]
  },
  "legacy": {
    "routes": 99,
    "renders": 495,
    "findings": [
      "99 public routes rendered at 360, 390, 834, 1440 and 2560 (495 renders) from a local build of the current source in demo mode — not production.",
      "Placeholder contact details rendered: (866) 000-0000, CONTACT@ALLINONEENTERPRISES.EXAMPLE.",
      "Prices rendered on 11 routes: /services/all-in-one-bookkeeping, /services/boc-3-assistance, /services/bookkeeping, /services/bookkeeping-essentials, /services/bookkeeping-plus, /services/books-rescue, /services/fleetcare, /services/fleetcare/plans, /services/llc-formation-assistance, /services/payroll-services, /services/tax-preparation.",
      "81 routes keep the default title “ALL IN ONE ENTERPRISES INC.” (no per-page title).",
      "Client-side redirects seen: /services/bookkeeping/recommendation → /services/bookkeeping/assessment; /sign-up → /signup.",
      "Demo copy visible on: /login, /office, /request-callback, /request/submit (and /office opens in demo mode with a staff identity).",
      "/debug/icon-library renders publicly (12,806 px tall on a 390 phone).",
      "5 desktop header links render dark on dark (contrast 1.13 : 1): START YOUR BUSINESS, ROAD READY™, ABOUT, CONTACT, (866) 000-0000.",
      "Page errors logged across all renders: 0."
    ]
  },
  "scroll": [
    {
      "path": "/",
      "group": "HOME",
      "before": {
        "s360": 7.24,
        "phone": 6.71,
        "tablet": 5.16,
        "tabletL": 5.91,
        "desktop": 5.62,
        "wide": 5.27
      },
      "after": {
        "s360": 7.64,
        "phone": 7.09,
        "tablet": 5.07,
        "tabletL": 5.67,
        "desktop": 5.17,
        "wide": 4.91
      }
    },
    {
      "path": "/services",
      "group": "SERVICES",
      "before": {
        "s360": 14.64,
        "phone": 13.65,
        "tablet": 6.13,
        "tabletL": 6.6,
        "desktop": 6.01,
        "wide": 4.03
      },
      "after": {
        "s360": 4.13,
        "phone": 3.88,
        "tablet": 3.42,
        "tabletL": 3.81,
        "desktop": 3.52,
        "wide": 2.69
      }
    },
    {
      "path": "/services/find",
      "group": "SERVICES",
      "before": {
        "s360": 4.32,
        "phone": 4.01,
        "tablet": 2.36,
        "tabletL": 2.84,
        "desktop": 2.57,
        "wide": 2
      },
      "after": {
        "s360": 4.33,
        "phone": 4.02,
        "tablet": 2.37,
        "tabletL": 2.79,
        "desktop": 2.53,
        "wide": 1.96
      }
    },
    {
      "path": "/services/permitting",
      "group": "SERVICES",
      "before": {
        "s360": 9.88,
        "phone": 9.08,
        "tablet": 4.87,
        "tabletL": 5.6,
        "desktop": 4.88,
        "wide": 3.67
      },
      "after": {
        "s360": 5.72,
        "phone": 5.27,
        "tablet": 3.99,
        "tabletL": 4.25,
        "desktop": 3.84,
        "wide": 3.41
      }
    },
    {
      "path": "/services/business-formation",
      "group": "SERVICES",
      "before": {
        "s360": 6.48,
        "phone": 5.95,
        "tablet": 3.74,
        "tabletL": 4.28,
        "desktop": 3.85,
        "wide": 3.21
      },
      "after": {
        "s360": 5.27,
        "phone": 4.9,
        "tablet": 3.16,
        "tabletL": 3.59,
        "desktop": 3.29,
        "wide": 2.83
      }
    },
    {
      "path": "/services/insurance",
      "group": "SERVICES",
      "before": {
        "s360": 6.53,
        "phone": 5.87,
        "tablet": 3.62,
        "tabletL": 4.29,
        "desktop": 3.79,
        "wide": 3.1
      },
      "after": {
        "s360": 5.22,
        "phone": 4.75,
        "tablet": 3.31,
        "tabletL": 3.67,
        "desktop": 3.36,
        "wide": 2.96
      }
    },
    {
      "path": "/services/dispatching",
      "group": "SERVICES",
      "before": {
        "s360": 6.07,
        "phone": 5.55,
        "tablet": 3.54,
        "tabletL": 4.09,
        "desktop": 3.7,
        "wide": 2.97
      },
      "after": {
        "s360": 4.93,
        "phone": 4.59,
        "tablet": 3.15,
        "tabletL": 3.5,
        "desktop": 3.24,
        "wide": 2.78
      }
    },
    {
      "path": "/services/brokerage",
      "group": "SERVICES",
      "before": {
        "s360": 6.33,
        "phone": 5.87,
        "tablet": 3.72,
        "tabletL": 4.32,
        "desktop": 3.92,
        "wide": 3.22
      },
      "after": {
        "s360": 5.24,
        "phone": 4.89,
        "tablet": 3.35,
        "tabletL": 3.74,
        "desktop": 3.47,
        "wide": 3.06
      }
    },
    {
      "path": "/services/bookkeeping",
      "group": "SERVICES",
      "before": {
        "s360": 7.65,
        "phone": 7.04,
        "tablet": 4.61,
        "tabletL": 4.68,
        "desktop": 4.2,
        "wide": 3.6
      },
      "after": {
        "s360": 6.56,
        "phone": 6.05,
        "tablet": 4.02,
        "tabletL": 4.9,
        "desktop": 4.29,
        "wide": 3.73
      }
    },
    {
      "path": "/services/factoring",
      "group": "SERVICES",
      "before": {
        "s360": 4.57,
        "phone": 4.18,
        "tablet": 2.68,
        "tabletL": 3.16,
        "desktop": 2.93,
        "wide": 2.58
      },
      "after": {
        "s360": 4.58,
        "phone": 4.19,
        "tablet": 2.69,
        "tabletL": 3.05,
        "desktop": 2.82,
        "wide": 2.48
      }
    },
    {
      "path": "/start-your-business",
      "group": "SOLUTIONS",
      "before": {
        "s360": 4.61,
        "phone": 4.3,
        "tablet": 2.58,
        "tabletL": 3,
        "desktop": 2.79,
        "wide": 2.34
      },
      "after": {
        "s360": 4.33,
        "phone": 4.01,
        "tablet": 2.55,
        "tabletL": 2.83,
        "desktop": 2.63,
        "wide": 2.19
      }
    },
    {
      "path": "/road-ready",
      "group": "SOLUTIONS",
      "before": {
        "s360": 4.86,
        "phone": 4.55,
        "tablet": 2.67,
        "tabletL": 3.02,
        "desktop": 2.77,
        "wide": 2.36
      },
      "after": {
        "s360": 4.88,
        "phone": 4.57,
        "tablet": 2.68,
        "tabletL": 2.95,
        "desktop": 2.7,
        "wide": 2.29
      }
    },
    {
      "path": "/roadmap",
      "group": "SOLUTIONS",
      "before": {
        "s360": 8.04,
        "phone": 7.06,
        "tablet": 4.1,
        "tabletL": 5.21,
        "desktop": 4.6,
        "wide": 3.48
      },
      "after": {
        "s360": 4.06,
        "phone": 3.81,
        "tablet": 2.34,
        "tabletL": 2.77,
        "desktop": 2.6,
        "wide": 2.08
      }
    },
    {
      "path": "/client-portal",
      "group": "SOLUTIONS",
      "before": {
        "s360": 3.68,
        "phone": 3.47,
        "tablet": 2.71,
        "tabletL": 2.53,
        "desktop": 2.5,
        "wide": 2.32
      },
      "after": {
        "s360": 3.7,
        "phone": 3.48,
        "tablet": 2.6,
        "tabletL": 2.48,
        "desktop": 2.45,
        "wide": 2.28
      }
    },
    {
      "path": "/get-started",
      "group": "GET STARTED",
      "before": {
        "s360": 3.79,
        "phone": 3.53,
        "tablet": 2.3,
        "tabletL": 2.37,
        "desktop": 2.21,
        "wide": 1.88
      },
      "after": {
        "s360": 3.91,
        "phone": 3.57,
        "tablet": 2.24,
        "tabletL": 2.83,
        "desktop": 2.59,
        "wide": 2.16
      }
    },
    {
      "path": "/about",
      "group": "COMPANY",
      "before": {
        "s360": 4.3,
        "phone": 4,
        "tablet": 2.57,
        "tabletL": 3.09,
        "desktop": 2.87,
        "wide": 2.36
      },
      "after": {
        "s360": 4.32,
        "phone": 4.02,
        "tablet": 2.58,
        "tabletL": 2.99,
        "desktop": 2.78,
        "wide": 2.27
      }
    },
    {
      "path": "/contact",
      "group": "COMPANY",
      "before": {
        "s360": 4.3,
        "phone": 4.06,
        "tablet": 2.53,
        "tabletL": 2.66,
        "desktop": 2.44,
        "wide": 2
      },
      "after": {
        "s360": 4.32,
        "phone": 4.07,
        "tablet": 2.54,
        "tabletL": 2.62,
        "desktop": 2.4,
        "wide": 1.95
      }
    },
    {
      "path": "/services/operating-authority-assistance",
      "group": "SERVICE PAGES",
      "before": {
        "s360": 5.58,
        "phone": 5.18,
        "tablet": 3.4,
        "tabletL": 3.77,
        "desktop": 3.47,
        "wide": 3.04
      },
      "after": {
        "s360": 6.24,
        "phone": 5.73,
        "tablet": 3.73,
        "tabletL": 3.89,
        "desktop": 3.45,
        "wide": 2.97
      }
    },
    {
      "path": "/services/ifta-fuel-tax-assistance",
      "group": "SERVICE PAGES",
      "before": {
        "s360": 5.52,
        "phone": 5.07,
        "tablet": 3.43,
        "tabletL": 3.64,
        "desktop": 3.35,
        "wide": 2.97
      },
      "after": {
        "s360": 5.51,
        "phone": 5.03,
        "tablet": 3.4,
        "tabletL": 3.69,
        "desktop": 3.27,
        "wide": 2.86
      }
    },
    {
      "path": "/services/trip-permits",
      "group": "SERVICE PAGES",
      "before": {
        "s360": 5.3,
        "phone": 4.92,
        "tablet": 3.31,
        "tabletL": 3.59,
        "desktop": 3.33,
        "wide": 2.98
      },
      "after": {
        "s360": 5.43,
        "phone": 5.01,
        "tablet": 3.42,
        "tabletL": 3.67,
        "desktop": 3.29,
        "wide": 2.88
      }
    }
  ],
  "scroll_all_pages": 92,
  "totals_px": {
    "s360": {
      "before": 367027,
      "after": 350495
    },
    "phone": {
      "before": 358635,
      "after": 343509
    },
    "tablet": {
      "before": 331215,
      "after": 325158
    },
    "tabletL": {
      "before": 254635,
      "after": 248462
    },
    "desktop": {
      "before": 253469,
      "after": 243081
    },
    "wide": {
      "before": 353648,
      "after": 338080
    }
  },
  "service_pages_px": {
    "s360": {
      "before": 217553,
      "after": 220299
    },
    "phone": {
      "before": 212431,
      "after": 215555
    },
    "tablet": {
      "before": 200118,
      "after": 203565
    },
    "tabletL": {
      "before": 152925,
      "after": 155291
    },
    "desktop": {
      "before": 151965,
      "after": 149599
    },
    "wide": {
      "before": 216213,
      "after": 208431
    }
  },
  "screenshots": {
    "qa": 282,
    "current_app": 198,
    "boards": 12
  },
  "a11y_perf": {
    "current": [
      "Main JavaScript bundle 1929 KB (one chunk; the build warns above 1,200 KB); main CSS 494 KB; 2 source maps published.",
      "The retired hero photograph (all-in-one-hero-truck.png, 1704 KB PNG) is preloaded on every page.",
      "Fonts: DM Sans + Plus Jakarta Sans via a Google Fonts @import inside the CSS (render-blocking chain).",
      "Touch targets under 24 × 24 (WCAG 2.2 AA 2.5.8) on the phone: / 6, /contact 19, /services/trip-permits 3, /get-started 7; on the desktop: / 10, /contact 21, /services/trip-permits 11, /get-started 8.",
      "Desktop header links at 1.13 : 1 contrast (fails WCAG 1.4.3 — needs 4.5 : 1).",
      "Nested interactive elements (a link wrapping a button) on service, bookkeeping, roadmap, plan and request pages.",
      "The 404 renders outside the public layout, unstyled; unknown routes return HTTP 200 (SPA rewrite)."
    ],
    "design": [
      "Touch targets under 24 × 24 on the probed pages (home, contact, a service page, get started): 0 on the phone and 0 on the desktop; nav icons are 44 × 44.",
      "Contrast: body text #F4EFE4 and muted #A8A195 on #050505 (≈ 17 : 1 and 7.9 : 1); gold buttons carry dark text #17130B on the gold gradient (≈ 8 : 1).",
      "Keyboard: every control is a button or link with a visible focus ring (2 px champagne); Esc closes menus, search and the drawer; tabs and selectors use role=tab / aria-selected; the step rail uses aria-current=step.",
      "Reduced motion turns every animation and transition off (checked by QA); nothing loops; reveals run once.",
      "Weight: site page 271 KB (HTML + CSS + JS + data inline), photographs 2654 KB for nine plates (JPEG ≤ 2560 px), fonts 91 KB self-hosted (font-display: swap).",
      "Layout shift: photographs are CSS backgrounds in fixed-height boxes; images in content (the client screen) have intrinsic size; fonts swap without layout-affecting fallbacks beyond metric differences.",
      "Scroll performance: container queries and transforms only; no scroll-linked JavaScript besides one passive listener for the hero nav state.",
      "Not yet measured on physical devices or with a screen reader — Composer port (stage 06) carries both."
    ]
  }
} as const;
