/**
 * P0.5C.4 — Art-Board Materiality + Imperfect Canvas Composition
 */

export const ART_BOARD_MATERIALITY_V1 = 'ART_BOARD_MATERIALITY_V1' as const;
export const EXPERIMENT_01_V23_VERSION = 'EXPERIMENT_01_V2_3_ART_BOARD_MATERIALITY' as const;

export const BASE_SURFACE_CLASSES = [
  'NOTEBOOK_PAPER',
  'OFFICE_PAPER',
  'ARCHIVAL_PAPER',
  'NEWSPRINT',
  'MAGAZINE_STOCK',
  'CARD_STOCK',
  'THERMAL_RECEIPT',
  'GRAPH_PAPER',
  'LEGAL_PAD',
  'INDEX_CARD',
  'PHOTO_PRINT',
  'CONTACT_SHEET',
  'PHOTOCOPY',
  'FAX',
  'PRINTER_PROOF',
  'DOCUMENT_FOLDER',
  'FILE_INSERT',
  'SCRAP',
  'POST_IT',
  'LABEL',
  'TICKET',
  'ENVELOPE',
  'PACKAGING',
  'BOOK_PAGE',
  'BOUND_NOTEBOOK',
  'ART_BOARD',
  'DIGITAL_CANVAS',
  'SCREEN_CAPTURE',
  'UI_PRINT',
  'TRANSPARENCY',
  'ACETATE',
  'FABRIC',
  'CUSTOM',
] as const;

export const ARTIFACT_SURFACE_ROLES = [
  'PRIMARY_CANVAS',
  'SECONDARY_INSERT',
  'EVIDENCE_LAYER',
  'ANNOTATION_LAYER',
  'HERO_OBJECT',
  'BACKGROUND_OBJECT',
  'CONTEXT_LAYER',
  'MEMORY_LAYER',
  'REVISION_LAYER',
  'CORRECTION_LAYER',
  'ARCHIVAL_LAYER',
  'DECORATIVE_SUBSTRATE',
] as const;

export const PAGE_CONSTRUCTION_MODES = [
  'SINGLE_SHEET',
  'BOUND_PAGE',
  'OPEN_NOTEBOOK',
  'TEAR_OUT',
  'LAYERED_INSERT',
  'ARCHIVAL_FILE',
  'PINBOARD',
  'CONTACT_SHEET',
  'DOSSIER',
  'SCRAP_ASSEMBLAGE',
  'PRINT_PROOF',
  'MARGIN_WORKSPACE',
  'OBJECT_PLUS_PAGE',
  'DIGITAL_PHYSICAL_HYBRID',
  'FULL_BLEED_PHOTO_WITH_INSERT',
  'MINIMAL_PAGE',
  'CUSTOM',
] as const;

export const PAGE_EDGE_BEHAVIORS = [
  'CLEAN',
  'SLIGHTLY_IRREGULAR',
  'ROUGH_CUT',
  'TORN',
  'DECKLED',
  'FOLDED',
  'WORN',
  'SCANNED_OFF_FRAME',
  'PARTIALLY_CROPPED',
  'LAYERED',
  'BOUND_EDGE',
  'PERFORATED',
] as const;

export const TORN_EDGE_BEHAVIORS = [
  'NONE',
  'SUBTLE',
  'ONE_EDGE',
  'MULTI_EDGE',
  'FULL_SCRAP',
  'INSERT_ONLY',
  'TEAR_AS_EVIDENCE',
  'TEAR_AS_REVISION',
] as const;

export const ARTIFACT_LAYER_TYPES = [
  'BASE_PAGE',
  'INSERT',
  'PHOTO',
  'SCREENSHOT',
  'NOTE',
  'RECEIPT',
  'LABEL',
  'HIGHLIGHT',
  'TAPE',
  'HAND_TRACE',
  'PRINTED_TEXT',
  'CORRECTION',
  'STAMP',
  'CLIP',
  'FOLD',
  'SHADOW',
  'OVERLAY',
  'UNDERLAY',
] as const;

export const ARTIFACT_ATTACHMENTS = [
  'TAPE',
  'PAPER_CLIP',
  'BINDER_CLIP',
  'STAPLE',
  'GLUE',
  'PIN',
  'STRING',
  'FOLD',
  'POCKET',
  'SLEEVE',
  'TAB',
  'DIGITAL_OVERLAY',
  'NONE',
] as const;

export const ARTIFACT_DEPTH_BEHAVIORS = ['FLAT_PRINT', 'SUBTLE_LAYERING', 'MULTI_LAYER', 'DEEP_ASSEMBLAGE'] as const;

export const PRINT_SCAN_BEHAVIORS = [
  'CLEAN_DIGITAL',
  'PRINTED',
  'SCANNED',
  'PHOTOCOPIED',
  'FAXED',
  'THERMAL_PRINTED',
  'OVERPRINTED',
  'MISREGISTERED',
  'GRAINED',
  'INK_VARIATION',
  'HALFTONE',
  'TONER_DUST',
  'EDGE_SHADOW',
  'SCAN_CROP',
  'SCANNER_GLARE',
] as const;

export const IMPERFECT_CANVAS_RESULTS = [
  'ALIVE_SURFACE',
  'CONTROLLED',
  'TOO_CLEAN',
  'TEMPLATE_LIKE',
  'FAKE_TEXTURE',
] as const;

export const MATERIAL_DENSITY_LEVELS = ['MINIMAL', 'LIGHT', 'MODERATE', 'RICH', 'OVERBUILT'] as const;

export const ART_BOARD_QUALITY_RESULTS = ['BESPOKE', 'STRONG', 'ADEQUATE', 'TEMPLATE_LIKE', 'GENERIC', 'FAKE_MATERIALITY'] as const;

export const MATERIAL_MODERNITY_RESULTS = [
  'CONTEMPORARY',
  'TIMELESS',
  'RETRO_INTENTIONAL',
  'ACCIDENTALLY_VINTAGE',
  'CRAFTY',
  'DATED',
] as const;

export const IMAGE_SURFACE_ROLES = [
  'PRINTED_ON_PAGE',
  'PHOTO_INSERT',
  'MAGAZINE_TEAR',
  'SCREENSHOT_PRINT',
  'CONTACT_SHEET',
  'CUTOUT',
  'PHOTO_STRIP',
  'FULL_BLEED',
  'LAYERED_FRAGMENT',
  'OVERPRINT',
  'ANNOTATED_IMAGE',
  'POLAROID_LIKE_PRINT',
  'DIGITAL_FRAME_WITH_PHYSICAL_INTERVENTION',
] as const;

export const HUMAN_MADE_MARK_CLASSES = [
  'HAND_DRAWN_ICON',
  'ROUGH_SYMBOL',
  'MARKER_ARROW',
  'CIRCLE',
  'UNDERLINE',
  'ASTERISK',
  'CHECK',
  'X_MARK',
  'BRACKET',
  'BOX',
  'SCRIBBLE',
  'TALLY',
  'ROUGH_DIAGRAM',
  'HAND_LABEL',
  'RANK_MARK',
  'REORDER_MARK',
  'ROUGH_GRAPHIC',
  'MARGIN_MARK',
  'CORRECTION_MARK',
] as const;

export const HAND_DRAWN_ICON_SUBJECTS = [
  'camera',
  'game',
  'blender',
  'printer',
  'car',
  'headphones',
  'watch',
  'TV',
  'tool',
  'laptop',
  'bike',
  'coffee maker',
  'book',
  'luggage',
  'guitar',
] as const;

export const LIME_INTERVENTION_DENSITY_LEVELS = ['SUBTLE', 'MODERATE', 'STRONG', 'OVERUSED'] as const;

export const LIME_APPLICATION_MODES = [
  'PRINTED',
  'MARKER',
  'HIGHLIGHTER',
  'INK',
  'PAINT',
  'DIGITAL_HAND_TRACE',
  'LABEL',
  'MIXED',
] as const;

export const ANTI_AI_ARTIFACT_RESULTS = [
  'HUMAN_AUTHORED',
  'EDITORIALLY_DRAWN',
  'MACHINE_GENERATED',
  'CLIP_ART_LIKE',
  'INFOGRAPHIC_GENERIC',
  'AI_DECORATIVE',
] as const;

export const MAKER_EVIDENCE_STRENGTH_LEVELS = ['NONE', 'LOW', 'MODERATE', 'STRONG'] as const;

export const HUMAN_MARK_CONSISTENCY_RESULTS = [
  'SAME_HAND',
  'ADEQUATE',
  'MIXED_STYLES',
  'VECTOR_ICON_MIXED',
  'FAKE_HANDWRITING',
] as const;

export const LIME_FEED_DISTANCE_RESULTS = ['CLEAR', 'SUBTLE_BUT_PRESENT', 'TOO_WEAK', 'OVERPOWERING'] as const;

export const HAND_MARK_LEGIBILITY_RESULTS = ['STRONG_AT_FEED', 'PRESENT_AT_FEED', 'TOO_SMALL', 'LOST_AT_FEED'] as const;

export const V23A_FOUNDER_JUDGMENTS = [
  'MORE_LIME',
  'LESS_LIME',
  'LIME_IS_PERFECT',
  'TOO_MONOCHROME',
  'TOO_POLISHED',
  'TOO_AI_LOOKING',
  'ICONS_FEEL_GENERATED',
  'MAKE_ICONS_HAND_DRAWN',
  'MARKS_FEEL_HUMAN',
  'MARKS_FEEL_FAKE',
  'NEEDS_MORE_MAKER_PRESENCE',
  'TOO_MANY_DOODLES',
  'KEEP_THIS_CLEAN',
  'THIS_FEELS_HAND_MADE',
  'THATS_NDX',
] as const;

export const V23_FOUNDER_JUDGMENTS = [
  'YES_THIS_FEELS_LIKE_AN_OBJECT',
  'TOO_FLAT',
  'TOO_DIGITAL',
  'TOO_TEMPLATE_LIKE',
  'NEEDS_MORE_MATERIALITY',
  'TOO_MUCH_PAPER',
  'TOO_SCRAPBOOK',
  'TOO_VINTAGE',
  'TOO_CRAFTY',
  'TOO_MANY_LAYERS',
  'WRONG_SURFACE',
  'WRONG_OBJECT',
  'WRONG_ATTACHMENT',
  'TORN_PAPER_FEELS_RANDOM',
  'TAPE_FEELS_RANDOM',
  'NOT_MODERN_ENOUGH',
  'MORE_NOTEBOOK_ENERGY',
  'LESS_NOTEBOOK',
  'MAKE_THE_CANVAS_PARTICIPATE',
  'THATS_THE_ART_BOARD',
] as const;

export const HUMAN_MADE_FAILURE_STATES = [
  'FAIL_GENERIC_PICTOGRAMS',
  'FAIL_AI_ICONOGRAPHY',
  'FAIL_VECTOR_ICON_SYSTEM',
  'FAIL_MACHINE_PERFECT_MICRODETAIL',
  'FAIL_FAKE_HANDDRAWN',
  'FAIL_MULTIPLE_HAND_STYLES',
  'FAIL_LIME_DECORATIVE_ONLY',
  'FAIL_LIME_TOO_PASSIVE',
  'FAIL_NO_VISIBLE_MAKER_ACTION',
  'FAIL_INFOGRAPHIC_COLLAPSE',
] as const;

export const MATERIAL_FAILURE_STATES = [
  'FAIL_TEMPLATE_LIKE_CANVAS',
  'FAIL_BACKGROUND_NOT_CANVAS',
  'FAIL_GRAPHIC_FLOATING_ON_SURFACE',
  'FAIL_FAKE_PAPER_TEXTURE',
  'FAIL_FAKE_MATERIALITY',
  'FAIL_NO_CONSTRUCTION_HISTORY',
  'FAIL_NO_SURFACE_INTERACTION',
  'FAIL_RANDOM_TORN_EDGE',
  'FAIL_RANDOM_TAPE',
  'FAIL_RANDOM_FOLD',
  'FAIL_RANDOM_CLIP',
  'FAIL_RANDOM_LAYER',
  'FAIL_SCRAPBOOK_COLLAPSE',
  'FAIL_CRAFTY_COLLAPSE',
  'FAIL_ACCIDENTALLY_VINTAGE',
  'FAIL_FLAT_DIGITAL_CARD',
  'FAIL_ALL_POSTS_SAME_CANVAS',
  'FAIL_ALL_POSTS_TORN',
  'FAIL_ALL_POSTS_NOTEBOOK',
  'FAIL_ALL_POSTS_COLLAGE',
  'FAIL_MATERIAL_OVERBUILD',
  'FAIL_MATERIALITY_REINTRODUCES_CLUTTER',
  'FAIL_MATERIALITY_OVERRIDES_HIERARCHY',
  'FAIL_CANVAS_NOT_CHARACTER_CAUSAL',
  'FAIL_NOT_BESPOKE_ART_BOARD',
] as const;

export const FAL_MATERIAL_PROMPT_SECTION_ORDER = [
  'WHAT_HAPPENED',
  'WHAT_NDX_NOTICED',
  'PRIMARY_EDITORIAL_IDEA',
  'VIEWER_FIRST_READ',
  'VISUAL_SUBJECT',
  'CHARACTER_BEAT',
  'HUMOR_HUMAN_TRACE',
  'ARTIFACT_FORM',
  'BASE_SURFACE',
  'PAGE_CONSTRUCTION_MODE',
  'CONSTRUCTION_HISTORY',
  'EDGE_BEHAVIOR',
  'LAYER_STRUCTURE',
  'ATTACHMENT_LOGIC',
  'MATERIAL_DEPTH',
  'PRINT_SCAN_BEHAVIOR',
  'TYPOGRAPHY_SURFACE',
  'IMAGE_SURFACE',
  'EVIDENCE_SURFACE',
  'CONTROLLED_MISBEHAVIOR',
  'INFORMATION_HIERARCHY',
  'TYPOGRAPHY_ROLES',
  'UPPERCASE_GOVERNANCE',
  'IMAGE_TYPE_BALANCE',
  'READING_PATH',
  'CHARACTER_DENSITY',
  'INFORMATION_DENSITY',
  'MATERIAL_DENSITY',
  'CULTURAL_PARTICIPATION',
  'LIME_FUNCTION',
  'HUMAN_MADE_MARK_LANGUAGE',
  'WHO_DREW_MARKED_WHAT',
  'WHY_MARK_EXISTS',
  'HAND_DRAWN_VS_PRINTED',
  'LIME_INTERVENTION_BEHAVIOR',
  'LIME_APPLICATION_MODE',
  'MAKER_ACTION',
  'ANTI_AI_DETAIL_CONSTRAINTS',
  'STERILITY_GUARD',
  'TEMPLATE_GUARD',
  'NEGATIVE_CONSTRAINTS',
] as const;

export const ARTIFACT_MATERIALITY_SYSTEM_IMPLEMENTED = true as const;
export const CANVAS_AS_OBJECT_IMPLEMENTED = true as const;
export const ART_BOARD_DIRECTION_IMPLEMENTED = true as const;
export const MODERN_NOTEBOOK_EXPRESSION_IMPLEMENTED = true as const;
export const TORN_PAPER_GOVERNANCE_IMPLEMENTED = true as const;
export const PAGE_EDGE_BEHAVIOR_IMPLEMENTED = true as const;
export const ARTIFACT_LAYER_CONSTRUCTION_IMPLEMENTED = true as const;
export const ARTIFACT_CONSTRUCTION_HISTORY_IMPLEMENTED = true as const;
export const ARTIFACT_DEPTH_BEHAVIOR_IMPLEMENTED = true as const;
export const ATTACHMENT_CAUSALITY_IMPLEMENTED = true as const;
export const PRINT_SCAN_BEHAVIOR_IMPLEMENTED = true as const;
export const IMPERFECT_CANVAS_EVALUATION_IMPLEMENTED = true as const;
export const MATERIAL_DENSITY_EVALUATION_IMPLEMENTED = true as const;
export const MATERIAL_MODERNITY_EVALUATION_IMPLEMENTED = true as const;
export const FEED_MATERIAL_RHYTHM_IMPLEMENTED = true as const;
export const TEMPLATE_LIKE_CANVAS_GUARD_IMPLEMENTED = true as const;
export const FAKE_PAPER_TEXTURE_GUARD_IMPLEMENTED = true as const;
export const SCRAPBOOK_COLLAPSE_GUARD_IMPLEMENTED = true as const;
export const P0_5C_3_CHARACTER_RETENTION_PRESERVED = true as const;
export const EXPERIMENT_01_V2_3_ART_BOARD_PIPELINE_READY = true as const;
export const P0_5E_ROUND_01_MATERIAL_GATE_INTEGRATED = true as const;
export const CONTENT_OPERATIONS_ART_BOARD_DIRECTION_INTEGRATED = true as const;

export const NDX_HUMAN_MADE_MARK_SYSTEM_IMPLEMENTED = true as const;
export const HAND_DRAWN_ICONOGRAPHY_SUPPORTED = true as const;
export const GENERIC_PICTOGRAM_GUARD_IMPLEMENTED = true as const;
export const ANTI_AI_ARTIFACT_EVALUATION_IMPLEMENTED = true as const;
export const LIME_INTERVENTION_SYSTEM_IMPLEMENTED = true as const;
export const LIME_DENSITY_GOVERNANCE_IMPLEMENTED = true as const;
export const LIME_APPLICATION_MODE_IMPLEMENTED = true as const;
export const MAKER_EVIDENCE_STRENGTH_IMPLEMENTED = true as const;
export const SAME_HAND_CONSISTENCY_IMPLEMENTED = true as const;
export const LIME_FEED_DISTANCE_EVALUATION_IMPLEMENTED = true as const;
export const HAND_MARK_LEGIBILITY_IMPLEMENTED = true as const;
export const FEED_MAKER_RHYTHM_IMPLEMENTED = true as const;
export const P0_5C_4_ART_BOARD_MATERIALITY_PRESERVED = true as const;
export const V2_3_HUMAN_MADE_REVISION_READY = true as const;
