/**
 * P0.5C.7 — Canonical Hand-Built Notebook Carousel Grammar
 * V2.3 visual-authority amendment — page object first, not background → text.
 */

import { LIME_PROMINENCE_PROHIBITED } from './constants.js';

/** Amended V2.3 visual authority chain (P0.5C.7). */
export const NDX_NOTEBOOK_CAROUSEL_AUTHORITY_CHAIN = [
  'CONTENT_THESIS',
  'PAGE_OBJECT',
  'PAGE_MATERIAL',
  'BINDING_EDGE_LOGIC',
  'CONSTRUCTION_HISTORY',
  'BESPOKE_COMPOSITION',
  'EDITORIAL_PHOTOGRAPHY',
  'TYPOGRAPHY',
  'EVIDENCE',
  'CHARACTER_TRACE',
  'LIME_INTERRUPTION',
  'QA',
] as const;

/** Legacy chain blocked — do not revert. */
export const BLOCKED_LEGACY_AUTHORITY_CHAIN = [
  'BACKGROUND',
  'TEXT',
  'PHOTO',
  'ANNOTATION',
] as const;

export const NOTEBOOK_CAROUSEL_GRAMMAR_VERSION = 'NOTEBOOK_CAROUSEL_GRAMMAR@P0.5C.7' as const;

export function notebookCarouselAuthorityChainCorrect(): boolean {
  const chain = NDX_NOTEBOOK_CAROUSEL_AUTHORITY_CHAIN;
  return (
    chain.indexOf('CONTENT_THESIS') === 0 &&
    chain.indexOf('PAGE_OBJECT') === 1 &&
    chain.indexOf('PAGE_MATERIAL') < chain.indexOf('TYPOGRAPHY') &&
    chain.indexOf('CONSTRUCTION_HISTORY') < chain.indexOf('BESPOKE_COMPOSITION') &&
    chain.indexOf('EDITORIAL_PHOTOGRAPHY') < chain.indexOf('TYPOGRAPHY') &&
    chain.indexOf('LIME_INTERRUPTION') < chain.indexOf('QA')
  );
}

export function legacyAuthorityChainBlocked(): boolean {
  return BLOCKED_LEGACY_AUTHORITY_CHAIN[0] === 'BACKGROUND';
}

export const NDX_CANONICAL_NOTEBOOK_CAROUSEL_GRAMMAR_IMPLEMENTED = true as const;
export const PHYSICAL_PAGE_OBJECT_CONTRACT_IMPLEMENTED = true as const;
export const PHYSICAL_PAGE_LINEAGE_REQUIRED = true as const;
export const HAND_BUILT_CONSTRUCTION_HISTORY_IMPLEMENTED = true as const;
export const PUNCHED_TORN_BOUND_PAGE_EVIDENCE_SUPPORTED = true as const;
export const NDX_AUTHORED_TEXT_UPPERCASE_ENFORCED = true as const;
export const AUTHENTIC_SOURCE_CASE_PRESERVED = true as const;
export const EDITORIAL_PHOTOGRAPHY_PAGE_INTEGRATION_IMPLEMENTED = true as const;
export const CLEAN_DIGITAL_PHOTO_BOX_GRAMMAR_PROHIBITED = true as const;
export const PAGE_MATERIAL_VARIATION_IMPLEMENTED = true as const;
export const EDGE_BINDING_VARIATION_IMPLEMENTED = true as const;
export const LIME_REQUIRED = true as const;
export const HUMAN_MARK_MAKING_PRESERVED = true as const;
export const DECORATIVE_HANDWRITING_WITHOUT_FUNCTION_PROHIBITED = true as const;
export const BESPOKE_COMPOSITION_REQUIRED = true as const;
export const CLONED_LAYOUT_GRAMMAR_PROHIBITED = true as const;
export const SEQUENCE_PAGE_ROLES_IMPLEMENTED = true as const;
export const COHESIVE_NOT_IDENTICAL_ENFORCED = true as const;
export const V2_3_PROMPT_COMPILER_UPDATED = true as const;
export const NEGATIVE_TEMPLATE_CONSTRAINTS_IMPLEMENTED = true as const;
export const PHYSICALITY_GATE_IMPLEMENTED = true as const;
export const TEMPLATE_GRAMMAR_GATE_IMPLEMENTED = true as const;
export const UPPERCASE_AUTHORSHIP_GATE_IMPLEMENTED = true as const;
export const PHOTO_INTEGRATION_GATE_IMPLEMENTED = true as const;
export const CONSTRUCTION_HISTORY_GATE_IMPLEMENTED = true as const;
export const PAGE_VARIETY_QA_IMPLEMENTED = true as const;
export const LAUNCH_POSTS_REGISTERED_AS_NORTH_STAR_EVIDENCE = true as const;
export const LAUNCH_POSTS_USED_AS_LITERAL_TEMPLATE = false as const;
export const V2_3_HISTORICAL_ASSETS_MUTATED = false as const;
export const NEW_VERSION_V2_4_CREATED = false as const;
export const FOUNDER_REVIEW_REQUIRED_FOR_REGENERATION = true as const;
export const AUTOMATIC_PROVIDER_SPEND_DURING_SPRINT = false as const;
export const P0_5C_7_IMPLEMENTED = true as const;

export function allP05C7SuccessCriteria(): Record<string, boolean> {
  return {
    NDX_CANONICAL_NOTEBOOK_CAROUSEL_GRAMMAR_IMPLEMENTED,
    PHYSICAL_PAGE_OBJECT_CONTRACT_IMPLEMENTED,
    PHYSICAL_PAGE_LINEAGE_REQUIRED,
    HAND_BUILT_CONSTRUCTION_HISTORY_IMPLEMENTED,
    PUNCHED_TORN_BOUND_PAGE_EVIDENCE_SUPPORTED,
    NDX_AUTHORED_TEXT_UPPERCASE_ENFORCED,
    AUTHENTIC_SOURCE_CASE_PRESERVED,
    EDITORIAL_PHOTOGRAPHY_PAGE_INTEGRATION_IMPLEMENTED,
    CLEAN_DIGITAL_PHOTO_BOX_GRAMMAR_PROHIBITED,
    PAGE_MATERIAL_VARIATION_IMPLEMENTED,
    EDGE_BINDING_VARIATION_IMPLEMENTED,
    LIME_REQUIRED,
    LIME_PROMINENCE_PROHIBITED,
    HUMAN_MARK_MAKING_PRESERVED,
    DECORATIVE_HANDWRITING_WITHOUT_FUNCTION_PROHIBITED,
    BESPOKE_COMPOSITION_REQUIRED,
    CLONED_LAYOUT_GRAMMAR_PROHIBITED,
    SEQUENCE_PAGE_ROLES_IMPLEMENTED,
    COHESIVE_NOT_IDENTICAL_ENFORCED,
    V2_3_PROMPT_COMPILER_UPDATED,
    NEGATIVE_TEMPLATE_CONSTRAINTS_IMPLEMENTED,
    PHYSICALITY_GATE_IMPLEMENTED,
    TEMPLATE_GRAMMAR_GATE_IMPLEMENTED,
    UPPERCASE_AUTHORSHIP_GATE_IMPLEMENTED,
    PHOTO_INTEGRATION_GATE_IMPLEMENTED,
    CONSTRUCTION_HISTORY_GATE_IMPLEMENTED,
    PAGE_VARIETY_QA_IMPLEMENTED,
    LAUNCH_POSTS_REGISTERED_AS_NORTH_STAR_EVIDENCE,
    LAUNCH_POSTS_USED_AS_LITERAL_TEMPLATE,
    V2_3_HISTORICAL_ASSETS_MUTATED,
    NEW_VERSION_V2_4_CREATED,
    FOUNDER_REVIEW_REQUIRED_FOR_REGENERATION,
    AUTOMATIC_PROVIDER_SPEND_DURING_SPRINT,
    BRAND_CHARACTER_MUTATED: false,
    BRAND_CANON_MUTATED: false,
    HISTORICAL_LINEAGE_MUTATED: false,
  };
}
