/**
 * P0.5C.5A — V2.3 Generation Authority adapter + constants.
 */

export const V23_FAL_COMPILER_VERSION = 'falPromptCompilerV23@P0.5C.6A' as const;
export const V23_EXPERIMENT_ID = 'marketing-expression-experiment-01-v23' as const;

export const V23_METHODOLOGY_VERSIONS = [
  'AUTHORED_ARTIFACT@P0.5C.6A',
  'VISUAL_AUTHORITY@P0.5C.6',
  'HUMAN_MADE_MARKS@P0.5C.4A',
  'SIGNATURE_LIME@P0.5C.4B',
  'SIGNATURE_LIME_RESTRAINT@P0.5C.4B.1',
  'FIRST_PERSON_AUTHORSHIP@P0.5C.5',
  'INTERNAL_LABEL_QUARANTINE@P0.5C.5',
  'ART_BOARD_MATERIALITY@P0.5C.4',
  'CULTURAL_IMAGE_PARTICIPATION@P0.5C.2',
] as const;

export const V23_GOVERNANCE_VERSIONS = [
  'AUTHORED_ARTIFACT_GRAMMAR@P0.5C.6A',
  'HUMAN_HISTORY_AUTHORITY@P0.5C.6A',
  'TEMPLATE_FRAME_REMOVAL@P0.5C.6A',
  'VISUAL_APPETITE_AUTHORITY@P0.5C.6',
  'BESPOKE_ART_DIRECTION@P0.5C.6',
  'PUBLIC_AUTHORSHIP@P0.5C.5',
  'SIGNATURE_LIME_REQUIRED@P0.5C.4B',
  'SIGNATURE_LIME_RESTRAINT@P0.5C.4B.1',
  'HUMAN_MADE_MARKS@P0.5C.4A',
  'CHROMATIC_ATTENTION_HIERARCHY@P0.5C.4B.1',
] as const;

export const V2_3_REGENERATION_USES_CURRENT_CONTRACTS = true as const;
export const V2_3_REGENERATION_RECOMPILES_PROMPT = true as const;
export const V2_3_STANDARD_REGENERATION_USES_STORED_PROMPT_SNAPSHOT = false as const;
export const HISTORICAL_PROMPT_REPLAY_SUPPORTED = true as const;
export const C4A_ACTIVE_IN_REGENERATION = true as const;
export const C4B_ACTIVE_IN_REGENERATION = true as const;
export const C5_ACTIVE_IN_REGENERATION = true as const;
export const SIGNATURE_LIME_REQUIRED = true as const;
export const HUMAN_MADE_MARKS_ACTIVE = true as const;
export const FIRST_PERSON_AUTHORSHIP_ACTIVE = true as const;
export const INTERNAL_LABEL_QUARANTINE_ACTIVE = true as const;
export const CURRENT_PUBLIC_COPY_ACTIVE = true as const;
export const LEGACY_ASSET_LINEAGE_CLASSIFIED = true as const;
export const SELECTED_ASSET_AUTHORITY_IMPLEMENTED = true as const;
export const ROUND_01_LOCK_REQUIRES_CURRENT_LINEAGE = true as const;
