/**
 * P0.VR.REPLICATION.3A — Authority reference benchmarks (NDXBOOK overview mobile pilot).
 * Derived from approved authority QA spec — not synthetic generic placeholders.
 */

import type { NdxDriftTraceRegionId } from './constants.js';
import type { RegionReferenceSnapshot } from './types.js';

export const NDX_AUTHORITY_REGION_BENCHMARKS: Record<NdxDriftTraceRegionId, RegionReferenceSnapshot> = {
  'host-header': {
    bounds: '0–52px full width',
    dominantSurfaces: ['warm host bar', 'bottom divider rule'],
    majorChildBlocks: ['SITE 00 wordmark', 'red diamond mark', 'menu icon', 'avatar circle'],
    textBlockCount: 1,
    imageBlockCount: 2,
    accentColorRole: 'brand red diamond + neutral host bar',
    layoutDirection: 'horizontal space-between',
    majorRelationships: ['mark left', 'actions right', 'divider below'],
    assetPresence: ['site00-diamond', 'avatar-photo-or-placeholder'],
    visualDensity: 'COMPACT',
  },
  'project-masthead': {
    bounds: 'below breadcrumb, ~120px band',
    dominantSurfaces: ['light editorial field'],
    majorChildBlocks: ['breadcrumb PROJECTS › NDXBOOK', 'large NDXBOOK title', 'subtitle', 'FOUNDER OWNED badge'],
    textBlockCount: 4,
    imageBlockCount: 0,
    accentColorRole: 'black typography on light ground',
    layoutDirection: 'vertical stack + split with context column',
    majorRelationships: ['breadcrumb above title', 'badge below subtitle', 'vertical rule to context column'],
    assetPresence: [],
    visualDensity: 'MEDIUM',
  },
  'masthead-context-column': {
    bounds: 'right column adjacent masthead',
    dominantSurfaces: ['narrow status column'],
    majorChildBlocks: ['culture label', 'category value', 'status stack'],
    textBlockCount: 3,
    imageBlockCount: 0,
    accentColorRole: 'muted meta typography',
    layoutDirection: 'vertical right-aligned',
    majorRelationships: ['aligned to masthead top', 'vertical divider left'],
    assetPresence: [],
    visualDensity: 'COMPACT',
  },
  'module-nav': {
    bounds: 'horizontal nav band ~32–40px',
    dominantSurfaces: ['ruled tab strip'],
    majorChildBlocks: ['OVERVIEW', 'IDENTITY', 'EVOLVE', 'PRODUCTION', 'REVIEWS', 'LIBRARY'],
    textBlockCount: 6,
    imageBlockCount: 0,
    accentColorRole: 'active tab underline',
    layoutDirection: 'horizontal scroll',
    majorRelationships: ['below masthead', 'above hero'],
    assetPresence: [],
    visualDensity: 'COMPACT',
  },
  'hero-editorial': {
    bounds: '~140–180px dominant block',
    dominantSurfaces: ['black dominant field', 'lime accent block', 'grayscale image slices'],
    majorChildBlocks: [
      'editorial left copy column',
      '3 image slices',
      'lime NDX graphic overlay',
      'right graphic cell',
      'CTA button',
    ],
    textBlockCount: 2,
    imageBlockCount: 4,
    accentColorRole: 'black ground + lime brand block',
    layoutDirection: 'split editorial + graphic column',
    majorRelationships: ['copy left', 'imagery center', 'graphic right', 'CTA anchored in copy'],
    assetPresence: ['hero-photo-slices', 'ndx-lime-graphic', 'cta-button'],
    visualDensity: 'EXPANSIVE',
  },
  'progress-phase': {
    bounds: 'thin band ~48px',
    dominantSurfaces: ['progress track', 'phase label'],
    majorChildBlocks: ['bar fill', 'current phase copy'],
    textBlockCount: 2,
    imageBlockCount: 0,
    accentColorRole: 'dark fill on light track',
    layoutDirection: 'vertical stack',
    majorRelationships: ['below hero', 'above metrics'],
    assetPresence: [],
    visualDensity: 'COMPACT',
  },
  'metric-status-row': {
    bounds: '4-up row ~72px',
    dominantSurfaces: ['four equal cells', 'dividers'],
    majorChildBlocks: ['icon', 'code/number', 'label'],
    textBlockCount: 4,
    imageBlockCount: 4,
    accentColorRole: 'status color per cell',
    layoutDirection: 'horizontal 4-column grid',
    majorRelationships: ['equal width cells', 'shared baseline'],
    assetPresence: ['metric-icons'],
    visualDensity: 'MEDIUM',
  },
  'focus-milestone': {
    bounds: 'dual column ~80px',
    dominantSurfaces: ['current focus', 'next milestone'],
    majorChildBlocks: ['focus title', 'milestone title', 'supporting thumb optional'],
    textBlockCount: 2,
    imageBlockCount: 1,
    accentColorRole: 'neutral editorial',
    layoutDirection: 'two column',
    majorRelationships: ['focus left', 'milestone right'],
    assetPresence: ['milestone-art-optional'],
    visualDensity: 'MEDIUM',
  },
  'recent-activity': {
    bounds: 'list block ~120px+',
    dominantSurfaces: ['ruled list rows'],
    majorChildBlocks: ['section label', 'activity rows', 'view link'],
    textBlockCount: 5,
    imageBlockCount: 0,
    accentColorRole: 'neutral list typography',
    layoutDirection: 'vertical list',
    majorRelationships: ['header row', 'numbered items'],
    assetPresence: [],
    visualDensity: 'MEDIUM',
  },
  'bottom-nav': {
    bounds: 'fixed 56px host bottom shell',
    dominantSurfaces: ['SITE 00 bottom nav shell'],
    majorChildBlocks: ['5 nav items', 'icon + label stacks', 'active PROJECTS state'],
    textBlockCount: 5,
    imageBlockCount: 5,
    accentColorRole: 'active fill on PROJECTS tab',
    layoutDirection: 'horizontal equal nav',
    majorRelationships: ['persistent shell', 'not module tab nav'],
    assetPresence: ['bottom-nav-icons'],
    visualDensity: 'COMPACT',
  },
};
