/**
 * P0.VR.REPLICATION.3A — What ShellFirstNdxOverviewTwin actually implements (source truth).
 */

import { NDX_SECTION_NAV_LABELS } from '../p0vrReplication2/constants.js';
import type { NdxDriftTraceRegionId } from './constants.js';
import type {
  GeneratedSourceSnapshot,
  ReconstructionDecisionSnapshot,
  DetectedRegionSnapshot,
  BlueprintRegionSnapshot,
  AssetBindingTrace,
  RenderedRegionSnapshot,
} from './types.js';

type PilotRuntimeRegion = {
  detected: DetectedRegionSnapshot;
  blueprint: BlueprintRegionSnapshot | null;
  decision: ReconstructionDecisionSnapshot;
  source: GeneratedSourceSnapshot;
  assets: AssetBindingTrace[];
  render: RenderedRegionSnapshot;
};

export const NDX_PILOT_RUNTIME_REGION_MAP: Record<NdxDriftTraceRegionId, PilotRuntimeRegion> = {
  'host-header': {
    detected: {
      summary: 'header shell — host chrome (profile proxy, not vision)',
      subregionCount: 4,
      features: ['wordmark slot', 'menu slot', 'avatar slot', 'divider implied'],
      confidence: 'MEDIUM',
      provider: 'pageRegionLayoutProfile',
      model: 'heuristic-profile-v1',
    },
    blueprint: {
      bandId: 'host-header',
      geometry: '52px fixed host band',
      buildMode: 'DIRECTLY_RECONSTRUCTED',
      contentType: 'host-chrome',
      genericness: 'MACRO',
      subregionCount: 4,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: false,
      notes: 'SITE 00 wordmark + diamond; menu uses ellipsis icon not hamburger; avatar empty span',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__host',
      elementSummary: 'header with brand + 2 actions (no red diamond fidelity check)',
      subregionCount: 3,
    },
    assets: [
      {
        slotId: 'host-diamond',
        authorityExpected: 'red SITE 00 diamond mark',
        decision: 'Site00Diamond HOST_DEFAULT',
        selectedPath: null,
        loaded: true,
        cropStrategy: 'vector component',
        renderSuccess: true,
        failureLayer: null,
      },
    ],
    render: {
      boundsApprox: '52px top band',
      computedStylesSummary: 'warm host bar #ebe6dc',
      assetLoadState: 'diamond component mounted',
      textContentSummary: 'SITE 00',
      screenshotCropRef: null,
    },
  },
  'project-masthead': {
    detected: {
      summary: 'masthead title stack (profile)',
      subregionCount: 4,
      features: ['breadcrumb', 'title', 'subtitle', 'badge'],
      confidence: 'MEDIUM',
      provider: 'pageRegionLayoutProfile',
      model: 'heuristic-profile-v1',
    },
    blueprint: {
      bandId: 'masthead',
      geometry: 'normalized masthead band',
      buildMode: 'MEASURED',
      contentType: 'masthead-title-block',
      genericness: 'MACRO',
      subregionCount: 4,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: false,
      notes: 'Breadcrumb separate band; title typography approximated',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__masthead + .site00-sft__breadcrumb',
      elementSummary: 'breadcrumb nav + h1 + subtitle + badge',
      subregionCount: 4,
    },
    assets: [],
    render: {
      boundsApprox: 'masthead grid band',
      computedStylesSummary: 'light editorial typography',
      assetLoadState: 'n/a',
      textContentSummary: 'NDXBOOK · FOUNDER OWNED',
      screenshotCropRef: null,
    },
  },
  'masthead-context-column': {
    detected: {
      summary: 'right meta column (profile supporting region)',
      subregionCount: 2,
      features: ['culture label', 'status date'],
      confidence: 'LOW',
      provider: 'pageRegionLayoutProfile',
      model: 'heuristic-profile-v1',
    },
    blueprint: {
      bandId: 'masthead-context-column',
      geometry: 'narrow right column',
      buildMode: 'MEASURED',
      contentType: 'context-column',
      genericness: 'GENERIC',
      subregionCount: 2,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: true,
      notes: 'Generic CULTURE / STATUS copy — not authority culture intelligence column',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__masthead-context',
      elementSummary: '2 label/value pairs',
      subregionCount: 2,
    },
    assets: [],
    render: {
      boundsApprox: 'right column in masthead grid',
      computedStylesSummary: '9px uppercase labels',
      assetLoadState: 'n/a',
      textContentSummary: 'Editorial systems + date',
      screenshotCropRef: null,
    },
  },
  'module-nav': {
    detected: {
      summary: 'horizontal module labels (6 tabs)',
      subregionCount: 6,
      features: [...NDX_SECTION_NAV_LABELS],
      confidence: 'MEDIUM',
      provider: 'constants NDX_SECTION_NAV_LABELS',
      model: 'static-list',
    },
    blueprint: {
      bandId: 'section-nav',
      geometry: 'nav band ~8% height',
      buildMode: 'MEASURED',
      contentType: 'section-nav',
      genericness: 'MACRO',
      subregionCount: 6,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: true,
      collapsedToGeneric: false,
      notes: 'Labels match authority set; underline style differs',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__section-nav',
      elementSummary: '6 span tabs with active underline',
      subregionCount: 6,
    },
    assets: [],
    render: {
      boundsApprox: 'horizontal scroll nav',
      computedStylesSummary: 'underline active tab',
      assetLoadState: 'n/a',
      textContentSummary: 'OVERVIEW … LIBRARY',
      screenshotCropRef: null,
    },
  },
  'hero-editorial': {
    detected: {
      summary: 'hero with image and text (profile — NOT 4-part literal)',
      subregionCount: 2,
      features: ['single media frame', 'copy block'],
      confidence: 'LOW',
      provider: 'pageRegionLayoutProfile',
      model: 'heuristic-profile-v1',
    },
    blueprint: {
      bandId: 'hero-editorial',
      geometry: 'media band ~14% viewport',
      buildMode: 'MEASURED',
      contentType: 'hero-editorial',
      genericness: 'GENERIC',
      subregionCount: 1,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: true,
      notes: 'Collapsed to generic media block + headline — authority 4-slice + lime graphic + CTA not represented',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__hero',
      elementSummary: 'single .site00-sft__hero-image + copy + decorative .site00-sft__hero-graphic',
      subregionCount: 3,
    },
    assets: [
      {
        slotId: 'hero-primary',
        authorityExpected: 'black field + 3 grayscale slices + lime NDX graphic',
        decision: 'entryProductionArtwork(first card) OR AssetPendingPlaceholder',
        selectedPath: 'dynamic / null',
        loaded: false,
        cropStrategy: 'cover single frame',
        renderSuccess: false,
        failureLayer: 'ASSET_BINDING',
      },
      {
        slotId: 'hero-lime-graphic',
        authorityExpected: 'lime brand overlay cell',
        decision: 'NOT BOUND',
        selectedPath: null,
        loaded: false,
        cropStrategy: 'n/a',
        renderSuccess: false,
        failureLayer: 'SOURCE_GENERATION',
      },
      {
        slotId: 'hero-cta',
        authorityExpected: 'CTA button in copy column',
        decision: 'NOT IMPLEMENTED',
        selectedPath: null,
        loaded: false,
        cropStrategy: 'n/a',
        renderSuccess: false,
        failureLayer: 'SOURCE_GENERATION',
      },
    ],
    render: {
      boundsApprox: 'full-width hero grid',
      computedStylesSummary: 'single background image or beige placeholder',
      assetLoadState: 'conditional on production card art',
      textContentSummary: 'EDITORIAL + production title',
      screenshotCropRef: null,
    },
  },
  'progress-phase': {
    detected: {
      summary: 'progress band (profile STATUS region)',
      subregionCount: 2,
      features: ['track', 'label'],
      confidence: 'MEDIUM',
      provider: 'pageRegionLayoutProfile',
      model: 'heuristic-profile-v1',
    },
    blueprint: {
      bandId: 'progress-phase',
      geometry: 'thin band',
      buildMode: 'CONTENT_BOUND',
      contentType: 'progress-phase',
      genericness: 'MACRO',
      subregionCount: 2,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: false,
      notes: 'Static 58% fill — not tied to live phase metric',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__progress',
      elementSummary: 'track + fill + label',
      subregionCount: 2,
    },
    assets: [],
    render: {
      boundsApprox: 'progress section',
      computedStylesSummary: '6px track black fill',
      assetLoadState: 'n/a',
      textContentSummary: 'Phase progress label',
      screenshotCropRef: null,
    },
  },
  'metric-status-row': {
    detected: {
      summary: '4 metric cells (profile METRICS)',
      subregionCount: 4,
      features: ['creative production', 'founder review', 'package readiness', 'technical health'],
      confidence: 'MEDIUM',
      provider: 'NDX_METRIC_STATUS_LABELS',
      model: 'static-list',
    },
    blueprint: {
      bandId: 'metric-status-row',
      geometry: '4-up grid',
      buildMode: 'CONTENT_BOUND',
      contentType: 'metric-row',
      genericness: 'MACRO',
      subregionCount: 4,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: false,
      notes: 'Labels match authority semantics; icons/status colors not replicated',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__metrics',
      elementSummary: '4 cells with count + label (pulse counts mapped)',
      subregionCount: 4,
    },
    assets: [
      {
        slotId: 'metric-icons',
        authorityExpected: 'per-cell iconography + status color',
        decision: 'numbers only — no icons',
        selectedPath: null,
        loaded: false,
        cropStrategy: 'n/a',
        renderSuccess: false,
        failureLayer: 'SOURCE_GENERATION',
      },
    ],
    render: {
      boundsApprox: '4-column metric grid',
      computedStylesSummary: 'light cells bordered',
      assetLoadState: 'numeric only',
      textContentSummary: 'operatingState.pulse counts',
      screenshotCropRef: null,
    },
  },
  'focus-milestone': {
    detected: {
      summary: 'dual focus/milestone (inferred from activity region split)',
      subregionCount: 2,
      features: ['current focus', 'next milestone'],
      confidence: 'LOW',
      provider: 'pilot shell map',
      model: 'heuristic',
    },
    blueprint: {
      bandId: 'focus-milestone',
      geometry: '2-column band',
      buildMode: 'CONTENT_BOUND',
      contentType: 'focus-milestone',
      genericness: 'MACRO',
      subregionCount: 2,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: false,
      notes: 'Titles from production cards — no supporting imagery band',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__focus',
      elementSummary: 'two columns CURRENT FOCUS / NEXT MILESTONE',
      subregionCount: 2,
    },
    assets: [],
    render: {
      boundsApprox: 'focus grid',
      computedStylesSummary: 'two equal columns',
      assetLoadState: 'optional art not used',
      textContentSummary: 'production card titles',
      screenshotCropRef: null,
    },
  },
  'recent-activity': {
    detected: {
      summary: 'activity list (profile radar region)',
      subregionCount: 3,
      features: ['header', 'rows', 'link'],
      confidence: 'MEDIUM',
      provider: 'pageRegionLayoutProfile',
      model: 'heuristic-profile-v1',
    },
    blueprint: {
      bandId: 'recent-activity',
      geometry: 'list block',
      buildMode: 'CONTENT_BOUND',
      contentType: 'activity-list',
      genericness: 'MACRO',
      subregionCount: 3,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: false,
      notes: 'Radar strings bound — visual treatment simplified vs authority',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__activity',
      elementSummary: 'numbered list + links',
      subregionCount: 3,
    },
    assets: [],
    render: {
      boundsApprox: 'activity section',
      computedStylesSummary: 'ruled list rows',
      assetLoadState: 'n/a',
      textContentSummary: 'radarItems slice',
      screenshotCropRef: null,
    },
  },
  'bottom-nav': {
    detected: {
      summary: 'persistent bottom nav (5 items)',
      subregionCount: 5,
      features: ['icons', 'labels', 'active state'],
      confidence: 'MEDIUM',
      provider: 'ndxFounderWorkspaceMobileNav',
      model: 'static-config',
    },
    blueprint: {
      bandId: 'bottom-nav',
      geometry: '56px fixed shell',
      buildMode: 'DIRECTLY_RECONSTRUCTED',
      contentType: 'persistent-bottom-nav',
      genericness: 'MACRO',
      subregionCount: 5,
    },
    decision: {
      strategy: 'SHELL_FIRST_DIRECT',
      literalReplication: false,
      collapsedToGeneric: false,
      notes: 'Uses project workspace nav — authority may show PROJECTS active in host shell nav',
    },
    source: {
      component: 'ShellFirstNdxOverviewTwin',
      selectorOrClass: '.site00-sft__bottom-nav',
      elementSummary: '5 Link/span nav items with NDXBottomNavIcon',
      subregionCount: 5,
    },
    assets: [
      {
        slotId: 'bottom-nav-icons',
        authorityExpected: 'SITE 00 host bottom nav icon set',
        decision: 'NDXBottomNavIcon from founder workspace config',
        selectedPath: 'component icons',
        loaded: true,
        cropStrategy: 'vector',
        renderSuccess: true,
        failureLayer: null,
      },
    ],
    render: {
      boundsApprox: 'fixed bottom 56px',
      computedStylesSummary: '#ebe6dc bar',
      assetLoadState: 'icons mounted',
      textContentSummary: 'workspace nav labels',
      screenshotCropRef: null,
    },
  },
};
