/**
 * P0.VR.1D — thresholds, taxonomy, authority order.
 */

import type { VisualDifferenceKind } from './types.js';

/** Formal authority order — reference image outranks text. */
export const VISUAL_AUTHORITY_ORDER = [
  'REFERENCE_IMAGE',
  'STRUCTURAL_EXTRACTION',
  'VISUAL_TOKENS',
  'REGION_GEOMETRY',
  'COMPONENT_CONSTRAINTS',
  'TEXT_DESCRIPTION',
  'GENERIC_DESIGN_HEURISTICS',
] as const;

export const PIXEL_MATCH_THRESHOLDS = {
  STRUCTURAL_PASS: 0.82,
  VISUAL_PASS: 0.9,
  PIXEL_PASS: 0.94,
} as const;

export const DEFAULT_GEOMETRY_TOLERANCES = {
  positionTolerancePx: 3,
  sizeTolerancePx: 4,
  rotationToleranceDeg: 1.5,
} as const;

export const VISUAL_QA_FAILURE_TAXONOMY = [
  'FAIL_REFERENCE_NOT_USED_AS_IMAGE_AUTHORITY',
  'FAIL_TEXT_DERIVED_VISUAL_DRIFT',
  'FAIL_REGION_GEOMETRY_DRIFT',
  'FAIL_CAMERA_FRAME_DRIFT',
  'FAIL_TYPOGRAPHY_POSITION_DRIFT',
  'FAIL_ARTWORK_POSITION_DRIFT',
  'FAIL_RESPONSIVE_REFERENCE_DRIFT',
  'FAIL_DESKTOP_REFERENCE_DRIFT',
  'FAIL_MOBILE_REFERENCE_DRIFT',
  'FAIL_EXTRA_ELEMENT',
  'FAIL_MISSING_ELEMENT',
  'FAIL_UNAUTHORIZED_DESIGN_IMPROVEMENT',
] as const;

export type VisualQaFailureCode = (typeof VISUAL_QA_FAILURE_TAXONOMY)[number];

export const DIFFERENCE_KIND_TO_QA: Partial<Record<VisualDifferenceKind, VisualQaFailureCode>> = {
  POSITION_DRIFT: 'FAIL_REGION_GEOMETRY_DRIFT',
  SIZE_DRIFT: 'FAIL_REGION_GEOMETRY_DRIFT',
  TYPOGRAPHY_DRIFT: 'FAIL_TYPOGRAPHY_POSITION_DRIFT',
  ARTWORK_DRIFT: 'FAIL_ARTWORK_POSITION_DRIFT',
  CAMERA_DRIFT: 'FAIL_CAMERA_FRAME_DRIFT',
  RESPONSIVE_DRIFT: 'FAIL_RESPONSIVE_REFERENCE_DRIFT',
  MISSING_ELEMENT: 'FAIL_MISSING_ELEMENT',
  EXTRA_ELEMENT: 'FAIL_EXTRA_ELEMENT',
};

export const P0_VR_LINEAGE_PRESERVED = ['P0.VR.1', 'P0.VR.1A', 'P0.VR.1C'] as const;
