/**
 * P0.5E — Generic Studio World marketing campaign production (brand-agnostic).
 */

export const MARKETING_CAMPAIGN_PRODUCTION_V1 = 'MARKETING_CAMPAIGN_PRODUCTION_V1' as const;

export const ASSET_PRODUCTION_STATUSES = [
  'PLANNED',
  'CONTRACT_READY',
  'READY_FOR_GENERATION',
  'GENERATED',
  'UNDER_REVIEW',
  'REVISION_REQUESTED',
  'REVISED',
  'APPROVED',
  'LOCKED',
  'REOPENED',
  'SUPERSEDED',
] as const;

export const CAMPAIGN_PERIOD_STATUSES = [
  'PLANNING',
  'IN_PRODUCTION',
  'UNDER_REVIEW',
  'APPROVED',
  'LOCKED',
  'PUBLISHING_READY',
  'ARCHIVED',
] as const;

export const PRODUCTION_ROUND_STATUSES = [
  'PLANNED',
  'FORMULATING',
  'CONTRACTS_READY',
  'GENERATING',
  'UNDER_REVIEW',
  'REVISION_REQUESTED',
  'APPROVED',
  'LOCKED',
] as const;

export const SEQUENCE_POSITION_ROLES = [
  'OPEN',
  'REVEAL',
  'CONTEXT',
  'EVIDENCE',
  'ESCALATION',
  'COMPLICATION',
  'CONTRADICTION',
  'COMPARISON',
  'PATTERN',
  'ZOOM_IN',
  'ZOOM_OUT',
  'CALLBACK',
  'CORRECTION',
  'TURN',
  'PAUSE',
  'PAYOFF',
  'RESOLUTION',
  'CTA',
  'SOURCE',
  'OTHER',
] as const;

export const CLIENT_APPROVAL_STAGES = [
  'CAMPAIGN_STRATEGY',
  'CONTENT_SLATE',
  'CONTENT_PIECE',
  'PRODUCTION_ROUND',
  'INDIVIDUAL_ASSET',
  'COMPLETE_SEQUENCE',
  'CAPTION',
  'CTA',
  'PUBLISHING_PACKAGE',
] as const;

export const CLIENT_ASSET_JUDGMENTS = ['APPROVE', 'REQUEST_REVISION'] as const;

export const CLIENT_REVISION_REASONS = [
  'COPY',
  'IMAGE',
  'LAYOUT',
  'TONE',
  'BRAND_FIT',
  'FACTUAL_ISSUE',
  'TOO_BUSY',
  'TOO_EMPTY',
  'OTHER',
] as const;

export const INTERNAL_CREATIVE_JUDGMENTS = [
  'LOCK_IT',
  'DEVELOP',
  'TOO_REPETITIVE',
  'TOO_SAFE',
  'TOO_BUSY',
  'TOO_CLEAN',
  'TOO_GENERIC',
  'TOO_TEMPLATE_LIKE',
  'WRONG_VISUAL_SUBJECT',
  'WRONG_HIERARCHY',
  'WRONG_CHARACTER',
  'WRONG_EMOTIONAL_TEMPERATURE',
  'NOT_ENOUGH_CULTURE',
  'NOT_ENOUGH_VISUAL_APPETITE',
  'SEQUENCE_DOESNT_PROGRESS',
  'CAMPAIGN_RHYTHM_FAILURE',
  'REGENERATE_WITH_DELTA',
] as const;

export const REOPEN_DOWNSTREAM_EFFECTS = [
  'NO_DOWNSTREAM_EFFECT',
  'REVIEW_REQUIRED',
  'SEQUENCE_REVIEW_REQUIRED',
  'CAMPAIGN_REVIEW_REQUIRED',
] as const;

export const CAMPAIGN_FAILURE_STATES = [
  'FAIL_HORIZONTAL_REPETITION',
  'FAIL_VERTICAL_DISCONTINUITY',
  'FAIL_CAMPAIGN_MONOTONY',
  'FAIL_TEMPLATE_PRODUCTION',
  'FAIL_SLIDE_02_AS_SECOND_COVER',
  'FAIL_NO_SWIPE_REWARD',
  'FAIL_INFORMATION_REPETITION',
  'FAIL_NO_SEQUENCE_PROGRESSION',
  'FAIL_VISUAL_SUBJECT_REPETITION',
  'FAIL_DENSITY_MONOTONY',
  'FAIL_EMOTIONAL_MONOTONY',
  'FAIL_CULTURAL_MONOTONY',
  'FAIL_CHARACTER_DRIFT',
  'FAIL_EXPRESSION_DRIFT',
  'FAIL_LOCKED_ASSET_MUTATION',
  'FAIL_UNAUTHORIZED_REOPEN',
  'FAIL_AUTO_REGENERATION_AFTER_APPROVAL',
  'FAIL_CLIENT_FEEDBACK_AUTO_GENERATION',
  'FAIL_CAMPAIGN_BOARD_AS_SPREADSHEET',
  'FAIL_FORCED_EQUAL_SEQUENCE_LENGTH',
  'FAIL_FILLER_SLIDE_GENERATION',
  'FAIL_PUBLISHING_STATE_COLLAPSED_WITH_PRODUCTION_STATE',
] as const;

export const BOARD_VIEW_MODES = [
  'CAMPAIGN_WALL',
  'ROUND_VIEW',
  'SEQUENCE_VIEW',
  'FEED_PREVIEW',
  'CONTENT_PLAN',
  'CLIENT_REVIEW',
] as const;

export const CONTINUITY_MODES = ['PRESERVE', 'EVOLVE', 'CONTRAST', 'INTRODUCE', 'REMOVE'] as const;

export const REFERENCE_CONDITIONING_ROLE = 'CONTINUITY_CALIBRATION' as const;

export const CAMPAIGN_PRODUCTION_BOARD_IMPLEMENTED = true as const;
export const HORIZONTAL_SEQUENCE_PRODUCTION_IMPLEMENTED = true as const;
export const VERTICAL_COHERENCE_EVALUATION_IMPLEMENTED = true as const;
export const HORIZONTAL_COHERENCE_EVALUATION_IMPLEMENTED = true as const;
export const CAMPAIGN_RHYTHM_EVALUATION_IMPLEMENTED = true as const;
export const PRODUCTION_ROUND_MODEL_IMPLEMENTED = true as const;
export const LOCKED_ASSET_PROTECTION_IMPLEMENTED = true as const;
export const SEQUENCE_POSITION_CONTRACT_IMPLEMENTED = true as const;
export const SLIDE_02_METHODOLOGY_IMPLEMENTED = true as const;
export const SLIDE_02_SWIPE_REWARD_REQUIRED = true as const;
export const CLIENT_MARKETING_APPROVAL_ARCHITECTURE_IMPLEMENTED = true as const;
export const CLIENT_REVIEW_MODE_IMPLEMENTED = true as const;
export const CAMPAIGN_APPROVAL_SNAPSHOT_IMPLEMENTED = true as const;
export const GENERIC_STUDIO_WORLD_MARKETING_WORKFLOW_IMPLEMENTED = true as const;
