/**
 * P0.5E.7 — Character-first content operations constants.
 */

export const NDX_CONTENT_SEED_SOURCE_TYPES = [
  'LIVE_WORLD_SIGNAL',
  'PERSONAL_EXPERIENCE',
  'AUDIENCE_SUBMISSION',
  'AUDIENCE_QUESTION',
  'SAVED_ITEM',
  'CULTURAL_MOMENT',
  'DATA_POINT',
  'HISTORICAL_CALLBACK',
  'BRAND_MEMORY',
  'FOUNDER_PROVIDED',
  'NDX_SELF_OBSERVATION',
  'BOOKMARK_CALLBACK',
  'DOG_EAR_FOLLOWUP',
  'ERRATA',
  'RABBIT_HOLE',
] as const;

export const NDX_THOUGHT_ARC_BEATS = [
  'NOTICE',
  'REACT',
  'ASSUME',
  'QUESTION',
  'INVESTIGATE',
  'CONNECT',
  'TEST',
  'REVISE_OR_CONFIRM',
  'DOCUMENT',
] as const;

export const BELIEF_REVISION_STATES = [
  'UNCHANGED',
  'STRENGTHENED',
  'SOFTENED',
  'REVERSED',
  'PARTIALLY_REVISED',
  'UNRESOLVED',
] as const;

export const NDX_KNOWLEDGE_STATES = [
  'KNOWS',
  'THINKS',
  'SUSPECTS',
  'TESTING',
  'LEARNS',
  'CHANGED_MIND',
  'DOES_NOT_KNOW_YET',
] as const;

export const CHARACTER_BEAT_CONTRACTS = [
  'THAT_CANNOT_BE_RIGHT',
  'I_WAS_WRONG',
  'I_HAVE_A_THEORY',
  'BE_SERIOUS',
  'REMEMBER_THIS',
  'INTERESTING_FAIR',
  'WE_OWE_HER_AN_APOLOGY',
  'WAIT',
  'NO_BECAUSE',
  'LOOK_AT_THIS',
  'QUIET_OBSERVATION',
  'UNRESOLVED',
] as const;

export const HUMOR_OPPORTUNITY_LEVELS = ['NONE', 'SUBTLE', 'MODERATE', 'STRONG'] as const;

export const BOOK_TRACE_TYPES = [
  'NEW_PAGE',
  'BOOKMARK',
  'DOG_EAR',
  'ERRATA',
  'FLIP_BACK',
  'MARGIN_TRACE',
  'INDEX_ENTRY',
  'CHAPTER_ENTRY',
] as const;

export const PAGE_NARRATIVE_ROLES = [
  'HOOK',
  'INITIAL_ASSUMPTION',
  'WHAT_I_MISSED',
  'EVIDENCE',
  'CONTRADICTION',
  'WHY_IT_MATTERS',
  'WHAT_I_THINK_NOW',
  'WHAT_I_AM_DOING_DIFFERENTLY',
  'BOOKMARK_CLOSING_TRACE',
] as const;

export const CONTENT_SURFACE_TYPES = [
  'PAGE',
  'MARGIN',
  'BOOK_IN_MOTION',
  'REEL',
  'STORY',
  'TIKTOK',
  'THREAD',
  'DOG_EAR',
  'ERRATA',
  'FLIP_BACK',
  'ADD_TO_BOOK',
] as const;

export const TOPIC_MIGRATION_STATUSES = [
  'NEEDS_CHARACTER_REFORMULATION',
  'REFORMULATED',
  'FOUNDER_APPROVED',
  'KEEP_AS_REFERENCE_ONLY',
  'RETIRE',
] as const;

export const FOUNDER_PREMISE_JUDGMENTS = [
  'YES_THAT_SOUNDS_LIKE_HER',
  'GOOD_TOPIC_WRONG_ANGLE',
  'TOO_EDUCATIONAL',
  'TOO_GENERIC',
  'TOO_THIRD_PERSON',
  'NOT_ENOUGH_NDX',
  'TOO_PERSONAL',
  'NEEDS_MORE_EVIDENCE',
  'GOOD_RABBIT_HOLE',
  'SAVE_FOR_LATER',
  'DOG_EAR_THIS',
  'BUILD_THE_PAGE',
] as const;

export const EXPERIENCE_MODES = [
  'PERSONALLY_EXPERIENCED',
  'OBSERVED',
  'AUDIENCE_TRIGGERED',
  'HYPOTHETICAL_SELF_INSERT',
  'CULTURAL_OBSERVATION',
  'RESEARCH_REACTION',
] as const;

export const CHARACTER_FIRST_CONTENT_VERSION = 'P0.5E.7' as const;

export const CREDIT_UTILIZATION_GOLDEN_PILOT_ID = 'golden-pilot-credit-utilization' as const;
