/**
 * P0.5E.7 — Character-first content operations constants.
 */

export const NDX_CONTENT_SEED_SOURCE_TYPES = [
  'LIVE_WORLD_SIGNAL',
  'PERSONAL_EXPERIENCE',
  'AUDIENCE_SUBMISSION',
  'AUDIENCE_QUESTION',
  'SAVED_ITEM',
  'CULTURAL_MOMENT',
  'DATA_POINT',
  'HISTORICAL_CALLBACK',
  'BRAND_MEMORY',
  'FOUNDER_PROVIDED',
  'NDX_SELF_OBSERVATION',
  'BOOKMARK_CALLBACK',
  'DOG_EAR_FOLLOWUP',
  'ERRATA',
  'RABBIT_HOLE',
] as const;

export const NDX_THOUGHT_ARC_BEATS = [
  'NOTICE',
  'REACT',
  'ASSUME',
  'QUESTION',
  'INVESTIGATE',
  'CONNECT',
  'TEST',
  'REVISE_OR_CONFIRM',
  'DOCUMENT',
] as const;

export const BELIEF_REVISION_STATES = [
  'UNCHANGED',
  'STRENGTHENED',
  'SOFTENED',
  'REVERSED',
  'PARTIALLY_REVISED',
  'UNRESOLVED',
] as const;

export const NDX_KNOWLEDGE_STATES = [
  'KNOWS',
  'THINKS',
  'SUSPECTS',
  'TESTING',
  'LEARNS',
  'CHANGED_MIND',
  'DOES_NOT_KNOW_YET',
] as const;

export const CHARACTER_BEAT_CONTRACTS = [
  'THAT_CANNOT_BE_RIGHT',
  'I_WAS_WRONG',
  'I_HAVE_A_THEORY',
  'BE_SERIOUS',
  'REMEMBER_THIS',
  'INTERESTING_FAIR',
  'WE_OWE_HER_AN_APOLOGY',
  'WAIT',
  'NO_BECAUSE',
  'LOOK_AT_THIS',
  'QUIET_OBSERVATION',
  'UNRESOLVED',
] as const;

export const HUMOR_OPPORTUNITY_LEVELS = ['NONE', 'SUBTLE', 'MODERATE', 'STRONG'] as const;

export const BOOK_TRACE_TYPES = [
  'NEW_PAGE',
  'BOOKMARK',
  'DOG_EAR',
  'ERRATA',
  'FLIP_BACK',
  'MARGIN_TRACE',
  'INDEX_ENTRY',
  'CHAPTER_ENTRY',
] as const;

export const PAGE_NARRATIVE_ROLES = [
  'HOOK',
  'INITIAL_ASSUMPTION',
  'WHAT_I_MISSED',
  'EVIDENCE',
  'CONTRADICTION',
  'WHY_IT_MATTERS',
  'WHAT_I_THINK_NOW',
  'WHAT_I_AM_DOING_DIFFERENTLY',
  'BOOKMARK_CLOSING_TRACE',
] as const;

export const CONTENT_SURFACE_TYPES = [
  'PAGE',
  'MARGIN',
  'BOOK_IN_MOTION',
  'REEL',
  'STORY',
  'TIKTOK',
  'THREAD',
  'DOG_EAR',
  'ERRATA',
  'FLIP_BACK',
  'ADD_TO_BOOK',
] as const;

export const TOPIC_MIGRATION_STATUSES = [
  'NEEDS_CHARACTER_REFORMULATION',
  'REFORMULATED',
  'FOUNDER_APPROVED',
  'KEEP_AS_REFERENCE_ONLY',
  'RETIRE',
] as const;

export const FOUNDER_PREMISE_JUDGMENTS = [
  'YES_THAT_SOUNDS_LIKE_HER',
  'GOOD_TOPIC_WRONG_ANGLE',
  'TOO_EDUCATIONAL',
  'TOO_GENERIC',
  'TOO_THIRD_PERSON',
  'NOT_ENOUGH_NDX',
  'TOO_PERSONAL',
  'NEEDS_MORE_EVIDENCE',
  'GOOD_RABBIT_HOLE',
  'SAVE_FOR_LATER',
  'DOG_EAR_THIS',
  'BUILD_THE_PAGE',
] as const;

export const EXPERIENCE_MODES = [
  'PERSONALLY_EXPERIENCED',
  'OBSERVED',
  'AUDIENCE_TRIGGERED',
  'HYPOTHETICAL_SELF_INSERT',
  'CULTURAL_OBSERVATION',
  'RESEARCH_REACTION',
] as const;

export const CHARACTER_FIRST_CONTENT_VERSION = 'P0.5E.7' as const;
export const CHARACTER_FIRST_REGENERATION_VERSION = 'P0.5E.7A' as const;

export const CREDIT_UTILIZATION_GOLDEN_PILOT_ID = 'golden-pilot-credit-utilization' as const;

/** P0.5E.7A — Hero slide 01 narrative role types */
export const HERO_SLIDE_ROLE_TYPES = [
  'INCITING_INCIDENT',
  'PERSONAL_CONTRADICTION',
  'CONFESSION',
  'QUESTION',
  'MISTAKEN_ASSUMPTION',
  'REACTION',
  'OBSERVATION',
  'CALLBACK',
  'CORRECTION',
] as const;

/** Prohibited default Slide 01 roles for character-first knowledge posts */
export const PROHIBITED_HERO_SLIDE_ROLES = [
  'DEFINITION',
  'TOPIC_LABEL',
  'GENERAL_EXPLAINER',
  'CHEAT_SHEET',
  'LIST_INTRO',
] as const;

/** P0.5E.7A — explicit narrative page role map roles */
export const NDX_PAGE_ROLE_MAP_ROLES = [
  'PERSONAL_CONTRADICTION',
  'INITIAL_ASSUMPTION',
  'WHAT_I_MISSED',
  'SYSTEM_LOGIC',
  'TIMING_COMPLICATION',
  'BELIEF_REVISION',
  'BEHAVIOR_CHANGE',
  'BOOKMARK',
  'INCITING_INCIDENT',
  'DISCOVERY',
  'COMPLICATION',
  'EVIDENCE',
  'CONTRADICTION',
  'OBSERVATION',
  'CALLBACK',
  'CORRECTION',
] as const;

export const CHARACTER_AUTHORITY_MIGRATION_STATUSES = [
  'CHARACTER_AUTHORITY_READY',
  'NEEDS_PREMISE',
  'NEEDS_THOUGHT_ARC',
  'NEEDS_PAGE_ROLE_MAP',
  'READY_TO_REGENERATE',
] as const;

export const CHARACTER_FIRST_REGENERATION_FAILURES = [
  'FAIL_TOPIC_WITHOUT_CHARACTER_ENTRY',
  'FAIL_REVISION_NOT_VISIBLE',
  'FAIL_GENERIC_EDUCATIONAL_COLLAPSE',
  'FAIL_CHARACTER_NOT_CAUSAL',
  'FAIL_HERO_CAUSALITY',
  'FAIL_HERO_PREMISE_DRIFT',
  'FAIL_TOPIC_ONLY_REGENERATION',
] as const;

export const CHARACTER_VISUAL_PARTICIPATION_LEVELS = [
  'NONE',
  'OPTIONAL',
  'RECOMMENDED',
  'STRONGLY_RECOMMENDED',
] as const;

export const FOUNDER_HERO_LOCK_FIELDS = [
  'LOCK_HERO_PREMISE',
  'LOCK_HERO_COPY',
  'LOCK_HERO_PHOTO',
  'LOCK_HERO_COMPOSITION_INTENT',
] as const;

export const FOUNDER_CAUSALITY_JUDGMENTS = [
  'YES_THATS_THE_POST',
  'GOOD_TOPIC_WRONG_NDX_ANGLE',
  'TOO_EDUCATIONAL',
  'NOT_PERSONAL_ENOUGH',
  'FAKE_PERSONALITY',
  'WRONG_ASSUMPTION',
  'WRONG_REVISION',
  'READY_TO_GENERATE',
] as const;

export const CHARACTER_FIRST_CREDIT_UTILIZATION_NORTH_STAR_ID =
  'CHARACTER_FIRST_CREDIT_UTILIZATION_VISUAL_NORTH_STAR' as const;

export const NEGATIVE_CHARACTER_COLLAPSE_EVIDENCE_ID =
  'NEGATIVE_CHARACTER_COLLAPSE_EVIDENCE' as const;
