/**
 * P0.5E.7A — Page role semantic contracts.
 */

import type { NdxPageRoleMapRole, PageRoleSemanticContract } from './types.js';

const BASE: Record<NdxPageRoleMapRole, PageRoleSemanticContract> = {
  PERSONAL_CONTRADICTION: {
    role: 'PERSONAL_CONTRADICTION',
    narrativePurpose: 'Establish NDX personal contradiction — why she is making this page',
    knowledgeState: 'THINKS',
    characterState: 'confused / contradicted',
    copyIntent: 'first-person inciting premise',
    evidenceIntent: 'attach proof of the contradiction',
    photoIntent: 'NDX reacting or reviewing evidence',
    bookArtifactIntent: 'torn notebook page beginning',
    annotationIntent: 'lime reaction to contradiction',
    allowedDensity: 'LOW',
    prohibitedBehavior: ['definition-only copy', 'topic label headline', 'generic explainer intro'],
    requiredBehavior: ['first-person causal framing', 'personal or observed entry'],
  },
  INITIAL_ASSUMPTION: {
    role: 'INITIAL_ASSUMPTION',
    narrativePurpose: 'Show what NDX thought first',
    knowledgeState: 'THINKS',
    characterState: 'confident but incomplete',
    copyIntent: 'I THOUGHT / I ASSUMED',
    evidenceIntent: 'support the assumption she held',
    photoIntent: 'optional — NDX writing initial theory',
    bookArtifactIntent: 'margin note or underline',
    annotationIntent: 'circle what she missed',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['neutral textbook definition as primary copy'],
    requiredBehavior: ['explicit initial belief'],
  },
  WHAT_I_MISSED: {
    role: 'WHAT_I_MISSED',
    narrativePurpose: 'Reveal the gap in her initial model',
    knowledgeState: 'LEARNS',
    characterState: 'investigating',
    copyIntent: 'HERE IS WHAT I MISSED',
    evidenceIntent: 'missing variable evidence',
    photoIntent: 'NDX searching / comparing',
    bookArtifactIntent: 'insert or attached scrap',
    annotationIntent: 'arrow to missed detail',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['checklist without character framing'],
    requiredBehavior: ['connect miss to her prior assumption'],
  },
  SYSTEM_LOGIC: {
    role: 'SYSTEM_LOGIC',
    narrativePurpose: 'Explain system logic because NDX is figuring out what happened',
    knowledgeState: 'LEARNS',
    characterState: 'connecting dots',
    copyIntent: 'explanation subordinated to investigation',
    evidenceIntent: 'formula / ratio / rule as evidence',
    photoIntent: 'optional',
    bookArtifactIntent: 'annotated diagram on page',
    annotationIntent: 'connect evidence to premise',
    allowedDensity: 'HIGH',
    prohibitedBehavior: ['standalone lecture with no character frame'],
    requiredBehavior: ['educational value preserved but subordinated'],
  },
  TIMING_COMPLICATION: {
    role: 'TIMING_COMPLICATION',
    narrativePurpose: 'Introduce timing/reporting complication',
    knowledgeState: 'LEARNS',
    characterState: 'complication discovered',
    copyIntent: 'WAIT — TIMING MATTERS TOO',
    evidenceIntent: 'statement close / reporting date evidence',
    photoIntent: 'optional',
    bookArtifactIntent: 'date annotation',
    annotationIntent: 'highlight timing mismatch',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['generic finance tip list'],
    requiredBehavior: ['complication tied to her investigation'],
  },
  BELIEF_REVISION: {
    role: 'BELIEF_REVISION',
    narrativePurpose: 'Show what changed in NDX understanding',
    knowledgeState: 'CHANGED_MIND',
    characterState: 'revised conclusion',
    copyIntent: 'before vs after thinking',
    evidenceIntent: 'contrast prior vs current model',
    photoIntent: 'recommended — NDX reconsidering',
    bookArtifactIntent: 'cross-out or revision mark',
    annotationIntent: 'strike-through prior assumption',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['neutral definition-only copy', 'revision invisible'],
    requiredBehavior: ['explicit revised conclusion', 'visible belief change', 'visible revision'],
  },
  BEHAVIOR_CHANGE: {
    role: 'BEHAVIOR_CHANGE',
    narrativePurpose: 'What NDX does differently now',
    knowledgeState: 'KNOWS',
    characterState: 'acting on revision',
    copyIntent: 'WHAT I AM DOING NOW',
    evidenceIntent: 'behavioral checklist as personal action',
    photoIntent: 'optional',
    bookArtifactIntent: 'action note',
    annotationIntent: 'checklist in her handwriting',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['generic advice detached from her story'],
    requiredBehavior: ['behavior tied to revision'],
  },
  BOOKMARK: {
    role: 'BOOKMARK',
    narrativePurpose: 'Book trace — save for later reference',
    knowledgeState: 'KNOWS',
    characterState: 'documenting',
    copyIntent: 'BOOKMARK THIS',
    evidenceIntent: 'minimal — closure artifact',
    photoIntent: 'none',
    bookArtifactIntent: 'dog-ear / bookmark tab',
    annotationIntent: 'bookmark mark',
    allowedDensity: 'LOW',
    prohibitedBehavior: ['new educational content', 'CTA spam'],
    requiredBehavior: ['book trace closure'],
  },
  INCITING_INCIDENT: {
    role: 'INCITING_INCIDENT',
    narrativePurpose: 'What happened to trigger the page',
    knowledgeState: 'THINKS',
    characterState: 'triggered',
    copyIntent: 'what happened first-person',
    evidenceIntent: 'incident proof',
    photoIntent: 'recommended',
    bookArtifactIntent: 'first page of sequence',
    annotationIntent: 'reaction mark',
    allowedDensity: 'LOW',
    prohibitedBehavior: ['topic label'],
    requiredBehavior: ['inciting event'],
  },
  DISCOVERY: {
    role: 'DISCOVERY',
    narrativePurpose: 'What NDX discovered during investigation',
    knowledgeState: 'LEARNS',
    characterState: 'discovery moment',
    copyIntent: 'I FOUND / I NOTICED',
    evidenceIntent: 'discovery evidence',
    photoIntent: 'optional',
    bookArtifactIntent: 'highlighted find',
    annotationIntent: 'discovery circle',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['detached explainer'],
    requiredBehavior: ['discovery framed as hers'],
  },
  COMPLICATION: {
    role: 'COMPLICATION',
    narrativePurpose: 'Complication that challenges simple answer',
    knowledgeState: 'LEARNS',
    characterState: 'complication',
    copyIntent: 'BUT WAIT',
    evidenceIntent: 'complicating evidence',
    photoIntent: 'optional',
    bookArtifactIntent: 'insert',
    annotationIntent: 'complication arrow',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['topic pivot'],
    requiredBehavior: ['complication in arc'],
  },
  EVIDENCE: {
    role: 'EVIDENCE',
    narrativePurpose: 'Evidence supporting investigation',
    knowledgeState: 'LEARNS',
    characterState: 'examining proof',
    copyIntent: 'proof with character frame',
    evidenceIntent: 'primary evidence object',
    photoIntent: 'optional',
    bookArtifactIntent: 'attached evidence',
    annotationIntent: 'evidence callout',
    allowedDensity: 'HIGH',
    prohibitedBehavior: ['evidence without narrative purpose'],
    requiredBehavior: ['evidence serves thought arc'],
  },
  CONTRADICTION: {
    role: 'CONTRADICTION',
    narrativePurpose: 'Contradiction that forces revision',
    knowledgeState: 'TESTING',
    characterState: 'contradicted',
    copyIntent: 'THIS CANNOT BE RIGHT',
    evidenceIntent: 'contradicting proof',
    photoIntent: 'recommended',
    bookArtifactIntent: 'conflict annotation',
    annotationIntent: 'contradiction highlight',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['ignore contradiction'],
    requiredBehavior: ['visible contradiction'],
  },
  OBSERVATION: {
    role: 'OBSERVATION',
    narrativePurpose: 'First-person observation without fabricated autobiography',
    knowledgeState: 'SUSPECTS',
    characterState: 'observing pattern',
    copyIntent: 'I KEEP SEEING / I STARTED LOOKING AT',
    evidenceIntent: 'pattern evidence',
    photoIntent: 'optional',
    bookArtifactIntent: 'observation note',
    annotationIntent: 'pattern mark',
    allowedDensity: 'LOW',
    prohibitedBehavior: ['fabricated personal events'],
    requiredBehavior: ['observation voice when not personally experienced'],
  },
  CALLBACK: {
    role: 'CALLBACK',
    narrativePurpose: 'Callback to prior book memory',
    knowledgeState: 'KNOWS',
    characterState: 'remembering',
    copyIntent: 'REMEMBER THIS / I SAID THIS BEFORE',
    evidenceIntent: 'prior page reference',
    photoIntent: 'optional',
    bookArtifactIntent: 'flip-back reference',
    annotationIntent: 'callback arrow',
    allowedDensity: 'LOW',
    prohibitedBehavior: ['standalone topic reintroduction'],
    requiredBehavior: ['book continuity'],
  },
  CORRECTION: {
    role: 'CORRECTION',
    narrativePurpose: 'Errata or self-correction',
    knowledgeState: 'CHANGED_MIND',
    characterState: 'correcting prior take',
    copyIntent: 'I WAS WRONG ABOUT',
    evidenceIntent: 'correction evidence',
    photoIntent: 'optional',
    bookArtifactIntent: 'errata slip',
    annotationIntent: 'correction mark',
    allowedDensity: 'MEDIUM',
    prohibitedBehavior: ['silent revision'],
    requiredBehavior: ['explicit correction'],
  },
};

export function getPageRoleSemanticContract(role: NdxPageRoleMapRole): PageRoleSemanticContract {
  return BASE[role];
}

export function pageRoleProhibitsGenericExplainer(role: NdxPageRoleMapRole): boolean {
  const contract = BASE[role];
  return contract.prohibitedBehavior.some(
    (b) => b.includes('definition') || b.includes('explainer') || b.includes('topic label'),
  );
}
