export const P0_VR_TWIN_V26_BUILD = 'v377' as const;

export const IR_SCHEMA_VERSION = 'twin-v2-ir-1' as const;

export const HOST_CONTRACT_VERSION = 'site00-host-shell-v1' as const;
export const RESPONSIVE_CONTRACT_VERSION = 'mobile-375-v1' as const;
export const STATE_CONTRACT_VERSION = 'ndx-overview-states-v1' as const;

export const INVENTION_BUDGET_BY_STAGE = {
  CREATIVE_DIRECTION: 'CONTROLLED',
  COMPOSITION_PLAN: 'CONTROLLED',
  VISUAL_GENERATION: 'CONTROLLED',
  RECONCILIATION: 'MICRO',
  BLUEPRINT_TO_CODE: 'NONE',
  FUNCTION_BINDING: 'NONE',
  FIDELITY_CORRECTION: 'MICRO',
  PROMOTION: 'NONE',
} as const;

export const FAILURE_TAXONOMY = [
  'IR_CHAIN_BROKEN',
  'BUNDLE_VERSION_MISMATCH',
  'AUTHORITY_CONFLICT',
  'TRANSLATION_INVENTION_VIOLATION',
  'SILENT_FALLBACK_ATTEMPTED',
  'OBJECT_LINEAGE_BROKEN',
  'TYPOGRAPHY_FIDELITY_FAILED',
  'ASSET_IDENTITY_MISMATCH',
  'ASSET_TRANSPARENCY_FAILED',
  'BAKED_TEXT_CONFLICT',
  'RESPONSIVE_CONTRACT_MISSING',
  'UNKNOWN_RENDERED_AS_ZERO',
  'STATE_VISUAL_UNDEFINED',
  'INTERACTION_GEOMETRY_FAILED',
  'OWNERSHIP_VIOLATION',
  'GENERATION_PROVIDER_CHANGED',
  'PREFLIGHT_FAILED',
  'REFINEMENT_SCOPE_VIOLATION',
  'STALE_REVIEW',
  'COMPILER_NOT_READY',
  'PRIMITIVE_CONTRACT_VIOLATION',
  'DEBUG_CONTENT_LEAK',
] as const;
