/** P0.5E.4F — Canonical character visual identity gate + injection authority */

export const CHARACTER_AUTHORITY_VERSION = 'CHARACTER_AUTHORITY@P0.5E.4F' as const;

export const NDX_CHARACTER_ID = 'ndx' as const;
export const NDX_VISUAL_VERSION_PREFIX = 'NDX_VISUAL' as const;

export const VISUAL_IDENTITY_READINESS_STATUSES = [
  'NOT_STARTED',
  'IN_DISCOVERY',
  'REFERENCE_SELECTED',
  'ANCHOR_PENDING',
  'ANCHOR_APPROVED',
  'PACK_INCOMPLETE',
  'QA_BLOCKED',
  'READY',
] as const;

export const PRODUCTION_READINESS_STATUSES = [
  'BLOCKED_CHARACTER_IDENTITY',
  'BLOCKED_REFERENCE_PACK',
  'BLOCKED_STILL_CONTINUITY',
  'BLOCKED_VIDEO_CONTINUITY',
  'READY_FOR_STILL_PRODUCTION',
  'READY_FOR_MOTION_PRODUCTION',
] as const;

export const CHARACTER_VARIATION_MODES = [
  'LOCKED',
  'ALLOWED_TO_VARY',
  'SCENE_DEPENDENT',
  'FOUNDER_APPROVAL_REQUIRED',
] as const;

export const PRE_CANON_ASSET_CLASSIFICATIONS = [
  'CANONICAL_REFERENCE_CANDIDATE',
  'HISTORICAL_EXPLORATION',
  'PRE_CANON_CHARACTER_PLACEHOLDER',
  'FOUNDER_VISUAL_REFERENCE',
  'NEGATIVE_IDENTITY_EVIDENCE',
] as const;

export const CHARACTER_AUTHORITY_FAILURE_CODES = [
  'FAIL_CHARACTER_VISUAL_IDENTITY_NOT_READY',
  'FAIL_CHARACTER_PRODUCTION_NOT_READY',
  'FAIL_CHARACTER_REFERENCE_PACK_MISSING',
  'FAIL_PRECANON_CHARACTER_CONTAMINATION',
  'FAIL_STALE_CHARACTER_VERSION',
  'FAIL_UNAUTHORIZED_CHARACTER_INJECTION',
] as const;

export const CHARACTER_PLACEHOLDER_LABEL = 'NDX VISUAL IDENTITY PENDING' as const;

export const CHARACTER_BLOCKER_MESSAGE =
  "NDX's visual identity is not locked yet. Finish Character Casting / Reference Pack before generating NDX in production assets." as const;

export const CHARACTER_BLOCKER_HEADLINE = 'NDX CHARACTER REQUIRED' as const;

export const CHARACTER_BLOCKER_SUBHEAD =
  'THIS ASSET USES NDX VISUALLY. HER PRODUCTION IDENTITY IS STILL BEING LOCKED.' as const;

/** Surfaces that may depict NDX as a person — require character authority when generating photography. */
export const CHARACTER_AUTHORITY_SURFACES = [
  'CAROUSEL',
  'SLIDE',
  'STORY',
  'REEL',
  'FILM_SCENE',
  'CAMPAIGN_ARTWORK',
  'EDITORIAL_PHOTO',
  'FOUNDER_CREATIVE_RECONSTRUCTION',
  'REALISM_LAB',
  'MEET_NDX',
  'CREDIT_UTILIZATION',
  'MARKETING_EXPRESSION',
] as const;

/** Planning-only surfaces allowed before visual identity is ready. */
export const REFERENCE_ONLY_SURFACES = [
  'SCRIPT',
  'CAPTION',
  'STORYBOARD_STRUCTURE',
  'SHOT_LIST',
  'PAGE_COPY',
  'CONTENT_SEED',
  'PAGE_ROLE',
  'SEQUENCE_PLAN',
  'CAMPAIGN_SCHEDULE',
  'PLACEHOLDER_LAYOUT',
  'VISUAL_REFERENCE_DISCUSSION',
] as const;
