export const P0_VR_TWIN_V30R8M2R3_LINEAGE = 'P0.VR.TWINV3.0R8M2R3' as const;
export const MOBILE_TWIN_IMPL_COMPILER_GENERATION_R8M2R3 = 'R8M2R3' as const;
export const MOBILE_TWIN_IMPLEMENTATION_VERSION_TRANSLATION_REBUILD = 'mobile-twin-impl-v5-translation-rebuild' as const;

export const R8M2R2_CORRECTION_REQUIRED_REASON = 'TRANSLATION_NOT_MATERIALLY_APPLIED' as const;

export const STALE_RENDER_TREE_REUSE = 'STALE_RENDER_TREE_REUSE' as const;
export const TRANSLATION_REBUILD_NOT_MATERIAL = 'TRANSLATION_REBUILD_NOT_MATERIAL' as const;
export const PATCH_EXISTING_PROHIBITED = 'PATCH_EXISTING_PROHIBITED' as const;

export const TRANSLATION_DRIVEN_CSS_PREFIX = 'site00-twin-td' as const;

export const CRITICAL_TRANSLATION_REGIONS = [
  'HOST_SHELL',
  'PROJECT_CONTEXT',
  'HERO_WORKSPACE',
  'AUTHORITY_PANEL',
  'CANDIDATE_GALLERY',
  'DECISION_BAR',
  'STRUCTURED_OUTPUT',
  'READINESS',
  'CONCEPT_DATA_HISTORY',
  'BOTTOM_NAV',
] as const;
