/**
 * B5.9R10 — Client simulation failure classes.
 */

export const CLIENT_SIMULATION_FAILURE_CLASSES = [
  'CLIENT_SIMULATION_NO_CONTEXT',
  'CLIENT_SELECTOR_SEARCH_FAILED',
  'CLIENT_SELECTOR_PROJECT_SEARCH_FAILED',
  'CLIENT_FIXTURE_MISSING',
  'CLIENT_MEMBERSHIP_MISSING',
  'CLIENT_MEMBERSHIP_SPECIAL_CASED',
  'CLIENT_PROJECT_COUNT_MISMATCH',
  'CLIENT_UNAUTHORIZED_PROJECT_VISIBLE',
  'CLIENT_SITE00_LEAK',
  'CLIENT_MODULE_PERMISSION_LEAK',
  'CLIENT_FIREWALL_LEAK',
  'CLIENT_SELECTOR_LAYOUT_SHIFT',
  'CLIENT_CONTEXT_STALE',
] as const;

export type ClientSimulationFailureClass = (typeof CLIENT_SIMULATION_FAILURE_CLASSES)[number];
