export const P0_VR_TWIN_V29_BUILD = 'v384' as const;

export const GENERATION_BUNDLE_OUTPUT_TYPES = [
  'AUTHORITY_VISUAL',
  'BLUEPRINT_TWIN_VISUAL',
  'SURGICAL_BLUEPRINT_DATA',
  'ASSET_GENERATION_CONTRACT_SET',
  'STANDALONE_ASSET_RENDER',
  'FUNCTION_BINDING_MAP',
] as const;

export const GENERATION_BUNDLE_STATUSES = [
  'PLANNING',
  'GENERATING',
  'PARTIAL',
  'VALIDATING',
  'RECONCILING',
  'READY_FOR_REGISTRATION',
  'REGISTERED',
  'FOUNDER_REVIEW',
  'APPROVED',
  'FAILED',
] as const;

export const ATOMIC_GENERATION_CLASSIFICATIONS = [
  'ATOMIC_CREATIVE_GENERATION_PROVEN',
  'ATOMIC_CREATIVE_GENERATION_PARTIAL',
  'ATOMIC_CREATIVE_GENERATION_BLOCKED',
] as const;

export const ATOMIC_FAILURE_CODES = [
  'ATOMIC_GENERATION_BLOCKED_BY_PROVIDER_CAPABILITY',
  'INCOMPLETE_TWIN_GENERATION',
  'INCOMPLETE_ASSET_GENERATION',
  'INCOMPLETE_BLUEPRINT_DATA',
  'INCOMPLETE_FUNCTION_MAP',
  'ATOMIC_TWIN_OBJECT_MISMATCH',
  'ATOMIC_BLUEPRINT_VISUAL_MISMATCH',
] as const;

export const ATOMIC_PIPELINE_CALL_ORDER = [
  'PAGE_INTENT',
  'FUNCTION_REQUIREMENTS',
  'BRAND_WORLD_CONTEXT',
  'CREATIVE_DIRECTION',
  'ConceptCompositionState',
  'ATOMIC_GENERATION_BUNDLE_OPEN',
  'SIBLING_AUTHORITY_VISUAL',
  'SIBLING_BLUEPRINT_TWIN_VISUAL',
  'SIBLING_SURGICAL_BLUEPRINT_DATA',
  'SIBLING_ASSET_GENERATION_CONTRACTS',
  'SIBLING_STANDALONE_ASSET_RENDERS',
  'SIBLING_FUNCTION_BINDING_MAP',
  'MULTI_WAY_RECONCILIATION',
  'GENERATION_BUNDLE_COMPLETENESS',
  'OBJECT_CONSISTENCY',
  'CANONICAL_REGISTRATION',
  'FOUNDER_REVIEW',
] as const;
