/** AUTO-GENERATED by scripts/icons/generateNdxV3SvgCanon.ts — do not edit */
import type { NDXIconName } from '../types.js';
export type V3AssetRegistryEntry = {
  iconName: NDXIconName;
  version: 'v3';
  sourcePath: string;
  publicPath: string;
  sourceHash: string;
  referenceId: string;
  filename: string;
  paths: string[];
  circles: Array<{ cx: number; cy: number; r: number; fill?: "currentColor" | "none" }>;
  strokeWidth: number;
};
export const NDX_V3_ASSET_REGISTRY: Record<string, V3AssetRegistryEntry> = {
  overview: {
    "iconName": "overview",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/overview.svg",
    "publicPath": "/icons/ndx/v3/overview.cde497fb.svg",
    "sourceHash": "sha256:cde497fbf7e745ddfc71769ae2f648e30fba543b4fa32685e6ae14d69c1795c0",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:overview",
    "filename": "overview.svg",
    "paths": [
      "M6 11.5 L12 5.5 L18 11.5 V19 H6 V11.5",
      "M10 14.25 H14 V19 H10 V14.25"
    ],
    "circles": [],
    "strokeWidth": 1.4
  },
  campaigns: {
    "iconName": "campaigns",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/campaigns.svg",
    "publicPath": "/icons/ndx/v3/campaigns.331051f1.svg",
    "sourceHash": "sha256:331051f1507a0c64bdfdf9a60e0a800ebdfc5e365abfcd5b47521cd64d6b432e",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:campaigns",
    "filename": "campaigns.svg",
    "paths": [
      "M5.25 10.25 H18.75 V18.75 H5.25 V10.25",
      "M5.25 10.25 L8.75 6.75 H15.25 L18.75 10.25",
      "M7.75 8 L9.25 9.5",
      "M10.25 7.5 L11.75 9",
      "M12.75 7.5 L14.25 9",
      "M8.75 13.25 H15.25"
    ],
    "circles": [],
    "strokeWidth": 1.4
  },
  content_ops: {
    "iconName": "content_ops",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/content-ops.svg",
    "publicPath": "/icons/ndx/v3/content-ops.a96082e3.svg",
    "sourceHash": "sha256:a96082e30b8e5e414e136425f444bcfa5950262b460da201e09023cb0dc7688d",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:content_ops",
    "filename": "content-ops.svg",
    "paths": [
      "M12 6 A6 6 0 1 1 12 18 A6 6 0 1 1 12 6"
    ],
    "circles": [
      {
        "cx": 12,
        "cy": 12,
        "r": 1.35,
        "fill": "currentColor"
      }
    ],
    "strokeWidth": 1.4
  },
  lab: {
    "iconName": "lab",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/lab.svg",
    "publicPath": "/icons/ndx/v3/lab.e03cb634.svg",
    "sourceHash": "sha256:e03cb63428206522401f378a09e91c39a7cbacf9d43e5ba4113f79997ebf2a03",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:lab",
    "filename": "lab.svg",
    "paths": [
      "M10 5 H14",
      "M10.5 5 V8.75 L7 18.5 H17 L13.5 8.75 V5",
      "M8 18.5 H16"
    ],
    "circles": [],
    "strokeWidth": 1.4
  },
  more: {
    "iconName": "more",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/more.svg",
    "publicPath": "/icons/ndx/v3/more.0b8786fa.svg",
    "sourceHash": "sha256:0b8786faa8737892acb6517e2d2a0be8c9ef2283322c0ac1c914d33303a4b412",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:more",
    "filename": "more.svg",
    "paths": [],
    "circles": [
      {
        "cx": 7.5,
        "cy": 12,
        "r": 1.4,
        "fill": "currentColor"
      },
      {
        "cx": 12,
        "cy": 12,
        "r": 1.4,
        "fill": "currentColor"
      },
      {
        "cx": 16.5,
        "cy": 12,
        "r": 1.4,
        "fill": "currentColor"
      }
    ],
    "strokeWidth": 1.4
  },
  notifications: {
    "iconName": "notifications",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/notifications.svg",
    "publicPath": "/icons/ndx/v3/notifications.7b1830d0.svg",
    "sourceHash": "sha256:7b1830d00523d4af4f5c87105b0426773c3da4b1aac6c2741d5acc9ef02fe47a",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:notifications",
    "filename": "notifications.svg",
    "paths": [
      "M12 5.25 C9.25 5.25 7.75 7.25 7.75 9.75 V12 L6.25 14.25 H17.75 L16.25 12 V9.75 C16.25 7.25 14.75 5.25 12 5.25"
    ],
    "circles": [
      {
        "cx": 12,
        "cy": 16.25,
        "r": 0.85,
        "fill": "currentColor"
      }
    ],
    "strokeWidth": 1.35
  },
  ellipsis: {
    "iconName": "ellipsis",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/project-menu.svg",
    "publicPath": "/icons/ndx/v3/project-menu.1be6acc7.svg",
    "sourceHash": "sha256:1be6acc7284ff16099da9cb10df0919aae407d31737a690d133d6e9f8c9dd016",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:ellipsis",
    "filename": "project-menu.svg",
    "paths": [
      "M12 5.5 A6.5 6.5 0 1 1 12 18.5 A6.5 6.5 0 1 1 12 5.5"
    ],
    "circles": [
      {
        "cx": 9,
        "cy": 12,
        "r": 1.15,
        "fill": "currentColor"
      },
      {
        "cx": 12,
        "cy": 12,
        "r": 1.15,
        "fill": "currentColor"
      },
      {
        "cx": 15,
        "cy": 12,
        "r": 1.15,
        "fill": "currentColor"
      }
    ],
    "strokeWidth": 1.35
  },
  project_overview: {
    "iconName": "project_overview",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/project-overview.svg",
    "publicPath": "/icons/ndx/v3/project-overview.f86ec459.svg",
    "sourceHash": "sha256:f86ec459956fe68c2971c70c5bb3bac22302d1bb3574bf4a57de63164839564c",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:project_overview",
    "filename": "project-overview.svg",
    "paths": [
      "M8.5 6.75 H16.25 V16.75 H8.5 V6.75",
      "M6.25 8.75 H14 V18.75 H6.25 V8.75",
      "M8.25 10.75 H12",
      "M8.25 12.75 H11.25"
    ],
    "circles": [],
    "strokeWidth": 1.4
  },
  project_settings: {
    "iconName": "project_settings",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/project-settings.svg",
    "publicPath": "/icons/ndx/v3/project-settings.7f850dd3.svg",
    "sourceHash": "sha256:7f850dd3e189bfe967252497da4a13d2bbf4761511abc0dc78f03c393314a349",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:project_settings",
    "filename": "project-settings.svg",
    "paths": [
      "M12 9.75 A2.25 2.25 0 1 0 12 14.25 A2.25 2.25 0 1 0 12 9.75",
      "M12 5.25 V6.75",
      "M12 17.25 V18.75",
      "M15.65 6.85 L16.55 5.95",
      "M8.35 17.15 L7.45 18.05",
      "M18.75 12 H17.25",
      "M6.75 12 H5.25",
      "M15.65 17.15 L16.55 18.05",
      "M8.35 6.85 L7.45 5.95",
      "M14.25 5.75 H16 V7.75 H14.25",
      "M8 5.75 H9.75 V7.75 H8",
      "M14.25 16.25 H16 V18.25 H14.25",
      "M8 16.25 H9.75 V18.25 H8"
    ],
    "circles": [],
    "strokeWidth": 1.35
  },
  back_to_projects: {
    "iconName": "back_to_projects",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/back-to-projects.svg",
    "publicPath": "/icons/ndx/v3/back-to-projects.3dc856d6.svg",
    "sourceHash": "sha256:3dc856d6355c61601d582451daf6def3dce6ffb7a65c93d4c9a973199551ec20",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:back_to_projects",
    "filename": "back-to-projects.svg",
    "paths": [
      "M8.5 6.25 V17.75",
      "M8.5 6.25 H17.25 V17.75 H8.5",
      "M4.75 12 H10.25",
      "M4.75 12 L7.25 9.5",
      "M4.75 12 L7.25 14.5"
    ],
    "circles": [],
    "strokeWidth": 1.4
  },
  return_to_origin: {
    "iconName": "return_to_origin",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/return-to-origin.svg",
    "publicPath": "/icons/ndx/v3/return-to-origin.baeeb1e4.svg",
    "sourceHash": "sha256:baeeb1e45dabc071147eec5b807064d8439aab04a304c396d97b9f077550eb8c",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:return_to_origin",
    "filename": "return-to-origin.svg",
    "paths": [
      "M12 5.75 A6.25 6.25 0 1 1 12 18.25 A6.25 6.25 0 1 1 12 5.75",
      "M9.25 14.75 A2.75 2.75 0 0 1 12 11.5"
    ],
    "circles": [
      {
        "cx": 15.25,
        "cy": 9.25,
        "r": 0.85,
        "fill": "currentColor"
      }
    ],
    "strokeWidth": 1.4
  },
  inspect: {
    "iconName": "inspect",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/inspect.svg",
    "publicPath": "/icons/ndx/v3/inspect.9e7dcae3.svg",
    "sourceHash": "sha256:9e7dcae3ea67a437fa1284a052d275674d9868ca8054ba151b60a9e28342b167",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:inspect",
    "filename": "inspect.svg",
    "paths": [
      "M9.25 9.25 A2.75 2.75 0 1 1 9.26 9.25",
      "M14.75 14.75 L18.75 18.75"
    ],
    "circles": [],
    "strokeWidth": 1.4
  },
  help: {
    "iconName": "help",
    "version": "v3",
    "sourcePath": "shared/site00-studio-world-ui/icons/ndx/v3/help.svg",
    "publicPath": "/icons/ndx/v3/help.d34286a2.svg",
    "sourceHash": "sha256:d34286a250ebf67589ed17cf8d9b92e1b1c9c4a87d3fd47533ece5602f10e3f9",
    "referenceId": "ndx-icon-reference-sheet-p0ui3d:help",
    "filename": "help.svg",
    "paths": [
      "M12 5.5 A6.5 6.5 0 1 1 12 18.5 A6.5 6.5 0 1 1 12 5.5",
      "M9.5 9.5 A2.25 2.25 0 1 1 13.75 9.5 C13.75 11.25 12 11.75 12 13.5",
      "M12 16.25 V16.35"
    ],
    "circles": [],
    "strokeWidth": 1.4
  },
};
