/**
 * P0.5E.3 — Generic Embodied Brand Character Discovery constants.
 */

export const EMBODIED_CHARACTER_DISCOVERY_VERSION = 'EMBODIED_CHARACTER_DISCOVERY@P0.5E.3' as const;

export const DISCOVERY_ROUNDS = [
  'WHO_IS_SHE',
  'HOW_DOES_SHE_THINK',
  'WHAT_MAKES_HER_HUMAN',
  'HOW_DOES_SHE_SOUND',
  'WHAT_DOES_SHE_NOTICE',
  'WHAT_DOES_SHE_GET_WRONG',
  'WHAT_MAKES_HER_LAUGH',
  'WHAT_IS_HER_LIFE_LIKE',
  'RELATIONSHIP_WITH_PRIMARY_ARTIFACT',
  'HOW_DOES_SHE_MOVE',
  'HOW_DOES_SHE_LOOK',
  'DOES_THIS_FEEL_LIKE_HER',
] as const;

export const VISUAL_AUTHORITY_LEVELS = ['NONE', 'TENDENCY_HYPOTHESIS', 'CASTING_CALIBRATION'] as const;

export const IDENTITY_AUTHORITY_LEVELS = ['NONE', 'PROVISIONAL', 'APPROVED'] as const;

export const CASTING_READINESS_STATES = [
  'NOT_READY',
  'CHARACTER_INSUFFICIENT',
  'FOUNDER_REVIEW_REQUIRED',
  'READY_FOR_CASTING_EXPLORATION',
  'FOUNDER_PROCEED_WITH_PARTIAL_EVIDENCE',
] as const;

export const FOUNDER_CHARACTER_JUDGMENTS = [
  'THATS_HER',
  'GETTING_CLOSE',
  'TOO_PERFECT',
  'TOO_COOL',
  'TOO_INFLUENCER',
  'TOO_BRANDY',
  'TOO_GENERIC',
  'TOO_SNARKY',
  'NOT_CULTURALLY_BELIEVABLE',
  'NEEDS_MORE_HUMANITY',
  'NEEDS_MORE_MESS',
  'NEEDS_MORE_WARMTH',
  'NEEDS_MORE_EDGE',
  'NEEDS_MORE_INTELLIGENCE',
  'NOT_HER',
] as const;

export const ARCHETYPE_COLLAPSE_FAILURES = [
  'FAIL_COOL_GIRL_ARCHETYPE',
  'FAIL_SASSY_WOMAN_ARCHETYPE',
  'FAIL_SMART_GIRL_COSTUME',
  'FAIL_INFLUENCER_HOST',
  'FAIL_BRAND_MASCOT',
  'FAIL_PERFECT_CHARACTER',
  'FAIL_ADJECTIVE_CHARACTER',
  'FAIL_FOUNDER_CLONE',
  'FAIL_DERIVATIVE_CHARACTER_CLONE',
  'FAIL_AI_PERSONALITY',
  'FAIL_ALWAYS_SNARKY',
  'FAIL_ALWAYS_UNBOTHERED',
  'FAIL_ALWAYS_CAMERA_READY',
  'FAIL_CULTURAL_REFERENCE_MACHINE',
] as const;

export const BEAUTY_ROLE_FAILURES = [
  'FAIL_INFLUENCER_COLLAPSE',
  'FAIL_FASHION_MODEL_AS_CHARACTER',
  'FAIL_SEXUALIZATION_AS_PERSONALITY',
  'FAIL_BEAUTY_AS_PRIMARY_REASON_TO_WATCH',
  'FAIL_PERMANENT_GLAM',
  'FAIL_PERMANENT_EDITORIAL_POSE',
] as const;

export const CAMERA_RELATIONSHIP_MODES = [
  'DIRECT_ADDRESS',
  'FRIEND_ON_FACETIME',
  'PASSIVE_OBSERVATION',
  'OVER_THE_SHOULDER',
  'SCREEN_DISCOVERY',
  'ROOM_OBSERVER',
  'PRIVATE_MOMENT',
  'PROCESS_DOCUMENTATION',
] as const;

export const EMBODIED_CHARACTER_DISCOVERY_IMPLEMENTED = true as const;
export const FINAL_CHARACTER_FACE_SELECTED = false as const;
export const FINAL_CHARACTER_VISUAL_IDENTITY_FINALIZED = false as const;
export const FINAL_CHARACTER_GENERATION_PERFORMED = false as const;
export const BRAND_CHARACTER_MUTATED = false as const;
export const BRAND_CANON_MUTATED = false as const;
export const PRODUCT_EXPRESSION_IMPLEMENTED = false as const;
export const WORLD_FORMATION_IMPLEMENTED = false as const;
