/**
 * P0.5E.1 — Generic daily publishing cadence + cross-platform derivation (brand-agnostic).
 */

export const DAILY_PUBLISHING_CADENCE_V1 = 'DAILY_PUBLISHING_CADENCE_V1' as const;

export const PUBLISHING_PLATFORMS = [
  'INSTAGRAM',
  'TIKTOK',
  'YOUTUBE',
  'THREADS',
  'OTHER',
] as const;

export const PUBLISHING_SURFACES = [
  'FEED',
  'STORY',
  'REEL',
  'SHORT',
  'TEXT',
] as const;

export const CADENCE_FULFILLMENT_STATES = [
  'FULLY_SUPPLIED',
  'PARTIALLY_SUPPLIED',
  'EVERGREEN_BACKFILL_AVAILABLE',
  'CALLBACK_BACKFILL_AVAILABLE',
  'RESEARCH_QUEUE_AVAILABLE',
  'FOUNDER_SEED_AVAILABLE',
  'NO_STRONG_OPPORTUNITY',
  'HOLD_SLOT_EMPTY',
] as const;

export const PRIMARY_EVENT_PLANNING_ROLES = [
  'EVENT_A_QUICK_CULTURAL',
  'EVENT_B_SUBSTANTIAL_INVESTIGATIVE',
  'EVENT_C_CALLBACK_REASSESSMENT',
] as const;

export const PRIMARY_EVENT_STATUSES = [
  'PLANNED',
  'INTELLIGENCE_DRAFT',
  'INTELLIGENCE_APPROVED',
  'IN_PRODUCTION',
  'COMPLETE',
  'ON_HOLD',
] as const;

export const CONTENT_INTELLIGENCE_STATUSES = [
  'DRAFT',
  'UNDER_REVIEW',
  'APPROVED',
  'FROZEN',
  'SUPERSEDED',
] as const;

export const PLATFORM_EXPRESSION_STATUSES = [
  'PLANNED',
  'NOT_RECOMMENDED',
  'FORMULATING',
  'READY',
  'UNDER_REVIEW',
  'APPROVED',
  'LOCKED',
  'PUBLISHED',
] as const;

export const SECOND_REEL_ELIGIBILITY = [
  'STRONG_OPPORTUNITY',
  'BREAKING_CULTURAL_SIGNAL',
  'CAMPAIGN_REQUIRED',
  'EVERGREEN_HIGH_VALUE',
  'FOUNDER_REQUESTED',
  'NOT_JUSTIFIED',
] as const;

export const REEL_PRODUCTION_COMPLEXITY = ['LOW', 'MEDIUM', 'HIGH', 'PREMIUM'] as const;

export const REEL_TYPE_BEHAVIORS = [
  'FAST_DISCOVERY',
  'CULTURAL_REACTION',
  'RABBIT_HOLE',
  'VISUAL_EVIDENCE',
  'VOICEOVER_ANALYSIS',
  'CALLBACK',
  'SELF_CORRECTION',
  'FIELD_OBSERVATION',
  'SCREEN_BEHAVIOR',
  'OBJECT_STORY',
  'TIMELINE',
  'CONNECTION_REVEAL',
] as const;

export const PLATFORM_ANGLE_DERIVATIONS = [
  'SAME_THESIS_DIFFERENT_HOOK',
  'SAME_THESIS_DIFFERENT_AUDIENCE_ENTRY',
  'SAME_THESIS_DIFFERENT_EVIDENCE_ORDER',
  'SAME_THESIS_DIFFERENT_EMOTIONAL_TEMPERATURE',
  'SAME_THESIS_DIFFERENT_FORMAT_LOGIC',
  'SAME_RESEARCH_DIFFERENT_QUESTION',
  'SAME_EVENT_DIFFERENT_CHARACTER_BEHAVIOR',
] as const;

export const CONTENT_PRIORITY_TIERS = [
  'TIER_1_BREAKING',
  'TIER_2_TODAY',
  'TIER_3_THIS_WEEK',
  'TIER_4_EVERGREEN',
  'TIER_5_ARCHIVE_HOLD',
] as const;

export const WATCH_QUEUE_STATES = [
  'WAIT_FOR_MORE_EVIDENCE',
  'WAIT_FOR_CURRENT_EVENT',
  'WAIT_FOR_CALLBACK',
  'WAIT_FOR_DATA',
  'WAIT_FOR_CULTURAL_MOMENT',
  'WAIT_FOR_FOUNDER',
] as const;

export const CONTENT_FATIGUE_LEVELS = ['LOW', 'MODERATE', 'HIGH', 'CRITICAL'] as const;

export const STORY_UNIT_PURPOSES = [
  'LIVE_REACTION',
  'AUDIENCE_QUESTION',
  'POLL',
  'RECEIPT',
  'BEHIND_THE_INVESTIGATION',
  'FOLLOW_UP',
  'UNRESOLVED_THOUGHT',
  'CALLBACK',
  'TEASER',
  'SOURCE_SHARE',
  'QUICK_CORRECTION',
  'FOUNDER_CHARACTER_MOMENT',
] as const;

export const STORY_ORIGIN_TYPES = ['PLANNED_STORY', 'SPONTANEOUS_STORY'] as const;

export const WEEKLY_BOARD_VIEW_MODES = [
  'WEEK_OVERVIEW',
  'PRIMARY_EVENTS',
  'FEED_ROUND',
  'STORY_CLUSTERS',
  'REEL_HOOKS',
  'REEL_SEQUENCES',
  'CROSS_PLATFORM_DERIVATIONS',
  'FINAL_WEEK',
  'PUBLISHING_HANDOFF',
] as const;

export const EXTENDED_CAMPAIGN_ROUND_TYPES = [
  'FEED_SLIDE_01',
  'FEED_SLIDE_02',
  'FEED_SLIDE_03',
  'STORY_CLUSTER',
  'REEL_HOOK',
  'REEL_STORYBOARD',
  'REEL_FINAL',
  'TIKTOK_HOOK',
  'TIKTOK_FINAL',
  'SHORTS_FINAL',
  'TEXT_EXPRESSION',
  'FINAL_DAY_REVIEW',
  'FINAL_WEEK_REVIEW',
] as const;

export const WEEKLY_APPROVAL_STAGES = [
  'WEEKLY_INTELLIGENCE_SLATE',
  'FEED_COVER_ROUND',
  'FEED_SLIDE_02_ROUND',
  'REEL_HOOK_ROUND',
  'REEL_DEVELOPMENT',
  'STORY_DAILY_CLUSTERS',
  'CROSS_PLATFORM_DERIVATIONS',
  'FINAL_WEEK_REVIEW',
] as const;

export const CADENCE_FAILURE_STATES = [
  'FAIL_CADENCE_AS_CONTENT_QUOTA',
  'FAIL_FILLER_CONTENT',
  'FAIL_THIRD_REEL_FORCED',
  'FAIL_TOO_MANY_UNIQUE_DAILY_PREMISES',
  'FAIL_NO_SHARED_CONTENT_INTELLIGENCE',
  'FAIL_CROSSPOST_COPY',
  'FAIL_PLATFORM_NATIVE_BEHAVIOR_MISSING',
  'FAIL_IG_ASSET_DUMP_TO_TIKTOK',
  'FAIL_IDENTICAL_HOOK_ACROSS_PLATFORMS',
  'FAIL_IDENTICAL_COPY_ACROSS_PLATFORMS',
  'FAIL_IDENTICAL_VISUAL_ACROSS_PLATFORMS',
  'FAIL_PLATFORM_DERIVATION_CHANGES_FACTS',
  'FAIL_DAILY_CHARACTER_RANGE_COLLAPSE',
  'FAIL_WEEKLY_CHARACTER_RANGE_COLLAPSE',
  'FAIL_FEED_OVERPRODUCTION',
  'FAIL_STORY_OVERPRODUCTION',
  'FAIL_REEL_OVERPRODUCTION',
  'FAIL_CONTENT_FATIGUE',
  'FAIL_RESEARCH_DUPLICATION',
  'FAIL_CAMPAIGN_BOARD_OVERWHELM',
  'FAIL_PLATFORM_EXPRESSION_DRIFT',
  'FAIL_CHARACTER_DRIFT',
  'FAIL_AUTONOMOUS_PUBLISHING_ENABLED',
] as const;

export const PLATFORM_NATIVE_FIT_DIMENSIONS = [
  'HOOK_NATIVE',
  'PACING_NATIVE',
  'FORMAT_NATIVE',
  'VISUAL_NATIVE',
  'INTERACTION_NATIVE',
  'TEXT_NATIVE',
  'AUDIO_NATIVE',
  'AUDIENCE_BEHAVIOR_NATIVE',
  'CHARACTER_PRESERVED',
  'CONTENT_THESIS_PRESERVED',
] as const;

export const NDX_DAILY_PUBLISHING_CADENCE_IMPLEMENTED = true as const;
export const GENERIC_PUBLISHING_CADENCE_POLICY_IMPLEMENTED = true as const;
export const PRIMARY_CONTENT_EVENT_MODEL_IMPLEMENTED = true as const;
export const CROSS_PLATFORM_CONTENT_INTELLIGENCE_IMPLEMENTED = true as const;
export const CROSS_PLATFORM_DERIVATION_POLICY_IMPLEMENTED = true as const;
export const REUSE_THINKING_NOT_POSTS_ENFORCED = true as const;
export const PLATFORM_CONTENT_EXPRESSION_IMPLEMENTED = true as const;
export const DAILY_CROSS_PLATFORM_CONTENT_MATRIX_IMPLEMENTED = true as const;
export const PLATFORM_NATIVE_FIT_EVALUATION_IMPLEMENTED = true as const;
export const CROSS_PLATFORM_CHARACTER_FIDELITY_IMPLEMENTED = true as const;
export const CROSS_PLATFORM_COPY_DUPLICATION_GUARD_IMPLEMENTED = true as const;
export const CROSS_PLATFORM_VISUAL_DUPLICATION_GUARD_IMPLEMENTED = true as const;
export const SHARED_RESEARCH_REUSE_IMPLEMENTED = true as const;
export const DAILY_EDITORIAL_HEALTH_IMPLEMENTED = true as const;
export const WEEKLY_EDITORIAL_HEALTH_HIGH_VOLUME_IMPLEMENTED = true as const;
export const CONTENT_FATIGUE_EVALUATION_IMPLEMENTED = true as const;
export const EVERGREEN_RESERVE_IMPLEMENTED = true as const;
export const WATCH_QUEUE_IMPLEMENTED = true as const;
export const RAPID_RESPONSE_POLICY_IMPLEMENTED = true as const;
export const WEEKLY_MARKETING_PRODUCTION_BOARD_IMPLEMENTED = true as const;
export const REEL_HOOK_ROUND_IMPLEMENTED = true as const;
export const STORY_CLUSTER_REVIEW_IMPLEMENTED = true as const;
export const CHANNEL_EXPRESSION_LEARNING_IMPLEMENTED = true as const;
export const AUTONOMOUS_PUBLISHING_ENABLED = false as const;
export const BRAND_CHARACTER_MUTATED = false as const;
export const BRAND_CANON_MUTATED = false as const;
export const PRODUCT_EXPRESSION_IMPLEMENTED = false as const;
export const WORLD_FORMATION_IMPLEMENTED = false as const;
