/**
 * DESIGN WORKSPACE — image-owned slot registry. Every `data-asset-slot` rendered by the workspace is generated by one
 * of these helpers, so the production manifest (ASSET_SLOTS.json) is derived, validated and never hand-maintained.
 * Slots are classified: ENVIRONMENT_IMAGE · CARD_IMAGE · FOREGROUND_IMAGE · TRANSPARENT_OBJECT · ICON3D · PROJECT_MARK.
 */
import type { DwsMode } from './dwsModel';
import { DWS_BRAND_ASSETS, DWS_ICON_SET_ITEMS, DWS_JOURNEYS, DWS_PROJECTS, DWS_SURFACES, DWS_SURFACE_FAMILIES, DWS_SURFACE_TABS, DWS_VARIANTS, DWS_COMPILER_INPUTS } from './dwsModel';
import { allDwsProfiles, type DwsFamily } from './dwsProfiles';
import { DWS_STAGE_FORMS } from './DwsIcons';
import { VP_DECK } from './dwsViewportMode';

export const slug = (s: string) => s.toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');

export const SLOT_ATRIUM = 'ENV.DESIGN.ATRIUM';
export const boardSlot = (mode: DwsMode, id: string) => (id.startsWith('ov-') ? `PROJECT.ART.OVERVIEW.${slug(id.slice(3))}` : `PROJECT.ART.${mode.toUpperCase()}.${slug(id)}`);
export const featuredSlot = (mode: DwsMode, id: string) => (id.startsWith('ov-') ? 'PROJECT.ART.OVERVIEW.FEATURED' : `PROJECT.ART.${mode.toUpperCase()}.FEATURED`);
export const tableSlot = (title: string) => `PROJECT.ART.TABLE.${slug(title)}`;
export const projectMarkSlot = (name: string) => `PROJECT.ART.PROJECT.${slug(name)}.MARK`;
export const brandAssetSlot = (id: string) => `PROJECT.ART.BRAND.ASSET.${slug(id)}`;
export const iconAssetSlot = (id: string) => `PROJECT.ART.ASSETS.${slug(id)}`;
export const stageObjectSlot = (form: string) => `ICON3D.PIPELINE.${form}`;

export type DwsSlotKind = 'ENVIRONMENT_IMAGE' | 'CARD_IMAGE' | 'FOREGROUND_IMAGE' | 'TRANSPARENT_OBJECT' | 'ICON3D' | 'PROJECT_MARK';
export type DwsSlotRecord = { id: string; kind: DwsSlotKind; surface: string; families: DwsFamily[]; aspect: string; crop: 'cover' | 'contain'; safeZone: string; continuity: string };

/** Compute every slot the workspace can render. */
export function listDwsSlots(): DwsSlotRecord[] {
  const map = new Map<string, DwsSlotRecord>();
  const add = (r: Omit<DwsSlotRecord, 'families'> & { family: DwsFamily }) => {
    const prev = map.get(r.id);
    if (prev) {
      if (!prev.families.includes(r.family)) prev.families.push(r.family);
    } else {
      const { family, ...rest } = r;
      map.set(r.id, { ...rest, families: [family] });
    }
  };
  const ALL: DwsFamily[] = ['desktop', 'tabletL', 'tabletP', 'mobile'];
  for (const f of ALL) add({ family: f, id: SLOT_ATRIUM, kind: 'ENVIRONMENT_IMAGE', surface: 'stage background (all modes)', aspect: f === 'desktop' || f === 'tabletL' ? '16:9' : f === 'tabletP' ? '3:4' : '9:16', crop: 'cover', safeZone: 'centre pedestal at 50% x 78%; upper 55% free of detail behind suspended boards', continuity: 'one atrium across all five modes' });
  for (const { family, mode, profile } of allDwsProfiles()) {
    for (const b of profile.boards) add({ family, id: boardSlot(mode, b.id), kind: 'CARD_IMAGE', surface: `${mode.toUpperCase()} board ${b.title}`, aspect: '1.1:1', crop: 'cover', safeZone: 'none (no baked text)', continuity: 'per project' });
    add({ family, id: featuredSlot(mode, profile.featured.id === 'ov-featured' ? 'ov-featured' : 'featured'), kind: 'FOREGROUND_IMAGE', surface: `${mode.toUpperCase()} featured board art`, aspect: '4:3.3', crop: 'cover', safeZone: 'lower-left 40% reserved for live statement text', continuity: 'per project' });
    for (const c of profile.table) add({ family, id: tableSlot(c.title), kind: 'CARD_IMAGE', surface: 'ON YOUR TABLE card', aspect: '4:1.5', crop: 'cover', safeZone: 'top-left PAGE chip', continuity: 'per project' });
    profile.pipeline.forEach((_, i) => void i);
  }
  // VIEWPORT is a chamber mode (live client preview): its only art slots are the ON YOUR TABLE cards of its deck.
  for (const f of ALL) for (const c of VP_DECK[f].table) add({ family: f, id: tableSlot(c.title), kind: 'CARD_IMAGE', surface: 'ON YOUR TABLE card (VIEWPORT)', aspect: '4:1.5', crop: 'cover', safeZone: 'top-left PAGE chip', continuity: 'per project' });
  for (const f of ALL) {
    for (const form of DWS_STAGE_FORMS) add({ family: f, id: stageObjectSlot(form), kind: 'ICON3D', surface: 'DESIGN PIPELINE stage object', aspect: '1:1', crop: 'contain', safeZone: 'none', continuity: 'pipeline icon family (ICON PACK 03)' });
    for (const p of DWS_PROJECTS) add({ family: f, id: projectMarkSlot(p.name), kind: 'PROJECT_MARK', surface: 'project selector mark', aspect: '34:40', crop: 'cover', safeZone: 'none', continuity: 'project' });
    for (const a of DWS_BRAND_ASSETS) add({ family: f, id: brandAssetSlot(a.id), kind: 'TRANSPARENT_OBJECT', surface: 'BRAND library grid / inspector / review', aspect: '4:3', crop: 'contain', safeZone: 'none', continuity: 'brand asset family' });
    for (const i of DWS_ICON_SET_ITEMS) add({ family: f, id: iconAssetSlot(i.id), kind: 'TRANSPARENT_OBJECT', surface: 'ASSETS icon grid / details', aspect: '1:1', crop: 'contain', safeZone: 'none', continuity: 'icon set' });
    for (const j of DWS_JOURNEYS) add({ family: f, id: `PROJECT.ART.EXPERIENCE.JOURNEY.${j.code}`, kind: 'CARD_IMAGE', surface: 'EXPERIENCE journey row', aspect: '10:7', crop: 'cover', safeZone: 'none', continuity: 'journey' });
    add({ family: f, id: 'PROJECT.ART.EXPERIENCE.PATH.PREVIEW', kind: 'FOREGROUND_IMAGE', surface: 'INTERACTION PATH REVIEW preview', aspect: '16:7', crop: 'cover', safeZone: 'lower-left reserved for live step copy', continuity: 'journey' });
    for (const t of DWS_SURFACE_TABS) add({ family: f, id: `PROJECT.ART.SURFACES.PREVIEW.${slug(t)}`, kind: 'FOREGROUND_IMAGE', surface: 'SURFACES centre preview', aspect: '16:10', crop: 'cover', safeZone: 'none', continuity: 'surface family' });
    for (const s of DWS_SURFACES) add({ family: f, id: `PROJECT.ART.SURFACES.PREVIEW.${slug(s.label)}`, kind: 'FOREGROUND_IMAGE', surface: 'SURFACES centre preview', aspect: '16:10', crop: 'cover', safeZone: 'none', continuity: 'surface family' });
    for (const s of DWS_SURFACES) add({ family: f, id: `PROJECT.ART.SURFACES.RELATED.${slug(s.id)}`, kind: 'CARD_IMAGE', surface: 'SURFACE related thumbnail', aspect: '4:3', crop: 'cover', safeZone: 'none', continuity: 'surface family' });
    DWS_VARIANTS.forEach((_, i) => add({ family: f, id: `PROJECT.ART.SURFACES.VARIANT.${i + 1}`, kind: 'CARD_IMAGE', surface: 'SURFACE expression variant', aspect: '4:3', crop: 'cover', safeZone: 'none', continuity: 'surface family' }));
    for (const s of DWS_SURFACE_FAMILIES) add({ family: f, id: `PROJECT.ART.SURFACES.FAMILY.${slug(s.id)}`, kind: 'CARD_IMAGE', surface: 'SURFACE family thumbnail', aspect: '3:2', crop: 'cover', safeZone: 'none', continuity: 'surface family' });
    for (const i of DWS_COMPILER_INPUTS) add({ family: f, id: `PROJECT.ART.COMPILER.INPUT.${slug(i.label)}`, kind: 'CARD_IMAGE', surface: 'COMPILER input', aspect: '1:1', crop: 'cover', safeZone: 'none', continuity: 'expression' });
    add({ family: f, id: 'PROJECT.ART.COMPILER.CENTER', kind: 'FOREGROUND_IMAGE', surface: 'COMPILER centre', aspect: '4:3', crop: 'cover', safeZone: 'none', continuity: 'expression' });
    add({ family: f, id: 'PROJECT.ART.COMPILER.EXPRESSION', kind: 'FOREGROUND_IMAGE', surface: 'COMPILER selected expression', aspect: '1:1', crop: 'cover', safeZone: 'none', continuity: 'expression' });
    for (const n of [1, 2, 3, 4]) add({ family: f, id: `PROJECT.ART.COMPILER.RELATED.${n}`, kind: 'CARD_IMAGE', surface: 'COMPILER related artifact', aspect: '1:1', crop: 'cover', safeZone: 'none', continuity: 'expression' });
  }
  return [...map.values()].sort((a, b) => a.id.localeCompare(b.id));
}

export const SLOT_ID_PATTERN = /^(ENV\.DESIGN\.ATRIUM|ICON3D\.PIPELINE\.[A-Z]+|PROJECT\.ART\.[A-Z0-9_.]+)$/;
