export const P0_VR_TWIN_V25_BUILD = 'v376' as const;

export const PAIRED_CONCEPT_COVERAGE_MIN = 0.95;

export const CONCEPT_OBJECT_SOURCE_TYPES = [
  'DOM_TEXT',
  'DOM_CONTROL',
  'CSS_GRAPHIC',
  'SVG_GRAPHIC',
  'EXISTING_PROJECT_ASSET',
  'GENERATED_RASTER_ASSET',
  'GENERATED_TRANSPARENT_ASSET',
  'GENERATED_COMPLEX_MEDIA',
] as const;

export const CONCEPT_VISUAL_OBJECT_TYPES = [
  'TEXT',
  'NAV_ITEM',
  'BUTTON',
  'ICON',
  'IMAGE',
  'DIVIDER',
  'BORDER',
  'SURFACE',
  'PROGRESS_TRACK',
  'PROGRESS_FILL',
  'PROGRESS_MARKER',
  'METRIC',
  'STATUS',
  'ACTIVITY_ROW',
  'TABLE_ROW',
  'BADGE',
  'GRAPHIC',
  'CONTAINER',
] as const;

export const PAIRED_CONCEPT_STATUSES = [
  'PLANNING',
  'BLUEPRINT_READY',
  'ASSET_PLAN_READY',
  'FUNCTION_PLAN_READY',
  'VISUAL_GENERATING',
  'VISUAL_READY',
  'ASSETS_RESOLVING',
  'RECONCILIATION_REQUIRED',
  'PAIRED_READY',
  'FOUNDER_REVIEW',
  'APPROVED',
  'REFINING',
  'REGENERATING',
  'BUILD_READY',
  'BUILDING',
  'BUILT',
  'FAILED',
  'CONCEPT_INCOMPLETE',
  'ASSET_INCOMPLETE',
  'FUNCTION_PLAN_INCOMPLETE',
] as const;
