/**
 * Generic Studio World — public authorship + internal/public language boundary.
 */

export const PUBLIC_AUTHORSHIP_MODE_V1 = 'PUBLIC_AUTHORSHIP_MODE_V1' as const;

export const PUBLIC_AUTHORSHIP_MODES = [
  'FIRST_PERSON_BRAND',
  'FIRST_PERSON_FOUNDER',
  'EDITORIAL_INSTITUTIONAL',
  'NARRATOR',
  'COMMUNITY_VOICE',
  'CHARACTER_VOICE',
  'HYBRID_AUTHORED',
] as const;

export const PERSON_REFERENCE_STATES = [
  'PASS_FIRST_PERSON',
  'PASS_IMPLIED_AUTHORSHIP',
  'FAIL_THIRD_PERSON_SELF_REFERENCE',
  'FAIL_SYSTEM_NARRATION',
] as const;

export const PUBLIC_METADATA_ELIGIBILITY = [
  'PUBLIC_NATIVE',
  'PUBLIC_WITH_TRANSLATION',
  'INTERNAL_ONLY',
] as const;

export const PERSONAL_AUTHORSHIP_CLASSIFICATIONS = [
  'NDX_NATIVE',
  'NDX_ACCEPTABLE',
  'TOO_ANALYTICAL',
  'TOO_EXPLANATORY',
  'TOO_BRAND_WRITTEN',
  'SYSTEM_EXPOSED',
  'AI_SUMMARY_LIKE',
] as const;

export const PUBLIC_COPY_FAILURE_STATES = [
  'FAIL_INTERNAL_LABEL_ON_PUBLIC_ARTIFACT',
  'FAIL_THIRD_PERSON_SELF_REFERENCE',
  'FAIL_PUBLIC_SYSTEM_NARRATION',
  'FAIL_ANALYTICAL_COPY_LEAK',
  'FAIL_META_CREATIVE_LANGUAGE',
  'FAIL_AI_SUMMARY_PUBLIC_COPY',
  'FAIL_PUBLIC_COPY_NOT_CHARACTER',
  'FAIL_PUBLIC_COPY_TOO_CLINICAL',
  'FAIL_PUBLIC_COPY_TOO_REPORT_LIKE',
  'FAIL_SYSTEM_LANGUAGE_ON_ARTIFACT',
  'FAIL_THIRD_PERSON_NDX',
  'FAIL_BRAND_EXPLAINS_ITSELF',
  'FAIL_ANALYTICAL_LABEL_LEAK',
  'FAIL_AI_SUMMARY_COPY',
  'FAIL_META_CREATIVE_LANGUAGE',
  'FAIL_CHARACTER_BEAT_LABEL_VISIBLE',
  'FAIL_PUBLIC_COPY_TOO_CLINICAL',
  'FAIL_PUBLIC_COPY_TOO_REPORT_LIKE',
] as const;

export const PUBLIC_ARTIFACT_EXPORT_STATES = [
  'PASS',
  'FAIL_INTERNAL_LANGUAGE',
  'FAIL_PLACEHOLDER',
  'FAIL_THIRD_PERSON_BRAND',
  'FAIL_DEBUG_TEXT',
  'FAIL_UNAPPROVED_COPY',
] as const;

export const PUBLIC_AUTHORSHIP_MODE_IMPLEMENTED = true as const;
export const INTERNAL_PUBLIC_LANGUAGE_BOUNDARY_IMPLEMENTED = true as const;
export const PUBLIC_COPY_TRANSLATION_IMPLEMENTED = true as const;
export const INTERNAL_LABEL_QUARANTINE_IMPLEMENTED = true as const;
export const THIRD_PERSON_SELF_REFERENCE_GUARD_IMPLEMENTED = true as const;
export const PERSONAL_AUTHORSHIP_EVALUATION_IMPLEMENTED = true as const;
export const SYSTEM_LANGUAGE_PUBLIC_EXPORT_BLOCKED = true as const;
export const PUBLIC_ARTIFACT_EXPORT_EVALUATION_IMPLEMENTED = true as const;
