# Emits src/projects/jurnl/runtime/layout/referenceLayout.ts from layout/*.json
import json, glob, os
from refs import WORK, LAYOUT_TS as OUT
L=os.path.join(WORK,'layout')
order=['parent','why','check','category','account','acct1','acct2','acct3','drawer','dock','dock_acct','dock_why']
names=[n for n in order if os.path.exists(f'{L}/{n}.json')]
def fmt(v):
    if isinstance(v,(list,tuple)): return '['+', '.join(fmt(x) for x in v)+']'
    if isinstance(v,float): return ('%.2f'%v).rstrip('0').rstrip('.')
    if isinstance(v,str): return json.dumps(v)
    return str(v)
lines=['/**',
' * Founder reference geometry for the SAFE TO SPEND family (P0.JURNL.F09.REFERENCE-REPLICA1).',
' * GENERATED by scripts/jurnl/reference-replica (build.py, then emit_ts.py) from the nine founder reference images in',
' * JURNL/F09_SAFE/REFERENCE_REPLICA1/REFERENCES. Every number is a reference pixel on the 853 × 1844 stage.',
' * `box` = measured [x0, y0, x1, y1]. `text` = type fitted to the measured ink: size and tracking (px),',
' * `top` of a line-height: 1 box, and the anchor (`left`, centre `cx`, or `right`). Do not edit by hand.',
' */','',
"export type RefBox = readonly [number, number, number, number];",
"export type RefType = { readonly family: 'sans' | 'serif'; readonly weight: number; readonly size: number; readonly ls: number; readonly top: number; readonly left?: number; readonly cx?: number; readonly right?: number; readonly rot?: number; readonly ink: RefBox };",
'']
for n in names:
    d=json.load(open(f'{L}/{n}.json'))
    lines.append(f'export const REF_{n.upper()} = {{')
    lines.append('  box: {')
    for k,v in d['box'].items(): lines.append(f'    {k}: {fmt(v)},')
    lines.append('  },')
    lines.append('  text: {')
    for k,t in d['text'].items():
        parts=[f"family: '{t['family']}'",f"weight: {t['weight']}",f"size: {fmt(t['size'])}",f"ls: {fmt(t['ls'])}",f"top: {fmt(t['top'])}"]
        for a in ('left','cx','right','rot'):
            if a in t: parts.append(f'{a}: {fmt(t[a])}')
        parts.append(f"ink: {fmt(t['ink'])}")
        lines.append(f'    {k}: {{ {", ".join(parts)} }},')
    lines.append('  },')
    lines.append('} as const satisfies { box: Record<string, RefBox | number | readonly number[]>; text: Record<string, RefType> };')
    lines.append('')
open(OUT,'w').write('\n'.join(lines))
print('wrote',OUT,names)
