/**
 * Composite Brand Character Synthesis + Artifact Visualization — P0.5B.2 composite sprint.
 */

export const BRAND_CHARACTER_SYNTHESIS_V1 = 'BRAND_CHARACTER_SYNTHESIS_V1' as const;
export const BRAND_CHARACTER_ARTIFACT_PROOF_V1 = 'BRAND_CHARACTER_ARTIFACT_PROOF_V1' as const;

export const NDXBOOK_CHARACTER_SYNTHESIS_RUN_ID = 'ndxbook-brand-character-synthesis';
export const NDXBOOK_CHARACTER_SYNTHESIS_DB_ID = 'c4e1a2b3-0011-4000-8000-000000000001';

export const NDXBOOK_SYNTHESIS_SOURCE_TERRITORY_NAMES = [
  'The Cultural Accomplice',
  'The Committed Contrarian',
  'The Relentless Synthesizer',
] as const;

export const CHARACTER_TERRITORY_ROLES = [
  'WHOLE_CHARACTER_CANDIDATE',
  'CHARACTER_COMPONENT',
  'CHARACTER_TENSION_SOURCE',
  'CHARACTER_CALIBRATION_SOURCE',
  'DEFERRED',
  'REJECTED',
] as const;

export const SYNTHESIS_FOUNDER_JUDGMENTS = [
  'THATS_NDX',
  'LOVE_THIS_CHARACTER',
  'PROMISING_DEVELOP',
  'TOO_CLEAN',
  'TOO_CLEAN_TOO_BRAND_LIKE',
  'TOO_GENERIC',
  'TOO_TRY_HARD',
  'TOO_INTERNET',
  'TOO_ACADEMIC',
  'TOO_SERIOUS',
  'TOO_IMMATURE',
  'TOO_SANITIZED',
  'NOT_FUNNY_ENOUGH',
  'NOT_CULTURALLY_ALIVE_ENOUGH',
  'NOT_OPINIONATED_ENOUGH',
  'NOT_CURIOUS_ENOUGH',
  'NOT_MESSY_ENOUGH',
  'NOT_MATURE_ENOUGH',
  'NOT_COHERENT',
  'NOT_NDXBOOK',
] as const;

export const ARTIFACT_PROOF_FOUNDER_JUDGMENTS = [
  'THATS_NDX',
  'LOVE_THE_CHARACTER_WRONG_VISUAL',
  'CHARACTER_THERE_DEVELOP',
  'TOO_DESIGNED',
  'TOO_GENERIC',
  'TOO_CLEAN',
  'TOO_RANDOM',
  'TOO_SERIOUS',
  'TOO_TRY_HARD',
  'TOO_LITERAL',
  'TOO_CLOSE_TO_BURN_BOOK',
  'NOT_ENOUGH_CULTURE',
  'NOT_ENOUGH_WIT',
  'NOT_ENOUGH_JUDGMENT',
  'NOT_ENOUGH_SYNTHESIS',
  'NOT_NDX',
] as const;

export const CHARACTER_TRACE_CLASSES = [
  'REACTION_TRACE',
  'JUDGMENT_TRACE',
  'MEMORY_TRACE',
  'CONNECTION_TRACE',
  'INVESTIGATION_TRACE',
  'HUMOR_TRACE',
  'CULTURAL_TRACE',
  'CORRECTION_TRACE',
  'WITHHOLDING_TRACE',
  'OBSESSION_TRACE',
  'SELECTION_TRACE',
  'REJECTION_TRACE',
  'RETURN_TRACE',
] as const;

export const SYNTHESIS_FAILURE_STATES = [
  'FAIL_CHARACTER_AS_ADJECTIVES',
  'FAIL_ARCHETYPE_MASHUP',
  'FAIL_PERSONALITY_SANITIZATION',
  'FAIL_MATURATION_BECAME_CORPORATE',
  'FAIL_NO_PRODUCTIVE_TENSION',
  'FAIL_NO_CULTURAL_INTERIORITY',
  'FAIL_GENERIC_WIT',
  'FAIL_GENERIC_EDITORIAL',
  'FAIL_GENERIC_EXPERT',
  'FAIL_REFERENCE_DEPENDENCY',
  'FAIL_STYLE_AS_CHARACTER',
  'FAIL_NO_MAKER',
  'FAIL_DECORATIVE_TRACE',
  'FAIL_UNCAUSED_ANNOTATION',
  'FAIL_RANDOM_COLLAGE',
  'FAIL_RANDOM_RECEIPTS',
  'FAIL_RANDOM_REDACTION',
  'FAIL_RANDOM_CULTURAL_REFERENCE',
  'FAIL_CHARACTER_NOT_VISIBLE',
  'FAIL_SAME_STYLE_DIFFERENT_CONTENT',
  'FAIL_BURN_BOOK_CLONE',
  'FAIL_LIME_DEPENDENCY',
  'FAIL_NO_RANGE',
  'FAIL_YOUNGER_SELF_ERASED',
  'FAIL_NO_MATURITY_GAIN',
] as const;

export const ARTIFACT_PROOF_SCENARIOS = [
  'PROOF_A_CAUGHT_SOMETHING',
  'PROOF_B_RABBIT_HOLE',
  'PROOF_C_HAS_RECEIPTS',
] as const;

export const NDXBOOK_CHARACTER_SYNTHESIS_MODE = 'NDX_BRAND_CHARACTER_SYNTHESIS' as const;

export const COMPOSITE_CHARACTER_METHODOLOGY_IMPLEMENTED = true as const;
export const CHARACTER_TERRITORIES_RECLASSIFIED_AS_DISCOVERIES = true as const;
export const NDXBOOK_CHARACTER_SYNTHESIS_PIPELINE_READY = true as const;
export const CHARACTER_TRACE_SYSTEM_IMPLEMENTED = true as const;
export const CHARACTER_ARTIFACT_CAUSALITY_ENFORCED = true as const;
export const THREE_ARTIFACT_PROOF_PIPELINE_READY = true as const;
export const FAL_CHARACTER_VISUALIZATION_READY = true as const;
export const EXPERIMENT_G_CHARACTER_REEVALUATION_FLAG_SUPPORTED = true as const;

export const FAL_CHARACTER_PROOF_COST_ESTIMATE_USD = 0.08;
