/**
 * P0.5C — Character-Led Marketing Expression System
 */

export const BRAND_MARKETING_EXPRESSION_V1 = 'BRAND_MARKETING_EXPRESSION_V1' as const;
export const MARKETING_EXPRESSION_EXPERIMENT_01_V1 = 'MARKETING_EXPRESSION_EXPERIMENT_01_V1' as const;

export const NDXBOOK_MARKETING_EXPRESSION_RUN_ID = 'ndxbook-brand-marketing-expression';
export const NDXBOOK_MARKETING_EXPRESSION_DB_ID = 'c4e1a2b3-0012-4000-8000-000000000001';

export const NDXBOOK_MARKETING_EXPRESSION_MODE = 'NDX_BRAND_MARKETING_EXPRESSION' as const;

export const FOUNDER_NORTH_STAR_CLASSIFICATION = 'CHARACTER_EXPRESSION_CALIBRATION' as const;

export const NDX_PUBLIC_BEHAVIOR_THESIS =
  'NDX does not simply publish information. NDX notices things, reacts, gets curious, asks the annoying second question, remembers something apparently unrelated, pulls receipts, investigates, connects things, catches contradictions, forms opinions — sometimes jokes, sometimes goes quiet. Marketing is the public residue of those behaviors.';

export const SURFACE_CLASSIFICATIONS = [
  'CAUSAL_BEHAVIOR',
  'BEHAVIORAL_TRACE',
  'POSSIBLE_VISUAL_MANIFESTATION',
  'SURFACE_STYLE',
  'UNKNOWN',
] as const;

export const RESOLUTION_STATES = [
  'REACTION_ONLY',
  'QUESTION_OPEN',
  'INVESTIGATION_IN_PROGRESS',
  'PROVISIONAL_CONCLUSION',
  'STRONG_CONCLUSION',
  'SELF_CORRECTION',
  'CALLBACK',
  'UNRESOLVED',
] as const;

export const MARKETING_CHARACTER_TEMPERATURES = [
  'IMPULSIVE',
  'PLAYFUL',
  'CURIOUS',
  'SUSPICIOUS',
  'INVESTIGATIVE',
  'OBSESSIVE',
  'CONVICTED',
  'REFLECTIVE',
  'SERIOUS',
  'SELF_CORRECTING',
] as const;

export const MARKETING_CHANNELS = [
  'INSTAGRAM_FEED',
  'INSTAGRAM_STORIES',
  'REELS',
  'EMAIL',
  'LONG_FORM',
  'CAMPAIGN',
] as const;

export const ARTIFACT_EXPRESSION_CLASSES = [
  'EVIDENCE_DOSSIER',
  'TYPOGRAPHIC_ARGUMENT',
  'PHOTOGRAPHIC_INTERVENTION',
  'ARCHIVAL_RECONSTRUCTION',
  'VISUAL_COMPARISON',
  'ANNOTATED_DIAGRAM',
  'DATA_COMPOSITION',
  'PHYSICAL_ASSEMBLAGE',
  'EDITORIAL_SPREAD',
  'SINGLE_IMAGE_INTERRUPTION',
  'OBJECT_STUDY',
  'TIMELINE',
  'ANNOTATED_INTERFACE',
  'VISUAL_ESSAY',
  'MINIMAL_REACTION',
  'MAXIMAL_INVESTIGATION',
  'CONCEPTUAL_GRAPHIC',
  'ORIGINAL_ILLUSTRATION',
  'MIXED_MEDIA_ARTIFACT',
  'MOTION_NATIVE_ARTIFACT',
] as const;

export const BEHAVIORAL_MODE_KINDS = ['SEED_MODE', 'DISCOVERED_BEHAVIORAL_MODE'] as const;

export const MARKETING_ARTIFACT_FOUNDER_JUDGMENTS = [
  'THATS_NDX',
  'LOVE_THIS',
  'CHARACTER_RIGHT_VISUAL_WRONG',
  'VISUAL_GREAT_CHARACTER_WRONG',
  'PROMISING_DEVELOP',
  'TOO_DESIGNED',
  'TOO_GENERIC',
  'TOO_CLEAN',
  'TOO_MESSY_WITHOUT_PURPOSE',
  'TOO_SERIOUS',
  'TRYING_TOO_HARD_TO_BE_FUNNY',
  'TRYING_TOO_HARD_TO_BE_SMART',
  'NOT_ENOUGH_CULTURE',
  'NOT_ENOUGH_JUDGMENT',
  'NOT_ENOUGH_CURIOSITY',
  'NOT_ENOUGH_SYNTHESIS',
  'NOT_ENOUGH_MAKER_PRESENCE',
  'TOO_CLOSE_TO_NORTH_STAR',
  'TOO_TEMPLATE_LIKE',
  'NOT_NDX',
] as const;

export const MARKETING_SET_FOUNDER_JUDGMENTS = [
  'THIS_IS_THE_NDX_FEED',
  'RIGHT_CHARACTER_NEEDS_MORE_RANGE',
  'RIGHT_RANGE_NEEDS_MORE_COHESION',
  'TOO_VISUALLY_SAME',
  'TOO_VISUALLY_RANDOM',
  'CHARACTER_DISAPPEARS_ACROSS_TOPICS',
  'DEVELOP_THE_SYSTEM',
  'NOT_READY',
] as const;

export const MARKETING_FAILURE_STATES = [
  'FAIL_TOPIC_TO_TEMPLATE',
  'FAIL_GENERIC_SOCIAL_POST',
  'FAIL_GENERIC_EDITORIAL',
  'FAIL_CHARACTER_AS_COPYWRITING_ONLY',
  'FAIL_CHARACTER_AS_AESTHETIC',
  'FAIL_SURFACE_NORTH_STAR_COPY',
  'FAIL_LIME_DEPENDENCY',
  'FAIL_COLLAGE_DEPENDENCY',
  'FAIL_HANDWRITING_DEPENDENCY',
  'FAIL_RECEIPT_DEPENDENCY',
  'FAIL_CONDENSED_TYPE_DEPENDENCY',
  'FAIL_DECORATIVE_EVIDENCE',
  'FAIL_DECORATIVE_ANNOTATION',
  'FAIL_UNCAUSED_HIGHLIGHT',
  'FAIL_UNCAUSED_CROSSOUT',
  'FAIL_UNCAUSED_CIRCLE',
  'FAIL_RANDOM_ARCHIVE',
  'FAIL_RANDOM_CULTURAL_REFERENCE',
  'FAIL_NO_JUDGMENT',
  'FAIL_NO_MAKER',
  'FAIL_NO_CHARACTER_EVENT',
  'FAIL_MANUFACTURED_HOT_TAKE',
  'FAIL_FORCED_HUMOR',
  'FAIL_PERFORMATIVE_INTELLIGENCE',
  'FAIL_CORPORATE_THOUGHT_LEADERSHIP',
  'FAIL_ALL_POSTS_SAME_TEMPERATURE',
  'FAIL_ALL_POSTS_SAME_DENSITY',
  'FAIL_SAME_TEMPLATE_DIFFERENT_TOPIC',
  'FAIL_NDX_NOT_RECOGNIZABLE',
] as const;

export const FAL_MARKETING_PROMPT_SECTION_ORDER = [
  'SUBJECT_SITUATION',
  'WHAT_NDX_NOTICED',
  'NDX_REACTION',
  'INVESTIGATION_CONNECTION_MEMORY',
  'JUDGMENT_STATE',
  'REQUIRED_INFORMATION',
  'ACTIONS_NDX_TOOK',
  'TRACES_LEFT',
  'ARTIFACT_TYPE',
  'COMPOSITIONAL_LOGIC',
  'MATERIAL_CONDITIONS',
  'TYPOGRAPHIC_BEHAVIOR',
  'COLOR_BEHAVIOR',
  'PHOTOGRAPHIC_ILLUSTRATIVE_CONDITIONS',
  'VISUAL_FREEDOM',
  'NEGATIVE_CONSTRAINTS',
] as const;

export const FAL_MARKETING_COST_ESTIMATE_USD = 0.08;
export const EXPERIMENT_01_ARTIFACT_COUNT = 9;

export const BRAND_MARKETING_EXPRESSION_LAYER_IMPLEMENTED = true as const;
export const NDXBOOK_MARKETING_EXPRESSION_SYSTEM_READY = true as const;
export const FOUNDER_NORTH_STAR_FORENSIC_DECOMPOSITION_IMPLEMENTED = true as const;
export const SURFACE_CAUSE_SEPARATION_IMPLEMENTED = true as const;
export const MARKETING_CHARACTER_EVENT_IMPLEMENTED = true as const;
export const NDX_BEHAVIORAL_CONTENT_GRAMMAR_IMPLEMENTED = true as const;
export const DISCOVERED_BEHAVIORAL_MODES_SUPPORTED = true as const;
export const VISUAL_CAUSALITY_IMPLEMENTED = true as const;
export const CHANNEL_MODULATION_IMPLEMENTED = true as const;
export const CHARACTER_RECOGNITION_TEST_IMPLEMENTED = true as const;
export const NORTH_STAR_CHARACTER_DISTANCE_IMPLEMENTED = true as const;
export const EXPERIMENT_01_PIPELINE_READY = true as const;
export const TEMPLATE_COLLAPSE_GUARDS_IMPLEMENTED = true as const;
export const EXPERIMENT_F_IMMUTABLE = true as const;
export const EXPERIMENT_G_IMMUTABLE = true as const;
export const PRODUCT_EXPRESSION_BLOCKED = true as const;
export const WORLD_FORMATION_BLOCKED = true as const;
