/** SITE 00 Admin Production OS — route constants (namespace avoids Studio OS /admin/studio/*). */
export const SITE00_ADMIN_ROUTES = {
  root: '/admin/site00',
  dashboard: '/admin/site00',
  studio: '/admin/site00/studio',
  studioQueue: '/admin/site00/studio/queue',
  studioRecipes: '/admin/site00/studio/recipes',
  approvals: '/admin/site00/approvals',
  identities: '/admin/site00/identities',
  identity: (id: string) => `/admin/site00/identities/${id}`,
  bldrIntakes: '/admin/site00/bldr-intakes',
  bldrIntake: (id: string) => `/admin/site00/bldr-intakes/${id}`,
  leads: '/admin/site00/leads',
  lead: (id: string) => `/admin/site00/leads/${id}`,
  discovery: '/admin/site00/discovery',
  discoveryBooking: (id: string) => `/admin/site00/discovery/${id}`,
  projects: '/admin/site00/projects',
  project: (id: string) => `/admin/site00/projects/${id}`,
  projectIntelligence: (id: string) => `/admin/site00/projects/${id}/intelligence`,
  projectStudio: (id: string) => `/admin/site00/projects/${id}/studio`,
  projectApprovals: (id: string) => `/admin/site00/projects/${id}/approvals`,
  projectDeliverables: (id: string) => `/admin/site00/projects/${id}/deliverables`,
  projectAccess: (id: string) => `/admin/site00/projects/${id}/access`,
  projectActivity: (id: string) => `/admin/site00/projects/${id}/activity`,
  sites: '/admin/site00/sites',
  site: (id: string) => `/admin/site00/sites/${id}`,
  ctrlRoom: '/admin/site00/ctrl-room',
  finance: '/admin/site00/finance',
  invoice: (id: string) => `/admin/site00/finance/invoices/${id}`,
  team: '/admin/site00/team',
  reports: '/admin/site00/reports',
  reportsPipeline: '/admin/site00/reports/pipeline',
  activity: '/admin/site00/activity',
  accessCredentials: '/admin/site00/access-credentials',
  accessCredential: (id: string) => `/admin/site00/access-credentials/${id}`,
  settings: '/admin/site00/settings',
  settingsAutomation: '/admin/site00/settings/studio/automation',
  emailPack: '/admin/site00/debug/email-pack',
  emailTemplate: (id: string) => `/admin/site00/debug/email-pack/${id}`,
  evolveMarketingDebug: '/admin/site00/debug/evolve-marketing',
  orchestrationDebug: '/admin/site00/debug/orchestration',
  orchestrationProject: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}`,
  evolve: '/admin/site00/evolve',
  evolveOrg: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}/evolve`,
  evolveCampaigns: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}/evolve/campaigns`,
  evolveCampaign: (orgSlug: string, campaignId: string) =>
    `/admin/site00/orchestration/${orgSlug}/evolve/campaigns/${campaignId}`,
  evolveCalendar: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}/evolve/calendar`,
  evolveCalendarItem: (orgSlug: string, itemId: string) =>
    `/admin/site00/orchestration/${orgSlug}/evolve/calendar/${itemId}`,
  evolveEmails: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}/evolve/emails`,
  evolveSocial: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}/evolve/social`,
  evolveProductionNew: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}/evolve/production/new`,
  evolvePlans: (orgSlug: string) => `/admin/site00/orchestration/${orgSlug}/evolve/plans`,
  evolveApprovals: '/admin/site00/evolve/approvals',
  evolveDebug: '/admin/site00/debug/evolve',
  reconciliation: '/admin/site00/reconciliation',
  marketingEngagements: '/admin/site00/marketing-engagements',
  marketingEngagement: (id: string) => `/admin/site00/marketing-engagements/${id}`,
  /** Shorthand aliases (redirect to emailPack) */
  emailPackDebugShort: '/debug/email-pack',
  emailPackDebugControl: '/control/debug/email-pack',
  clientProvisioning: (slug: string) => `/project/${slug}/provisioning`,
} as const;
