/**
 * P0.5C.4 — Art-Board Materiality + Imperfect Canvas (61 requirements)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  ARTIFACT_MATERIALITY_SYSTEM_IMPLEMENTED,
  CANVAS_AS_OBJECT_IMPLEMENTED,
  ART_BOARD_DIRECTION_IMPLEMENTED,
  MODERN_NOTEBOOK_EXPRESSION_IMPLEMENTED,
  TORN_PAPER_GOVERNANCE_IMPLEMENTED,
  PAGE_EDGE_BEHAVIOR_IMPLEMENTED,
  ARTIFACT_LAYER_CONSTRUCTION_IMPLEMENTED,
  ARTIFACT_CONSTRUCTION_HISTORY_IMPLEMENTED,
  ARTIFACT_DEPTH_BEHAVIOR_IMPLEMENTED,
  ATTACHMENT_CAUSALITY_IMPLEMENTED,
  PRINT_SCAN_BEHAVIOR_IMPLEMENTED,
  IMPERFECT_CANVAS_EVALUATION_IMPLEMENTED,
  MATERIAL_DENSITY_EVALUATION_IMPLEMENTED,
  MATERIAL_MODERNITY_EVALUATION_IMPLEMENTED,
  FEED_MATERIAL_RHYTHM_IMPLEMENTED,
  TEMPLATE_LIKE_CANVAS_GUARD_IMPLEMENTED,
  FAKE_PAPER_TEXTURE_GUARD_IMPLEMENTED,
  SCRAPBOOK_COLLAPSE_GUARD_IMPLEMENTED,
  P0_5C_3_CHARACTER_RETENTION_PRESERVED,
  EXPERIMENT_01_V2_3_ART_BOARD_PIPELINE_READY,
  P0_5E_ROUND_01_MATERIAL_GATE_INTEGRATED,
  CONTENT_OPERATIONS_ART_BOARD_DIRECTION_INTEGRATED,
  FAL_MATERIAL_PROMPT_SECTION_ORDER,
  V23_FOUNDER_JUDGMENTS,
  BASE_SURFACE_CLASSES,
} from './artBoardMateriality/constants.js';
import {
  buildArtBoardDirectionContract,
  attachmentRequiresCausality,
  tornPaperOptional,
  notebookOptional,
  materialSeparateFromBackgroundTexture,
  canvasModeledAsObject,
  sparseMayBeMateriallyRich,
} from './artBoardMateriality/artBoardDirectionContract.js';
import {
  buildArtifactMaterialityEvaluation,
  fakePaperTextureFails,
  materialRichnessSeparateFromInformationDensity,
} from './artBoardMateriality/evaluations.js';
import {
  buildFeedMaterialRhythm,
  allPostsSameCanvasFails,
  allPostsTornPaperFails,
  scrapbookCollapseFails,
} from './artBoardMateriality/feedRhythm.js';
import {
  compileArtBoardMaterialityFalPrompt,
  materialFalPromptHasTemplateGuard,
  falPositiveInstructionPresent,
  materialFalPromptArtifactFormBeforeAesthetic,
} from './artBoardMateriality/falPromptCompilerV23.js';
import {
  formulateExperiment01V23,
  v23ContractReviewBeforeGeneration,
  v22HistoryNotMutated,
  v23KeepsSameNineTopics,
  v23PreservesC3Character,
  v23PreservesC1Hierarchy,
  experiment01V23GeneratedByDefault,
  sequenceMaterialProgressionSupported,
} from './artBoardMateriality/experiment01V23.js';
import {
  artBoardMaterialityApprovalGatePasses,
  round01LockRequiresMaterialGate,
  slide02EvolvesMaterialNotCopy,
} from './artBoardMateriality/approvalGate.js';
import {
  contentOperationsRequiresArtBoardDirection,
  platformDerivationDoesNotBlindlyReusePaperArtifact,
  brandCharacterImmutable,
  experimentFImmutable,
  experimentGImmutable,
} from './artBoardMateriality/integration.js';
import { evaluateNorthStarArtBoardMateriality, northStarMaterialNotIdentityPromotion } from './artBoardMateriality/northStarMaterialForensics.js';
import { CHARACTER_RETENTION_SYSTEM_IMPLEMENTED } from './characterRetention/constants.js';
import { CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED } from './culturalVisualParticipation/constants.js';
import { EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED } from './editorialInformationArchitecture/constants.js';
import { formulateExperiment01V2 } from './editorialInformationArchitecture/experiment01V2.js';
import { formulateExperiment01V21 } from './culturalVisualParticipation/experiment01V21.js';
import { formulateExperiment01V22 } from './characterRetention/experiment01V22.js';
import { formulateExperiment01Artifacts } from './brandMarketingExpression/characterEventFormulation.js';
import { compileBrandMarketingExpressionSystem } from './brandMarketingExpression/marketingExpressionCompiler.js';
import { buildVitestBrandCharacterSystemForMarketing } from './brandMarketingExpression/vitestFixtures.js';
import { buildFounderMarketingNorthStarArtifact } from './brandMarketingExpression/northStarArtifact.js';
import { buildSocialContentPackage } from './contentOperations/contentPackage.js';
import { seedPilotOpportunities } from './contentOperations/opportunityEngine.js';
import { selectChannelForOpportunity, selectFormatForOpportunity } from './contentOperations/channelFormatSelection.js';
import {
  noPageLoadGeneration,
  experiment01V23NotAutoGenerated,
  resetBrandMarketingExpressionWorkers,
  prepareBrandMarketingExpression,
  compileBrandMarketingExpression,
  formulateMarketingExpressionExperiment01,
  formulateMarketingExpressionExperiment01V2,
  formulateMarketingExpressionExperiment01V21,
  formulateMarketingExpressionExperiment01V22,
  formulateMarketingExpressionExperiment01V23,
  generateAllExperiment01V23ArtifactAssets,
  getBrandMarketingExpressionState,
} from '../../api/_lib/site00Evolve/creativeDirection/brandMarketingExpressionExperiment/brandMarketingExpressionService.js';
import { lockCampaignRound01 as lockRound01Service, initializeCampaignBoardFromExperiment01 } from '../../api/_lib/site00Evolve/marketingCampaignProduction/marketingCampaignProductionService.js';

const ROOT = join(process.cwd());

describe('P0.5C.4 Art-Board Materiality', () => {
  const characterSystem = buildVitestBrandCharacterSystemForMarketing();
  const expressionSystem = compileBrandMarketingExpressionSystem({
    characterSystem,
    northStarId: buildFounderMarketingNorthStarArtifact('ndxbook').id,
    projectId: 'ndxbook',
  });
  const { artifacts } = formulateExperiment01Artifacts({
    expressionSystem,
    characterSystemId: characterSystem.id,
  });

  let v22Result: ReturnType<typeof formulateExperiment01V22>;
  let v23Result: ReturnType<typeof formulateExperiment01V23>;

  beforeAll(() => {
    const v2 = formulateExperiment01V2({
      v1Artifacts: artifacts,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    const v21 = formulateExperiment01V21({
      v1Artifacts: artifacts,
      v2Experiment: v2.experiment,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    v22Result = formulateExperiment01V22({
      v1Artifacts: artifacts,
      v21Experiment: v21.experiment,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    v23Result = formulateExperiment01V23({
      v1Artifacts: artifacts,
      v22Experiment: v22Result.experiment,
      expressionSystem,
    });
  });

  it('1-4. Prior systems remain valid', () => {
    expect(ARTIFACT_MATERIALITY_SYSTEM_IMPLEMENTED).toBe(true);
    expect(EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED).toBe(true);
    expect(CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED).toBe(true);
    expect(CHARACTER_RETENTION_SYSTEM_IMPLEMENTED).toBe(true);
  });

  it('5-8. Canvas as object + surface roles', () => {
    expect(CANVAS_AS_OBJECT_IMPLEMENTED).toBe(true);
    expect(materialSeparateFromBackgroundTexture()).toBe(true);
    const ab = v23Result.artifacts[0]!.contract.artBoardDirection;
    expect(canvasModeledAsObject(ab.canvasObject)).toBe(true);
    expect(ab.primaryLayer.role).toBe('PRIMARY_CANVAS');
  });

  it('9-12. Optional paper/tape/notebook + surface classes', () => {
    expect(BASE_SURFACE_CLASSES.length).toBeGreaterThan(20);
    expect(tornPaperOptional('NONE')).toBe(true);
    expect(notebookOptional('MINIMAL_PAGE')).toBe(true);
    const surfaces = new Set(v23Result.artifacts.map((a) => a.contract.artBoardDirection.materialitySystem.baseSurface));
    expect(surfaces.size).toBeGreaterThan(3);
  });

  it('13-16. Attachment causality + random guards', () => {
    expect(ATTACHMENT_CAUSALITY_IMPLEMENTED).toBe(true);
    const withAtt = v23Result.artifacts.find((a) => a.contract.artBoardDirection.attachmentLogic.length > 0);
    if (withAtt) {
      expect(attachmentRequiresCausality(withAtt.contract.artBoardDirection.attachmentLogic[0]!.mechanism, withAtt.contract.artBoardDirection.attachmentLogic[0]!.causality)).toBe(true);
    }
    expect(attachmentRequiresCausality('TAPE', 'for personality')).toBe(false);
  });

  it('17-21. Construction history + layers + depth', () => {
    expect(ARTIFACT_CONSTRUCTION_HISTORY_IMPLEMENTED).toBe(true);
    expect(ARTIFACT_LAYER_CONSTRUCTION_IMPLEMENTED).toBe(true);
    expect(ARTIFACT_DEPTH_BEHAVIOR_IMPLEMENTED).toBe(true);
    const ab = v23Result.artifacts[0]!.contract.artBoardDirection;
    expect(ab.constructionHistory.firstPresent.length).toBeGreaterThan(0);
    expect(ab.primaryLayer.layerType).toBe('BASE_PAGE');
  });

  it('22-26. Surface interaction + modern notebook', () => {
    expect(MODERN_NOTEBOOK_EXPRESSION_IMPLEMENTED).toBe(true);
    const notebook = v23Result.artifacts.find((a) => a.contract.artBoardDirection.modernNotebookExpression);
    expect(notebook?.contract.artBoardDirection.modernNotebookExpression?.contemporary).toBe(true);
    expect(v23Result.artifacts[0]!.contract.artBoardDirection.typographySurfaceInteraction.length).toBeGreaterThan(0);
  });

  it('27-31. Material density separate + sparse materially rich', () => {
    expect(MATERIAL_DENSITY_EVALUATION_IMPLEMENTED).toBe(true);
    const sparse = v23Result.artifacts.find((a) => a.contract.textDensity.level === 'SPARSE' || a.contract.textDensity.level === 'MINIMAL');
    if (sparse) {
      expect(sparseMayBeMateriallyRich(sparse.contract.textDensity.level, sparse.materialityEvaluation.materialDensity.level)).toBe(true);
    }
    expect(materialRichnessSeparateFromInformationDensity('SPARSE', 'RICH')).toBe(true);
  });

  it('32-36. Feed material rhythm + repetition guards', () => {
    expect(FEED_MATERIAL_RHYTHM_IMPLEMENTED).toBe(true);
    expect(v23Result.experiment.feedMaterialRhythm?.variationAdequate).toBe(true);
    expect(allPostsSameCanvasFails({ allSameCanvas: true } as never)).toBe(true);
    expect(allPostsTornPaperFails({ allTornPaper: true } as never)).toBe(true);
    expect(scrapbookCollapseFails({ allCollage: true } as never)).toBe(true);
  });

  it('37-43. V2.2 preserved + V2.3 lineage + C.3 preserved', () => {
    expect(v22HistoryNotMutated()).toBe(true);
    expect(EXPERIMENT_01_V2_3_ART_BOARD_PIPELINE_READY).toBe(true);
    expect(v23KeepsSameNineTopics(v23Result.artifacts)).toBe(true);
    expect(v23PreservesC1Hierarchy(v23Result.artifacts[0]!.contract)).toBe(true);
    expect(v23PreservesC3Character(v23Result.artifacts[0]!.contract)).toBe(true);
  });

  it('44-48. FAL prompt + founder-triggered', () => {
    expect(experiment01V23GeneratedByDefault()).toBe(false);
    expect(experiment01V23NotAutoGenerated()).toBe(true);
    expect(noPageLoadGeneration()).toBe(true);
    expect(FAL_MATERIAL_PROMPT_SECTION_ORDER.length).toBe(35);
    const prompt = compileArtBoardMaterialityFalPrompt({ artifact: artifacts[0]!, contract: v23Result.artifacts[0]!.contract });
    expect(materialFalPromptHasTemplateGuard(prompt)).toBe(true);
    expect(falPositiveInstructionPresent(prompt)).toBe(true);
    expect(materialFalPromptArtifactFormBeforeAesthetic(prompt)).toBe(true);
  });

  it('49-52. P0.5E + content ops + cross-platform', () => {
    expect(P0_5E_ROUND_01_MATERIAL_GATE_INTEGRATED).toBe(true);
    expect(CONTENT_OPERATIONS_ART_BOARD_DIRECTION_INTEGRATED).toBe(true);
    expect(round01LockRequiresMaterialGate({ v23Experiment: null }).allowed).toBe(false);
    expect(platformDerivationDoesNotBlindlyReusePaperArtifact()).toBe(true);
    expect(slide02EvolvesMaterialNotCopy()).toBe(true);
    expect(sequenceMaterialProgressionSupported()).toBe(true);
  });

  it('53-55. Experimental integrity', () => {
    expect(brandCharacterImmutable()).toBe(true);
    expect(experimentFImmutable()).toBe(true);
    expect(experimentGImmutable()).toBe(true);
  });

  it('56. Content package art-board direction', () => {
    const opp = seedPilotOpportunities('ndxbook')[0]!;
    const pkg = buildSocialContentPackage({
      projectId: 'ndxbook',
      opportunity: opp,
      channel: selectChannelForOpportunity(opp),
      format: selectFormatForOpportunity(opp, selectChannelForOpportunity(opp)),
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    expect(contentOperationsRequiresArtBoardDirection({ id: 'abd-test' } as never)).toBe(true);
    expect(pkg.artBoardDirectionContractId).toBeTruthy();
  });

  it('57. Service: formulate V2.3 + material lock gate', async () => {
    resetBrandMarketingExpressionWorkers();
    await prepareBrandMarketingExpression({ projectId: 'ndxbook' });
    await compileBrandMarketingExpression({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V2({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V21({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V22({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V23({ projectId: 'ndxbook' });

    await initializeCampaignBoardFromExperiment01({ projectId: 'ndxbook' });
    await expect(lockRound01Service({ projectId: 'ndxbook' })).rejects.toThrow(/V2\.3|materiality/i);

    await generateAllExperiment01V23ArtifactAssets({ projectId: 'ndxbook' });
    const freshRun = await getBrandMarketingExpressionState({ projectId: 'ndxbook' });
    for (const a of freshRun!.experiment01V23!.generatedArtifacts) {
      expect(artBoardMaterialityApprovalGatePasses(a)).toBe(true);
    }
    expect(round01LockRequiresMaterialGate({ v23Experiment: freshRun!.experiment01V23 }).allowed).toBe(true);
  });

  it('58-61. UI + north star + template guards', () => {
    const page = readFileSync(join(ROOT, 'src/site00/pages/ProjectBrandMarketingExpressionExperiment01Page.tsx'), 'utf8');
    expect(page).toContain('V2.3 — ART-BOARD MATERIALITY');
    expect(page).toContain('ARTIFACT FORM');
    expect(V23_FOUNDER_JUDGMENTS.length).toBeGreaterThanOrEqual(18);
    expect(TEMPLATE_LIKE_CANVAS_GUARD_IMPLEMENTED).toBe(true);
    expect(FAKE_PAPER_TEXTURE_GUARD_IMPLEMENTED).toBe(true);
    expect(SCRAPBOOK_COLLAPSE_GUARD_IMPLEMENTED).toBe(true);
    expect(P0_5C_3_CHARACTER_RETENTION_PRESERVED).toBe(true);
    const cal = evaluateNorthStarArtBoardMateriality();
    expect(cal.classification).toBe('ART_BOARD_MATERIALITY_CALIBRATION');
    expect(northStarMaterialNotIdentityPromotion()).toBe(true);
    const evaln = buildArtifactMaterialityEvaluation({
      artifactId: 'x',
      contract: v23Result.artifacts[0]!.contract.artBoardDirection,
      v22Contract: v23Result.artifacts[0]!.contract,
      topic: 'test',
    });
    expect(fakePaperTextureFails(evaln)).toBe(false);
  });
});
