/**
 * P0.5C.4B — Signature lime presence + color continuity (30 requirements)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import {
  NDX_SIGNATURE_LIME_REQUIRED,
  EVERY_NDX_MARKETING_ARTIFACT_HAS_SIGNATURE_LIME,
  SIGNATURE_LIME_DOES_NOT_REQUIRE_DOMINANCE,
  SEMANTIC_LIME_ACCENT_SELECTION_IMPLEMENTED,
  WORD_LEVEL_LIME_ACCENT_SUPPORTED,
  PUNCTUATION_LIME_ACCENT_SUPPORTED,
  NDX_MAKER_MARK_COLOR_RULE_IMPLEMENTED,
  SOURCE_COLOR_PRESERVATION_IMPLEMENTED,
  RANDOM_ACCENT_COLOR_GUARD_IMPLEMENTED,
  PERCEPTIBLE_SIGNATURE_EVALUATION_IMPLEMENTED,
  FEED_SIGNATURE_COLOR_CONTINUITY_IMPLEMENTED,
  LIME_TEMPLATE_REPETITION_GUARD_IMPLEMENTED,
  SIGNATURE_LIME_MICRO_REVISION_IMPLEMENTED,
  ROUND_01_SIGNATURE_LIME_GATE_IMPLEMENTED,
  STUDIO_WORLD_SIGNATURE_BRAND_TRACE_GENERALIZED,
  P0_5C_4A_HUMAN_MADE_MARK_SYSTEM_PRESERVED,
  P0_5C_4_ART_BOARD_MATERIALITY_PRESERVED,
  P0_5C_3_CHARACTER_RETENTION_PRESERVED,
  FAL_MATERIAL_PROMPT_SECTION_ORDER,
  V23B_FOUNDER_JUDGMENTS,
} from './artBoardMateriality/constants.js';
import { SIGNATURE_BRAND_TRACE_GENERALIZED } from '../site00-studio-world-production/signatureBrandTrace/constants.js';
import {
  NDX_SIGNATURE_LIME,
  NDX_SIGNATURE_LIME_PRESENCE_REQUIREMENT,
  NDX_SIGNATURE_BRAND_TRACE_REQUIREMENT,
  selectSignatureLimeAccent,
  evaluateNdxAuthoredColorOwnership,
  evaluateSignatureLimePresence,
  evaluateLimeDominance,
  evaluatePerceptibleSignature,
  buildSignatureLimeRevision,
  auditV23SignatureLimeMigration,
  ndxAuthoredRedWithoutReasonFails,
  randomAccentColorFails,
  invisibleLimeFails,
  decorativeOnlyLimeFails,
  punctuationCanSatisfyRequirement,
  oneElementCanSatisfyRequirement,
  signatureLimeDoesNotRequireDominance,
  ndxMakerMarkPrefersLime,
  sourceColorPreserved,
  signatureLimeRevisionReady,
} from './artBoardMateriality/signatureLime.js';
import {
  buildFeedSignatureColorContinuity,
  limeTemplateRepetitionFails,
  feedSignatureColorContinuityPasses,
} from './artBoardMateriality/feedSignatureContinuity.js';
import {
  compileArtBoardMaterialityFalPrompt,
  materialFalPromptHasSignatureLimeRequirement,
  materialFalPromptDistinguishesSourceVsNdxColor,
} from './artBoardMateriality/falPromptCompilerV23.js';
import {
  formulateExperiment01V23,
  v23PreservesC3Character,
  experiment01V23GeneratedByDefault,
} from './artBoardMateriality/experiment01V23.js';
import {
  artBoardMaterialityApprovalGatePasses,
  signatureLimeGatePasses,
  round01LockRequiresMaterialGate,
} from './artBoardMateriality/approvalGate.js';
import { ARTIFACT_MATERIALITY_SYSTEM_IMPLEMENTED, NDX_HUMAN_MADE_MARK_SYSTEM_IMPLEMENTED } from './artBoardMateriality/constants.js';
import { formulateExperiment01Artifacts } from './brandMarketingExpression/characterEventFormulation.js';
import { compileBrandMarketingExpressionSystem } from './brandMarketingExpression/marketingExpressionCompiler.js';
import { buildVitestBrandCharacterSystemForMarketing } from './brandMarketingExpression/vitestFixtures.js';
import { buildFounderMarketingNorthStarArtifact } from './brandMarketingExpression/northStarArtifact.js';
import { formulateExperiment01V2 } from './editorialInformationArchitecture/experiment01V2.js';
import { formulateExperiment01V21 } from './culturalVisualParticipation/experiment01V21.js';
import { formulateExperiment01V22 } from './characterRetention/experiment01V22.js';
import { noPageLoadGeneration, experiment01V23NotAutoGenerated } from '../../api/_lib/site00Evolve/creativeDirection/brandMarketingExpressionExperiment/brandMarketingExpressionService.js';

describe('P0.5C.4B Signature Lime Presence', () => {
  const characterSystem = buildVitestBrandCharacterSystemForMarketing();
  const expressionSystem = compileBrandMarketingExpressionSystem({
    characterSystem,
    northStarId: buildFounderMarketingNorthStarArtifact('ndxbook').id,
    projectId: 'ndxbook',
  });
  const { artifacts } = formulateExperiment01Artifacts({
    expressionSystem,
    characterSystemId: characterSystem.id,
  });
  let v23Result: ReturnType<typeof formulateExperiment01V23>;

  beforeAll(() => {
    const v2 = formulateExperiment01V2({ v1Artifacts: artifacts, expressionSystem, characterSystemId: characterSystem.id });
    const v21 = formulateExperiment01V21({ v1Artifacts: artifacts, v2Experiment: v2.experiment, expressionSystem, characterSystemId: characterSystem.id });
    const v22 = formulateExperiment01V22({ v1Artifacts: artifacts, v21Experiment: v21.experiment, expressionSystem, characterSystemId: characterSystem.id });
    v23Result = formulateExperiment01V23({ v1Artifacts: artifacts, v22Experiment: v22.experiment, expressionSystem });
  });

  it('1–4. Every artifact requires signature lime; no dominance required; one element suffices; punctuation valid', () => {
    expect(NDX_SIGNATURE_LIME_REQUIRED).toBe(true);
    expect(EVERY_NDX_MARKETING_ARTIFACT_HAS_SIGNATURE_LIME).toBe(true);
    expect(oneElementCanSatisfyRequirement()).toBe(true);
    expect(NDX_SIGNATURE_LIME_PRESENCE_REQUIREMENT.minimumVisibleSignatureElements).toBe(1);
    for (const a of v23Result.artifacts) {
      expect(a.signatureLimeEvaluation?.presence.signaturePresent).toBe(true);
    }
    const topic6 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-6')!;
    expect(punctuationCanSatisfyRequirement(topic6.signatureLimeEvaluation!.accentSelection)).toBe(true);
  });

  it('5–7. Word-level accent; semantic selection; topic 3 APOLOGY calibration', () => {
    expect(WORD_LEVEL_LIME_ACCENT_SUPPORTED).toBe(true);
    expect(SEMANTIC_LIME_ACCENT_SELECTION_IMPLEMENTED).toBe(true);
    const topic3 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-3')!;
    expect(topic3.signatureLimeEvaluation?.accentSelection.wordLevelAccent?.word).toBe('APOLOGY');
    expect(topic3.signatureLimeEvaluation?.accentSelection.secondaryAccent?.targetText).toContain('NDX circle');
    expect(topic3.signatureLimeMigration?.revisionClass).toBe('PASS_AS_IS');
  });

  it('8–11. Maker marks prefer lime; source color preserved; red rejected; random accent fails', () => {
    expect(NDX_MAKER_MARK_COLOR_RULE_IMPLEMENTED).toBe(true);
    expect(SOURCE_COLOR_PRESERVATION_IMPLEMENTED).toBe(true);
    expect(RANDOM_ACCENT_COLOR_GUARD_IMPLEMENTED).toBe(true);
    expect(sourceColorPreserved(true)).toBe(true);
    const red = evaluateNdxAuthoredColorOwnership({
      artifactId: 't',
      ndxAuthoredMarkColor: 'red',
      isSourceMaterial: false,
      semanticJustification: null,
    });
    expect(ndxAuthoredRedWithoutReasonFails(red)).toBe(true);
    expect(randomAccentColorFails(red)).toBe(true);
    const lime = evaluateNdxAuthoredColorOwnership({
      artifactId: 't',
      ndxAuthoredMarkColor: NDX_SIGNATURE_LIME,
      isSourceMaterial: false,
      semanticJustification: null,
    });
    expect(ndxMakerMarkPrefersLime({
      targetType: 'NDX_MARK',
      targetText: 'circle',
      reason: 'NDX maker mark in signature lime',
      colorToken: NDX_SIGNATURE_LIME,
      wordLevelAccent: null,
      punctuationAccent: null,
      secondaryAccent: null,
    })).toBe(true);
  });

  it('12–14. Invisible lime fails; decorative-only fails; dominance separate', () => {
    expect(PERCEPTIBLE_SIGNATURE_EVALUATION_IMPLEMENTED).toBe(true);
    expect(invisibleLimeFails({ passes: false, perceptibleAtFeedDistance: false, withinReadingPath: false, evaluationId: 'x', artifactId: 'x', evaluatedAt: '' })).toBe(true);
    expect(decorativeOnlyLimeFails({ targetType: 'NDX_MARK', targetText: 'x', reason: 'short', colorToken: NDX_SIGNATURE_LIME, wordLevelAccent: null, punctuationAccent: null, secondaryAccent: null })).toBe(true);
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    expect(signatureLimeDoesNotRequireDominance(topic1.signatureLimeEvaluation!.dominance)).toBe(true);
    expect(SIGNATURE_LIME_DOES_NOT_REQUIRE_DOMINANCE).toBe(true);
  });

  it('15–18. Feed continuity; template guard; varied manifestation; micro revision', () => {
    expect(FEED_SIGNATURE_COLOR_CONTINUITY_IMPLEMENTED).toBe(true);
    expect(LIME_TEMPLATE_REPETITION_GUARD_IMPLEMENTED).toBe(true);
    const feed = v23Result.experiment.feedSignatureColorContinuity!;
    expect(feed.allArtifactsContainSignatureLime).toBe(true);
    expect(feed.uniqueManifestationCount).toBeGreaterThan(3);
    expect(limeTemplateRepetitionFails({ ...feed, templateRepetitionDetected: true })).toBe(true);
    expect(feedSignatureColorContinuityPasses(feed)).toBe(true);
    expect(SIGNATURE_LIME_MICRO_REVISION_IMPLEMENTED).toBe(true);
    const rev = buildSignatureLimeRevision({
      parentFingerprint: 'parent',
      topicIndex: 3,
      accent: v23Result.artifacts[2]!.signatureLimeEvaluation!.accentSelection,
      migrationClass: 'MICRO_LIME_REVISION',
    });
    expect(rev.revisionType).toBe('SIGNATURE_LIME_REVISION');
    expect(rev.changeOnly.some((c) => c.includes('APOLOGY'))).toBe(true);
  });

  it('19–21. Round 01 gate; preserved gates; parent preserved on revision', () => {
    expect(ROUND_01_SIGNATURE_LIME_GATE_IMPLEMENTED).toBe(true);
    for (const a of v23Result.artifacts) {
      expect(signatureLimeGatePasses(a)).toBe(true);
      expect(artBoardMaterialityApprovalGatePasses(a)).toBe(true);
      expect(signatureLimeRevisionReady(a.signatureLimeEvaluation)).toBe(true);
    }
    expect(round01LockRequiresMaterialGate({
      v23Experiment: {
        ...v23Result.experiment,
        generatedArtifacts: v23Result.artifacts.map((a) => {
          const prompt = a.generationContract?.prompt ?? '';
          return {
            ...a,
            generationStatus: 'GENERATED' as const,
            generatedAssetUrl: 'url',
            selectedGenerationAssetId: 'lineage-test',
            generationAssets: [
              {
                assetId: 'lineage-test',
                url: 'url',
                promptSnapshotId: a.promptSnapshots?.[0]?.id ?? 'snap',
                lineageClassification: 'CURRENT' as const,
                assetGeneratedFromCurrentContract: true,
                assetIncludesC4A: prompt.includes('HUMAN-MADE MARKS'),
                assetIncludesC4B: prompt.includes('SIGNATURE LIME REQUIREMENT'),
                assetIncludesC4B1: prompt.includes('SIGNATURE LIME RESTRAINT + CHROMATIC ATTENTION'),
                assetIncludesC5: prompt.includes('PUBLIC AUTHORSHIP MODE'),
                assetUsesCurrentPublicCopy: prompt.includes('VISIBLE NDX HEADLINE'),
                assetUsesCurrentAuthorship: prompt.includes('FIRST-PERSON CHARACTER AUTHORSHIP'),
                assetUsesCurrentLabelQuarantine: prompt.includes('INTERNAL CONTRACT LABELS ARE NOT PUBLIC COPY'),
                createdAt: a.createdAt,
              },
            ],
          };
        }),
      },
    }).allowed).toBe(true);
  });

  it('22–26. Materiality + human-made + character preserved; generic trace; other clients optional', () => {
    expect(P0_5C_4_ART_BOARD_MATERIALITY_PRESERVED).toBe(true);
    expect(P0_5C_4A_HUMAN_MADE_MARK_SYSTEM_PRESERVED).toBe(true);
    expect(P0_5C_3_CHARACTER_RETENTION_PRESERVED).toBe(true);
    expect(ARTIFACT_MATERIALITY_SYSTEM_IMPLEMENTED).toBe(true);
    expect(NDX_HUMAN_MADE_MARK_SYSTEM_IMPLEMENTED).toBe(true);
    for (const a of v23Result.artifacts) {
      expect(v23PreservesC3Character(a.contract)).toBe(true);
    }
    expect(STUDIO_WORLD_SIGNATURE_BRAND_TRACE_GENERALIZED).toBe(true);
    expect(SIGNATURE_BRAND_TRACE_GENERALIZED).toBe(true);
    expect(NDX_SIGNATURE_BRAND_TRACE_REQUIREMENT.required).toBe(true);
    expect(NDX_SIGNATURE_BRAND_TRACE_REQUIREMENT.brandToken).toBe('NDX_SIGNATURE_LIME');
  });

  it('27–30. FAL prompt; no auto generation; board audit; founder judgments', () => {
    expect(FAL_MATERIAL_PROMPT_SECTION_ORDER.length).toBe(35);
    const fal = compileArtBoardMaterialityFalPrompt({ artifact: artifacts[2]!, contract: v23Result.artifacts[2]!.contract });
    expect(materialFalPromptHasSignatureLimeRequirement(fal)).toBe(true);
    expect(materialFalPromptDistinguishesSourceVsNdxColor(fal)).toBe(true);
    expect(fal.prompt).toContain(NDX_SIGNATURE_LIME);
    expect(fal.prompt).toContain('SIGNATURE LIME REQUIREMENT');
    expect(experiment01V23GeneratedByDefault()).toBe(false);
    expect(experiment01V23NotAutoGenerated()).toBe(true);
    expect(noPageLoadGeneration()).toBe(true);
    expect(V23B_FOUNDER_JUDGMENTS).toContain('MAKE_THIS_WORD_LIME');
    expect(V23B_FOUNDER_JUDGMENTS).toContain('MICRO_REVISION_ONLY');
    const migrations = v23Result.experiment.signatureLimeMigrations;
    expect(migrations.length).toBe(9);
  });
});
