/**
 * P0.5C.4A — Human-Made Mark System + Lime Intervention + Anti-AI (30 requirements)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import {
  NDX_HUMAN_MADE_MARK_SYSTEM_IMPLEMENTED,
  HAND_DRAWN_ICONOGRAPHY_SUPPORTED,
  GENERIC_PICTOGRAM_GUARD_IMPLEMENTED,
  ANTI_AI_ARTIFACT_EVALUATION_IMPLEMENTED,
  LIME_INTERVENTION_SYSTEM_IMPLEMENTED,
  LIME_DENSITY_GOVERNANCE_IMPLEMENTED,
  LIME_APPLICATION_MODE_IMPLEMENTED,
  MAKER_EVIDENCE_STRENGTH_IMPLEMENTED,
  SAME_HAND_CONSISTENCY_IMPLEMENTED,
  LIME_FEED_DISTANCE_EVALUATION_IMPLEMENTED,
  HAND_MARK_LEGIBILITY_IMPLEMENTED,
  FEED_MAKER_RHYTHM_IMPLEMENTED,
  P0_5C_4_ART_BOARD_MATERIALITY_PRESERVED,
  P0_5C_3_CHARACTER_RETENTION_PRESERVED,
  V2_3_HUMAN_MADE_REVISION_READY,
  HUMAN_MADE_MARK_CLASSES,
  V23A_FOUNDER_JUDGMENTS,
} from './artBoardMateriality/constants.js';
import {
  buildNdxHumanMadeMarkSystem,
  evaluateHumanMarkConsistency,
  genericPictogramFails,
  vectorIconLookFails,
  multipleHandStylesFail,
  humanMarkRequiresCausality,
  handDrawnIconRequiresSemanticReason,
  notEveryPostRequiresIcons,
  notEveryPostRequiresHandwriting,
} from './artBoardMateriality/humanMadeMarks.js';
import {
  buildNdxLimeInterventionSystem,
  evaluateLimeInterventionDensity,
  limeCanExceedTwoElementsWhenJustified,
  limeDensityIndependentFromRawCount,
  limeNotDecorativeOnly,
  evaluateLimeFeedDistance,
  limeInterventionPreservesHeadlineHierarchy,
} from './artBoardMateriality/limeIntervention.js';
import {
  evaluateAntiAIGeneratedArtifact,
  evaluateHandMarkLegibility,
  evaluateMakerEvidenceStrength,
  machineGeneratedBlocked,
  fakeHandwritingFails,
  machinePerfectMicrodetailFails,
} from './artBoardMateriality/antiAiEvaluation.js';
import { buildFeedMakerRhythm, feedMakerRhythmPreventsIdenticalDoodles } from './artBoardMateriality/makerRhythm.js';
import {
  applyV23HumanMadeRevision,
  v23ParentFingerprintPreserved,
  v23HumanMadeRevisionReady,
} from './artBoardMateriality/v23HumanMadeRevision.js';
import {
  compileArtBoardMaterialityFalPrompt,
  materialFalPromptHasHumanMadeSection,
  materialFalPromptHasAntiAiConstraints,
} from './artBoardMateriality/falPromptCompilerV23.js';
import {
  formulateExperiment01V23,
  v23PreservesC3Character,
  v23PreservesC1Hierarchy,
  experiment01V23GeneratedByDefault,
} from './artBoardMateriality/experiment01V23.js';
import { ARTIFACT_MATERIALITY_SYSTEM_IMPLEMENTED } from './artBoardMateriality/constants.js';
import { CHARACTER_RETENTION_SYSTEM_IMPLEMENTED } from './characterRetention/constants.js';
import { CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED } from './culturalVisualParticipation/constants.js';
import { formulateExperiment01V2 } from './editorialInformationArchitecture/experiment01V2.js';
import { formulateExperiment01V21 } from './culturalVisualParticipation/experiment01V21.js';
import { formulateExperiment01V22 } from './characterRetention/experiment01V22.js';
import { formulateExperiment01Artifacts } from './brandMarketingExpression/characterEventFormulation.js';
import { compileBrandMarketingExpressionSystem } from './brandMarketingExpression/marketingExpressionCompiler.js';
import { buildVitestBrandCharacterSystemForMarketing } from './brandMarketingExpression/vitestFixtures.js';
import { buildFounderMarketingNorthStarArtifact } from './brandMarketingExpression/northStarArtifact.js';
import {
  noPageLoadGeneration,
  experiment01V23NotAutoGenerated,
  resetBrandMarketingExpressionWorkers,
  prepareBrandMarketingExpression,
  compileBrandMarketingExpression,
  formulateMarketingExpressionExperiment01,
  formulateMarketingExpressionExperiment01V2,
  formulateMarketingExpressionExperiment01V21,
  formulateMarketingExpressionExperiment01V22,
  formulateMarketingExpressionExperiment01V23,
} from '../../api/_lib/site00Evolve/creativeDirection/brandMarketingExpressionExperiment/brandMarketingExpressionService.js';

describe('P0.5C.4A Human-Made Mark + Lime Intervention', () => {
  const characterSystem = buildVitestBrandCharacterSystemForMarketing();
  const expressionSystem = compileBrandMarketingExpressionSystem({
    characterSystem,
    northStarId: buildFounderMarketingNorthStarArtifact('ndxbook').id,
    projectId: 'ndxbook',
  });
  const { artifacts } = formulateExperiment01Artifacts({
    expressionSystem,
    characterSystemId: characterSystem.id,
  });
  let v23Result: ReturnType<typeof formulateExperiment01V23>;

  beforeAll(() => {
    const v2 = formulateExperiment01V2({
      v1Artifacts: artifacts,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    const v21 = formulateExperiment01V21({
      v1Artifacts: artifacts,
      v2Experiment: v2.experiment,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    const v22 = formulateExperiment01V22({
      v1Artifacts: artifacts,
      v21Experiment: v21.experiment,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    v23Result = formulateExperiment01V23({
      v1Artifacts: artifacts,
      v22Experiment: v22.experiment,
      expressionSystem,
    });
  });

  it('1–3. Human-made mark system exists; hand-drawn icons; generic pictograms fail', () => {
    expect(NDX_HUMAN_MADE_MARK_SYSTEM_IMPLEMENTED).toBe(true);
    expect(HAND_DRAWN_ICONOGRAPHY_SUPPORTED).toBe(true);
    expect(HUMAN_MADE_MARK_CLASSES).toContain('HAND_DRAWN_ICON');
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    expect(topic1.humanMadeEvaluation?.markSystem.handDrawnIcons.length).toBeGreaterThan(0);
    expect(genericPictogramFails(true)).toBe(true);
  });

  it('4–5. Vector icon look fails; same-hand consistency evaluated', () => {
    expect(GENERIC_PICTOGRAM_GUARD_IMPLEMENTED).toBe(true);
    expect(SAME_HAND_CONSISTENCY_IMPLEMENTED).toBe(true);
    expect(vectorIconLookFails(true)).toBe(true);
    const topic1 = v23Result.artifacts[0]!;
    const consistency = topic1.humanMadeEvaluation!.humanMarkConsistency;
    expect(consistency.sameStrokeFamily).toBe(true);
    expect(multipleHandStylesFail({ ...consistency, result: 'MIXED_STYLES' })).toBe(true);
  });

  it('6–9. Lime intervention system; not decorative-only; exceeds two when justified; density independent', () => {
    expect(LIME_INTERVENTION_SYSTEM_IMPLEMENTED).toBe(true);
    expect(LIME_DENSITY_GOVERNANCE_IMPLEMENTED).toBe(true);
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    const lime = topic1.humanMadeEvaluation!.limeIntervention;
    expect(limeNotDecorativeOnly(lime)).toBe(true);
    expect(limeCanExceedTwoElementsWhenJustified(lime)).toBe(true);
    expect(limeDensityIndependentFromRawCount({ elementCount: 5, semanticallyJustifiedCount: 5 })).toBe(true);
    expect(evaluateLimeInterventionDensity({ limeIntervention: lime })).toMatch(/MODERATE|STRONG/);
  });

  it('10–12. Lime application mode; marker/highlighter; maker evidence strength', () => {
    expect(LIME_APPLICATION_MODE_IMPLEMENTED).toBe(true);
    expect(MAKER_EVIDENCE_STRENGTH_IMPLEMENTED).toBe(true);
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    expect(topic1.humanMadeEvaluation!.limeIntervention.applicationModes).toContain('MARKER');
    expect(topic1.humanMadeEvaluation!.makerEvidenceStrength).toBe('STRONG');
  });

  it('13–15. Machine-perfect detail; fake handwriting; multiple hand styles fail', () => {
    expect(ANTI_AI_ARTIFACT_EVALUATION_IMPLEMENTED).toBe(true);
    expect(machinePerfectMicrodetailFails(true)).toBe(true);
    expect(fakeHandwritingFails(true)).toBe(true);
    expect(multipleHandStylesFail({ result: 'MIXED_STYLES', sameStrokeFamily: false, mixedIconSystems: true } as never)).toBe(true);
  });

  it('16–17. Human marks require causality; hand-drawn icons require semantic reason', () => {
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    const mark = topic1.humanMadeEvaluation!.markSystem.marks[0]!;
    expect(humanMarkRequiresCausality(mark)).toBe(true);
    const icon = topic1.humanMadeEvaluation!.markSystem.handDrawnIcons[0]!;
    expect(handDrawnIconRequiresSemanticReason(icon)).toBe(true);
  });

  it('18–20. Feed-distance lime; hand-mark legibility; lime does not override headline', () => {
    expect(LIME_FEED_DISTANCE_EVALUATION_IMPLEMENTED).toBe(true);
    expect(HAND_MARK_LEGIBILITY_IMPLEMENTED).toBe(true);
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    expect(['CLEAR', 'SUBTLE_BUT_PRESENT']).toContain(topic1.humanMadeEvaluation!.limeFeedDistance.result);
    expect(topic1.humanMadeEvaluation!.handMarkLegibility.feedRhythmContribution).toBe(true);
    expect(limeInterventionPreservesHeadlineHierarchy(topic1.humanMadeEvaluation!.markSystem)).toBe(true);
  });

  it('21–23. Feed maker rhythm; not every post needs icons or handwriting', () => {
    expect(FEED_MAKER_RHYTHM_IMPLEMENTED).toBe(true);
    const rhythm = v23Result.experiment.feedMakerRhythm!;
    expect(feedMakerRhythmPreventsIdenticalDoodles(rhythm)).toBe(true);
    const withIcons = v23Result.artifacts.filter((a) => (a.humanMadeEvaluation?.markSystem.handDrawnIcons.length ?? 0) > 0);
    expect(notEveryPostRequiresIcons(withIcons.map((_, i) => i))).toBe(true);
    expect(notEveryPostRequiresHandwriting([2, 8])).toBe(true);
  });

  it('24–27. P0.5C.4 preserved; P0.5C.3 preserved; density controlled; cultural imagery preserved', () => {
    expect(P0_5C_4_ART_BOARD_MATERIALITY_PRESERVED).toBe(true);
    expect(P0_5C_3_CHARACTER_RETENTION_PRESERVED).toBe(true);
    expect(ARTIFACT_MATERIALITY_SYSTEM_IMPLEMENTED).toBe(true);
    expect(CHARACTER_RETENTION_SYSTEM_IMPLEMENTED).toBe(true);
    expect(CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED).toBe(true);
    for (const a of v23Result.artifacts) {
      expect(v23PreservesC3Character(a.contract)).toBe(true);
      expect(v23PreservesC1Hierarchy(a.contract)).toBe(true);
      expect(a.materialityEvaluation.passesApprovalGate).toBe(true);
    }
  });

  it('28–30. FAL founder-triggered; no page load generation; V2.3 parent immutable', () => {
    expect(experiment01V23GeneratedByDefault()).toBe(false);
    expect(experiment01V23NotAutoGenerated()).toBe(true);
    expect(noPageLoadGeneration()).toBe(true);
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    expect(topic1.parentFingerprint).toBeTruthy();
    expect(v23ParentFingerprintPreserved(topic1.humanMadeRevision!, topic1.parentFingerprint!)).toBe(true);
    expect(topic1.fingerprint).not.toBe(topic1.parentFingerprint);
  });

  it('FAL prompt includes human-made + anti-AI sections', () => {
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    const fal = compileArtBoardMaterialityFalPrompt({
      artifact: artifacts[0]!,
      contract: topic1.contract,
    });
    expect(materialFalPromptHasHumanMadeSection(fal)).toBe(true);
    expect(materialFalPromptHasAntiAiConstraints(fal)).toBe(true);
    expect(fal.prompt).toContain('HAND-DRAWN');
    expect(fal.negativePrompt).toContain('vector icon library');
  });

  it('V2.3 human-made revision ready + founder judgments', () => {
    expect(V2_3_HUMAN_MADE_REVISION_READY).toBe(true);
    expect(V23A_FOUNDER_JUDGMENTS).toContain('MAKE_ICONS_HAND_DRAWN');
    expect(V23A_FOUNDER_JUDGMENTS).toContain('THATS_NDX');
    const topic1 = v23Result.artifacts.find((a) => a.id === 'bma-exp01-v23-1')!;
    expect(v23HumanMadeRevisionReady(topic1.humanMadeEvaluation)).toBe(true);
    expect(machineGeneratedBlocked(topic1.humanMadeEvaluation!.antiAi)).toBe(false);
  });

  it('Service formulate path integrates human-made revision', async () => {
    resetBrandMarketingExpressionWorkers();
    await prepareBrandMarketingExpression({ projectId: 'ndxbook-p05c4a' });
    await compileBrandMarketingExpression({ projectId: 'ndxbook-p05c4a' });
    await formulateMarketingExpressionExperiment01({ projectId: 'ndxbook-p05c4a' });
    await formulateMarketingExpressionExperiment01V2({ projectId: 'ndxbook-p05c4a' });
    await formulateMarketingExpressionExperiment01V21({ projectId: 'ndxbook-p05c4a' });
    await formulateMarketingExpressionExperiment01V22({ projectId: 'ndxbook-p05c4a' });
    const v23 = await formulateMarketingExpressionExperiment01V23({ projectId: 'ndxbook-p05c4a' });
    expect(v23.experiment01V23?.generatedArtifacts.length).toBe(9);
    expect(v23.experiment01V23?.feedMakerRhythm).toBeTruthy();
    expect(v23.experiment01V23?.generatedArtifacts[0]?.humanMadeEvaluation).toBeTruthy();
  });
});
