/**
 * P0.5C.3 — Character Retention + Controlled Misbehavior + Humor Reinjection (61 requirements)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  CHARACTER_RETENTION_SYSTEM_IMPLEMENTED,
  INFORMATION_VS_CHARACTER_DENSITY_SEPARATED,
  CHARACTER_BEAT_IMPLEMENTED,
  COMPRESSION_CHARACTER_SAFETY_IMPLEMENTED,
  HUMOR_REINJECTION_IMPLEMENTED,
  PUNCHLINE_PRESERVATION_IMPLEMENTED,
  CONTROLLED_MISBEHAVIOR_IMPLEMENTED,
  HUMAN_TRACE_STRENGTH_IMPLEMENTED,
  STERILITY_EVALUATION_IMPLEMENTED,
  CLEAR_VS_STERILE_DISTINCTION_IMPLEMENTED,
  LOGO_REMOVAL_CHARACTER_RECOGNITION_IMPLEMENTED,
  FEED_CHARACTER_RHYTHM_IMPLEMENTED,
  FEED_HUMOR_RHYTHM_IMPLEMENTED,
  P0_5C_1_INFORMATION_HIERARCHY_PRESERVED,
  P0_5C_1_TYPOGRAPHY_GOVERNANCE_PRESERVED,
  P0_5C_2_CULTURAL_VISUAL_GOVERNANCE_PRESERVED,
  EXPERIMENT_01_V2_1_PRESERVED,
  EXPERIMENT_01_V2_2_CHARACTER_RETENTION_PIPELINE_READY,
  P0_5E_ROUND_01_CHARACTER_GATE_INTEGRATED,
  CONTENT_OPERATIONS_CHARACTER_RETENTION_INTEGRATED,
  FAL_CHARACTER_PROMPT_SECTION_ORDER,
  V22_FOUNDER_JUDGMENTS,
  HUMOR_ELIGIBILITY,
  CHARACTER_BEAT_TYPES,
} from './characterRetention/constants.js';
import {
  buildCharacterRetentionContract,
  characterBeatExplicitlyFormulated,
  sparseMayHaveStrongCharacterDensity,
  controlledMisbehaviorRequiresCausality,
} from './characterRetention/characterRetentionContract.js';
import {
  evaluateCharacterDensity,
  evaluateCompressionCharacterSafety,
  evaluatePunchlinePreservation,
  evaluateHeadlineCharacter,
  evaluateArtifactSterility,
  evaluateClarityVsSterility,
  evaluateLogoRemovalCharacter,
  evaluateMisbehaviorBudget,
  evaluateImageCarriesCharacter,
  buildCharacterRetentionEvaluation,
  characterLossAfterCompressionFails,
  clearButSterileDistinctFromClearAndAlive,
  pettinessCannotPunchDown,
  genericWitInsufficient,
} from './characterRetention/evaluations.js';
import {
  buildFeedCharacterRhythm,
  buildFeedHumorRhythm,
  everyPostIsJokeFails,
  noHumorWhereRequiredFails,
} from './characterRetention/feedRhythm.js';
import { compileCharacterRetentionFalPrompt } from './characterRetention/falPromptCompilerV22.js';
import {
  formulateExperiment01V22,
  v22ContractReviewBeforeGeneration,
  v21HistoryNotMutated,
  v22KeepsSameNineTopics,
  v22PreservesC1Hierarchy,
  v22PreservesC2Imagery,
  experiment01V22GeneratedByDefault,
} from './characterRetention/experiment01V22.js';
import {
  characterRetentionApprovalGatePasses,
  round01LockRequiresCharacterRetentionGate,
  slide02InheritsCharacterNotJoke,
} from './characterRetention/approvalGate.js';
import {
  contentOperationsRequiresCharacterRetentionContract,
  contentOperationsBypassCharacterRetentionBlocked,
  performanceLearningCannotMutateHumorAutomatically,
  platformDerivationConsumesCharacterPayload,
  brandCharacterImmutable,
  brandCanonUnchanged,
  experimentFImmutable,
  experimentGImmutable,
  productExpressionBlocked,
  worldFormationBlocked,
} from './characterRetention/integration.js';
import { evaluateNorthStarCharacterRetention } from './characterRetention/northStarCharacterForensics.js';
import { EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED } from './editorialInformationArchitecture/constants.js';
import { CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED } from './culturalVisualParticipation/constants.js';
import { formulateExperiment01V2 } from './editorialInformationArchitecture/experiment01V2.js';
import { formulateExperiment01V21 } from './culturalVisualParticipation/experiment01V21.js';
import { ndxAuthoredCopyIsUppercase } from './editorialInformationArchitecture/typographyGovernance.js';
import { formulateExperiment01Artifacts } from './brandMarketingExpression/characterEventFormulation.js';
import { compileBrandMarketingExpressionSystem } from './brandMarketingExpression/marketingExpressionCompiler.js';
import { buildVitestBrandCharacterSystemForMarketing } from './brandMarketingExpression/vitestFixtures.js';
import { buildFounderMarketingNorthStarArtifact } from './brandMarketingExpression/northStarArtifact.js';
import { buildSocialContentPackage } from './contentOperations/contentPackage.js';
import { seedPilotOpportunities } from './contentOperations/opportunityEngine.js';
import { selectChannelForOpportunity, selectFormatForOpportunity } from './contentOperations/channelFormatSelection.js';
import {
  noPageLoadGeneration,
  providerGenerationRequiresFounderTrigger,
  experiment01V22NotAutoGenerated,
  resetBrandMarketingExpressionWorkers,
  prepareBrandMarketingExpression,
  compileBrandMarketingExpression,
  formulateMarketingExpressionExperiment01,
  formulateMarketingExpressionExperiment01V2,
  formulateMarketingExpressionExperiment01V21,
  formulateMarketingExpressionExperiment01V22,
  formulateMarketingExpressionExperiment01V23,
  generateAllExperiment01V22ArtifactAssets,
  getBrandMarketingExpressionState,
} from '../../api/_lib/site00Evolve/creativeDirection/brandMarketingExpressionExperiment/brandMarketingExpressionService.js';
import { lockCampaignRound01 as lockRound01Service, initializeCampaignBoardFromExperiment01 } from '../../api/_lib/site00Evolve/marketingCampaignProduction/marketingCampaignProductionService.js';

const ROOT = join(process.cwd());

describe('P0.5C.3 Character Retention', () => {
  const characterSystem = buildVitestBrandCharacterSystemForMarketing();
  const northStar = buildFounderMarketingNorthStarArtifact('ndxbook');
  const expressionSystem = compileBrandMarketingExpressionSystem({
    characterSystem,
    northStarId: northStar.id,
    projectId: 'ndxbook',
  });
  const { artifacts } = formulateExperiment01Artifacts({
    expressionSystem,
    characterSystemId: characterSystem.id,
  });

  let v21Result: ReturnType<typeof formulateExperiment01V21>;
  let v22Result: ReturnType<typeof formulateExperiment01V22>;

  beforeAll(() => {
    const v2 = formulateExperiment01V2({
      v1Artifacts: artifacts,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    v21Result = formulateExperiment01V21({
      v1Artifacts: artifacts,
      v2Experiment: v2.experiment,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    v22Result = formulateExperiment01V22({
      v1Artifacts: artifacts,
      v21Experiment: v21Result.experiment,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
  });

  it('1-3. P0.5C / C.1 / C.2 remain valid', () => {
    expect(CHARACTER_RETENTION_SYSTEM_IMPLEMENTED).toBe(true);
    expect(EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED).toBe(true);
    expect(CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED).toBe(true);
    expect(P0_5C_1_INFORMATION_HIERARCHY_PRESERVED).toBe(true);
    expect(P0_5C_2_CULTURAL_VISUAL_GOVERNANCE_PRESERVED).toBe(true);
  });

  it('4-8. Information vs character density separation', () => {
    expect(INFORMATION_VS_CHARACTER_DENSITY_SEPARATED).toBe(true);
    const contract = v22Result.artifacts[0]!.contract.characterRetention;
    const density = evaluateCharacterDensity({
      artifactId: 'bma-exp01-v22-1',
      textDensity: 'SPARSE',
      contract,
    });
    expect(density.independent).toBe(true);
    expect(sparseMayHaveStrongCharacterDensity('SPARSE', density.characterDensity)).toBe(true);
    expect(characterBeatExplicitlyFormulated(contract.primaryCharacterBeat)).toBe(true);
    expect(CHARACTER_BEAT_TYPES).toContain(contract.primaryCharacterBeat.beatType);
  });

  it('9-12. Humor eligibility + Brand Character authority', () => {
    expect(HUMOR_REINJECTION_IMPLEMENTED).toBe(true);
    expect(HUMOR_ELIGIBILITY).toContain('INAPPROPRIATE');
    const serious = v22Result.artifacts.find((a) => a.contract.characterRetention.humorEligibility === 'NOT_NEEDED');
    expect(serious).toBeTruthy();
    expect(genericWitInsufficient('OBSERVATIONAL_UNDERSTATEMENT')).toBe(true);
  });

  it('13-17. Punchline preservation + compression safety', () => {
    expect(PUNCHLINE_PRESERVATION_IMPLEMENTED).toBe(true);
    expect(COMPRESSION_CHARACTER_SAFETY_IMPLEMENTED).toBe(true);
    const artifact = v22Result.artifacts[0]!;
    const pp = evaluatePunchlinePreservation({
      artifactId: artifact.id,
      contract: artifact.contract.characterRetention,
      sourcePunchline: artifact.contract.primaryTrace,
    });
    expect(pp.silentlyRemoved).toBe(false);
    const evaln = buildCharacterRetentionEvaluation({
      artifactId: artifact.id,
      textDensity: artifact.contract.textDensity.level,
      contract: artifact.contract.characterRetention,
      v21Contract: v21Result.experiment.amendedContracts[0]!,
      sourcePunchline: artifact.contract.primaryTrace,
    });
    expect(characterLossAfterCompressionFails(evaln)).toBe(false);
  });

  it('18-21. Controlled misbehavior + causality', () => {
    expect(CONTROLLED_MISBEHAVIOR_IMPLEMENTED).toBe(true);
    const withMisbehavior = v22Result.artifacts.find((a) => a.contract.characterRetention.controlledMisbehavior.length > 0);
    expect(withMisbehavior).toBeTruthy();
    for (const m of withMisbehavior!.contract.characterRetention.controlledMisbehavior) {
      expect(controlledMisbehaviorRequiresCausality(m)).toBe(true);
    }
    const budget = evaluateMisbehaviorBudget(withMisbehavior!.contract.characterRetention);
    expect(['SUFFICIENT', 'NONE_NEEDED', 'TOO_CLEAN']).toContain(budget);
  });

  it('22-27. Human trace + typography + uppercase', () => {
    expect(HUMAN_TRACE_STRENGTH_IMPLEMENTED).toBe(true);
    expect(P0_5C_1_TYPOGRAPHY_GOVERNANCE_PRESERVED).toBe(true);
    for (const a of v22Result.artifacts) {
      const beat = a.contract.characterRetention.primaryCharacterBeat.text;
      if (beat) expect(beat).toBe(beat.toUpperCase());
      expect(ndxAuthoredCopyIsUppercase(a.contract.typographyAssignments)).toBe(true);
    }
    const headline = evaluateHeadlineCharacter({ artifactId: 'x', headline: 'WHY DOES EVERYTHING HAVE A SUBSCRIPTION NOW?' });
    expect(headline.result).toBe('NDX_STRONG');
  });

  it('28-33. Sterility + clarity vs sterility + logo removal', () => {
    expect(STERILITY_EVALUATION_IMPLEMENTED).toBe(true);
    expect(CLEAR_VS_STERILE_DISTINCTION_IMPLEMENTED).toBe(true);
    expect(LOGO_REMOVAL_CHARACTER_RECOGNITION_IMPLEMENTED).toBe(true);
    expect(clearButSterileDistinctFromClearAndAlive()).toBe(true);
    const artifact = v22Result.artifacts[0]!;
    const evaln = artifact.characterEvaluation;
    expect(evaln.sterility.level).not.toBe('CORPORATE');
    expect(evaln.logoRemovalCharacter.dependsOnLime).toBe(false);
    expect(evaln.logoRemovalCharacter.dependsOnLogo).toBe(false);
  });

  it('34-37. Feed character + humor rhythm', () => {
    expect(FEED_CHARACTER_RHYTHM_IMPLEMENTED).toBe(true);
    expect(FEED_HUMOR_RHYTHM_IMPLEMENTED).toBe(true);
    expect(v22Result.experiment.feedCharacterRhythm?.variationAdequate).toBe(true);
    expect(v22Result.experiment.feedHumorRhythm?.everyPostIsJoke).toBe(false);
    expect(everyPostIsJokeFails({ everyPostIsJoke: true })).toBe(true);
    expect(noHumorWhereRequiredFails({ noHumorWhereRequired: true })).toBe(true);
  });

  it('38-40. Visual punchline + pettiness + cultural shorthand', () => {
    const imageEval = evaluateImageCarriesCharacter(v22Result.artifacts[0]!.contract);
    expect(['YES_STRONGLY', 'YES_PARTIALLY', 'NO']).toContain(imageEval);
    expect(pettinessCannotPunchDown('PLAYFUL')).toBe(true);
    expect(pettinessCannotPunchDown('TOO_FAR')).toBe(false);
    expect(v22Result.artifacts[0]!.contract.characterRetention.culturalShorthandAllowed).toBe(true);
  });

  it('41-42. Microcopy budget', () => {
    expect(v22Result.artifacts[0]!.contract.characterRetention.microcopyBudget).toBeLessThanOrEqual(2);
  });

  it('43-47. V2.1 preserved + V2.2 lineage + same topics + C.1/C.2 preserved', () => {
    expect(EXPERIMENT_01_V2_1_PRESERVED).toBe(true);
    expect(v21HistoryNotMutated()).toBe(true);
    expect(EXPERIMENT_01_V2_2_CHARACTER_RETENTION_PIPELINE_READY).toBe(true);
    expect(v22KeepsSameNineTopics(v22Result.artifacts)).toBe(true);
    expect(v22PreservesC1Hierarchy(v22Result.artifacts[0]!.contract)).toBe(true);
    expect(v22PreservesC2Imagery(v22Result.artifacts[0]!.contract)).toBe(true);
  });

  it('48-49. FAL founder-triggered + no page load generation', () => {
    expect(experiment01V22GeneratedByDefault()).toBe(false);
    expect(experiment01V22NotAutoGenerated()).toBe(true);
    expect(noPageLoadGeneration()).toBe(true);
    expect(providerGenerationRequiresFounderTrigger()).toBe(true);
    expect(FAL_CHARACTER_PROMPT_SECTION_ORDER.length).toBe(28);
    const prompt = compileCharacterRetentionFalPrompt({
      artifact: artifacts[0]!,
      contract: v22Result.artifacts[0]!.contract,
    });
    expect(prompt.prompt).toContain('STERILITY GUARD');
    expect(prompt.prompt).toContain('NOT A PERFECT BRAND TEMPLATE');
  });

  it('50-52. P0.5E gate + content ops + performance learning', () => {
    expect(P0_5E_ROUND_01_CHARACTER_GATE_INTEGRATED).toBe(true);
    expect(CONTENT_OPERATIONS_CHARACTER_RETENTION_INTEGRATED).toBe(true);
    expect(round01LockRequiresCharacterRetentionGate({ v22Experiment: null }).allowed).toBe(false);
    expect(contentOperationsBypassCharacterRetentionBlocked(null)).toBe(true);
    expect(performanceLearningCannotMutateHumorAutomatically()).toBe(true);
    expect(platformDerivationConsumesCharacterPayload()).toBe(true);
    expect(slide02InheritsCharacterNotJoke()).toBe(true);
  });

  it('53-58. Experimental integrity', () => {
    expect(brandCharacterImmutable()).toBe(true);
    expect(brandCanonUnchanged()).toBe(true);
    expect(experimentFImmutable()).toBe(true);
    expect(experimentGImmutable()).toBe(true);
    expect(productExpressionBlocked()).toBe(false);
    expect(worldFormationBlocked()).toBe(false);
  });

  it('59. Content package carries character retention contract', () => {
    const opp = seedPilotOpportunities('ndxbook')[0]!;
    const channel = selectChannelForOpportunity(opp);
    const format = selectFormatForOpportunity(opp, channel);
    const pkg = buildSocialContentPackage({
      projectId: 'ndxbook',
      opportunity: opp,
      channel,
      format,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    expect(contentOperationsRequiresCharacterRetentionContract({ id: 'crc-test' } as never)).toBe(true);
    expect(pkg.characterRetentionContractId).toBeTruthy();
  });

  it('60. Service integration: formulate V2.2 + lock gate', async () => {
    resetBrandMarketingExpressionWorkers();
    await prepareBrandMarketingExpression({ projectId: 'ndxbook' });
    await compileBrandMarketingExpression({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V2({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V21({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V22({ projectId: 'ndxbook' });
    const v22Run = await getBrandMarketingExpressionState({ projectId: 'ndxbook' });
    expect(v22Run!.experiment01V22?.generatedArtifacts.length).toBe(9);
    expect(v22ContractReviewBeforeGeneration(v22Run!.experiment01V22!)).toBe(true);

    await formulateMarketingExpressionExperiment01V23({ projectId: 'ndxbook' });

    await initializeCampaignBoardFromExperiment01({ projectId: 'ndxbook' });
    await expect(lockRound01Service({ projectId: 'ndxbook' })).rejects.toThrow(/V2\.3|materiality|art-board/i);

    await generateAllExperiment01V22ArtifactAssets({ projectId: 'ndxbook' });
    const freshRun = await getBrandMarketingExpressionState({ projectId: 'ndxbook' });
    for (const a of freshRun!.experiment01V22!.generatedArtifacts) {
      expect(a.generationStatus).toBe('GENERATED');
      expect(characterRetentionApprovalGatePasses(a)).toBe(true);
    }
    const gate = round01LockRequiresCharacterRetentionGate({ v22Experiment: freshRun!.experiment01V22 });
    expect(gate.allowed).toBe(true);
  });

  it('61. UI + routes wired', () => {
    const page = readFileSync(join(ROOT, 'src/site00/pages/ProjectBrandMarketingExpressionExperiment01Page.tsx'), 'utf8');
    const api = readFileSync(join(ROOT, 'src/site00/services/site00ProjectsApi.ts'), 'utf8');
    expect(page).toContain('V2.2 — CHARACTER RETENTION');
    expect(page).toContain('PRIMARY CHARACTER BEAT');
    expect(V22_FOUNDER_JUDGMENTS.length).toBeGreaterThanOrEqual(18);
    expect(api).toContain('marketing_expression_experiment_01_v22_formulate');
    expect(evaluateNorthStarCharacterRetention(northStar).classification).toBe('CHARACTER_RETENTION_CALIBRATION');
  });
});
