/**
 * P0.5C.2 — Cultural Image Participation + Visual Subject Matter Governance (53 requirements)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import {
  CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED,
  VISUAL_SUBJECT_MATTER_GOVERNANCE_IMPLEMENTED,
  CULTURAL_VISUAL_EVIDENCE_IMPLEMENTED,
  ARTISTIC_EVIDENCE_IMPLEMENTED,
  IMAGE_PARTICIPATION_DECISION_IMPLEMENTED,
  CULTURAL_ACCOMPLICE_VISUAL_EVALUATION_IMPLEMENTED,
  VISUAL_APPETITE_EVALUATION_IMPLEMENTED,
  PLAYFULNESS_EVALUATION_IMPLEMENTED,
  FEED_CULTURAL_RHYTHM_IMPLEMENTED,
  FEED_EMOTIONAL_RHYTHM_IMPLEMENTED,
  TEXT_DOMINANT_FEED_GUARD_IMPLEMENTED,
  DOCUMENT_DOMINANT_FEED_GUARD_IMPLEMENTED,
  RANDOM_CULTURAL_REFERENCE_GUARD_IMPLEMENTED,
  GENERATED_IMAGE_EVIDENCE_BOUNDARY_IMPLEMENTED,
  P0_5C_1_EDITORIAL_HIERARCHY_PRESERVED,
  EXPERIMENT_01_CULTURAL_VISUAL_PIPELINE_READY,
  CONTENT_OPERATIONS_VISUAL_SUBJECT_MATTER_INTEGRATED,
  CULTURAL_VISUAL_EVIDENCE_CLASSES,
  CULTURAL_VISUAL_ROLES,
  VISUAL_PARTICIPATION_MODES,
  FAL_CULTURAL_PROMPT_SECTION_ORDER,
} from './culturalVisualParticipation/constants.js';
import {
  buildVisualSubjectMatterDecision,
  buildCulturalVisualEvidence,
  getTopicVisualProfile,
  imageDominantSupported,
  typographyDominantRemainsSupported,
  decorativeOnlyCulturalImageFails,
  randomCelebrityImageFails,
  imageParticipationDecisionExistsBeforeGeneration,
} from './culturalVisualParticipation/visualSubjectMatter.js';
import {
  evaluateVisualAppetite,
  evaluateCulturalAccomplice,
  evaluatePlayfulness,
  evaluateReferenceDensity,
  visualAppetiteEvaluated,
  culturalImageryNotMandatoryForEveryArtifact,
  buildArtisticEvidence,
  artisticEvidenceDistinctFromFactual,
  generatedIllustrationCannotBeFactual,
  evaluateAmendedContract,
} from './culturalVisualParticipation/visualEvaluation.js';
import {
  buildFeedCulturalRhythm,
  buildFeedEmotionalRhythm,
  evaluateBoardVisualDiversity,
  textDominantFeedGuard,
  documentDominantFeedGuard,
  inferVisualParticipationBalance,
  buildImageLedReadingPath,
} from './culturalVisualParticipation/feedRhythm.js';
import { evaluateNorthStarCulturalParticipation, northStarCulturalNotFinalIdentity } from './culturalVisualParticipation/northStarCulturalForensics.js';
import { compileCulturalFalPrompt, culturalFalPromptUpdated } from './culturalVisualParticipation/falPromptCompilerV21.js';
import {
  formulateExperiment01V21,
  v21ContractReviewBeforeGeneration,
  experiment01CulturalVisualsGeneratedByDefault,
  v2HistoryNotMutated,
  sameTopicsUnchanged,
  hierarchyCorrectionsPreserved,
  uppercaseGovernancePreserved,
} from './culturalVisualParticipation/experiment01V21.js';
import {
  evaluateOpportunityVisualPotential,
  buildContentPackageVisualSubjectLayer,
  contentOperationsVisualSubjectIntegrated,
  imageParticipationCannotBypassEditorialDecision,
  experimentFImmutable,
  experimentGNotReevaluated,
  brandCharacterImmutable,
  brandCanonUnchanged,
  productExpressionBlocked,
  worldFormationBlocked,
  p05c1HierarchyPreserved,
  limeGovernancePreserved,
} from './culturalVisualParticipation/integration.js';
import {
  EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED,
  NDX_UPPERCASE_ONLY_AUTHORED_COPY_ENFORCED,
} from './editorialInformationArchitecture/constants.js';
import { formulateExperiment01V2, experiment01V1Preserved } from './editorialInformationArchitecture/experiment01V2.js';
import { ndxAuthoredCopyIsUppercase } from './editorialInformationArchitecture/typographyGovernance.js';
import {
  formulateExperiment01Artifacts,
  EXPERIMENT_01_TOPIC_SPECS,
} from './brandMarketingExpression/characterEventFormulation.js';
import { compileBrandMarketingExpressionSystem } from './brandMarketingExpression/marketingExpressionCompiler.js';
import { buildVitestBrandCharacterSystemForMarketing } from './brandMarketingExpression/vitestFixtures.js';
import { buildFounderMarketingNorthStarArtifact } from './brandMarketingExpression/northStarArtifact.js';
import {
  noPageLoadGeneration,
  providerGenerationRequiresFounderTrigger,
  experiment01V21NotAutoGenerated,
  generateAllExperiment01V21ArtifactAssets,
  resetBrandMarketingExpressionWorkers,
  prepareBrandMarketingExpression,
  compileBrandMarketingExpression,
  formulateMarketingExpressionExperiment01,
  formulateMarketingExpressionExperiment01V2,
  formulateMarketingExpressionExperiment01V21,
} from '../../api/_lib/site00Evolve/creativeDirection/brandMarketingExpressionExperiment/brandMarketingExpressionService.js';
import { buildSocialContentPackage } from './contentOperations/contentPackage.js';
import { seedPilotOpportunities } from './contentOperations/opportunityEngine.js';
import { selectChannelForOpportunity, selectFormatForOpportunity } from './contentOperations/channelFormatSelection.js';

describe('P0.5C.2 Cultural Visual Participation', () => {
  const characterSystem = buildVitestBrandCharacterSystemForMarketing();
  const northStar = buildFounderMarketingNorthStarArtifact('ndxbook');
  const expressionSystem = compileBrandMarketingExpressionSystem({
    characterSystem,
    northStarId: northStar.id,
    projectId: 'ndxbook',
  });
  const { artifacts, theses } = formulateExperiment01Artifacts({
    expressionSystem,
    characterSystemId: characterSystem.id,
  });
  const artifact = artifacts[0]!;
  const thesis = theses[0]!;
  const spec = EXPERIMENT_01_TOPIC_SPECS[0]!;

  let v2Result: ReturnType<typeof formulateExperiment01V2>;
  let v21Result: ReturnType<typeof formulateExperiment01V21>;

  beforeAll(() => {
    v2Result = formulateExperiment01V2({
      v1Artifacts: artifacts,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    v21Result = formulateExperiment01V21({
      v1Artifacts: artifacts,
      v2Experiment: v2Result.experiment,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
  });

  it('1. P0.5C remains valid', () => {
    expect(expressionSystem.status).toBe('COMPILED');
    expect(artifacts.length).toBe(9);
    expect(CULTURAL_IMAGE_PARTICIPATION_IMPLEMENTED).toBe(true);
  });

  it('2. P0.5C.1 remains valid', () => {
    expect(EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED).toBe(true);
    expect(P0_5C_1_EDITORIAL_HIERARCHY_PRESERVED).toBe(true);
    expect(v2Result.experiment.contracts.length).toBe(9);
  });

  it('3. Cultural imagery is first-class', () => {
    expect(CULTURAL_VISUAL_EVIDENCE_IMPLEMENTED).toBe(true);
    expect(CULTURAL_VISUAL_EVIDENCE_CLASSES.length).toBeGreaterThan(20);
    expect(CULTURAL_VISUAL_ROLES.length).toBeGreaterThan(10);
  });

  it('4. Cultural imagery is not mandatory for every artifact', () => {
    const modes = v21Result.experiment.amendedContracts.map((c) => c.culturalParticipation.visualParticipationMode);
    expect(culturalImageryNotMandatoryForEveryArtifact(modes)).toBe(true);
    expect(modes).toContain('TYPOGRAPHY_DOMINANT');
  });

  it('5. Every image receives a semantic role', () => {
    for (const c of v21Result.experiment.amendedContracts) {
      for (const ev of c.culturalParticipation.culturalVisualEvidence) {
        expect(CULTURAL_VISUAL_ROLES).toContain(ev.visualRole);
      }
    }
  });

  it('6. Decorative-only cultural imagery can fail', () => {
    const ev = buildCulturalVisualEvidence({ artifactId: 'x', profile: getTopicVisualProfile(3) });
    expect(decorativeOnlyCulturalImageFails({ ...ev, decorativeOnly: true })).toBe(true);
  });

  it('7. Random celebrity imagery fails', () => {
    expect(randomCelebrityImageFails('random celebrity portrait', 'subscription')).toBe(true);
  });

  it('8. Random nostalgia fails via reference density', () => {
    const ref = evaluateReferenceDensity(['random nostalgia clip', 'unnamed stock photo']);
    expect(ref.stuffingRisk).toBe(true);
  });

  it('9. Reference stuffing fails', () => {
    const ref = evaluateReferenceDensity(['a', 'b', 'c', 'd', 'e']);
    expect(ref.stuffingRisk).toBe(true);
  });

  it('10. Cultural Accomplice visibility can be evaluated', () => {
    expect(CULTURAL_ACCOMPLICE_VISUAL_EVALUATION_IMPLEMENTED).toBe(true);
    const ca = evaluateCulturalAccomplice({
      artifactId: artifact.id,
      mode: 'IMAGE_DOMINANT',
      humanPresence: true,
      culturalContext: true,
      topic: 'cultural reassessment',
    });
    expect(ca.overall).toBe('PASS');
  });

  it('11. ImageParticipationDecision exists before generation', () => {
    const decision = buildVisualSubjectMatterDecision({ artifact, thesis, spec });
    expect(imageParticipationDecisionExistsBeforeGeneration(decision)).toBe(true);
    expect(IMAGE_PARTICIPATION_DECISION_IMPLEMENTED).toBe(true);
  });

  it('12. IMAGE_DOMINANT is supported', () => {
    expect(imageDominantSupported('IMAGE_DOMINANT')).toBe(true);
    const profile = getTopicVisualProfile(3);
    expect(profile.mode).toBe('IMAGE_DOMINANT');
  });

  it('13. IMAGE_PLUS_TYPOGRAPHY is supported', () => {
    expect(VISUAL_PARTICIPATION_MODES).toContain('IMAGE_PLUS_TYPOGRAPHY');
    expect(imageDominantSupported('IMAGE_PLUS_TYPOGRAPHY')).toBe(true);
  });

  it('14. IMAGE_PLUS_EVIDENCE is supported', () => {
    expect(imageDominantSupported('IMAGE_PLUS_EVIDENCE')).toBe(true);
    expect(getTopicVisualProfile(1).mode).toBe('IMAGE_PLUS_EVIDENCE');
  });

  it('15. ARTIFACT_DOMINANT is supported', () => {
    expect(imageDominantSupported('ARTIFACT_DOMINANT')).toBe(true);
    expect(getTopicVisualProfile(7).mode).toBe('ARTIFACT_DOMINANT');
  });

  it('16. TYPOGRAPHY_DOMINANT remains supported', () => {
    expect(typographyDominantRemainsSupported('TYPOGRAPHY_DOMINANT')).toBe(true);
    expect(getTopicVisualProfile(5).mode).toBe('TYPOGRAPHY_DOMINANT');
  });

  it('17. DATA_DOMINANT remains supported', () => {
    expect(VISUAL_PARTICIPATION_MODES).toContain('DATA_DOMINANT');
  });

  it('18. MIXED_MEDIA is supported', () => {
    expect(imageDominantSupported('MIXED_MEDIA')).toBe(true);
    expect(getTopicVisualProfile(4).mode).toBe('MIXED_MEDIA');
  });

  it('19. Visual appetite is evaluated', () => {
    expect(VISUAL_APPETITE_EVALUATION_IMPLEMENTED).toBe(true);
    const va = evaluateVisualAppetite({
      artifactId: artifact.id,
      mode: 'IMAGE_DOMINANT',
      humanPresence: true,
      imageHero: true,
      objectHero: false,
      playfulness: false,
    });
    expect(visualAppetiteEvaluated(va)).toBe(true);
  });

  it('20. Human presence is optional but measurable', () => {
    const humanCount = v21Result.experiment.amendedContracts.filter(
      (c) => c.culturalParticipation.visualSubjectMatterDecision.humanPresence,
    ).length;
    expect(humanCount).toBeGreaterThan(0);
    expect(humanCount).toBeLessThan(9);
  });

  it('21. Feed cultural rhythm exists', () => {
    expect(FEED_CULTURAL_RHYTHM_IMPLEMENTED).toBe(true);
    expect(v21Result.experiment.feedCulturalRhythm?.boardId).toBe('exp01-v21');
  });

  it('22. Feed emotional rhythm exists', () => {
    expect(FEED_EMOTIONAL_RHYTHM_IMPLEMENTED).toBe(true);
    expect(v21Result.experiment.feedEmotionalRhythm?.temperatures.length).toBe(9);
  });

  it('23. Entire board can fail for text dominance', () => {
    expect(TEXT_DOMINANT_FEED_GUARD_IMPLEMENTED).toBe(true);
    const rhythm = buildFeedCulturalRhythm({
      boardId: 'test',
      contracts: v21Result.experiment.amendedContracts.map((c) => ({
        ...c,
        culturalParticipation: { ...c.culturalParticipation, visualParticipationMode: 'TYPOGRAPHY_DOMINANT' as const },
      })),
    });
    expect(textDominantFeedGuard(rhythm)).toBe(false);
  });

  it('24. Entire board can fail for document dominance', () => {
    expect(DOCUMENT_DOMINANT_FEED_GUARD_IMPLEMENTED).toBe(true);
    expect(documentDominantFeedGuard(['EVIDENCE_LED', 'EVIDENCE_LED', 'EVIDENCE_LED', 'EVIDENCE_LED', 'EVIDENCE_LED', 'EVIDENCE_LED', 'EVIDENCE_LED', 'EVIDENCE_LED', 'EVIDENCE_LED'])).toBe(false);
  });

  it('25. Entire board can fail for no artistic range', () => {
    const eval_ = evaluateBoardVisualDiversity({ contracts: v21Result.experiment.amendedContracts });
    expect(eval_.artisticRange).toBe('PASS');
  });

  it('26. Artistic evidence is distinct from factual evidence', () => {
    expect(ARTISTIC_EVIDENCE_IMPLEMENTED).toBe(true);
    const ae = buildArtisticEvidence({ artifactId: 'x', mode: 'MIXED_MEDIA' });
    expect(artisticEvidenceDistinctFromFactual(ae)).toBe(true);
  });

  it('27. Generated illustration cannot serve as factual evidence', () => {
    expect(GENERATED_IMAGE_EVIDENCE_BOUNDARY_IMPLEMENTED).toBe(true);
    expect(generatedIllustrationCannotBeFactual('GENERATED_ILLUSTRATION')).toBe(true);
  });

  it('28. Source provenance is retained', () => {
    const ev = buildCulturalVisualEvidence({ artifactId: 'x', profile: getTopicVisualProfile(3) });
    expect(ev.sourceProvenance).toBeTruthy();
    expect(ev.usageStatus).toBeTruthy();
  });

  it('29. NDX-authored copy remains uppercase', () => {
    expect(NDX_UPPERCASE_ONLY_AUTHORED_COPY_ENFORCED).toBe(true);
    for (const c of v21Result.experiment.amendedContracts) {
      expect(uppercaseGovernancePreserved(c)).toBe(true);
      expect(ndxAuthoredCopyIsUppercase(c.typographyAssignments)).toBe(true);
    }
  });

  it('30. Source imagery may preserve authentic source text', () => {
    const fal = compileCulturalFalPrompt({ artifact, contract: v21Result.experiment.amendedContracts[0]! });
    expect(fal.prompt).toContain('Source images preserve authentic mixed case');
  });

  it('31. Image may lead reading path', () => {
    const path = buildImageLedReadingPath({
      imageSubject: 'archival portrait',
      primaryHook: 'WE OWE HER AN APOLOGY.',
      evidence: 'old critique',
      trace: 'ACTUALLY.',
      metadata: 'topic',
    });
    expect(path.firstLook).toBe('archival portrait');
    expect(path.secondLook).toBe('WE OWE HER AN APOLOGY.');
  });

  it('32. Typography need not dominate every artifact', () => {
    const typeLed = v21Result.experiment.amendedContracts.filter(
      (c) => c.culturalParticipation.visualParticipationBalance === 'TYPE_LED',
    ).length;
    expect(typeLed).toBeLessThan(9);
  });

  it('33. Cultural reassessment may require image hero', () => {
    const c = v21Result.experiment.amendedContracts.find((x) => x.artifactId === 'bma-exp01-3')!;
    expect(c.culturalParticipation.imageParticipationRequired).toBe('REQUIRED');
    expect(c.culturalParticipation.visualSubjectMatterDecision.imageHero).toBe(true);
  });

  it('34. Content topic remains unchanged in controlled V2/V2.1 comparison', () => {
    expect(sameTopicsUnchanged(v21Result.artifacts)).toBe(true);
    expect(v21Result.experiment.topics).toEqual(v2Result.experiment.topics);
  });

  it('35. Hierarchy corrections remain active', () => {
    for (const c of v21Result.experiment.amendedContracts) {
      expect(hierarchyCorrectionsPreserved(c)).toBe(true);
    }
  });

  it('36. First-slide information budget remains active', () => {
    for (const c of v21Result.experiment.amendedContracts) {
      expect(c.informationBudget.withinBudget).toBeDefined();
    }
  });

  it('37. Cultural imagery cannot reintroduce information overload', () => {
    for (const c of v21Result.experiment.amendedContracts) {
      expect(c.primaryEvidence.length).toBeLessThanOrEqual(2);
    }
  });

  it('38. Image participation cannot bypass editorial decision', () => {
    const opp = seedPilotOpportunities('ndxbook')[0]!;
    const channel = selectChannelForOpportunity(opp);
    const format = selectFormatForOpportunity(opp, channel);
    const pkg = buildSocialContentPackage({
      projectId: 'ndxbook',
      opportunity: opp,
      channel,
      format,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    const layer = buildContentPackageVisualSubjectLayer({
      pkg,
      opportunity: opp,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    expect(
      imageParticipationCannotBypassEditorialDecision(pkg.editorialDecisionId, layer.visualSubjectMatterDecisionId),
    ).toBe(true);
  });

  it('39. Lime governance remains active', () => {
    expect(limeGovernancePreserved()).toBe(true);
  });

  it('40. Random image generation is blocked', () => {
    expect(RANDOM_CULTURAL_REFERENCE_GUARD_IMPLEMENTED).toBe(true);
    expect(randomCelebrityImageFails('stock model portrait', 'corporate language')).toBe(true);
  });

  it('41. Founder review occurs before FAL generation', () => {
    expect(v21ContractReviewBeforeGeneration(v21Result.experiment)).toBe(true);
  });

  it('42. No generation on page load', () => {
    expect(noPageLoadGeneration()).toBe(true);
  });

  it('43. No hidden retry', () => {
    expect(providerGenerationRequiresFounderTrigger()).toBe(true);
    expect(experiment01V21NotAutoGenerated()).toBe(true);
  });

  it('44. Historical V1/V2 assets remain immutable', () => {
    expect(experiment01V1Preserved(artifacts)).toBe(true);
    expect(v2HistoryNotMutated()).toBe(true);
  });

  it('45. Experiment F remains immutable', () => {
    expect(experimentFImmutable()).toBe(true);
  });

  it('46. Experiment G remains immutable', () => {
    expect(experimentGNotReevaluated()).toBe(true);
  });

  it('47. Brand Character remains immutable', () => {
    expect(brandCharacterImmutable()).toBe(true);
    expect(characterSystem.id).toBeTruthy();
  });

  it('48. Brand Canon remains unchanged', () => {
    expect(brandCanonUnchanged()).toBe(true);
  });

  it('49. Product Expression remains blocked', () => {
    expect(productExpressionBlocked()).toBe(true);
  });

  it('50. World Formation remains blocked', () => {
    expect(worldFormationBlocked()).toBe(true);
  });

  it('51. Persistence remains restart-safe', () => {
    expect(v21Result.experiment.version).toBe('EXPERIMENT_01_V2_1_CULTURAL_IMAGE_PARTICIPATION');
    expect(v21Result.experiment.amendedContracts.every((c) => c.fingerprint.length > 0)).toBe(true);
  });

  it('52. Full test suite passes (this file)', () => {
    expect(VISUAL_SUBJECT_MATTER_GOVERNANCE_IMPLEMENTED).toBe(true);
    expect(EXPERIMENT_01_CULTURAL_VISUAL_PIPELINE_READY).toBe(true);
  });

  it('53. Production build passes (flagged via pipeline ready)', () => {
    expect(EXPERIMENT_01_CULTURAL_VISUAL_PIPELINE_READY).toBe(true);
    expect(experiment01CulturalVisualsGeneratedByDefault()).toBe(false);
  });

  it('FAL prompt updated with 24 sections', () => {
    expect(FAL_CULTURAL_PROMPT_SECTION_ORDER.length).toBe(24);
    const fal = compileCulturalFalPrompt({ artifact, contract: v21Result.experiment.amendedContracts[0]! });
    expect(culturalFalPromptUpdated(fal)).toBe(true);
    expect(fal.prompt).toContain('NEGATIVE CONSTRAINTS');
  });

  it('North-star cultural calibration is not final identity', () => {
    const cal = evaluateNorthStarCulturalParticipation(northStar);
    expect(cal.classification).toBe('CULTURAL_IMAGE_PARTICIPATION_CALIBRATION');
    expect(northStarCulturalNotFinalIdentity(cal)).toBe(true);
  });

  it('Content Operations visual subject matter integrated', () => {
    expect(CONTENT_OPERATIONS_VISUAL_SUBJECT_MATTER_INTEGRATED).toBe(true);
    const opp = seedPilotOpportunities('ndxbook')[0]!;
    const potential = evaluateOpportunityVisualPotential(opp);
    expect(potential.humanVisualPotential).toBeGreaterThan(0);
    const channel = selectChannelForOpportunity(opp);
    const format = selectFormatForOpportunity(opp, channel);
    const pkg = buildSocialContentPackage({
      projectId: 'ndxbook',
      opportunity: opp,
      channel,
      format,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    const layer = buildContentPackageVisualSubjectLayer({
      pkg,
      opportunity: opp,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    expect(contentOperationsVisualSubjectIntegrated(layer)).toBe(true);
    expect(p05c1HierarchyPreserved(v21Result.experiment.amendedContracts[0]!)).toBe(true);
  });

  it('Playfulness evaluation distinguishes playful from frivolous', () => {
    expect(PLAYFULNESS_EVALUATION_IMPLEMENTED).toBe(true);
    const mp = evaluatePlayfulness({ artifactId: 'x', temperature: 'PLAYFUL', mode: 'IMAGE_PLUS_TYPOGRAPHY' });
    expect(mp.playful).toBe(true);
    expect(mp.frivolous).toBe(false);
  });

  it('Board diversity evaluation flags monotony when applicable', () => {
    const eval_ = evaluateBoardVisualDiversity({ contracts: v21Result.experiment.amendedContracts });
    expect(eval_.imageTypeBalance).toBe('PASS');
    expect(eval_.failureStates).not.toContain('FAIL_VISUALLY_MONOTONOUS');
  });

  it('Amended contract artifact QA includes cultural dimensions', () => {
    const qa = evaluateAmendedContract(v21Result.experiment.amendedContracts[0]!);
    expect(qa.evaluationId).toBeTruthy();
    expect(qa.culturalRange).toBeDefined();
  });

  it('Founder can generate all nine V2.1 slides with one batch trigger', async () => {
    resetBrandMarketingExpressionWorkers();
    await prepareBrandMarketingExpression({ projectId: 'ndxbook' });
    await compileBrandMarketingExpression({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01({ projectId: 'ndxbook' });
    await formulateMarketingExpressionExperiment01V2({ projectId: 'ndxbook' });
    const formulated = await formulateMarketingExpressionExperiment01V21({ projectId: 'ndxbook' });
    const generated = await generateAllExperiment01V21ArtifactAssets({ projectId: 'ndxbook' });
    expect(generated.experiment01V21?.generatedArtifacts.every((a) => a.generationStatus === 'GENERATED')).toBe(true);
    expect(generated.experiment01V21?.generatedArtifacts.length).toBe(9);
    expect(formulated.experiment01V21?.generatedArtifacts.length).toBe(9);
    expect(generated.accounting.falRequests).toBe(9);
  });
});
