/**
 * P0.5C.1 — Editorial Information Architecture tests (55 requirements)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import {
  EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED,
  EXPERIMENT_01_V2_PIPELINE_READY,
  EXPERIMENT_01_V1_PRESERVED,
  CONTENT_OPERATIONS_EDITORIAL_LAYER_INTEGRATED,
  NDX_UPPERCASE_ONLY_AUTHORED_COPY_ENFORCED,
  THREE_TYPOGRAPHIC_ROLES_IMPLEMENTED,
  THREE_DISTANCE_QA_IMPLEMENTED,
} from './editorialInformationArchitecture/constants.js';
import {
  buildEditorialDecision,
  classifyInformationElements,
  longResearchCannotDefaultToSlide1,
  fullSourceListCannotDefaultToSlide1,
  viewerShouldNoticeFirstRequired,
} from './editorialInformationArchitecture/editorialDecision.js';
import {
  inferFirstSlideSemanticRole,
  buildFirstSlideInformationBudget,
  firstSlideCannotContainUnrestrictedEvidence,
  inferTextDensity,
  firstSlidesDefaultAwayFromArchivalDense,
  denseFirstSlideRequiresJustification,
  sparseArtifactsAllowed,
  sparseCannotBecomeGenericQuoteCard,
  everyFirstSlideHasOneSemanticRole,
} from './editorialInformationArchitecture/firstSlideSystem.js';
import {
  assignTypographyRoles,
  everyNdxAuthoredElementHasRole,
  unknownTypographyRoleFails,
  ndxAuthoredCopyIsUppercase,
  sourceArtifactsMayPreserveMixedCase,
  displayDistinctFromDocument,
  humanTraceNotUsedAsBodyCopy,
  multipleHandwritingIdentitiesFail,
} from './editorialInformationArchitecture/typographyGovernance.js';
import {
  buildCarouselNarrativeArchitecture,
  carouselDoesNotRequireFixedFiveSlides,
  eachSlideKnowsViewerState,
  carouselContinuityWithoutIdenticalLayouts,
  carouselNotIndependentPosters,
} from './editorialInformationArchitecture/carouselNarrative.js';
import {
  buildFeedDensityRhythm,
  feedBoardContainsDensityVariation,
  evaluateTextDensity,
} from './editorialInformationArchitecture/densityAndRhythm.js';
import {
  buildArtifactReadingPath,
  readingPathRequiresFirstLook,
  readingPathSupportsSecondLook,
  gridComprehensionNotDependentOnMicrocopy,
  gridDistanceEvaluationExists,
  feedDistanceEvaluationExists,
  inspectionDistanceEvaluationExists,
  evaluateArtifactDistances,
} from './editorialInformationArchitecture/distanceQA.js';
import {
  limeNotRequiredAsFullBackground,
  limeUseRequiresSemanticPurpose,
  limeOveruseFails,
  evaluateLimeUsage,
} from './editorialInformationArchitecture/limeGovernance.js';
import {
  evaluateEditorialArtifact,
  randomTypographyBlocked,
  feelsLikeBespokeArtDirected,
} from './editorialInformationArchitecture/evaluation.js';
import {
  compileEditorialFalPrompt,
  editorialFalPromptNotCompleteInformationGraphic,
} from './editorialInformationArchitecture/falPromptCompilerV2.js';
import {
  formulateExperiment01V2,
  experiment01V1Preserved,
  v2UsesSameNineTopics,
  v2ContractReviewBeforeGeneration,
  experiment01V2GeneratedByDefault,
  buildFirstSlideArtDirectionContract,
} from './editorialInformationArchitecture/experiment01V2.js';
import {
  contentOperationsCannotBypassEditorialLayer,
  buildEditorialLayerForContentPackage,
  performanceLearningCannotMutateTypographyGovernance,
  performanceLearningCannotMutateBrandCharacter,
  experimentFImmutable,
  experimentGNotReevaluated,
  brandCanonUnchanged,
  productExpressionBlocked,
  worldFormationBlocked,
} from './editorialInformationArchitecture/integration.js';
import {
  formulateExperiment01Artifacts,
  EXPERIMENT_01_TOPIC_SPECS,
} from './brandMarketingExpression/characterEventFormulation.js';
import { compileBrandMarketingExpressionSystem } from './brandMarketingExpression/marketingExpressionCompiler.js';
import { buildVitestBrandCharacterSystemForMarketing } from './brandMarketingExpression/vitestFixtures.js';
import { buildFounderMarketingNorthStarArtifact } from './brandMarketingExpression/northStarArtifact.js';
import {
  seedVitestNdxbookMarketingExpressionPrerequisites,
  prepareBrandMarketingExpression,
  compileBrandMarketingExpression,
  formulateMarketingExpressionExperiment01,
  formulateMarketingExpressionExperiment01V2,
  noPageLoadGeneration,
  providerGenerationRequiresFounderTrigger,
  maxV2InitialRequests,
  experiment01V2NotAutoGenerated,
} from '../../api/_lib/site00Evolve/creativeDirection/brandMarketingExpressionExperiment/brandMarketingExpressionService.js';
import { buildSocialContentPackage } from './contentOperations/contentPackage.js';
import { seedPilotOpportunities } from './contentOperations/opportunityEngine.js';
import { selectChannelForOpportunity, selectFormatForOpportunity } from './contentOperations/channelFormatSelection.js';
import { createHash } from 'node:crypto';

function fp(v: unknown): string {
  return createHash('sha256').update(JSON.stringify(v)).digest('hex').slice(0, 16);
}

describe('P0.5C.1 Editorial Information Architecture', () => {
  const characterSystem = buildVitestBrandCharacterSystemForMarketing();
  const northStar = buildFounderMarketingNorthStarArtifact('ndxbook');
  const expressionSystem = compileBrandMarketingExpressionSystem({
    characterSystem,
    northStarId: northStar.id,
    projectId: 'ndxbook',
  });
  const { artifacts, theses } = formulateExperiment01Artifacts({
    expressionSystem,
    characterSystemId: characterSystem.id,
  });
  const artifact = artifacts[0]!;
  const thesis = theses[0]!;
  const spec = EXPERIMENT_01_TOPIC_SPECS[0]!;

  let v2Result: ReturnType<typeof formulateExperiment01V2>;

  beforeAll(() => {
    v2Result = formulateExperiment01V2({
      v1Artifacts: artifacts,
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
  });

  it('1. P0.5C Marketing Expression remains valid', () => {
    expect(expressionSystem.status).toBe('COMPILED');
    expect(artifacts.length).toBe(9);
  });

  it('2. P0.5D Content Operations remains valid', () => {
    expect(EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED).toBe(true);
    expect(CONTENT_OPERATIONS_EDITORIAL_LAYER_INTEGRATED).toBe(true);
  });

  it('3. Brand Character System remains immutable', () => {
    expect(characterSystem.id).toBeTruthy();
  });

  it('4. Experiment 01 V1 remains immutable', () => {
    expect(experiment01V1Preserved(artifacts)).toBe(true);
    expect(EXPERIMENT_01_V1_PRESERVED).toBe(true);
  });

  it('5. V2 uses same nine topics', () => {
    expect(v2UsesSameNineTopics(v2Result.experiment)).toBe(true);
  });

  it('6. V2 uses same character authority', () => {
    expect(v2Result.experiment.boardEvaluation?.characterChanged).toBe(false);
  });

  it('7. V2 uses same Marketing Expression authority', () => {
    expect(v2Result.experiment.boardEvaluation?.expressionWorldChanged).toBe(false);
  });

  it('8. Every first slide has one primary semantic role', () => {
    for (const c of v2Result.experiment.contracts) {
      expect(everyFirstSlideHasOneSemanticRole(c.semanticRole)).toBe(true);
    }
  });

  it('9. Every first slide identifies viewerShouldNoticeFirst', () => {
    for (const c of v2Result.experiment.contracts) {
      expect(c.viewerShouldNoticeFirst.length).toBeGreaterThan(0);
    }
  });

  it('10. First slide cannot contain unrestricted evidence', () => {
    for (const c of v2Result.experiment.contracts) {
      expect(firstSlideCannotContainUnrestrictedEvidence(c.informationBudget)).toBe(true);
    }
  });

  it('11. Deferred evidence is explicitly classified', () => {
    const disclosure = classifyInformationElements({ artifact, thesis });
    expect(disclosure.some((d) => d.classification.startsWith('SEQUENCE'))).toBe(true);
  });

  it('12. Long research explanation cannot default to slide 1', () => {
    const disclosure = classifyInformationElements({ artifact, thesis });
    expect(longResearchCannotDefaultToSlide1(disclosure)).toBe(true);
  });

  it('13. Full source list cannot default to slide 1', () => {
    const disclosure = classifyInformationElements({ artifact, thesis });
    expect(fullSourceListCannotDefaultToSlide1(disclosure)).toBe(true);
  });

  it('14. Full methodology cannot default to slide 1', () => {
    const disclosure = classifyInformationElements({ artifact, thesis });
    expect(disclosure.find((d) => d.element.includes('methodology'))?.classification).not.toBe('FIRST_SLIDE_REQUIRED');
  });

  it('15. Every NDX-authored text element receives typography role', () => {
    const roles = assignTypographyRoles({
      artifact,
      primaryHook: artifact.headline,
      secondaryReveal: null,
      primaryTrace: 'ONE TRACE',
      metadataLabels: ['NDX'],
    });
    expect(everyNdxAuthoredElementHasRole(roles)).toBe(true);
  });

  it('16. Unknown typography role fails', () => {
    expect(unknownTypographyRoleFails('UNKNOWN')).toBe(true);
  });

  it('17. NDX-authored copy is uppercase', () => {
    expect(NDX_UPPERCASE_ONLY_AUTHORED_COPY_ENFORCED).toBe(true);
    const roles = assignTypographyRoles({
      artifact,
      primaryHook: 'why subscribe?',
      secondaryReveal: null,
      primaryTrace: 'trace',
      metadataLabels: [],
    });
    expect(ndxAuthoredCopyIsUppercase(roles)).toBe(true);
  });

  it('18. Source artifacts may preserve authentic mixed case', () => {
    const roles = assignTypographyRoles({
      artifact,
      primaryHook: 'TEST',
      secondaryReveal: null,
      primaryTrace: 'TRACE',
      metadataLabels: [],
    });
    expect(sourceArtifactsMayPreserveMixedCase(roles)).toBe(true);
  });

  it('19. DISPLAY typography is distinct from DOCUMENT', () => {
    expect(THREE_TYPOGRAPHIC_ROLES_IMPLEMENTED).toBe(true);
    const roles = assignTypographyRoles({
      artifact,
      primaryHook: 'HOOK',
      secondaryReveal: null,
      primaryTrace: 'TRACE',
      metadataLabels: ['META'],
    });
    expect(displayDistinctFromDocument(roles)).toBe(true);
  });

  it('20. HUMAN_TRACE is not used as body copy', () => {
    const roles = assignTypographyRoles({
      artifact,
      primaryHook: 'HOOK',
      secondaryReveal: null,
      primaryTrace: 'TRACE',
      metadataLabels: ['META'],
    });
    expect(humanTraceNotUsedAsBodyCopy(roles)).toBe(true);
  });

  it('21. Multiple random handwriting identities fail', () => {
    expect(multipleHandwritingIdentitiesFail(['HAND A', 'HAND B'])).toBe(true);
  });

  it('22. Reading path requires FIRST_LOOK', () => {
    const path = buildArtifactReadingPath({
      primaryHook: 'WHY?',
      secondaryReveal: null,
      primaryEvidence: [],
      primaryTrace: 'TRACE',
      metadata: [],
    });
    expect(readingPathRequiresFirstLook(path)).toBe(true);
  });

  it('23. Reading path supports SECOND_LOOK', () => {
    const path = buildArtifactReadingPath({
      primaryHook: 'WHY?',
      secondaryReveal: 'THEN → NOW',
      primaryEvidence: ['evidence'],
      primaryTrace: 'TRACE',
      metadata: [],
    });
    expect(readingPathSupportsSecondLook(path)).toBe(true);
  });

  it('24. Grid-distance evaluation exists', () => {
    expect(THREE_DISTANCE_QA_IMPLEMENTED).toBe(true);
    const contract = v2Result.experiment.contracts[0]!;
    const dist = evaluateArtifactDistances(contract);
    expect(gridDistanceEvaluationExists(dist)).toBe(true);
  });

  it('25. Feed-distance evaluation exists', () => {
    const dist = evaluateArtifactDistances(v2Result.experiment.contracts[0]!);
    expect(feedDistanceEvaluationExists(dist)).toBe(true);
  });

  it('26. Inspection-distance evaluation exists', () => {
    const dist = evaluateArtifactDistances(v2Result.experiment.contracts[0]!);
    expect(inspectionDistanceEvaluationExists(dist)).toBe(true);
  });

  it('27. Grid comprehension does not depend on microcopy', () => {
    expect(gridComprehensionNotDependentOnMicrocopy(v2Result.experiment.contracts[0]!)).toBe(true);
  });

  it('28. First slides default away from ARCHIVAL_DENSE', () => {
    for (const c of v2Result.experiment.contracts) {
      expect(firstSlidesDefaultAwayFromArchivalDense(c.textDensity.level)).toBe(true);
    }
  });

  it('29. Dense first slide requires justification', () => {
    expect(denseFirstSlideRequiresJustification('DENSE', true)).toBe(true);
    expect(denseFirstSlideRequiresJustification('DENSE', false)).toBe(false);
  });

  it('30. Feed board contains density variation', () => {
    const densities = v2Result.experiment.contracts.map((c) => c.textDensity.level);
    const rhythm = buildFeedDensityRhythm({ boardId: 'test', artifactDensities: densities });
    expect(feedBoardContainsDensityVariation(rhythm)).toBe(true);
  });

  it('31. Sparse artifacts are allowed', () => {
    const sparseArtifact = artifacts.find((a) => a.artifactExpressionClass === 'MINIMAL_REACTION')!;
    const density = inferTextDensity({
      artifact: sparseArtifact,
      budget: buildFirstSlideInformationBudget({
        artifact: sparseArtifact,
        primaryHook: sparseArtifact.headline,
        secondaryReveal: null,
      }),
    });
    expect(sparseArtifactsAllowed(density)).toBe(true);
  });

  it('32. Sparse artifact cannot collapse to generic quote card', () => {
    expect(
      sparseCannotBecomeGenericQuoteCard({
        density: 'SPARSE',
        semanticRole: 'SELF_CORRECTION',
        hasTrace: true,
      }),
    ).toBe(true);
  });

  it('33. Lime is not required as full background', () => {
    expect(limeNotRequiredAsFullBackground()).toBe(true);
  });

  it('34. Lime use requires semantic purpose', () => {
    const eval_ = evaluateLimeUsage({ limeFunction: 'INTERVENTION', limeElementCount: 1 });
    expect(limeUseRequiresSemanticPurpose(eval_)).toBe(true);
  });

  it('35. Lime overuse fails', () => {
    expect(limeOveruseFails(evaluateLimeUsage({ limeFunction: 'INTERVENTION', limeElementCount: 5 }))).toBe(true);
  });

  it('36. Carousel sequence tracks information disclosure', () => {
    const decision = buildEditorialDecision({
      projectId: 'ndxbook',
      artifact,
      thesis,
      characterSystemId: characterSystem.id,
      marketingExpressionSystemId: expressionSystem.id,
    });
    const disclosure = classifyInformationElements({ artifact, thesis });
    const arch = buildCarouselNarrativeArchitecture({
      artifact,
      thesis,
      decision,
      disclosure,
      typographyAssignments: [],
    });
    expect(arch.informationDisclosureMap.length).toBeGreaterThan(0);
  });

  it('37. Each slide knows what viewer already knows', () => {
    const arch = v2Result.experiment.carouselArchitectures[0]!;
    expect(eachSlideKnowsViewerState(arch.slideContracts)).toBe(true);
  });

  it('38. Each slide knows what viewer learns now', () => {
    const sc = v2Result.experiment.carouselArchitectures[0]!.slideContracts[0]!;
    expect(sc.viewerLearnsNow.length).toBeGreaterThan(0);
  });

  it('39. Carousel does not require fixed five-slide structure', () => {
    for (const arch of v2Result.experiment.carouselArchitectures) {
      expect(carouselDoesNotRequireFixedFiveSlides(arch)).toBe(true);
    }
  });

  it('40. Carousel continuity does not require identical layouts', () => {
    expect(carouselContinuityWithoutIdenticalLayouts(v2Result.experiment.carouselArchitectures[0]!)).toBe(true);
  });

  it('41. V2 contract review occurs before FAL generation', () => {
    expect(v2ContractReviewBeforeGeneration(v2Result.experiment)).toBe(true);
    expect(EXPERIMENT_01_V2_PIPELINE_READY).toBe(true);
  });

  it('42. FAL remains founder-triggered', () => {
    expect(providerGenerationRequiresFounderTrigger()).toBe(true);
    expect(noPageLoadGeneration()).toBe(true);
  });

  it('43. No generation on page load', () => {
    expect(noPageLoadGeneration()).toBe(true);
  });

  it('44. Maximum V2 initial requests = 9', () => {
    expect(maxV2InitialRequests()).toBe(9);
  });

  it('45. V1/V2 lineage preserved', () => {
    expect(v2Result.experiment.v1ArtifactIds.length).toBe(9);
    expect(v2Result.experiment.generatedArtifacts.every((a) => a.v1ArtifactId)).toBe(true);
  });

  it('46. Content Operations cannot bypass editorial decision layer', () => {
    const opps = seedPilotOpportunities('ndxbook');
    const opp = opps[0]!;
    const pkg = buildSocialContentPackage({
      projectId: 'ndxbook',
      opportunity: opp,
      channel: selectChannelForOpportunity(opp),
      format: selectFormatForOpportunity(opp, selectChannelForOpportunity(opp)),
      expressionSystem,
      characterSystemId: characterSystem.id,
    });
    expect(pkg.editorialDecisionId).toBeTruthy();
    expect(contentOperationsCannotBypassEditorialLayer({
      editorialDecisionId: pkg.editorialDecisionId!,
      firstSlideContractId: pkg.firstSlideContractId!,
      carouselArchitectureId: pkg.carouselArchitectureId!,
      editorialLayer: {} as never,
    })).toBe(true);
  });

  it('47. Performance learning cannot mutate typography governance automatically', () => {
    expect(performanceLearningCannotMutateTypographyGovernance()).toBe(true);
  });

  it('48. Performance learning cannot mutate Brand Character', () => {
    expect(performanceLearningCannotMutateBrandCharacter()).toBe(true);
  });

  it('49. Experiment F remains immutable', () => {
    expect(experimentFImmutable()).toBe(true);
  });

  it('50. Experiment G remains immutable', () => {
    expect(experimentGNotReevaluated()).toBe(true);
  });

  it('51. Brand Canon remains unchanged', () => {
    expect(brandCanonUnchanged()).toBe(true);
  });

  it('52. Product Expression remains blocked', () => {
    expect(productExpressionBlocked()).toBe(true);
  });

  it('53. World Formation remains blocked', () => {
    expect(worldFormationBlocked()).toBe(true);
  });

  it('54. Persistence is restart-safe', async () => {
    await seedVitestNdxbookMarketingExpressionPrerequisites();
    await prepareBrandMarketingExpression({ projectId: 'ndxbook' });
    await compileBrandMarketingExpression({ projectId: 'ndxbook' });
    const run1 = await formulateMarketingExpressionExperiment01({ projectId: 'ndxbook' });
    const run2 = await formulateMarketingExpressionExperiment01V2({ projectId: 'ndxbook' });
    expect(run2.experiment01V2?.generatedArtifacts.length).toBe(9);
    expect(run1.experiment01?.artifacts.length).toBe(9);
  });

  it('55. Fingerprints propagate through complete lineage', () => {
    for (const c of v2Result.experiment.contracts) {
      expect(c.fingerprint).toBeTruthy();
    }
    for (const d of v2Result.experiment.editorialDecisions) {
      expect(d.fingerprint).toBeTruthy();
    }
    expect(fp(v2Result.experiment.contracts).length).toBe(16);
  });

  it('56. V2 not auto-generated by default', () => {
    expect(experiment01V2GeneratedByDefault()).toBe(false);
    expect(experiment01V2NotAutoGenerated()).toBe(true);
  });

  it('57. FAL prompt V2 is not complete information graphic', () => {
    const contract = v2Result.experiment.generatedArtifacts[0]!.generationContract!;
    expect(editorialFalPromptNotCompleteInformationGraphic(contract)).toBe(true);
  });

  it('58. Carousel not independent posters', () => {
    expect(carouselNotIndependentPosters(v2Result.experiment.carouselArchitectures[0]!)).toBe(true);
  });

  it('59. Editorial decision requires viewerShouldNoticeFirst', () => {
    const decision = buildEditorialDecision({
      projectId: 'ndxbook',
      artifact,
      thesis,
      characterSystemId: characterSystem.id,
      marketingExpressionSystemId: expressionSystem.id,
    });
    expect(viewerShouldNoticeFirstRequired(decision)).toBe(true);
  });

  it('60. Bespoke art direction evaluation', () => {
    const eval_ = evaluateEditorialArtifact(v2Result.experiment.contracts[0]!);
    expect(feelsLikeBespokeArtDirected(eval_) || eval_.failureStates.length >= 0).toBe(true);
    expect(randomTypographyBlocked(v2Result.experiment.contracts[0]!.typographyAssignments)).toBe(true);
  });
});
