/**
 * Blind personality replay execution phases — persisted for founder UI progression.
 */

export const REPLAY_EXECUTION_PHASES = [
  'PERSONALITY_SUBMITTED',
  'SYNTHESIZING_PERSONALITY',
  'FORMING_CORE_DIRECTION',
  'FORMING_DIRECTION_EXPRESSION',
  'FORMING_CREATIVE_EXPRESSION',
  'FORMING_IDENTITY_ART_DIRECTION',
  'BUILDING_HERO_CONCEPT',
  'COMPILING_VISUAL_BRIEF',
  'GENERATING_HERO',
  'HERO_READY',
  'COMPARING_METHODOLOGY',
  'REPLAY_COMPLETE',
  'EXECUTION_FAILED',
] as const;

export type ReplayExecutionPhase = (typeof REPLAY_EXECUTION_PHASES)[number];

/** Founder-facing labels — match blind replay progression UI. */
export const REPLAY_EXECUTION_PHASE_LABELS: Record<ReplayExecutionPhase, string> = {
  PERSONALITY_SUBMITTED: 'PERSONALITY SUBMITTED',
  SYNTHESIZING_PERSONALITY: 'SYNTHESIZING PERSONALITY',
  FORMING_CORE_DIRECTION: 'FORMING CORE DIRECTION',
  FORMING_DIRECTION_EXPRESSION: 'FORMING DIRECTION EXPRESSION',
  FORMING_CREATIVE_EXPRESSION: 'FORMING CREATIVE EXPRESSION',
  FORMING_IDENTITY_ART_DIRECTION: 'FORMING IDENTITY ART DIRECTION',
  BUILDING_HERO_CONCEPT: 'BUILDING HERO CONCEPT',
  COMPILING_VISUAL_BRIEF: 'COMPILING VISUAL BRIEF',
  GENERATING_HERO: 'GENERATING HERO',
  HERO_READY: 'HERO READY',
  COMPARING_METHODOLOGY: 'COMPARING METHODOLOGY',
  REPLAY_COMPLETE: 'REPLAY COMPLETE',
  EXECUTION_FAILED: 'EXECUTION FAILED',
};

export function replayExecutionPhaseLabel(phase: ReplayExecutionPhase | null | undefined): string {
  if (!phase) return 'UNKNOWN';
  return REPLAY_EXECUTION_PHASE_LABELS[phase] ?? phase.replace(/_/g, ' ');
}

/** Ordered founder progression (excludes failure terminal). */
export const REPLAY_EXECUTION_PROGRESS_PHASES = [
  'PERSONALITY_SUBMITTED',
  'SYNTHESIZING_PERSONALITY',
  'FORMING_CORE_DIRECTION',
  'FORMING_DIRECTION_EXPRESSION',
  'FORMING_CREATIVE_EXPRESSION',
  'FORMING_IDENTITY_ART_DIRECTION',
  'BUILDING_HERO_CONCEPT',
  'COMPILING_VISUAL_BRIEF',
  'GENERATING_HERO',
  'HERO_READY',
  'COMPARING_METHODOLOGY',
  'REPLAY_COMPLETE',
] as const satisfies readonly ReplayExecutionPhase[];

export function replayExecutionPhaseIndex(phase: ReplayExecutionPhase): number {
  return REPLAY_EXECUTION_PHASES.indexOf(phase);
}
