/**
 * P0.5C.1 — Editorial Information Architecture + Typographic Governance
 */

export const EDITORIAL_INFORMATION_ARCHITECTURE_V1 = 'EDITORIAL_INFORMATION_ARCHITECTURE_V1' as const;
export const EXPERIMENT_01_V1_VERSION = 'EXPERIMENT_01_V1' as const;
export const EXPERIMENT_01_V2_VERSION = 'EXPERIMENT_01_V2_INFORMATION_ARCHITECTURE' as const;

export const FIRST_SLIDE_SEMANTIC_ROLES = [
  'QUESTION',
  'JUDGMENT',
  'CONTRADICTION',
  'RECEIPT',
  'CALLBACK',
  'DISCOVERY',
  'SELF_CORRECTION',
  'COMPARISON',
  'PATTERN',
  'PROVOCATION',
  'OBSERVATION',
  'DECLARATION',
  'OPEN_LOOP',
] as const;

export const DEFER_CLASSIFICATIONS = [
  'FIRST_SLIDE_REQUIRED',
  'FIRST_SLIDE_OPTIONAL',
  'SEQUENCE_EVIDENCE',
  'SEQUENCE_CONTEXT',
  'SEQUENCE_COMPLICATION',
  'SEQUENCE_SYNTHESIS',
  'SEQUENCE_JUDGMENT',
  'CAPTION_ONLY',
  'PROVENANCE_ONLY',
  'REMOVE',
] as const;

export const CAROUSEL_SEQUENCE_FUNCTIONS = [
  'HOOK',
  'EVIDENCE',
  'CONTEXT',
  'COMPLICATION',
  'CONTRADICTION',
  'INVESTIGATION',
  'CONNECTION',
  'CALLBACK',
  'SYNTHESIS',
  'JUDGMENT',
  'SELF_CORRECTION',
  'UNRESOLVED_QUESTION',
  'CTA',
] as const;

export const TYPOGRAPHY_ROLES = ['DISPLAY', 'DOCUMENT', 'HUMAN_TRACE', 'SOURCE_TEXT'] as const;

export const NDX_AUTHORING_TYPOGRAPHY_ROLES = ['DISPLAY', 'DOCUMENT', 'HUMAN_TRACE'] as const;

export const TEXT_DENSITY_LEVELS = ['SPARSE', 'LIGHT', 'MODERATE', 'DENSE', 'ARCHIVAL_DENSE'] as const;

export const FEED_DENSITY_RHYTHM_TARGETS = ['DENSE', 'MODERATE', 'SPARSE'] as const;

export const LIME_FUNCTIONS = [
  'ATTENTION',
  'INTERVENTION',
  'JUDGMENT',
  'CORRECTION',
  'CONNECTION',
  'SIGNAL',
] as const;

export const EDITORIAL_FAILURE_STATES = [
  'FAIL_NO_PRIMARY_READ',
  'FAIL_COMPETING_HEADLINES',
  'FAIL_INFORMATION_OVERLOAD',
  'FAIL_REPORT_ON_SLIDE_ONE',
  'FAIL_NO_READING_PATH',
  'FAIL_EVIDENCE_COMPETES_WITH_HOOK',
  'FAIL_TOO_MUCH_MICROCOPY',
  'FAIL_RANDOM_TYPOGRAPHY',
  'FAIL_UNKNOWN_TYPOGRAPHY_ROLE',
  'FAIL_MIXED_CASE_NDX_COPY',
  'FAIL_MULTIPLE_HANDWRITING_IDENTITIES',
  'FAIL_TRACE_OVERLOAD',
  'FAIL_LIME_OVERUSE',
  'FAIL_DECORATIVE_LIME',
  'FAIL_GRID_ILLEGIBLE',
  'FAIL_FEED_ILLEGIBLE',
  'FAIL_NO_INSPECTION_REWARD',
  'FAIL_ALL_POSTS_SAME_DENSITY',
  'FAIL_SPARSE_BECOMES_GENERIC',
  'FAIL_CAROUSEL_AS_INDEPENDENT_POSTERS',
  'FAIL_SEQUENCE_REPEATS_LAYOUT',
  'FAIL_FIRST_SLIDE_CONTAINS_WHOLE_ARGUMENT',
  'FAIL_AI_EDITORIAL_CLUTTER',
  'FAIL_NOT_BESPOKE_ART_DIRECTION',
] as const;

export const V2_FOUNDER_JUDGMENTS = [
  'THATS_IT',
  'LOVE_THIS',
  'RIGHT_CHARACTER_TOO_BUSY',
  'RIGHT_CHARACTER_WRONG_HIERARCHY',
  'DONT_KNOW_WHERE_TO_LOOK',
  'TOO_MUCH_INFORMATION',
  'MOVE_THIS_TO_SLIDE_2',
  'HEADLINE_NOT_STRONG_ENOUGH',
  'TYPOGRAPHY_WRONG',
  'TOO_MANY_FONTS',
  'TOO_MUCH_HANDWRITING',
  'NOT_ENOUGH_HUMAN_TRACE',
  'TOO_MUCH_LIME',
  'NOT_ENOUGH_LIME',
  'TOO_CLEAN',
  'TOO_DESIGNED',
  'TOO_GENERIC',
  'TOO_INFOGRAPHIC',
  'TOO_AI',
  'NOT_BESPOKE_ENOUGH',
  'NOT_NDX',
] as const;

export const FAL_EDITORIAL_PROMPT_SECTION_ORDER = [
  'WHAT_HAPPENED',
  'WHAT_NDX_NOTICED',
  'SINGLE_PRIMARY_EDITORIAL_IDEA',
  'VIEWER_MUST_NOTICE_FIRST',
  'FIRST_SLIDE_SEMANTIC_ROLE',
  'INFORMATION_HIERARCHY',
  'PRIMARY_EVIDENCE',
  'DEFERRED_INFORMATION',
  'NDX_TRACE',
  'TYPOGRAPHIC_ROLE_ASSIGNMENTS',
  'UPPERCASE_GOVERNANCE',
  'READING_PATH',
  'DENSITY_TARGET',
  'MATERIAL_CONDITIONS',
  'COMPOSITIONAL_CONDITIONS',
  'LIME_BEHAVIOR',
  'PHOTOGRAPHIC_RENDERING',
  'NEGATIVE_CONSTRAINTS',
] as const;

export const EDITORIAL_INFORMATION_ARCHITECTURE_IMPLEMENTED = true as const;
export const MESSY_THINKING_VS_PUBLISHED_ARTIFACT_DISTINCTION_IMPLEMENTED = true as const;
export const EDITORIAL_DECISION_MODEL_IMPLEMENTED = true as const;
export const FIRST_SLIDE_SEMANTIC_ROLE_IMPLEMENTED = true as const;
export const FIRST_SLIDE_INFORMATION_BUDGET_IMPLEMENTED = true as const;
export const DEFER_TO_SEQUENCE_SYSTEM_IMPLEMENTED = true as const;
export const CAROUSEL_NARRATIVE_ARCHITECTURE_IMPLEMENTED = true as const;
export const SEQUENCE_CREATIVE_SYSTEM_INTEGRATED = true as const;
export const NDX_TYPOGRAPHIC_GOVERNANCE_IMPLEMENTED = true as const;
export const NDX_UPPERCASE_ONLY_AUTHORED_COPY_ENFORCED = true as const;
export const THREE_TYPOGRAPHIC_ROLES_IMPLEMENTED = true as const;
export const TEXT_DENSITY_GOVERNANCE_IMPLEMENTED = true as const;
export const FEED_DENSITY_RHYTHM_IMPLEMENTED = true as const;
export const SPARSE_ARTIFACT_SUPPORT_IMPLEMENTED = true as const;
export const THREE_DISTANCE_QA_IMPLEMENTED = true as const;
export const ARTIFACT_READING_PATH_IMPLEMENTED = true as const;
export const LIME_USAGE_GOVERNANCE_IMPLEMENTED = true as const;
export const EXPERIMENT_01_V1_PRESERVED = true as const;
export const EXPERIMENT_01_V2_PIPELINE_READY = true as const;
export const CONTENT_OPERATIONS_EDITORIAL_LAYER_INTEGRATED = true as const;
