/**
 * P0.5C.6A — Generic Studio World Authored Artifact constants.
 * Brand consistency through authorship behavior, not repeated layout architecture.
 */

export const AUTHORED_ARTIFACT_SYSTEM_VERSION = 'AUTHORED_ARTIFACT@P0.5C.6A' as const;

/** Generic authority chain — adapters may extend; NDX adapter supplies psychology. */
export const GENERIC_AUTHORED_ARTIFACT_AUTHORITY_CHAIN = [
  'CONTENT_THESIS',
  'VISUAL_SUBJECT_ARTISTIC_PREMISE',
  'RAW_VISUAL_ARTIFACT',
  'BESPOKE_COMPOSITION',
  'AUTHOR_INTERVENTION',
  'HUMAN_HISTORY',
  'EDITORIAL_INFORMATION',
  'CHARACTER_TRACE',
  'SIGNATURE_BRAND_TRACE',
  'FINAL_QA',
] as const;

export const TEMPLATE_FRAME_FAILURE_STATES = [
  'FAIL_TOP_HEADLINE_PANEL',
  'FAIL_BOTTOM_EVIDENCE_PANEL',
  'FAIL_HEADER_BODY_FOOTER_TEMPLATE',
  'FAIL_INFOGRAPHIC_SHELL',
  'FAIL_SYMMETRICAL_INFORMATION_ZONES',
  'FAIL_PRESENTATION_BOARD_COMPOSITION',
  'FAIL_POSTER_TEMPLATE_FRAMING',
  'FAIL_CONTENT_CONTAINER_AROUND_ARTWORK',
] as const;

export const AUTHORED_ARTIFACT_FAILURE_STATES = [
  ...TEMPLATE_FRAME_FAILURE_STATES,
  'FAIL_NO_AUTHORED_ARTIFACT_HISTORY',
  'FAIL_DECORATIVE_HUMAN_MARKS',
  'FAIL_RANDOM_ANALOG_TEXTURE',
  'FAIL_OVER_RESOLVED_GENERATED_GRAPHIC',
  'FAIL_REPEATED_ARTIFACT_GRAMMAR',
  'FAIL_INFORMATION_OUTSIDE_ARTIFACT_WORLD',
] as const;

export const INFORMATION_INHABITATION_MODES = [
  'WRITTEN_ON_IMAGE',
  'NEGATIVE_SPACE_SQUEEZE',
  'TAPED_OVER',
  'ATTACHED_SCRAP',
  'PASTED_FRAGMENT',
  'PARTIALLY_OBSCURING',
  'OBJECT_GEOMETRY_FOLLOW',
  'BESIDE_CIRCLED_EVIDENCE',
  'REPLACING_EARLIER_THOUGHT',
  'CORRECTION_OVERLAY',
  'MARGIN_HANDWRITTEN',
  'EVIDENCE_ATTACHMENT',
  'UNDERNEATH_AFTER_FACT',
] as const;

export const HUMAN_HISTORY_TRACE_TYPES = [
  'CROSSED_OUT_WORDING',
  'REWRITTEN_WORDING',
  'REPOSITIONED_FRAGMENT',
  'TAPE',
  'CROP_MARK',
  'TORN_EDGE',
  'FOLDED_CORNER',
  'HANDWRITING',
  'PEN_CIRCLE',
  'GRAPHITE_NOTE',
  'ATTACHED_RECEIPT',
  'PHOTOCOPY_DEGRADATION',
  'REMOVED_OBJECT_RESIDUE',
  'OVERWRITTEN_CAPTION',
  'LATER_ARROW',
  'POST_DISCOVERY_HIGHLIGHT',
  'CUT_REASSEMBLED',
  'CORRECTION_INSERT',
  'SOURCE_ATTRIBUTION_SCRIBBLE',
  'PARTIALLY_COVERED',
  'STAPLED_EVIDENCE',
  'ABANDONED_IDEA_FAINT',
] as const;

export const STUDIO_WORLD_AUTHORED_ARTIFACT_SYSTEM_IMPLEMENTED = true as const;
export const ARTIFACT_HUMAN_HISTORY_CONTRACT_IMPLEMENTED = true as const;
export const TEMPLATE_FRAME_DETECTION_IMPLEMENTED = true as const;
export const OVER_RESOLVED_ARTIFACT_EVALUATION_IMPLEMENTED = true as const;
export const ARTIFACT_GRAMMAR_DIVERSITY_IMPLEMENTED = true as const;
export const AUTHORED_INTERVENTION_EVALUATION_IMPLEMENTED = true as const;
export const INFORMATION_INHABITS_ARTIFACT_IMPLEMENTED = true as const;
export const CHARACTER_CAUSAL_AUTHORSHIP_PREPARED = true as const;
export const V2_4_CREATED = false as const;
