/**
 * P0.VR.1D.1 — screenshot emulation, moodboard extraction, DOM patch convergence.
 */

export const SCREENSHOT_EMULATION_MODE = 'SCREENSHOT_EMULATION' as const;

export const P0_VR_1D1_LINEAGE = ['P0.VR.1', 'P0.VR.1A', 'P0.VR.1C', 'P0.VR.1D', 'P0.VR.1D.1'] as const;

export const SCREEN_REFERENCE_AUTHORITY_PRIORITY: readonly string[] = [
  'FOUNDER_FULL_SCREEN_REFERENCE',
  'MOOD_BOARD_CROP',
  'HISTORICAL_REFERENCE',
] as const;

export const P0_VR_1D1_FAILURE_TAXONOMY = [
  'FAIL_SCREENSHOT_TREATED_AS_INSPIRATION',
  'FAIL_MOOD_BOARD_NOT_DECOMPOSED',
  'FAIL_MULTIPLE_SCREENS_AVERAGED_TOGETHER',
  'FAIL_SCREEN_REFERENCE_RESOLUTION_INSUFFICIENT',
  'FAIL_FULL_SCREEN_OVERRIDE_NOT_MATCHED',
  'FAIL_VISUAL_SPEC_NOT_TRANSLATED_TO_CODE',
  'FAIL_COMPOSER_REINTERPRETATION',
  'FAIL_LAYOUT_MODEL_REINTERPRETED',
  'FAIL_REFERENCE_DOM_DELTA',
  'FAIL_MOBILE_SCREEN_ORDER_DRIFT',
  'FAIL_TYPOGRAPHY_REFLOW_DRIFT',
  'FAIL_ASSET_PLACEMENT_DRIFT',
  'FAIL_MATCHED_REGION_REWRITTEN',
  'FAIL_PATCH_NOT_CODE_ACTIONABLE',
] as const;

export const CONVERGENCE_FIX_ORDER = [
  'viewport',
  'page_frame',
  'main_columns_rows',
  'major_region_sizes',
  'region_positions',
  'card_dimensions',
  'spacing_gaps',
  'typography_geometry',
  'asset_crop_placement',
  'decorative_styling',
] as const;

export const COMPOSER_RECONSTRUCTION_DIRECTIVES = [
  'BUILD THIS SCREEN USING THE SPEC BELOW.',
  'DO NOT REDESIGN.',
  'DO NOT APPROXIMATE.',
  'DO NOT INFER A SIMILAR STRUCTURE.',
  'THE REFERENCE IMAGE IS THE VISUAL SOURCE OF TRUTH.',
  'THE IMPLEMENTATION SPEC TRANSLATES THAT VISUAL TRUTH INTO CODE.',
  'DO NOT TOUCH LOCKED REGIONS.',
] as const;

export const MOOD_BOARD_RESOLUTION_THRESHOLDS = {
  SUFFICIENT_MIN_PX: 280,
  PARTIAL_MIN_PX: 160,
} as const;
