/**
 * P0.AIO.PUBLIC-WEBSITE.LIVE-LEGACY-AUDIT-RESPONSIVE-CREATIVE-RECONCILIATION-AND-MIGRATION-READINESS1 — export the
 * twenty deliverables (single source: shared/studioos-experience-brain/projects/aio/public-migration.ts + the generated
 * public-migration-evidence.ts).
 *
 *   npx tsx scripts/studioos/aio-public-migration-export.ts
 *
 * Every file in docs/aio/public-migration/ is GENERATED; tests/aioPublicMigration1.test.ts keeps them in sync. Vendored to
 * fsbw all-in-one-enterprises/docs/aio/public-migration/ with a provenance file. Nothing here is deployed.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { aio as brain } from '../../shared/studioos-experience-brain/index.js';

export const AIO_PM_DOCS_DIR = 'docs/aio/public-migration';
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const cell = (s: unknown) => String(s ?? '—').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: unknown[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const S = brain.AIO_PM_STATUS;
const E = brain.AIO_PM_EVIDENCE;
const DEVS = ['s360', 'phone', 'tablet', 'tabletL', 'desktop', 'wide'] as const;
const DEV_NAME: Record<string, string> = { s360: '360', phone: '390', tablet: '834', tabletL: '1194 L', desktop: '1440', wide: '2560' };
const MD_HEAD = (n: string, title: string) => [
  `# ${n} · ${title}`, '',
  '> Generated by `scripts/studioos/aio-public-migration-export.ts` from the Experience Brain. Do not edit by hand.', '',
  `**Sprint:** ${brain.AIO_PM_SPRINT} (${brain.AIO_PM_DATE})  `,
  `**Live site:** ${S.live_site}  `,
  `**Audit basis:** ${S.audit_basis}  `,
  `**Public design:** ${S.public_design}  `,
  `**Review:** ${brain.AIO_PM_LINKS.review}  `,
  `**Rule:** ${brain.AIO_PM_RULE}`, '',
];
const scrollRows = (paths: string[]) => table(['PAGE', ...DEVS.map((d) => DEV_NAME[d])], E.scroll.filter((p) => paths.includes(p.path)).map((p) => [p.path, ...DEVS.map((d) => `${p.before[d].toFixed(2)} → ${p.after[d].toFixed(2)}`)]));
const pct = (b: number, a: number) => `${a <= b ? '−' : '+'}${Math.abs((100 * (a - b)) / b).toFixed(1)}%`;

export function aioPublicMigrationQualityGate() {
  return {
    sprint: brain.AIO_PM_SPRINT,
    gate: {
      PRODUCTION_URL_VERIFIED: 'NO — see the live-site record; the audit is of the source and a local build',
      CURRENT_APP_RENDERED: `YES — ${E.legacy.routes} public routes × 5 sizes = ${E.legacy.renders} renders (local build, demo mode, not production)`,
      FUNCTIONAL_INVENTORY: `${brain.AIO_PM_INVENTORY.length} capabilities classified`,
      KNOWN_ISSUES_REVERIFIED: brain.AIO_PM_ISSUES.map((i) => `${i.id}: ${i.verdict}`).join(' · '),
      COMPOSER_TASKS: `${brain.AIO_PM_COMPOSER_TASKS.length} (P0 ${brain.AIO_PM_COMPOSER_TASKS.filter((t) => t.priority === 'P0').length})`,
      DESKTOP_TABLET_RECOMPOSED: 'YES — candidates, awaiting founder review',
      MOBILE: 'PRESERVED — genuine-issue fixes and required answers only',
      PUBLIC_QA: E.qa.fail === 0 ? `PASSED — ${E.qa.pass}/${E.qa.pass} · ${E.qa.pages} pages × ${E.qa.sizes.length} sizes` : `FAILED — ${E.qa.fail}`,
      PRICES_SHOWN: 'NO — none approved',
      BROKERAGE: 'PAUSED — not activated',
      LIVE_APP_CHANGED: 'NO',
      PRODUCTION_DEPLOYED: 'NO',
      MIGRATION_READY: 'NO — production blockers open',
      FOUNDER_APPROVED: 'NO — AWAITING FOUNDER REVIEW',
    },
    counts: { inventory: brain.AIO_PM_INVENTORY.length, composer_tasks: brain.AIO_PM_COMPOSER_TASKS.length, blockers: brain.AIO_PM_BLOCKERS.length, founder_decisions: brain.AIO_PM_FOUNDER_DECISIONS.length, scroll_pages: E.scroll_all_pages },
    problems: brain.validatePublicMigration(),
    status: S,
    next_gate: brain.AIO_PM_NEXT_GATE,
  };
}

const DOCS: [string, string, () => string[]][] = [
  ['01_LIVE_FUNCTIONAL_INVENTORY.md', 'LIVE FUNCTIONAL INVENTORY', () => [
    '## What could be verified', '', `- Production URL: **${brain.AIO_PM_LIVE.production_url ?? 'NOT VERIFIED'}**`, ...bullets(brain.AIO_PM_LIVE.attempts), `- Domain record: ${brain.AIO_PM_LIVE.domain_record}`, `- Preview: ${brain.AIO_PM_LIVE.preview}`, `- Screen recordings: ${brain.AIO_PM_LIVE.screen_recordings}`, `- Instead: ${brain.AIO_PM_LIVE.local_render}`, `- To audit the deployed site: ${brain.AIO_PM_LIVE.remedy}`, '',
    '## Every capability of the current public site', '',
    table(['ID', 'AREA', 'ROUTE', 'WHAT IT DOES', 'BACKEND', 'CLASSIFICATION', 'EVIDENCE'], brain.AIO_PM_INVENTORY.map((r) => [r.id, r.area, r.route, r.fn, r.backend, r.classes.join(' + '), r.evidence])), '',
    `## The current app, rendered (${E.legacy.renders} renders)`, '', ...bullets(E.legacy.findings), '',
  ]],
  ['02_ROUTE_AND_CONTENT_COMPARISON.md', 'ROUTE AND CONTENT COMPARISON', () => {
    const R = brain.AIO_PM_ROUTES;
    return ['## Matched', '', R.matched, '', '## In the current site, not in the design', '', ...bullets(R.missing_in_design), '', '## New in the design', '', ...bullets(R.new_in_design), '', '## Redirects', '', ...bullets(R.redirects), '', '## Feature conflicts', '', ...bullets(R.conflicts), '', '## Functionality not represented in the design', '', ...bullets(R.unrepresented), '', '## Content differences', '', ...bullets(R.content_differences), '', '## Approval dependencies', '', ...bullets(R.approvals), ''];
  }],
  ['03_PRESERVATION_MATRIX.md', 'REUSE / PRESERVE / REPAIR MATRIX', () => [
    table(['CURRENT ROUTE', 'CURRENT FUNCTION', 'BACKEND DEPENDENCY', 'NEW DESIGN DESTINATION', 'WHAT MUST BE PRESERVED', 'WHAT SHOULD BE RESTYLED', 'SECURITY CONSIDERATIONS', 'MIGRATION RISK', 'TEST REQUIRED', 'CLASSIFICATION'], brain.AIO_PM_INVENTORY.map((r) => [r.route, r.fn, r.backend, r.destination, r.preserve, r.restyle, r.security, r.risk, r.test, r.classes.join(' + ')])), '',
  ]],
  ['04_INTEGRATION_INVENTORY.md', 'INTEGRATION INVENTORY', () => [table(['INTEGRATION', 'WHAT', 'STATUS', 'MIGRATION'], brain.AIO_PM_INTEGRATIONS.map((i) => [i.name, i.what, i.status, i.migration])), '']],
  ['05_VERIFIED_LEGACY_DEPENDENCIES.md', 'VERIFIED LEGACY DEPENDENCIES (KNOWN ISSUES A–H) AND COMPOSER REPAIR TASKS', () => [
    '## Known issues, re-checked against the current source', '', table(['', 'CLAIM', 'VERDICT', 'EVIDENCE', 'TASK'], brain.AIO_PM_ISSUES.map((i) => [i.id, i.claim, i.verdict, i.evidence, i.task])), '',
    '## Composer repair tasks (none performed in this sprint)', '', ...brain.AIO_PM_COMPOSER_TASKS.flatMap((t) => [`### ${t.id} · ${t.priority} · ${t.title}`, '', `- **Files:** ${t.files}`, `- **Do:** ${t.do}`, `- **Accept when:** ${t.accept}`, ...(t.approval ? [`- **Approval:** ${t.approval}`] : []), '']),
  ]],
  ['06_DESKTOP_RECONSTRUCTION.md', 'DESKTOP RECONSTRUCTION (1440 · 2560)', () => [...bullets(brain.AIO_PM_DESIGN.desktop), '', '## Page lengths (screens) — before → after', '', scrollRows(['/', '/services', '/services/permitting', '/services/trip-permits', '/get-started', '/start-your-business', '/roadmap']), '']],
  ['07_TABLET_RECONSTRUCTION.md', 'TABLET RECONSTRUCTION (834 · 1194 LANDSCAPE)', () => [...bullets(brain.AIO_PM_DESIGN.tablet), '']],
  ['08_PROTECTED_MOBILE.md', 'PROTECTED MOBILE (390 · 360)', () => [...bullets(brain.AIO_PM_DESIGN.phone), '', '## Phone lengths (screens) — before → after', '', table(['PAGE', '360', '390'], E.scroll.map((p) => [p.path, `${p.before.s360.toFixed(2)} → ${p.after.s360.toFixed(2)}`, `${p.before.phone.toFixed(2)} → ${p.after.phone.toFixed(2)}`])), '']],
  ['09_HOMEPAGE_SCROLL.md', 'HOMEPAGE SCROLL OPTIMIZATION', () => [
    'The homepage answers, in order: WHO IS AIO (the approved hero, unchanged) · WHAT CAN AIO DO FOR ME (the four live pathways) · WHICH CUSTOMER AM I + WHERE TO BEGIN (start · operate · maintain, each with a first step) · WHY TRUST (the client portal; who does what — no figures) · ROAD READY™ · WHAT NEXT.', '',
    scrollRows(['/']), '', 'The phone grows by the WHERE TO BEGIN box and the fourth trust point (both required answers); the tablet, landscape, desktop and ultra-wide are shorter.', '']],
  ['10_SERVICE_PAGE_SCROLL.md', 'SERVICE-PAGE SCROLL OPTIMIZATION', () => [
    'Every service page establishes: the service and its status · who needs it · what AIO provides · what the customer provides · the process · availability (status, jurisdiction) · what happens after · questions · the next action — with an anchored ON THIS PAGE bar. The second closing band is gone (the next step sits beside QUESTIONS).', '',
    scrollRows(['/services', '/services/permitting', '/services/business-formation', '/services/insurance', '/services/bookkeeping', '/services/trip-permits', '/services/operating-authority-assistance', '/roadmap']), '',
    '## All 52 service pages, total height', '', table(['SIZE', 'BEFORE (px)', 'AFTER (px)', 'CHANGE'], DEVS.map((d) => [DEV_NAME[d], E.service_pages_px[d].before, E.service_pages_px[d].after, pct(E.service_pages_px[d].before, E.service_pages_px[d].after)])), '',
    '## Whole site, total height', '', table(['SIZE', 'BEFORE (px)', 'AFTER (px)', 'CHANGE'], DEVS.map((d) => [DEV_NAME[d], E.totals_px[d].before, E.totals_px[d].after, pct(E.totals_px[d].before, E.totals_px[d].after)])), '',
  ]],
  ['11_INTERACTIVE_JOURNEYS.md', 'INTERACTIVE JOURNEYS', () => [...bullets(brain.AIO_PM_DESIGN.journeys), '', `Motion: ${brain.AIO_PM_DESIGN.motion}`, '']],
  ['12_RESPONSIVE_SCREENSHOTS.md', 'RESPONSIVE SCREENSHOTS', () => [
    `- New design, QA first screens: ${E.screenshots.qa} (AIO_PUBLIC_MIGRATION_READINESS/screens/ — every non-generated page and five representative service pages at 360, 390, 834, 1194, 1440, 2560).`,
    `- Current app, local build: ${E.screenshots.current_app} (AIO_PUBLIC_MIGRATION_READINESS/current-app/ — every public route at 390 and 1440; the 495-render metrics in metrics.json).`,
    `- Boards: ${E.screenshots.boards} (AIO_PUBLIC_MIGRATION_READINESS/boards/ — B-* desktop/tablet beside the phone, C-* before/after full pages, A-* current app).`, '',
    'Every board was looked at, not only checked by script.', '']],
  ['13_INTERACTIVE_REVIEW.md', 'INTERACTIVE REVIEW', () => [`${brain.AIO_PM_LINKS.review}`, '', '- START HERE → A · KEEP WHAT WORKS → B · DESKTOP & TABLET → C · SHORTER PAGES → THE CONNECTED SITE (every page, clickable, in six device frames) → the five page groups, the page tree, reference & recovery.', '']],
  ['14_TYPOGRAPHY_AND_OVERFLOW_QA.md', 'TYPOGRAPHY AND OVERFLOW QA', () => [`Public QA: **${E.qa.pass} passed, ${E.qa.fail} failed** — ${E.qa.pages} pages × ${E.qa.sizes.join(', ')}.`, '', ...bullets(E.qa.checks), '']],
  ['15_ACCESSIBILITY_AND_PERFORMANCE.md', 'ACCESSIBILITY AND PERFORMANCE FINDINGS', () => ['## Current app (local build)', '', ...bullets(E.a11y_perf.current), '', '## New design', '', ...bullets(E.a11y_perf.design), '']],
  ['16_ASSET_MANIFEST.md', 'ASSET MANIFEST', () => [table(['ASSET', 'SOURCE', 'USED', 'STATUS'], brain.AIO_PM_ASSETS.map((a) => [a.asset, a.source, a.used, a.status])), '']],
  ['17_COMPOSER_MIGRATION_HANDOFF.md', 'COMPOSER MIGRATION HANDOFF', () => [...brain.AIO_PM_HANDOFF.flatMap((h) => [`## ${h.section}`, '', h.content, '']), '## Repair tasks', '', table(['ID', 'PRIORITY', 'TITLE', 'ACCEPT WHEN'], brain.AIO_PM_COMPOSER_TASKS.map((t) => [t.id, t.priority, t.title, t.accept])), '']],
  ['18_RELEASE_CHECKLIST.md', 'STAGED RELEASE CHECKLIST', () => [table(['STAGE', 'NAME', 'GATE'], brain.AIO_PM_RELEASE.map((s) => [s.stage, s.name, s.gate])), '', `**${brain.AIO_PM_RULE}** No production deployment was performed in this sprint.`, '']],
  ['19_ROLLBACK_AND_REGRESSION.md', 'ROLLBACK AND REGRESSION PLAN', () => [...bullets(brain.AIO_PM_ROLLBACK), '']],
  ['20_BLOCKERS_AND_DECISIONS.md', 'BLOCKERS AND FOUNDER DECISIONS', () => ['## Production blockers', '', ...bullets(brain.AIO_PM_BLOCKERS), '', '## Founder decisions', '', ...bullets(brain.AIO_PM_FOUNDER_DECISIONS), '', `**Next gate:** ${brain.AIO_PM_NEXT_GATE}`, '']],
];

export function aioPublicMigrationFiles(): Record<string, string> {
  const files: Record<string, string> = {};
  for (const [f, t, body] of DOCS) files[f] = [...MD_HEAD(f.slice(0, 2), t), ...body()].join('\n');
  const g = aioPublicMigrationQualityGate();
  files['README.md'] = [`# AIO PUBLIC WEBSITE — LIVE/LEGACY AUDIT, RESPONSIVE RECONCILIATION, MIGRATION READINESS`, '', '> Generated. Do not edit by hand.', '', `**Sprint:** ${brain.AIO_PM_SPRINT}  `, `**Review:** ${brain.AIO_PM_LINKS.review}  `, `**Next gate:** ${brain.AIO_PM_NEXT_GATE}`, '', table(['GATE', 'VALUE'], Object.entries(g.gate)), '', '## Deliverables', '', ...DOCS.map(([f, t]) => `- [${f.slice(0, 2)} · ${t}](./${f})`), '', `**${brain.AIO_PM_RULE}**`, ''].join('\n');
  files['PUBLIC_MIGRATION.json'] = json({
    sprint: brain.AIO_PM_SPRINT, date: brain.AIO_PM_DATE, base: brain.AIO_PM_BASE, links: brain.AIO_PM_LINKS, status: S, live: brain.AIO_PM_LIVE, rule: brain.AIO_PM_RULE,
    inventory: brain.AIO_PM_INVENTORY, routes: brain.AIO_PM_ROUTES, integrations: brain.AIO_PM_INTEGRATIONS, issues: brain.AIO_PM_ISSUES, tasks: brain.AIO_PM_COMPOSER_TASKS,
    design: brain.AIO_PM_DESIGN, assets: brain.AIO_PM_ASSETS, handoff: brain.AIO_PM_HANDOFF, release: brain.AIO_PM_RELEASE, rollback: brain.AIO_PM_ROLLBACK,
    blockers: brain.AIO_PM_BLOCKERS, decisions: brain.AIO_PM_FOUNDER_DECISIONS, evidence: E, next_gate: brain.AIO_PM_NEXT_GATE,
  });
  files['QUALITY_GATE.json'] = json(g);
  return files;
}

if (process.argv[1]?.endsWith('aio-public-migration-export.ts')) {
  mkdirSync(AIO_PM_DOCS_DIR, { recursive: true });
  const files = aioPublicMigrationFiles();
  for (const [f, body] of Object.entries(files)) writeFileSync(`${AIO_PM_DOCS_DIR}/${f}`, body);
  const g = aioPublicMigrationQualityGate();
  console.log(`exported ${Object.keys(files).length} files to ${AIO_PM_DOCS_DIR} · problems: ${g.problems.length ? g.problems.join('; ') : 'none'}`);
}
