/**
 * P0.AIO.OFFICE.FOUNDER-HOME-WORK-REPORTS-MORE.FOUNDER-APPROVAL-AND-VISUAL-AUTHORITY1 — export the founder's approval of
 * the fifteen design decisions, the internal AIO OFFICE creative-direction profile and the record of the HOME · WORK ·
 * REPORTS · MORE visual authority candidates (single sources: shared/studioos-experience-brain/projects/aio/office-visual-authority.ts,
 * shared/studioos-visual-authority/projects/aio/office-creative-direction-profile.ts).
 *
 *   npx tsx scripts/studioos/aio-office-visual-authority-export.ts
 *
 * Every file in docs/aio/office-visual-authority/ is GENERATED; tests/aioOfficeVisualAuthority1.test.ts keeps them in sync.
 * The renders themselves live in fsbw (AIO_OFFICE_VISUAL_AUTHORITY/), pinned here by sha256. Decisions APPROVED; visuals
 * GENERATED and AWAITING FOUNDER APPROVAL; live implementation NOT AUTHORIZED.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { aio as brain, validateDecisionApprovals } from '../../shared/studioos-experience-brain/index.js';
import { AIO_OFFICE_CREATIVE_DIRECTION_PROFILE as PROFILE, AIO_OFFICE_PROFILE_SCOPE as SCOPE, checkCreativeDirectionProfile } from '../../shared/studioos-visual-authority/index.js';

export const AIO_VA_DOCS_DIR = 'docs/aio/office-visual-authority';
const SPRINT = brain.AIO_VA_SPRINT;
const REC = brain.AIO_DESIGN_RECONCILIATION;
const APPROVALS = brain.AIO_DESIGN_DECISION_APPROVALS;
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const S = brain.AIO_VA_STATUS;
const MD_HEAD = (title: string) => [
  `# ${title}`, '',
  '> Generated by `scripts/studioos/aio-office-visual-authority-export.ts` from the Experience Brain. Do not edit by hand.', '',
  `**Sprint:** ${SPRINT} (${brain.AIO_VA_DATE})  `,
  `**Decisions:** ${S.decisions}  `,
  `**Visuals:** ${S.visuals}  `,
  `**Approval:** ${S.approval}  `,
  `**Implementation:** ${S.implementation}`, '',
];
const decision = (id: string) => REC.decisions.find((d) => d.decision_id === id)!;
const rendersOf = (frame: string) => brain.AIO_VA_RENDERS.filter((r) => r.frame === frame);

export function aioVisualAuthorityQualityGate() {
  const profile = checkCreativeDirectionProfile(PROFILE);
  const approvals = validateDecisionApprovals(REC, APPROVALS);
  const record = brain.validateVisualAuthority();
  const renders = brain.AIO_VA_RENDERS;
  const gate = {
    FOUNDER_DECISIONS_RECORDED: approvals.length === 0 && APPROVALS.length === REC.decisions.length ? 'YES' : 'NO',
    MODIFICATION_RECORDED: APPROVALS.some((a) => a.decision_id === 'D-CREATIVE-PROFILE' && !!a.modification) ? 'YES' : 'NO',
    ORIGINAL_REFERENCE_PRESERVED: REC.reference.file.sha256 === brain.AIO_DESIGN_RECON_REFERENCE_SHA256 ? 'YES' : 'NO',
    DESIGN_PROFILE_READY: profile.status === 'PROFILE_READY' ? 'YES' : 'NO',
    EVERY_ROOT_AT_EVERY_VIEWPORT: record.filter((r) => / frame$/.test(r)).length === 0 ? 'YES' : 'NO',
    EVERY_RENDER_PASSED_VISUAL_QA: renders.every((r) => r.qa_pass) ? 'YES' : 'NO',
    RECORD_CONSISTENT: record.length === 0 ? 'YES' : 'NO',
    VISUALS_APPROVED_BY_FOUNDER: 'NO — AWAITING FOUNDER REVIEW',
    LIVE_IMPLEMENTATION_AUTHORIZED: 'NO',
  };
  return {
    sprint: SPRINT,
    gate,
    counts: { decisions_approved: APPROVALS.length, frames: brain.AIO_VA_FRAMES.length, render_files: renders.length, stand_in_lanes: 7, missing_assets: brain.AIO_VA_MISSING_ASSETS.length },
    problems: [...approvals, ...record, ...profile.missing.map((m) => `profile: ${m}`)],
    status: S,
    next_gate: brain.AIO_VA_NEXT_GATE,
    constraints: { live_routes_changed: false, schemas_changed: false, auth_changed: false, permissions_changed: false, billing_changed: false, client_records_changed: false, ifta_changed: false, migration_changed: false, deployed: false, platform_fee_activated: false, privacy_gaps_fixed: false, openart_used: false },
  };
}

function readmeMd() {
  const g = aioVisualAuthorityQualityGate();
  return [
    ...MD_HEAD('AIO OFFICE — founder approval and visual authority (HOME · WORK · REPORTS · MORE)'),
    'The founder approved all fifteen recommended decisions from the design reconciliation, with one modification: the four-screen visual language becomes the creative foundation of the **internal AIO OFFICE only**. On that basis this package records the decisions, establishes the AIO OFFICE creative-direction profile, and delivers the four pages as visual authority candidates at phone, tablet, desktop and ultra-wide sizes, for founder review.', '',
    '## Status', '',
    table(['', ''], [['Decisions', S.decisions], ['Visuals', S.visuals], ['Approval', S.approval], ['Implementation', S.implementation]]), '',
    '## Quality gate', '',
    table(['Check', 'Result'], Object.entries(g.gate)), '',
    '## Where things are', '',
    table(['What', 'Where'], Object.entries(brain.AIO_VA_LOCATIONS)), '',
    '## Files', '',
    table(['File', 'Deliverable'], [
      ['01_FOUNDER_APPROVAL_RECORD.md', '1 · approval record'],
      ['02_AIO_OFFICE_CREATIVE_DIRECTION_PROFILE.md', '2 · internal AIO OFFICE creative-direction profile'],
      ['03_VISUAL_AUTHORITY_FRAMES.md', '3–15, 18, 19 · every frame with its files, sha256 and QA'],
      ['04_APPROVED_ASSET_REUSE.md', '16 · approved asset reuse manifest (+ new assets)'],
      ['05_MISSING_ASSETS.md', '17 · missing assets and the blocked photo pass'],
      ['06_COMPONENTS_AND_ICONS.md', '18 · shared component and icon guidance'],
      ['07_ORIGINAL_VS_REVISED.md', '19 · original-versus-revised comparison'],
      ['08_RESPONSIVE_AND_ULTRA_WIDE.md', '7–15 · tablet, desktop and ultra-wide compositions'],
      ['09_PERMISSIONS_AND_PRIVACY.md', 'visual decisions that depend on future security work'],
      ['10_COMPOSER_HANDOFF_DRAFT.md', '20 · Composer implementation handoff (DRAFT)'],
      ['VISUAL_AUTHORITY.json', 'the whole record'],
      ['QUALITY_GATE.json', 'gate, counts, constraints'],
    ]), '',
    `**Next gate:** ${brain.AIO_VA_NEXT_GATE}`, '',
  ].join('\n');
}

function approvalMd() {
  return [
    ...MD_HEAD('01 · Founder approval record'),
    `Fifteen decisions, decided by the FOUNDER on ${brain.AIO_VA_DATE}. Each one approves the reconciliation’s recommended option. The reconciliation package itself stays as delivered (its decisions were OPEN at delivery) — this record carries the approvals, so the lineage is kept.`, '',
    'Approving these decisions authorizes **design development only** — not live implementation, security changes, deployment, or automatic approval of the renders built on them.', '',
    table(['Decision', 'Question', 'Approved option', 'Approved as', 'Modification'], APPROVALS.map((a) => {
      const d = decision(a.decision_id);
      return [`${a.decision_id} — ${d.title}`, d.question, d.options[a.chosen_option].option, a.approved_as, a.modification ?? '—'];
    })), '',
  ].join('\n');
}

function profileMd() {
  const c = checkCreativeDirectionProfile(PROFILE);
  const sec = (t: string, xs: readonly string[]) => [`## ${t}`, '', ...bullets(xs), ''];
  return [
    ...MD_HEAD('02 · Internal AIO OFFICE creative-direction profile'),
    `**Profile:** \`${PROFILE.profile_id}\` · check: **${c.status}**${c.missing.length ? ` (missing: ${c.missing.join(', ')})` : ''}`, '',
    '## Scope (the founder’s modification)', '',
    table(['', ''], [['Applies to', SCOPE.applies_to.join(' · ')], ['Does not apply to', SCOPE.does_not_apply_to.join(' · ')], ['Protected', SCOPE.protected.join(' · ')], ['Shared across AIO', SCOPE.shared_across_aio.join(' · ')]]), '',
    ...sec('Brand lines', PROFILE.brand_lines),
    ...sec('Product philosophy', PROFILE.product_philosophy),
    ...sec('Logo system — marks', PROFILE.logo_system.marks),
    ...sec('Logo system — lockups', PROFILE.logo_system.lockups),
    ...sec('Logo system — placement', PROFILE.logo_system.placement_rules),
    ...sec('Logo system — forbidden', PROFILE.logo_system.forbidden),
    ...sec('Colour world', PROFILE.color_world),
    ...sec('Material world', PROFILE.material_world),
    ...sec('Environment world', PROFILE.environment_world),
    ...sec('Object language', PROFILE.object_language),
    ...sec('Typography', PROFILE.typography_direction),
    ...sec('Graphic design rules', PROFILE.graphic_design_rules),
    ['## Wit', '', PROFILE.wit_definition, ''].join('\n'),
    ...sec('Must not become', PROFILE.must_not_become),
    ...sec('Anti-generic rules', PROFILE.anti_generic_rules),
    ...sec('Anti-AI rules', PROFILE.anti_ai_rules),
    '## Renderer', '',
    table(['', ''], Object.entries(PROFILE.renderer).map(([k, v]) => [k, Array.isArray(v) ? v.join(', ') : String(v)])), '',
    ...sec('Provenance', PROFILE.provenance),
  ].join('\n');
}

function framesMd() {
  return [
    ...MD_HEAD('03 · Visual authority frames'),
    `Thirty frames, ${brain.AIO_VA_RENDERS.length} PNG files in fsbw \`AIO_OFFICE_VISUAL_AUTHORITY/\`. Every one is a **CANDIDATE awaiting founder approval**, carries ILLUSTRATIVE SAMPLE DATA (labelled SAMPLE), and passed the automated visual QA read from the rendered DOM. A re-render reproduces every sha256.`, '',
    table(['#', 'Frame', 'Root', 'Viewport', 'Actor', 'Shows', 'Files (sha256)', 'QA'], brain.AIO_VA_FRAMES.map((f) => [
      String(f.deliverable), f.frame, f.root, f.viewport, f.actor, f.shows,
      rendersOf(f.frame).map((r) => `\`${r.file.split('/').pop()}\` ${r.sha256.slice(0, 12)}…`).join('<br>'),
      rendersOf(f.frame).every((r) => r.qa_pass) ? `PASS (${[...new Set(rendersOf(f.frame).flatMap((r) => r.qa_checks))].join(', ')})` : 'FAIL',
    ])), '',
  ].join('\n');
}

function assetsMd() {
  return [
    ...MD_HEAD('04 · Approved asset reuse'),
    table(['Asset', 'Path', 'Used for', 'Status', 'Note'], brain.AIO_VA_ASSET_REUSE.map((a) => [a.asset, `\`${a.path}\``, a.used_for.join(' · ') || '—', a.status, a.note])), '',
    '## New assets created', '',
    table(['Asset', 'Path', 'Note'], brain.AIO_VA_NEW_ASSETS.map((a) => [a.asset, `\`${a.path}\``, a.note])), '',
    'No photograph was generated into the package and no logo was created or redrawn.', '',
  ].join('\n');
}

function missingMd() {
  const p = brain.AIO_VA_PHOTOGRAPHY_PASS;
  return [
    ...MD_HEAD('05 · Missing assets'),
    '## The photo pass', '',
    table(['', ''], [['Status', p.status], ['Attempted', p.attempted], ['Cause', p.cause], ['Fix', p.fix], ['Never used', p.forbidden_providers.join(', ')]]), '',
    '## What is missing', '',
    table(['Asset', 'Needed for', 'Interim in the renders', 'Why missing', 'Brief for the pass'], brain.AIO_VA_MISSING_ASSETS.map((m) => [m.asset, m.needed_for, m.interim, m.why_missing, m.brief])), '',
  ].join('\n');
}

function componentsMd() {
  return [
    ...MD_HEAD('06 · Shared components and icons'),
    'Drawn on `05_COMPONENTS/AIO-OFFICE-COMPONENTS-AND-STATES-1440.png`.', '',
    table(['Component', 'Rule'], brain.AIO_VA_COMPONENTS.map((c) => [c.component, c.rule])), '',
  ].join('\n');
}

function comparisonMd() {
  return [
    ...MD_HEAD('07 · Original versus revised'),
    'Each board shows the founder’s drawing, the revised first screen, the revised full page and what changed (`06_COMPARISON/`). The drawing itself is preserved unchanged in `docs/aio/office-design-reconciliation/reference/`.', '',
    ...brain.AIO_VA_COMPARISON.flatMap((c) => [`## ${c.root}`, '', `Board: \`${c.board}\``, '', '**Preserved from the drawing**', '', ...bullets(c.preserved), '', '**Changed (approved decisions)**', '', ...bullets(c.changed), '']),
  ].join('\n');
}

function responsiveMd() {
  const vp = ['TABLET', 'DESKTOP', 'ULTRA_WIDE'] as const;
  return [
    ...MD_HEAD('08 · Responsive compositions and ultra-wide'),
    'The approved AIO OFFICE staff frame is reused unchanged except that WORK replaces FILING: tablet 77 px header + 113 px dock; desktop 68 px header + 138 px sidebar. Desktop and tablet are their own compositions — they reflow, never scale.', '',
    ...vp.flatMap((v) => [`## ${v.replace('_', '-')}`, '', table(['Frame', 'Actor', 'Composition'], brain.AIO_VA_FRAMES.filter((f) => f.viewport === v).map((f) => [f.frame, f.actor, f.shows])), '']),
    '## Ultra-wide guidance', '', ...bullets(brain.AIO_VA_ULTRA_WIDE), '',
  ].join('\n');
}

function permissionsMd() {
  return [
    ...MD_HEAD('09 · Permissions and privacy'),
    'The visuals show how each area should behave by role and grant. They change no backend permission and fix none of the twelve recorded privacy gaps; each decision below depends on future security work.', '',
    table(['Area', 'Visual decision', 'Depends on'], brain.AIO_VA_PERMISSION_NOTES.map((n) => [n.area, n.visual_decision, n.depends_on.join(' · ')])), '',
    '## Founder versus staff (from the reconciliation, now drawn)', '',
    table(['Area', 'Founder', 'Staff', 'Decided by'], REC.roles.map((r) => [r.area, r.founder, r.staff, r.decided_by])), '',
  ].join('\n');
}

function handoffMd() {
  const h = brain.AIO_VA_COMPOSER_HANDOFF;
  return [
    ...MD_HEAD('10 · Composer implementation handoff — DRAFT'),
    `**${h.status}**  `, `**Gate:** ${h.gate}`, '',
    '## Read first', '', ...bullets(h.read_first), '',
    '## Sequence (after approval)', '', ...bullets(h.sequence), '',
    '## Do not', '', ...bullets(h.do_not), '',
  ].join('\n');
}

export function buildAioVisualAuthorityExports(): Record<string, string> {
  return {
    'README.md': readmeMd(),
    '01_FOUNDER_APPROVAL_RECORD.md': approvalMd(),
    '02_AIO_OFFICE_CREATIVE_DIRECTION_PROFILE.md': profileMd(),
    '03_VISUAL_AUTHORITY_FRAMES.md': framesMd(),
    '04_APPROVED_ASSET_REUSE.md': assetsMd(),
    '05_MISSING_ASSETS.md': missingMd(),
    '06_COMPONENTS_AND_ICONS.md': componentsMd(),
    '07_ORIGINAL_VS_REVISED.md': comparisonMd(),
    '08_RESPONSIVE_AND_ULTRA_WIDE.md': responsiveMd(),
    '09_PERMISSIONS_AND_PRIVACY.md': permissionsMd(),
    '10_COMPOSER_HANDOFF_DRAFT.md': handoffMd(),
    'VISUAL_AUTHORITY.json': json({
      id: 'AIO_OFFICE_VISUAL_AUTHORITY', sprint: SPRINT, date: brain.AIO_VA_DATE, generated_by: 'scripts/studioos/aio-office-visual-authority-export.ts',
      source: ['shared/studioos-experience-brain/projects/aio/office-visual-authority.ts', 'shared/studioos-experience-brain/projects/aio/office-visual-authority-renders.ts', 'shared/studioos-visual-authority/projects/aio/office-creative-direction-profile.ts'],
      status: S, next_gate: brain.AIO_VA_NEXT_GATE, locations: brain.AIO_VA_LOCATIONS,
      reference: REC.reference.file,
      approvals: APPROVALS, profile: { scope: SCOPE, profile: PROFILE, check: checkCreativeDirectionProfile(PROFILE) },
      frames: brain.AIO_VA_FRAMES, renders: brain.AIO_VA_RENDERS,
      assets: { reused: brain.AIO_VA_ASSET_REUSE, created: brain.AIO_VA_NEW_ASSETS, missing: brain.AIO_VA_MISSING_ASSETS, photography_pass: brain.AIO_VA_PHOTOGRAPHY_PASS },
      components: brain.AIO_VA_COMPONENTS, ultra_wide: brain.AIO_VA_ULTRA_WIDE, permissions: brain.AIO_VA_PERMISSION_NOTES, comparison: brain.AIO_VA_COMPARISON, composer_handoff: brain.AIO_VA_COMPOSER_HANDOFF,
    }),
    'QUALITY_GATE.json': json(aioVisualAuthorityQualityGate()),
  };
}

if (process.argv[1] && /aio-office-visual-authority-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_VA_DOCS_DIR, { recursive: true });
  const files = buildAioVisualAuthorityExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_VA_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_VA_DOCS_DIR}`);
}
