/**
 * P0.AIO.CLIENT-MIGRATION-ACTIVATION-AND-OFFICE-PROVISIONING-ARCHITECTURE1 — export the client migration, activation and
 * office provisioning architecture (single sources: shared/studioos-experience-brain/client-lifecycle.ts +
 * projects/aio/client-migration.ts + projects/aio/migration.ts).
 *
 *   npx tsx scripts/studioos/aio-client-migration-export.ts
 *
 * Every file in docs/aio/client-migration/ is GENERATED — edit the TypeScript, never the output.
 * tests/aioClientMigrationActivation1.test.ts keeps them in sync. ARCHITECTURE ONLY · NO PAGE IMPLEMENTATION.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import {
  ACTIVATION_CONDITIONS,
  BATCH_STATES,
  CANONICAL_DOCUMENT_STATUSES,
  CLIENT_ENTRY_TYPES,
  CLIENT_LIFECYCLE_STATES,
  CLIENT_LIFECYCLE_TRANSITIONS,
  CLIENT_REVIEW_STATES,
  CONFIDENCE_LEVELS,
  FACT_SOURCES,
  FOUNDER_CLIENT_SEGMENTS,
  INVITE_MESSAGE_ALLOWED,
  INVITE_STATES,
  LIFECYCLE_ACTORS,
  LIFECYCLE_AUDIT_EVENTS,
  LIFECYCLE_DOMAINS,
  MATCH_CLASSES,
  MIGRATION_EXCEPTIONS,
  MIGRATION_PIPELINE,
  PASSWORD_DELIVERY_FORBIDDEN,
  REVIEW_ACTIONS,
  REVIEW_DECISIONS,
  REVIEW_RESPONSES,
  SOURCE_DOCUMENT_STATES,
  STALENESS,
  VAULT_COMPLETENESS_STATES,
  aio as brain,
  validateExperienceContract,
} from '../../shared/studioos-experience-brain/index.js';

export const AIO_CLIENT_MIGRATION_DOCS_DIR = 'docs/aio/client-migration';
const SPRINT = brain.AIO_MIGRATION_SPRINT;
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const head = (id: string) => ({
  id, sprint: SPRINT, generated_by: 'scripts/studioos/aio-client-migration-export.ts',
  source: ['shared/studioos-experience-brain/client-lifecycle.ts', 'shared/studioos-experience-brain/projects/aio/client-migration.ts', 'shared/studioos-experience-brain/projects/aio/migration.ts'],
  audit: { repo: 'yoteenz/fsbw · all-in-one-enterprises', sha: brain.AIO_MIGRATION_AUDIT_SHA, mode: 'READ-ONLY' },
  constraints: { page_implementation: false, new_paid_generations: 0, openart_accessed: false, ifta_lane_blocked: false, aio_code_changed: false },
});
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map((c) => c.replace(/\|/g, '/')).join(' | ')} |`)].join('\n');
const MD_HEAD = (title: string) => [`# ${title}`, '', '> Generated by `scripts/studioos/aio-client-migration-export.ts` from the Experience Brain. Do not edit by hand.', '', `**Sprint:** ${SPRINT}`, ''];
const transitions = () => CLIENT_LIFECYCLE_TRANSITIONS.map(({ guard: _g, ...t }) => t);

/* ─────────────────────────────── JSON artifacts ─────────────────────────────── */

function lifecycle() {
  return {
    ...head('AIO_CLIENT_LIFECYCLE'),
    invariant: 'PROFILE EXISTS ≠ ACTIVE CLIENT. ACTIVE requires CLIENT_CONFIRMATION_COMPLETE (and every activation condition).',
    actors: LIFECYCLE_ACTORS,
    domains: LIFECYCLE_DOMAINS,
    states: CLIENT_LIFECYCLE_STATES,
    entry_types: CLIENT_ENTRY_TYPES,
    activation_conditions: ACTIVATION_CONDITIONS,
    transitions: transitions(),
    founder_segments: FOUNDER_CLIENT_SEGMENTS,
    audit_events: LIFECYCLE_AUDIT_EVENTS,
    aio: brain.AIO_LIFECYCLE_MAPPING,
  };
}

function pipelineContract() {
  return {
    ...head('AIO_MIGRATION_PIPELINE_CONTRACT'),
    rule: 'No profile mutation before review. Every stage proposes; only APPROVE MIGRATION commits.',
    batch_states: BATCH_STATES,
    document_states: SOURCE_DOCUMENT_STATES,
    pipeline: MIGRATION_PIPELINE,
    file_policy: brain.AIO_MIGRATION_FILE_POLICY,
    document_classes: brain.AIO_DOCUMENT_CLASSES,
    extraction_fields: brain.AIO_MIGRATION_FIELD_RULES,
    confidence: { levels: CONFIDENCE_LEVELS, rule: 'Confidence streamlines review (ordering, bulk confirm of HIGH) but never bypasses the founder’s migration approval.' },
    provenance: { sources: FACT_SOURCES, lineage: ['SOURCE DOCUMENT', 'PAGE / REGION (if available)', 'EXTRACTED FACT', 'CONFIDENCE', 'REVIEWER', 'REVIEW DECISION', 'CANONICAL PROFILE FIELD'] },
    staleness: STALENESS,
    matching: { classes: MATCH_CLASSES, signals: brain.AIO_MATCH_SIGNALS, existing_capabilities: brain.AIO_EXISTING_MATCHING, rule: 'The system proposes LIKELY_MATCH / AMBIGUOUS / NEW_CLIENT_CANDIDATE; only a staff decision yields MATCH_CONFIRMED. Creating a business while a likely match exists needs a recorded reason.' },
    exceptions: MIGRATION_EXCEPTIONS,
  };
}

function reviewContract() {
  return {
    ...head('AIO_MIGRATION_REVIEW_CONTRACT'),
    workspace: 'CLIENT MIGRATION REVIEW (founder / staff)',
    header: ['CLIENT / CANDIDATE', 'MIGRATION BATCH', 'PROCESSING STATUS', 'MATCH STATUS', 'DOCUMENT COUNT'],
    summary: ['PROFILE FACTS FOUND', 'VEHICLES FOUND', 'DRIVERS FOUND', 'SERVICES FOUND', 'DOCUMENTS FOUND', 'CONFLICTS', 'STALE ITEMS', 'UNRESOLVED ITEMS'],
    actions: REVIEW_ACTIONS,
    decisions: REVIEW_DECISIONS,
    primary_completion: 'APPROVE MIGRATION',
    commit_gate: {
      requires: ['identity MATCH_CONFIRMED (staff decision)', 'no fact without a decision', 'no unresolved conflict', 'complete provenance on every fact', 'every required prebuilt field confirmed', 'a canonical home for every confirmed field', 'an approver'],
      writes_only: 'CONFIRMED / EDITED facts, each carrying fact id + reviewer + provenance',
      separately: 'NEEDS CLIENT CONFIRMATION facts become client review items; IGNORED / MARKED STALE / REJECTED stay in history',
      result: 'PREBUILT — NOT ACTIVE',
      targets: brain.AIO_COMMIT_TARGETS,
    },
    experience_contract: brain.AIO_CLIENT_MIGRATION.feature_id,
  };
}

function vaultLineage() {
  return {
    ...head('AIO_VAULT_MIGRATION_LINEAGE'),
    doctrine: ['CURRENT OPERATING TRUTH FIRST.', 'HISTORICAL ARCHIVE SECOND.', 'Never delete a historical source file because a newer record exists.', 'Vault completeness is not business-profile completeness.'],
    lineage_fields: ['client_id', 'organization_id', 'document_type', 'source_migration_batch', 'original_filename', 'sha256', 'ingested_at', 'document_date', 'effective_date', 'expiration_date', 'classification', 'review_status', 'canonical_status', 'superseded_by', 'extracted_fact_ids', 'workspace_relationships'],
    canonical_statuses: CANONICAL_DOCUMENT_STATUSES,
    completeness_states: VAULT_COMPLETENESS_STATES,
    aio_vault: brain.AIO_VAULT_MAPPING,
    current_truth_priority: brain.AIO_CURRENT_TRUTH_PRIORITY,
  };
}

function identityActivation() {
  return {
    ...head('AIO_CLIENT_IDENTITY_AND_ACTIVATION'),
    separation: 'AIO CLIENT IDENTITY ≠ LOGIN EMAIL ≠ OPTIONAL AIO ALIAS',
    identity: brain.AIO_CLIENT_IDENTITY,
    auth: brain.AIO_AUTH_CONTRACT,
    invitation: { states: INVITE_STATES, message_allowed: INVITE_MESSAGE_ALLOWED, message_forbidden: ['any profile fact', 'documents', 'any credential'], template: brain.AIO_INVITE_TEMPLATE },
    passwords: { delivery_forbidden: PASSWORD_DELIVERY_FORBIDDEN, rule: 'The client sets their own password on the activation page (or signs in by magic link). AIO never generates, stores in plain text, emails, texts or reads out a password.', findings_in_aio: brain.AIO_PASSWORD_FINDINGS },
    consents: brain.AIO_REQUIRED_CONSENTS,
    experience_contract: brain.AIO_CLIENT_ACTIVATION.feature_id,
  };
}

function provisioningContract() {
  return {
    ...head('AIO_OFFICE_PROVISIONING_CONTRACT'),
    prebuilt: brain.AIO_PREBUILT_PROVISIONING,
    workspaces: { rule: 'A staff-confirmed service relationship provisions the workspace shell as PENDING_SETUP; it turns ACTIVE only when the client is ACTIVE. Documents alone never activate a workspace — they surface as WE ALSO KNOW ABOUT … REVIEW NEEDED.', map: brain.AIO_WORKSPACE_PROVISIONING },
    after_activation: { composition: ['ACTIVE WITH AIO', 'WE ALSO KNOW ABOUT', 'WORKSPACES THAT MAY HELP'], expansion_placement: 'AFTER_ACTIVATION (never inside the review steps)', proof: brain.aioMigrationProofScenarios().POST_ACTIVATION_OFFICE },
    new_client_convergence: brain.AIO_NEW_CLIENT_CONVERGENCE,
  };
}

function founderSurfaces() {
  return {
    ...head('AIO_FOUNDER_CLIENT_STATUS_SURFACES'),
    segments: brain.AIO_FOUNDER_SEGMENTS,
    active_count_rule: 'Count a client ACTIVE only when lifecycle = ACTIVE and every activation condition holds (isCountedActive). Prebuilt, invited and waiting clients are never in the active count, operational queues for active clients, or active-client metrics.',
    current_count_sites: brain.AIO_CLIENT_COUNT_SITES,
    proof: brain.aioMigrationProofScenarios().FOUNDER_SEGMENTS,
  };
}

function eventsExceptions() {
  return {
    ...head('AIO_CLIENT_MIGRATION_EVENTS_AND_EXCEPTIONS'),
    audit_record_fields: ['event', 'actor', 'actor_role', 'at', 'source', 'subject', 'before', 'after'],
    events: LIFECYCLE_AUDIT_EVENTS,
    aio_event_mapping: brain.AIO_EVENT_MAPPING,
    exceptions: MIGRATION_EXCEPTIONS,
  };
}

/* ─────────────────────────────── markdown ─────────────────────────────── */

function architectureMd() {
  const sc = brain.aioMigrationProofScenarios();
  return [
    ...MD_HEAD('AIO Client Migration, Activation + Office Provisioning — Architecture'),
    '**Founder decision:** EXISTING-CLIENT ONBOARDING IS NOT ACCOUNT CREATION. It is reconciliation between AIO’s existing knowledge and the client’s current business truth.',
    '',
    '```',
    'LEGACY / PHYSICAL CLIENT FILE → MIGRATION INTAKE → EXTRACTION / CLASSIFICATION → FOUNDER REVIEW → PREBUILT CLIENT PROFILE',
    '→ VAULT ORGANIZATION → OFFICE PROVISIONING → ACTIVATION INVITE → CLIENT REVIEW → WHAT CHANGED? → CLIENT CONFIRMATION',
    '→ ACTIVE CLIENT → ACTIVE WORKSPACES → CONTEXTUAL EXPANSION',
    '```',
    '',
    '## Lifecycle',
    '',
    table(['From', 'To', 'Trigger', 'Actor', 'Events'], transitions().map((t) => [t.from, t.to, t.trigger, t.actor, t.events.join(' · ')])),
    '',
    `**PROFILE EXISTS ≠ ACTIVE CLIENT.** ACTIVE requires all of: ${ACTIVATION_CONDITIONS.join(' · ')}. The only way into ACTIVE is CLIENT_CONFIRMATION_REQUIRED → CONFIRM & ENTER MY OFFICE (or resuming a client that was active).`,
    '',
    '### Mapping onto AIO’s existing status fields',
    '',
    table(['Lifecycle', 'Client.accountStatus', 'Archive migration', 'Portal access', 'Counted active'], brain.AIO_LIFECYCLE_MAPPING.map((m) => [m.state, m.client_account_status, m.archive_migration_status, m.portal_access, m.counted_active ? 'YES' : 'no'])),
    '',
    '## Three entry types',
    '',
    table(['Entry', 'Starts at', 'Path'], brain.AIO_ENTRY_TYPES.map((e) => [e.entry_type, e.starts_at, e.path])),
    '',
    '## Migration intake (founder / staff, desktop)',
    '',
    'PC → client folder → batch-scan paper → put PDFs / photos / files together → upload the whole batch. The founder does not classify files first.',
    '',
    'SELECT / CREATE MIGRATION BATCH → SELECT CLIENT OR UNKNOWN CLIENT → UPLOAD FOLDER / FILE BATCH → INGEST → PROCESS → REVIEW → COMMIT VERIFIED DATA → PROVISION PREBUILT OFFICE',
    '',
    `File policy: ${brain.AIO_MIGRATION_FILE_POLICY.accepted.join(' · ')}. ${brain.AIO_MIGRATION_FILE_POLICY.note}`,
    '',
    '### Pipeline (proposes; never commits)',
    '',
    table(['Stage', 'Does', 'Exception'], MIGRATION_PIPELINE.map((p) => [p.stage, p.does, p.failure ?? '—'])),
    '',
    '### Review and commit gate',
    '',
    'Review actions: ' + REVIEW_ACTIONS.join(' · ') + '. Primary completion: **APPROVE MIGRATION** → **PREBUILT (not active)**.',
    '',
    '## Completeness — three separate measures',
    '',
    '```',
    `BUSINESS PROFILE   ${sc.COMPLETENESS.business_profile.pct}% KNOWN`,
    `DOCUMENT VAULT     ${sc.COMPLETENESS.document_vault.state.replace(/_/g, ' ')}`,
    `CLIENT REVIEW      ${sc.COMPLETENESS.client_review.state}`,
    '```',
    '',
    'An empty vault never makes a profile 0 %: staff knowledge and existing records count, with provenance.',
    '',
    '## Current truth first',
    '',
    table(['Priority', 'Domain', 'Required to activate'], brain.AIO_CURRENT_TRUTH_PRIORITY.map((c) => [String(c.priority), c.domain, c.required_for_activation ? 'yes' : 'no — migrates gradually'])),
    '',
    '## Identity and activation',
    '',
    `- **AIO client ID:** ${brain.AIO_CLIENT_IDENTITY.business_identity.format} — ${brain.AIO_CLIENT_IDENTITY.business_identity.rule}`,
    `- **Login email:** ${brain.AIO_CLIENT_IDENTITY.login_email.rule}`,
    `- **Optional AIO alias:** ${brain.AIO_CLIENT_IDENTITY.alias.rule}`,
    `- **Activation:** ${brain.AIO_AUTH_CONTRACT.flow.join(' → ')}`,
    '- **Passwords:** set by the client on the activation page. Never generated, never emailed, texted or read out.',
    '',
    '## Founder status surfaces',
    '',
    table(['Segment', 'Founder hub label', 'Meaning'], brain.AIO_FOUNDER_SEGMENTS.map((s) => [s.segment, s.label, s.meaning])),
    '',
    'Active-client count: lifecycle ACTIVE and every activation condition met — nothing else.',
    '',
  ].join('\n');
}

function firstLoginMd() {
  const sc = brain.aioMigrationProofScenarios();
  return [
    ...MD_HEAD('Existing Client — First Login'),
    'Design doctrine: **SIMPLE · QUICK · CONCISE · TO THE POINT.** This is review, not intake.',
    '',
    table(['Step', 'Shows', 'Client answers'], brain.AIO_FIRST_LOGIN_STEPS.map((s) => [s.step, s.shows, s.answer ?? '—'])),
    '',
    '## Review interaction',
    '',
    `Each section: ${REVIEW_RESPONSES.join(' · ')}. A correct section needs one tap; field-by-field editing only opens for NEEDS AN UPDATE. I’M NOT SURE never blocks — it becomes an AIO follow-up.`,
    '',
    `Client review states: ${CLIENT_REVIEW_STATES.join(' · ')}.`,
    '',
    '## What changed?',
    '',
    table(['Shortcut', 'Routes to', 'Reconciliation', 'Affects'], brain.AIO_WHAT_CHANGED.map((w) => [w.label, w.routes_to, w.reconciliation, w.affects.join(' · ') || '—'])),
    '',
    'A client report never silently overwrites a verified fact: contact changes apply with the prior value kept in history; everything with regulatory or service impact waits for staff.',
    '',
    '## Confirmation gate',
    '',
    'Before: **CLIENT_CONFIRMATION_REQUIRED**. The founder sees PROFILE PREPARED · MIGRATION REVIEW COMPLETE · INVITATION SENT · CLIENT CONFIRMATION PENDING. The client does not count as active.',
    '',
    'Final action: **CONFIRM & ENTER MY OFFICE** → ACTIVE, with CLIENT_CONFIRMED + CLIENT_ACTIVATED events.',
    '',
    '## Proof (fixture)',
    '',
    '```',
    ...sc.ACTIVATION_JOURNEY.steps.map((s) => `${s.step.padEnd(28)} ${s.lifecycle.padEnd(30)} counted active: ${s.counted_active ? 'YES' : 'no'}`),
    '```',
    '',
  ].join('\n');
}

function proofMd() {
  const sc = brain.aioMigrationProofScenarios();
  const v = [brain.AIO_CLIENT_MIGRATION, brain.AIO_CLIENT_ACTIVATION].map((c) => [c.feature_id, validateExperienceContract(c).earned_completion]);
  return [
    ...MD_HEAD('AIO Client Migration — Proof'),
    brain.AIO_MIGRATION_FIXTURE_NOTE,
    '',
    '## Success criteria',
    '',
    table(['Criterion', 'Result', 'Evidence'], sc.CRITERIA.map((c) => [c.criterion, c.pass ? 'PASS' : 'FAIL', c.evidence])),
    '',
    '## Experience Brain',
    '',
    table(['Feature', 'Earned completion'], v as string[][]),
    '',
  ].join('\n');
}

function futureFamiliesMd() {
  return [
    ...MD_HEAD('Future Authority Families (structure only)'),
    'No visual authority exists for these families. Each goes through the Visual Authority Development Gate (territories → reference → founder lock) before any page.',
    '',
    ...brain.AIO_FUTURE_AUTHORITY_FAMILIES.flatMap((f) => [`## ${f.family_id}`, '', `- Actor: ${f.actor} · archetype: ${f.archetype} · primary object: ${f.primary_object}`, `- Zones: ${f.zones.join(' · ')}`, `- Primary action: ${f.primary_action}`, `- Status: ${f.authority_status}`, '']),
  ].join('\n');
}

export function buildAioClientMigrationExports(): Record<string, string> {
  return {
    'AIO_CLIENT_MIGRATION_ARCHITECTURE.md': architectureMd(),
    'AIO_CLIENT_LIFECYCLE.json': json(lifecycle()),
    'AIO_MIGRATION_PIPELINE_CONTRACT.json': json(pipelineContract()),
    'AIO_MIGRATION_REVIEW_CONTRACT.json': json(reviewContract()),
    'AIO_VAULT_MIGRATION_LINEAGE.json': json(vaultLineage()),
    'AIO_CLIENT_IDENTITY_AND_ACTIVATION.json': json(identityActivation()),
    'AIO_EXISTING_CLIENT_FIRST_LOGIN.md': firstLoginMd(),
    'AIO_OFFICE_PROVISIONING_CONTRACT.json': json(provisioningContract()),
    'AIO_FOUNDER_CLIENT_STATUS_SURFACES.json': json(founderSurfaces()),
    'AIO_CLIENT_MIGRATION_EVENTS_AND_EXCEPTIONS.json': json(eventsExceptions()),
    'AIO_CLIENT_MIGRATION_PROOF.md': proofMd(),
    'FUTURE_AUTHORITY_FAMILIES.md': futureFamiliesMd(),
  };
}

if (process.argv[1] && /aio-client-migration-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_CLIENT_MIGRATION_DOCS_DIR, { recursive: true });
  const files = buildAioClientMigrationExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_CLIENT_MIGRATION_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_CLIENT_MIGRATION_DOCS_DIR}`);
}
