/**
 * P0.AIO.OFFICE.UNIFIED-EXPERIENCE2.MATERIAL-MOTION-AND-DETAIL-POLISH1 — export the AIO OFFICE WORKSPACE STYLE and the
 * record of the material, motion and detail pass (single source:
 * shared/studioos-experience-brain/projects/aio/office-workspace-style.ts).
 *
 *   npx tsx scripts/studioos/aio-office-workspace-style-export.ts
 *
 * Every file in docs/aio/office-workspace-style/ is GENERATED; tests/aioOfficeWorkspaceStyle1.test.ts keeps them in
 * sync. The tokens are the ones in fsbw design-authority/aio-office/workspaces/ws.css; fsbw's evidence test holds the
 * vendored STYLE.json to that file. Candidates until the founder reviews; nothing here applies the style elsewhere.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { aio as brain } from '../../shared/studioos-experience-brain/index.js';

export const AIO_WSS_DOCS_DIR = 'docs/aio/office-workspace-style';
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const word = (r: string) => r.replace(/_/g, ' ');
const S = brain.AIO_WSS_STATUS;
const MD_HEAD = (title: string) => [
  `# ${title}`, '',
  '> Generated by `scripts/studioos/aio-office-workspace-style-export.ts` from the Experience Brain. Do not edit by hand.', '',
  `**Sprint:** ${brain.AIO_WSS_SPRINT} (${brain.AIO_WSS_DATE})  `,
  `**Language:** ${S.language}  `,
  `**Proofs:** ${S.proofs}  `,
  `**Review:** ${brain.AIO_WSS_REVIEW_LINK}  `,
  `**Next gate:** ${brain.AIO_WSS_NEXT_GATE}`, '',
];
const tokens = (ts: readonly { name: string; value: string; use: string; min?: number; max?: number }[]) => table(['Token', 'Value', 'Brief range', 'Use'], ts.map((t) => [`\`${t.name}\``, `\`${t.value}\``, t.min != null ? `${t.min}–${t.max}` : '—', t.use]));

export function aioWorkspaceStyleQualityGate() {
  const q = brain.AIO_WSS_QA;
  return {
    sprint: brain.AIO_WSS_SPRINT,
    gate: {
      DESIGN_LANGUAGE_LOCKED: /^LOCKED/.test(S.language) ? 'YES — the four directions refined in place, not redesigned' : 'NO',
      FOUR_DIRECTIONS_RECOGNIZABLE: 'YES — fleet = the vehicle, bookkeeping = the period, compliance = the deadline, Client 360 = the business',
      DEFECTS_A_TO_J: brain.AIO_WSS_DEFECTS.every((d) => d.status === 'FIXED') ? 'FIXED — all ten' : `OPEN — ${brain.AIO_WSS_DEFECTS.filter((d) => d.status !== 'FIXED').map((d) => d.id).join(', ')}`,
      MOTION_INSIDE_THE_BRIEF: brain.AIO_WSS_MOTION.every((t) => parseFloat(t.value) >= t.min! && parseFloat(t.value) <= t.max!) ? 'YES' : 'NO',
      REDUCED_MOTION_HONOURED: 'YES — checked by qa.mjs (no animation over 10 ms; instant drawer and confirmation)',
      NO_CLIPPED_OR_OVERLAPPING_TEXT: Object.values(q.text_audit.this_pass).every((n) => n === 0) ? `YES — ${q.text_audit.states} states × ${q.text_audit.sizes.length} sizes` : 'NO',
      REVIEW_QA_PASSED: q.failures === 0 ? `YES — ${q.checks_run}/${q.checks_run}` : 'NO',
      RECORDINGS: `${q.recordings.count} interactions · last pass and this pass · MP4 + WebM`,
      FOUNDER_RECORDING_INSPECTED: 'NO — not available; states captured directly',
      APPROVED_ROOTS_CHANGED: 'NO',
      EXPANDED_TO_OTHER_LANES: 'NO',
      PUBLIC_SITE_AFFECTED: 'NO — separate',
      LIVE_APP_CHANGED: 'NO',
      FOUNDER_APPROVED: 'NO — AWAITING FOUNDER REVIEW',
      SECURITY_GAPS_FIXED: 'NO — still open; separate Composer work',
    },
    counts: { style_sections: brain.AIO_WS_STYLE.length, defects: brain.AIO_WSS_DEFECTS.length, qa_checks: q.checks_run, screenshots: q.screenshots, recordings: q.recordings.count, audit_states: q.text_audit.states, found_and_fixed: q.found_and_fixed.length },
    problems: brain.validateWorkspaceStyle(),
    status: S,
    next_gate: brain.AIO_WSS_NEXT_GATE,
  };
}

function readmeMd() {
  const g = aioWorkspaceStyleQualityGate();
  return [
    ...MD_HEAD('AIO OFFICE WORKSPACE STYLE — and the material, motion and detail pass'),
    'The four workspace proofs’ design language, locked: every workspace that follows inherits this grammar while keeping its own subject composition. AIO OFFICE only — the public website keeps its own language.', '',
    '## Files', '',
    ...bullets(['01_STYLE.md — the specification: layout, hierarchy, responsive, type, spacing, surfaces, gold, states, panels, drawers, motion, reduced motion, overflow, accessibility, scope; with the tokens', '02_POLISH_PASS.md — what the founder asked, defects A–J, per-workspace refinements, drawers, typography, responsive results, QA, recordings, evidence, what remains, decisions', 'STYLE.json · QUALITY_GATE.json']), '',
    '## Quality gate', '', table(['Check', 'Result'], Object.entries(g.gate).map(([k, v]) => [word(k), v])), '',
    '## Where things are', '', table(['What', 'Where'], Object.entries(brain.AIO_WSS_LOCATIONS).map(([k, v]) => [word(k), v])), '',
  ].join('\n');
}
const styleMd = () => [
  ...MD_HEAD('01 · AIO OFFICE WORKSPACE STYLE'),
  ...brain.AIO_WS_STYLE.flatMap((s) => [`## ${s.title}`, '', ...bullets(s.rules), '']),
  '## Tokens', '',
  '### Type', '', tokens(brain.AIO_WSS_TYPE), '',
  '### Motion', '', tokens(brain.AIO_WSS_MOTION), '', tokens(brain.AIO_WSS_EASING), '',
  '### Surfaces', '', tokens(brain.AIO_WSS_SURFACES), '',
  '### Elevation', '', tokens(brain.AIO_WSS_ELEVATION), '',
].join('\n');
const passMd = () => {
  const q = brain.AIO_WSS_QA;
  const f = brain.AIO_WSS_FOUNDER_FEEDBACK;
  return [
    ...MD_HEAD('02 · The material, motion and detail pass'),
    '## What the founder said', '', '**Liked:**', '', ...bullets(f.liked), '', '**Asked:**', '', ...bullets(f.asked), '',
    `**Founder recording:** ${f.recording}`, '',
    '## Defects A–J', '', table(['', 'Defect', 'Status', 'Fix'], brain.AIO_WSS_DEFECTS.map((d) => [d.id, d.defect, d.status, d.fix])), '',
    '## Refinements by workspace', '', table(['Workspace', 'Refinements'], Object.entries(brain.AIO_WSS_REFINEMENTS).map(([k, v]) => [({ fleet: 'VEHICLES & FLEET', client: 'CLIENT 360', books: 'BOOKKEEPING', comp: 'COMPLIANCE' } as Record<string, string>)[k], v.join(' · ')])), '',
    '## Drawers and popups', '', ...bullets(brain.AIO_WSS_DRAWERS), '',
    '## Typography', '', ...bullets(brain.AIO_WSS_TYPOGRAPHY), '',
    '## Responsive results', '', table(['Device', 'Size', 'Result'], brain.AIO_WSS_RESPONSIVE.map((r) => [word(r.device), r.size, r.result])), '',
    '## Tests actually run', '', table(['', ''], [['Tool', q.tool], ['Checks', `${q.checks_run} run · ${q.failures} failed`], ['Screenshots', `${q.screenshots} (fsbw AIO_OFFICE_WORKSPACE_PROOFS/screens/)`]]), '',
    ...bullets(q.covers), '',
    `### Text audit — ${q.text_audit.states} states at ${q.text_audit.sizes.join(', ')}`, '',
    table(['Count', 'Last pass', 'This pass'], Object.keys(q.text_audit.last_pass).map((k) => [word(k), String(q.text_audit.last_pass[k as keyof typeof q.text_audit.last_pass]), String(q.text_audit.this_pass[k as keyof typeof q.text_audit.this_pass])])), '',
    '### Recordings', '', `${q.recordings.builds}. ${q.recordings.inspected}`, '', ...bullets(q.recordings.list), '',
    '### Found by looking and fixed', '', ...bullets(q.found_and_fixed), '',
    '## Evidence', '', ...bullets([`This pass: ${brain.AIO_WSS_EVIDENCE.boards.join(' · ')}`, `Since Batch 1 (refreshed): ${brain.AIO_WSS_EVIDENCE.boards_since_batch1.join(' · ')}`, brain.AIO_WSS_EVIDENCE.folder]), '',
    '## What remains', '', ...bullets(brain.AIO_WSS_KNOWN_REMAINING), '',
    '## Decisions for the founder', '', ...brain.AIO_WSS_FOUNDER_DECISIONS.map((d, i) => `${i + 1}. ${d}`), '',
  ].join('\n');
};

export function buildAioWorkspaceStyleExports(): Record<string, string> {
  return {
    'README.md': readmeMd(),
    '01_STYLE.md': styleMd(),
    '02_POLISH_PASS.md': passMd(),
    'STYLE.json': json({
      id: 'AIO_OFFICE_WORKSPACE_STYLE', sprint: brain.AIO_WSS_SPRINT, date: brain.AIO_WSS_DATE, generated_by: 'scripts/studioos/aio-office-workspace-style-export.ts',
      source: ['shared/studioos-experience-brain/projects/aio/office-workspace-style.ts'], base: brain.AIO_WSS_BASE,
      status: S, next_gate: brain.AIO_WSS_NEXT_GATE, review_link: brain.AIO_WSS_REVIEW_LINK, locations: brain.AIO_WSS_LOCATIONS,
      tokens: { type: brain.AIO_WSS_TYPE, motion: brain.AIO_WSS_MOTION, easing: brain.AIO_WSS_EASING, surfaces: brain.AIO_WSS_SURFACES, elevation: brain.AIO_WSS_ELEVATION },
      style: brain.AIO_WS_STYLE, founder_feedback: brain.AIO_WSS_FOUNDER_FEEDBACK, defects: brain.AIO_WSS_DEFECTS, refinements: brain.AIO_WSS_REFINEMENTS,
      drawers: brain.AIO_WSS_DRAWERS, typography: brain.AIO_WSS_TYPOGRAPHY, responsive: brain.AIO_WSS_RESPONSIVE, qa: brain.AIO_WSS_QA, evidence: brain.AIO_WSS_EVIDENCE,
      known_remaining: brain.AIO_WSS_KNOWN_REMAINING, founder_decisions: brain.AIO_WSS_FOUNDER_DECISIONS,
    }),
    'QUALITY_GATE.json': json(aioWorkspaceStyleQualityGate()),
  };
}

if (process.argv[1] && /aio-office-workspace-style-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_WSS_DOCS_DIR, { recursive: true });
  const files = buildAioWorkspaceStyleExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_WSS_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_WSS_DOCS_DIR}`);
}
