/**
 * P0.AIO.OFFICE.UNIFIED-EXPERIENCE2.CREATIVE-DIRECTION-AND-WORKSPACE-RECOVERY1 — export the record of the four
 * creative-directed AIO OFFICE workspace proofs (single source:
 * shared/studioos-experience-brain/projects/aio/office-workspace-proofs.ts).
 *
 *   npx tsx scripts/studioos/aio-office-workspace-proofs-export.ts
 *
 * Every file in docs/aio/office-workspace-proofs/ is GENERATED; tests/aioOfficeWorkspaceProofs1.test.ts keeps them in
 * sync. The proofs themselves live in fsbw (design-authority/aio-office/workspaces/). Candidates until the founder
 * approves; nothing here expands the design into the other lanes or authorizes live implementation.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { aio as brain } from '../../shared/studioos-experience-brain/index.js';

export const AIO_WP_DOCS_DIR = 'docs/aio/office-workspace-proofs';
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const word = (r: string) => r.replace(/_/g, ' ');
const S = brain.AIO_WP_STATUS;
const MD_HEAD = (title: string) => [
  `# ${title}`, '',
  '> Generated by `scripts/studioos/aio-office-workspace-proofs-export.ts` from the Experience Brain. Do not edit by hand.', '',
  `**Sprint:** ${brain.AIO_WP_SPRINT} (${brain.AIO_WP_DATE})  `,
  `**Proofs:** ${S.proofs}  `,
  `**Expansion:** ${S.expansion}  `,
  `**Review:** ${brain.AIO_WP_REVIEW_LINK}  `,
  `**Next gate:** ${brain.AIO_WP_NEXT_GATE}`, '',
];
const proof = (id: string) => brain.AIO_WP_PROOFS.find((p) => p.id === id)!;

export function aioWorkspaceProofsQualityGate() {
  const problems = brain.validateWorkspaceProofs();
  return {
    sprint: brain.AIO_WP_SPRINT,
    gate: {
      FOUR_PROOFS_ONLY: brain.AIO_WP_PROOFS.length === 4 ? 'YES — VEHICLES & FLEET · BOOKKEEPING · COMPLIANCE · CLIENT 360' : 'NO',
      DISTINCT_COMPOSITIONS: new Set(brain.AIO_WP_PROOFS.map((p) => p.signature)).size === 4 ? 'YES' : 'NO',
      MAIN_SELECTED_CONTEXT_ACTION_STATES: brain.AIO_WP_PROOFS.every((p) => Object.values(p.states).every(Boolean)) ? 'YES' : 'NO',
      PHONE_TABLET_DESKTOP_ULTRA_WIDE: brain.AIO_WP_DEVICES.length === 4 ? 'YES' : 'NO',
      DESKTOP_FITS_ONE_SCREEN: 'YES — checked by qa.mjs at 1440 × 900 and 2560 × 1440 (and tablet)',
      REVIEW_QA_PASSED: brain.AIO_WP_QA.failures === 0 ? `YES — ${brain.AIO_WP_QA.checks_run}/${brain.AIO_WP_QA.checks_run}` : 'NO',
      SIMULATED_ACTIONS_LABELLED: 'YES — inline confirm says SIMULATED — NOTHING IS SAVED OR SENT',
      SAMPLE_DATA_ONLY: 'YES — no balances, no live data',
      APPROVED_ROOTS_CHANGED: 'NO',
      BATCH1_REGENERATED: 'NO — 619-page review untouched',
      EXPANDED_TO_OTHER_LANES: 'NO — recommendation only',
      FOUNDER_APPROVED: 'NO — AWAITING FOUNDER REVIEW',
      LIVE_APP_CHANGED: 'NO',
      SECURITY_GAPS_FIXED: 'NO — 12 OPEN; separate Composer work',
    },
    counts: { proofs: brain.AIO_WP_PROOFS.length, rules: brain.AIO_WP_RULES.length, demos: Object.values(brain.AIO_WP_DEMOS).flat().length, qa_checks: brain.AIO_WP_QA.checks_run, screenshots: brain.AIO_WP_QA.screenshots, defects_found_and_fixed: brain.AIO_WP_QA.found_and_fixed.length },
    problems,
    status: S,
    next_gate: brain.AIO_WP_NEXT_GATE,
  };
}

function readmeMd() {
  const g = aioWorkspaceProofsQualityGate();
  return [
    ...MD_HEAD('AIO OFFICE — four creative-directed workspace proofs'),
    `> “${brain.AIO_WP_FOUNDER_FEEDBACK.quote}” — founder, on Batch 1`, '',
    'Keep the function, rebuild the look: four representative workspaces, each composed for its work, inside the approved header and five-root navigation. They are the approval benchmark for every workspace that follows.', '',
    '## Files', '',
    ...bullets(['01_DIAGNOSIS.md — A · what was wrong with Batch 1 (with the five boards)', '02_CREATIVE_DIRECTION.md — B · the twelve rules and the answer to the founder', '03_WORKSPACE_PROOFS.md — C–G · the four proofs and their main, selected, context and action states', '04_INTERACTIONS_AND_QA.md — H, N, O · interactions, demonstrations, roles, tests run, defects fixed', '05_DEVICES.md — I, J, K · phone, tablet, desktop and ultra-wide', '06_ASSETS_AND_ROOTS.md — L, M · assets reused and the comparison with the approved roots', '07_FOUNDER_PACKAGE.md — P · review link, walkthrough, decisions required', '08_EXPANSION_AND_DEPENDENCIES.md — Q, R · recommendations for the other lanes (not started) and production / security dependencies', 'WORKSPACE_PROOFS.json · QUALITY_GATE.json']), '',
    '## Quality gate', '', table(['Check', 'Result'], Object.entries(g.gate).map(([k, v]) => [word(k), v])), '',
    '## Where things are', '', table(['What', 'Where'], Object.entries(brain.AIO_WP_LOCATIONS).map(([k, v]) => [word(k), v])), '',
  ].join('\n');
}
const diagnosisMd = () => [
  ...MD_HEAD('01 · Diagnosis — Batch 1 deeper pages'),
  'Boards: fsbw `AIO_OFFICE_WORKSPACE_PROOFS/boards/` (and in the review, WHAT WAS WRONG).', '',
  ...brain.AIO_WP_DIAGNOSIS.flatMap((d) => [`## ${d.title}`, '', `Board: \`${d.board}\``, '', ...bullets(d.findings), '']),
].join('\n');
const directionMd = () => [
  ...MD_HEAD('02 · Creative direction'),
  '## What the founder said', '', `> ${brain.AIO_WP_FOUNDER_FEEDBACK.quote}`, '',
  '## The answer', '', ...bullets(brain.AIO_WP_FOUNDER_FEEDBACK.answer), '',
  '## The twelve rules', '', table(['#', 'Rule', 'What it means'], brain.AIO_WP_RULES.map((r) => [String(r.n).padStart(2, '0'), r.rule, r.detail])), '',
].join('\n');
const proofsMd = () => [
  ...MD_HEAD('03 · The four workspace proofs'),
  ...brain.AIO_WP_PROOFS.flatMap((p) => [
    `## ${p.workspace} — centred on ${p.centered_on.toLowerCase()}`, '',
    p.signature, '',
    table(['Region', 'What it holds'], [['CHOOSE', p.regions.choose], ['WORK', p.regions.work], ['ACT', p.regions.act]]), '',
    table(['State', 'In the proof'], [['Main', p.states.main], ['Selected record', p.states.selected], ['Context', p.states.context], ['Action / workflow', p.states.action]]), '',
    '**Honest states:**', '', ...bullets(p.honest), '',
    '**Not invented:**', '', ...bullets(p.not_invented), '',
    `**IA:** ${p.ia.map((n) => `\`${n}\``).join(' · ')}  `, `**Live app:** ${p.live}`, '',
  ]),
].join('\n');
const qaMd = () => {
  const q = brain.AIO_WP_QA;
  return [
    ...MD_HEAD('04 · Interactions, roles and QA'),
    '## Interactions', '', table(['Workspace', 'Interaction', 'Kind'], brain.AIO_WP_INTERACTIONS.map((i) => [i.workspace === 'all' ? 'ALL' : proof(i.workspace).workspace, i.interaction, word(i.kind)])), '',
    '## TRY demonstrations (press the real controls)', '', table(['Workspace', 'Demonstrations'], Object.entries(brain.AIO_WP_DEMOS).map(([id, d]) => [proof(id).workspace, d.join(' · ')])), '',
    '## Founder and staff', '', table(['Area', 'Founder', 'Staff'], brain.AIO_WP_ROLES.map((r) => [r.area, r.founder, r.staff])), '',
    '## Tests actually run', '', table(['', ''], [['Tool', q.tool], ['Checks', `${q.checks_run} run · ${q.failures} failed`], ['Screenshots', `${q.screenshots} (fsbw AIO_OFFICE_WORKSPACE_PROOFS/screens/)`]]), '',
    ...bullets(q.covers), '',
    '## Defects found by looking and fixed', '', ...bullets(q.found_and_fixed), '',
  ].join('\n');
};
const devicesMd = () => [
  ...MD_HEAD('05 · Devices'),
  ...brain.AIO_WP_DEVICES.flatMap((d) => [`## ${word(d.device)} — ${d.size}`, '', d.rule, '', table(['Workspace', 'Composition'], Object.entries(d.per_workspace).map(([id, c]) => [proof(id).workspace, c])), '']),
].join('\n');
const assetsMd = () => {
  const a = brain.AIO_WP_ASSETS;
  const c = brain.AIO_WP_ROOT_COMPARISON;
  return [
    ...MD_HEAD('06 · Assets and the approved roots'),
    '## Assets', '', table(['', ''], [['Reused', a.reused.join(' · ')], ['Drawn this sprint', a.created.join(' · ')], ['Generated', a.generated], ['Logo', a.logo]]), '',
    '## Same family as the approved roots', '', `Board: \`${c.board}\``, '', '**Same:**', '', ...bullets(c.same), '', '**Different (below the root):**', '', ...bullets(c.different), '',
  ].join('\n');
};
const founderMd = () => [
  ...MD_HEAD('07 · Founder package'),
  `**Review:** ${brain.AIO_WP_REVIEW_LINK}`, '',
  ...brain.AIO_WP_WALKTHROUGH.map((w, i) => `${i + 1}. ${w}`), '',
  '## Decisions required', '', ...brain.AIO_WP_FOUNDER_DECISIONS.map((d, i) => `${i + 1}. ${d}`), '',
].join('\n');
const expansionMd = () => [
  ...MD_HEAD('08 · Expansion (recommendation only) and dependencies'),
  `**${S.expansion}**`, '',
  '## Recommended family for each remaining lane', '', table(['Lane', 'Builds on', 'Recommendation'], brain.AIO_WP_EXPANSION.map((e) => [e.lane, e.family === 'own' ? 'ITS OWN' : proof(e.family).workspace, e.recommendation])), '',
  '## Production and security dependencies', '', table(['Area', 'Dependency', 'Blocks'], brain.AIO_WP_DEPENDENCIES.map((d) => [d.area, d.dependency, d.blocks])), '',
].join('\n');

export function buildAioWorkspaceProofsExports(): Record<string, string> {
  return {
    'README.md': readmeMd(),
    '01_DIAGNOSIS.md': diagnosisMd(),
    '02_CREATIVE_DIRECTION.md': directionMd(),
    '03_WORKSPACE_PROOFS.md': proofsMd(),
    '04_INTERACTIONS_AND_QA.md': qaMd(),
    '05_DEVICES.md': devicesMd(),
    '06_ASSETS_AND_ROOTS.md': assetsMd(),
    '07_FOUNDER_PACKAGE.md': founderMd(),
    '08_EXPANSION_AND_DEPENDENCIES.md': expansionMd(),
    'WORKSPACE_PROOFS.json': json({
      id: 'AIO_OFFICE_WORKSPACE_PROOFS', sprint: brain.AIO_WP_SPRINT, date: brain.AIO_WP_DATE, generated_by: 'scripts/studioos/aio-office-workspace-proofs-export.ts',
      source: ['shared/studioos-experience-brain/projects/aio/office-workspace-proofs.ts'], base: brain.AIO_WP_BASE,
      status: S, next_gate: brain.AIO_WP_NEXT_GATE, review_link: brain.AIO_WP_REVIEW_LINK, locations: brain.AIO_WP_LOCATIONS,
      founder_feedback: brain.AIO_WP_FOUNDER_FEEDBACK, diagnosis: brain.AIO_WP_DIAGNOSIS, rules: brain.AIO_WP_RULES, proofs: brain.AIO_WP_PROOFS,
      interactions: brain.AIO_WP_INTERACTIONS, demos: brain.AIO_WP_DEMOS, roles: brain.AIO_WP_ROLES, devices: brain.AIO_WP_DEVICES, assets: brain.AIO_WP_ASSETS,
      root_comparison: brain.AIO_WP_ROOT_COMPARISON, qa: brain.AIO_WP_QA, walkthrough: brain.AIO_WP_WALKTHROUGH, founder_decisions: brain.AIO_WP_FOUNDER_DECISIONS,
      expansion: brain.AIO_WP_EXPANSION, dependencies: brain.AIO_WP_DEPENDENCIES,
    }),
    'QUALITY_GATE.json': json(aioWorkspaceProofsQualityGate()),
  };
}

if (process.argv[1] && /aio-office-workspace-proofs-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_WP_DOCS_DIR, { recursive: true });
  const files = buildAioWorkspaceProofsExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_WP_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_WP_DOCS_DIR}`);
}
