/**
 * P0.AIO.COMPLETE-PRODUCT-VISUAL-CONVERGENCE.INTERNAL-OFFICE-AND-PUBLIC-WEBSITE1 — export the record of the completed
 * AIO OFFICE and the designed public website (single source: shared/studioos-experience-brain/projects/aio/complete-product.ts).
 *
 *   npx tsx scripts/studioos/aio-complete-product-export.ts
 *
 * Every file in docs/aio/complete-product/ is GENERATED; tests/aioCompleteProduct1.test.ts keeps them in sync. Vendored
 * to fsbw all-in-one-enterprises/docs/aio/complete-product/ with a provenance file. Candidates until the founder reviews.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { aio as brain } from '../../shared/studioos-experience-brain/index.js';

export const AIO_CP_DOCS_DIR = 'docs/aio/complete-product';
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const cell = (s: string) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const word = (r: string) => r.replace(/_/g, ' ');
const S = brain.AIO_CP_STATUS;
const Q = brain.AIO_CP_QA;
const MD_HEAD = (title: string) => [
  `# ${title}`, '',
  '> Generated by `scripts/studioos/aio-complete-product-export.ts` from the Experience Brain. Do not edit by hand.', '',
  `**Sprint:** ${brain.AIO_CP_SPRINT} (${brain.AIO_CP_DATE})  `,
  `**Office:** ${S.office}  `,
  `**Public website:** ${S.public_site}  `,
  `**Office review:** ${brain.AIO_CP_LINKS.office_review}  `,
  `**Public review:** ${brain.AIO_CP_LINKS.public_review}  `,
  `**Next gate:** ${brain.AIO_CP_NEXT_GATE}`, '',
];

export function aioCompleteProductQualityGate() {
  const lanes = brain.AIO_CP_OFFICE.filter((p) => /^\d\d$/.test(p.no));
  return {
    sprint: brain.AIO_CP_SPRINT,
    gate: {
      LOCKED_OFFICE_AUTHORITY_RECOVERED: 'YES — roots, the locked style, the four approved workspaces, the IA tree, sample records, approved IFTA and migration screens',
      INTERNAL_LANES_COMPLETED: `${lanes.length} OF 12 — each built around its own object`,
      REPORTS_MORE_COVERAGE: `${brain.AIO_CP_REPORTS_AREAS.length} REPORTS AREAS · ${brain.AIO_CP_MORE_DESTINATIONS.length} MORE DESTINATIONS`,
      APPROVED_ROOTS_CHANGED: 'NO',
      PUBLIC_PAGE_TREE_RECOVERED: `YES — ${Q.public.pages} pages from AioCoreRoutes.tsx and the catalog`,
      ORIGINAL_PUBLIC_REFERENCE_RECOVERED: 'PARTLY — panel 04 of the founder brand DNA board (homepage first screen); the 2026-08 full-page mocks are not in either repository',
      PUBLIC_DEPLOYED: 'NO',
      OFFICE_QA: Q.office.failures === 0 && Q.office.checks_run ? `PASSED — ${Q.office.checks_run}/${Q.office.checks_run}` : 'NOT RUN',
      PUBLIC_QA: Q.public.failures === 0 ? `PASSED — ${Q.public.checks_run}/${Q.public.checks_run} · ${Q.public.pages} pages × ${Q.public.sizes} sizes` : 'FAILED',
      PRICES_SHOWN: 'NO — none approved',
      BROKERAGE: 'PAUSED — not activated',
      LIVE_APP_CHANGED: 'NO',
      FOUNDER_APPROVED: 'NO — AWAITING FOUNDER REVIEW',
      SECURITY_GAPS_FIXED: 'NO — still open; separate Composer work',
    },
    counts: { office_pages: brain.AIO_CP_OFFICE.length, lanes: lanes.length, public_pages: Q.public.pages, assets: brain.AIO_CP_ASSETS.length, gaps: brain.AIO_CP_GAPS.length, founder_decisions: brain.AIO_CP_FOUNDER_DECISIONS.length },
    problems: brain.validateCompleteProduct(),
    status: S,
    next_gate: brain.AIO_CP_NEXT_GATE,
  };
}

const readme = () => {
  const g = aioCompleteProductQualityGate();
  return [
    ...MD_HEAD('AIO COMPLETE PRODUCT — the completed AIO OFFICE and the public website design'),
    'Stage A completes the internal AIO OFFICE in the locked workspace language: twelve service lanes, HOME, INTAKE, REPORTS and MORE, every link on the unchanged approved roots opening a designed page. Stage B designs the public website from the founder’s recovered brand authority. Design review only — nothing is deployed.', '',
    '## Files', '',
    ...bullets(['01_OFFICE.md — authority recovered, the office tree, the twelve lanes and the deeper pages, the review rule', '02_PUBLIC_WEBSITE.md — reference recovery, the page tree, the homepage, the service family, the rules', '03_QA_AND_SIZES.md — the four sizes and the tests actually run', '04_ASSETS.md — every asset reused and where it came from', '05_COMPOSER_HANDOFF.md — what Composer builds next, and what it must not do', '06_GAPS_AND_DECISIONS.md — what remains and the founder’s decisions', 'COMPLETE_PRODUCT.json · QUALITY_GATE.json']), '',
    '## Quality gate', '', table(['Check', 'Result'], Object.entries(g.gate).map(([k, v]) => [word(k), v])), '',
    '## Status', '', table(['', ''], Object.entries(S).map(([k, v]) => [word(k), v])), '',
  ].join('\n');
};
const office = () => [
  ...MD_HEAD('01 · The complete AIO OFFICE'),
  '## The locked authority, recovered', '', table(['What', 'Where', 'State'], brain.AIO_CP_AUTHORITY.map((a) => [a.what, a.where, a.state])), '',
  '## Every page', '', table(['No.', 'Page', 'Group', 'Under', 'Built around', 'Line', 'TRY', 'Routes'], brain.AIO_CP_OFFICE.map((p) => [p.no, `${p.name}${p.approved ? ' (approved, unchanged)' : ''}`, p.group, p.under, p.built_around, p.line, p.demos.join(' · '), p.routes.join(' · ')])), '',
  ...brain.AIO_CP_OFFICE.filter((p) => p.note).flatMap((p) => [`- **${p.name}:** ${p.note}`]), '',
  '## REPORTS — ten areas', '', ...bullets(brain.AIO_CP_REPORTS_AREAS), '',
  '## MORE — eleven destinations', '', ...bullets(brain.AIO_CP_MORE_DESTINATIONS), '',
  '## Review groups', '', table(['Group', 'Pages'], brain.AIO_CP_REVIEW_GROUPS.map((g) => [g.name, g.pages.join(' · ')])), '',
  '## The review rule', '', brain.AIO_CP_OFFICE_REVIEW_RULE, '',
].join('\n');
const pub = () => {
  const r = brain.AIO_CP_PUBLIC_RECOVERY;
  const h = brain.AIO_CP_PUBLIC_HOME;
  const f = brain.AIO_CP_PUBLIC_FAMILY;
  return [
    ...MD_HEAD('02 · The public website'),
    '## Reference recovery (searched before designing)', '', r.searched, '',
    table(['Found', 'Where', 'Used as'], r.found.map((x) => [x.item, x.where, x.use])), '',
    '**Not found — not substituted:**', '', ...bullets(r.not_found), '', `**Decision:** ${r.decision}`, '',
    '## The page tree', '', table(['Group', 'Pages', 'What'], brain.AIO_CP_PUBLIC_TREE.map((g) => [g.group, String(g.pages), g.note])), '',
    '**Not designed on purpose:**', '', ...bullets(brain.AIO_CP_PUBLIC_NOT_DESIGNED), '',
    `## The homepage — held to ${h.reference}`, '', ...bullets(h.sections), '', '**Matches the reference:**', '', ...bullets(h.matches), '', '**Differs, and why:**', '', ...bullets(h.differs), '',
    `## The service family — held to ${f.reference}`, '', ...bullets(f.grammar), '', table(['Page', 'Job'], f.representatives.map((x) => [x.path, x.job])), '',
    '## Rules kept', '', ...bullets(brain.AIO_CP_PUBLIC_RULES), '',
  ].join('\n');
};
const qa = () => [
  ...MD_HEAD('03 · Sizes and the tests actually run'),
  '## Four sizes, each composed', '', table(['Device', 'Size', 'Office', 'Public website'], brain.AIO_CP_SIZES.map((s) => [word(s.device), s.size, s.office, s.public])), '',
  '## Office', '', table(['', ''], [['Tool', Q.office.tool], ['Checks', `${Q.office.checks_run} run · ${Q.office.failures} failed`], ['Screenshots', String(Q.office.screenshots)], ['Lane checks', `${Q.office.lane_checks.states} state × size renders · ${Q.office.lane_checks.failures} failed`]]), '',
  '## Public website', '', table(['', ''], [['Tool', Q.public.tool], ['Checks', `${Q.public.checks_run} run · ${Q.public.failures} failed`], ['Pages', `${Q.public.pages} × ${Q.public.sizes} sizes`], ['Screenshots', String(Q.public.screenshots)]]), '',
].join('\n');
const assets = () => [...MD_HEAD('04 · Assets reused'), 'Nothing was generated and no paid image credits were used.', '', table(['Asset', 'Source', 'Provenance', 'Used in'], brain.AIO_CP_ASSETS.map((a) => [a.asset, a.source, a.provenance, a.used_in])), ''].join('\n');
const handoff = () => [...MD_HEAD('05 · Composer handoff'), ...brain.AIO_CP_COMPOSER_HANDOFF.flatMap((h) => [`## ${h.area}`, '', '**Build:**', '', ...bullets(h.build), '', '**Do not:**', '', ...bullets(h.do_not), ''])].join('\n');
const gaps = () => [...MD_HEAD('06 · Gaps and founder decisions'), '## What remains', '', ...bullets(brain.AIO_CP_GAPS), '', '## Decisions for the founder', '', ...brain.AIO_CP_FOUNDER_DECISIONS.map((d, i) => `${i + 1}. ${d}`), ''].join('\n');

export function buildAioCompleteProductExports(): Record<string, string> {
  return {
    'README.md': readme(),
    '01_OFFICE.md': office(),
    '02_PUBLIC_WEBSITE.md': pub(),
    '03_QA_AND_SIZES.md': qa(),
    '04_ASSETS.md': assets(),
    '05_COMPOSER_HANDOFF.md': handoff(),
    '06_GAPS_AND_DECISIONS.md': gaps(),
    'COMPLETE_PRODUCT.json': json({
      id: 'AIO_COMPLETE_PRODUCT', sprint: brain.AIO_CP_SPRINT, date: brain.AIO_CP_DATE, generated_by: 'scripts/studioos/aio-complete-product-export.ts',
      source: ['shared/studioos-experience-brain/projects/aio/complete-product.ts'], base: brain.AIO_CP_BASE, links: brain.AIO_CP_LINKS, status: S, next_gate: brain.AIO_CP_NEXT_GATE,
      authority: brain.AIO_CP_AUTHORITY, office: brain.AIO_CP_OFFICE, reports_areas: brain.AIO_CP_REPORTS_AREAS, more_destinations: brain.AIO_CP_MORE_DESTINATIONS, review_groups: brain.AIO_CP_REVIEW_GROUPS, review_rule: brain.AIO_CP_OFFICE_REVIEW_RULE,
      public: { recovery: brain.AIO_CP_PUBLIC_RECOVERY, tree: brain.AIO_CP_PUBLIC_TREE, not_designed: brain.AIO_CP_PUBLIC_NOT_DESIGNED, home: brain.AIO_CP_PUBLIC_HOME, family: brain.AIO_CP_PUBLIC_FAMILY, rules: brain.AIO_CP_PUBLIC_RULES },
      sizes: brain.AIO_CP_SIZES, qa: Q, assets: brain.AIO_CP_ASSETS, composer_handoff: brain.AIO_CP_COMPOSER_HANDOFF, gaps: brain.AIO_CP_GAPS, founder_decisions: brain.AIO_CP_FOUNDER_DECISIONS,
    }),
    'QUALITY_GATE.json': json(aioCompleteProductQualityGate()),
  };
}

if (process.argv[1] && /aio-complete-product-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_CP_DOCS_DIR, { recursive: true });
  const files = buildAioCompleteProductExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_CP_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_CP_DOCS_DIR}`);
}
