/**
 * P0.AIO.OFFICE.FOUNDER-HOME-WORK-REPORTS-MORE.EXISTING-DESIGN-RECONCILIATION1 — export the reconciliation of the
 * founder's four-screen AIO OFFICE design against the office IA and the root authority contracts
 * (single sources: shared/studioos-experience-brain/office-design-reconciliation.ts + projects/aio/office-design-reconciliation.ts).
 *
 *   npx tsx scripts/studioos/aio-office-design-reconciliation-export.ts
 *
 * Every file in docs/aio/office-design-reconciliation/ except reference/ is GENERATED. reference/ holds the founder's
 * image byte for byte. tests/aioOfficeDesignReconciliation1.test.ts keeps them in sync.
 * FIRST DELIVERY ONLY: no image generated, no visual authority approved, no page / nav / route / schema / auth change.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import {
  DESIGN_VIEWPORTS,
  aio as brain,
  drawnFigures,
  iaNode,
  iaPath,
  referenceCoverage,
  validateDesignReconciliation,
  type ContractRef,
  type PageReconciliation,
} from '../../shared/studioos-experience-brain/index.js';

export const AIO_DESIGN_RECON_DOCS_DIR = 'docs/aio/office-design-reconciliation';
const REC = brain.AIO_DESIGN_RECONCILIATION;
const C = brain.AIO_OFFICE_CONTRACTS;
const IA = brain.AIO_OFFICE_IA;
const SPRINT = brain.AIO_DESIGN_RECON_SPRINT;
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const head = (id: string) => ({
  id, sprint: SPRINT, generated_by: 'scripts/studioos/aio-office-design-reconciliation-export.ts',
  source: ['shared/studioos-experience-brain/office-design-reconciliation.ts', 'shared/studioos-experience-brain/projects/aio/office-design-reconciliation.ts', 'shared/studioos-experience-brain/projects/aio/office-contracts.ts'],
  reference: REC.reference.file,
  constraints: { first_delivery_only: true, images_generated: 0, visual_authorities_approved: false, live_nav_changed: false, routes_changed: false, pages_built: false, supabase_schema_changed: false, auth_changed: false, permissions_changed: false, metrics_invented: false, deployed: false },
});

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const MD_HEAD = (title: string) => [
  `# ${title}`, '',
  '> Generated by `scripts/studioos/aio-office-design-reconciliation-export.ts` from the Experience Brain. Do not edit by hand.', '',
  `**Sprint:** ${SPRINT}  `,
  `**Reference:** \`${REC.reference.file.path}\` (${REC.reference.file.width} × ${REC.reference.file.height}, sha256 \`${REC.reference.file.sha256.slice(0, 12)}…\`)  `,
  '**Status:** first delivery — for founder review. Nothing here is approved; no image was generated; nothing in the live app changed.', '',
];
function at(id: string | null): string {
  if (!id) return '—';
  const n = iaNode(IA, id);
  if (!n) return id;
  const p = iaPath(IA, id);
  return n.shell_id === 'AIO_OFFICE' && p.length > 1 ? p.slice(1).join(' → ') : p.join(' → ');
}
const refLabel = (r: ContractRef) => {
  if (r.kind === 'NONE') return '—';
  if (r.kind === 'METRIC') { const m = C.metrics.find((x) => x.metric_id === r.id)!; return `metric ${m.label} (${m.classification}, ${m.state})`; }
  if (r.kind === 'ACTION') { const a = C.roots.flatMap((x) => x.actions).find((x) => x.action_id === r.id)!; return `action ${a.label} (${a.state})`; }
  if (r.kind === 'REGION') { const g = C.roots.flatMap((x) => x.regions).find((x) => x.region_id === r.id)!; return `region ${g.label}`; }
  return at(r.id);
};
const pageOf = (root: string) => REC.pages.find((p) => p.root_id === root)!;
const screenOf = (root: string) => REC.reference.screens.find((s) => s.root_id === root)!;
const decision = (id: string) => REC.decisions.find((d) => d.decision_id === id)!;
const coverage = () => referenceCoverage(REC, C, IA);
const short = (id: string) => at(id).split(' → ').pop()!;

/* ─────────────────────────────── quality gate ─────────────────────────────── */

const yes = (b: boolean) => (b ? 'YES' : 'NO');
const eq = (a: readonly string[], b: readonly string[]) => a.length === b.length && a.every((v, i) => v === b[i]);

export function aioDesignReconciliationQualityGate(fileSha?: string) {
  const violations = validateDesignReconciliation(REC, C, IA);
  const els = REC.reference.screens.flatMap((s) => s.elements);
  const kept = els.filter((e) => e.verdict === 'KEEP' || e.verdict === 'REFINE' || e.verdict === 'ASSET_PASS').length;
  const removed = els.filter((e) => e.verdict === 'REMOVE').length;
  const proposedRefs = (root: string, kind: ContractRef['kind']) => pageOf(root).proposed.filter((s) => s.maps_to.kind === kind).map((s) => s.maps_to.id!);
  const home = C.roots[0];
  const homeProposed = proposedRefs(home.root_id, 'REGION');
  const lanes = proposedRefs('AIO_OFFICE.WORK', 'LANE');
  const entries = proposedRefs('AIO_OFFICE.MORE', 'MORE_ENTRY');
  const placement = brain.AIO_REPORT_DOMAIN_PLACEMENT.map((d) => `AIO_OFFICE.REPORTS.${d.domain}`);
  const figures = drawnFigures(REC, C);
  const unsupported = pageOf('AIO_OFFICE.REPORTS').proposed.filter((s) => s.maps_to.kind === 'METRIC').map((s) => ({ s, m: C.metrics.find((x) => x.metric_id === s.maps_to.id)! })).filter(({ m }) => m.classification === 'DERIVED_UNSUPPORTED' || m.classification === 'NOT_IMPLEMENTED');
  const logo = REC.assets.find((a) => a.asset_id === 'logo-header')!;
  const open = REC.decisions.filter((d) => d.status === 'OPEN');
  const plansDiffer = C.roots.every((r) => DESIGN_VIEWPORTS.every((vp) => REC.responsive.some((p) => p.root_id === r.root_id && p.viewport === vp)) && new Set(REC.responsive.filter((p) => p.root_id === r.root_id).map((p) => p.layout)).size === DESIGN_VIEWPORTS.length);
  const checks: { key: string; value: string; evidence: string }[] = [
    { key: 'ATTACHMENT_INSPECTED', value: yes(REC.reference.screens.length === 4 && els.length > 0 && (fileSha === undefined || fileSha === REC.reference.file.sha256)), evidence: `4 screens, ${els.length} drawn elements inventoried; reference sha256 ${REC.reference.file.sha256.slice(0, 12)}…` },
    { key: 'EXISTING_DESIGN_PRESERVED', value: yes(kept / els.length >= 0.7 && REC.pages.every((p) => p.preserve.length > 0)), evidence: `${kept} of ${els.length} drawn elements kept, refined or re-shot; ${removed} removed (the INTAKE lane tile and card)` },
    { key: 'PAGES_MATCH_CONTRACTS', value: yes(eq(homeProposed, home.regions.map((r) => r.region_id)) && eq(lanes, C.lanes.map((l) => l.lane_id)) && eq(placement, C.roots[2].regions.map((r) => r.region_id)) && eq([...entries].sort(), C.more_entries.map((e) => e.entry_id).sort())), evidence: 'proposed HOME = 8 regions in order · WORK = 12 lanes in order · REPORTS places all 10 domains · MORE = 11 entries' },
    { key: 'WORK_TWELVE_LANES', value: yes(lanes.length === 12 && !lanes.includes('AIO_OFFICE.INTAKE')), evidence: `proposed: ${lanes.map(short).join(' · ')}` },
    { key: 'MORE_ELEVEN_ENTRIES', value: yes(entries.length === 11), evidence: brain.AIO_MORE_PROPOSED_GROUPS.map((g) => `${g.group}: ${g.entries.length}`).join(' · ') },
    { key: 'HOME_NO_SERVICE_OWNERSHIP', value: yes(home.owns.length === 0 && pageOf(home.root_id).proposed.every((s) => s.maps_to.kind === 'ROOT' ? s.maps_to.id === home.root_id : s.maps_to.kind === 'REGION' && s.maps_to.id!.startsWith(home.root_id))), evidence: 'every proposed HOME slot is a HOME region that routes to its owner' },
    { key: 'REPORTS_NO_INVENTED_FIGURES', value: yes(figures.every((f) => !f.production_backed) && unsupported.every(({ s }) => /not connected/i.test(s.treatment))), evidence: `${figures.reduce((n, f) => n + f.figures.length, 0)} drawn figures, all design examples; ${unsupported.length} unsupported metric slot(s) drawn as honest states` },
    { key: 'FOUNDER_STAFF_VISIBILITY_DEFINED', value: yes(C.roots.every((r) => REC.roles.some((x) => x.root_id === r.root_id))), evidence: `${REC.roles.length} rows, each decided by a role or grant, never a name` },
    { key: 'RESPONSIVE_PLAN_INTENTIONAL', value: yes(plansDiffer), evidence: `${REC.responsive.length} plans: 4 roots × ${DESIGN_VIEWPORTS.join(' / ')}; each viewport has its own layout` },
    { key: 'BRANDING_PRESERVED', value: yes(logo.path === 'all-in-one-enterprises/public/migration/brand-lockup.png' && REC.assets.some((a) => a.asset_id === 'logo-global-dotted' && a.status === 'DO_NOT_USE')), evidence: 'header keeps the approved staff lockup; the dotted lockup and invented marks are kept out; no logo regenerated' },
    { key: 'PRODUCTION_CODE_CHANGED', value: 'NO', evidence: 'docs and Brain data only' },
    { key: 'IMAGES_GENERATED', value: '0', evidence: 'regeneration waits for founder approval' },
    { key: 'EXISTING_WORK_DISCARDED', value: 'NO', evidence: 'contracts, IA, IFTA and migration authorities untouched' },
    { key: 'FOUNDER_APPROVAL_REQUIRED', value: yes(open.length > 0 && open.every((d) => d.status === 'OPEN')), evidence: `${open.length} open decisions (${open.filter((d) => d.priority === 'BEFORE_REGENERATION').length} must be decided before regeneration)` },
  ];
  const ready = violations.length === 0 && checks.every((c) => c.value !== 'NO' || ['PRODUCTION_CODE_CHANGED', 'EXISTING_WORK_DISCARDED'].includes(c.key));
  checks.push({ key: 'READY_FOR_FOUNDER_REVIEW', value: yes(ready), evidence: `validator violations ${violations.length}` });
  return { ...head('AIO_DESIGN_RECONCILIATION_QUALITY_GATE'), next_gate: brain.AIO_DESIGN_RECON_NEXT_GATE, checks, coverage: coverage(), violations };
}

/* ─────────────────────────────── 01 audit ─────────────────────────────── */

function auditMd() {
  const figs = drawnFigures(REC, C);
  return [
    ...MD_HEAD('01 · Existing four-screen visual audit'),
    `Four mobile screens, inventoried element by element. Root nav as drawn: **${REC.reference.drawn_nav.join(' · ')}**. Identity as drawn: **${REC.reference.drawn_identity.name} · ${REC.reference.drawn_identity.role_label}** (a sample person).`, '',
    `Every figure and date on the screens is a design example: ${figs.reduce((n, f) => n + f.figures.length, 0)} figures across ${figs.length} elements, none backed by production data.`, '',
    ...REC.reference.screens.flatMap((s) => [
      `## ${short(s.root_id)} — “${s.title_as_drawn}”`, '',
      table(['Element', 'As drawn', 'Stands for', 'Verdict', 'Finding', 'Anti-AI'], s.elements.map((e) => [e.kind, e.label, e.maps_to.map(refLabel).join('<br>'), e.verdict, e.finding, e.anti_ai.map((a) => `${a.flag} (${a.severity.toLowerCase()}): ${a.note}`).join('<br>') || '—'])), '',
    ]),
    '## Across all four', '',
    table(['Topic', 'Finding', 'Verdict', 'Change'], REC.cross_cutting.map((x) => [x.topic, x.finding, x.verdict, x.change])), '',
  ].join('\n');
}

/* ─────────────────────────────── 02–05 pages ─────────────────────────────── */

function pageMd(n: string, p: PageReconciliation, extra: string[] = []) {
  const name = short(p.root_id);
  const cov = coverage().filter((c) => c.root_id.startsWith(p.root_id));
  return [
    ...MD_HEAD(`${n} · ${name} reconciliation`),
    `**Drawn as:** “${screenOf(p.root_id).title_as_drawn}”  `,
    `**Contract:** ${C.roots.find((r) => r.root_id === p.root_id)!.purpose}`, '',
    '## A · What already works', '', ...bullets(p.works), '',
    '## B · What must be preserved', '', ...bullets(p.preserve), '',
    '## C · What is missing', '', ...bullets(p.missing), '',
    '## D · What is incorrect', '', ...bullets(p.incorrect), '',
    '## E · What needs visual refinement', '', ...bullets(p.refine), '',
    '## F · What needs your decision', '', ...bullets(p.founder_decisions.map((d) => `**${d}** — ${decision(d).title}: ${decision(d).question}`)), '',
    '## Coverage (computed from the drawing)', '',
    table(['Set', 'Required', 'Drawn', 'Missing', 'Drawn but not in the set'], cov.map((c) => [c.root_id === p.root_id ? name : `${name} → ${short(c.root_id)}`, String(c.required.length), String(c.drawn.length - c.extra.filter((x) => c.drawn.includes(x)).length), c.missing.map(short).join(' · ') || '—', c.extra.map((x) => (x.startsWith('AIO_OFFICE') ? short(x) : x)).join(' · ') || '—'])), '',
    '## Current versus required', '',
    table(['Topic', 'Current design', 'Required experience', 'Recommended change'], p.current_vs_required.map((r) => [r.topic, r.current, r.required, r.change])), '',
    '## The revised page (mobile reading order)', '',
    table(['Slot', 'Shows', 'How', 'Photo / icon'], p.proposed.map((s) => [s.label, refLabel(s.maps_to), s.treatment, s.asset ?? '—'])), '',
    ...extra,
  ].join('\n');
}

const homeMd = () => pageMd('02', pageOf('AIO_OFFICE.HOME'));
const workMd = () => pageMd('03', pageOf('AIO_OFFICE.WORK'));
const reportsMd = () => pageMd('04', pageOf('AIO_OFFICE.REPORTS'), [
  '## Where each of the ten report areas goes', '',
  'Not all ten on one screen. Each area appears where it is useful: a headline figure on the overview, its own view, history, detail (the owning WORK / MORE item) and export.', '',
  table(['Area', 'On the overview', 'Its own view', 'History', 'Detail', 'Export', 'Today'], brain.AIO_REPORT_DOMAIN_PLACEMENT.map((d) => [short(`AIO_OFFICE.REPORTS.${d.domain}`), d.overview ?? '—', d.own_view, d.history ?? '—', d.detail ?? '—', d.export ?? '—', d.state_today])), '',
]);
const moreMd = () => pageMd('05', pageOf('AIO_OFFICE.MORE'), [
  '## Proposed groups (D-MORE-GROUPS)', '',
  table(['Group', 'Entries'], brain.AIO_MORE_PROPOSED_GROUPS.map((g) => [g.group, g.entries.map((e) => short(`AIO_OFFICE.MORE.${e}`)).join(' · ')])), '',
]);

/* ─────────────────────────────── 06–10 ─────────────────────────────── */

function vsMd() {
  return [
    ...MD_HEAD('06 · Existing versus required'),
    'Computed from the drawing: what each page shows of what its contract requires.', '',
    table(['Set', 'Required', 'Drawn', 'Missing', 'Drawn but not in the set'], coverage().map((c) => [at(c.root_id) === c.root_id ? c.root_id : at(c.root_id), String(c.required.length), String(c.drawn.length), c.missing.map(short).join(' · ') || '—', c.extra.map((x) => (x.startsWith('AIO_OFFICE') ? short(x) : x)).join(' · ') || '—'])), '',
    ...REC.pages.flatMap((p) => [`## ${short(p.root_id)}`, '', table(['Topic', 'Current design', 'Required experience', 'Recommended change'], p.current_vs_required.map((r) => [r.topic, r.current, r.required, r.change])), '']),
    '## Drawn figures', '',
    table(['Page', 'Element', 'Figures', 'Would need', 'Production-backed'], drawnFigures(REC, C).map((f) => [short(f.root_id), f.element_id, f.figures.join(' · '), f.metrics.join(' · ') || '— (count only)', f.production_backed ? 'yes' : 'no — design example'])), '',
  ].join('\n');
}

function changesMd() {
  return [
    ...MD_HEAD('07 · Recommended changes'),
    'In plain words, page by page. Each change keeps the drawing’s look; where a choice is yours, it is listed in 08.', '',
    ...REC.pages.flatMap((p) => [`## ${short(p.root_id)}`, '', ...bullets(p.current_vs_required.map((r) => `**${r.topic}:** ${r.change}`)), '', ...bullets(p.refine.map((x) => `Refine: ${x}`)), '']),
    '## Across all four pages', '',
    ...bullets(REC.cross_cutting.map((x) => `**${x.topic}:** ${x.change}`)), '',
    '## Founder and staff see different things', '',
    'The same frame for everyone; what fills it depends on the person’s role and grants — never on their name.', '',
    table(['Area', 'Page', 'Founder', 'Staff', 'Decided by'], REC.roles.map((r) => [r.area, short(r.root_id), r.founder, r.staff, r.decided_by])), '',
    '## Areas touched by the recorded privacy gaps', '',
    'These pages are staff-only, but they show or link to data affected by the 12 privacy gaps recorded in the contract sprint. The design labels the difference; the repairs need their own security sprint.', '',
    table(['Gap', 'Area', 'What the design does / what still waits'], REC.privacy_touchpoints.map((x) => [x.gap_id, x.area, x.effect])), '',
  ].join('\n');
}

function decisionsMd() {
  return [
    ...MD_HEAD('08 · Open founder decisions'),
    `${REC.decisions.length} decisions. **${REC.decisions.filter((d) => d.priority === 'BEFORE_REGENERATION').length} must be decided before regeneration**; the rest proceed with the recommendation unless you say otherwise. Nothing is decided here.`, '',
    ...REC.decisions.flatMap((d) => [
      `## ${d.decision_id} — ${d.title}`, '',
      `${d.priority === 'BEFORE_REGENERATION' ? '**Decide before regeneration.**' : 'Proceeds with the recommendation unless you change it.'} Pages: ${d.roots.map(short).join(' · ')}`, '',
      d.question, '',
      table(['Option', 'What it means', ''], d.options.map((o, i) => [o.option, o.effect, i === d.recommended_option ? 'RECOMMENDED' : ''])), '',
      `**Recommendation:** ${d.recommendation}`, '',
    ]),
  ].join('\n');
}

function responsiveMd() {
  return [
    ...MD_HEAD('09 · Responsive design plan'),
    'Built on the approved AIO responsive blueprint (`AIO_CLIENT_MIGRATION_RESPONSIVE_BLUEPRINT/`): MOBILE below 700 px, TABLET 700–1023 px, DESKTOP from 1024 px, and WIDE from about 1600 px. **Reflow, never scale.** The phone screens are not stretched; tablet and desktop get their own compositions inside the approved frame (desktop: header bar + left menu; tablet: compact header + touch dock), with WORK in place of FILING.', '',
    ...REC.pages.flatMap((p) => [
      `## ${short(p.root_id)}`, '',
      table(['Viewport', 'Navigation', 'Hero', 'Layout', 'Reading order', 'Notes'], DESIGN_VIEWPORTS.map((vp) => REC.responsive.find((x) => x.root_id === p.root_id && x.viewport === vp)!).map((x) => [x.viewport, x.nav, x.hero, x.layout, x.order.map((id) => p.proposed.find((s) => s.slot_id === id)!.label.split(' · ').pop()!).join(' → '), x.notes || '—'])), '',
    ]),
  ].join('\n');
}

function assetsMd() {
  return [
    ...MD_HEAD('10 · Asset preservation and reuse plan'),
    'Reuse approved assets first. The founder’s composite is a reference only: it is 1536 × 1024 for all four screens, and crops, inpaints or upscales of reference boards are forbidden as production imagery. Anything new goes to one controlled asset pass after approval. The AIO logo is never regenerated.', '',
    table(['Asset', 'What', 'Path (fsbw)', 'Plan', 'Used for', 'Why'], REC.assets.map((a) => [a.asset_id, a.what, a.path ? `\`${a.path}\`` : '—', a.status, a.used_for.join(' · ') || '—', a.reason])), '',
    '## Rules for the asset pass', '',
    ...bullets([
      'Same subjects the founder chose; high-resolution masters framed for mobile, tablet and desktop.',
      'No legible generated text on paperwork, clipboards or screens; any real text is AIO typography composited afterwards.',
      'No invented marks or emblems; where a mark appears it is the approved lockup, composited.',
      'People look like professionals at work, faces visible.',
      'No two lanes share a near-identical scene.',
      'Each candidate passes the studio anti-AI audit before it is shown for approval.',
    ]), '',
  ].join('\n');
}

const ARTIFACTS: [string, string][] = [
  ['01_EXISTING_FOUR_SCREEN_AUDIT.md', 'Every drawn element: what it stands for, verdict, finding, anti-AI flags'],
  ['02_HOME_RECONCILIATION.md', 'HOME: works · preserve · missing · incorrect · refine · decisions · revised page'],
  ['03_WORK_RECONCILIATION.md', 'WORK: the twelve lanes, card signals, MY WORK'],
  ['04_REPORTS_RECONCILIATION.md', 'REPORTS: backed figures only, where each of the ten areas goes'],
  ['05_MORE_RECONCILIATION.md', 'MORE: eleven entries in four groups'],
  ['06_EXISTING_VS_REQUIRED.md', 'Computed coverage and every current-vs-required row'],
  ['07_RECOMMENDED_CHANGES.md', 'Changes in plain words, founder vs staff, privacy touchpoints'],
  ['08_FOUNDER_DECISIONS.md', 'Open decisions with options and recommendations'],
  ['09_RESPONSIVE_DESIGN_PLAN.md', 'Mobile, tablet, desktop and wide plans per page'],
  ['10_ASSET_PRESERVATION_PLAN.md', 'What to reuse, fix, keep out, and shoot in the asset pass'],
  ['DESIGN_RECONCILIATION.json', 'Everything above, machine-readable'],
  ['QUALITY_GATE.json', 'The sprint gate, computed'],
  ['reference/AIO_OFFICE_FOUR_SCREEN_REFERENCE.png', 'The founder’s four-screen design, byte for byte'],
];

function readmeMd(fileSha?: string) {
  const gate = aioDesignReconciliationQualityGate(fileSha);
  return [
    ...MD_HEAD('AIO OFFICE — existing design reconciliation'),
    'Your four-screen design for HOME, WORK, REPORTS and MORE, held against the approved office structure and authority contracts. The look stays. Most changes complete or correct the content; a handful of choices are yours.', '',
    '## In short', '',
    ...bullets([
      'HOME already has the right shape. The three cards need the items behind them, and quick actions are missing. WORK ACROSS AIO needs all twelve lanes and no INTAKE tile.',
      'WORK has the right photographic directory. INTAKE’s card becomes VEHICLES & FLEET, so all twelve lanes fit the same 3 × 4 grid.',
      'REPORTS keeps its premium feel, but only figures the system can back may appear. Client growth, the percentage changes and “estimated revenue” become honest “not connected yet” states.',
      'MORE is clean but misses GROWTH / CRM, BILLING and ACCOUNT, and “ADDITIONAL TOOLS” reads like a junk drawer. Four named groups fix both.',
      'Across all four: uppercase text (AIO rule), larger small text, one consistent set of sample figures, and repaired photos (fake paperwork text, an invented logo on the MORE notebook).',
    ]), '',
    '## Artifacts', '',
    table(['File', 'What'], ARTIFACTS.map(([f, w]) => [`[${f}](${f})`, w])), '',
    '## Quality gate', '',
    table(['Check', 'Value', 'Evidence'], gate.checks.map((c) => [c.key, c.value, c.evidence])), '',
    `**Next gate:** ${brain.AIO_DESIGN_RECON_NEXT_GATE}. No regeneration or implementation before your approval.`, '',
  ].join('\n');
}

export function buildAioDesignReconciliationExports(fileSha?: string): Record<string, string> {
  return {
    'README.md': readmeMd(fileSha),
    '01_EXISTING_FOUR_SCREEN_AUDIT.md': auditMd(),
    '02_HOME_RECONCILIATION.md': homeMd(),
    '03_WORK_RECONCILIATION.md': workMd(),
    '04_REPORTS_RECONCILIATION.md': reportsMd(),
    '05_MORE_RECONCILIATION.md': moreMd(),
    '06_EXISTING_VS_REQUIRED.md': vsMd(),
    '07_RECOMMENDED_CHANGES.md': changesMd(),
    '08_FOUNDER_DECISIONS.md': decisionsMd(),
    '09_RESPONSIVE_DESIGN_PLAN.md': responsiveMd(),
    '10_ASSET_PRESERVATION_PLAN.md': assetsMd(),
    'DESIGN_RECONCILIATION.json': json({ ...head('AIO_DESIGN_RECONCILIATION'), next_gate: brain.AIO_DESIGN_RECON_NEXT_GATE, ...REC, coverage: coverage(), drawn_figures: drawnFigures(REC, C), report_domain_placement: brain.AIO_REPORT_DOMAIN_PLACEMENT, more_groups: brain.AIO_MORE_PROPOSED_GROUPS }),
    'QUALITY_GATE.json': json(aioDesignReconciliationQualityGate(fileSha)),
  };
}

export const referenceSha256 = (root = '.') => createHash('sha256').update(readFileSync(`${root}/${REC.reference.file.path}`)).digest('hex');

if (process.argv[1] && /aio-office-design-reconciliation-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_DESIGN_RECON_DOCS_DIR, { recursive: true });
  const files = buildAioDesignReconciliationExports(referenceSha256());
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_DESIGN_RECON_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_DESIGN_RECON_DOCS_DIR}`);
}
