/**
 * P0.AIO.OFFICE-IA.FOUNDER-WORK-TREE-AND-CLIENT-OFFICE-CANONICALIZATION1 — export the AIO office information architecture
 * (single sources: shared/studioos-experience-brain/office-information-architecture.ts + projects/aio/office-ia.ts).
 *
 *   npx tsx scripts/studioos/aio-office-ia-export.ts
 *
 * Every file in docs/aio/office-ia/ is GENERATED — edit the TypeScript, never the output.
 * tests/aioOfficeIaWorkTree1.test.ts keeps them in sync. ARCHITECTURE ONLY: no page, nav, route, schema, lifecycle or auth change.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import {
  REQUIRED_WORKSPACE_STATES,
  aio as brain,
  iaChildren,
  iaDescendants,
  iaNode,
  iaPath,
  iaRootNav,
  validateOfficeInformationArchitecture,
  type IaNode,
  type IaService,
} from '../../shared/studioos-experience-brain/index.js';
import { aioIfta } from '../../shared/studioos-visual-authority/index.js';

export const AIO_OFFICE_IA_DOCS_DIR = 'docs/aio/office-ia';
const IA = brain.AIO_OFFICE_IA;
const SPRINT = brain.AIO_OFFICE_IA_SPRINT;
const G = brain.AIO_OFFICE_IA_QUALITY_GATE;
const PG = brain.AIO_IA_PRODUCT_GRAPH_MAP;
const MAS = brain.AIO_MIGRATION_AUTHORITY_SET;
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const head = (id: string) => ({
  id, sprint: SPRINT, lineage_id: IA.lineage_id, generated_by: 'scripts/studioos/aio-office-ia-export.ts',
  source: ['shared/studioos-experience-brain/office-information-architecture.ts', 'shared/studioos-experience-brain/projects/aio/office-ia.ts'],
  audit: { repo: 'yoteenz/fsbw · all-in-one-enterprises', sha: brain.AIO_OFFICE_IA_AUDIT_SHA, mode: 'READ-ONLY' },
  constraints: { architecture_only: true, visual_redesign: false, images_generated: 0, visual_authorities_modified: false, live_nav_changed: false, routes_changed: false, supabase_schema_changed: false, client_lifecycle_changed: false, auth_changed: false, deployed: false },
});

const n = (id: string) => iaNode(IA, id)!;
const at = (id: string) => iaPath(IA, id).join(' → ');
const cell = (s: string) => s.replace(/\|/g, '\\|');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const MD_HEAD = (title: string) => [`# ${title}`, '', '> Generated by `scripts/studioos/aio-office-ia-export.ts` from the Experience Brain office information architecture. Do not edit by hand.', '', `**Sprint:** ${SPRINT}  `, `**Lineage:** \`${IA.lineage_id}\`  `, `**Audit:** yoteenz/fsbw @ \`${brain.AIO_OFFICE_IA_AUDIT_SHA.slice(0, 8)}\` (read-only)`, ''];
const impl = (x: Pick<IaNode, 'implementation' | 'depth'>) => (x.implementation === 'IMPLEMENTATION_PARTIAL' ? `PARTIAL · ${x.depth}` : x.implementation === 'IMPLEMENTED' ? 'IMPLEMENTED' : 'NOT STARTED');
const routesOf = (x: IaNode) => x.routes.map((r) => `\`${r.path}\`${r.status === 'EXISTING' ? '' : ` (${r.status})`}`).join(' · ') || '—';
const STATUS_KEY = 'IMPLEMENTED = production-backed behaviour · PARTIAL · FUNCTIONAL_DEMO = works on the demo store · PARTIAL · READ_ONLY = views without actions · PARTIAL · GENERIC_PIPELINE = only the universal service-request pipeline · PARTIAL · PRODUCTION_BACKED = wired to Supabase but incomplete · NOT STARTED = no surface or model.';

/* ─────────────────────────────── derived facts ─────────────────────────────── */

const lanes = () => iaChildren(IA, 'AIO_OFFICE.WORK').filter((x) => x.kind === 'SERVICE_LANE');
const notStartedFor = (s: IaService) => IA.nodes.filter((x) => x.service_ids.includes(s.service_id) && x.implementation === 'IMPLEMENTATION_NOT_STARTED').map((x) => x.label);
/** The nearest staff ancestor's approved client-safe projection. */
function projectionOf(x: IaNode): string | null {
  for (let c: IaNode | undefined = x; c; c = c.parent ? iaNode(IA, c.parent) : undefined) if (c.client_projection) return c.client_projection;
  return null;
}
/** How staff reach a client-office node's data from AIO OFFICE (never by entering the client shell). */
function staffReach(c: IaNode): string[] {
  for (let p: IaNode | undefined = c; p && p.kind !== 'SHELL'; p = p.parent ? iaNode(IA, p.parent) : undefined) {
    const direct = IA.nodes.filter((s) => s.client_projection === p!.node_id).map((s) => s.node_id);
    if (direct.length) return direct;
    const viaService = [...new Set(IA.services.filter((s) => p!.service_ids.includes(s.service_id)).flatMap((s) => s.staff_nodes))];
    if (viaService.length) return viaService;
  }
  return ['AIO_OFFICE.MORE.CLIENTS'];
}
const firewalled = new Set(IA.firewall.flatMap((f) => f.node_ids));
const migrationAuthorityRefs = () => IA.nodes.flatMap((x) => x.authority_refs.filter((a) => a.startsWith('AIO-MIG-')).map((a) => ({ authority_id: a, node_id: x.node_id })));
const notStartedNodes = () => IA.nodes.filter((x) => x.implementation === 'IMPLEMENTATION_NOT_STARTED');

/* ─────────────────────────────── quality gate ─────────────────────────────── */

const eq = (a: readonly string[], b: readonly string[]) => a.length === b.length && a.every((v, i) => v === b[i]);
const yes = (b: boolean) => (b ? 'YES' : 'NO');

export function aioOfficeIaQualityGate() {
  const founderNav = iaRootNav(IA, 'AIO_OFFICE');
  const clientNav = iaRootNav(IA, 'CLIENT_OFFICE');
  const home = iaChildren(IA, 'AIO_OFFICE.HOME');
  const reports = iaChildren(IA, 'AIO_OFFICE.REPORTS');
  const more = iaChildren(IA, 'AIO_OFFICE.MORE');
  const mig = migrationAuthorityRefs();
  const migIds = new Set(mig.map((m) => m.authority_id));
  const intakeOrGate = (id: string) => id.startsWith('AIO_OFFICE.INTAKE') || id === 'CLIENT_OFFICE.ACTIVATION';
  const iftaAuth = ['AIO.OFFICE.WS.IFTA', 'AIO.IFTA.STAFF.QUEUE', 'AIO.CLIENT_OFFICE.WS.IFTA'];
  const iftaTree = new Set(aioIfta.AIO_IFTA_TREE.map((x) => x.node_id));
  const workspaceIds = new Set(brain.AIO_WORKSPACES.map((w) => w.workspace_id));
  const clientWs = IA.nodes.filter((x) => x.shell_id === 'CLIENT_OFFICE' && x.workspace_ids.length);
  const prebuilt = brain.AIO_LIFECYCLE_MAPPING.find((m) => m.state === 'PREBUILT');
  const violations = validateOfficeInformationArchitecture(IA);
  const checks: { key: string; value: string; evidence: string }[] = [
    { key: 'FOUNDER_ROOT_NAV', value: founderNav.join(' · '), evidence: 'AIO_OFFICE shell root_nav = its ROOT_DESTINATION children (validator)' },
    { key: 'CLIENT_ROOT_NAV', value: clientNav.join(' · '), evidence: 'CLIENT_OFFICE shell root_nav = its ROOT_DESTINATION children (validator)' },
    { key: 'ROOT_FILING_SUPERSEDED', value: yes(!founderNav.includes('FILING') && IA.supersessions.some((s) => s.old_item === 'FILING (root)' && s.disposition === 'SUPERSEDED')), evidence: `supersession FILING (root) → WORK · ${IA.lineage_id}` },
    { key: 'FILING_REHOMED_UNDER_WORK', value: yes(eq(iaPath(IA, 'AIO_OFFICE.WORK.FILING_FUEL_TAXES'), G.NEW_FILING_LOCATION) && eq(iaPath(IA, 'AIO_OFFICE.WORK.FILING_FUEL_TAXES.IFTA'), G.NEW_IFTA_LOCATION)), evidence: `${at('AIO_OFFICE.WORK.FILING_FUEL_TAXES.IFTA')}` },
    { key: 'INTAKE_STAFF_ONLY', value: yes(IA.nodes.filter((x) => x.node_id.startsWith('AIO_OFFICE.INTAKE')).every((x) => x.visibility.CLIENT === 'HIDDEN') && firewalled.has('AIO_OFFICE.INTAKE')), evidence: 'every INTAKE node CLIENT = HIDDEN; INTAKE is a firewall item' },
    { key: 'CLIENT_INTAKE_EXPOSURE', value: yes(IA.nodes.some((x) => x.shell_id === 'CLIENT_OFFICE' && (x.role === 'ENTRY' || x.routes.some((r) => r.path === '/office' || r.path.startsWith('/office/'))))), evidence: 'no ENTRY role and no /office route in the client shell (validator)' },
    { key: 'FULL_AIO_SERVICE_SCOPE_REPRESENTED', value: yes(G.REQUIRED_SERVICES.every((id) => IA.services.some((s) => s.service_id === id && s.staff_nodes.length > 0)) && lanes().length === 11), evidence: `${G.REQUIRED_SERVICES.length} required services mapped · ${lanes().length} WORK lanes` },
    { key: 'HOME_DEFINED_AS_PROJECTION', value: yes(n('AIO_OFFICE.HOME').role === 'COMMAND' && home.every((r) => r.role === 'PROJECTION' && r.projects.length > 0) && eq(home.map((r) => r.label), G.HOME_REGIONS)), evidence: `${home.length} regions, every one PROJECTION with named owners` },
    { key: 'WORK_DEFINED_AS_PRODUCTION', value: yes(n('AIO_OFFICE.WORK').role === 'PRODUCTION' && iaDescendants(IA, 'AIO_OFFICE.WORK').every((x) => x.role === 'PRODUCTION')), evidence: 'WORK and every lane / section role = PRODUCTION' },
    { key: 'REPORTS_DEFINED_AS_OVERSIGHT', value: yes(n('AIO_OFFICE.REPORTS').role === 'OVERSIGHT' && reports.length === 10 && reports.every((r) => r.role === 'OVERSIGHT' && r.data_status !== null)), evidence: `${reports.length} domains, each with a data status` },
    { key: 'MORE_DEFINED_AS_SECONDARY', value: yes(n('AIO_OFFICE.MORE').role === 'SECONDARY' && eq(more.map((r) => r.label), G.MORE_ENTRIES) && more.every((r) => r.role === 'SECONDARY')), evidence: `${more.length} entries, none PRODUCTION / ENTRY / COMMAND / PROJECTION` },
    { key: 'CLIENT_SERVICE_ENTITLEMENT_MODEL_PRESERVED', value: yes(REQUIRED_WORKSPACE_STATES.join('|') === 'ACTIVE|AVAILABLE_NOT_ACTIVATED|NOT_APPLICABLE' && brain.AIO_EXPANSION_RULES.length > 0 && clientWs.every((x) => x.workspace_ids.every((w) => workspaceIds.has(w)) && (x.client_resolution === 'ENTITLEMENT' || x.client_resolution === 'APPLICABILITY'))), evidence: `${clientWs.length} client workspace nodes resolve through the Brain workspace resolver (${REQUIRED_WORKSPACE_STATES.join(' · ')}) + ${brain.AIO_EXPANSION_RULES.length} expansion rules` },
    { key: 'PREBUILT_NOT_ACTIVE', value: yes(prebuilt?.counted_active === false), evidence: 'AIO_LIFECYCLE_MAPPING PREBUILT counted_active = false; CLIENT_OFFICE.ACTIVATION gate unchanged' },
    { key: 'IFTA_AUTHORITY_PRESERVED', value: yes(iftaAuth.every((id) => iftaTree.has(id)) && iftaAuth.every((id) => IA.nodes.some((x) => x.authority_refs.includes(id)))), evidence: 'IFTA tree nodes unchanged and re-associated (WORK → FILING & FUEL TAXES → IFTA · OPERATIONS → FILING / IFTA)' },
    { key: 'MIGRATION_AUTHORITY_PRESERVED', value: yes(migIds.size === MAS.total - MAS.superseded.length && mig.length === migIds.size && mig.every((m) => intakeOrGate(m.node_id)) && MAS.superseded.every((x) => !migIds.has(x.authority_id))), evidence: `${MAS.approved} approved + ${MAS.founder_review_required.length} under founder review re-associated once (staff → INTAKE, client → activation gate); ${MAS.superseded.length} superseded draft kept as lineage` },
    { key: 'EXPERIENCE_BRAIN_UPDATED', value: yes(violations.length === 0), evidence: `office-information-architecture.ts + projects/aio/office-ia.ts · validator violations ${violations.length}` },
    { key: 'PRODUCT_GRAPH_UPDATED', value: yes(PG.containers.length === 8 && PG.families.length === 18), evidence: 'AIO_IA_PRODUCT_GRAPH_MAP (8 containers · 18 families · 4 role projections); vendored to fsbw src/product-graph as an overlay' },
    { key: 'VISUAL_REDESIGN_PERFORMED', value: 'NO', evidence: 'no page, image or visual authority touched' },
    { key: 'LIVE_IMPLEMENTATION_CHANGED', value: 'NO', evidence: 'no route, nav, schema, lifecycle or auth change' },
  ];
  return { ...head('AIO_OFFICE_IA_QUALITY_GATE'), checks, violations };
}

/* ─────────────────────────────── 01 / 02 trees ─────────────────────────────── */

function treeJson(id: string): unknown {
  const x = n(id);
  return {
    node_id: x.node_id, label: x.label, kind: x.kind, role: x.role, architecture: x.architecture, implementation: x.implementation, depth: x.depth,
    ...(x.client_resolution ? { client_resolution: x.client_resolution } : {}),
    ...(x.data_status ? { data_status: x.data_status } : {}),
    routes: x.routes.map((r) => `${r.path}${r.status === 'EXISTING' ? '' : ` (${r.status})`}`),
    ...(x.workspace_ids.length ? { workspaces: x.workspace_ids } : {}),
    ...(x.service_ids.length ? { services: x.service_ids } : {}),
    children: iaChildren(IA, id).map((c) => treeJson(c.node_id)),
  };
}

function treeLines(id: string, depth: number): string[] {
  const x = n(id);
  const tags = [x.role, impl(x), x.client_resolution ? `client: ${x.client_resolution}` : '', x.data_status ?? '', x.architecture === 'CANDIDATE_UNRESOLVED' ? 'CANDIDATE' : ''].filter(Boolean).join(' · ');
  const line = `${'  '.repeat(depth)}- **${x.label}** — ${tags}${x.routes.length ? ` — ${routesOf(x)}` : ''}`;
  return [line, ...iaChildren(IA, id).flatMap((c) => treeLines(c.node_id, depth + 1))];
}

function shellMd(shellId: 'AIO_OFFICE' | 'CLIENT_OFFICE', title: string, extra: string[]) {
  const shell = IA.shells.find((s) => s.shell_id === shellId)!;
  const roots = shell.root_nav.map((id) => n(id));
  return [
    ...MD_HEAD(title),
    `**Root navigation:** ${iaRootNav(IA, shellId).join(' · ')}`,
    '',
    shell.semantics,
    '',
    `Scope: \`${shell.scope}\` · actors: ${shell.actors.join(', ')} · environment: \`${shell.environment_id}\` · route root: \`${shell.route_root}\``,
    '',
    ...extra,
    '## Root destinations',
    '',
    table(['#', 'Destination', 'Role', 'What it is', 'Implementation', 'Children'], roots.map((r, i) => [String(i + 1), r.label, r.role, r.semantics, impl(r), String(iaChildren(IA, r.node_id).length)])),
    '',
    '## Full tree',
    '',
    ...iaChildren(IA, shellId).flatMap((c) => treeLines(c.node_id, 0)),
    '',
    `_Status key:_ ${STATUS_KEY}`,
    '',
  ].join('\n');
}

const founderTreeMd = () => shellMd('AIO_OFFICE', '01 · AIO OFFICE — founder / staff tree', [
  'FILING is no longer a root item. It is a WORK lane: **AIO OFFICE → WORK → FILING & FUEL TAXES**, and IFTA lives at **AIO OFFICE → WORK → FILING & FUEL TAXES → IFTA** (canonical case identity unchanged).',
  '',
  'HOME = projection · INTAKE = entry (staff / founder only) · WORK = production · REPORTS = oversight · MORE = secondary. Founder and staff see the same tree; no founder-only node is asserted (Q-FOUNDER-ROLE).',
  '',
  `### WORK lanes (${lanes().length})`,
  '',
  table(['Lane', 'Sections', 'Brain workspaces', 'Implementation', 'Office routes today'], lanes().map((l) => [l.label, iaChildren(IA, l.node_id).map((s) => s.label).join(' · ') || '—', l.workspace_ids.join(' · ') || '— (not a workspace)', impl(l), routesOf(l)])),
  '',
  '### WORK authority contract — cross-service production hub',
  '',
  'The capabilities the founder requires, each with today’s truth. Nothing here is invented: PARTIAL means the capability exists somewhere, not across WORK.',
  '',
  table(['Capability', 'Today', 'Evidence', 'Note'], brain.AIO_WORK_CAPABILITIES.map((c) => [c.capability, impl(c), c.evidence.join(' · '), c.note])),
  '',
  '### Case identity (unchanged)',
  '',
  `A case is PROJECT + CLIENT / ORG + WORKSPACE + CASE TYPE + SUBCONTEXT (\`canonicalCaseKey\`, operating-environment.ts). Its office location is not part of its identity, so moving FILING under WORK changes no key: e.g. \`${brain.AIO_IFTA_CASES[0].case_key}\`.`,
  '',
]);

const clientTreeMd = () => shellMd('CLIENT_OFFICE', '02 · CLIENT OFFICE — client tree', [
  'INTAKE is never part of the client office. The client meets only the activation gate (confirmation before ACTIVE), which renders without staff navigation.',
  '',
  '### How each destination resolves for one client',
  '',
  table(['Resolution', 'Meaning'], [
    ['ALWAYS', 'Every client.'],
    ['APPLICABILITY', 'Only where the client’s type makes it real (a shipper has no trucks).'],
    ['ENTITLEMENT', 'Through the Brain workspace resolver: ACTIVE → shown in its destination · AVAILABLE_NOT_ACTIVATED → SERVICES and approved contextual placements only (expansion rules) · NOT_APPLICABLE → never promoted.'],
    ['STATE', 'Only while a lifecycle state holds (the activation gate: INVITED · CLIENT_CONFIRMATION_REQUIRED). PREBUILT is not ACTIVE.'],
  ]),
  '',
  `The landing (today MY OFFICE at \`/portal\`) is recorded as **${n('CLIENT_OFFICE.HUB').label}** (${n('CLIENT_OFFICE.HUB').architecture}) — not an eighth root (Q-CLIENT-HUB).`,
  '',
]);

/* ─────────────────────────────── 03 actor visibility matrix ─────────────────────────────── */

function visibilityRows() {
  return IA.nodes.filter((x) => x.kind !== 'SHELL').map((x) => {
    const staffShell = x.shell_id === 'AIO_OFFICE';
    const proj = staffShell ? projectionOf(x) : null;
    return {
      node_id: x.node_id, path: at(x.node_id), kind: x.kind,
      FOUNDER: x.visibility.FOUNDER, STAFF: x.visibility.STAFF, CLIENT: x.visibility.CLIENT,
      firewall: firewalled.has(x.node_id),
      client_safe_projection: firewalled.has(x.node_id) ? null : proj,
      staff_reach: staffShell ? null : staffReach(x),
      client_resolution: x.client_resolution,
      staff_gate: x.staff_gate,
    };
  });
}

function visibilityMd() {
  const rows = visibilityRows();
  const roots = [...IA.shells.flatMap((s) => s.root_nav)].map((id) => rows.find((r) => r.node_id === id)!);
  return [
    ...MD_HEAD('03 · Actor visibility matrix'),
    '**FULL** — the actor works in it · **CLIENT_SAFE_PROJECTION** — the actor sees an approved client-safe projection · **VIA_AIO_OFFICE** — staff reach the same client data from AIO OFFICE (client context), never by entering the client shell · **HIDDEN** — never shown.',
    '',
    'FOUNDER and STAFF share the internal office (ExperienceActor FOUNDER_STAFF). No founder-only node is asserted until a founder role exists (Q-FOUNDER-ROLE); existing office permissions keep gating where they already do (never broadened).',
    '',
    '## Root destinations',
    '',
    table(['Destination', 'FOUNDER', 'STAFF', 'CLIENT', 'Client sees instead / staff reach'], roots.map((r) => [r.path, r.FOUNDER, r.STAFF, r.CLIENT, r.staff_reach ? `staff: ${r.staff_reach.map(at).join(' · ')}` : r.firewall ? 'nothing (firewall)' : r.client_safe_projection ? at(r.client_safe_projection) : 'nothing'])),
    '',
    '## Staff / client firewall',
    '',
    table(['Never client-visible', 'Nodes', 'Why'], IA.firewall.map((f) => [f.item, f.node_ids.map(at).join(' · '), f.reason])),
    '',
    '## Every node',
    '',
    table(['Node', 'FOUNDER', 'STAFF', 'CLIENT', 'Client-safe projection', 'Staff reach (client nodes)', 'Client resolution', 'Existing gate'], rows.map((r) => [
      r.path, r.FOUNDER, r.STAFF, r.firewall ? `${r.CLIENT} (firewall)` : r.CLIENT,
      r.client_safe_projection ? at(r.client_safe_projection) : '—',
      r.staff_reach ? r.staff_reach.map(at).join(' · ') : '—',
      r.client_resolution ?? '—', r.staff_gate ?? '—',
    ])),
    '',
  ].join('\n');
}

/* ─────────────────────────────── 04 / 05 service maps + crosswalk ─────────────────────────────── */

const clientLocation = (s: IaService) => (s.client_nodes.length ? s.client_nodes.map(at).join(' · ') : s.client_visibility === 'STAFF_ONLY' ? '— (staff only)' : '— unresolved (see notes)');
const implCell = (s: IaService) => {
  const ns = notStartedFor(s);
  return `${s.architecture} · ${s.implementation} — ${s.implementation_detail}${ns.length ? ` Not started: ${ns.join(', ')}.` : ''}`;
};

export function serviceCrosswalk() {
  return IA.services.map((s) => ({
    service_id: s.service_id,
    SERVICE: s.name,
    'STAFF LOCATION': s.staff_nodes.map(at),
    'CLIENT LOCATION': s.client_nodes.map(at),
    'CLIENT VISIBILITY': `${s.client_visibility} — ${s.client_visibility_note}`,
    'CURRENT IMPLEMENTATION STATUS': { architecture: s.architecture, implementation: s.implementation, detail: s.implementation_detail, not_started_nodes: notStartedFor(s) },
    'CANONICAL DATA SOURCE': s.canonical_data_source,
    NOTES: s.notes,
    workspace_ids: s.workspace_ids,
    feature_refs: s.feature_refs,
    evidence: s.evidence,
  }));
}

function crosswalkMd() {
  return [
    ...MD_HEAD('SERVICE CROSSWALK — every AIO service, staff side and client side'),
    `${IA.services.length} services: the ${G.REQUIRED_SERVICES.length} the founder listed plus CLIENT MIGRATION / INTAKE (staff only). Every service is ARCHITECTURALLY_CANONICAL; implementation is reported as it is today.`,
    '',
    table(['SERVICE', 'STAFF LOCATION', 'CLIENT LOCATION', 'CLIENT VISIBILITY', 'CURRENT IMPLEMENTATION STATUS', 'CANONICAL DATA SOURCE', 'NOTES'], IA.services.map((s) => [
      s.name, s.staff_nodes.map(at).join(' · '), clientLocation(s), `${s.client_visibility} — ${s.client_visibility_note}`, implCell(s), s.canonical_data_source, s.notes,
    ])),
    '',
  ].join('\n');
}

function staffMapMd() {
  return [
    ...MD_HEAD('04 · Service → staff workspace map'),
    'Where each service is worked in AIO OFFICE. A WORK lane is a production location; a Brain workspace is the entitlement unit (client × workspace). A lane may carry several workspaces and a workspace may surface in more than one lane section.',
    '',
    table(['Service', 'Staff location', 'Brain workspaces', 'Case types', 'Office routes today', 'Implementation'], IA.services.map((s) => [
      s.name,
      s.staff_nodes.map(at).join(' · '),
      s.workspace_ids.join(' · ') || '— (not a workspace)',
      [...new Set(s.workspace_ids.flatMap((w) => brain.AIO_WORKSPACES.find((x) => x.workspace_id === w)?.active_case_types ?? []))].join(' · ') || '—',
      [...new Set(s.staff_nodes.flatMap((id) => n(id).routes.filter((r) => r.status === 'EXISTING').map((r) => `\`${r.path}\``)))].join(' · ') || '—',
      `${s.implementation} — ${s.implementation_detail}`,
    ])),
    '',
    '## Lane → Brain workspace',
    '',
    table(['Lane', 'Workspaces', 'Section → workspace'], lanes().map((l) => [l.label, l.workspace_ids.join(' · ') || '—', iaChildren(IA, l.node_id).map((s) => `${s.label}: ${s.workspace_ids.join('/') || '—'}`).join(' · ') || '—'])),
    '',
    'Open: the Brain COMPLIANCE workspace bundles authority + BOC-3 + safety while the founder tree puts authority and BOC-3 under PERMITTING & AUTHORITIES (Q-COMPLIANCE-SPLIT).',
    '',
  ].join('\n');
}

function clientMapMd() {
  return [
    ...MD_HEAD('05 · Service → client destination map'),
    'Where each service appears in CLIENT OFFICE, and how it resolves for one client. A service is shown in its destination only when its workspace is ACTIVE; AVAILABLE_NOT_ACTIVATED services appear in SERVICES and approved contextual placements; NOT_APPLICABLE services are never promoted.',
    '',
    table(['Service', 'Client destination', 'Resolution', 'Client routes today', 'Visibility rule'], IA.services.map((s) => [
      s.name,
      clientLocation(s),
      [...new Set(s.client_nodes.map((id) => n(id).client_resolution ?? '—'))].join(' · ') || s.client_visibility,
      [...new Set(s.client_nodes.flatMap((id) => n(id).routes.filter((r) => r.status === 'EXISTING').map((r) => `\`${r.path}\``)))].join(' · ') || '—',
      s.client_visibility_note,
    ])),
    '',
    `Contextual expansion stays governed by the Brain expansion rules (${brain.AIO_EXPANSION_RULES.length} rules in projects/aio/office.ts); the five legacy generic AVAILABLE fallbacks are not reused.`,
    '',
    '## Contextual expansion rule → Brain mechanism',
    '',
    table(['Founder rule', 'Kind', 'Enforced by'], brain.AIO_EXPANSION_CRITERIA.map((c) => [c.founder_rule, c.kind, c.brain_mechanism])),
    '',
  ].join('\n');
}

/* ─────────────────────────────── 06 supersession ─────────────────────────────── */

export function supersessionMap() {
  return {
    ...head('AIO_OFFICE_IA_SUPERSESSION_MAP'),
    old_root_nav: ['HOME', 'INTAKE', 'FILING', 'REPORTS', 'MORE'],
    new_root_nav: iaRootNav(IA, 'AIO_OFFICE'),
    old_root_filing_status: 'SUPERSEDED',
    new_filing_location: iaPath(IA, 'AIO_OFFICE.WORK.FILING_FUEL_TAXES'),
    new_ifta_location: iaPath(IA, 'AIO_OFFICE.WORK.FILING_FUEL_TAXES.IFTA'),
    supersessions: IA.supersessions.map((s) => ({ ...s, new_locations: s.new_node_ids.map(at) })),
    legacy_marked_superseded: IA.legacy.filter((l) => l.classification === 'SUPERSEDE').map((l) => ({ repo: l.repo, ref: l.ref, what: l.what })),
  };
}

function supersessionMd() {
  return [
    ...MD_HEAD('06 · FILING supersession map — old root → new WORK subtree'),
    `The old staff / founder dock **HOME · INTAKE · FILING · REPORTS · MORE** is marked \`${IA.lineage_id}\`. Lineage is kept; nothing is deleted.`,
    '',
    '```',
    'OLD ROOT                         NEW ROOT',
    'HOME     ───────────────────────▶ HOME      (projection)',
    'INTAKE   ───────────────────────▶ INTAKE    (entry · staff / founder only)',
    'FILING   ──┬─ root position ────▶ WORK      (production hub, all service lanes)',
    '           └─ filing work ──────▶ WORK → FILING & FUEL TAXES → IFTA',
    'REPORTS  ───────────────────────▶ REPORTS   (oversight)',
    'MORE     ───────────────────────▶ MORE      (secondary directory)',
    '```',
    '',
    table(['Old structure', 'Old item', 'Old target', 'Disposition', 'New location', 'Note'], IA.supersessions.map((s) => [s.old_structure, s.old_item, s.old_target, s.disposition, s.new_node_ids.map(at).join(' · '), s.note])),
    '',
    '## Marked in place (lineage kept)',
    '',
    table(['Repo', 'Reference', 'What'], IA.legacy.filter((l) => l.classification === 'SUPERSEDE').map((l) => [l.repo, l.ref, l.what])),
    '',
    'The live dock (fsbw `AioMigrationKit.tsx` STAFF_NAV) is **not** changed in this sprint — it is MIGRATE_LATER (see LEGACY_RECONCILIATION.md). The approved migration authority images keep their drawn dock (KEEP — authority is never edited).',
    '',
  ].join('\n');
}

/* ─────────────────────────────── 07 HOME / 08 REPORTS / 09 MORE ─────────────────────────────── */

export function homeProjectionModel() {
  return {
    ...head('AIO_OFFICE_HOME_PROJECTION_MODEL'),
    rule: 'HOME is a cross-business command center. It projects the state owned by INTAKE and WORK; it owns no production state. Every HOME item opens its owning INTAKE / WORK location.',
    requirements: brain.AIO_HOME_REQUIREMENTS,
    examples: brain.AIO_PROJECTION_EXAMPLES.filter((e) => e.surface === 'HOME'),
    regions: iaChildren(IA, 'AIO_OFFICE.HOME').map((r) => ({ node_id: r.node_id, label: r.label, semantics: r.semantics, projects: r.projects.map((p) => ({ node_id: p, location: at(p) })), implementation: r.implementation, depth: r.depth, routes: r.routes, evidence: r.evidence, notes: r.notes })),
  };
}

function homeMd() {
  const m = homeProjectionModel();
  return [
    ...MD_HEAD('07 · HOME projection model'),
    `**Rule:** ${m.rule}`,
    '',
    'HOME never: holds a queue of its own · edits a case · counts PREBUILT as ACTIVE · shows a client anything (staff only).',
    '',
    table(['Region', 'Shows', 'Projects (owner)', 'Implementation', 'Evidence / notes'], m.regions.map((r) => [r.label, r.semantics, r.projects.map((p) => p.location).join(' · '), impl(r), [...r.evidence, r.notes].filter(Boolean).join(' · ') || '—'])),
    '',
    '## Founder requirements → regions',
    '',
    table(['HOME must support', 'Region'], m.requirements.map((r) => [r.requirement, r.regions.map(at).join(' · ')])),
    '',
    '## Projection vs ownership (founder examples — illustrative counts, not data)',
    '',
    table(['HOME says', 'Region', 'Opens (owner in WORK)'], m.examples.map((e) => [`“${e.says}”`, at(e.region), at(e.owner)])),
    '',
  ].join('\n');
}

export function reportsAggregationModel() {
  const domains = iaChildren(IA, 'AIO_OFFICE.REPORTS');
  return {
    ...head('AIO_OFFICE_REPORTS_AGGREGATION_MODEL'),
    rule: 'REPORTS is internal oversight: history, performance, analytics and exports. It aggregates WORK and INTAKE and never replaces active production. Each domain declares whether its data is real today.',
    data_status_counts: Object.fromEntries(['REAL_DATA', 'PARTIAL_DATA', 'NOT_YET_IMPLEMENTED'].map((k) => [k, domains.filter((d) => d.data_status === k).length])),
    examples: brain.AIO_PROJECTION_EXAMPLES.filter((e) => e.surface === 'REPORTS'),
    domains: domains.map((d) => ({ node_id: d.node_id, label: d.label, data_status: d.data_status, aggregates: d.aggregates.map((a) => ({ node_id: a, location: at(a) })), routes: d.routes, staff_gate: d.staff_gate, implementation: d.implementation, depth: d.depth, notes: d.notes })),
  };
}

function reportsMd() {
  const m = reportsAggregationModel();
  return [
    ...MD_HEAD('08 · REPORTS aggregation model'),
    `**Rule:** ${m.rule}`,
    '',
    `Data status: ${Object.entries(m.data_status_counts).map(([k, v]) => `${k} ${v}`).join(' · ')}. No domain is REAL_DATA yet: management command centers read the demo store.`,
    '',
    table(['Domain', 'Data', 'Aggregates', 'Routes today', 'Notes'], m.domains.map((d) => [d.label, d.data_status ?? '—', d.aggregates.map((a) => a.location).join(' · ') || '—', d.routes.map((r) => `\`${r.path}\``).join(' · ') || '—', [d.notes, d.staff_gate ? `gate: ${d.staff_gate}` : ''].filter(Boolean).join(' · ') || '—'])),
    '',
    '## Oversight vs production (founder example)',
    '',
    table(['REPORTS', 'Domain', 'Never replaces (production in WORK)'], m.examples.map((e) => [e.says, at(e.region), at(e.owner)])),
    '',
  ].join('\n');
}

function moreMd() {
  const r = IA.more_rules;
  const entries = iaChildren(IA, r.container_node);
  const intoMore = IA.candidates.filter((c) => c.recommended_node?.startsWith(r.container_node));
  return [
    ...MD_HEAD('09 · MORE inclusion / exclusion rules'),
    `**Rule:** ${r.rule}`,
    '',
    `May contain roles: ${r.may_contain_roles.join(', ')} · must not contain: ${r.must_not_contain_roles.join(', ')} (enforced by the validator).`,
    '',
    '## Included',
    '',
    table(['Entry', 'What it holds', 'Routes today', 'Implementation', 'Gate / notes'], entries.map((e) => [e.label, e.notes || e.semantics || '—', routesOf(e), impl(e), [e.staff_gate ? `gate: ${e.staff_gate}` : '', e.evidence.join(' · ')].filter(Boolean).join(' · ') || '—'])),
    '',
    '## Excluded (belongs elsewhere)',
    '',
    table(['Item', 'Belongs in', 'Why'], r.exclusions.map((x) => [x.item, at(x.belongs_in), x.reason])),
    '',
    '## Candidates recommended into MORE (founder decision pending)',
    '',
    table(['Candidate', 'Recommended', 'Rationale'], intoMore.map((c) => [c.label, at(c.recommended_node!), c.rationale])),
    '',
    `The MORE directory surface itself is ${impl(n(r.container_node))}: its entries exist today as separate routes.`,
    '',
  ].join('\n');
}

/* ─────────────────────────────── 10 Experience Brain / 11 product graph ─────────────────────────────── */

function brainUpdatesMd() {
  const kinds = [...new Set(IA.nodes.map((x) => x.kind))].map((k) => `${k} ${IA.nodes.filter((x) => x.kind === k).length}`).join(' · ');
  const impls = ['IMPLEMENTED', 'IMPLEMENTATION_PARTIAL', 'IMPLEMENTATION_NOT_STARTED'].map((k) => `${k} ${IA.nodes.filter((x) => x.implementation === k).length}`).join(' · ');
  return [
    ...MD_HEAD('10 · Experience Brain updates'),
    '## Added',
    '',
    table(['File', 'What'], [
      ['shared/studioos-experience-brain/office-information-architecture.ts', 'Generic office IA layer (any project): actors FOUNDER / STAFF / CLIENT, node kinds, roles (COMMAND · PROJECTION · ENTRY · PRODUCTION · OVERSIGHT · SECONDARY · client roles), visibility (FULL · CLIENT_SAFE_PROJECTION · VIA_AIO_OFFICE · HIDDEN), architecture vs implementation status, client resolution (ALWAYS · APPLICABILITY · ENTITLEMENT · STATE), supersession lineage, legacy classification, candidates, firewall, MORE rules; helpers and `validateOfficeInformationArchitecture`.'],
      ['shared/studioos-experience-brain/projects/aio/office-ia.ts', `AIO data: ${IA.nodes.length} nodes (${kinds}), ${IA.services.length} services, ${IA.supersessions.length} supersessions, ${IA.legacy.length} legacy references, ${IA.candidates.length} candidates, ${IA.firewall.length} firewall items, ${IA.open_questions.length} open questions, the product-graph crosswalk and the founder quality gate.`],
      ['scripts/studioos/aio-office-ia-export.ts', 'Generates docs/aio/office-ia/ (this folder).'],
      ['tests/aioOfficeIaWorkTree1.test.ts', 'Founder gate, validator, firewall, references into the Brain and the IFTA tree, export sync.'],
    ]),
    '',
    `Implementation truth across nodes: ${impls}.`,
    '',
    '## Validator rules (generic)',
    '',
    ...[
      'unique node ids; every parent exists in the same shell',
      'a shell’s root_nav equals its ROOT_DESTINATION children, in order',
      'an internal-office node is never visible to CLIENT',
      'a client-office node has a client resolution, never routes into /office, never carries ENTRY (INTAKE) work',
      'firewall nodes are CLIENT = HIDDEN',
      'a PROJECTION names what it projects and never projects another projection',
      'a REPORT_DOMAIN declares its data status and what it aggregates',
      'MORE holds no PRODUCTION / ENTRY / COMMAND / PROJECTION node',
      'service staff nodes sit in the internal office, client nodes in the client office; a STAFF_ONLY service has no client node',
      'supersessions carry the sprint lineage id; legacy, candidate and supersession targets exist',
    ].map((s) => `- ${s}`),
    '',
    '## Linked, not changed',
    '',
    table(['Existing Brain source', 'Link'], [
      ['projects/aio/office.ts AIO_ENVIRONMENTS', `shells AIO_OFFICE → ${IA.shells[0].environment_id}, CLIENT_OFFICE → ${IA.shells[1].environment_id}`],
      ['projects/aio/office.ts AIO_WORKSPACES', `${new Set(IA.nodes.flatMap((x) => x.workspace_ids)).size} of ${brain.AIO_WORKSPACES.length} workspaces carried by lanes / client destinations (lane ≠ workspace; see 04)`],
      ['projects/aio/office.ts AIO_EXPANSION_RULES', 'client SERVICES / contextual placements keep resolving through them'],
      ['projects/aio/office.ts AIO_OFFICE_HUB_RESPONSIBILITIES', 'crosswalked to the HOME regions (06 supersession map)'],
      ['projects/aio/client-migration.ts AIO_LIFECYCLE_MAPPING', 'PREBUILT counted_active = false; activation gate = CLIENT_OFFICE.ACTIVATION'],
      ['experience contracts (AIO_EXPERIENCE_CONTRACTS) + screen families', 'feature_refs on nodes and services'],
      ['visual authority IFTA tree (AIO.OFFICE.WS.IFTA · AIO.IFTA.STAFF.QUEUE · AIO.CLIENT_OFFICE.WS.IFTA)', 're-associated to WORK → FILING & FUEL TAXES → IFTA and OPERATIONS → FILING / IFTA; tree node ids and parents unchanged (re-parenting is MIGRATE_LATER)'],
      ['fsbw AIO_CLIENT_MIGRATION_AUTHORITY (42 plates)', `${new Set(migrationAuthorityRefs().map((m) => m.authority_id)).size} current authorities (${MAS.approved} approved + ${MAS.founder_review_required.join(', ')} under founder review) re-associated under INTAKE sections and the client activation gate; ${MAS.superseded.map((x) => x.authority_id).join(', ')} superseded (lineage only)`],
    ]),
    '',
    'Unchanged: operating-environment.ts, client-lifecycle.ts, projects/aio/office.ts, client-migration.ts, migration.ts, the IFTA authority tree and its coverage counts, every existing export.',
    '',
  ].join('\n');
}

export const AIO_OFFICE_IA_FSBW_OVERLAY_PATH = 'all-in-one-enterprises/src/product-graph/officeInformationArchitecture.json';

function productGraphMd() {
  return [
    ...MD_HEAD('11 · Product graph updates'),
    `The fsbw runtime product graph is generated and is **not** edited. fsbw vendors this IA as an overlay (\`${AIO_OFFICE_IA_FSBW_OVERLAY_PATH}\`, a copy of AIO_OFFICE_IA.json) with a typed loader (\`officeInformationArchitecture.ts\`, data only — no UI import) and tests that hold the overlay to the graph, the route files and the migration authority manifest.`,
    '',
    `Source graph: ${PG.source}.`,
    '',
    '## Customer containers → CLIENT OFFICE',
    '',
    table(['Graph container', 'IA node', 'Disposition', 'Note'], PG.containers.map((c) => [c.container, at(c.ia_node), c.disposition, c.note || '—'])),
    '',
    '## Families → both offices',
    '',
    table(['Family', 'Name', 'Graph nav today', 'CLIENT OFFICE', 'AIO OFFICE', 'Note'], PG.families.map((f) => [f.family, f.name, f.graph_nav ?? '— (public)', f.client_node ? at(f.client_node) : '—', f.staff_node ? at(f.staff_node) : '—', f.note || '—'])),
    '',
    '## Role projections',
    '',
    table(['Projection', 'IA', 'Note'], PG.role_projections.map((p) => [p.projection, p.ia_node ? at(p.ia_node) : '— (outside both offices)', p.note])),
    '',
    '## Routes the generated graph predates (MIGRATE_LATER — regenerate in the graph sprint)',
    '',
    table(['Route / prefix', 'Why'], PG.route_gaps.map((g) => [`\`${g.prefix}\``, g.reason])),
    '',
  ].join('\n');
}

/* ─────────────────────────────── legacy / candidates / README ─────────────────────────────── */

function legacyMd() {
  const counts = ['KEEP', 'REMAP', 'SUPERSEDE', 'MIGRATE_LATER', 'REMOVE_WHEN_IMPLEMENTED'].map((k) => `${k} ${IA.legacy.filter((l) => l.classification === k).length}`).join(' · ');
  return [
    ...MD_HEAD('Legacy reconciliation'),
    `Every older reference found to the superseded structures, classified. ${counts}.`,
    '',
    table(['Classification', 'Repo', 'Reference', 'What', 'Canonical target', 'Note'], IA.legacy.map((l) => [l.classification, l.repo, l.ref, l.what, l.target_node_ids.map(at).join(' · '), l.note])),
    '',
  ].join('\n');
}

function candidatesMd() {
  return [
    ...MD_HEAD('Candidates and open questions'),
    'Source truth the founder tree does not name. Recorded with a recommendation — never discarded and never promoted silently.',
    '',
    '## Candidates',
    '',
    table(['Id', 'Observed', 'Recommended', 'Rationale'], IA.candidates.map((c) => [`${c.candidate_id} — ${c.label}`, c.observed.join(' · '), c.recommended_node ? at(c.recommended_node) : 'founder decision', c.rationale])),
    '',
    '## Open founder questions',
    '',
    table(['Id', 'Question', 'Recommendation', 'Blocks'], IA.open_questions.map((q) => [q.question_id, q.question, q.recommendation, q.blocks])),
    '',
  ].join('\n');
}

const ARTIFACTS: [string, string][] = [
  ['01_AIO_OFFICE_TREE.md', 'AIO OFFICE founder / staff tree (+ AIO_OFFICE_TREE.json)'],
  ['02_CLIENT_OFFICE_TREE.md', 'CLIENT OFFICE tree (+ CLIENT_OFFICE_TREE.json)'],
  ['03_ACTOR_VISIBILITY_MATRIX.md', 'Actor visibility matrix + firewall (+ ACTOR_VISIBILITY_MATRIX.json)'],
  ['04_SERVICE_STAFF_WORKSPACE_MAP.md', 'Service → staff workspace map'],
  ['05_SERVICE_CLIENT_DESTINATION_MAP.md', 'Service → client destination map'],
  ['06_FILING_SUPERSESSION_MAP.md', 'Old FILING root → new WORK subtree (+ SUPERSESSION_MAP.json)'],
  ['07_HOME_PROJECTION_MODEL.md', 'HOME projection model (+ HOME_PROJECTION_MODEL.json)'],
  ['08_REPORTS_AGGREGATION_MODEL.md', 'REPORTS aggregation model (+ REPORTS_AGGREGATION_MODEL.json)'],
  ['09_MORE_RULES.md', 'MORE inclusion / exclusion rules'],
  ['10_EXPERIENCE_BRAIN_UPDATES.md', 'Experience Brain updates'],
  ['11_PRODUCT_GRAPH_UPDATES.md', 'Product graph updates'],
  ['SERVICE_CROSSWALK.md', 'Service crosswalk table (+ SERVICE_CROSSWALK.json)'],
  ['LEGACY_RECONCILIATION.md', 'KEEP / REMAP / SUPERSEDE / MIGRATE_LATER / REMOVE_WHEN_IMPLEMENTED'],
  ['CANDIDATES_AND_OPEN_QUESTIONS.md', 'What the founder tree does not name + open questions'],
  ['AIO_OFFICE_IA.json', 'The whole architecture as data (the fsbw product-graph overlay)'],
  ['QUALITY_GATE.json', 'The founder gate, computed'],
];

function readmeMd() {
  const gate = aioOfficeIaQualityGate();
  return [
    ...MD_HEAD('AIO office information architecture'),
    `**AIO OFFICE** (founder / staff): ${iaRootNav(IA, 'AIO_OFFICE').join(' · ')}  `,
    `**CLIENT OFFICE**: ${iaRootNav(IA, 'CLIENT_OFFICE').join(' · ')}`,
    '',
    `FILING is no longer a root item: it is **${iaPath(IA, 'AIO_OFFICE.WORK.FILING_FUEL_TAXES').join(' → ')}**, and IFTA is **${iaPath(IA, 'AIO_OFFICE.WORK.FILING_FUEL_TAXES.IFTA').join(' → ')}**. The old dock HOME · INTAKE · FILING · REPORTS · MORE is \`${IA.lineage_id}\`. INTAKE is staff / founder only.`,
    '',
    'HOME = projection · WORK = production · REPORTS = oversight · MORE = secondary. Architecture only — no page, nav, route, schema, lifecycle or auth change; no image generated; no visual authority modified.',
    '',
    '## Artifacts',
    '',
    table(['File', 'What'], ARTIFACTS.map(([f, w]) => [`[${f}](${f})`, w])),
    '',
    '## Quality gate',
    '',
    table(['Check', 'Value', 'Evidence'], gate.checks.map((c) => [c.key, c.value, c.evidence])),
    '',
    `Next sprint: \`${brain.AIO_OFFICE_IA_NEXT_SPRINT}\`.`,
    '',
  ].join('\n');
}

export function buildAioOfficeIaExports(): Record<string, string> {
  return {
    'README.md': readmeMd(),
    '01_AIO_OFFICE_TREE.md': founderTreeMd(),
    'AIO_OFFICE_TREE.json': json({ ...head('AIO_OFFICE_TREE'), root_nav: iaRootNav(IA, 'AIO_OFFICE'), tree: treeJson('AIO_OFFICE') }),
    '02_CLIENT_OFFICE_TREE.md': clientTreeMd(),
    'CLIENT_OFFICE_TREE.json': json({ ...head('CLIENT_OFFICE_TREE'), root_nav: iaRootNav(IA, 'CLIENT_OFFICE'), tree: treeJson('CLIENT_OFFICE') }),
    '03_ACTOR_VISIBILITY_MATRIX.md': visibilityMd(),
    'ACTOR_VISIBILITY_MATRIX.json': json({ ...head('AIO_OFFICE_ACTOR_VISIBILITY_MATRIX'), firewall: IA.firewall, nodes: visibilityRows() }),
    '04_SERVICE_STAFF_WORKSPACE_MAP.md': staffMapMd(),
    '05_SERVICE_CLIENT_DESTINATION_MAP.md': clientMapMd(),
    '06_FILING_SUPERSESSION_MAP.md': supersessionMd(),
    'SUPERSESSION_MAP.json': json(supersessionMap()),
    '07_HOME_PROJECTION_MODEL.md': homeMd(),
    'HOME_PROJECTION_MODEL.json': json(homeProjectionModel()),
    '08_REPORTS_AGGREGATION_MODEL.md': reportsMd(),
    'REPORTS_AGGREGATION_MODEL.json': json(reportsAggregationModel()),
    '09_MORE_RULES.md': moreMd(),
    '10_EXPERIENCE_BRAIN_UPDATES.md': brainUpdatesMd(),
    '11_PRODUCT_GRAPH_UPDATES.md': productGraphMd(),
    'SERVICE_CROSSWALK.md': crosswalkMd(),
    'SERVICE_CROSSWALK.json': json({ ...head('AIO_SERVICE_CROSSWALK'), columns: ['SERVICE', 'STAFF LOCATION', 'CLIENT LOCATION', 'CLIENT VISIBILITY', 'CURRENT IMPLEMENTATION STATUS', 'CANONICAL DATA SOURCE', 'NOTES'], services: serviceCrosswalk() }),
    'LEGACY_RECONCILIATION.md': legacyMd(),
    'CANDIDATES_AND_OPEN_QUESTIONS.md': candidatesMd(),
    'AIO_OFFICE_IA.json': json({ ...head('AIO_OFFICE_IA'), next_sprint: brain.AIO_OFFICE_IA_NEXT_SPRINT, ...IA, migration_authority_set: MAS, home_requirements: brain.AIO_HOME_REQUIREMENTS, projection_examples: brain.AIO_PROJECTION_EXAMPLES, work_capabilities: brain.AIO_WORK_CAPABILITIES, expansion_criteria: brain.AIO_EXPANSION_CRITERIA, product_graph_map: PG, quality_gate: G }),
    'QUALITY_GATE.json': json(aioOfficeIaQualityGate()),
  };
}

if (process.argv[1] && /aio-office-ia-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_OFFICE_IA_DOCS_DIR, { recursive: true });
  const files = buildAioOfficeIaExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_OFFICE_IA_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_OFFICE_IA_DOCS_DIR}`);
}
