/**
 * P0.AIO.OFFICE.COMPLETE-INTERNAL-OFFICE-AND-UNIFIED-EXPERIENCE1 — export the record of the unified internal AIO OFFICE
 * (single source: shared/studioos-experience-brain/projects/aio/office-unified-experience.ts).
 *
 *   npx tsx scripts/studioos/aio-office-unified-experience-export.ts
 *
 * Every file in docs/aio/office-unified-experience/ is GENERATED; tests/aioOfficeUnifiedExperience1.test.ts keeps them in
 * sync. The review studio itself lives in fsbw (design-authority/aio-office/office/). Batch 1 designed; founder review
 * pending; the live app is NOT complete; live implementation and security repairs are NOT authorized by this sprint.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { aio as brain } from '../../shared/studioos-experience-brain/index.js';

export const AIO_UO_DOCS_DIR = 'docs/aio/office-unified-experience';
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const S = brain.AIO_UO_STATUS;
const word = (r: string) => r.replace(/_/g, ' ');
const MD_HEAD = (title: string) => [
  `# ${title}`, '',
  '> Generated by `scripts/studioos/aio-office-unified-experience-export.ts` from the Experience Brain. Do not edit by hand.', '',
  `**Sprint:** ${brain.AIO_UO_SPRINT} (${brain.AIO_UO_DATE})  `,
  `**Batch:** ${S.batch}  `,
  `**Office:** ${S.office}  `,
  `**Live app:** ${S.live_app}  `,
  `**Review:** ${brain.AIO_UO_REVIEW_LINK}  `,
  `**Next gate:** ${brain.AIO_UO_NEXT_GATE}`, '',
];
const tree = brain.AIO_UO_PAGE_TREE;
const treeRows = (root: string) => tree.filter((p) => p.root === root).map((p) => [p.family, `\`${p.route}\``, word(p.review), word(p.live), `${p.founder_only ? 'FOUNDER / GRANT ONLY. ' : ''}${p.note ?? ''}`]);

export function aioUnifiedExperienceQualityGate() {
  const problems = brain.validateUnifiedExperience();
  const count = (k: string) => tree.filter((p) => p.review === k).length;
  return {
    sprint: brain.AIO_UO_SPRINT,
    gate: {
      EVERY_IA_NODE_HAS_A_PAGE_FAMILY: problems.some((p) => /has no page/.test(p)) ? 'NO' : 'YES',
      FIVE_ROOTS: 'YES — HOME · INTAKE · WORK · REPORTS · MORE (FILING not restored)',
      TWELVE_LANES: brain.AIO_UO_LANES.length === 12 ? 'YES' : 'NO',
      TEN_REPORT_DOMAINS: brain.AIO_UO_REPORT_DOMAINS.length === 10 ? 'YES' : 'NO',
      ELEVEN_MORE_DESTINATIONS: brain.AIO_UO_MORE.length === 11 ? 'YES' : 'NO',
      REVIEW_QA_PASSED: brain.AIO_UO_QA.failures === 0 ? 'YES' : 'NO',
      APPROVED_SCREENS_REGENERATED: 'NO — approved roots, migration screens and IFTA authority shown unchanged',
      SAMPLE_DATA_ONLY: 'YES',
      FOUNDER_APPROVED: 'NO — AWAITING FOUNDER REVIEW',
      OFFICE_COMPLETE: 'NO — BATCH 1; continuation sprints recorded',
      LIVE_APP_COMPLETE: 'NO',
      SECURITY_GAPS_FIXED: 'NO — 12 OPEN; separate handoff',
      LIVE_IMPLEMENTATION_AUTHORIZED: 'NO',
    },
    counts: { page_families: tree.length, approved_root: count('APPROVED_ROOT'), approved_authority: count('APPROVED_AUTHORITY'), new_for_review: count('NEW_FOR_REVIEW'), honest_state: count('HONEST_STATE'), crawled_routes: brain.AIO_UO_QA.crawled_routes, journeys: brain.AIO_UO_JOURNEYS.length, screenshots: brain.AIO_UO_QA.screenshots, open_privacy_gaps: brain.AIO_UO_SECURITY_HANDOFF.length },
    problems,
    status: S,
    next_gate: brain.AIO_UO_NEXT_GATE,
  };
}

function readmeMd() {
  const g = aioUnifiedExperienceQualityGate();
  return [
    ...MD_HEAD('AIO OFFICE — unified internal office experience (batch 1)'),
    'The internal AIO OFFICE designed as one connected product — five roots, INTAKE, twelve WORK lanes, ten REPORTS domains, eleven MORE destinations, record pages and Client 360 — and proven in an isolated, clickable review with sample records only.', '',
    '## Files', '',
    ...bullets(['01_INVENTORY.md — what existed and how it was reused', '02_FIVE_ROOT_PAGE_TREE.md — every page family, its review status and what the live app has (existing versus missing)', '03_SHARED_DESIGN_SYSTEM.md', '04_INTAKE.md', '05_WORK_LANES.md', '06_REPORTS_AND_MORE.md', '07_ROLES_AND_CLIENT_CONTEXT.md', '08_REVIEW_ENVIRONMENT_AND_VIEWPORTS.md', '09_JOURNEYS_AND_QA.md', '10_COMPOSER_INTEGRATION_PLAN.md (DRAFT)', '11_SECURITY_REPAIR_HANDOFF.md (separate; nothing patched)', '12_GAPS_AND_CONTINUATION.md', '13_FOUNDER_WALKTHROUGH.md', 'UNIFIED_EXPERIENCE.json · QUALITY_GATE.json']), '',
    '## Quality gate', '', table(['Check', 'Result'], Object.entries(g.gate).map(([k, v]) => [word(k), v])), '',
    '## Where things are', '', table(['What', 'Where'], Object.entries(brain.AIO_UO_LOCATIONS).map(([k, v]) => [word(k), v])), '',
  ].join('\n');
}
const inventoryMd = () => [...MD_HEAD('01 · Inventory — what already existed'), table(['Item', 'Kind', 'Source', 'Status', 'Used as'], brain.AIO_UO_INVENTORY.map((i) => [i.item, word(i.kind), i.source, i.status, i.used_as])), ''].join('\n');
function treeMd() {
  const out = [...MD_HEAD('02 · Five-root page tree — existing versus missing'), 'Review status: APPROVED ROOT (drawn as approved) · APPROVED AUTHORITY (shown unchanged) · NEW FOR REVIEW (designed this sprint) · HONEST STATE (the product lacks it; the page says so). Live: what the live app has today.', ''];
  for (const root of ['HOME', 'INTAKE', 'WORK', 'REPORTS', 'MORE']) out.push(`## ${root}`, '', table(['Page family', 'Review route', 'Review', 'Live', 'Note'], treeRows(root)), '');
  const missing = tree.filter((p) => p.live === 'NOT_BUILT' || p.live === 'DESIGN_ONLY' || p.live === 'PAUSED');
  out.push('## Missing or unavailable in the live app', '', ...bullets(missing.map((p) => `${p.family} — ${word(p.live)}`)), '');
  return out.join('\n');
}
const designMd = () => [...MD_HEAD('03 · Shared design system'), 'Built on the approved root components (studio.css). Shared grammar, purpose-built pages: no lane is a copy of another.', '', table(['Component', 'Rule'], brain.AIO_UO_COMPONENTS.map((c) => [c.component, c.rule])), ''].join('\n');
const intakeMd = () => [
  ...MD_HEAD('04 · INTAKE'),
  '- The INTAKE root carries the approved migration root’s modules (hero, three paths, migration status, file types, providers, security, START MIGRATION) inside the office frame, with the responsive plates the live flow uses.',
  '- Each flow step is the approved authority screen itself (41 screens + root), with its step detail, lifecycle and live route; the clickable migration flow prototype is linked.',
  '- New for staff: the ten sections and a case page per migration (lifecycle stepper, approved screen for the step, actions).',
  '- Staff preparation stops at PREBUILT. Approval is founder-only and lands on PREBUILT; only the client’s own confirmation makes a client ACTIVE. MARK ACTIVE and CONFIRM ON THE CLIENT’S BEHALF are drawn as unavailable.', '',
  table(['Page family', 'Review route', 'Review', 'Live', 'Note'], treeRows('INTAKE')), '',
].join('\n');
const workMd = () => [
  ...MD_HEAD('05 · WORK — twelve lane families'),
  'Each lane: landing (A), queues (B), directory (C), record pages (D) with actions (E), history (F) and related records (G), and honest empty / blocked / not-built / paused states (H).', '',
  table(['Lane', 'Landing', 'Tabs (IA section)'], brain.AIO_UO_LANES.map((l) => [l.name, l.landing, l.tabs.map(([, label, ia, , live]) => `${label}${ia ? ` (${ia})` : ''}${live === 'NOT_BUILT' ? ' — NOT BUILT' : live === 'PAUSED' ? ' — PAUSED' : ''}`).join(' · ')])), '',
  '## Record pages', '', table(['Record', 'Owner', 'Page'], brain.AIO_UO_RECORD_TYPES.map((r) => [r.type, r.owner, r.page])), '',
  '## MY WORK and ALL OPEN WORK', '', ...bullets(['MY WORK: everything assigned to the viewer across lanes, with lane filters.', 'ALL OPEN WORK: every open record across lanes (reads each lane; no second queue), sorted most urgent first, filterable by lane and client.']), '',
].join('\n');
const reportsMoreMd = () => [
  ...MD_HEAD('06 · REPORTS and MORE'),
  '## REPORTS — ten domains', '', 'Every domain: overview figures backed by records only, area selection, period, filters, detail rows that open records, history (or NOT CONNECTED YET), CSV export (simulated, logged), PDF later, restricted views and unavailable states.', '',
  table(['Domain', 'Route', 'Review', 'Live', 'What it shows'], brain.AIO_UO_REPORT_DOMAINS.map(([slug, title, , review, live, note]) => [title, `\`${slug ? `reports/${slug}` : 'reports'}\``, word(review), word(live), note])), '',
  '## MORE — eleven destinations in four groups', '',
  table(['Group', 'Destination', 'Children', 'Staff', 'Founder', 'Live'], brain.AIO_UO_MORE.map((m) => [m.group, m.title, m.children.join(' · ') || '—', m.staff, m.founder, word(m.live)])), '',
].join('\n');
const rolesMd = () => [
  ...MD_HEAD('07 · Founder and staff · client context'),
  '## Founder and staff', '', table(['Area', 'Founder', 'Staff', 'Staff with reports'], brain.AIO_UO_ROLES.map((r) => [r.area, r.founder, r.staff, r.staff_with_reports])), '',
  ...bullets(brain.AIO_UO_GRANT_ENFORCEMENT), '',
  '## Client context', '', ...bullets(brain.AIO_UO_CLIENT_CONTEXT.map((c) => c.rule)), '',
].join('\n');
const reviewMd = () => [
  ...MD_HEAD('08 · Review environment and viewports'),
  '## Interactions', '', table(['Interaction', 'Kind'], brain.AIO_UO_INTERACTIONS.map((i) => [i.interaction, word(i.kind)])), '',
  '## Viewport families', '', table(['Viewport', 'Size', 'Rules'], brain.AIO_UO_VIEWPORTS.map((v) => [word(v.viewport), v.size, v.rules.join(' · ')])), '',
  '## Assets', '', table(['', ''], [['Reused', brain.AIO_UO_ASSETS.reused.join(' · ')], ['Generated', brain.AIO_UO_ASSETS.generated], ['Logo', brain.AIO_UO_ASSETS.logo], ['Still missing', brain.AIO_UO_ASSETS.still_missing.join(' · ')]]), '',
].join('\n');
const qaMd = () => {
  const q = brain.AIO_UO_QA;
  return [
    ...MD_HEAD('09 · Cross-service journeys and QA'),
    '## Journeys', '', table(['Journey', 'Role', 'Steps'], brain.AIO_UO_JOURNEYS.map((j) => [j.title, j.role, j.steps.map((s) => `\`${s}\``).join(' → ')])), '',
    '## Tests actually run', '', table(['', ''], [['Tool', q.tool], ['Routes crawled', String(q.crawled_routes)], ['Passes', q.passes.join(' · ')], ['Checks', q.checks.join(' · ')], ['Pages by status', Object.entries(q.by_status).map(([k, v]) => `${word(k)} ${v}`).join(' · ')], ['Failures', String(q.failures)], ['Journeys', q.journeys], ['Interactions', `${q.interactions_passed}: ${q.interactions.join(' · ')}`], ['Approved renders', q.authority_renders], ['Screenshots', `${q.screenshots} (AIO_OFFICE_UNIFIED_REVIEW/screens/)`]]), '',
  ].join('\n');
};
const composerMd = () => {
  const c = brain.AIO_UO_COMPOSER_PLAN;
  return [...MD_HEAD('10 · Composer integration plan — DRAFT'), `**${c.status}**  `, `**Gate:** ${c.gate}`, '', '## Sequence (after approval)', '', ...bullets(c.sequence), '', `**Must land first:** ${c.must_land_first}`, '', '## Do not', '', ...bullets(c.do_not), ''].join('\n');
};
const securityMd = () => {
  const r = brain.AIO_UO_SECURITY_RECHECK;
  return [
    ...MD_HEAD('11 · Security-repair handoff (separate from the design work)'),
    `**Rechecked at:** ${r.rechecked_at}  `, `**Method:** ${r.method}  `, `**Result:** ${r.result}  `, `**Patched in this sprint:** ${r.patched_here}`, '',
    'For Composer, as its own reviewed change. The office pages that depend on each repair are listed so the UI work does not build client-facing projections on an open gap.', '',
    table(['Gap', 'Status', 'Evidence still present', 'Repair', 'Office pages waiting'], brain.AIO_UO_SECURITY_HANDOFF.map((g) => [g.gap_id, g.status, g.evidence_still_present, g.repair, g.office_pages_waiting])), '',
    '## Grant enforcement', '', ...bullets(brain.AIO_UO_GRANT_ENFORCEMENT), '',
  ].join('\n');
};
const gapsMd = () => [...MD_HEAD('12 · Remaining gaps and continuation sprints'), '## Product gaps (shown honestly in the review)', '', ...bullets(brain.AIO_UO_PRODUCT_GAPS), '', '## Continuation', '', table(['Sprint', 'Scope'], brain.AIO_UO_CONTINUATION.map((c) => [c.sprint, c.scope])), ''].join('\n');
const walkMd = () => [...MD_HEAD('13 · Founder review link and walkthrough'), `**Review:** ${brain.AIO_UO_REVIEW_LINK}`, '', ...brain.AIO_UO_WALKTHROUGH.map((w, i) => `${i + 1}. ${w}`), ''].join('\n');

export function buildAioUnifiedExperienceExports(): Record<string, string> {
  return {
    'README.md': readmeMd(),
    '01_INVENTORY.md': inventoryMd(),
    '02_FIVE_ROOT_PAGE_TREE.md': treeMd(),
    '03_SHARED_DESIGN_SYSTEM.md': designMd(),
    '04_INTAKE.md': intakeMd(),
    '05_WORK_LANES.md': workMd(),
    '06_REPORTS_AND_MORE.md': reportsMoreMd(),
    '07_ROLES_AND_CLIENT_CONTEXT.md': rolesMd(),
    '08_REVIEW_ENVIRONMENT_AND_VIEWPORTS.md': reviewMd(),
    '09_JOURNEYS_AND_QA.md': qaMd(),
    '10_COMPOSER_INTEGRATION_PLAN.md': composerMd(),
    '11_SECURITY_REPAIR_HANDOFF.md': securityMd(),
    '12_GAPS_AND_CONTINUATION.md': gapsMd(),
    '13_FOUNDER_WALKTHROUGH.md': walkMd(),
    'UNIFIED_EXPERIENCE.json': json({
      id: 'AIO_OFFICE_UNIFIED_EXPERIENCE', sprint: brain.AIO_UO_SPRINT, date: brain.AIO_UO_DATE, generated_by: 'scripts/studioos/aio-office-unified-experience-export.ts',
      source: ['shared/studioos-experience-brain/projects/aio/office-unified-experience.ts'], base: brain.AIO_UO_BASE,
      status: S, next_gate: brain.AIO_UO_NEXT_GATE, review_link: brain.AIO_UO_REVIEW_LINK, locations: brain.AIO_UO_LOCATIONS,
      inventory: brain.AIO_UO_INVENTORY, page_tree: tree, lanes: brain.AIO_UO_LANES, record_types: brain.AIO_UO_RECORD_TYPES, report_domains: brain.AIO_UO_REPORT_DOMAINS, more: brain.AIO_UO_MORE,
      components: brain.AIO_UO_COMPONENTS, roles: brain.AIO_UO_ROLES, client_context: brain.AIO_UO_CLIENT_CONTEXT, interactions: brain.AIO_UO_INTERACTIONS, viewports: brain.AIO_UO_VIEWPORTS, assets: brain.AIO_UO_ASSETS,
      journeys: brain.AIO_UO_JOURNEYS, qa: brain.AIO_UO_QA, composer_plan: brain.AIO_UO_COMPOSER_PLAN, security: { recheck: brain.AIO_UO_SECURITY_RECHECK, handoff: brain.AIO_UO_SECURITY_HANDOFF, grants: brain.AIO_UO_GRANT_ENFORCEMENT },
      product_gaps: brain.AIO_UO_PRODUCT_GAPS, continuation: brain.AIO_UO_CONTINUATION, walkthrough: brain.AIO_UO_WALKTHROUGH,
    }),
    'QUALITY_GATE.json': json(aioUnifiedExperienceQualityGate()),
  };
}

if (process.argv[1] && /aio-office-unified-experience-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_UO_DOCS_DIR, { recursive: true });
  const files = buildAioUnifiedExperienceExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_UO_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_UO_DOCS_DIR}`);
}
