/**
 * P0.AIO.OFFICE-IA.FOUNDER-HOME-WORK-REPORTS-MORE.AUTHORITY-CONTRACTS1 — export the AIO OFFICE root authority contracts
 * (single sources: shared/studioos-experience-brain/office-root-contracts.ts + projects/aio/office-contracts.ts, built on
 * the office information architecture in projects/aio/office-ia.ts).
 *
 *   npx tsx scripts/studioos/aio-office-contracts-export.ts
 *
 * Every file in docs/aio/office-contracts/ is GENERATED — edit the TypeScript, never the output.
 * tests/aioOfficeRootContracts1.test.ts keeps them in sync. CONTRACT ONLY: no page, nav, route, schema, auth or lifecycle
 * change; no visual authority; no metric invented.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import {
  ACTION_OWNERSHIP_RULE,
  CLIENT_SAFE_PROJECTION_RULE,
  CONTRACT_ACTORS,
  CONTRACT_VIEWPORTS,
  LANE_SHELL_SECTIONS,
  METRIC_SOURCE_CLASSES,
  SURFACE_STATES,
  aio as brain,
  iaChildren,
  iaNode,
  iaPath,
  laneShellRef,
  validateOfficeRootContracts,
  type ContractAccess,
  type ContractActor,
  type ContractSource,
  type ImplementationGap,
  type RegionContract,
  type RootContract,
} from '../../shared/studioos-experience-brain/index.js';

export const AIO_OFFICE_CONTRACTS_DOCS_DIR = 'docs/aio/office-contracts';
const C = brain.AIO_OFFICE_CONTRACTS;
const IA = brain.AIO_OFFICE_IA;
const SPRINT = brain.AIO_OFFICE_CONTRACTS_SPRINT;
const [HOME, WORK, REPORTS, MORE] = C.roots;
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
const head = (id: string) => ({
  id, sprint: SPRINT, generated_by: 'scripts/studioos/aio-office-contracts-export.ts',
  source: ['shared/studioos-experience-brain/office-root-contracts.ts', 'shared/studioos-experience-brain/projects/aio/office-contracts.ts', 'shared/studioos-experience-brain/projects/aio/office-ia.ts'],
  audit: { repo: 'yoteenz/fsbw · all-in-one-enterprises', sha: brain.AIO_OFFICE_CONTRACTS_AUDIT_SHA, mode: 'READ-ONLY' },
  constraints: { contract_only: true, visual_redesign: false, images_generated: 0, visual_authorities_created: false, live_nav_changed: false, routes_changed: false, pages_built: false, supabase_schema_changed: false, auth_changed: false, client_lifecycle_changed: false, metrics_invented: false, records_invented: false, deployed: false },
});

/* ─────────────────────────────── formatting ─────────────────────────────── */

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (h: string[], rows: string[][]) => [`| ${h.join(' | ')} |`, `|${h.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const bullets = (xs: readonly string[]) => (xs.length ? xs.map((x) => `- ${x}`) : ['- —']);
const MD_HEAD = (title: string) => [
  `# ${title}`, '',
  '> Generated by `scripts/studioos/aio-office-contracts-export.ts` from the Experience Brain office root contracts. Do not edit by hand.', '',
  `**Sprint:** ${SPRINT}  `,
  `**Audit:** yoteenz/fsbw @ \`${brain.AIO_OFFICE_CONTRACTS_AUDIT_SHA.slice(0, 8)}\` (read-only)  `,
  '**Scope:** contract formalization only — no page, nav, route, schema, auth or lifecycle change; no visual authority; no metric invented.', '',
];
const EVIDENCE_KEY = '_Evidence paths are relative to `all-in-one-enterprises/` in fsbw, except `api/…`, which sits at the fsbw repo root._';
const ev = (xs: readonly string[]) => xs.map((x) => `\`${x.replace(/^all-in-one-enterprises\//, '')}\``).join(' · ') || '—';
/** An IA node as a readable path (AIO OFFICE nodes without the shell prefix). */
function at(id: string | null): string {
  if (!id) return '—';
  const n = iaNode(IA, id);
  if (!n) return id;
  const p = iaPath(IA, id);
  return n.shell_id === 'AIO_OFFICE' && p.length > 1 ? p.slice(1).join(' → ') : p.join(' → ');
}
const ACCESS_LABEL: Record<ContractAccess, string> = { FULL: 'full', BY_GRANT: 'by grant', CLIENT_SAFE_PROJECTION: 'client-safe projection', OWN_RECORDS_ONLY: 'own records only', NONE: '—' };
const vis = (v: Record<ContractActor, ContractAccess>) => CONTRACT_ACTORS.map((a) => `${a} ${ACCESS_LABEL[v[a]]}`).join(' · ');
const LANE_SECTION_LABEL = Object.fromEntries(LANE_SHELL_SECTIONS.map((s) => [laneShellRef(s), `Open lane · ${s.replace(/_/g, ' ').toLowerCase()}`]));
const label = (root: RootContract, id: string) => root.regions.find((r) => r.region_id === id)?.label ?? root.actions.find((a) => a.action_id === id)?.label ?? LANE_SECTION_LABEL[id] ?? iaNode(IA, id)?.label ?? id;
const STANCE_ACTS: Record<RootContract['stance'], string> = { PROJECTION: 'routes to actions (ROUTE only)', ENTRY: 'executes client entry, migration and activation work', PRODUCTION: 'executes service production (EXECUTE)', OVERSIGHT: 'reviews history and analysis (REVIEW, ROUTE)', ADMINISTRATION: 'administers supporting business systems (ADMINISTER)' };
const gap = (id: string) => C.gaps.find((g) => g.gap_id === id)!;
const yes = (b: boolean) => (b ? 'YES' : 'NO');
const eq = (a: readonly string[], b: readonly string[]) => a.length === b.length && a.every((v, i) => v === b[i]);
const under = (id: string, root: string) => id === root || id.startsWith(`${root}.`);

/* ─────────────────────────────── shared sections ─────────────────────────────── */

function sourcesTable(sources: ContractSource[]) {
  if (!sources.length) return ['_No source today._'];
  return [table(
    ['Source', 'Owner (route target)', 'Route', 'Data source', 'Backing', 'State', 'Priority / due rule', 'Staff', 'Evidence', 'Note'],
    sources.map((s) => [s.label, at(s.owner_node), s.route ? `\`${s.route}\`` : '—', s.data_source, s.backing, s.state, [s.priority_rule, s.due_rule].filter(Boolean).join(' · ') || '—', ACCESS_LABEL[s.visibility.STAFF], ev(s.evidence), s.note || '—']),
  )];
}

function regionMd(r: RegionContract, i: number) {
  return [
    `### ${i + 1} · ${r.label} — ${r.presence} · ${r.state}`, '',
    `**Answers:** ${r.question}  `,
    `**Each item shows:** ${r.item_fields.join(' · ')}`, '',
    ...bullets(r.rules), '',
    ...sourcesTable(r.sources), '',
  ];
}

function authorityMd(r: RootContract) {
  const reads = r.reads.map((x) => `${x.domain} — via ${x.via}`);
  return [
    '## Authority', '',
    table(['', ''], [
      ['Stance', r.stance],
      ['Owns', r.owns.join('<br>') || 'nothing'],
      ['Only projects', r.projects.join('<br>') || '—'],
      ['Reads', reads.join('<br>') || '—'],
      ['May mutate', r.may_mutate.join('<br>') || 'nothing'],
      ['Must not', r.must_not.join('<br>')],
      ['Staff-only', r.staff_only.join('<br>') || '—'],
      ['Founder-only', r.founder_only.join('<br>') || '—'],
    ]), '',
    '### Belongs elsewhere', '',
    table(['Item', 'Belongs in'], r.belongs_elsewhere.map((b) => [b.item, at(b.belongs_in)])), '',
    '### When source truth is partial or absent', '',
    r.partial_truth_rule, '',
    table(['Honest state', 'When', 'The surface shows'], r.states.map((s) => [s.state, s.when, s.shows])), '',
  ];
}

function actionsMd(r: RootContract) {
  return [
    '## Actions', '',
    table(['Action', 'Tier', 'Kind', 'Owner', 'Route', 'State', 'Requires', 'Evidence'], r.actions.map((a) => [a.label, a.tier, a.kind, at(a.owner_node), a.route ? `\`${a.route}\`` : '—', a.state, a.requires ?? '—', ev(a.evidence)])), '',
    '**Action ownership rule**', '',
    table(['Root', 'Its actions'], C.roots.map((x) => [at(x.root_id), STANCE_ACTS[x.stance]])), '',
    ...bullets(ACTION_OWNERSHIP_RULE), '',
  ];
}

function visualInputsMd(r: RootContract) {
  const rp = C.responsive.find((x) => x.root_id === r.root_id)!;
  const st = (s: string) => r.states.find((x) => x.state === s)?.shows ?? '—';
  return [
    '## Visual authority inputs', '',
    'What the next sprint’s visual authority must express for this root. Semantic only — no layout, colour or imagery is decided here.', '',
    table(['Input', 'Contract'], [
      ['Purpose', r.purpose],
      ['Primary question', r.primary_question],
      ['Hierarchy', r.hierarchy.join(' → ')],
      ['Regions', r.regions.map((x) => `${x.label}${x.presence === 'OPTIONAL' ? ' (optional)' : ''}`).join(' · ')],
      ['Primary actions', r.actions.filter((a) => a.tier === 'PRIMARY').map((a) => a.label).join(' · ') || '—'],
      ['Secondary actions', r.actions.filter((a) => a.tier === 'SECONDARY').map((a) => a.label).join(' · ') || '—'],
      ['Empty state (NO_DATA)', st('NO_DATA')],
      ['Partial state (PARTIAL)', st('PARTIAL')],
      ['Error state (ERROR)', st('ERROR')],
      ['Permission state (NO_ACCESS)', st('NO_ACCESS')],
      ['Not built (NOT_IMPLEMENTED)', st('NOT_IMPLEMENTED')],
      ...CONTRACT_VIEWPORTS.map((vp) => [`${vp[0]}${vp.slice(1).toLowerCase()} priority`, rp.order[vp].map((id) => label(r, id)).join(' → ')]),
    ]), '',
  ];
}

function rootMd(r: RootContract, n: string, title: string, extra: string[]) {
  return [
    ...MD_HEAD(`${n} · ${title}`),
    `**${at(r.root_id)}** — ${r.stance}. ${r.purpose}`, '',
    `**Primary question:** ${r.primary_question}`, '',
    'It answers:', '',
    ...bullets(r.answers), '',
    ...authorityMd(r),
    `## Regions (${r.regions.length})`, '',
    ...r.regions.flatMap(regionMd),
    ...actionsMd(r),
    ...extra,
    ...visualInputsMd(r),
    EVIDENCE_KEY, '',
  ].join('\n');
}

/* ─────────────────────────────── 01 HOME ─────────────────────────────── */

const homeMd = () => rootMd(HOME, '01', 'HOME authority contract', [
  '## Blocker groups (a display mapping, never a new enum)', '',
  'HOME groups blockers under the founder’s names by mapping each owner’s existing status / waiting literals. Nothing new is stored.', '',
  table(['Group', 'Existing literals it maps', 'Status', 'Note'], brain.AIO_HOME_BLOCKER_GROUPS.map((m) => [m.term, m.existing.join(' · ') || '—', m.status, m.note || '—'])), '',
  '## Recent Activity verbs (mapped onto the existing event vocabulary)', '',
  table(['Verb', 'Existing ActivityKind / lifecycle events', 'Status', 'Note'], brain.AIO_HOME_EVENT_VERBS.map((m) => [m.term, m.existing.join(' · ') || '—', m.status, m.note || '—'])), '',
  '## CRM and billing on HOME', '',
  `HOME may **project** CRM follow-ups and billing items (overdue invoices, failed payments). It owns neither: CRM lives in **${at('AIO_OFFICE.MORE.GROWTH_CRM')}**, billing in **${at('AIO_OFFICE.MORE.BILLING')}**, and both need their grants to appear.`, '',
]);

/* ─────────────────────────────── 02 WORK ─────────────────────────────── */

function laneMd(l: (typeof C.lanes)[number]) {
  const n = iaNode(IA, l.lane_id)!;
  return [
    `### ${n.label}`, '',
    `Sections: ${iaChildren(IA, l.lane_id).map((c) => c.label).join(' · ') || '—'}`, '',
    table(['Shell section', 'State', 'Source today', 'Note'], LANE_SHELL_SECTIONS.map((s) => [s, l.shell[s].state, l.shell[s].source, l.shell[s].note || '—'])), '',
    table(['', ''], [
      ['Records (as they exist)', l.records.map((r) => `${r.record} — ${ev([r.evidence])}`).join('<br>')],
      ['Statuses', l.statuses.join('<br>')],
      ['Assignment', l.assignment ?? 'none in the record'],
      ['Due', l.due ?? 'none in the record'],
      ['Blocker', l.blocker ?? '—'],
      ['Client-safe projection', l.client_safe],
      ['Related work (linked, never copied)', l.related.map((r) => `${at(r.node_id)} — ${r.relation}`).join('<br>')],
      ['Gaps', l.gaps.map((g) => `${g} (${gap(g).kind})`).join(' · ') || '—'],
    ]), '',
  ];
}

const workMd = () => rootMd(WORK, '02', 'WORK authority contract', [
  `## Root capabilities (${brain.AIO_WORK_ROOT_CAPABILITIES.length})`, '',
  table(['Capability', 'Today', 'Evidence', 'Note'], brain.AIO_WORK_ROOT_CAPABILITIES.map((c) => [c.capability, c.state, ev(c.evidence), c.note])), '',
  '## Common lane shell', '',
  `Every lane exposes the same six-part shell before its service sections: ${LANE_SHELL_SECTIONS.join(' · ')}. A section without source truth shows its honest state; no lane invents workflow depth.`, '',
  table(['Lane', ...LANE_SHELL_SECTIONS], C.lanes.map((l) => [iaNode(IA, l.lane_id)!.label, ...LANE_SHELL_SECTIONS.map((s) => l.shell[s].state)])), '',
  `## Lane contracts (${C.lanes.length})`, '',
  'IFTA keeps its canonical identity and authority (WORK → FILING & FUEL TAXES → IFTA); nothing here redesigns it.', '',
  ...C.lanes.flatMap(laneMd),
  '## Cross-service relationships', '',
  'Related work is linked, never duplicated: each hub’s record is the one source; the spokes link to it.', '',
  table(['Hub', 'Linked work', 'Linked through'], brain.AIO_WORK_RELATIONSHIPS.map((r) => [`${r.label} — ${at(r.hub)}`, r.spokes.map(at).join('<br>'), r.via])), '',
  '## VEHICLES & FLEET — minimum ownership', '',
  'NO STAFF SCREEN YET. The lane is the vehicle backbone: it owns the vehicle record and shows everything else by cross-link to the lane that owns it.', '',
  table(['Item', 'Relation', 'Source of truth'], brain.AIO_VEHICLES_FLEET_SCOPE.map((x) => [x.item, x.relation, at(x.source_of_truth)])), '',
  'Today there are three vehicle stores (demo PowerUnit, Supabase `aio_fleet_vehicles`, IFTA embedded copies) plus the dispatch overlay. The lane must anchor on one record and project the rest (G-VEHICLES-THREE-STORES).', '',
  '## Road Ready', '',
  'Road Ready has no per-client engagement state (AVAILABLE · ACTIVE · COMPLETED) in code. The contract does not invent one: placement by state (D-ROAD-READY-PLACEMENT) and RECENTLY COMPLETED stay BLOCKED until the state exists (G-ROAD-READY-NO-ENGAGEMENT-STATE).', '',
]);

/* ─────────────────────────────── 03 REPORTS ─────────────────────────────── */

const reportsMd = () => rootMd(REPORTS, '03', 'REPORTS authority contract', [
  '## Metric classification', '',
  `Every metric carries a source class (${METRIC_SOURCE_CLASSES.join(' · ')}) and a backing (PRODUCTION · DEMO_STORE · NONE). NOT_IMPLEMENTED and DERIVED_UNSUPPORTED metrics never render as numbers; DEMO_STORE metrics render only in demo mode, labelled demo. Nothing is illustrative; profitability is never shown beyond what source truth supports.`, '',
  ...REPORTS.regions.flatMap((r) => {
    const ms = C.metrics.filter((m) => m.domain_node === r.region_id);
    return [`### ${iaNode(IA, r.region_id)!.label} — ${r.state}`, '', ms.length ? table(['Metric', 'Class', 'Backing', 'Source', 'Derivation', 'State', 'Evidence', 'Note'], ms.map((m) => [m.label, m.classification, m.backing, m.source, m.derivation ?? '—', m.state, ev(m.evidence), m.note || '—'])) : '_NOT STARTED — contract only: no metric is defined until a source exists._', ''];
  }),
  '## Exports today', '',
  table(['Export', 'State', 'Evidence', 'Note'], brain.AIO_REPORT_EXPORTS.map((x) => [x.label, x.state, ev(x.evidence), x.note])), '',
  '## Export contract (EXPORTS is NOT STARTED — contract only)', '',
  ...bullets(brain.AIO_EXPORT_RULES), '',
  '## Class summary', '',
  table(['Class', 'Metrics'], METRIC_SOURCE_CLASSES.map((k) => [k, String(C.metrics.filter((m) => m.classification === k).length)])), '',
]);

/* ─────────────────────────────── 04 MORE ─────────────────────────────── */

const moreMd = () => rootMd(MORE, '04', 'MORE authority contract', [
  `## Entries (${C.more_entries.length})`, '',
  'MORE is not a junk drawer: every entry has one stated purpose and one owner.', '',
  table(['Entry', 'Is for', 'Owns', 'Not for', 'Distinguishes', 'Potential children', 'State', 'Evidence'], C.more_entries.map((e) => [iaNode(IA, e.entry_id)!.label, e.is_for, e.owns.join(' · '), e.not_for.join(' · ') || '—', e.distinguishes.join('<br>') || '—', iaNode(IA, e.entry_id)!.potential_children.join(' · ') || '—', e.state, ev(e.evidence)])), '',
  '## Distinctions', '',
  table(['Pair', 'Rule'], [
    ['Document visibilities', 'Staff-only (visibility internal) · client-visible (visibility customer) · generated (service / system) · historical / superseded (isCurrent · recordLifecycle · supersededBy). Only client-visible, current or historical documents reach CLIENT OFFICE → VAULT.'],
    ['MECHANIC NETWORK vs MAINTENANCE', 'MORE → MECHANIC NETWORK administers providers (onboarding, verification, directory). WORK → MECHANIC / MAINTENANCE owns tickets and service work.'],
    ['MESSAGES vs INBOX', 'MORE → MESSAGES is the staff side (staff-to-client, internal notes, system notifications). CLIENT OFFICE → INBOX reads customer-visible messages only and keeps its own logic.'],
    ['ACCOUNT vs TEAM & STAFF', 'ACCOUNT is the signed-in staff member’s own profile (NOT STARTED). TEAM & STAFF administers other people and roles (founder act).'],
  ]), '',
]);

/* ─────────────────────────────── 05 ownership ─────────────────────────────── */

const ownershipMd = () => [
  ...MD_HEAD('05 · Root ownership matrix'),
  'One canonical owner per domain. HOME projects, WORK produces, REPORTS aggregates, MORE administers; CLIENT OFFICE sees a client-safe projection only. A projection or oversight root is never a canonical owner (validator).', '',
  table(['DOMAIN', 'CANONICAL OWNER', 'HOME PROJECTION', 'WORK PRODUCTION', 'REPORTS AGGREGATION', 'MORE ADMIN', 'CLIENT SAFE PROJECTION', 'FOUNDER ONLY', 'STAFF ACCESS', 'NOTE'],
    C.ownership.map((o) => [o.label, at(o.canonical_owner), at(o.home_projection), at(o.work_production), at(o.reports_aggregation), at(o.more_admin), at(o.client_safe_projection), o.founder_only ?? '—', ACCESS_LABEL[o.staff_access], o.note || '—'])), '',
  '## Locked locations', '',
  table(['Domain', 'Lives in', 'HOME', 'REPORTS', 'Client'], [
    ['Growth / CRM', at('AIO_OFFICE.MORE.GROWTH_CRM'), 'projects follow-ups (by grant)', 'aggregates (by grant)', 'never visible'],
    ['Billing', at('AIO_OFFICE.MORE.BILLING'), 'projects overdue / failed (by grant)', `aggregates in ${at('AIO_OFFICE.REPORTS.FINANCIAL_REVENUE')}`, `client-safe only: ${at('CLIENT_OFFICE.FINANCES.FEES_PAYMENTS')}`],
  ]), '',
].join('\n');

/* ─────────────────────────────── 06 data sources ─────────────────────────────── */

const dataSourcesMd = () => [
  ...MD_HEAD('06 · Data source matrix'),
  'Source-truth audit per HOME region, WORK lane, REPORTS domain and MORE entry. Backing: PRODUCTION = read from Supabase · DEMO_STORE = the browser-local demo store (shown as demo only) · NONE = no source. Nothing is guessed: a missing contract, table, service or route is named.', '',
  ...C.roots.flatMap((r) => {
    const rows = C.data_sources.filter((d) => d.root === r.root_id);
    return [`## ${at(r.root_id)} (${rows.length})`, '', table(
      ['SUBJECT', 'DATA SOURCE', 'BACKING', 'STATUS', 'WRITE OWNER', 'READERS', 'ACTOR VISIBILITY', 'MISSING CONTRACTS', 'MISSING TABLES / SERVICES', 'MISSING ROUTES', 'EVIDENCE'],
      rows.map((d) => [at(d.subject_id) === d.subject_id ? label(r, d.subject_id) : at(d.subject_id), d.data_source, d.backing, d.state, d.write_owner, d.readers.map(at).join(' · '), vis(d.visibility), d.missing_contracts.join(' · ') || '—', d.missing_tables_services.join(' · ') || '—', d.missing_routes.join(' · ') || '—', ev(d.evidence)]),
    ), ''];
  }),
  '## HOME sources in detail', '',
  ...HOME.regions.flatMap((r) => [`### ${r.label}`, '', ...sourcesTable(r.sources), '']),
  EVIDENCE_KEY, '',
].join('\n');

/* ─────────────────────────────── 07 permissions ─────────────────────────────── */

const F = brain.AIO_FOUNDER_ROLE;
const grantOnly = () => [
  ...C.roots.flatMap((r) => r.regions.flatMap((reg) => reg.sources.filter((s) => s.visibility.STAFF === 'BY_GRANT').map((s) => `${reg.label} · ${s.label}`))),
  ...IA.nodes.filter((n) => n.shell_id === 'AIO_OFFICE' && n.visibility.STAFF === 'BY_GRANT').map((n) => at(n.node_id)),
];
const permissionsMd = () => [
  ...MD_HEAD('07 · Permission matrix'),
  '## Permission boundaries', '',
  table(['Actor', 'Boundary'], [
    ['FOUNDER', 'Privileged internal role: every AIO OFFICE node, founder acts, internal financial visibility. A role held by one or more people — never an identity.'],
    ['STAFF', 'Internal: every AIO OFFICE node except founder acts; grant-only views (financials, reporting, CRM, billing, some settings) need an explicit grant. Never inherits founder authority.'],
    ['CLIENT', 'CLIENT OFFICE only, own organisation only, client-safe projections only. Never AIO OFFICE, never INTAKE, never staff navigation.'],
    ['SERVICE_PROVIDER', 'Its own provider portal and its own records only (tickets assigned to it). Never either office.'],
  ]), '',
  '## Scopes', '',
  table(['Scope', 'FOUNDER', 'STAFF', 'CLIENT', 'SERVICE_PROVIDER', 'Enforced today by', 'Note'], C.permissions.map((p) => [at(p.scope), ACCESS_LABEL[p.access.FOUNDER], ACCESS_LABEL[p.access.STAFF], ACCESS_LABEL[p.access.CLIENT], ACCESS_LABEL[p.access.SERVICE_PROVIDER], p.enforced_by, p.note || '—'])), '',
  '## Staff by grant only', '',
  ...bullets([...new Set(grantOnly())]), '',
  '## FOUNDER role contract', '',
  table(['', ''], [
    ['Definition', F.definition],
    ['Identity', F.identity_rule],
    ['Multiplicity', F.multiplicity],
    ['Code today', F.code_today],
  ]), '',
  '**Assignment**', '',
  ...bullets(F.assignment), '',
  '**Never**', '',
  ...bullets(F.never), '',
  '**Founder acts**', '',
  table(['Act', 'Where', 'Gated today by', 'State', 'Evidence'], F.acts.map((a) => [a.act, a.node_ids.map(at).join(' · ') || '—', a.today, a.state, ev(a.evidence)])), '',
  `**Gaps:** ${F.gaps.join(' · ')}. FOUNDER_ROLE_IMPLEMENTED: NO — no role, auth or database policy was changed in this sprint.`, '',
  EVIDENCE_KEY, '',
].join('\n');

/* ─────────────────────────────── 08 client-safe ─────────────────────────────── */

const privacyGaps = () => C.gaps.filter((g) => g.kind === 'PRIVACY');
const privacyTable = () => table(['Gap', 'What', 'Blocks', 'Evidence'], privacyGaps().map((g) => [g.gap_id, g.gap, g.blocks, ev(g.evidence)]));
const clientSafeMd = () => [
  ...MD_HEAD('08 · Client-safe projection matrix'),
  '## Rule', '',
  ...bullets(CLIENT_SAFE_PROJECTION_RULE), '',
  `## Projections (${C.client_safe.length})`, '',
  table(['Staff side', 'Client side', 'Client sees', 'Client never sees', 'State', 'Evidence'], C.client_safe.map((x) => [at(x.staff_node), at(x.client_node), x.client_sees, x.client_never_sees, x.state, ev(x.evidence)])), '',
  `## Live privacy gaps — verified, recorded, NOT fixed (${privacyGaps().length})`, '',
  'These exist in the fsbw code and migrations today. This sprint changes no auth or schema, so they are recorded, not fixed. A dedicated security sprint should close them before any of these projections is built or shown to clients.', '',
  privacyTable(), '',
  EVIDENCE_KEY, '',
].join('\n');

/* ─────────────────────────────── 09 responsive ─────────────────────────────── */

const responsiveMd = () => [
  ...MD_HEAD('09 · Responsive priority matrix'),
  'Priority order per root and viewport. Mobile: what needs action first, summaries before lists. Tablet: adds blockers and quick actions. Desktop: parallel context. Items not listed for a viewport sit behind navigation there — never removed.', '',
  ...C.responsive.flatMap((rp) => {
    const root = C.roots.find((r) => r.root_id === rp.root_id)!;
    const depth = Math.max(...CONTRACT_VIEWPORTS.map((vp) => rp.order[vp].length));
    return [`## ${at(rp.root_id)}`, '', rp.rule, '', table(['#', ...CONTRACT_VIEWPORTS], Array.from({ length: depth }, (_, i) => [String(i + 1), ...CONTRACT_VIEWPORTS.map((vp) => (rp.order[vp][i] ? label(root, rp.order[vp][i]) : ''))])), ''];
  }),
].join('\n');

/* ─────────────────────────────── 10 gaps ─────────────────────────────── */

const gapRows = (gs: ImplementationGap[]) => table(['Gap', 'Kind', 'Origin', 'What', 'Blocks', 'Evidence'], gs.map((g) => [g.gap_id, g.kind, g.origin, g.gap, g.blocks, ev(g.evidence)]));
const gapsMd = () => {
  const known = brain.AIO_KNOWN_GAPS.map(gap);
  const kinds = [...new Set(C.gaps.map((g) => g.kind))];
  const rest = C.gaps.filter((g) => !brain.AIO_KNOWN_GAPS.includes(g.gap_id as (typeof brain.AIO_KNOWN_GAPS)[number]) && g.kind !== 'PRIVACY');
  return [
    ...MD_HEAD('10 · Implementation gaps'),
    `${C.gaps.length} gaps: ${kinds.map((k) => `${k} ${C.gaps.filter((g) => g.kind === k).length}`).join(' · ')}. Previous NOT STARTED sections stay NOT STARTED; nothing here is fixed by this sprint.`, '',
    '## Known founder gaps (kept until code proves otherwise)', '',
    gapRows(known), '',
    `## Privacy — live, verified, not fixed (${privacyGaps().length})`, '',
    'Recommended: a dedicated security sprint (database policies, views, column grants, client page filters) before any implementation sprint builds on these projections.', '',
    privacyTable(), '',
    ...C.roots.flatMap((r) => {
      const gs = rest.filter((g) => g.root === r.root_id);
      return gs.length ? [`## ${at(r.root_id)} (${gs.length})`, '', gapRows(gs), ''] : [];
    }),
    ...(() => {
      const gs = rest.filter((g) => !C.roots.some((r) => r.root_id === g.root));
      return gs.length ? ['## Whole office (permissions, roles)', '', gapRows(gs), ''] : [];
    })(),
    EVIDENCE_KEY, '',
  ].join('\n');
};

/* ─────────────────────────────── quality gate ─────────────────────────────── */

export function aioOfficeContractsQualityGate() {
  const violations = validateOfficeRootContracts(C, IA);
  const iaLanes = iaChildren(IA, 'AIO_OFFICE.WORK').filter((n) => n.kind === 'SERVICE_LANE').map((n) => n.node_id);
  const homeIds = iaChildren(IA, 'AIO_OFFICE.HOME').map((n) => n.node_id);
  const reportIds = iaChildren(IA, 'AIO_OFFICE.REPORTS').map((n) => n.node_id);
  const moreIds = iaChildren(IA, 'AIO_OFFICE.MORE').map((n) => n.node_id);
  const vf = C.lanes.find((l) => l.lane_id === 'AIO_OFFICE.WORK.VEHICLES_FLEET');
  const vfLinks = ['AIO_OFFICE.WORK.DISPATCH', 'AIO_OFFICE.WORK.COMPLIANCE', 'AIO_OFFICE.WORK.FILING_FUEL_TAXES', 'AIO_OFFICE.WORK.INSURANCE', 'AIO_OFFICE.WORK.MECHANIC_MAINTENANCE', 'AIO_OFFICE.WORK.DRIVERS_CARRIERS', 'AIO_OFFICE.MORE.DOCUMENTS_VAULT', 'AIO_OFFICE.MORE.BILLING', 'AIO_OFFICE.REPORTS'];
  const vfOwns = brain.AIO_VEHICLES_FLEET_SCOPE.filter((x) => x.relation === 'OWNS').map((x) => x.item);
  const own = (d: string) => C.ownership.find((o) => o.domain_id === d)!;
  const rr = C.lanes.find((l) => l.lane_id === 'AIO_OFFICE.WORK.ROAD_READY')!;
  const shownAsData = (s: string) => s === 'AVAILABLE' || s === 'PARTIAL';
  const clientNodes = new Set(C.client_safe.map((x) => x.client_node));
  const dsSubjects = new Set(C.data_sources.map((d) => d.subject_id));
  const required = brain.AIO_REQUIRED_OWNERSHIP_DOMAINS;
  const optional = HOME.regions.filter((r) => r.presence === 'OPTIONAL').map((r) => r.region_id);
  const checks: { key: string; value: string; evidence: string }[] = [
    { key: 'HOME_PURPOSE_LOCKED', value: yes(HOME.stance === 'PROJECTION' && eq(HOME.regions.map((r) => r.region_id), homeIds) && eq(optional, ['AIO_OFFICE.HOME.BUSINESS_PULSE'])), evidence: `${HOME.regions.length} regions = the IA HOME regions in order; Business Pulse the only OPTIONAL one` },
    { key: 'HOME_PROJECTION_ONLY', value: yes(!HOME.owns.length && !HOME.may_mutate.length && HOME.actions.every((a) => a.kind === 'ROUTE') && HOME.regions.every((r) => r.sources.every((s) => !under(s.owner_node, HOME.root_id)))), evidence: `owns 0 · mutates 0 · ${HOME.actions.length} actions, all ROUTE · every source owned outside HOME` },
    { key: 'WORK_PURPOSE_LOCKED', value: yes(WORK.stance === 'PRODUCTION' && brain.AIO_WORK_ROOT_CAPABILITIES.length === 15 && WORK.must_not.some((m) => /REPORTS/.test(m))), evidence: `PRODUCTION · ${brain.AIO_WORK_ROOT_CAPABILITIES.length} root capabilities · history stays in REPORTS` },
    { key: 'WORK_12_LANES_REPRESENTED', value: yes(eq(C.lanes.map((l) => l.lane_id), iaLanes) && iaLanes.length === 12 && C.lanes.every((l) => LANE_SHELL_SECTIONS.every((s) => !!l.shell[s]))), evidence: `${C.lanes.length} lane contracts = the IA lanes in order, each with the ${LANE_SHELL_SECTIONS.length}-part shell; IFTA preserved` },
    { key: 'VEHICLES_FLEET_CONTRACT_DEFINED', value: yes(!!vf && own('VEHICLES').canonical_owner === vf.lane_id && vfLinks.every((t) => vf.related.some((r) => under(r.node_id, t))) && ['Vehicle roster', 'Vehicle profiles', 'Registration state'].every((x) => vfOwns.includes(x)) && vf.gaps.includes('G-VEHICLES-NO-STAFF-SCREEN')), evidence: `owns ${vfOwns.join(' · ')} · cross-links ${vf?.related.length ?? 0} (the founder’s 9 + Tags / Registration) · NO STAFF SCREEN YET recorded` },
    { key: 'REPORTS_PURPOSE_LOCKED', value: yes(REPORTS.stance === 'OVERSIGHT' && !REPORTS.may_mutate.length && eq(REPORTS.regions.map((r) => r.region_id), reportIds) && reportIds.length === 10), evidence: `OVERSIGHT · mutates nothing · ${REPORTS.regions.length} domains = the IA report domains` },
    { key: 'REPORTS_FAKE_DATA_PROHIBITED', value: yes(C.metrics.every((m) => !((m.classification === 'NOT_IMPLEMENTED' || m.classification === 'DERIVED_UNSUPPORTED') && shownAsData(m.state)) && (m.classification !== 'REAL_DATA' || m.backing === 'PRODUCTION')) && C.metrics.filter((m) => /profitab/i.test(m.label)).every((m) => m.classification === 'DERIVED_UNSUPPORTED' && !shownAsData(m.state))), evidence: `${C.metrics.length} metrics classified (${METRIC_SOURCE_CLASSES.map((k) => `${k} ${C.metrics.filter((m) => m.classification === k).length}`).join(' · ')}); none unsupported shown as data; profitability never shown` },
    { key: 'MORE_PURPOSE_LOCKED', value: yes(MORE.stance === 'ADMINISTRATION' && eq(C.more_entries.map((e) => e.entry_id), moreIds) && moreIds.length === 11 && C.more_entries.every((e) => e.is_for.length > 0) && C.more_entries.find((e) => e.entry_id === 'AIO_OFFICE.MORE.ACCOUNT')?.state === 'NOT_IMPLEMENTED'), evidence: `${C.more_entries.length} entries, each with a purpose and owner; ACCOUNT NOT STARTED` },
    { key: 'CRM_LOCATION_LOCKED', value: yes(own('CRM').canonical_owner === 'AIO_OFFICE.MORE.GROWTH_CRM' && own('CRM').client_safe_projection === null && own('CRM').home_projection?.startsWith('AIO_OFFICE.HOME') === true), evidence: 'MORE → GROWTH / CRM owns; HOME projects; never client-visible' },
    { key: 'BILLING_LOCATION_LOCKED', value: yes(own('BILLING').canonical_owner === 'AIO_OFFICE.MORE.BILLING' && own('BILLING').reports_aggregation === 'AIO_OFFICE.REPORTS.FINANCIAL_REVENUE' && own('BILLING').client_safe_projection === 'CLIENT_OFFICE.FINANCES.FEES_PAYMENTS'), evidence: 'MORE → BILLING owns; REPORTS aggregates; client sees FINANCES → FEES / PAYMENTS only' },
    { key: 'FOUNDER_ROLE_ARCHITECTURE_DEFINED', value: yes(C.privileged_roles.some((r) => r.role === 'FOUNDER' && r.multiplicity === 'ONE_OR_MORE' && r.acts.length > 0) && violations.length === 0), evidence: `${F.acts.length} founder acts with today’s gate · assignment, never-rules and gaps recorded` },
    { key: 'FOUNDER_ROLE_IMPLEMENTATION_CHANGED', value: 'NO', evidence: 'no auth, role or database-policy change' },
    { key: 'ROAD_READY_STATE_INVENTED', value: yes(!(rr.gaps.includes('G-ROAD-READY-NO-ENGAGEMENT-STATE') && rr.shell.RECENTLY_COMPLETED.state === 'BLOCKED')), evidence: 'engagement state recorded as missing (G-ROAD-READY-NO-ENGAGEMENT-STATE); RECENTLY COMPLETED BLOCKED' },
    { key: 'CLIENT_SAFE_PROJECTIONS_DEFINED', value: yes(C.ownership.every((o) => !o.client_safe_projection || clientNodes.has(o.client_safe_projection))), evidence: `${C.client_safe.length} projections; every ownership domain with a client side has a row` },
    { key: 'ROOT_OWNERSHIP_MATRIX', value: C.ownership.length >= 20 && required.every((d) => C.ownership.some((o) => o.domain_id === d)) ? 'COMPLETE' : 'INCOMPLETE', evidence: `${C.ownership.length} domains (${required.length} required + WORK_ITEMS)` },
    { key: 'DATA_SOURCE_MATRIX', value: [...HOME.regions.map((r) => r.region_id), ...C.lanes.map((l) => l.lane_id), ...REPORTS.regions.map((r) => r.region_id), ...C.more_entries.map((e) => e.entry_id)].every((id) => dsSubjects.has(id)) ? 'COMPLETE' : 'INCOMPLETE', evidence: `${C.data_sources.length} rows: every HOME region, WORK lane, REPORTS domain and MORE entry` },
    { key: 'RESPONSIVE_PRIORITY_MATRIX', value: C.roots.every((r) => C.responsive.some((rp) => rp.root_id === r.root_id && CONTRACT_VIEWPORTS.every((vp) => rp.order[vp].length > 0))) ? 'COMPLETE' : 'INCOMPLETE', evidence: `${C.responsive.length} roots × ${CONTRACT_VIEWPORTS.length} viewports` },
    { key: 'PRIVACY_GAPS_RECORDED', value: String(privacyGaps().length), evidence: 'verified live; not fixed (no auth / schema change) — recommend a security sprint' },
    { key: 'VISUAL_REDESIGN_PERFORMED', value: 'NO', evidence: 'no page, image or visual authority touched' },
    { key: 'LIVE_IMPLEMENTATION_CHANGED', value: 'NO', evidence: 'no route, nav, page, schema, lifecycle or auth change' },
  ];
  const MUST_BE_NO = ['FOUNDER_ROLE_IMPLEMENTATION_CHANGED', 'ROAD_READY_STATE_INVENTED', 'VISUAL_REDESIGN_PERFORMED', 'LIVE_IMPLEMENTATION_CHANGED'];
  const ready = violations.length === 0 && checks.every((c) => (MUST_BE_NO.includes(c.key) ? c.value === 'NO' : !['NO', 'INCOMPLETE'].includes(c.value)));
  checks.push({ key: 'READY_FOR_FOUNDER_CONTRACT_REVIEW', value: yes(ready), evidence: `validator violations ${violations.length}` });
  const report = {
    WORK_SERVICE_LANES: C.lanes.length,
    MORE_ENTRIES: C.more_entries.length,
    HOME_REGIONS: `${HOME.regions.length} (${HOME.regions.filter((r) => r.presence === 'REQUIRED').length} required + ${optional.length} optional)`,
    REPORT_DOMAINS: REPORTS.regions.length,
    FOUNDER_ROLE_IMPLEMENTED: 'NO',
    ROAD_READY_ENGAGEMENT_STATE_EXISTS: 'NO',
    VEHICLES_FLEET_STAFF_SCREEN_EXISTS: 'NO',
    FAKE_METRICS_INTRODUCED: 'NO',
  };
  return { ...head('AIO_OFFICE_CONTRACTS_QUALITY_GATE'), checks, report, violations };
}

/* ─────────────────────────────── README ─────────────────────────────── */

const ARTIFACTS: [string, string][] = [
  ['01_HOME_AUTHORITY_CONTRACT.md', 'HOME — projection-only command center: 8 regions, sources, route-only actions'],
  ['02_WORK_AUTHORITY_CONTRACT.md', 'WORK — production: 15 capabilities, common lane shell, 12 lane contracts, VEHICLES & FLEET'],
  ['03_REPORTS_AUTHORITY_CONTRACT.md', 'REPORTS — oversight: 10 domains, every metric classified, exports'],
  ['04_MORE_AUTHORITY_CONTRACT.md', 'MORE — administration: 11 entries and their distinctions'],
  ['05_ROOT_OWNERSHIP_MATRIX.md', 'One canonical owner per domain, and who projects / produces / aggregates / administers it'],
  ['06_DATA_SOURCE_MATRIX.md', 'Source-truth audit per region, lane, domain and entry'],
  ['07_PERMISSION_MATRIX.md', 'Actor boundaries, scopes, grant-only views, FOUNDER role contract'],
  ['08_CLIENT_SAFE_PROJECTION_MATRIX.md', 'What crosses to the client, what never does, and the live privacy gaps'],
  ['09_RESPONSIVE_PRIORITY_MATRIX.md', 'Priority order per root on mobile, tablet and desktop'],
  ['10_IMPLEMENTATION_GAPS.md', 'Every missing state, role, surface, table, route and contract, with evidence'],
  ['AIO_OFFICE_ROOT_CONTRACTS.json', 'Everything above, machine-readable'],
  ['ROOT_OWNERSHIP_MATRIX.json · DATA_SOURCE_MATRIX.json · PERMISSION_MATRIX.json · CLIENT_SAFE_PROJECTION_MATRIX.json · RESPONSIVE_PRIORITY_MATRIX.json · IMPLEMENTATION_GAPS.json', 'Each matrix on its own'],
  ['QUALITY_GATE.json', 'The sprint quality gate, computed from the contracts'],
];

function readmeMd() {
  const gate = aioOfficeContractsQualityGate();
  return [
    ...MD_HEAD('AIO OFFICE root authority contracts — HOME · WORK · REPORTS · MORE'),
    'What each root owns, only projects, reads and may mutate; what is staff-only and founder-only; what belongs elsewhere; and what each surface does when source truth is partial or absent. Built on the canonical office IA; every feed is evidence-cited against fsbw.', '',
    table(['Root', 'Stance', 'Primary question', 'Regions', 'Actions'], C.roots.map((r) => [at(r.root_id), r.stance, r.primary_question, String(r.regions.length), `${r.actions.length} (${[...new Set(r.actions.map((a) => a.kind))].join(' · ')})`])), '',
    `**Honest states:** ${SURFACE_STATES.join(' · ')} (+ ERROR for a failed load). A surface that is not AVAILABLE says so; nothing is filled with examples.`, '',
    '## Read first: live privacy gaps', '',
    `${privacyGaps().length} privacy gaps were verified in fsbw during the audit (cross-organisation views, internal notes reaching shippers and clients, clients able to change their own lifecycle). They are recorded, not fixed — this sprint changes no auth or schema. See [08](08_CLIENT_SAFE_PROJECTION_MATRIX.md) and [10](10_IMPLEMENTATION_GAPS.md). Recommended: a dedicated security sprint before implementation.`, '',
    '## Artifacts', '',
    table(['File', 'What'], ARTIFACTS.map(([f, w]) => [f.includes('·') ? f : `[${f}](${f})`, w])), '',
    '## Quality gate', '',
    table(['Check', 'Value', 'Evidence'], gate.checks.map((c) => [c.key, c.value, c.evidence])), '',
    table(['Report field', 'Value'], Object.entries(gate.report).map(([k, v]) => [k, String(v)])), '',
    `Next sprint: \`${brain.AIO_OFFICE_CONTRACTS_NEXT_SPRINT}\`.`, '',
  ].join('\n');
}

/* ─────────────────────────────── build ─────────────────────────────── */

export function buildAioOfficeContractsExports(): Record<string, string> {
  return {
    'README.md': readmeMd(),
    '01_HOME_AUTHORITY_CONTRACT.md': homeMd(),
    '02_WORK_AUTHORITY_CONTRACT.md': workMd(),
    '03_REPORTS_AUTHORITY_CONTRACT.md': reportsMd(),
    '04_MORE_AUTHORITY_CONTRACT.md': moreMd(),
    '05_ROOT_OWNERSHIP_MATRIX.md': ownershipMd(),
    '06_DATA_SOURCE_MATRIX.md': dataSourcesMd(),
    '07_PERMISSION_MATRIX.md': permissionsMd(),
    '08_CLIENT_SAFE_PROJECTION_MATRIX.md': clientSafeMd(),
    '09_RESPONSIVE_PRIORITY_MATRIX.md': responsiveMd(),
    '10_IMPLEMENTATION_GAPS.md': gapsMd(),
    'AIO_OFFICE_ROOT_CONTRACTS.json': json({
      ...head('AIO_OFFICE_ROOT_CONTRACTS'), next_sprint: brain.AIO_OFFICE_CONTRACTS_NEXT_SPRINT,
      rules: { action_ownership: ACTION_OWNERSHIP_RULE, client_safe_projection: CLIENT_SAFE_PROJECTION_RULE },
      state_vocabularies: { surface_states: SURFACE_STATES, metric_source_classes: METRIC_SOURCE_CLASSES, lane_shell_sections: LANE_SHELL_SECTIONS, viewports: CONTRACT_VIEWPORTS },
      work_lane_order: brain.AIO_WORK_LANE_ORDER, work_root_capabilities: brain.AIO_WORK_ROOT_CAPABILITIES, report_exports: brain.AIO_REPORT_EXPORTS, known_gaps: brain.AIO_KNOWN_GAPS,
      ...C,
    }),
    'ROOT_OWNERSHIP_MATRIX.json': json({ ...head('AIO_ROOT_OWNERSHIP_MATRIX'), columns: ['DOMAIN', 'CANONICAL OWNER', 'HOME PROJECTION', 'WORK PRODUCTION', 'REPORTS AGGREGATION', 'MORE ADMIN', 'CLIENT SAFE PROJECTION', 'FOUNDER ONLY', 'STAFF ACCESS'], domains: C.ownership }),
    'DATA_SOURCE_MATRIX.json': json({ ...head('AIO_DATA_SOURCE_MATRIX'), columns: ['DATA SOURCE', 'STATUS', 'WRITE OWNER', 'READERS', 'ACTOR VISIBILITY', 'MISSING CONTRACTS', 'MISSING TABLES / SERVICES', 'MISSING ROUTES'], rows: C.data_sources, home_sources: HOME.regions.map((r) => ({ region_id: r.region_id, sources: r.sources })) }),
    'PERMISSION_MATRIX.json': json({ ...head('AIO_PERMISSION_MATRIX'), actors: CONTRACT_ACTORS, scopes: C.permissions, privileged_roles: C.privileged_roles }),
    'CLIENT_SAFE_PROJECTION_MATRIX.json': json({ ...head('AIO_CLIENT_SAFE_PROJECTION_MATRIX'), rule: CLIENT_SAFE_PROJECTION_RULE, projections: C.client_safe, privacy_gaps: privacyGaps() }),
    'RESPONSIVE_PRIORITY_MATRIX.json': json({ ...head('AIO_RESPONSIVE_PRIORITY_MATRIX'), viewports: CONTRACT_VIEWPORTS, roots: C.responsive }),
    'IMPLEMENTATION_GAPS.json': json({ ...head('AIO_IMPLEMENTATION_GAPS'), known_gaps: brain.AIO_KNOWN_GAPS, gaps: C.gaps }),
    'QUALITY_GATE.json': json(aioOfficeContractsQualityGate()),
  };
}

if (process.argv[1] && /aio-office-contracts-export\.ts$/.test(process.argv[1])) {
  mkdirSync(AIO_OFFICE_CONTRACTS_DOCS_DIR, { recursive: true });
  const files = buildAioOfficeContractsExports();
  for (const [name, body] of Object.entries(files)) writeFileSync(`${AIO_OFFICE_CONTRACTS_DOCS_DIR}/${name}`, body);
  console.log(`exported ${Object.keys(files).length} files to ${AIO_OFFICE_CONTRACTS_DOCS_DIR}`);
}
