export const PROJECT_NOTIFICATION_DROPDOWN_LIMIT = 12;

export const PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER = '__DEV_FIXTURE__';

export const FOUNDER_RELEVANT_EVENT_TYPES = new Set([
  'GENERATION_COMPLETE',
  'GENERATION_FAILED',
  'GENERATION_BLOCKED',
  'REVIEW_REQUIRED',
  'APPROVAL_REQUIRED',
  'FOUNDER_JUDGMENT_REQUIRED',
  'CHARACTER_TURNAROUND_READY',
  'CHARACTER_ISOLATE_READY',
  'CHARACTER_CONTINUITY_DRIFT',
  'SLIDE_REVIEW_REQUIRED',
  'CAMPAIGN_ASSETS_UPDATED',
  'CULTURAL_SIGNAL_NEW',
  'FILM_SHOT_READY',
  'EXPERIMENT_READY',
  'SYSTEM_MESSAGE',
]);

export const INTERNAL_EVENT_SUPPRESS = new Set([
  'PERSISTENCE_WRITE',
  'STATE_SYNC',
  'IDEMPOTENCY_HIT',
  'CACHE_REFRESH',
  'QA_STORED',
  'PROVIDER_DISPATCHED',
  'GENERATION_QUEUED',
  'GENERATION_STARTED',
]);
