import { randomUUID } from 'node:crypto';
import { PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER } from './constants.js';
import type { ProjectNotification } from './types.js';

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

/** Development-only founder notification fixtures — never production founder alerts. */
export function buildDevProjectNotificationFixtures(projectId: string): ProjectNotification[] {
  return [
    {
      id: `${PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER}:review:${randomUUID()}`,
      projectId,
      type: 'SLIDE_REVIEW_REQUIRED',
      category: 'REVIEW_REQUIRED',
      title: 'SLIDE 03 NEEDS YOUR EYE',
      message: 'Meet NDX · founder creative ingestion',
      createdAt: minutesAgo(14),
      readAt: null,
      status: 'UNREAD',
      priority: 'HIGH',
      sourceSystem: 'founder_creative_ingestion',
      sourceEntityType: 'SLIDE',
      sourceEntityId: 'slide-03',
      actionType: 'REVIEW',
      actionTarget: null,
      isDevFixture: true,
      metadata: { fixture: true, slideLabel: '03' },
    },
    {
      id: `${PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER}:character:${randomUUID()}`,
      projectId,
      type: 'CHARACTER_TURNAROUND_READY',
      category: 'CHARACTER_UPDATE',
      title: 'CHARACTER TURNAROUND READY FOR REVIEW',
      message: 'Identity pack · casting lab',
      createdAt: minutesAgo(2),
      readAt: null,
      status: 'UNREAD',
      priority: 'NORMAL',
      sourceSystem: 'character_casting',
      sourceEntityType: 'CHARACTER_ASSET',
      sourceEntityId: 'turnaround-pack-01',
      actionType: 'REVIEW',
      actionTarget: null,
      isDevFixture: true,
    },
    {
      id: `${PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER}:complete:${randomUUID()}`,
      projectId,
      type: 'GENERATION_COMPLETE',
      category: 'GENERATION_COMPLETE',
      title: 'CREDIT UTILIZATION HERO REGENERATION COMPLETE',
      message: 'Experiment 01 · V23',
      createdAt: minutesAgo(45),
      readAt: minutesAgo(30),
      status: 'READ',
      priority: 'NORMAL',
      sourceSystem: 'marketing_expression',
      sourceEntityType: 'EXPERIMENT',
      sourceEntityId: 'experiment-01-v23',
      actionType: 'VIEW',
      actionTarget: null,
      isDevFixture: true,
    },
    {
      id: `${PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER}:failed:${randomUUID()}`,
      projectId,
      type: 'GENERATION_FAILED',
      category: 'GENERATION_FAILED',
      title: 'MEET NDX REFERENCE DECOMPOSITION FAILED',
      message: 'Provider timeout · retry available',
      createdAt: minutesAgo(90),
      readAt: null,
      status: 'UNREAD',
      priority: 'HIGH',
      sourceSystem: 'founder_creative_ingestion',
      sourceEntityType: 'SLIDE',
      sourceEntityId: 'meet-ndx-ref',
      actionType: 'VIEW',
      actionTarget: null,
      isDevFixture: true,
    },
    {
      id: `${PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER}:cultural:${randomUUID()}`,
      projectId,
      type: 'CULTURAL_SIGNAL_NEW',
      category: 'CULTURAL_INTELLIGENCE_ALERT',
      title: 'NEW CULTURAL SIGNAL ENTERED THE WATCH QUEUE',
      message: 'Subscription fatigue · cultural intelligence',
      createdAt: minutesAgo(60),
      readAt: minutesAgo(55),
      status: 'READ',
      priority: 'NORMAL',
      sourceSystem: 'cultural_intelligence',
      sourceEntityType: 'CULTURAL_SIGNAL',
      sourceEntityId: 'signal-subscription-fatigue',
      actionType: 'VIEW',
      actionTarget: null,
      isDevFixture: true,
    },
    {
      id: `${PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER}:campaign:${randomUUID()}`,
      projectId,
      type: 'CAMPAIGN_ASSETS_UPDATED',
      category: 'CAMPAIGN_UPDATE',
      title: 'CAMPAIGN WEEK 01 HAS 2 UNRESOLVED ASSETS',
      message: '3 assets ready · campaign board',
      createdAt: minutesAgo(120),
      readAt: null,
      status: 'UNREAD',
      priority: 'NORMAL',
      sourceSystem: 'campaign_production',
      sourceEntityType: 'CAMPAIGN',
      sourceEntityId: 'week-01',
      actionType: 'VIEW',
      actionTarget: null,
      isDevFixture: true,
    },
    {
      id: `${PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER}:system:${randomUUID()}`,
      projectId,
      type: 'SYSTEM_MESSAGE',
      category: 'SYSTEM_MESSAGE',
      title: 'STUDIO WORLD NOTIFICATION CENTER ONLINE',
      message: 'Dev fixture · messages transport blocked',
      createdAt: minutesAgo(180),
      readAt: minutesAgo(170),
      status: 'READ',
      priority: 'LOW',
      sourceSystem: 'studio_world',
      sourceEntityType: 'PROJECT',
      sourceEntityId: projectId,
      actionType: 'NONE',
      actionTarget: null,
      isDevFixture: true,
    },
  ];
}

export function isDevFixtureNotification(notification: Pick<ProjectNotification, 'id' | 'isDevFixture'>): boolean {
  return notification.isDevFixture === true || notification.id.includes(PROJECT_NOTIFICATION_DEV_FIXTURE_MARKER);
}
