/**
 * NDXBOOK Core Direction Boards + Branch Lineage declarations — the Stage A / Stage B
 * validation example for docs/site00/CORE_DIRECTION_METHODOLOGY.md.
 *
 * These three CoreDirectionDefinitions are the formal "do we believe this world?"
 * answer for each direction (§2–3). The BranchLineageDeclarations retroactively
 * document why every branch already built for each direction (see
 * docs/studio-world/ndxbook/NDXBOOK_CD_REFERENCE_DECOMPOSITION.md) legitimately
 * emerges from that direction's Core Concept, using the seven-question lineage
 * test from §8. None of the three directions has reached CORE_DIRECTION_APPROVED —
 * see types.ts coreDirectionGateStatus() — so none of this is canonical yet; it is
 * the Core Direction Board + Branch Lineage record awaiting founder review.
 */

import type { BranchLineageDeclaration, CoreDirectionDefinition, TerritoryRendererKey } from './types.js';

export const NDXBOOK_CORE_DIRECTIONS: Record<TerritoryRendererKey, CoreDirectionDefinition> = {
  editorial_utility: {
    directionName: 'EDITORIAL UTILITY',
    bigIdea:
      'NDX BOOK is a living, evolving editorial dossier on the things that shape our lives — money and credit are just two subjects inside a much larger book.',
    oneLineThesis: 'THE BOOK ON EVERYTHING.',
    brandConnection:
      'NDX BOOK\u2019s core promise ("every page makes you smarter") is literally the behavior of a book that never stops being written \u2014 annotated, evidenced, and opinionated in a voice only NDX would use.',
    culturalReference:
      'The culturally recognizable BEHAVIOR of a Burn Book \u2014 opinion, annotation, evidence, insertion, handwriting, commentary, physical interruption \u2014 matured into a contemporary independent-magazine publication system. Not the physical prop; the behavior it represents.',
    emotionalPromise:
      'You feel like someone finally wrote down the thing everyone was thinking but nobody said in print \u2014 confident, opinionated, a little unfiltered, but never mean.',
    visualMetaphor: 'The page as evidence locker \u2014 every page is a record, a receipt, a note in the margin, a redaction, something taped in.',
    governingBehavior:
      'ANNOTATION \u2014 the visual system\u2019s fundamental behavior is marking, commenting on, and interrupting existing information, not presenting it neutrally.',
    materialImageryLanguage:
      'Premium uncoated publication paper, clean torn edges, translucent tape, receipt paper, black marker, contemporary editorial photography \u2014 physical without being old.',
    typographicAttitude:
      'Confident modern editorial \u2014 serif-accent wordmark, large confident sans headlines, comfortable reading body, small-caps metadata labels.',
    coreColorLogic:
      'Paper white / black / neutral gray foundation with SIGNAL LIME reserved strictly for editorial intervention (marker, highlight, stamp, underline) \u2014 never a flood fill.',
    signatureDevices: [
      'Lime marker / underline interruption',
      'Torn-edge paper fragments',
      'Redaction bars',
      '"FACTS." stamp',
      'Handwritten margin annotation',
    ],
    primaryBrandArtifact:
      'THE RECEIPTS \u2014 an isolated, annotated evidence fragment (a real receipt) placed onto an editorial page and lime-stamped "FACTS."',
    proprietaryQuality:
      'Burn-Book-derived annotation behavior + modern independent-magazine production values + a single reserved accent used only as an editorial mark is not generic "editorial brand" territory \u2014 most editorial brands are either purely clean-minimal or purely maximalist collage; NDX is annotated-minimal.',
    antiDirection: [
      'Must never become antique parchment / vintage diary / cottage-core scrapbook',
      'Must never flood the page in lime',
      'Must never look like a school notebook or Pinterest moodboard',
      'Must never become an ecommerce or SaaS layout',
    ],
  },
  index_signal: {
    directionName: 'INDEX SIGNAL',
    bigIdea: 'The world produces constant noise about money, culture, and behavior; NDX BOOK\u2019s job is to find and surface the signal inside it.',
    oneLineThesis: 'FIND THE SIGNAL.',
    brandConnection:
      'NDX BOOK\u2019s promise to make readers smarter requires actually noticing patterns other publications miss \u2014 Index Signal makes that noticing behavior visible as the brand\u2019s core visual act.',
    culturalReference:
      'Scientific observation and signal-processing instrumentation \u2014 oscilloscopes, scanning equipment, field-note archives, technical publishing diagrams \u2014 reinterpreted as an editorial voice, not a SaaS dashboard.',
    emotionalPromise:
      'You feel like you\u2019re being let in on something precise and slightly ahead of everyone else \u2014 observant, quietly authoritative, never anxious or salesy.',
    visualMetaphor: 'The scan \u2014 a beam or instrument passing over ordinary life and returning a finding.',
    governingBehavior:
      'SCANNING \u2014 the visual system\u2019s fundamental behavior is detecting and isolating one signal out of ambient noise, then reporting it plainly.',
    materialImageryLanguage:
      'Real-world photography interrupted by cobalt analysis marks, archival/library environments, macro object photography treated like evidence under instrumentation, technical coordinate/diagram overlays.',
    typographicAttitude:
      'Geometric sans wordmark with tight tracking; monospace for every metadata/coordinate/identifier, reinforcing an instrument-readout feel without becoming a UI.',
    coreColorLogic:
      'Graphite / ice-white foundation with ELECTRIC COBALT as the single proprietary signal color \u2014 used for lines, alerts, and findings, never as ambient wallpaper.',
    signatureDevices: [
      'Cobalt connection-line diagrams',
      'Coordinate / index-card stamps',
      'Monospace metadata labels',
      'Scan-line overlays',
      'Signal alert cards',
    ],
    primaryBrandArtifact:
      'THE SCAN \u2014 a real photographic environment (an archive) with a cobalt scan-line and "SCANNING ARCHIVE\u00b7\u00b7\u00b7" readout overlaid, mid-detection.',
    proprietaryQuality:
      'Signal imagery paired with editorial voice (not SaaS copy) and a single reserved cobalt is not interchangeable with fintech/analytics-dashboard visual language \u2014 most data-forward brands read as tools; Index Signal reads as an editorial voice with instruments.',
    antiDirection: [
      'Must never become a SaaS/fintech dashboard',
      'Must never use generic stock chart imagery',
      'Must never look like a Bloomberg terminal or gamer HUD',
      'Must never bury the editorial voice under raw numbers',
    ],
  },
  kinetic_field: {
    directionName: 'KINETIC FIELD',
    bigIdea: 'Knowledge is not static \u2014 every decision produces momentum, and NDX BOOK visualizes the forces that choices set into motion.',
    oneLineThesis: 'EVERYTHING MOVES SOMETHING.',
    brandConnection:
      'NDX BOOK exists to show readers what actually happens after a choice \u2014 Kinetic Field is the direction that makes consequence itself visible as physics rather than as advice.',
    culturalReference:
      'Physical motion principles \u2014 orbit, collision, momentum, drag, ripple \u2014 borrowed from physics/astrophysics visualization and high-speed photography, not from generic neon/cyberpunk decoration.',
    emotionalPromise:
      'You feel the stakes of a decision physically \u2014 urgency, momentum, cause-and-effect \u2014 without being scared or lectured.',
    visualMetaphor: 'The frozen frame \u2014 a still image that reads unmistakably as a moment extracted from something still moving.',
    governingBehavior:
      'MOVEMENT \u2014 the visual system\u2019s fundamental behavior is depicting force, trajectory, and consequence in a single still frame, always implying a before/after.',
    materialImageryLanguage:
      'Motion-blurred documentary photography of real human movement, particle/trail renders, physics-diagram line work \u2014 always tied to a specific motion principle, never decorative glow alone.',
    typographicAttitude:
      'Compressed display sans that reads as a "signal block," variable-weight motion-ready headline type, tabular numerals for velocity/momentum metrics.',
    coreColorLogic:
      'Terminal-black dark field with a rose / orange / deep-purple momentum spectrum \u2014 each motion principle can lean into any of the three hues, never one flat neon accent.',
    signatureDevices: [
      'Radial / orbit motion-path lines',
      'Frame-sequence storyboards',
      'Velocity / momentum numerals',
      'Collision burst marks',
      'Frozen-motion photography crops',
    ],
    primaryBrandArtifact:
      'THE PUSH \u2014 a real photograph of a body mid-motion (a runner captured mid-stride) with a code-native motion-path line and "YOU PUSH FIRST." callout.',
    proprietaryQuality:
      'Deriving every composition from a named physical motion principle (never "neon aesthetic" alone) keeps the direction from collapsing into generic cyberpunk/gaming decoration \u2014 motion is always in service of a specific idea (pull, collision, momentum), never ambient.',
    antiDirection: [
      'Must never become a generic purple gradient wallpaper',
      'Must never become a screensaver or gaming aesthetic',
      'Must never use decorative glow without a named motion principle behind it',
      'Must never become a cyberpunk city or sci-fi clich\u00e9',
    ],
  },
};

const CHANNELS_SOCIAL = ['FEED', 'CAROUSEL', 'STORIES', 'REELS', 'CAMPAIGN_MOMENTS'];

function pass(notes: string): BranchLineageDeclaration['lineageTest'] {
  return {
    emergesFromCoreConcept: true,
    explainableWithoutColorAlone: true,
    preservesCoreDna: true,
    introducesMeaningfulVariation: true,
    servesActualPurpose: true,
    recognizableWithoutBrandName: true,
    distinctFromSiblings: true,
    notes,
  };
}

export const NDXBOOK_BRANCH_LINEAGE: Record<TerritoryRendererKey, BranchLineageDeclaration[]> = {
  editorial_utility: [
    {
      branchName: 'THE BURN PAGE',
      specimenType: 'branch_burn_page',
      branchPurpose: 'Opinionated commentary \u2014 the book takes a side.',
      coreLineage: 'A book that annotates the world must sometimes just state an opinion outright \u2014 this is annotation at its most direct.',
      conceptualTranslation: 'Governing behavior (ANNOTATION) expressed as bold, underlined, unhedged claim rather than a marked-up existing artifact.',
      visualLineage: 'Black/white foundation, lime underline as the sole intervention, editorial type scale.',
      differentiation: 'Only branch that is a bare opinion statement with no secondary artifact \u2014 the most typographic, least material branch.',
      primaryBehavior: 'State a claim, underline the load-bearing word in lime.',
      assetRequirements: 'CODE_NATIVE \u2014 typography and a single lime rule; no photography required.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE LIST (ranked) and MARGIN NOTES (brief aside) by being a single, forceful, unranked claim.'),
    },
    {
      branchName: 'THE RECEIPTS',
      specimenType: 'branch_receipts',
      branchPurpose: 'Evidence, proof, documentation.',
      coreLineage: 'Annotation requires something to annotate \u2014 THE RECEIPTS supplies the physical evidence a Burn Book would tape in.',
      conceptualTranslation: 'A real, isolated evidence artifact (photographed receipt) is composited under a lime "FACTS." stamp \u2014 the book showing its work.',
      visualLineage: 'Isolated paper artifact (REMOVE_BACKGROUND), lime stamp intervention, black/white page.',
      differentiation: 'Only branch built as a HYBRID_COMPOSITION with a real isolated photographic prop \u2014 proves the material language beyond SVG.',
      primaryBehavior: 'Present a physical artifact as evidence, stamp it as verified.',
      assetRequirements: 'HYBRID_COMPOSITION \u2014 FAL-generated receipt, background-removed, composited with code-native stamp/headline.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE INSERT (found cultural artifact) by being specifically a financial/proof document, not a cultural reference object.'),
    },
    {
      branchName: 'MARGIN NOTES',
      specimenType: 'branch_margin_notes',
      branchPurpose: 'Short observations / small thoughts.',
      coreLineage: 'A book has margins; a Burn Book\u2019s margins are where the real commentary happens \u2014 brief, human, handwritten-feeling.',
      conceptualTranslation: 'ANNOTATION at its smallest scale \u2014 a fragment of thought, not a full argument.',
      visualLineage: 'Quiet typographic treatment, small scale, quote-like presentation.',
      differentiation: 'The lowest-density, quietest branch \u2014 provides feed rhythm contrast against dense collage branches like THE FILE or THE INSERT.',
      primaryBehavior: 'Present one short, human observation.',
      assetRequirements: 'CODE_NATIVE \u2014 typography only.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE BURN PAGE by being an aside rather than a forceful claim \u2014 tone is reflective, not confrontational.'),
    },
    {
      branchName: 'THE LIST',
      specimenType: 'branch_the_list',
      branchPurpose: 'Rankings, frameworks, recommendations.',
      coreLineage: 'A book that covers everything eventually organizes what it knows \u2014 THE LIST is the book\u2019s framework-building behavior.',
      conceptualTranslation: 'ANNOTATION applied to a set, not a single fact \u2014 ranking/ordering as a form of editorial judgment.',
      visualLineage: 'Numbered/ranked layout, lime used to mark the top or flagged items only.',
      differentiation: 'Only branch with an explicit ranked/ordered structure \u2014 distinct from THE FILE\u2019s open-ended investigation format.',
      primaryBehavior: 'Rank or order a set of items with editorial judgment visible.',
      assetRequirements: 'CODE_NATIVE \u2014 typographic list treatment.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE FILE by being a closed, ranked set rather than an open investigation.'),
    },
    {
      branchName: 'THE FILE',
      specimenType: 'branch_the_file',
      branchPurpose: 'Deep dives / investigations.',
      coreLineage: 'A book\u2019s longest entries are its investigations \u2014 THE FILE is where the annotation behavior gets sustained across many observations.',
      conceptualTranslation: 'Multiple annotated data points accumulate into a single dossier-style entry.',
      visualLineage: 'Dark file-folder treatment, indexed/numbered entries, restrained lime tick marks.',
      differentiation: 'The highest-density, most investigative branch \u2014 contrasts with the sparse MARGIN NOTES.',
      primaryBehavior: 'Accumulate multiple related facts into one dossier composition.',
      assetRequirements: 'CODE_NATIVE \u2014 typography and index marks; no photography required this pass.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE LIST by presenting an open investigation (numbered entries) rather than a closed ranking.'),
    },
    {
      branchName: 'THE INSERT',
      specimenType: 'branch_the_insert',
      branchPurpose: 'Artifacts, references, culture, found material.',
      coreLineage: 'A Burn Book has things taped/inserted into it that aren\u2019t original writing \u2014 THE INSERT is that found-material behavior.',
      conceptualTranslation: 'A borrowed cultural reference (not original commentary) is presented as a physical inclusion in the book.',
      visualLineage: 'Framed/bordered artifact presentation, dotted archive-tag border.',
      differentiation: 'Distinct from THE RECEIPTS by presenting cultural/reference material rather than financial evidence.',
      primaryBehavior: 'Present a found cultural artifact as if physically inserted into the book.',
      assetRequirements: 'CODE_NATIVE this pass \u2014 could become GENERATED_ASSET for a specific real artifact in a future pass.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE RECEIPTS (financial proof) by being cultural/reference material, not evidence of a claim.'),
    },
    {
      branchName: 'REDACTION',
      specimenType: 'branch_redaction',
      branchPurpose: 'Partial information, tension, withholding, reveal.',
      coreLineage: 'Annotation isn\u2019t only additive \u2014 a real annotator sometimes withholds. REDACTION is the book choosing what NOT to show yet.',
      conceptualTranslation: 'Black-bar redaction over text visualizes withheld information as a deliberate editorial device, building anticipation.',
      visualLineage: 'Black redaction bars over otherwise plain type \u2014 the starkest, most minimal branch.',
      differentiation: 'Only branch defined by absence/withholding rather than presence of information \u2014 unique tension mechanic.',
      primaryBehavior: 'Withhold part of a statement behind a black bar to build anticipation for a reveal.',
      assetRequirements: 'CODE_NATIVE \u2014 typography and solid black bars only.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from every other branch by being defined by subtraction rather than addition.'),
    },
    {
      branchName: 'THE CENTERFOLD',
      specimenType: 'branch_centerfold',
      branchPurpose: 'Large visual/editorial moments.',
      coreLineage: 'Every real magazine has a centerfold \u2014 the book\u2019s biggest visual swing, proving it is a genuine publication and not just annotated notes.',
      conceptualTranslation: 'A single full-bleed photographic moment with minimal type \u2014 the book showing restraint and confidence at its largest scale.',
      visualLineage: 'Full-bleed contemporary editorial photography, lime used only as a thin caption underline.',
      differentiation: 'Only full-bleed, photography-first, minimal-type branch \u2014 the visual "rest" beat in the feed rhythm against dense branches.',
      primaryBehavior: 'Let a single photographic image carry the entire composition.',
      assetRequirements: 'GENERATED_ASSET (KEEP_BACKGROUND, full-bleed) \u2014 fulfilled by eu_centerfold_hero.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from every text-forward branch by being image-first with near-silent typography.'),
    },
    {
      branchName: 'THE BACK PAGE',
      specimenType: 'branch_back_page',
      branchPurpose: 'Questions, games, prompts, participation, confession, community.',
      coreLineage: 'A Burn Book is written collaboratively \u2014 THE BACK PAGE is where the book invites the reader to annotate it back.',
      conceptualTranslation: 'ANNOTATION becomes participatory \u2014 the reader is asked to answer/circle/confess rather than just read.',
      visualLineage: 'Quiz/checklist visual treatment, lime checkbox accents, playful but still editorial type.',
      differentiation: 'Only branch that requests reader input rather than delivering a finished editorial statement \u2014 closes the feed rhythm on an interactive beat.',
      primaryBehavior: 'Pose a question or prompt the audience can answer/engage with directly.',
      assetRequirements: 'CODE_NATIVE \u2014 typography and simple checkbox/circle marks.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from all other branches by being reader-authored rather than book-authored content.'),
    },
  ],
  index_signal: [
    {
      branchName: 'THE PULSE',
      specimenType: 'signal_pulse',
      branchPurpose: 'What\u2019s happening right now \u2014 live, fast shifts, breaking patterns.',
      coreLineage: 'Scanning requires a live read of the present moment before anything can be found \u2014 THE PULSE is that live-read behavior.',
      conceptualTranslation: 'GOVERNING_BEHAVIOR (SCANNING) expressed as a real-time waveform/live readout rather than a settled finding.',
      visualLineage: 'Cobalt waveform line on graphite field, monospace "LIVE" timestamp.',
      differentiation: 'Only branch presented as continuously live rather than a completed finding \u2014 sets urgency at the top of the branch system.',
      primaryBehavior: 'Display a live, moving signal reading.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG waveform.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE READOUT by being live/continuous rather than a single settled statistic.'),
    },
    {
      branchName: 'THE READOUT',
      specimenType: 'signal_readout',
      branchPurpose: 'What do the numbers actually say \u2014 measured, compared, understood.',
      coreLineage: 'After scanning, the instrument reports a number \u2014 THE READOUT is the plain, confident reporting of a finding.',
      conceptualTranslation: 'A single oversized cobalt statistic with a plain-language caption \u2014 SCANNING resolved into a clean result.',
      visualLineage: 'Large cobalt numeral, ice-white caption, graphite field.',
      differentiation: 'Only branch built entirely around one dominant number \u2014 the most reductive, headline-forward signal branch.',
      primaryBehavior: 'State one number with plain-language context.',
      assetRequirements: 'CODE_NATIVE \u2014 typography only.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE FORECAST by reporting a present measured fact, not a projection.'),
    },
    {
      branchName: 'THE PATTERN',
      specimenType: 'signal_pattern',
      branchPurpose: 'Connect the dots \u2014 uncover what others miss.',
      coreLineage: 'SCANNING\u2019s payoff is recognizing a pattern across multiple data points, not just one reading.',
      conceptualTranslation: 'A real photographed object (evidence) plus a cobalt connection-line diagram made over it \u2014 instrumentation literally drawn on top of reality.',
      visualLineage: 'Isolated archival object (REMOVE_BACKGROUND) with cobalt dashed connection line and node overlay.',
      differentiation: 'Only branch combining a real isolated photographic prop with a code-native diagram overlay \u2014 proves the HYBRID_COMPOSITION material language for this direction.',
      primaryBehavior: 'Connect a real object to a finding via a visible diagram line.',
      assetRequirements: 'HYBRID_COMPOSITION \u2014 FAL-generated archival object, background-removed, composited with code-native connection-line diagram (is_card_prop).',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE COORDINATE (positional) by being about relationship between two facts, not a single location.'),
    },
    {
      branchName: 'THE SCAN',
      specimenType: 'signal_scan',
      branchPurpose: 'Let\u2019s examine this closely \u2014 zoom in, zoom out, see it clearly.',
      coreLineage: 'This branch IS the governing behavior made literal \u2014 an actual scanning act captured mid-detection, the Primary Brand Artifact of the direction.',
      conceptualTranslation: 'A real environment (archive) photographed with a cobalt scan-line and readout overlaid mid-process.',
      visualLineage: 'Full-bleed real photography, cobalt scan-line, monospace "SCANNING ARCHIVE\u00b7\u00b7\u00b7" readout.',
      differentiation: 'The only full-bleed, environmental-photography branch \u2014 the visual "establishing shot" of the direction.',
      primaryBehavior: 'Show the scanning instrument actively examining a real environment.',
      assetRequirements: 'GENERATED_ASSET (KEEP_BACKGROUND, full-bleed) \u2014 fulfilled by is_scan_hero (2 reject/regenerate cycles before approval).',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('This is the Primary Brand Artifact itself \u2014 lineage is definitional, not inferred.'),
    },
    {
      branchName: 'THE FORECAST',
      specimenType: 'signal_forecast',
      branchPurpose: 'Where could this be going \u2014 evidence-based projection.',
      coreLineage: 'A good scan doesn\u2019t just report the present \u2014 it extrapolates a likely trajectory forward.',
      conceptualTranslation: 'A cobalt line splits into a solid (measured) and dashed (projected) path \u2014 SCANNING extended into prediction.',
      visualLineage: 'Cobalt solid-to-dashed trend line, "PROJECTED" monospace label.',
      differentiation: 'Only branch depicting the future rather than a present or past reading.',
      primaryBehavior: 'Extend a measured trend into a labeled projection.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG trend line.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE READOUT (present fact) by explicitly labeling projected vs. measured segments.'),
    },
    {
      branchName: 'THE ALERT',
      specimenType: 'signal_alert',
      branchPurpose: 'You should know this now \u2014 high importance, don\u2019t ignore it.',
      coreLineage: 'When a scan finds something urgent, the instrument doesn\u2019t whisper \u2014 THE ALERT is the direction\u2019s urgency register.',
      conceptualTranslation: 'The only branch that inverts the palette (solid cobalt field, not accent-on-graphite) \u2014 a genuine interruption, used sparingly.',
      visualLineage: 'Full cobalt fill, bold white numbered alert headline.',
      differentiation: 'The single highest-contrast, most attention-demanding branch \u2014 must stay rare to keep its meaning.',
      primaryBehavior: 'Interrupt the feed with a numbered, urgent finding.',
      assetRequirements: 'CODE_NATIVE \u2014 typography on a solid cobalt field.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from all other branches by being the only one that inverts cobalt from accent to field \u2014 reserved for genuine urgency.'),
    },
    {
      branchName: 'THE TRANSMISSION',
      specimenType: 'signal_transmission',
      branchPurpose: 'A direct message from NDX \u2014 opinion, observation, intelligence.',
      coreLineage: 'An intelligence system occasionally needs to speak in first person, not just report data \u2014 THE TRANSMISSION is NDX\u2019s own voice.',
      conceptualTranslation: 'A bordered "message" card presents an NDX-authored observation, distinct from an instrument readout.',
      visualLineage: 'Ice-white card, cobalt border, first-person editorial statement.',
      differentiation: 'Only branch structured as direct address from the brand, not a data readout.',
      primaryBehavior: 'Deliver a first-person editorial observation from NDX.',
      assetRequirements: 'CODE_NATIVE \u2014 typography and a simple bordered card.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE READOUT/THE PULSE by voice \u2014 this is NDX speaking, not the instrument reporting.'),
    },
    {
      branchName: 'THE COORDINATE',
      specimenType: 'signal_coordinate',
      branchPurpose: 'Where are you \u2014 benchmarks, checkpoints, self-location.',
      coreLineage: 'An intelligence system that reads the world outward must also let the reader locate themselves within it \u2014 self-diagnostic scanning.',
      conceptualTranslation: 'Concentric cobalt rings with a single located point \u2014 positioning as a visual signal.',
      visualLineage: 'Concentric ring diagram, single cobalt dot marking position.',
      differentiation: 'Only branch about the reader\u2019s own position rather than an external finding.',
      primaryBehavior: 'Mark a single position within a concentric field.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG concentric circles.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE PATTERN (relationship between facts) by being about the reader\u2019s own single location.'),
    },
    {
      branchName: 'THE PROJECTION',
      specimenType: 'signal_projection',
      branchPurpose: 'What happens if you act \u2014 every decision changes the outcome.',
      coreLineage: 'The intelligence layer\u2019s ultimate purpose is actionable insight \u2014 THE PROJECTION shows two possible paths depending on the reader\u2019s choice.',
      conceptualTranslation: 'A dotted "current path" branches from a solid "alternate path" \u2014 SCANNING made prescriptive, not just descriptive.',
      visualLineage: 'Dual cobalt paths (solid vs. dotted), labeled endpoints.',
      differentiation: 'Only branch presenting a fork/decision structure rather than a single reading.',
      primaryBehavior: 'Present two possible outcome paths from a single decision point.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG dual-path diagram.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE FORECAST (single trend) by explicitly forking into two labeled, comparable paths.'),
    },
  ],
  kinetic_field: [
    {
      branchName: 'THE PUSH',
      specimenType: 'motion_push',
      branchPurpose: 'Momentum starts with a decision \u2014 your push. Life pulls back.',
      coreLineage: 'This IS the governing behavior (MOVEMENT) at its origin point \u2014 the Primary Brand Artifact, the first force in the system.',
      conceptualTranslation: 'A real photographed body mid-stride (the moment force is applied) with a headline stating the principle plainly.',
      visualLineage: 'Full-bleed motion photography, rose accent headline band.',
      differentiation: 'The only branch depicting the origin of motion rather than its consequence \u2014 anchors the sequence that follows.',
      primaryBehavior: 'Depict the initiating force of a motion sequence.',
      motionBehavior: 'ENTRY: static readiness \u2192 PEAK: force applied (mid-stride) \u2192 EXIT: hands off to THE PULL/THE COLLISION as consequence beats.',
      assetRequirements: 'GENERATED_ASSET (KEEP_BACKGROUND, full-bleed) \u2014 fulfilled by kf_push_hero.',
      channelApplicability: [...CHANNELS_SOCIAL, 'SHORTS'],
      lineageTest: pass('This is the Primary Brand Artifact itself \u2014 lineage is definitional, not inferred.'),
    },
    {
      branchName: 'THE PULL',
      specimenType: 'motion_pull',
      branchPurpose: 'Some things attract you forward. Some pull you back.',
      coreLineage: 'Every push has a counter-force \u2014 THE PULL is the attraction/resistance half of the same physical system.',
      conceptualTranslation: 'Concentric rose rings converging on a single point visualize gravitational attraction as a decision metaphor.',
      visualLineage: 'Concentric ring falloff, single accent point, dark field.',
      differentiation: 'The only branch depicting an inward/converging force, as opposed to outward pushes or collisions.',
      primaryBehavior: 'Show an object being drawn toward a center point.',
      motionBehavior: 'ENTRY: object at rest at the periphery \u2192 PEAK: acceleration toward center \u2192 EXIT/LOOP: settles at center, ring pulses once.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG concentric rings.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE CURRENT by being a single point-attraction, not a continuous flowing path.'),
    },
    {
      branchName: 'THE RIPPLE',
      specimenType: 'motion_ripple',
      branchPurpose: 'Every move sends ripples. They travel farther than you think.',
      coreLineage: 'MOVEMENT does not stay contained \u2014 THE RIPPLE visualizes consequence spreading outward from a single action.',
      conceptualTranslation: 'Expanding, fading concentric circles from one origin point make "consequences travel" literal.',
      visualLineage: 'Expanding ring set with decreasing opacity, single origin point.',
      differentiation: 'Distinct from THE PULL by expanding outward (consequence) rather than converging inward (attraction).',
      primaryBehavior: 'Show consequence spreading outward from a single point of impact.',
      motionBehavior: 'ENTRY: single point disturbance \u2192 PEAK: rings expand and fade \u2192 EXIT/LOOP: fully dissipated, ready to restart from a new point.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG expanding rings.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE AFTERMATH by showing the spreading process itself, not the settled scatter after it.'),
    },
    {
      branchName: 'THE COLLISION',
      specimenType: 'motion_collision',
      branchPurpose: 'Choices collide. Consequences travel farther than you think.',
      coreLineage: 'Two forces meeting is the most direct visualization of cause-and-effect \u2014 core to the "everything moves something" thesis.',
      conceptualTranslation: 'Two colored circles (a rose choice, a purple consequence) with orange impact lines fanning outward at the meeting point.',
      visualLineage: 'Two-body impact diagram, tri-hue accent use (rose/orange/purple) in one composition.',
      differentiation: 'The only branch using all three momentum hues at once \u2014 the system\u2019s most kinetic single frame.',
      primaryBehavior: 'Show two forces meeting and the resulting impact lines.',
      motionBehavior: 'ENTRY: two bodies approaching \u2192 PEAK: impact, lines fan outward \u2192 EXIT: bodies deflect onto new trajectories.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG two-body impact diagram.',
      channelApplicability: [...CHANNELS_SOCIAL, 'SHORTS'],
      lineageTest: pass('Distinct from THE RIPPLE (single-source consequence) by depicting two independent forces meeting.'),
    },
    {
      branchName: 'THE CURRENT',
      specimenType: 'motion_current',
      branchPurpose: 'Life has currents. You can fight them or learn to move with them.',
      coreLineage: 'Not every force is a discrete event \u2014 some are continuous fields you move through, which the direction must also represent.',
      conceptualTranslation: 'A continuous flowing purple line (with a faint trailing echo) visualizes an ambient, ongoing force rather than a single impact.',
      visualLineage: 'Continuous flowing S-curve path, trailing echo line.',
      differentiation: 'The only branch depicting a sustained, ambient force field rather than a discrete event.',
      primaryBehavior: 'Depict a continuous force the subject moves through, not a single impact.',
      motionBehavior: 'ENTRY: enters the current \u2192 PEAK: continuous flow along the path \u2192 EXIT/LOOP: exits and the path loops back to entry.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG flowing path.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE TRAJECTORY by being ambient/continuous rather than a single directed decision path.'),
    },
    {
      branchName: 'THE TRAJECTORY',
      specimenType: 'motion_trajectory',
      branchPurpose: 'Direction is everything. Small shifts change the entire path.',
      coreLineage: 'A decision doesn\u2019t just create force \u2014 it sets a direction, and the direction is what compounds over time.',
      conceptualTranslation: 'A single bending orange line with small shifts amplified at each segment visualizes sensitivity to early decisions.',
      visualLineage: 'Segmented bending line ending in an accent dot, dark field.',
      differentiation: 'Distinct from THE CURRENT by being a single deliberate directed path (with visible course changes) rather than ambient flow.',
      primaryBehavior: 'Show a single path bending after small directional shifts.',
      motionBehavior: 'ENTRY: path begins straight \u2192 PEAK: visible bend at decision points \u2192 EXIT: path reaches a distant, changed endpoint.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG segmented path.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE PROJECTION-style fork in Index Signal by being a single realized path, not a comparison of two futures.'),
    },
    {
      branchName: 'THE BUILD',
      specimenType: 'motion_build',
      branchPurpose: 'Consistent moves stack. Stack it.',
      coreLineage: 'Momentum compounds \u2014 THE BUILD is the accumulation half of the thesis, showing force stacking rather than force spent.',
      conceptualTranslation: 'Ascending bars of increasing height and opacity visualize compounding small actions into a large one.',
      visualLineage: 'Ascending bar-chart-like stack, rose accent, increasing opacity per step.',
      differentiation: 'The only branch depicting gradual accumulation rather than a single event or force.',
      primaryBehavior: 'Show small repeated actions accumulating into a larger result.',
      motionBehavior: 'ENTRY: first small bar appears \u2192 PEAK: bars stack upward in sequence \u2192 EXIT/LOOP: full stack holds, then resets.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG ascending bars.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE MOMENTUM by depicting the accumulation process itself, not the resulting velocity.'),
    },
    {
      branchName: 'THE BREAK',
      specimenType: 'motion_break',
      branchPurpose: 'Pressure breaks weak things. Strong things break through.',
      coreLineage: 'Not all momentum is smooth \u2014 sometimes force meets resistance and something breaks, which is also "everything moves something."',
      conceptualTranslation: 'A jagged fracture line visualizes the moment resistance gives way under pressure.',
      visualLineage: 'Jagged orange break-line, sharp angular path.',
      differentiation: 'The only branch depicting rupture/failure-then-breakthrough rather than smooth continuous motion.',
      primaryBehavior: 'Show a path fracturing under pressure, then continuing past the break.',
      motionBehavior: 'ENTRY: rising line under pressure \u2192 PEAK: sharp fracture \u2192 EXIT: path continues past the break point.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG jagged path.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE COLLISION by depicting internal structural failure/breakthrough, not two external bodies meeting.'),
    },
    {
      branchName: 'THE AFTERMATH',
      specimenType: 'motion_aftermath',
      branchPurpose: 'Every action leaves a mark. Learn. Adjust. Keep moving.',
      coreLineage: 'After force is spent, evidence remains \u2014 THE AFTERMATH is the settled scatter that proves motion already happened.',
      conceptualTranslation: 'A scattered field of purple particles at rest visualizes the residue of a completed motion event.',
      visualLineage: 'Scattered particle field, varied dot sizes, no directional lines.',
      differentiation: 'The only branch depicting motion that has already stopped \u2014 a deliberate stillness beat late in the sequence.',
      primaryBehavior: 'Depict the settled residue left behind after a motion event.',
      motionBehavior: 'ENTRY: particles mid-scatter (post-event) \u2192 PEAK: settling into final positions \u2192 EXIT/LOOP: fully still, ready for the next push.',
      assetRequirements: 'CODE_NATIVE \u2014 SVG particle scatter.',
      channelApplicability: CHANNELS_SOCIAL,
      lineageTest: pass('Distinct from THE RIPPLE by depicting the after-state (settled) rather than the active spreading process.'),
    },
    {
      branchName: 'THE MOMENTUM',
      specimenType: 'motion_momentum',
      branchPurpose: 'You don\u2019t stay in motion by accident. You stay by decision.',
      coreLineage: 'This is the thesis stated as a closing argument \u2014 momentum as an earned, sustained state, the branch that names the direction itself.',
      conceptualTranslation: 'A real photographed numeral (a physical "3") floats over a dotted orange trajectory line \u2014 momentum made into a countable, physical artifact.',
      visualLineage: 'Isolated photographic numeral prop (REMOVE_BACKGROUND), dotted trajectory path, closing headline.',
      differentiation: 'Only branch combining a real isolated photographic prop with a code-native trajectory line, and the only one explicitly framed as a closing statement.',
      primaryBehavior: 'Present a physical numeral artifact as evidence of sustained momentum.',
      motionBehavior: 'ENTRY: numeral rises along the dotted path \u2192 PEAK: numeral settles at path\u2019s end, in focus \u2192 EXIT/LOOP: headline reveals, loops to THE PUSH.',
      assetRequirements: 'HYBRID_COMPOSITION \u2014 FAL-generated numeral, background-removed, composited with code-native trajectory line (kf_numeral_prop).',
      channelApplicability: [...CHANNELS_SOCIAL, 'SHORTS'],
      lineageTest: pass('Names and closes the thesis directly \u2014 lineage is definitional, functions as the direction\u2019s closing artifact.'),
    },
  ],
};
