/**
 * P0.5C.3 — Character Retention + Controlled Misbehavior + Humor Reinjection
 */

export const CHARACTER_RETENTION_V1 = 'CHARACTER_RETENTION_V1' as const;
export const EXPERIMENT_01_V22_VERSION = 'EXPERIMENT_01_V2_2_CHARACTER_RETENTION' as const;

export const CHARACTER_BEAT_TYPES = [
  'PUNCHLINE',
  'SIDE_COMMENT',
  'REACTION',
  'CALLBACK',
  'PETTY_OBSERVATION',
  'ABSURD_SPECIFICITY',
  'CORRECTION',
  'VISUAL_JOKE',
  'UNDERSTATEMENT',
  'QUESTION_UNDER_THE_QUESTION',
  'CULTURAL_SHORTHAND',
  'SELF_AWARE_COMMENT',
  'MICRO_JUDGMENT',
  'HUMAN_TRACE',
  'SOCIAL_RECOGNITION',
  'MEMORY_FLASH',
  'INTERRUPTION',
] as const;

export const CHARACTER_DENSITY_LEVELS = ['ABSENT', 'LOW', 'SUFFICIENT', 'STRONG', 'OVERDONE'] as const;

export const COMPRESSION_CHARACTER_SAFETY = ['SAFE', 'CHARACTER_REDUCED', 'CHARACTER_CRITICAL_LOSS', 'NOT_EVALUATED'] as const;

export const HUMOR_ELIGIBILITY = ['REQUIRED', 'STRONGLY_HELPFUL', 'OPTIONAL', 'NOT_NEEDED', 'INAPPROPRIATE'] as const;

export const HUMOR_MECHANISMS = [
  'CONTRADICTION_EXPOSURE',
  'OBSERVATIONAL_UNDERSTATEMENT',
  'DEADPAN',
  'CALLBACK',
  'ABSURD_SPECIFICITY',
  'EVIDENCE_AS_PUNCHLINE',
  'CULTURAL_SHORTHAND',
  'RESTRAINED_PETTINESS',
  'TIMED_JUDGMENT',
  'VISUAL_INTERRUPTION',
] as const;

export const PUNCHLINE_DISPOSITION = [
  'PRESERVE_ON_SLIDE_1',
  'MOVE_TO_LATER_SLIDE',
  'MOVE_TO_CAPTION',
  'REMOVE_WITH_JUSTIFICATION',
] as const;

export const CONTROLLED_MISBEHAVIOR_MODES = [
  'OFF_AXIS_NOTE',
  'IMPERFECT_UNDERLINE',
  'BOUNDARY_OVERLAP',
  'INTENTIONAL_CROP',
  'MARGIN_INTRUSION',
  'HAND_PLACED_ARROW',
  'ROUGH_CIRCLE',
  'STRIKE_THROUGH',
  'LAYER_DISPLACEMENT',
  'MISALIGNED_STICKER',
  'OBJECT_INTERRUPTION',
  'TYPE_INTERRUPTION',
  'VISIBLE_CORRECTION',
  'REPLACEMENT_LABEL',
  'TAPED_INSERT',
  'HANDLED_EDGE',
  'SLIGHT_ROTATION',
] as const;

export const MISBEHAVIOR_BUDGET_EVAL = ['NONE_NEEDED', 'SUFFICIENT', 'TOO_CLEAN', 'TOO_CHAOTIC'] as const;

export const HUMAN_TRACE_STRENGTH = ['NONE', 'SUBTLE', 'MODERATE', 'STRONG'] as const;

export const HEADLINE_CHARACTER_RESULTS = [
  'NDX_STRONG',
  'NDX_PRESENT',
  'GENERIC_EDITORIAL',
  'CORPORATE',
  'OVERWRITTEN',
  'TRY_HARD',
] as const;

export const STERILITY_LEVELS = ['ALIVE', 'CONTROLLED', 'COOLING', 'STERILE', 'CORPORATE'] as const;

export const CLARITY_VS_STERILITY = [
  'CLEAR_AND_ALIVE',
  'CLEAR_BUT_COOL',
  'CLEAR_BUT_STERILE',
  'MESSY_BUT_ALIVE',
  'MESSY_AND_CONFUSING',
] as const;

export const LOGO_REMOVAL_CHARACTER = ['STRONG', 'SUFFICIENT', 'WEAK', 'FAIL'] as const;

export const PETTINESS_LEVELS = ['NONE', 'LIGHT', 'PLAYFUL', 'POINTED', 'TOO_FAR'] as const;

export const CHARACTER_BEAT_POSITIONS = [
  'MARGIN',
  'OVER_IMAGE',
  'UNDER_HEADLINE',
  'IN_EVIDENCE',
  'ON_OBJECT',
  'AS_CORRECTION',
  'AS_REPLACEMENT',
  'AS_CAPTION',
  'AS_TAPE_INSERT',
  'AS_VISUAL_PUNCHLINE',
] as const;

export const IMAGE_CARRIES_CHARACTER = ['YES_STRONGLY', 'YES_PARTIALLY', 'NO'] as const;

export const V22_FOUNDER_JUDGMENTS = [
  'YES_THAT_SOUNDS_LIKE_NDX',
  'NOT_FUNNY_ENOUGH',
  'TOO_CLEAN',
  'TOO_POLISHED',
  'TOO_SERIOUS',
  'TOO_MUCH_PERSONALITY',
  'TOO_TRY_HARD',
  'PUNCHLINE_IS_WEAK',
  'WRONG_PUNCHLINE',
  'WRONG_KIND_OF_HUMOR',
  'NEEDS_A_SIDE_COMMENT',
  'NEEDS_MORE_HUMAN_TRACE',
  'TRACE_FEELS_FAKE',
  'MISBEHAVIOR_FEELS_RANDOM',
  'KEEP_IT_CLEANER',
  'CHARACTER_IS_THERE',
  'CHARACTER_GOT_EDITED_OUT',
  'THATS_THE_LINE',
] as const;

export const CHARACTER_FAILURE_STATES = [
  'FAIL_CHARACTER_LOST_DURING_COMPRESSION',
  'FAIL_CHARACTER_DENSITY_ABSENT',
  'FAIL_GENERIC_EDITORIAL_AFTER_COMPRESSION',
  'FAIL_STERILE_ARTIFACT',
  'FAIL_CORPORATE_ARTIFACT',
  'FAIL_TOO_PERFECT',
  'FAIL_NO_MAKER_RESIDUE',
  'FAIL_NO_REACTION',
  'FAIL_HUMOR_REMOVED',
  'FAIL_PUNCHLINE_REMOVED',
  'FAIL_PUNCHLINE_WEAK',
  'FAIL_GENERIC_SNARK',
  'FAIL_FORCED_HUMOR',
  'FAIL_JOKE_STUFFING',
  'FAIL_EVERY_POST_IS_A_JOKE',
  'FAIL_CONTROLLED_MISBEHAVIOR_ABSENT_WHEN_REQUIRED',
  'FAIL_RANDOM_MISBEHAVIOR',
  'FAIL_TOO_MUCH_MISBEHAVIOR',
  'FAIL_HANDWRITING_AS_PERSONALITY',
  'FAIL_CHARACTER_DEPENDS_ON_LIME',
  'FAIL_CHARACTER_DEPENDS_ON_LOGO',
  'FAIL_CHARACTER_DEPENDS_ON_NDX_LABEL',
  'FAIL_CLEAR_BUT_STERILE',
  'FAIL_HUMAN_TRACE_FAKE',
  'FAIL_CHARACTER_MICROCOPY_OVERLOAD',
] as const;

export const FAL_CHARACTER_PROMPT_SECTION_ORDER = [
  'WHAT_HAPPENED',
  'WHAT_NDX_NOTICED',
  'PRIMARY_EDITORIAL_IDEA',
  'VIEWER_FIRST_READ',
  'VISUAL_SUBJECT_MATTER',
  'WHY_VISUAL_SUBJECT_BELONGS',
  'INFORMATION_HIERARCHY',
  'INFORMATION_DELIBERATELY_REMOVED',
  'CHARACTER_FACULTIES_ACTIVE',
  'PRIMARY_CHARACTER_BEAT',
  'HUMOR_ELIGIBILITY',
  'HUMOR_PUNCHLINE_MECHANISM',
  'HUMAN_TRACE',
  'CONTROLLED_MISBEHAVIOR',
  'CHARACTER_DENSITY_TARGET',
  'TYPOGRAPHIC_ROLE_ASSIGNMENTS',
  'UPPERCASE_GOVERNANCE',
  'IMAGE_TYPE_BALANCE',
  'READING_PATH',
  'INFORMATION_DENSITY',
  'CULTURAL_PARTICIPATION',
  'PLAYFULNESS',
  'EMOTIONAL_TEMPERATURE',
  'MATERIAL_CONDITIONS',
  'COMPOSITION',
  'LIME_FUNCTION',
  'STERILITY_GUARD',
  'NEGATIVE_CONSTRAINTS',
] as const;

export const CHARACTER_RETENTION_SYSTEM_IMPLEMENTED = true as const;
export const INFORMATION_VS_CHARACTER_DENSITY_SEPARATED = true as const;
export const CHARACTER_BEAT_IMPLEMENTED = true as const;
export const COMPRESSION_CHARACTER_SAFETY_IMPLEMENTED = true as const;
export const HUMOR_REINJECTION_IMPLEMENTED = true as const;
export const PUNCHLINE_PRESERVATION_IMPLEMENTED = true as const;
export const CONTROLLED_MISBEHAVIOR_IMPLEMENTED = true as const;
export const HUMAN_TRACE_STRENGTH_IMPLEMENTED = true as const;
export const STERILITY_EVALUATION_IMPLEMENTED = true as const;
export const CLEAR_VS_STERILE_DISTINCTION_IMPLEMENTED = true as const;
export const LOGO_REMOVAL_CHARACTER_RECOGNITION_IMPLEMENTED = true as const;
export const FEED_CHARACTER_RHYTHM_IMPLEMENTED = true as const;
export const FEED_HUMOR_RHYTHM_IMPLEMENTED = true as const;
export const P0_5C_1_INFORMATION_HIERARCHY_PRESERVED = true as const;
export const P0_5C_1_TYPOGRAPHY_GOVERNANCE_PRESERVED = true as const;
export const P0_5C_2_CULTURAL_VISUAL_GOVERNANCE_PRESERVED = true as const;
export const EXPERIMENT_01_V2_1_PRESERVED = true as const;
export const EXPERIMENT_01_V2_2_CHARACTER_RETENTION_PIPELINE_READY = true as const;
export const P0_5E_ROUND_01_CHARACTER_GATE_INTEGRATED = true as const;
export const CONTENT_OPERATIONS_CHARACTER_RETENTION_INTEGRATED = true as const;
