/**
 * P0.VR.1D.4 — Canonical visual reconstruction region IDs (shared reference ↔ DOM).
 */

export const NDX_VR_REGION = {
  header: 'ndx.header',
  railNav: 'ndx.rail.nav',
  overviewHero: 'ndx.overview.hero',
  overviewScreen: 'ndx.overview.screen',
  overviewHeaderShell: 'ndx.overview.header-shell',
  overviewContentShell: 'ndx.overview.content-shell',
  overviewBottomNavShell: 'ndx.overview.bottom-nav-shell',
  overviewMetrics: 'ndx.overview.metrics',
  overviewKpis: 'ndx.overview.kpis',
  overviewKpiAudience: 'ndx.overview.kpi.audience',
  productionRow: 'ndx.production.row',
  overviewProduction: 'ndx.overview.production',
  productionCardSubscription: 'ndx.overview.production.card.subscription',
  productionCardLayoff: 'ndx.overview.production.card.layoff',
  productionCardLateFees: 'ndx.overview.production.card.late-fees',
  radarList: 'ndx.radar.list',
  overviewRadar: 'ndx.overview.radar',
  bottomNav: 'ndx.bottom-nav',
  projectMenu: 'ndx.project.menu',
  notificationPanel: 'ndx.notification.panel',
  notificationHeader: 'ndx.notification.header',
  notificationTabs: 'ndx.notification.tabs',
  notificationList: 'ndx.notification.list',
  notificationRow: 'ndx.notification.row',
  notificationFooter: 'ndx.notification.footer',
  campaignWeekHeader: 'ndx.campaign.week-header',
  campaignTitle: 'ndx.campaign.title',
  campaignDaySelector: 'ndx.campaign.day-selector',
  campaignPages: 'ndx.campaign.pages',
  campaignPagesCard1: 'ndx.campaign.pages.card.1',
  campaignPagesCard2: 'ndx.campaign.pages.card.2',
  campaignPagesCard3: 'ndx.campaign.pages.card.3',
  campaignMargins: 'ndx.campaign.margins',
  campaignMarginsCard1: 'ndx.campaign.margins.card.1',
  campaignMarginsCard2: 'ndx.campaign.margins.card.2',
  campaignMarginsCard3: 'ndx.campaign.margins.card.3',
  campaignMotion: 'ndx.campaign.motion',
  campaignHeader: 'ndx.campaign.header',
  campaignScreen: 'ndx.campaign.screen',
  campaignHeaderShell: 'ndx.campaign.header-shell',
  campaignContentShell: 'ndx.campaign.content-shell',
  campaignBottomNavShell: 'ndx.campaign.bottom-nav-shell',
  campaignBottomNav: 'ndx.campaign.bottom-nav',
  campaignPagesLane: 'ndx.campaign.pages-lane',
  campaignMarginsLane: 'ndx.campaign.margins-lane',
  campaignMotionLane: 'ndx.campaign.motion-lane',
  experimentGrid: 'ndx.experiment.grid',
  labHeader: 'ndx.lab.header',
  labScreen: 'ndx.lab.screen',
  labHeaderShell: 'ndx.lab.header-shell',
  labContentShell: 'ndx.lab.content-shell',
  labBottomNavShell: 'ndx.lab.bottom-nav-shell',
  labBreadcrumb: 'ndx.lab.breadcrumb',
  labTitle: 'ndx.lab.title',
  labSubject: 'ndx.lab.subject',
  labMetrics: 'ndx.lab.metrics',
  labGrid: 'ndx.lab.grid',
  labCard1: 'ndx.lab.card.1',
  labCard2: 'ndx.lab.card.2',
  labCard3: 'ndx.lab.card.3',
  labCard4: 'ndx.lab.card.4',
  labCard5: 'ndx.lab.card.5',
  labCard6: 'ndx.lab.card.6',
  labCard7: 'ndx.lab.card.7',
  labCard8: 'ndx.lab.card.8',
  labCard9: 'ndx.lab.card.9',
  labDirection: 'ndx.lab.direction',
  labInspect: 'ndx.lab.inspect',
  labBottomNav: 'ndx.lab.bottom-nav',
  contentOpsDesk: 'ndx.content-ops.desk',
  contentOpsScreen: 'ndx.content-ops.screen',
  contentOpsHeaderShell: 'ndx.content-ops.header-shell',
  contentOpsContentShell: 'ndx.content-ops.content-shell',
  contentOpsOperatingMode: 'ndx.content-ops.operating-mode',
  contentOpsOpportunities: 'ndx.content-ops.opportunities',
  contentOpsCurrentWork: 'ndx.content-ops.current-work',
  contentOpsNeedsEye: 'ndx.content-ops.needs-eye',
  contentOpsBottomNavShell: 'ndx.content-ops.bottom-nav-shell',
  culturalIntelligenceRadar: 'ndx.cultural-intelligence.radar',
  intelligenceScreen: 'ndx.intelligence.screen',
  intelligenceHeaderShell: 'ndx.intelligence.header-shell',
  intelligenceContentShell: 'ndx.intelligence.content-shell',
  intelligenceSignals: 'ndx.intelligence.signals',
  intelligenceRadar: 'ndx.intelligence.radar',
  intelligenceBottomNavShell: 'ndx.intelligence.bottom-nav-shell',
  characterProfile: 'ndx.character.profile',
  characterScreen: 'ndx.character.screen',
  characterHeader: 'ndx.character.header',
  characterHeaderShell: 'ndx.character.header-shell',
  characterContentShell: 'ndx.character.content-shell',
  characterTabs: 'ndx.character.tabs',
  characterHero: 'ndx.character.hero',
  characterPortrait: 'ndx.character.portrait',
  characterLanguageNote: 'ndx.character.language-note',
  characterIdentity: 'ndx.character.identity',
  characterStickyNote: 'ndx.character.sticky-note',
  characterQuote: 'ndx.character.quote',
  characterNotes: 'ndx.character.notes',
  characterPerformance: 'ndx.character.performance',
  characterPerformanceCard1: 'ndx.character.performance.card.1',
  characterPerformanceCard2: 'ndx.character.performance.card.2',
  characterPerformanceCard3: 'ndx.character.performance.card.3',
  characterPerformanceCard4: 'ndx.character.performance.card.4',
  characterBottomNavShell: 'ndx.character.bottom-nav-shell',
  performanceLearning: 'ndx.performance.learning',
  desktopComposite: 'ndx.overview.desktop-composite',
} as const;

/** P0.VR.1D.7 — Scoped DOM roots for embedded desktop workspace panels. */
export const NDX_VR_SCOPE = {
  desktopOverview: 'ndx.desktop.overview',
  desktopCampaignBoardPanel: 'ndx.desktop.campaign-board-panel',
  desktopExperimentPanel: 'ndx.desktop.experiment-panel',
  desktopContentOpsPanel: 'ndx.desktop.content-ops-panel',
  desktopCulturalIntelligencePanel: 'ndx.desktop.cultural-intelligence-panel',
  desktopCharacterLabPanel: 'ndx.desktop.character-lab-panel',
} as const;

export type NdxVisualScopeId = (typeof NDX_VR_SCOPE)[keyof typeof NDX_VR_SCOPE];

export function vrScopeAttr(id: NdxVisualScopeId | string): { 'data-vr-scope': string } {
  return { 'data-vr-scope': id };
}

export type NdxVisualRegionId = (typeof NDX_VR_REGION)[keyof typeof NDX_VR_REGION];

/** Legacy hyphen IDs from P0.VR.1D.3 — mapped during transition. */
export const NDX_VR_LEGACY_REGION_ALIASES: Record<string, NdxVisualRegionId> = {
  'ndx-header': NDX_VR_REGION.header,
  'ndx-overview-heading': NDX_VR_REGION.overviewHero,
  'ndx-metrics': NDX_VR_REGION.overviewMetrics,
  'ndx-production': NDX_VR_REGION.productionRow,
  'ndx-radar': NDX_VR_REGION.radarList,
  'ndx-bottom-nav': NDX_VR_REGION.bottomNav,
  'ndx-project-menu': NDX_VR_REGION.projectMenu,
  DESKTOP_COMPOSITE_OVERVIEW: NDX_VR_REGION.desktopComposite,
};

export function vrRegionAttr(id: NdxVisualRegionId | string): { 'data-vr-region': string } {
  return { 'data-vr-region': id };
}
