import type { HeroOutlierSnapshot } from './types.js';

/** Playwright DOM capture (375px) before 4R4R1 CSS patches — founder QA: 8 outliers / 6 pass. */
export const HERO_OUTLIER_SNAPSHOT_4R4R1_BASELINE: HeroOutlierSnapshot = {
  twinId: 'dev-hero-measure-4r4r1',
  captureTimestamp: '2026-09-13T00:00:00.000Z',
  measurementSource: 'PLAYWRIGHT_DOM',
  measuredCount: 14,
  renderedCount: 14,
  passCount: 6,
  outlierCount: 8,
  outliers: [
    {
      objectId: 'H01',
      deltaX: 0,
      deltaY: -2,
      deltaWidth: 48,
      deltaHeight: -1,
      leftError: 0,
      rightError: 48,
      topError: -2,
      bottomError: -3,
      severity: 'RED',
      visibleMismatch: 'entry label stack: size mismatch, vertical drift',
    },
    {
      objectId: 'H02',
      deltaX: 0,
      deltaY: -1,
      deltaWidth: -12,
      deltaHeight: -2.5625,
      leftError: 0,
      rightError: -12,
      topError: -1,
      bottomError: -3.5625,
      severity: 'RED',
      visibleMismatch: 'headline block: size mismatch, vertical drift',
    },
    {
      objectId: 'H03',
      deltaX: 0,
      deltaY: 4.4375,
      deltaWidth: 0,
      deltaHeight: 0,
      leftError: 0,
      rightError: 0,
      topError: 4.4375,
      bottomError: 4.4375,
      severity: 'RED',
      visibleMismatch: 'lime accent line: vertical drift',
    },
    {
      objectId: 'H04',
      deltaX: 0,
      deltaY: 2.4375,
      deltaWidth: -20,
      deltaHeight: 2.0625,
      leftError: 0,
      rightError: -20,
      topError: 2.4375,
      bottomError: 4.5,
      severity: 'RED',
      visibleMismatch: 'supporting copy: size mismatch, vertical drift',
    },
    {
      objectId: 'H05',
      deltaX: 0,
      deltaY: 2.5,
      deltaWidth: -28.09375,
      deltaHeight: -4,
      leftError: 0,
      rightError: -28.09375,
      topError: 2.5,
      bottomError: -1.5,
      severity: 'RED',
      visibleMismatch: 'CTA placement: size mismatch, vertical drift',
    },
    {
      objectId: 'H08',
      deltaX: -2,
      deltaY: 1.109375,
      deltaWidth: -31.375,
      deltaHeight: -4.109375,
      leftError: -2,
      rightError: -33.375,
      topError: 1.109375,
      bottomError: -3,
      severity: 'RED',
      visibleMismatch: 'NDX overlay scale/anchor: size mismatch, horizontal drift, vertical drift',
    },
    {
      objectId: 'H11',
      deltaX: -25,
      deltaY: 4,
      deltaWidth: 48,
      deltaHeight: -2,
      leftError: -25,
      rightError: 23,
      topError: 4,
      bottomError: 2,
      severity: 'RED',
      visibleMismatch: '00 label cell: size mismatch, horizontal drift, vertical drift',
    },
    {
      objectId: 'H12',
      deltaX: 0,
      deltaY: 5,
      deltaWidth: 0,
      deltaHeight: 0,
      leftError: 0,
      rightError: 0,
      topError: 5,
      bottomError: 5,
      severity: 'RED',
      visibleMismatch: 'lower-right photo slot: vertical drift',
    },
  ],
};
