export const P0_VR_TWIN_V41_LINEAGE = 'P0.VR.TWINV4.1' as const;
export const TWIN_V41_EXTRACTION_VERSION = 'v41-pixel-1' as const;

export const TWIN_V41_STORAGE_PREFIX = 'site00:twin-v41:' as const;

export const TWIN_V41_FORENSIC_PIXEL_AUTHORITY_UNAVAILABLE =
  'TWIN_V41_FORENSIC_PIXEL_AUTHORITY_UNAVAILABLE' as const;
export const PLACEHOLDER_SCENE_GRAPH_GENERATION_ATTEMPTED =
  'PLACEHOLDER_SCENE_GRAPH_GENERATION_ATTEMPTED' as const;
export const PIXEL_EXTRACTION_REVIEW_REQUIRED = 'PIXEL_EXTRACTION_REVIEW_REQUIRED' as const;

export const V40_SCENE_GRAPH_REJECTION_REASON = 'HARDCODED_SCENE_GRAPH_PLACEHOLDER_RENDER' as const;

export const TWIN_V41_REQUIRED_MAJOR_REGIONS = [
  'DOCUMENT_CANVAS',
  'TITLE_HEADER',
  'LEFT_MAIN_BLUEPRINT_PANEL',
  'RIGHT_OBJECT_INVENTORY',
  'LOWER_COLOR_PALETTE',
  'LOWER_TYPOGRAPHY_KEY',
  'LOWER_DIVIDER_SPECS',
  'LOWER_NOTES_CONTEXT',
] as const;

export type TwinV41RequiredMajorRegionId = (typeof TWIN_V41_REQUIRED_MAJOR_REGIONS)[number];
