import { HERO_PAGE_TOP_Y } from './constants.js';
import type { HeroObjectContract } from './types.js';

function localY(pageY: number): number {
  return pageY - HERO_PAGE_TOP_Y;
}

function sel(heroId: string, blueprintId?: string): string {
  return `[data-hero-object="${heroId}"]${blueprintId ? `,[data-forensic-object-id="${blueprintId}"]` : ''}`;
}

export function buildHeroObjectContracts(): HeroObjectContract[] {
  const file = 'src/site00/components/reconstruction/ForensicBlueprintNdxOverviewTwin.tsx';
  const base = (c: Omit<HeroObjectContract, 'sourceFile' | 'parent' | 'status'>): HeroObjectContract => ({
    ...c,
    parent: 'hero-root',
    sourceFile: file,
    status: 'BOUND',
  });

  return [
    base({
      objectId: 'H01',
      blueprintObjectId: '17',
      role: 'entry-label',
      authorityBounds: { x: 24, y: localY(240), width: 80, height: 14 },
      domSelector: sel('H01', '17'),
      renderStrategy: 'DOM_TEXT',
      assetBinding: null,
      typographySpec: 'label-s',
      surfaceSpec: null,
      zIndex: 30,
      overflowPolicy: 'VISIBLE',
    }),
    base({
      objectId: 'H02',
      blueprintObjectId: '18',
      role: 'headline',
      authorityBounds: { x: 24, y: localY(256), width: 152, height: 80 },
      domSelector: sel('H02', '18'),
      renderStrategy: 'DOM_TEXT',
      assetBinding: null,
      typographySpec: 'display-l',
      surfaceSpec: null,
      zIndex: 30,
      overflowPolicy: 'CLIP',
    }),
    base({
      objectId: 'H03',
      blueprintObjectId: '20',
      role: 'accent-line',
      authorityBounds: { x: 24, y: localY(338), width: 120, height: 2 },
      domSelector: sel('H03', '20'),
      renderStrategy: 'CSS_SHAPE',
      assetBinding: null,
      typographySpec: null,
      surfaceSpec: 'hero-accent',
      zIndex: 30,
      overflowPolicy: 'VISIBLE',
    }),
    base({
      objectId: 'H04',
      blueprintObjectId: '19',
      role: 'supporting-copy',
      authorityBounds: { x: 24, y: localY(348), width: 160, height: 40 },
      domSelector: sel('H04', '19'),
      renderStrategy: 'DOM_TEXT',
      assetBinding: null,
      typographySpec: 'body-s',
      surfaceSpec: null,
      zIndex: 30,
      overflowPolicy: 'CLIP',
    }),
    base({
      objectId: 'H05',
      blueprintObjectId: '21',
      role: 'cta',
      authorityBounds: { x: 24, y: localY(396), width: 132, height: 32 },
      domSelector: sel('H05', '21'),
      renderStrategy: 'DOM_BUTTON',
      assetBinding: null,
      typographySpec: 'label-s',
      surfaceSpec: 'button-outline',
      zIndex: 60,
      overflowPolicy: 'VISIBLE',
    }),
    base({
      objectId: 'H06',
      blueprintObjectId: '22',
      role: 'center-architecture-image',
      authorityBounds: { x: 140, y: localY(228), width: 160, height: 220 },
      domSelector: sel('H06', '22'),
      renderStrategy: 'IMG_CROP',
      assetBinding: 'authority-crop-center',
      typographySpec: null,
      surfaceSpec: 'grayscale-cover',
      zIndex: 10,
      overflowPolicy: 'CLIP',
    }),
    base({
      objectId: 'H07',
      blueprintObjectId: '—',
      role: 'center-stack-graphic',
      authorityBounds: { x: 200, y: localY(280), width: 48, height: 72 },
      domSelector: '[data-hero-object="H07"]',
      renderStrategy: 'IMG_CROP',
      assetBinding: 'baked-in-H06-only',
      typographySpec: null,
      surfaceSpec: 'no-dom-duplicate',
      zIndex: 10,
      overflowPolicy: 'MASK',
    }),
    base({
      objectId: 'H08',
      blueprintObjectId: '25',
      role: 'large-ndx-overlay',
      authorityBounds: { x: 200, y: localY(360), width: 160, height: 48 },
      domSelector: sel('H08', '25'),
      renderStrategy: 'OVERLAY_GRAPHIC',
      assetBinding: null,
      typographySpec: 'display-xl',
      surfaceSpec: 'lime-fill',
      zIndex: 50,
      overflowPolicy: 'CLIP',
    }),
    base({
      objectId: 'H09',
      blueprintObjectId: '—',
      role: 'right-utility-column',
      authorityBounds: { x: 287, y: localY(228), width: 88, height: 220 },
      domSelector: '[data-hero-object="H09"]',
      renderStrategy: 'GRID',
      assetBinding: null,
      typographySpec: null,
      surfaceSpec: 'utility-column',
      zIndex: 20,
      overflowPolicy: 'CLIP',
    }),
    base({
      objectId: 'H10',
      blueprintObjectId: '23',
      role: 'crosshair',
      authorityBounds: { x: 318, y: localY(248), width: 20, height: 20 },
      domSelector: sel('H10', '23'),
      renderStrategy: 'CSS_SHAPE',
      assetBinding: 'dom:crosshair',
      typographySpec: null,
      surfaceSpec: 'reticle',
      zIndex: 40,
      overflowPolicy: 'VISIBLE',
    }),
    base({
      objectId: 'H11',
      blueprintObjectId: '24',
      role: 'zero-counter',
      authorityBounds: { x: 328, y: localY(268), width: 28, height: 16 },
      domSelector: sel('H11', '24'),
      renderStrategy: 'DOM_TEXT',
      assetBinding: null,
      typographySpec: 'label-s',
      surfaceSpec: null,
      zIndex: 40,
      overflowPolicy: 'VISIBLE',
    }),
    base({
      objectId: 'H12',
      blueprintObjectId: '—',
      role: 'lower-right-photo',
      authorityBounds: { x: 300, y: localY(380), width: 64, height: 56 },
      domSelector: '[data-hero-object="H12"]',
      renderStrategy: 'IMG_CROP',
      assetBinding: 'authority-crop-lower-right',
      typographySpec: null,
      surfaceSpec: 'grayscale-cover',
      zIndex: 10,
      overflowPolicy: 'CLIP',
    }),
    base({
      objectId: 'H13',
      blueprintObjectId: '—',
      role: 'internal-grid-dividers',
      authorityBounds: { x: 0, y: 0, width: 375, height: 220 },
      domSelector: '[data-hero-object="H13"]',
      renderStrategy: 'GRID',
      assetBinding: null,
      typographySpec: null,
      surfaceSpec: '1px-rules',
      zIndex: 20,
      overflowPolicy: 'VISIBLE',
    }),
    base({
      objectId: 'H14',
      blueprintObjectId: '22-band',
      role: 'hero-outer-bounds',
      authorityBounds: { x: 0, y: 0, width: 375, height: 220 },
      domSelector: '[data-hero-object="H14"]',
      renderStrategy: 'GRID',
      assetBinding: null,
      typographySpec: null,
      surfaceSpec: 'hero-root',
      zIndex: 0,
      overflowPolicy: 'HIDDEN',
    }),
  ];
}
