import type { FigmaStyleInterfaceTranslationPackage } from '../../shared/site00-sol-design-bench/contracts';

export function strictSolPackageFixture(
  sha256: string,
): Omit<FigmaStyleInterfaceTranslationPackage, 'packageType'> {
  return {
    VISUAL_INTERFACE_PREVIEW: {
      artboardWidth: 2,
      artboardHeight: 2,
      background: '#ffffff',
      componentIds: ['page'],
      renderingNotes: ['Minimal strict-schema fixture.'],
      visualPreviewRef: 'sol-preview://fixture',
    },
    PAGE_FRAME_SPEC: {
      frame: { width: 2, height: 2 },
      contentBounds: { x: 0, y: 0, width: 2, height: 2 },
      background: '#ffffff',
      outerMargins: { x: 0, y: 0, width: 0, height: 0 },
      grid: 'none',
      columns: 1,
      gutters: 0,
      verticalRhythm: 1,
    },
    SECTION_TREE: [{
      id: 'page',
      parentId: null,
      label: 'Page',
      level: 'PAGE',
      order: 0,
      bounds: { x: 0, y: 0, width: 2, height: 2 },
    }],
    COMPONENT_TREE: [{
      componentId: 'page',
      parentId: null,
      label: 'Page',
      semanticRole: 'page',
      visualRole: 'canvas',
      siblingOrder: 0,
      x: 0,
      y: 0,
      width: 2,
      height: 2,
      normalizedBounds: { x: 0, y: 0, width: 1, height: 1 },
      layoutMode: 'absolute',
      alignment: 'start',
      padding: 0,
      gap: 0,
      visualPriority: 'DOMINANT',
      style: {
        background: '#ffffff',
        color: null,
        border: null,
        borderRadius: null,
        fontSize: null,
        fontWeight: null,
        lineHeight: null,
        textAlign: null,
      },
      text: null,
      assetId: null,
      state: null,
    }],
    LAYOUT_GEOMETRY_SPEC: {
      relations: [],
      baselines: [],
      anchors: ['top-left'],
      stacking: [],
      overlaps: [],
      repeatedDimensions: [],
    },
    TYPOGRAPHY_SYSTEM: [],
    COLOR_SYSTEM: [{ role: 'page', value: '#ffffff', usage: 'Page background' }],
    SPACING_SYSTEM: {
      pageMargin: 0,
      sectionSpacing: [],
      panelPadding: [],
      componentGaps: [],
      textRhythm: [],
      rowSpacing: [],
      controlSpacing: [],
    },
    BORDER_RADIUS_SURFACE_SYSTEM: {
      borders: [],
      radii: [],
      fills: [{ role: 'page', value: '#ffffff', usage: 'Page background' }],
      shadows: [],
      separators: [],
      stateTreatments: [],
      nestedSurfaceHierarchy: [],
    },
    ASSET_PLACEMENT_MAP: [],
    CONTROL_STATE_SYSTEM: [],
    VISUAL_HIERARCHY_MAP: [{
      componentId: 'page',
      semanticRole: 'page',
      visualWeight: 'DOMINANT',
      dominanceRank: 1,
      contrastWeight: 0,
      areaWeight: 1,
      typographicWeight: 0,
      positionalProminence: 1,
      accentContribution: 0,
    }],
    IMPLEMENTATION_HANDOFF: {
      handoffType: 'SolComposerImplementationHandoff',
      executionIntent: 'REFERENCE_TRANSLATION',
      sourceAuthoritySha256: sha256,
      inventionBudget: 'NONE',
      targetFrame: { width: 2, height: 2 },
      orderedBuildInstructions: ['Build the measured frame.'],
      componentContracts: ['page: absolute 2x2 canvas'],
      tokenContracts: ['page background: #ffffff'],
      assetBindings: [],
      acceptanceChecks: ['Match the 2x2 frame.'],
      composerInvoked: false,
    },
    DO_NOT_CHANGE_RULES: ['Preserve frame ratio.'],
  };
}
