import type { PageInteractionContract } from '../site00-studio-world-production/visualReconstruction/pageCompletionIntelligence/types.js';

export const EVOLVE_SERVICE_PAGE_ID = 'evolve-service-digital-evolution';

export const EVOLVE_SERVICE_PAGE_COMPLETION_CONTRACTS: PageInteractionContract[] = [
  {
    interactionId: 'ix-evolve-hub-nav-overview',
    pageId: EVOLVE_SERVICE_PAGE_ID,
    regionId: 'nav',
    label: 'OVERVIEW',
    affordanceType: 'TAB',
    intent: 'SCROLL_TO_SECTION',
    targetType: 'INLINE_EXPANSION',
    route: '/evolve#overview',
    status: 'IMPLEMENTED',
    confidence: 'HIGH',
  },
  {
    interactionId: 'ix-evolve-path-enter-refine',
    pageId: EVOLVE_SERVICE_PAGE_ID,
    regionId: 'paths',
    label: 'ENTER PATH',
    affordanceType: 'BUTTON',
    intent: 'OPEN_PATH_ASSESSMENT',
    targetType: 'CHILD_ROUTE',
    route: '/evolve/refine/property',
    childSurfaceRequirement: 'evolve-path-detail-refine',
    status: 'IMPLEMENTED',
    confidence: 'HIGH',
  },
  {
    interactionId: 'ix-evolve-path-enter-install',
    pageId: EVOLVE_SERVICE_PAGE_ID,
    regionId: 'paths',
    label: 'ENTER PATH',
    affordanceType: 'BUTTON',
    intent: 'OPEN_PATH_ASSESSMENT',
    targetType: 'CHILD_ROUTE',
    route: '/evolve/install/property',
    childSurfaceRequirement: 'evolve-path-detail-install',
    status: 'IMPLEMENTED',
    confidence: 'HIGH',
  },
  {
    interactionId: 'ix-evolve-path-enter-transform',
    pageId: EVOLVE_SERVICE_PAGE_ID,
    regionId: 'paths',
    label: 'ENTER PATH',
    affordanceType: 'BUTTON',
    intent: 'OPEN_PATH_ASSESSMENT',
    targetType: 'CHILD_ROUTE',
    route: '/evolve/transform/property',
    childSurfaceRequirement: 'evolve-path-detail-transform',
    status: 'IMPLEMENTED',
    confidence: 'HIGH',
  },
  {
    interactionId: 'ix-evolve-faq-rebuild',
    pageId: EVOLVE_SERVICE_PAGE_ID,
    regionId: 'faq',
    label: 'DO I NEED TO REBUILD FROM ZERO?',
    affordanceType: 'EXPANDER',
    intent: 'TOGGLE_FAQ',
    targetType: 'INLINE_EXPANSION',
    route: '/evolve#faq',
    status: 'IMPLEMENTED',
    confidence: 'HIGH',
  },
  {
    interactionId: 'ix-evolve-start-cta',
    pageId: EVOLVE_SERVICE_PAGE_ID,
    regionId: 'start',
    label: 'START EVOLVE',
    affordanceType: 'BUTTON',
    intent: 'START_EVOLVE_HANDOFF',
    targetType: 'ROUTE',
    route: '/evolve/state',
    childSurfaceRequirement: 'evolve-onboarding',
    status: 'IMPLEMENTED',
    confidence: 'HIGH',
  },
  {
    interactionId: 'ix-evolve-case-studies-notify',
    pageId: EVOLVE_SERVICE_PAGE_ID,
    regionId: 'cases',
    label: 'NOTIFY ME',
    affordanceType: 'LINK',
    intent: 'CAPTURE_COMING_SOON_INTEREST',
    targetType: 'SUBMIT_MUTATION',
    route: '/evolve#cases',
    status: 'IMPLEMENTED',
    confidence: 'HIGH',
  },
];
