/**
 * P0.5D.1 — Generic Live Cultural Intelligence + Trend Forecasting (brand-agnostic).
 */

export const LIVE_CULTURAL_INTELLIGENCE_V1 = 'LIVE_CULTURAL_INTELLIGENCE_V1' as const;

export const SIGNAL_ORIGINS = [
  'KNOWN_UPCOMING',
  'BREAKING',
  'EMERGING',
  'ACCELERATING',
  'PEAKING',
  'STABLE',
  'DECLINING',
  'RECURRING',
  'RESURFACED',
  'EVERGREEN_REACTIVATED',
] as const;

export const SIGNAL_SOURCE_TYPES = [
  'NEWS',
  'ENTERTAINMENT',
  'CELEBRITY_PUBLIC_CULTURE',
  'AWARD_SHOWS',
  'FILM',
  'TELEVISION',
  'MUSIC',
  'FASHION',
  'BEAUTY',
  'SPORTS',
  'TECHNOLOGY',
  'BUSINESS',
  'WORKPLACE',
  'ECONOMICS',
  'CONSUMER_BEHAVIOR',
  'INTERNET_CULTURE',
  'MEMES',
  'SOCIAL_PLATFORM_BEHAVIOR',
  'CREATOR_CULTURE',
  'ADVERTISING',
  'BRAND_CAMPAIGNS',
  'RETAIL',
  'DESIGN',
  'ART',
  'FOOD',
  'LIFESTYLE',
  'RELATIONSHIPS',
  'EDUCATION',
  'SCIENCE',
  'RESEARCH',
  'DATA_RELEASES',
  'POLICY_CIVIC',
  'HISTORICAL_ANNIVERSARY',
  'CULTURAL_ANNIVERSARY',
  'PRODUCT_LAUNCH',
  'PLATFORM_LAUNCH',
  'PUBLIC_REPORT',
  'SEARCH_BEHAVIOR',
  'COMMUNITY_DISCUSSION',
  'ARCHIVAL_RESURGENCE',
  'MANUAL_FOUNDER',
  'OTHER',
] as const;

export const CONNECTOR_STATUSES = [
  'CONNECTED',
  'MANUAL',
  'AVAILABLE_NOT_CONFIGURED',
  'NOT_AVAILABLE',
  'BLOCKED',
  'FAILED',
] as const;

export const TREND_LIFECYCLE_STATES = [
  'DISCOVERED',
  'WATCHING',
  'EMERGING',
  'ACCELERATING',
  'BREAKING',
  'PEAKING',
  'SATURATED',
  'DECLINING',
  'EXHAUSTED',
  'RESURFACING',
  'EVERGREEN_REACTIVATED',
] as const;

export const FORECAST_CONFIDENCE_LEVELS = [
  'OBSERVED_FACT',
  'SCHEDULED_CERTAINTY',
  'STRONG_FORECAST',
  'MODERATE_FORECAST',
  'WEAK_FORECAST',
  'SPECULATIVE',
] as const;

export const EXPECTED_ATTENTION_LEVELS = ['LOW', 'MODERATE', 'HIGH', 'MAJOR'] as const;

export const TEMPORAL_CLASSES = [
  'IMMEDIATE',
  'SAME_DAY',
  '24_HOUR',
  '48_72_HOUR',
  'THIS_WEEK',
  'MULTI_WEEK',
  'SEASONAL',
  'EVERGREEN',
  'EVERGREEN_REACTIVATED',
] as const;

export const WHY_NOW_RESULTS = [
  'URGENT_NOW',
  'TIMELY_NOW',
  'PREPARE_FOR_KNOWN_MOMENT',
  'WATCH_AND_WAIT',
  'EVERGREEN_BUT_REACTIVATED',
  'NOT_TIME_SENSITIVE',
  'WINDOW_PASSED',
] as const;

export const FRESHNESS_STATES = ['LIVE', 'CURRENT', 'RECENT', 'AGING', 'STALE', 'HISTORICAL'] as const;

export const CURRENT_CLAIM_CLASSES = [
  'VERIFIED',
  'SUPPORTED',
  'SINGLE_SOURCE',
  'DEVELOPING',
  'DISPUTED',
  'UNVERIFIED',
  'SPECULATIVE',
] as const;

export const BRAND_RELEVANCE_DECISIONS = [
  'STRONG_OPPORTUNITY',
  'PROMISING_INVESTIGATE',
  'WATCH',
  'EVERGREEN_CONNECTION',
  'CALLBACK_OPPORTUNITY',
  'RAPID_RESPONSE',
  'NOT_FOR_THIS_BRAND',
  'NOTHING_NEW_TO_ADD',
  'TOO_SATURATED',
  'TOO_SPECULATIVE',
  'FORCED_PARTICIPATION',
] as const;

export const EDITORIAL_WHITESPACE_OUTCOMES = [
  'OPEN',
  'NARROW',
  'SATURATED_BUT_ANGLE_EXISTS',
  'SATURATED_NO_ADDITIONAL_VALUE',
  'TOO_EARLY',
  'WAIT_FOR_MORE_EVIDENCE',
] as const;

export const CULTURAL_MEMORY_MATCH_TYPES = [
  'CALLBACK',
  'CONTRADICTION',
  'REPEAT_PATTERN',
  'REVERSAL',
  'CULTURAL_REASSESSMENT',
  'RECEIPT_RETURN',
  'PREDICTION_UPDATE',
  'SELF_CORRECTION',
  'SAME_SYSTEM_NEW_EVENT',
] as const;

export const SIGNAL_DUPLICATE_CLASSES = [
  'SAME_EVENT',
  'SAME_STORY_DIFFERENT_SOURCE',
  'FOLLOW_UP',
  'NEW_DEVELOPMENT',
  'RELATED_BUT_DISTINCT',
  'UNRELATED',
] as const;

export const LIVE_WATCH_QUEUE_STATES = [
  'WATCHING',
  'ACCELERATING',
  'WAITING_FOR_SOURCE',
  'WAITING_FOR_DATA',
  'WAITING_FOR_EVENT',
  'WAITING_FOR_CONTEXT',
  'BRAND_ANGLE_FOUND',
  'EVIDENCE_SUFFICIENT',
  'READY_FOR_OPPORTUNITY',
  'DECLINING',
  'WINDOW_PASSED',
  'EXHAUSTED',
  'ARCHIVED',
] as const;

export const RAPID_RESPONSE_STATES = [
  'RAPID_RESPONSE_CANDIDATE',
  'RAPID_RESPONSE_RESEARCHING',
  'RAPID_RESPONSE_READY',
  'RAPID_RESPONSE_REJECTED',
] as const;

export const OPPORTUNITY_ORIGINS = [
  'LIVE_SIGNAL',
  'KNOWN_UPCOMING',
  'CULTURAL_WEATHER',
  'CALLBACK',
  'DATA_RELEASE',
  'EVERGREEN',
  'PERFORMANCE_LEARNING',
  'FOUNDER_IDEA',
  'WATCH_QUEUE',
  'RAPID_RESPONSE',
] as const;

export const SLATE_COMPOSITION_TYPES = ['PLANNED', 'CURRENT', 'FLEX', 'WATCH', 'RAPID_RESPONSE'] as const;

export const FORECAST_OUTCOME_RESULTS = [
  'ACCURATE',
  'DIRECTIONALLY_ACCURATE',
  'OVERPREDICTED',
  'UNDERPREDICTED',
  'FALSE_SIGNAL',
  'INSUFFICIENT_DATA',
] as const;

export const NOTIFICATION_CANDIDATE_TYPES = [
  'SIGNAL_ACCELERATING',
  'KNOWN_EVENT_APPROACHING',
  'BRAND_ANGLE_FOUND',
  'NEW_EVIDENCE',
  'CALLBACK_ACTIVATED',
  'PUBLISH_WINDOW_OPENING',
  'PUBLISH_WINDOW_CLOSING',
  'FORECAST_CHANGED',
] as const;

export const REFRESH_MODES = ['MANUAL_REFRESH', 'SCHEDULED_REFRESH', 'EVENT_TRIGGERED_WHERE_AVAILABLE'] as const;

export const CURRENT_VISUAL_EVIDENCE_CLASSES = [
  'CURRENT_PHOTOGRAPH',
  'ARCHIVAL_PHOTOGRAPH',
  'EVENT_PHOTOGRAPH',
  'PUBLIC_DOCUMENT',
  'SCREEN_CAPTURE',
  'DATA_VISUAL',
  'ADVERTISEMENT',
  'CAMPAIGN_ARTIFACT',
  'PRODUCT_IMAGE',
  'FASHION_IMAGE',
  'CULTURAL_ARTIFACT',
  'HISTORICAL_IMAGE',
  'PUBLICATION_COVER',
] as const;

export const INTELLIGENCE_FAILURE_STATES = [
  'FAIL_TREND_EQUALS_CONTENT',
  'FAIL_TREND_CHASING',
  'FAIL_FORCED_BRAND_RELEVANCE',
  'FAIL_NO_WHY_NOW',
  'FAIL_STALE_SIGNAL',
  'FAIL_WINDOW_PASSED',
  'FAIL_SATURATED_NO_ANGLE',
  'FAIL_FORECAST_AS_FACT',
  'FAIL_UNVERIFIED_AS_FACT',
  'FAIL_SINGLE_SOURCE_AS_CONSENSUS',
  'FAIL_SYNDICATION_AS_SOURCE_DIVERSITY',
  'FAIL_RANDOM_CULTURAL_REFERENCE',
  'FAIL_CULTURAL_REFERENCE_WITHOUT_CONTEXT',
  'FAIL_CURRENT_EVENT_HALLUCINATION',
  'FAIL_GENERATED_IMAGE_AS_FACTUAL_EVIDENCE',
  'FAIL_FAKE_CURRENT_PHOTO',
  'FAIL_FAKE_DATA',
  'FAIL_FAKE_RECEIPT',
  'FAIL_FAKE_CALLBACK',
  'FAIL_MEMORY_WITHOUT_EVIDENCE',
  'FAIL_TREND_ONLY_BRAND_INTEREST',
  'FAIL_NO_EDITORIAL_WHITESPACE',
  'FAIL_FILLER_FOR_CADENCE',
  'FAIL_ALL_CONTENT_CURRENT_EVENTS',
  'FAIL_NO_EVERGREEN_BALANCE',
  'FAIL_NO_FLEX_CAPACITY',
  'FAIL_FORECAST_OVERCONFIDENCE',
  'FAIL_AUTONOMOUS_PUBLISH',
  'FAIL_CHARACTER_MUTATION_FROM_TREND',
  'FAIL_CANON_MUTATION_FROM_PERFORMANCE',
] as const;

export const LIVE_CULTURAL_INTELLIGENCE_IMPLEMENTED = true as const;
export const LIVE_WORLD_SIGNAL_MODEL_IMPLEMENTED = true as const;
export const SIGNAL_SOURCE_ARCHITECTURE_IMPLEMENTED = true as const;
export const SIGNAL_DEDUPLICATION_IMPLEMENTED = true as const;
export const SIGNAL_CLUSTERING_IMPLEMENTED = true as const;
export const TREND_LIFECYCLE_IMPLEMENTED = true as const;
export const FORECAST_CONFIDENCE_IMPLEMENTED = true as const;
export const UPCOMING_CULTURAL_MOMENT_FORECAST_IMPLEMENTED = true as const;
export const TEMPORAL_RELEVANCE_IMPLEMENTED = true as const;
export const WHY_NOW_GATE_IMPLEMENTED = true as const;
export const CURRENT_INTELLIGENCE_PACKAGE_IMPLEMENTED = true as const;
export const SOURCE_FRESHNESS_IMPLEMENTED = true as const;
export const CURRENT_CLAIM_EVALUATION_IMPLEMENTED = true as const;
export const BRAND_SIGNAL_INTERPRETATION_IMPLEMENTED = true as const;
export const EDITORIAL_WHITESPACE_IMPLEMENTED = true as const;
export const CULTURAL_WEATHER_IMPLEMENTED = true as const;
export const WEEKLY_CULTURAL_FORECAST_IMPLEMENTED = true as const;
export const EDITORIAL_FLEX_CAPACITY_IMPLEMENTED = true as const;
export const WATCH_QUEUE_UPGRADED = true as const;
export const RAPID_RESPONSE_INTEGRATED = true as const;
export const CONTENT_OPPORTUNITY_LIVE_LINEAGE_IMPLEMENTED = true as const;
export const FORECAST_LEARNING_IMPLEMENTED = true as const;
export const STUDIO_WORLD_CLIENT_GENERALIZATION_IMPLEMENTED = true as const;
export const FAL_REQUESTS_FOR_FORECASTING = 0 as const;
export const AUTONOMOUS_PUBLISHING_ENABLED = false as const;
export const BRAND_CHARACTER_MUTATED = false as const;
export const BRAND_CANON_MUTATED = false as const;
export const PRODUCT_EXPRESSION_IMPLEMENTED = false as const;
export const WORLD_FORMATION_IMPLEMENTED = false as const;
