/**
 * P0.CJ.1 — Creative failure class registry (extensible).
 */

export const CREATIVE_JUDGMENT_FAILURE_CLASSES = [
  'TOO_SAFE',
  'TOO_GENERIC',
  'TOO_CLOSE',
  'WRONG_MECHANISM',
  'WEAK_MECHANISM',
  'BRAND_DRIFT',
  'COPY_DRIFT',
  'NDX_LEAK',
  'STYLE_ONLY_NO_IDEA',
  'IDEA_ONLY_NO_WORLD',
  'CHANNEL_DUPLICATION',
  'RESIZE_ONLY_THINKING',
  'WEAK_SEQUENCE',
  'WEAK_INTERJECTION',
  'OBVIOUS_FIRST_ANSWER',
  'UNSUPPORTED_CULTURAL_CLAIM',
  'PRODUCTION_IMPRACTICAL',
  'OVERCOMPLICATED',
  'UNDERDEVELOPED',
  'GOOD_IDEA_BAD_EXECUTION',
  'GOOD_EXECUTION_WEAK_IDEA',
  'NOT_BRAND',
  'NOT_NDXBOOK',
  'NEEDS_FOUNDER_JUDGMENT',
  'GENERIC_CONCEPT_REJECTION',
  'BRAND_GENERICITY',
] as const;

export type CreativeJudgmentFailureClass = (typeof CREATIVE_JUDGMENT_FAILURE_CLASSES)[number];

export const FOUNDER_JUDGMENT_LABELS = [
  'LOVE_IT',
  'PROMISING',
  'TOO_SAFE',
  'TOO_GENERIC',
  'TOO_CLOSE',
  'NOT_NDXBOOK',
  'NOT_BRAND',
  'WRONG_MECHANISM',
  'GOOD_IDEA_BAD_EXECUTION',
  'GOOD_EXECUTION_WEAK_IDEA',
  'NEEDS_MORE',
  'KILL_IT',
] as const;

export type FounderJudgmentLabel = (typeof FOUNDER_JUDGMENT_LABELS)[number];

export const REVISION_TARGETS_BY_FAILURE: Partial<Record<CreativeJudgmentFailureClass, string>> = {
  WRONG_MECHANISM: 'REBUILD_CONCEPTUAL_MECHANISM',
  WEAK_MECHANISM: 'REBUILD_CONCEPTUAL_MECHANISM',
  CHANNEL_DUPLICATION: 'REBUILD_CHANNEL_ROLE_MAP',
  RESIZE_ONLY_THINKING: 'REBUILD_CHANNEL_ROLE_MAP',
  COPY_DRIFT: 'REWRITE_COPY_ONLY',
  BRAND_DRIFT: 'RE_ANCHOR_BRAND_EXPRESSION_FINGERPRINT',
  NDX_LEAK: 'RE_ANCHOR_BRAND_EXPRESSION_FINGERPRINT',
  IDEA_ONLY_NO_WORLD: 'REBUILD_WORLD_EXPRESSION_SYSTEM',
  STYLE_ONLY_NO_IDEA: 'REBUILD_CONCEPTUAL_MECHANISM',
  TOO_GENERIC: 'REBUILD_CONCEPTUAL_MECHANISM',
  TOO_SAFE: 'PUSH_NON_OBVIOUS_ANSWER',
  TOO_CLOSE: 'REGENERATE_TERRITORY_ARCHITECTURE',
};
